- doc/sphinx/dev_guide/building_documentation.rst
Suggested new doc for https://github.com/tarantool/tarantool/issues/804, draft from Maria K.
Suggested location for the file: ../doc/sphinx/dev_guide
> Building Documentation topic for issue #804

- README.CentOS
- README.FreeBSD
- README.MacOSX
- README.md
- cmake/luajit.cmake
- debian/rules
- doc/sphinx/book/app/d_plugins.rst
- doc/sphinx/dev_guide/building_from_source.rst
- doc/sphinx/reference/tarantool.rst
- extra/rpm/tarantool.rpm.spec.in
- extra/travis/build_linux.sh
- extra/travis/build_osx.sh
see https://cmake.org/cmake/help/v3.4/variable/CMAKE_BUILD_TYPE.html
> instead of RelWithDebugInfo should be used RelWithDebInfo

- extra/tarantool.rb
Relates to https://github.com/tarantool/tarantool/issues/1497#issuecomment-220993800
> Correct misprint in tarantool.rb

- src/box/xlog.h
> Fix compilation on Alpine Linux

- extra/exports
- test/app-tap/module_api.c
- test/app-tap/module_api.result
- test/app-tap/module_api.test.lua
luaT_error is declared at module.h but not exported. Fixed #2291
> Export luaT_error symbol

- test/app/ipc.result
- test/app/ipc.test.lua
* delete background fibers
* error on multiple run of test
> Fix for IPC test

- extra/exports
- src/box/index.cc
- src/box/index.h
- test/app-tap/module_api.c
- test/app-tap/module_api.result
- test/app-tap/module_api.test.lua
> Export box_index_key_def() to public C API

- extra/dist/tarantool@.service.in
- src/CMakeLists.txt
- src/box/box.cc
- src/main.cc
- src/systemd.c
- src/systemd.h
Rewritten sd_notify -> `systemd_notify`/`snotify`/`vsnotify`, e.t.c.
Proposal -> add `cfg_gets` (values `loaded`, `before loaded`, `custom`) for systemd for user to send `READY` from Lua when it wants.
> Add sd_notify for systemd start checking

- extra/exports
were added in:
https://github.com/tarantool/luajit/commit/de97b9d52bbc42effeaf1180764053a912526873
https://github.com/tarantool/luajit/commit/cde968f91f28a4819e15443a5f32c89daddb4c15
https://github.com/tarantool/luajit/commit/2b8de8cfc6ae483d6ec16b7609bab64e37d6fc02
> Export more luaL_*

- .travis.mk
* Added new coveralls options to sync repo
* Pass travis job to coverage docker
> Added new coveralls options to sync repos with coveralls site (#3327)

- src/httpc.c
- test/app-tap/http_client.test.lua
I rewrite httpc_set_header for up limit to 8kb and add header checks when lua put header.
> Fix httpc header limit in 1024 bytes

- src/httpc.c
- src/httpc.h
- src/lua/httpc.c
I'm add option for set source interface in http client. Can you add this in upstream?
> Add option interface for set source interface in http client

- test/unit/CMakeLists.txt
Required in master and 2.1 branches
> fix unit test linking in static build

- src/lua/fio.lua
- test/app/fio.result
- test/app/fio.test.lua
> Fix fio.mktree error message

- Dockerfile.staticbuild
Add python-dev and pip to container to install test-run dependency
Install test-run dependency from requirements.txt of test-run subrepo
> Add python environment for test-run

- src/box/lua/feedback_daemon.lua
- test/box-tap/feedback_daemon.test.lua
Patch adds tarantool repository URL to feedback report
> Report repo URL

- src/box/memtx_engine.c
- src/box/tuple.c
- test/engine/engine.cfg
- test/engine/gh-5216-small_alloc_factor.lua
- test/engine/gh-5216-small_alloc_factor.result
- test/engine/gh-5216-small_alloc_factor.test.lua
Change small allocator behavior and add test for #5216 issue
Closes #5216
> Fix bug in small allocator in case of small slab_alloc_factor

- changelogs/unreleased/cmake-3.md
- changelogs/unreleased/drop-autotools.md
- changelogs/unreleased/drop-centos-6.md
- changelogs/unreleased/drop-debian-jessie.md
- changelogs/unreleased/drop-mac-os-10.13.md
- changelogs/unreleased/exclude-null.md
- changelogs/unreleased/fedora-33.md
- changelogs/unreleased/fix-freebsd-build.md
- changelogs/unreleased/github-actions.md
- changelogs/unreleased/jepsen-in-ci.md
- changelogs/unreleased/static-build-dont-refetch.md
- changelogs/unreleased/zstd-1.4.8.md
- doc/changelogs.md
- tools/gen-release-notes
See https://github.com/tarantool/tarantool/discussions/5634
> Store changelogs in the repository

- test/app-tap/suite.ini
- test/app/suite.ini
- test/box-py/suite.ini
- test/box-tap/suite.ini
- test/box/suite.ini
- test/engine/suite.ini
- test/engine_long/suite.ini
- test/replication-py/suite.ini
- test/replication/suite.ini
- test/sql-tap/suite.ini
- test/sql/suite.ini
- test/vinyl/suite.ini
- test/wal_off/suite.ini
- test/xlog/suite.ini
Found more flaky tests running testings with real parallel even for
tests in fragile lists.
> tests: add checksums for flaky tests

- .github/workflows/perf_cbench.yml
- .github/workflows/perf_linkbench_ssd.yml
- .github/workflows/perf_nosqlbench_hash.yml
- .github/workflows/perf_nosqlbench_tree.yml
- .github/workflows/perf_sysbench.yml
- .github/workflows/perf_tpcc.yml
- .github/workflows/perf_tpch.yml
- .github/workflows/perf_ycsb_hash.yml
- .github/workflows/perf_ycsb_tree.yml
Added cleanup routine for performance workflows before sources checkout
to avoid of fails on previously created files from inside docker with
any UID:GID.
> github-ci: add cleanup routine for perf

- changelogs/unreleased/gh-6045-missing-tuples-in-sk.md
- src/box/vy_lsm.h
- src/box/vy_tx.c
- test/vinyl/gh-6045-missing-tuples-after-sc-build.result
- test/vinyl/gh-6045-missing-tuples-after-sc-build.test.lua
> Don't annihilate DELETE+INSERT statements in write set if index is being created

- .github/workflows/ubuntu_20_10.yml
- debian/copyright
- tools/update_repo.sh
Add ubuntu-groovy workflow, which runs on push and pull-requests.
Part of: #5824
> github-ci: add ubuntu groovy (20.10) workflow

- .github/workflows/ubuntu_21_04.yml
- src/box/mp_error.cc
- tools/update_repo.sh
Add ubuntu-hirsute workflow, which runs on push and pull-requests.
Part of: #5825
> github-ci: add ubuntu hirsute (21.04) workflow

- changelogs/unreleased/gh-6095-mvcc-ephemeral-spaces.md
- src/box/memtx_tree.cc
- src/box/memtx_tx.h
- test/box/tx_man.result
- test/box/tx_man.test.lua
> txm: skip ephemeral spaces while positioning iterator

- changelogs/unreleased/gh-5892-segmentaion-fault-in-mvcc.md
- test/box/tx_man.result
- test/box/tx_man.test.lua
The problem was fixed in #6131, this commit just verifies that the
test case works fine.
Closes #5892
> txm: add a test that updates entire space concurrently

- test/unit/fiber_stack.c
- test/unit/fiber_stack.result
> unit/fiber: disable error logging in fiber_stack.test

- changelogs/unreleased/gh-6040-hash-select-not-tracked-by-mvcc.md
- changelogs/unreleased/gh-6132-mvcc-lost-tuple-after-conflict-exception.md
- changelogs/unreleased/gh-6206-repeat-read-violation.md
- changelogs/unreleased/gh-6234-mvcc-suspicious-tuning.md
- changelogs/unreleased/gh-6274-mvcc-crash-after-space-drop.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_engine.c
- src/box/memtx_hash.c
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- src/box/txn.h
- test/box/tx_man.result
- test/box/tx_man.test.lua
- test/box/tx_man_intervals.result
- test/box/tx_man_intervals.test.lua
> Alyapunov/gh 6206 all in one 2.8

- changelogs/unreleased/gh-6040-hash-select-not-tracked-by-mvcc.md
- changelogs/unreleased/gh-6132-mvcc-lost-tuple-after-conflict-exception.md
- changelogs/unreleased/gh-6206-repeat-read-violation.md
- changelogs/unreleased/gh-6234-mvcc-suspicious-tuning.md
- changelogs/unreleased/gh-6274-mvcc-crash-after-space-drop.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_engine.c
- src/box/memtx_hash.c
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- src/box/txn.h
- test/box/tx_man.result
- test/box/tx_man.test.lua
- test/box/tx_man_intervals.result
- test/box/tx_man_intervals.test.lua
> Alyapunov/gh 6206 all in one 2.7

- .gitlab.mk
> github-ci: hotfix for updating S3 in CI

- .github/workflows/source.yml
> github-ci: don't deploy tarballs per push

- .github/actions/pack_and_deploy/action.yml
- .github/workflows/centos_7_arm.yml
- .github/workflows/centos_8_arm.yml
- .github/workflows/debian_10_arm.yml
- .github/workflows/debian_11_arm.yml
- .github/workflows/fedora_33_arm.yml
- .github/workflows/fedora_34_arm.yml
- .github/workflows/ubuntu_20_04_arm.yml
- .github/workflows/ubuntu_20_10_arm.yml
- rpm/tarantool.spec
Support packaging for arm ~and publishing it to the S3~ (the automatic deployment is postponed).
Were added additional jobs in workflows for the arm.
Part of #6222
> Support packaging for arm64

- changelogs/2.10.0-beta1.md
- changelogs/unreleased/add-check-for-user-input-of-the-number-of-iproto-threads.md
- changelogs/unreleased/fix-undeleted-unix-socket-path-and-multiple-socket-closing.md
- changelogs/unreleased/gh-5447-downstream-lag.md
- changelogs/unreleased/gh-5979-recovery-yield.md
- changelogs/unreleased/gh-6045-missing-tuples-in-sk.md
- changelogs/unreleased/gh-6165-multibyte-fselect.md
- changelogs/unreleased/luarocks-disable-force-config.md
Few changelog entries were fixed to resolve syntax errors.
> Generate changelog for 2.10.0-beta1

- changelogs/unreleased/gh-6332-crash-on-replace-in-schema.md
- src/box/alter.cc
- src/box/tuple.h
- test/box/gh-6332-on-replace-schema.result
- test/box/gh-6332-on-replace-schema.test.lua
> alter: fix insertion of malformed tuples into _schema system space

- test/box/gh-5998-one-tx-for-ddl-errinj.result
- test/box/gh-5998-one-tx-for-ddl-errinj.test.lua
Subj. Ran test ~100 times on local machine, no hangs anymore.
Closes #6354
> test: fix box/gh-5998-one-tx-for-ddl-errinj.test.lua

- src/box/func.c
Make it possible to set a temporary directory where
the module will be copied before load.
Title: Justify module (re-)loading semantics
It is now possible to set the directory where temporary
copies of modules to be loaded will be created.
It is done by setting `$(TMPDIR)` variable. It
will be `/tmp` if the variable was not set.
Closes #6412
(cherry picked from commit 366b2de7cb244fcafeb6d3bc57ed444169b2c433)
#	src/box/call.c
#	test/box/func_reload.result
> Allow to set directory for copying DSO before load

- changelogs/unreleased/gh-5389-fix-assertion-during-grant.md
- src/box/alter.cc
- src/box/schema_def.c
- src/box/schema_def.h
- test/box/access.result
- test/box/access.test.lua
> access: fix diag raised when privileges are granted not from admin

- src/lib/core/coio.c
- test/unit/coio.cc
- test/unit/coio.result
> coio: check inet_pton result

- test/replication-luatest/suite.ini
The tests in here use unix sockets. Should work in parallel fine
and not interfere.
> test: make replication-luatest parallel

- src/box/box.cc
- src/box/memtx_rtree.c
- src/box/sql/func.c
- src/box/sql/mem.c
- src/box/sql/select.c
- src/lib/core/tt_static.h
About printf format of `uint64_t`/`int64_t` in various places and a couple of fixes in SQL code.
> Several coverity fixes

- CMakeLists.txt
- cmake/FindOptionalPackage.cmake
- cmake/atomic.cmake
- cmake/module.cmake
- cmake/os.cmake
- cmake/profile.cmake
- cmake/utils.cmake
- extra/CMakeLists.txt
- perf/CMakeLists.txt
- src/CMakeLists.txt
- src/box/CMakeLists.txt
- src/lib/uri/CMakeLists.txt
- test/box-tap/CMakeLists.txt
- test/unit/CMakeLists.txt
Use of PROJECT_ prefix gives ability to build the project as a
submodule of other projects.
> cmake: align folders dependencies

- static-build/CMakeLists.txt
Needed for [Tarantool EE](https://github.com/tarantool/tarantool-ee).
> Make lookup of statically built binary more robust

- src/box/CMakeLists.txt
- src/box/audit.c
- src/box/audit.h
- src/box/box.cc
- src/box/lua/load_cfg.lua
- src/trivia/config.h.cmake
- test/app-tap/init_script.result
- test/box/admin.result
- test/box/cfg.result
- test/box/cfg.test.lua
- test/box/errinj.result
- test/box/errinj.test.lua
- test/box/net.box_watcher.result
- test/box/net.box_watcher.test.lua
Needed for [Tarantool EE](https://github.com/tarantool/tarantool-ee).
> Audit log stub

- .gitmodules
- CMakeLists.txt
- cmake/FindZZIP.cmake
- src/CMakeLists.txt
- src/lua/init.c
- src/trivia/config.h.cmake
Needed for [Tarantool EE](https://github.com/tarantool/tarantool-ee). Off by default.
> cmake: add option to embed luazip

- changelogs/1.10.12.md
- changelogs/unreleased/debian-remove-binutils-dependency.md
- changelogs/unreleased/drop-ubuntu-trusty.md
- changelogs/unreleased/gh-4617-fix-lua-stack-usage-while-results-encoding.md
- changelogs/unreleased/gh-4669-applier-reconfig-reconnect.md
- changelogs/unreleased/gh-6092-invalid-listen-address-make-tarantool-blind.md
- changelogs/unreleased/gh-6224-lj-dualnum-luajit-gdb.md
- changelogs/unreleased/gh-6227-fix-bytecode-register-allocator.md
- changelogs/unreleased/gh-6248-fix-lua-api-misuse-while-results-encoding.md
- changelogs/unreleased/gh-6266-fix-crash-in-lua-triggers.md
- changelogs/unreleased/gh-6393-bump-debian-compat.md
- changelogs/unreleased/gh-6480-crash-if-box-cfg-listen-is-woken-up.md
- changelogs/unreleased/gh-6520-fix-box-session-push-crash.md
- changelogs/unreleased/gh-6686-build-with-glibc-2-34.md
- changelogs/unreleased/luajit-fix-frame-traversal-for-__gc-handler-frames.md
Drop entries from changelog/unreleased/* as well.
> Generate changelog for 1.10.12

- .github/workflows/ubuntu_21_10.yml
Add ubuntu-impish workflow, which runs on push and pull-requests.
Closes #6566
> github-ci: add ubuntu implish (21.10) workflow for amd64

- .github/workflows/fedora_35.yml
- .github/workflows/fedora_35_aarch64.yml
- changelogs/unreleased/gh-6692-fedora-35-ci.md
Add GitHub Actions workflows for Fedora 35
Closes: #6692
> github-ci: add fedora-35 workflows

- src/lib/core/backtrace.cc
`get_proc_name` code is clogged with procedure cache management logic:
refactor this logic out.
Needed for #4002
NO_DOC:refactoring
NO_CHANGELOG:refactoring
> core: refactor `get_proc_name`

- .github/actions/environment/action.yml
- .github/workflows/coverage.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/freebsd-12.yml
- .github/workflows/freebsd-13.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/osx_11_aarch64.yml
- .github/workflows/osx_11_aarch64_debug.yml
- .travis.mk
Closes tarantool/tarantool-qa#156
> ci: improve artifact stuff in workflows

- changelogs/unreleased/fiber-custom-stack-leak.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- test/unit/fiber.cc
- test/unit/fiber.result
- test/unit/fiber_stack.c
- test/unit/fiber_stack.result
The patchset fixes some issues in the fiber library. See commit messages.
> Fiber library fixes

- changelogs/unreleased/gh-6150-memtx-mvcc-memory-monitoring.md
- extra/exports
- src/box/lua/schema.lua
- src/box/lua/stat.c
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box-luatest/gh_6635_garbage_of_last_prep_txn_test.lua
* Implement Memtx MVCC memory monitoring.
* Fix a problem when garbage of last prepared txn could not be deleted.
Closes #6635 
Closes #6150
> Memtx MVCC memory monitoring

- src/lib/core/CMakeLists.txt
- src/lib/core/prbuf.c
- src/lib/core/prbuf.h
- test/unit/CMakeLists.txt
- test/unit/prbuf.c
- test/unit/prbuf.result
Subj. First iteration of the buffer implementation.
> core: partitioned ring buffer

- extra/exports
- src/lua/buffer.lua
- test/app-luatest/prbuf_test.lua
> lua: introduce interface for prbuf

- changelogs/unreleased/gh-6773-datetime-sql-builtin-functions.md
- src/box/sql/func.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- test/sql-luatest/datetime_test.lua
- test/unit/datetime.c
This patch-set introduces SQL built-in function NOW() and DATE_PART().
> DATETIME SQL built-in functions

- src/lib/core/datetime.c
- test/fuzz/datetime_parse_full_fuzzer.c
- test/fuzz/datetime_strptime_fuzzer.c
- test/sql-luatest/datetime_test.lua
Due to full-ci a few problems were found.
> sql: fixes for new built-in functions

- changelogs/unreleased/gh-6773-arithmetic-operands.md
- changelogs/unreleased/gh-6773-introduce-field-type-interval-to-sql.md
- extra/mkkeywordhash.c
- src/box/bind.c
- src/box/bind.h
- src/box/lua/execute.c
- src/box/sql.c
- src/box/sql/func.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/box/sql/parse.y
- src/box/sql/sqlInt.h
- src/box/sql/vdbe.c
- src/box/sql/vdbeapi.c
- test/sql-luatest/CMakeLists.txt
- test/sql-luatest/datetime_test.lua
- test/sql-luatest/gh_6668_problems_with_map_array_test.lua
- test/sql-luatest/gh_6773_arithmetic_operands_test.lua
- test/sql-luatest/interval_test.lua
- test/sql-luatest/sql_interval.c
- test/sql-tap/array.test.lua
- test/sql-tap/map.test.lua
- test/sql-tap/metatypes.test.lua
- test/sql-tap/sql-errors.test.lua
- test/sql-tap/tkt-a8a0d2996a.test.lua
- test/sql-tap/uuid.test.lua
- test/sql/boolean.result
- test/sql/types.result
This patch-set introduces basic INTERVAL support in SQL.
> Introduce interval to SQL

- changelogs/1.10.13.md
Generate change log for new release in 1.10 release series.
> Generate changelog for 1.10.13

- src/CMakeLists.txt
- src/box/flightrec.h
- src/box/iproto.cc
- src/lua/buffer.lua
- test/app-luatest/prbuf_test.lua
Subj. Follow-up to 247515e98bf5739d1f4f3b7ace7bc41bc5f191f0
> box/iproto: introduce reqstart to iproto_msg

- changelogs/unreleased/fix-string-dequoting.md
- changelogs/unreleased/gh-4763-introduce-map-to-sql.md
- changelogs/unreleased/gh-6251-operator-brackets.md
- changelogs/unreleased/gh-6751-olson-timezones.md
- changelogs/unreleased/gh-6793-datetime-set-with-tzoffset.md
- changelogs/unreleased/gh-7076-tz-attributes.md
- changelogs/unreleased/gh-7089-applier-vclock-race.md
- changelogs/unreleased/gh-7113-rev-tree-iters-gap-tracking.md
- changelogs/unreleased/gh-7129-improve-check-for-dangerous-select-calls.md
- changelogs/unreleased/gh-7132-sql-insertion-crash.md
Related to https://github.com/tarantool/doc/issues/2868
> doc: proofread changelogs/unreleased for 2.10.0

- src/box/lua/net_box.lua
- test/box-luatest/net_box_test.lua
Subj. See commit message for details.
> net.box: fix box.error() usage

- src/box/errcode.h
- src/box/memtx_hash.cc
- src/box/memtx_space.c
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/session_settings.c
- src/box/space.c
- src/box/space_upgrade.h
- src/box/vinyl.c
- test/box-py/call.result
- test/box/alter.result
- test/box/alter_limits.result
- test/box/before_replace.result
- test/box/session_settings.result
- test/box/tree_pk_multipart.result
- test/box/update.result
- test/sql-tap/intpkey.test.lua
- test/vinyl/on_replace.result
- test/vinyl/quota.result
- test/vinyl/savepoint.result
Subj. For details see commit messages. Also one patch fixes ER_CANT_UPDATE_PRIMARY_KEY error.
> space_upgrade: prerequisites for PK modification check

- tools/gdb.sh
Regular expression now works on versions: alpha, beta, rc and so on.
> tools: fix gdb.sh revision regex

- src/lua/help_en_US.lua
I'm not sure that we need to highlight this change in changelog. But if reviewers are not agree, I'll add a changelog entry.
> tutorial: use https links

- src/box/gc.c
- src/box/recovery.cc
- src/lib/core/coio.c
- src/lib/core/fiber.c
- test/unit/coio.cc
- test/unit/coio.result
- test/unit/fiber.cc
- test/unit/fiber.result
See commit messages.
Part of #7166
> Get rid of fiber_set_cancellable in 4 more places

- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/iproto_constants.c
- src/box/iproto_constants.h
- src/box/lua/init.c
- src/box/lua/load_cfg.lua
- src/box/lua/xlog.c
- src/box/space.c
- src/box/space.h
- src/box/space_cache.c
- src/box/txn.c
- src/box/vinyl.c
- src/box/wal_ext.h
- src/box/xrow.c
- src/box/xrow.h
- src/trivia/config.h.cmake
- test/box-luatest/wal_ext_test.lua
- test/unit/xrow.cc
- test/unit/xrow.result
These patches are required to introduce extended WAL format entries in Tarantool EE.
> Prerequisites for Extended WAL Format

- test/box-luatest/gh_6634_different_log_on_tuple_new_and_free_test.lua
Subj, see commit message. Another option is simply remove this test, but as far as I remember @alyapunov said that we should try to test every change.
> Fix gh_6634 test case

- perf/tuple.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/tuple.c
- src/box/tuple.h
> tuple: refactor flags

- src/lib/bitset/bitset.c
> Fix compilation on macOS 12

- .gitmodules
Part of https://github.com/tarantool/security/issues/12
NO_DOC=bugfix
NO_TEST=bugfix
> rocks: switch luarocks module to 3.1.3 branch

- changelogs/unreleased/qsort-fix.md
- third_party/qsort_arg.c
- third_party/qsort_arg_mt.c
This is a backport of commit https://github.com/postgres/postgres/commit/9d6077abf9d6efd992a59f05ef5aba981ea32096.
> Fix a low-probability crash in our qsort implementation

- .github/workflows/submodule_update.yml
- Run the workflow in tarantool/tarantool repo only
- Fix the condition to compose PR title prefix
- Add a small description for created PRs
> ci: hotfixes for `submodule_update.yml` workflow

- .luacheckrc
- src/box/lua/console.lua
> lua: fix luacheck warnings in src/box/console.lua

- .github/workflows/publish-module-api-doc.yaml
- Doxyfile
- changelogs/unreleased/publish-doxygen-doc.md
- doc/index.html
Generated docs: https://bronevichok.ru/static/module_api/
> Publish module API documentation generated with doxygen

- .github/workflows/publish-module-api-doc.yaml
> ci: fix version in GH action used for publishing

- changelogs/unreleased/gh-4450-logger-sigsegv.md
- src/lib/core/say.c
- src/main.cc
- test/app-tap/gh-4450-log-rotate-exit.test.lua
- test/app-tap/suite.ini
Guys, take a look please, once time permit
- implemented a test
- fixed typos
Fixes #4450
> Gh 4450 logger sigsegv 3

- .github/workflows/publish-module-api-doc.yaml
- doc/index.html
> ci: fix conditions in publishing workflow

- src/lib/core/say.c
- src/lib/core/say.h
Subj. Required for [flight recorder issue](https://github.com/tarantool/tarantool-ee/issues/201)
> say: introduce internal on_log_level routines

- changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md
- changelogs/unreleased/gh-4450-logger-sigsegv.md
- changelogs/unreleased/gh-7473-system-fibers.md
- changelogs/unreleased/gh-7605-fix-qsort.md
- changelogs/unreleased/gh-7614-fix-nullable-from-format.md
- changelogs/unreleased/ghs-5-fix-auth-check-on-truncate.md
Fix wording, punctuation, and formatting.
Resolves https://github.com/tarantool/doc/issues/3120
> doc: proofread 2.10.2 changelogs

- test/app-tap/module_api.c
This commit pursues several goals:
* Eliminate unused parameter/variable warnings at building module_api.c
in non-debug configuration. The problem was introduced in commit
5c1bc3dacbe6 ("decimal: add the library into the module API").
* Eliminate a need to check newly added tests in two build
configurations (Debug and RelWithDebInfo) and don't forget to add
`(void)x;` statements in addition to a test condition check.
* Fail the testing if conditions required by the
app-tap/module_api.test.lua test are not met -- not only in the Debug
build, but also in RelWithDebInfo.
Fixes #7625
> test: always perform assertions in module API test

- README.md
> readme: add OSS Fuzz badge

- src/box/lua/load_cfg.lua
Feedback daemon is reconfiguread as many times as number of options changed during single box.cfg call which is suboptimal. Add proper support for modules which configure all its options in a single call.
Part of https://github.com/tarantool/tarantool-ee/issues/200
> box: support module as unit of reconfiguring

- src/box/vinyl.c
- src/box/vy_read_iterator.c
- src/box/vy_read_iterator.h
- test/engine-luatest/pagination_test.lua
Pagination for vinyl works exactly like in memtx. See the commit log for implementation details.
Closes #7634
> vinyl: implement iterator pagination

- test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua
- test/app-luatest/gh_7288_console_helper.lua
Such style is not recommented and going to be banned.
Closes #7715
NO_TEST=test refactoring
NO_DOC=test refactoring
NO_CHANGELOG= test refactoring
> test: don't call box.cfg() from test instance in gh-7288

- changelogs/unreleased/gh-7645-ck-and-fk-constraints-on-the-same-field.md
- src/box/tuple_constraint_def.c
- test/engine-luatest/gh_7645_ck_fk_constraints_test.lua
Fix a simple typo that caused the problem.
Closes #7645
NO_DOC=bugfix
> box: fix creation of CK and FK constraints on the same field

- .github/workflows/jepsen-cluster-txm.yml
- .github/workflows/jepsen-cluster.yml
- .github/workflows/jepsen-single-instance-txm.yml
- .github/workflows/jepsen-single-instance.yml
Fixes tarantool/tarantool-qa#282
Testing:
- https://github.com/tarantool/tarantool/actions/runs/3361121588/jobs/5571128792
- https://github.com/tarantool/tarantool/actions/runs/3361122657/jobs/5571130954
> ci: add recursive checkout to jepsen workflows

- changelogs/unreleased/gh-7860-syslog-json.md
- src/box/box.cc
- src/lib/core/say.c
- test/app-tap/logger.test.lua
- test/box-luatest/gh_7860_syslog_json_test.lua
- test/box-tap/cfg.test.lua
> say: enable json log format with syslog

- src/box/relay.cc
When replica heartbeat is read while another heartbeat is en route, it's delivery is delayed for a full replication_timeout.
This can be seen in replication/qsync_basic.test.lua occasional hangs on these lines:
```lua
--
-- gh-5100: replica should send ACKs for sync transactions after
-- WAL write immediately, not waiting for replication timeout or
-- a CONFIRM.
--
-- on replica:
box.cfg{replication_timeout = 1000, replication_synchro_timeout = 1000}
test_run:switch('default')
box.cfg{replication_timeout = 1000, replication_synchro_timeout = 1000}
<factored-out>
-- Now commit something sync. It should return immediately even
-- though the replication timeout is huge.
box.space.sync:replace{4}
```
Change that so that a pending heartbeat is sent immediately upon status message return from …
> relay: fix loss of one of the two consecutive heartbeats

- changelogs/unreleased/gh-4450-fix-crash-on-logrotate-and-exit.md
- changelogs/unreleased/gh-5183-fix-index-field-missing.md
- changelogs/unreleased/gh-5310-fix-cursor-invalidation.md
- changelogs/unreleased/gh-5526-no-error-on-too-many-indexes.md
- changelogs/unreleased/gh-5678-assertion-in-JOIN-using-unsupported-index.md
- changelogs/unreleased/gh-5940-strengthen-field-type-check.md
- changelogs/unreleased/gh-5976-fix-assertion-during-indexed-by.md
- changelogs/unreleased/gh-6989-type-of-NULLIF.md
- changelogs/unreleased/gh-7230-luajit-fixes.md
- changelogs/unreleased/gh-7458-fix-lj-stack-command-on-Python2.md
- changelogs/unreleased/gh-7583-txn-stat.md
- changelogs/unreleased/gh-7645-ck-and-fk-constraints-on-the-same-field.md
- changelogs/unreleased/gh-7652-complex-fkey-new-field-name.md
- changelogs/unreleased/gh-7698-datetime-subtraction-with-tz.md
- changelogs/unreleased/gh-7700-interval-arithmetic-across-dst.md
- changelogs/unreleased/gh-7712-loss-of-commited-tuple-in-secondary-index.md
- changelogs/unreleased/gh-7757-memtx-space-drop-triggers-assertion.md
- changelogs/unreleased/gh-7761-memtx-sk-index-uniqueness-violation.md
- changelogs/unreleased/gh-7797-untrusted-input-validation.md
- changelogs/unreleased/gh-7800-recover-snap-without-spaces.md
- changelogs/unreleased/gh-7808-fix-abs-file-paths-in-diag-and-debug-info.md
- changelogs/unreleased/gh-7818-msgpack-0xc1-fix.md
- changelogs/unreleased/gh-7822-fix-_vfunc-format.md
- changelogs/unreleased/gh-7888-store-compiler-id-and-version-in-compiler-info.md
- changelogs/unreleased/gh-7917-log-row-on-recovery-error.md
- changelogs/unreleased/ghs-14-revoke-access-to-LUA-from-public.md
- changelogs/unreleased/ghs-17-fix-decimal-unpack-overflow.md
- changelogs/unreleased/ghs-18-mp-check-overflow-fix.md
- changelogs/unreleased/ghs_16_user_enumeration.md
Fix wording, punctuation, and formatting.
> doc: proofread 2.10.4 CE changelog

- src/lib/core/crash.c
- src/main.cc
- test/box-py/args.result
NO_DOC=fix protocol in link
NO_TEST=fix protocol in link
NO_CHANGELOG=fix protocol in link
> lua: use https protocol in a crash report message

- src/box/iproto.cc
- src/box/iproto_constants.c
- src/box/iproto_constants.h
- src/box/iproto_features.c
- src/box/iproto_features.h
- src/box/lua/misc.cc
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- src/box/lua/schema.lua
- src/box/xrow.c
- src/box/xrow.h
- test/box-luatest/pagination_netbox_test.lua
- test/box-py/iproto.result
- test/box-py/iproto.test.py
- test/box/access.result
- test/box/access.test.lua
- test/box/net.box_incorrect_iterator_gh-841.result
- test/box/net.box_incorrect_iterator_gh-841.test.lua
- test/box/net.box_iproto_id.result
- test/unit/xrow.cc
The patchset adds pagination options to IPROTO and net_box. Documentation will appear with the next patchset.
Closes https://github.com/tarantool/tarantool/issues/7637
> Pagination netbox

- test/replication-luatest/gh_7253_election_long_wal_write_test.lua
It appears that we have to wait for commit completion on master before start waiting for it on replica.
> flaky: fix flakiness of the gh_7253 test

- changelogs/unreleased/gh-7947-tuple-missing-after-rollback-delete.md
- src/box/vinyl.c
- src/box/vy_cache.c
- src/box/vy_cache.h
- src/box/vy_read_iterator.c
- src/box/vy_read_iterator.h
- test/engine-luatest/pagination_test.lua
- test/unit/vy_iterators_helper.c
- test/vinyl-luatest/gh_7947_tuple_missing_after_rollback_delete_test.lua
> vinyl: fix bugs in cache that can lead to existing tuples missing in select results

- changelogs/unreleased/pagination.md
- extra/exports
- src/box/index.cc
- src/box/index.h
- src/box/lua/index.c
- src/box/lua/misc.cc
- src/box/lua/misc.h
- src/box/lua/schema.lua
- src/box/memtx_engine.h
- src/box/tuple.c
- src/box/tuple.h
- test/engine-luatest/pagination_test.lua
- Introduce pagination to pairs
- Add changelog and doc request for pagination
Closes #7638
Closes #7639
> Pagination in pairs

- changelogs/unreleased/gh-7898-msgpack-object-indexation.md
- src/lua/msgpack.c
- test/app-luatest/msgpack_test.lua
> msgpack: add `__index` metamethod and `get` method to `msgpack.object`

- .github/workflows/codeql.yml
This patch will enable the CodeQL analyzer for PRs and commits into the master branch.
NO_CHGANGELOG=no code changes
> Add CodeQL analyzer for PRs to master

- changelogs/unreleased/gh-7895-export-session-id-to-c-api.md
- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/lua/session.c
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
> box: export current session's identifier to C API

- test/box-luatest/gh_7743_term_initial_cfg_snap_test.lua
The test sends SIGTERM to the process while it is writing a snapshot. Using `g.server.process:kill('TERM')`.
On a next line the test was doing `g.server:stop()` which also sends SIGTERM. Apparently, the second SIGTERM sometimes killed the server immediately.
It usually happened inside fiber_free(). Sometimes right after the file tt_exit_file.txt.inprogress was created but before it was renamed to tt_exit_file.txt.
The reason is in signal_free() being called quite early. After that any signal becomes fatal and is not caught by the handlers.
The patch also increases on-shutdown timeout not to depend on it for certain. Although it shouldn't be a problem right now.
Follow-up #7743
Closes https://github.com/tarantool/tarantool-qa/issues/297
NO_DOC=test
> test: fix flaky 'sigterm during box.cfg' test

- src/CMakeLists.txt
- src/lua/init.c
- src/trivia/config.h.cmake
- src/trivia/util.h
Part of https://github.com/tarantool/tarantool-ee/issues/158
> Compress Lua module - CE part

- changelogs/unreleased/gh-7897-sending-arbitrary-iproto-packets.md
- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/errcode.h
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/init.c
- src/box/lua/init.h
- src/box/lua/iproto.c
- src/box/lua/iproto.h
- src/lib/core/util.c
- src/lua/msgpack.c
- src/lua/msgpack.h
- src/main.cc
- src/trivia/util.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/box-luatest/sending_arbitrary_iproto_packets_test.lua
- test/box/error.result
- test/unit/lua_msgpack.c
- test/unit/string.c
> box: sending arbitrary IPROTO packets

- .github/workflows/integration.yml
Integration testing workflow for CRUD and DDL modules.
Resolves #6619 
Resolves #6620
Depends on https://github.com/tarantool/ddl/pull/103
Depends on https://github.com/tarantool/crud/pull/335
> ci: integration testing workflow for crud and ddl modules

- src/lib/uri/uri.c
Use an array to convert a hex digit into a number instead of `isdigit()` and `tolower()`.
Eliminate the `isxdigit()` check by reusing the same array lookup.
Results on perf/lua/uri_escape_unescape.lua show 2.4x average boost (from 2.1x to 2.5x).
Noise in the results: 4% in baseline, 11% in the new version (the maximal difference between min and max results). The average linear/standard deviation is within 3%. 
Measured on i7-10510U, acpi-cpufreq driver (no intel_pstate), no TurboBoost, userspace governor, 1.80GHz, HyperThreading. The workload is bound to a single logical core using `taskset`.
> lua: speedup uri.unescape()

- changelogs/unreleased/gh-7901-iproto-request-handlers-overriding.md
- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/iproto.cc
- src/box/iproto.h
- src/box/iproto_constants.h
- src/box/lua/iproto.c
- src/box/xrow.h
- src/lua/msgpack.c
- src/lua/msgpack.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/box-luatest/iproto_request_handlers_overriding_test.lua
- test/unit/lua_msgpack.c
> box: overriding IPROTO request handlers

- changelogs/unreleased/gh-7202-options-in-atomic.md
- changelogs/unreleased/gh-7945-assert-in-mvcc.md
- changelogs/unreleased/gh-8122-excess-conflict-in-mvcc.md
- extra/exports
- src/box/lua/schema.lua
- src/box/memtx_engine.cc
- src/box/memtx_space.c
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box-luatest/gh_7202_options_in_atomic_test.lua
- test/box-luatest/gh_7945_mvcc_assert_in_mvcc_test.lua
- test/box-luatest/gh_8122_excess_conflict_secondary_test.lua
A series of refactoring commits in MVCC. A couple of bugs were fixed and options in box.atomic are introduced.
Closes #7945 and #7202.
> Gh 7202 mvcc refactoring

- changelogs/unreleased/add-fiber_set_ctx.md
- changelogs/unreleased/decimal-lua-module-api.md
- changelogs/unreleased/drop-opensuse-ci-cd.md
- changelogs/unreleased/gh-3012-yaml-prettier-multiline-output
- changelogs/unreleased/gh-3012-yaml-prettier-multiline-output.md
- changelogs/unreleased/gh-3159-recovery-triggers.md
- changelogs/unreleased/gh-3211-per-module-log_level.md
- changelogs/unreleased/gh-3682-uri-encode-decode.md
- changelogs/unreleased/gh-4726-execute-field-in-box.md
- changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md
- changelogs/unreleased/gh-5665-get-rid-of-fiber_gc.md
- changelogs/unreleased/gh-5869-remove-fiber-top-cpu_misses.md
- changelogs/unreleased/gh-6011-follow-env-vars-on-log-cfg.md
- changelogs/unreleased/gh-6085-log-and-limit-iteration.md
- changelogs/unreleased/gh-6126-retry-join-automatically.md
- changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md
- changelogs/unreleased/gh-6251-operator-brackets.md
- changelogs/unreleased/gh-6506-allow-spurious-wakeups-in-wal_write.md
- changelogs/unreleased/gh-6530-netbox-opts-check.md
- changelogs/unreleased/gh-6572-nan-is-not-null.md
- changelogs/unreleased/gh-6575-assertion-in-modulo.md
- changelogs/unreleased/gh-6650-round-with-big-precision.md
- changelogs/unreleased/gh-6793-datetime-set-with-tzoffset.md
- changelogs/unreleased/gh-6832-httpc-params-encoding.md
- changelogs/unreleased/gh-6832-uri-values.md
- changelogs/unreleased/gh-6833-decode-body-http-response.md
- changelogs/unreleased/gh-6833-encode-body-http-request.md
Fix grammar, wording, and formatting
Resolves https://github.com/tarantool/doc/issues/3287
> doc: proofread changelogs 2.11-rc part 1

- src/box/lua/console.c
- src/lua/print.lua
- test/app-luatest/gh_8136_fix_print_wrapper_not_handling_errors_thrown_from_print_test.lua
> console: make prompt bookkeeping thread-safe

- src/box/iproto.cc
The event is used by appliers as a better alternative to IPROTO_VOTE. Besides, event subscribers receive exactly the same payload as the ones sending IPROTO_VOTE. So there's no need to guard against subscription to this particular event as long as IPROTO_VOTE isn't guarded.
Follow-up #5272
NO_DOC=no user-visible changes
NO_CHANGELOG=no user-visible changes
NO_TEST=tested by ee
> security: do not check subscriptions on "internal.ballot" event

- src/tarantool-gdb.py
gdb: add rlist pretty-printer and 'tt-list' command
1. Add pretty-printer for 'rlist' type
Script holds table of possible rlists in tarantool. It recognizes
automatically actual type of entries and either expression refers to a
single items or to entire list. Then either single entry is displayed
(along with its index in the list) or the entire list (entry-by-entry).
2. Add command 'tt-list' that use the mentioned pretty-printer and
provide additional functionality, namely:
- walking over the list (both directions)
- filter entries with predicate
- allow to explicitly specify list head and actual entry type
if automatic recognition doesn't work
See 'help tt-list' for details.
Close #7731
> gdb: add command to handle rlists

- changelogs/unreleased/gh-8121-memtx-mvcc-replication-stream.md
- src/box/applier.cc
- test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua
> applier: fix isolation level of applied transactions

- changelogs/unreleased/gh-7972-func-def-wrong-options-err-msg.md
- src/box/alter.cc
- src/box/errcode.h
- test/box-luatest/gh_7972_func_def_err_conditions_test.lua
- test/box/error.result
> box: fix function definition wrong options error message

- changelogs/unreleased/gh-5809-bitset-index-len-crash.md
- src/lib/bitset/index.h
- test/box-luatest/gh_5809_bitset_index_len_crash_test.lua
- test/unit/bitset_index.c
> bitset: fix index size calculation

- test/app-luatest/digest_crc32_recording_test.lua
- test/app-luatest/gh_4963_fio_pread_err_msg_test.lua
- test/app-luatest/gh_5747_crash_multiple_args_test.lua
- test/app-luatest/http_client_test.lua
- test/app-luatest/msgpack_test.lua
- test/box-luatest/gh_6647_yield_gc_hook_test.lua
- test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
- test/box-luatest/gh_7014_session_disconnect_peer_test.lua
- test/replication-luatest/gh_6966_readonly_bootstrap_test.lua
- test/replication-luatest/quorum_misc_test.lua
- test/vinyl-luatest/gh_6778_recovery_crash_test.lua
- test/vinyl-luatest/gh_7947_tuple_missing_after_rollback_delete_test.lua
- test/vinyl-luatest/update_optimize_test.lua
Just a regular cherry-pick of #8202 via a pull request to verify changes.
> [1.10] test: fix autorequire luatest module

- .github/workflows/osx_debug.yml
- .github/workflows/osx_release.yml
- .github/workflows/osx_release_lto.yml
- .test.mk
Just a regular backport of #8294 via a pull request to verify changes.
> [1.10] ci: add more testing for macOS 12 and 13 

- src/tarantool-gdb.py
> gdb: support unicode in MP_STR type of MsgPack

- src/tarantool-gdb.py
> gdb: put warnings about missed rlist types into 'debug' log level

- changelogs/unreleased/clang-15.md
- changelogs/unreleased/drop-opensuse-ci-cd.md
- changelogs/unreleased/gh-7458-fix-lj-stack-command-on-Python2.md
- changelogs/unreleased/gh-7955-improve-logging-of-tables.md
- changelogs/unreleased/gh-8269-log-syslog-incorrect-facility.md
Proofread changelogs for 1.10.15
Resolves https://github.com/tarantool/doc/issues/3311
> doc: proofread 1.10.15 changelogs

- src/box/lua/schema.lua
Needed for tarantool/tarantool-ee#211
See also tarantool/tarantool-ee#394
> box: add `check_select_safety` to `box.internal`

- changelogs/unreleased/ghs-73-unsafe-extensions-decoding.md
- extra/exports
- src/box/bind.c
- src/box/mp_error.cc
- src/box/mp_error.h
- src/box/msgpack.c
- src/box/sql/mem.c
- src/lib/core/decimal.c
- src/lib/core/mp_interval.c
- src/lib/core/mp_interval.h
- src/lua/msgpack.c
- src/lua/msgpackffi.lua
- src/lua/tnt_datetime.c
- test/box-luatest/gh_6857_tuple_ext_validation_test.lua
- test/unit/mp_error.cc
> msgpack: fix unsafe extension decoding

- changelogs/unreleased/gh-8457-downgrade-handle-takes-raw-args.md
- src/box/lua/upgrade.lua
- test/box-luatest/downgrade_test.lua
Disable to downgrade in this case.
Closes #8457
> downgrade: handle function option `takes_raw_args`

- src/box/lua/call.c
- src/box/port.c
- src/box/port.h
- src/box/sql/delete.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/box/sql/sqlInt.h
- src/box/sql/trigger.c
- src/box/sql/update.c
- src/box/sql/vdbe.c
- src/box/sql/vdbeaux.c
- src/box/sql/where.c
- src/lib/core/port.h
> SQL small refactorings

- changelogs/unreleased/gh-4317-console-add-line-carrying-backslash.md
- changelogs/unreleased/gh-7294-long-reconnection-fix.md
- changelogs/unreleased/gh-7954-sort-spaces-in-snapshot-by-id.md
- changelogs/unreleased/gh-7974-force-recovery-without-user-spaces.md
- changelogs/unreleased/gh-8069-luajit-fixes.md
- changelogs/unreleased/gh-8252-disable-jit-on-macOS-by-default.md
- changelogs/unreleased/gh-8363-unable-decode-body.md
- changelogs/unreleased/gh-8391-bump-zstd.md
- changelogs/unreleased/ghs-73-unsafe-extensions-decoding.md
Proofread changelogs for the latest version
> Proofread changelogs for the latest version

- src/box/lua/init.c
- src/box/lua/iproto.c
- src/box/lua/iproto.h
- src/box/lua/load_cfg.lua
- src/box/mp_error.cc
- src/lib/core/diag.h
- src/lib/core/exception.cc
- src/lib/core/exception.h
- src/lib/core/prbuf.c
- src/lib/core/prbuf.h
- src/lib/core/say.c
- src/lib/core/say.h
- src/main.cc
- test/unit/CMakeLists.txt
- test/unit/mp_error.cc
- test/unit/mp_error.result
- test/unit/prbuf.c
- test/unit/say.c
- test/unit/say.result
This includes prbuf reader from file API.
Part of https://github.com/tarantool/tarantool-ee/issues/319
EE part: https://github.com/tarantool/tarantool-ee/pull/419
> misc: add parts for flightrec reader in EE

- tools/tarantool-gdb.py
> gdb: support exploring of stailq lists

- test/box-luatest/gh_4264_recursive_trigger_test.lua
- test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
- test/box-luatest/gh_7800_recover_snap_without_spaces_test.lua
- test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua
- test/box-luatest/gh_7917_log_row_on_recovery_error_test.lua
- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
- test/replication-luatest/bootstrap_strategy_auto_test.lua
- test/replication-luatest/election_fencing_test.lua
- test/replication-luatest/gh_5295_split_brain_test.lua
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_6036_qsync_order_test.lua
- test/replication-luatest/gh_6754_promote_before_new_term_test.lua
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/gh_7086_box_issue_promote_assert_test.lua
- test/replication-luatest/gh_7253_election_long_wal_write_test.lua
- test/replication-luatest/gh_7377_bootstrap_connection_failure_test.lua
- test/replication-luatest/gh_7515_sync_node_sees_leader_hang_test.lua
- test/replication-luatest/gh_8168_extra_term_bump_test.lua
- test/replication-luatest/linearizable_test.lua
Just a regular backport of https://github.com/tarantool/tarantool/pull/8540 via a pull request to verify changes.
> [2.11] test: bump test-run to version w/ updated luatest and fix tests

- test/box-luatest/gh_4264_recursive_trigger_test.lua
- test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
- test/box-luatest/gh_7800_recover_snap_without_spaces_test.lua
- test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua
- test/box-luatest/gh_7917_log_row_on_recovery_error_test.lua
- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
- test/replication-luatest/election_fencing_test.lua
- test/replication-luatest/gh_5295_split_brain_test.lua
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_6036_qsync_order_test.lua
- test/replication-luatest/gh_6754_promote_before_new_term_test.lua
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/gh_7086_box_issue_promote_assert_test.lua
- test/replication-luatest/gh_7253_election_long_wal_write_test.lua
- test/replication-luatest/gh_8168_extra_term_bump_test.lua
Just a regular backport of #8540 via a pull request to verify changes.
> [2.10] test: bump test-run to version w/ updated luatest

- tools/tarantool-gdb.py
> gdb: allow to filter entry fields while exploring lists

- tools/tarantool-gdb.py
Introduced command 'tt-list-walk'
Changes in 'tt-list' options:
- dropped options -pre/post (previously used to implement walking
functionality; no longer needed)
- option -filter was renamed to -predicate (so it can be specified with
just -p while previously at least -fil need to be used to avoid
ambiguity with -fields option)
Closes #8524
> gdb: nice list walking

- src/box/lua/net_box.c
> box: refactor net.box response body decoding

- changelogs/unreleased/gh-6126-retry-join-automatically.md
- changelogs/unreleased/gh-7590-replicaset-assert.md
> changelog: proofread 2.10.7 changelogs

- changelogs/unreleased/gh-7939-fix-misc-memory-leaks-on-tuple-encoding-failure.md
- src/box/lua/call.c
- src/box/lua/execute.c
- src/box/lua/index.c
- src/box/lua/iproto.c
- src/box/lua/misc.cc
- src/box/lua/net_box.c
- src/box/lua/tuple.c
- src/box/lua/tuple.h
- src/box/lua/watcher.c
- src/box/sql/mem.c
- src/lua/msgpack.c
- src/lua/msgpack.h
- src/lua/serializer.c
- src/lua/serializer.h
- test/app-tap/lua/serializer_test.lua
- test/box-luatest/gh_7939_fix_meamleak_on_tuple_encode_test.lua
- test/unit/lua_msgpack.c
Fixes misc places where failure to encode tuple leads to memory leaks.
Closes #7939
> Fix misc memleaks on tuple encode failure

- changelogs/unreleased/gh-7149-forbid-ddl-until-box-schema-upgrade.md
See https://github.com/tarantool/tarantool/pull/8705#discussion_r1206913100
Fixes commit 97c2c9a4fb58
Follow-up #7149
> changelog: mark changelog entry for gh-7149 as breaking

- test/box-luatest/gh_8192_feedback_daemon_metrics_test.lua
The patch fixes two mistakes that were made while writing the test. Firstly, we should replace metrics module with an empty table before every test case - otherwise, metrics can be collected before the test. Secondly, all attempts to check if a required amount of metrics was collected is pointless, even with margin - some environments are incredibly slow. So let's check if some metrics were collected, and check if there are not too many of them.
Also, the patch increases some timeouts to minimize the probability of fail due to slow environment.
Follows up #8192
Closes tarantool/tarantool-qa#312
> test: fix flaky feedback_daemon_metrics test

- tools/tarantool-gdb.py
This commit introduce commands:
- info tt-fibers (Display fibers of the current cord)
- tt-fiber FID (Select fiber which stack need to be explored)
After switching to the desired fiber its stack can be explored with
general stack commands of GDB (bt, frame, etc.)
Closes #7733
> gdb: explore stack of non-current fiber

- cmake/compiler.cmake
- cmake/utils.cmake
> build: replace string with JOIN option to string_join helper in CMake

- src/lib/core/proc_name_cache.cc
Benchmark from #7207 shows that this change does not effect performance.
Closes #8777
> core: use `malloc` instead of `region` allocator in procedure name cache

- changelogs/unreleased/gh-7124-remove-cord-slab-cache-symbol-from-public-api-export.md
- extra/exports
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
> box: remove `cord_slab_cache` symbol from public API export

- changelogs/unreleased/gh-8326-mvcc-lost-gap-record.md
- changelogs/unreleased/gh-8648-mvcc-broken-rollback-of-prepared.md
- changelogs/unreleased/gh-8654-mvcc-abort-readers-of-prepared-and-rollbacked.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_space.c
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box-luatest/gh_8326_mvcc_lost_gap_record_test.lua
- test/box-luatest/gh_8648_memtx_mvcc_rollback_prepared_test.lua
- test/box/tx_man.result
- test/box/tx_man.test.lua
- test/engine-luatest/gh_8654_memtx_mvcc_abort_readers_of_prepared_test.lua
A huge refactoring of MVCC engine.
Closes https://github.com/tarantool/tarantool/issues/8654
Closes https://github.com/tarantool/tarantool/issues/8648
Closes https://github.com/tarantool/tarantool/issues/8326
(backport from master).
> Gh 8654 memtx mvcc abort readers of prepared 2.10

- src/box/lua/tuple.c
`<luaT_pushtuple>` function created a new GCfunc object for a tuple `__gc` handler (i.e. `<lbox_tuple_gc>`), having no upvalues, on each call when tuple object for Lua world is created.
The change introduces the reference to the single GCfunc object created on Tarantool startup and stored to Lua registry. Using this approach in scope of `<luaT_pushtuple>` is aimed to reduce Lua GC memory usage.
Part of #5201
Signed-off-by: Igor Munkin <imun@tarantool.org>
---
Here are some benchmarks.
Firstly, I've written a simple benchmark in Lua.
<details>
```lua
local bench = require('clock').bench
local function stats(results, msgfmt, ...)
print(("%s: %f"):format(msgfmt:format(...), results[1]))
end
local reps = arg[1] or 1e6
collectgarbage('collect')
collectgarbage('collect')
stats(bench(function(n) …
```
> box: reduce luaT_pushtuple Lua GC memory usage

- changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md
- src/box/memtx_tx.c
> memtx: fix heap-use-after-free of tuple stories caused by space alter

- changelogs/unreleased/config.md
> config: add changelog entry re config

- changelogs/3.0.0-alpha1.md
> Generate changelog for 3.0.0-alpha1

- changelogs/unreleased/gh-7483-ignore-mpack-types.md
- src/box/field_def.c
- src/box/key_def.h
- src/box/tuple_bloom.c
- src/box/tuple_compare.cc
- src/box/tuple_hash.cc
- test/engine-luatest/gh_7483_insert_int_into_double_field_test.lua
- test/engine/insert.result
- test/engine/insert.test.lua
- test/sql-tap/cast.test.lua
- test/unit/msgpack.result
- test/vinyl/upsert.result
- test/vinyl/upsert.test.lua
Backport of https://github.com/tarantool/tarantool/pull/8666
> box: compare and hash msgpack value of double key field as double 2.11

- changelogs/unreleased/gh-8861-feedback-options.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patch introduces all feedback options.
Part of #8861
> config: introduce feedback options

- .github/CODEOWNERS
In order to improve tests of Tarantool core
assign dedicated team to perform review of each
and every change.
> Add owners for test/ and /test-run/

- .github/CODEOWNERS
Add code owners for CI-related script.
> Add owners for .test.mk and .github

- perf/lua/1mops_write.lua
The test can be used for regression testing. It is advisable to tune the machine: check the NUMA configuration, fix the pstate or similar CPU autotune. Although, running dozen times gives more-less stable result for the peak performance, that should be enough for regression identification.
> perf: initial version of 1M operations test

- .github/CODEOWNERS
- .github/workflows/release_clang.yml
- .github/workflows/release_lto_clang.yml
- static-build/cmake/AddDependencyProjects.cmake
Just a regular backporting of test/infra commits via a pull request to verify changes.
> [2.10] Backport test/infra relevant changes

- changelogs/unreleased/config-extras.md
- src/box/lua/config/init.lua
- test/config-luatest/basic_test.lua
- test/config-luatest/helpers.lua
This is not a public API, at least now.
Part of #8862
> config: allow to extend the module on Tarantool CE

- changelogs/unreleased/gh-8967-remove-hashes-from-creds.md
- changelogs/unreleased/gh-8967-upgrade-password-sync.md
- doc/examples/config/replicaset.yaml
- doc/examples/config/replicaset_election_failover.yaml
- doc/examples/config/replicaset_manual_failover.yaml
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/applier/credentials.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/basic_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patchset aims to fix several minor credentials issues from #8967.
> config: minor credential upgrades

- changelogs/3.0.0-alpha2.md
> Generate changelog for 3.0.0-alpha2

- test/interactive_tarantool.lua
Before this patch interactive_tarantool `:read_response()` helper used
to just deserialise Lua errors as tables like `[{error = 'msg'}]`.
Now it checks if response is actually an error and rethrows it.
This provides additional verification for many tests that use
interactive_tarantool.
This patch is a followup to commit 261a21bd1fe8 ("test/config: adjust
initial permissions in a test"). It provides additional output checks
to prevent similar issues.
Part of #8967
> test: add error rethrow to :read_response() in interactive_tarantool

- .github/CODEOWNERS
I want to receive review request notifications about the changes and let people know who is responsible to accept them.
> Add @Totktonada as codeowner for config

- test/box-luatest/gh_8051_set_box_cfg_thru_env_test.lua
The test starts a child tarantool instance in the current working directory and run box.cfg(). The current working directory is a source directory. test-run.py runs many tests from it in parallel and in some circumstances it appears that the directory is locked by some other box.cfg() call from some other tarantool instance (maybe another test is doing the same).
The test is rewritten to use a temporary directory for such runs.
The test.interactive_tarantool helper is used for convenience instead of a popen wrapper that is written specifically for the test.
> test: fix flaky box.cfg() env vars test

- test/box-luatest/gh_8051_set_box_cfg_thru_env_test.lua
(Backport of PR #9024 to 2.11.)
The test starts a child tarantool instance in the current working directory and run box.cfg(). The current working directory is a source directory. test-run.py runs many tests from it in parallel and in some circumstances it appears that the directory is locked by some other box.cfg() call from some other tarantool instance (maybe another test is doing the same).
The test is rewritten to use a temporary directory for such runs.
The test.interactive_tarantool helper is used for convenience instead of a popen wrapper that is written specifically for the test.
> [backport 2.11] test: fix flaky box.cfg() env vars test

- src/box/tuple_compare.cc
The tuple_compare_slowpath comparator had unreachable branch under this condition: `key_def->part_count == 1 && part->fieldno == 0 && (!has_json_paths || part->path == NULL)`. The condition will never be true in the function context.
It has been introduced in the commit c8b87dc7696bff484981c55dff9dad0118ea662c ("Speed up tuple_compare()."), when there was no sqeuential comparators, and so it was reasonable at that moment. But since the sequential comparators had been introduced in the 78102868cd35c0b5dc6fadb614cb7a5c9b074f82 ("Don't store offsets for sequential multi-parts keys") the condition became permanently falsy.
There're two ways it can be true:
1. `key_def->part_count == 1 && part->fieldno == 0 && !has_json_paths`
2. `key_def->part_count == 1 && part->fieldno == 0 && …
> box: get rid of the unreachable branch

- test/fuzz/CMakeLists.txt
- test/fuzz/xrow_header_decode_fuzzer.c
> test/fuzz: add fuzzing tests for xrow_header_decode

- changelogs/3.0.0-alpha3.md
> Generate changelog for 3.0.0-alpha3

- test/fuzz/CMakeLists.txt
- test/fuzz/xrow_decode_error_fuzzer.c
~~Depends on #9015~~
~~Depends on #9098~~
~~Follows up #8921~~
> Add fuzzing test for xrow_decode_error

- perf/lua/1mops_write.lua
The option --sync was ignored due to a misprint.
The temporary dir was never removed, overflowing the /tmp by default.
NO_TEST=test update
NO_DOC=test update
NO_CHANGELOG=test update
> test: fixup the 1mops perf test

- changelogs/3.0.0-beta1.md
> Generate changelog for 3.0.0-beta1

- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/lint.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/release.yml
- .github/workflows/release_lto.yml
- .github/workflows/source.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/submodule_update.yml
Just a regular backport of #9257 via a pull request to verify changes.
> [2.11] ci: dockerize linux workflows

- changelogs/unreleased/config-set-names-on-reload.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/set_names_reload_test.lua
- test/config-luatest/validate_names_test.lua
Closes tarantool/tarantool-qa#328
Closes tarantool/tarantool-qa#329
> Config names tests stabilization

- tools/gen-release-notes
Some changes are not new features, rather developer tools updates and improvements. There are also number of tweaks we can introduce to improve testing and tests backporting across branches, which also are not considered neither feature nor bug fix.
> changelog: added new topics 'tools' and 'testing'

- changelogs/unreleased/add-asan-flag-to-tarantool-build.md
- changelogs/unreleased/bump-libcurl-to-8.3.0.md
- changelogs/unreleased/gh-6597-update-luarocks.md
- changelogs/unreleased/gh-7593-console-debugger.md
- changelogs/unreleased/gh-9086-fix-streaming-connection-stuck.md
- changelogs/unreleased/ghe-523-max-config-param-length.md
Updates to make minor release feature-less. 
NO_DOC=no features
NO_TEST=no code added
NO_CHANGELOG=it is the changelog
> Proposed changes to changelog for 2.11.2 release.

- asan/asan.supp
- src/box/box.cc
- src/box/box.h
- src/box/iproto.cc
- src/box/iproto.h
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/relay.cc
- src/box/relay.h
- src/box/replication.cc
- src/lib/core/coio.c
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/main.cc
- test/box-luatest/sending_arbitrary_iproto_packets_test.lua
- test/unit/fiber.cc
- test/unit/fiber.result
Iproto and relay part of #8423
**update**: We have to leave `cord_cancel_and_join` for iproto for now. So iproto part is not complete.
> Iproto and relay graceful shutdown

- src/box/iproto.cc
Deadlock is described in detail in the ticket. Let's don't wait while connection that called iproto_drop_connections is deleted. It will be deleted eventually when request executing iproto_drop_connections is finished and all other requests in progress from this connection are finished too (they are cancelled just as requests of other connections).
CE part for issue https://github.com/tarantool/tarantool-ee/issues/609
[EE part](https://github.com/tarantool/tarantool-ee/pull/610)
> iproto: fix deadlock when dropping connections from iproto

- changelogs/unreleased/bump-libcurl-to-8.5.0.md
- cmake/BuildLibCURL.cmake
- cmake/CheckPatch.cmake
Passed CI in Tarantool EE: https://github.com/tarantool/tarantool-ee/pull/616
> Bump curl 8.5.0 and fix checkpatch module

- .github/actions/install-deps-osx/action.yml
- .github/workflows/freebsd.yml
- .github/workflows/osx.yml
- Drop testing for macOS 12 since macOS 14 is available
- Add testing for macOS 14
> ci: drop testing for macOS 12, add for macOS 14 

- src/box/applier.cc
- src/box/box.cc
- src/box/lua/info.c
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/shutdown_test.lua
Part of https://github.com/tarantool/tarantool/issues/8423 related to replication.
> Replication graceful shutdown

- test/app-tap/gh-2717-no-quit-sigint.test.lua
- First `string.endswith` returns boolean so fix where it compared with nil. Due to the invalid comparison we actually don't check for prompt in nested case.
- Add trailing space to prompt in this test case.
- Reset readline configuration in this test case.
> test: fix gh-2717-no-quit-sigint test

- changelogs/unreleased/gh-9547-fix-reading-data-in-chunked-request.md
- src/httpc.c
Tarantool EE CI: https://github.com/tarantool/tarantool-ee/pull/623
Fix #9547 
~~Depends on https://github.com/curl/curl/pull/12740~~
> Fix reading data in a chunked request

- changelogs/3.0.1.md
- changelogs/unreleased/bump-libcurl-to-8.5.0.md
- changelogs/unreleased/fix-lua-loader-error-handling.md
- changelogs/unreleased/gh-9547-fix-reading-data-in-chunked-request.md
- changelogs/unreleased/gh_9572_config_with_uuids.md
Also, remove unreleased/ entries.
> Generate changelog for 3.0.1

- test/app-luatest/fix_lua_loader_error_handling_test.lua
This patch is a follow-up for the commit
b99a35412d0c65dd84209872654fec9aaf2f1d02 ("lua: fix loader behaviour in case of syntax error").
This test uses full matching of the error message and assumes that the temporary directory is short enough, so the full patch is less than 60 symbols (size of `lua_Debug.short_src`). But for macOS, the temporary directory has a longer path, so the error message is shrunk and isn't equal to the expected string.
This patch replaces full matching with matching of the last part of the error message.
Relates to tarantool/tarantool-ee#585
---
I tested it on my macOS locally -- no more failures:).
> test: fix fix_lua_loader_error_handling on macOS

- src/box/box.cc
- test/app-luatest/shutdown_test.lua
Currently hot standby in not cancelable. So if for example it is executed in init script then server shutdown hang. The issue is shutdown waits init script fiber finishing.
Part of #8423
> box: fix hot standby shutdown hang

- changelogs/unreleased/gh-8138-iproto-override-via-event-triggers.md
- changelogs/unreleased/gh-8138-switch-box-iproto-override-to-triggers.md
- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/iproto.cc
- src/box/iproto.h
- src/box/iproto_constants.c
- src/box/iproto_constants.h
- src/box/lua/func_adapter.c
- src/box/lua/init.c
- src/box/lua/iproto.c
- src/box/lua/iproto.h
- src/box/lua/iproto.lua
- src/box/space.c
- src/lib/core/event.c
- src/lib/core/event.h
- src/lib/core/func_adapter.h
- test/box-luatest/iproto_request_handlers_overriding_test.lua
- test/engine-luatest/space_triggers_test.lua
- test/unit/event.c
- test/unit/lua_func_adapter.c
> iproto: override request handlers using event triggers

- CMakeLists.txt
- changelogs/unreleased/gh-9580-fix-cpath-for-external-libs.md
Just a regular backport of #9663 via a pull request to verify changes.
> [3.0] build: fix package.cpath for Debian based distros

- tools/tarantool-gdb.py
> gdb: support msgpack extension MP_TUPLE

- src/box/vy_scheduler.c
`sql-tap/intpkey.test` start to flak under load after the commit fe769b0a0325 ("vinyl: add graceful shutdown"). The issue is vy_scheduler_complete_tasks() may yield. So on shutdown `vinyl.scheduler` fiber may be cancelled during this yield and then we go to sleep waiting for new tasks forever.  Now vinyl shutdown hangs.
Part of #8423
> vinyl: check if fiber is cancelled after tasks completion

- .github/workflows/etcd_integration.yml
- .github/workflows/integration.yml
Just a regular backport of #9779 via a pull request to verify changes.
> [3.0] ci: add integration testing for etcd-client

- changelogs/unreleased/gh-9107-error-autocomplete.md
- src/box/lua/console.c
- src/lua/error.lua
- test/app-luatest/gh_6305_autocomplete_metamethod_test.lua
- test/box-luatest/error_subsystem_improvements_test.lua
This patch set adds error autocompletion.
Closes #9107
> Add error autocompletion

- test/box-luatest/gh_8663_persistent_triggers_test.lua
The replication test of persistent triggers was waiting only for the persistent triggers to arrive on replica, so the replica tried to write to the space which was not created there yet. Let's wait for all changes to arrive to make the test stable.
Closes #9967
> test: fix flaky persistent triggers test

- test/box-luatest/gh_8663_persistent_triggers_test.lua
The replication test of persistent triggers was waiting only for the persistent triggers to arrive on replica, so the replica tried to write to the space which was not created there yet. Let's wait for all changes to arrive to make the test stable.
Closes #9967
NO_DOC=test
(cherry picked from commit 927e351625292c20ff6d07cc70164725fce8b338)
> [backport 3.1] test: fix flaky persistent triggers test

- changelogs/unreleased/add-box-error-is.md
- changelogs/unreleased/gh-9792-support-level-with-errcode.md
- src/box/lua/error.cc
- test/app-luatest/gh_9792_error_level_test.lua
- test/box-luatest/error_subsystem_improvements_test.lua
- test/box-py/call.result
- test/box-py/call.test.py
Namely:
- error: support level with errcode
- lua: add box.error.is
Part of #9914
> misc error enhancements

- test/box-luatest/gh_9823_net_replicaset_test.lua
Fix several problems that led to unexpected results:
* Handle error thrown by box.clt.promote. Not very often but it could fail ruining the test. Fixed by retry.
* It's not so obvious but RO server after successful call of box.ctl.promote for some time remains RO. On the other hand both net.replicaset and the test rely box.info.ro to define the leader, for in their view the actual switch to the new leader happens some (perhaps different) time after call to box.ctl.promote. That asynchrony sometimes led to unexpected results. Fixed by waiting of RW status.
* The fix above (wait for RW of the new leader) introduced new problem: in case with sequential leader change and broadcast of new values, the new leader has good chances (but not 100%) to deliver old broadcasted value to the watcher. …
> net.replicaset: fix a flaky test

- test/replication-luatest/gh_9748_downstream_lag_test.lua
It could fail in ASAN build. Binaries of that build are very slow and the tests could too easily outrun the default retry timeout in luatest which is just 5 seconds.
The patch manually bumps it to 60 seconds.
Closes #10031
NO_DOC=test
> test: fix flaky downstream lag test

- test/replication-luatest/gh_9748_downstream_lag_test.lua
It could fail in ASAN build. Can't tell why just there.
The main reason was that in a topology server1 + server2->server3 one of the cases
- did a txn on server1,
- then enabled server2->server3 replication,
- then waited for server2->server3 sync,
- and instantly assumed the txn reached server3.
Surely it not always did. At the server2->server3 sync the txn might not had reached server2 itself yet.
The fix is as simple as explicitly ensure the txn is on server2 before waiting server2->server3 sync.
Another potential for flakiness was that the default timeout in luatest.helpers.retrying is super low, just 5 seconds. The patch manually bumps it to 60 seconds to be sure any future failures wouldn't be related to too small timeout.
Closes #10031
NO_DOC=test
(cherry picked …
> [backport 3.1] test: fix flaky downstream lag test

- changelogs/unreleased/gh-9893-rollback-ddl-on-_space-space.md
- src/box/alter.cc
- src/box/applier.cc
- src/box/lua/init.c
- src/box/txn.c
- src/box/txn.h
- src/box/user.cc
- src/box/user.h
- src/box/vinyl.c
- test/box-luatest/gh_9893_rollback_ddl_on__space_space_test.lua
- test/box-luatest/rollback_ddl_on__priv_space_test.lua
Also had to backport an extra commit: https://github.com/tarantool/tarantool/commit/a1d8582769e03b7bb5885cd71de35dc808bb213f
> [backport 2.11] txn: run statement on_rollback triggers before rolling back statement

- .github/workflows/submodule_update.yml
- Fix the `test-sdk` job according to recent changes in SDK
- Fix sending VK Teams message on failure
> [2.11] ci: fix submodule_update.yml workflow 

- .github/workflows/submodule_update.yml
- Fix the `test-sdk` job according to recent changes in SDK
- Fix sending VK Teams message on failure
> [2.10] ci: fix submodule_update.yml workflow

- changelogs/unreleased/gh-6860-demote-in-off-mode.md
- changelogs/unreleased/gh-9855-box-ctl-demote-guarantee-demoting.md
- src/box/box.cc
- src/box/raft.c
- src/box/raft.h
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/gh_6860_election_off_demote_test.lua
- test/replication-luatest/gh_9855_box_ctl_demote_guarantee_demoting_test.lua
Also had to backport https://github.com/tarantool/tarantool/commit/1afe2274d9155fc19d228237d04d1a1ddfa17270
> [backport 2.11] box: prevent demoted leader from being a candidate in the next elections

- test/replication-luatest/gh_5295_split_brain_test.lua
This test checks, that when PROMOTE from the prevous term is encountered we immediately notice split-brain situation and break replication without corrupting data.
Closes #9943
NO_DOC=test
> test: cover split-brain during promote

- test/replication-luatest/gh_5295_split_brain_test.lua
This test checks, that when PROMOTE from the previous term is encountered we immediately notice split-brain situation and break replication without corrupting data.
Closes #9943
NO_DOC=test
(cherry picked from commit 06b87e27ea42c1f2f84b98b7156eba60db669dfb)
> [backport 2.11] test: cover split-brain during promote

- test/replication-luatest/gh_5295_split_brain_test.lua
This test checks, that when PROMOTE from the previous term is encountered we immediately notice split-brain situation and break replication without corrupting data.
Closes #9943
NO_DOC=test
(cherry picked from commit 06b87e27ea42c1f2f84b98b7156eba60db669dfb)
> [backport 3.1] test: cover split-brain during promote

- docker/README.md
Doc issue: https://github.com/tarantool/doc/issues/4112
> Review the 'Tarantool Docker Image' readme

- perf/bps_tree.cc
- src/lib/salad/bps_tree.h
- test/unit/bps_tree_offset_api.cc
Closes #9982
Closes #10045
Part of #10322
> Bps tree simplification

- doc/examples/config/config-storage/README.md
Update `config.storage` README to include `tarantool-ee` changes from this PR [1].
Note that these changes are for EE only.
[1] https://github.com/tarantool/tarantool-ee/pull/857
Part of https://github.com/tarantool/tarantool-ee/issues/849
> doc: update config storage doc

- cmake/BuildICU.cmake
- cmake/BuildOpenSSL.cmake
- cmake/BuildReadline.cmake
- cmake/BuildZLIB.cmake
- cmake/ProtobufMutator.cmake
https://github.com/tarantool/tarantool/pull/10329
> [Backport 3.11] Fixes in CMake module

- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/lua/info.c
- test/box-luatest/gh_10378_export_symbols_test.lua
box_info_lsn
box_is_ro
box_ro_reason
box_wait_ro
Closes #10378
NO_CHANGELOG=minor change
Title: document 4 more symbols in public C API
box_info_lsn
box_is_ro
box_ro_reason
box_wait_ro
Their meaning is identical to lua methods:
box.info.lsn
box.info.ro
box.info.ro_reason
box.wait_ro
> box: export more symbols

- changelogs/unreleased/gh-67-commit-wait-mode.md
- src/box/applier.cc
- src/box/box.cc
- src/box/errcode.h
- src/box/journal.c
- src/box/journal.h
- src/box/lua/init.c
- src/box/lua/schema.lua
- src/box/txn.c
- src/box/txn.h
- src/box/txn_limbo.h
- src/box/wal.c
- test/box-luatest/commit_wait_test.lua
- test/box/error.result
- test/replication-luatest/commit_wait_test.lua
See #67 and the commit messages.
> Async commit

- src/box/applier.cc
- src/box/relay.cc
- test/replication-luatest/gh_10088_apply_deletion_of_replica_from_cluster_on_deleted_replica_test.lua
This patch fixes several corner cases of #10088.
Follows up #10088
Closes #10397
> box: fix several gh-10088 corner cases

- test/fuzz/CMakeLists.txt
Fixes required by PR https://github.com/google/oss-fuzz/pull/12322.
> Fixes required for using static build in OSS Fuzz

- src/box/box.cc
- test/replication/gh-5430-cluster-mvcc.result
- test/replication/gh-5430-cluster-mvcc.test.lua
This patch fixes the gh-5430 test.
Closes #9617
> test: fix gh-5430 test

- changelogs/unreleased/gh-10476-fix-fkey-constraint-check-memleak.md
- changelogs/unreleased/gh-10477-fix-iproto-override-memleak.md
- changelogs/unreleased/gh-10479-fix-xlog-open-memleak.md
- changelogs/unreleased/gh-10480-fix-replica-disconnect-memleak.md
- changelogs/unreleased/gh-10482-fix-coio-connect-memleak.md
- src/box/applier.cc
- src/box/iproto.cc
- src/box/lua/xlog.c
- src/box/space.c
- src/lib/core/coio.c
Part of #10211 
Factored out from all-in-one PR #10207
Closes #10476
Closes #10477
Closes #10479
Closes #10480
Closes #10482
> Fix memory leaks reported by ASAN (with suppressions turned off) part 1

- changelogs/unreleased/gh-10484-fix-space-DDL-memleak.md
- changelogs/unreleased/gh-10485-fix-user-DDL-memleak.md
- changelogs/unreleased/gh-10487-fix-iconv-memleak.md
- changelogs/unreleased/gh-10489-fix-vinyl-on-dump-failure-memleak.md
- changelogs/unreleased/gh-10490-fix-replica-deleted-memleak.md
- src/box/alter.cc
- src/box/applier.cc
- src/box/vy_run.c
- src/lua/iconv.lua
Part of https://github.com/tarantool/tarantool/issues/10211
Factored out from all-in-one PR https://github.com/tarantool/tarantool/pull/10207
Closes #10484
Closes #10485 
Closes #10487 
Closes #10489 
Closes #10490
> Fix memory leaks reported by ASAN (with suppressions turned off) part 2

- src/box/box.cc
- src/box/coll_id_cache.c
- src/box/gc.c
- src/box/memtx_engine.cc
- src/box/replication.cc
- src/box/space.c
- src/box/space.h
- src/box/space_cache.c
- src/box/sql.h
- src/box/sql/trigger.c
- src/box/txn.c
- src/box/txn.h
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- src/box/user.cc
- src/main.cc
Part of https://github.com/tarantool/tarantool/issues/10211
Factored out from all-in-one PR https://github.com/tarantool/tarantool/pull/10207
> Prepare to drop LSAN suppressions, part 2

- changelogs/unreleased/update-c-api.md
- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/lua/slab.cc
Add struct slab_info and fuction box_slab_info for use in lbox_slab_info and export in c API
> Update c API

- test/fuzz/lua/test_engine.lua
> test/fuzz: fix error injections in engine test

- asan/lsan.supp
- changelogs/unreleased/gh-10495-fix-swim-crash-on-shutdown.md
- src/box/gc.c
- src/box/lua/func_adapter.c
- src/box/lua/init.c
- src/box/lua/space.cc
- src/box/lua/space.h
- src/box/lua/watcher.c
- src/box/memtx_engine.cc
- src/box/space.c
- src/lib/swim/swim.c
- src/main.cc
- test/app-tap/module_api.c
Factored out from all-in-one PR https://github.com/tarantool/tarantool/pull/10207
Closes #10211
Closes #3071
Closes #8890
Closes #10055
Closes #9213
Closes #10495
Related EE PR https://github.com/tarantool/tarantool-ee/pull/835
> Drop LSAN suppressions (almost)

- third_party/sptree.h
This causes warnings if compiled with clang-18. Let's define a sane upper limit for the max tree depth and use it for allocating arrays on stack. Note that we don't really care about performance because sptree is used only in unit tests.
Closes #10354
> sptree: don't use variable length arrays

- changelogs/unreleased/gh-10391-forbid-non-integers-datetime-new.md
- changelogs/unreleased/gh-10391-forbid-non-integers-datetime-set.md
- changelogs/unreleased/gh-10391-forbid-non-integers-sql-datetime.md
- src/lib/core/datetime.c
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
- test/sql-luatest/datetime_test.lua
> Forbid non-integers in datetime.new, :set() and parse()

- changelogs/unreleased/gh-8333-fix-ignoring-tzoffset-in-parse.md
- src/box/sql/mem.c
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- src/lua/datetime.lua
- src/lua/tnt_datetime.c
- test/app-tap/datetime.test.lua
- test/fuzz/datetime_parse_full_fuzzer.c
- test/unit/datetime.c
> datetime: use tzoffset in datetime.parse{format}

- test/fuzz/lua/test_engine.lua
> Fix `test/fuzz/lua/test_engine.lua` hang at exit due to enabled error injections

- .github/workflows/debug_asan_clang.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto_clang.yml
- cmake/BuildLibXXhash.cmake
- cmake/BuildZSTD.cmake
Docker image: https://github.com/tarantool/infra/pull/206
Tarantool EE: https://github.com/tarantool/tarantool-ee/pull/922
Depends on https://github.com/tarantool/tarantool/issues/10631
NO_DOC=ci
NO_TEST=ci
> ci: bump clang version to 19

- cmake/compiler.cmake
- src/box/sql/func.c
- src/box/sql/util.c
- src/lib/core/datetime.c
- src/lib/core/fiber.c
- src/trivia/config.h.cmake
Depends on https://github.com/tarantool/tarantool/issues/10699
> Fix GCC's UBsan and update a list of disabled UBSan checks

- cmake/compiler.cmake
- src/box/sql/func.c
- src/box/sql/util.c
- src/lib/core/datetime.c
- src/lib/core/fiber.c
- src/trivia/config.h.cmake
Orig PR: https://github.com/tarantool/tarantool/pull/10702
> [Backport 3.2] Fix GCC's UBsan and update a list of disabled UBSan checks

- perf/CMakeLists.txt
- src/box/index.cc
- src/box/index.h
- src/box/lua/schema.lua
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/sequence.c
Part of tarantool/tarantool-ee#858
> Make it possible to accelerate the select with offset and implement count in the memtx tree read view

- changelogs/unreleased/gh-10089-raft-meta-join.md
- changelogs/unreleased/gh-10727-no-local-rows-via-replication.md
- src/box/applier.cc
- src/box/box.cc
- src/box/iproto_constants.h
- src/box/memtx_engine.cc
- src/box/raft.c
- src/box/relay.cc
- src/box/relay.h
- src/box/xrow.c
- src/box/xrow.h
- src/lib/core/errinj.h
- test/replication-luatest/gh_10727_no_local_rows_test.lua
- test/replication-luatest/join_test.lua
Closes https://github.com/tarantool/tarantool/issues/10089
Closes https://github.com/tarantool/tarantool/issues/10727
> Fix raft state never being sent

- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/isolated_mode_test.lua
The isolated instance shouldn't produce new transactions, including ones from a background fiber started by an application or a role. So, the isolated instance forcefully goes to the read-only mode disregarding any other configuration options.
Part of #10796
> config: switch to RO in isolated mode

- test/config-luatest/isolated_mode_test.lua
It shouldn't affect other developers. I'll look into it in background. Filed issue tarantool/tarantool-qa#332 as a reminder.
Follows up #10796
Related to tarantool/tarantool-qa#332
> test: skip flaky test case for isolated mode

- .github/workflows/config_jsonschema_check.yml
- .pack.mk
- changelogs/unreleased/gh-10636-cluster-config-json-schema.md
- changelogs/unreleased/gh-10636-generate-json-schema.md
- src/box/CMakeLists.txt
- src/box/lua/config/cluster_config.lua
- src/box/lua/config/descriptions.lua
- src/box/lua/config/init.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/config/utils/schema.lua
- src/box/lua/config/utils/textutils.lua
- src/box/lua/init.c
- test/app-luatest/override_test.lua
- test/config-luatest/anonymous_replica_test.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/failover_and_election_mode_test.lua
- test/config-luatest/jsonschema_config_test.lua
- test/config-luatest/jsonschema_schema_test.lua
This patch adds a method `:jsonschema()` to `config` module. This method generates JSON schema of cluster config schema.
You can generate and save this json schema to a file.
```lua
local config = require('config')
local json = require('json')
local fio = require('fio')
-- Generate the JSON schema of the cluster configuration as a Lua table
local schema = config:jsonschema()
-- Encode the schema as a JSON string
local schema_json = json.encode(schema)
-- Save the schema to a file named 'config-schema.json'
local file_path = fio.pathjoin(fio.cwd(), 'config-schema.json')
local file = fio.open(file_path, {'O_WRONLY', 'O_CREAT', 'O_TRUNC'}, tonumber('644', 8))
if file then
file:write(schema_json)
file:close()
End
```
And use it in the following scenarios:
- CLI Validation with …
> config: `:jsonschema()` method and descriptions for schema fields

- changelogs/unreleased/gh-10377-do-not-abort-unrelated-on-ddl.md
- src/box/engine.h
- src/box/memtx_engine.cc
- src/box/memtx_space.c
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/space.c
- src/box/txn.c
- src/box/txn.h
- src/box/vinyl.c
- test/box/gh-5998-one-tx-for-ddl-errinj.result
- test/box/gh-5998-one-tx-for-ddl-errinj.test.lua
- test/box/gh-5998-one-tx-for-ddl.result
- test/box/gh-5998-one-tx-for-ddl.test.lua
- test/engine-luatest/gh_10375_ddl_does_not_abort_unrelated_transactions_test.lua
- test/engine-luatest/gh_10377_ddl_and_concurrent_transactions_test.lua
- test/engine/errinj_ddl.result
- test/engine/errinj_ddl.test.lua
- test/replication-luatest/gh_9720_tmp_spaces_ddl_abort_applier_txs_test.lua
See the commits for details.
Closes #10377
> memtx: do not abort unrelated transactions on DDL

- .github/workflows/perf_micro.yml
- perf/tools/setup_env.sh
Depends on https://github.com/tarantool/tarantool/pull/10778
Depends on https://github.com/tarantool/tarantool/pull/10866
Tests in a branch: https://github.com/tarantool/tarantool/pull/10876
> Tuning performance testing

- test/fuzz/lua/test_engine.lua
The option `txn_isolation` was introduced in commit ec750af66d94 ("txm: introduce transaction isolation levels") and described in documentation (see [1] and [2]), but missed in a page with `box.cfg` parameters. It is a reason why it was not used in the test `test_engine.lua` from the beginning. The patch fixes that.
1. https://www.tarantool.io/en/doc/latest/platform/atomic/txn_mode_mvcc/
2. https://www.tarantool.io/en/doc/latest/platform/atomic/transaction_model/
NO_DOC=testing
> test/fuzz: support txn_isolation option

- changelogs/unreleased/gh-10089-raft-meta-join.md
- changelogs/unreleased/gh-10727-no-local-rows-via-replication.md
- src/box/applier.cc
- src/box/box.cc
- src/box/iproto_constants.h
- src/box/memtx_engine.cc
- src/box/raft.c
- src/box/relay.cc
- src/box/relay.h
- src/box/xrow.c
- src/box/xrow.h
- src/lib/core/errinj.h
- test/replication-luatest/gh_10727_no_local_rows_test.lua
- test/replication-luatest/join_test.lua
> [backport 3.2] Fix raft state never being sent

- changelogs/unreleased/gh-10089-raft-meta-join.md
- changelogs/unreleased/gh-10727-no-local-rows-via-replication.md
- src/box/applier.cc
- src/box/box.cc
- src/box/iproto_constants.h
- src/box/memtx_engine.cc
- src/box/raft.c
- src/box/relay.cc
- src/box/relay.h
- src/box/xrow.c
- src/box/xrow.h
- src/lib/core/errinj.h
- test/replication-luatest/gh_10727_no_local_rows_test.lua
- test/replication-luatest/join_test.lua
This is a backport of #10293
Also had to backport commit https://github.com/tarantool/tarantool/commit/7d093bb19cbc1409441286bacb35523ec25b1d72
> [backport 2.11] Fix raft state never being sent

- .github/workflows/perf_micro.yml
- `pull_request_target` was tested on PR https://github.com/sqaunderhood/tarantool/pull/1
- CI in main repository https://github.com/tarantool/tarantool/pull/10954
> Tuning perf_micro workflow

- .test.mk
- CMakeLists.txt
- cmake/MakeLuaPath.cmake
- cmake/SetBuildParallelLevel.cmake
- cmake/luajit.cmake
- perf/CMakeLists.txt
- perf/lua/CMakeLists.txt
- test/CMakeLists.txt
- test/app-luatest/CMakeLists.txt
- test/box-luatest/CMakeLists.txt
- test/config-luatest/CMakeLists.txt
- test/fuzz/CMakeLists.txt
- test/fuzz/lua/CMakeLists.txt
- test/metrics-luatest/CMakeLists.txt
- test/replication-luatest/CMakeLists.txt
- test/sql-luatest/CMakeLists.txt
- test/unit/CMakeLists.txt
- test/vinyl-luatest/CMakeLists.txt
Merging depends on:
CTest support sub-tasks:
> Support CTest

- .github/workflows/perf_micro.yml
Orig PR: https://github.com/tarantool/tarantool/pull/10899
> [Backport 3.3] Tuning perf_micro workflow

- .test.mk
- CMakeLists.txt
- cmake/MakeLuaPath.cmake
- cmake/SetBuildParallelLevel.cmake
- cmake/luajit.cmake
- perf/CMakeLists.txt
- perf/lua/CMakeLists.txt
- test/CMakeLists.txt
- test/app-luatest/CMakeLists.txt
- test/box-luatest/CMakeLists.txt
- test/config-luatest/CMakeLists.txt
- test/fuzz/CMakeLists.txt
- test/fuzz/lua/CMakeLists.txt
- test/metrics-luatest/CMakeLists.txt
- test/replication-luatest/CMakeLists.txt
- test/sql-luatest/CMakeLists.txt
- test/unit/CMakeLists.txt
- test/vinyl-luatest/CMakeLists.txt
Orig PRs:
- https://github.com/tarantool/tarantool/pull/10216
- https://github.com/tarantool/tarantool/pull/10979
- https://github.com/tarantool/tarantool/pull/10978
> [Backport 3.3] Support CTest

- changelogs/3.3.1.md
- changelogs/unreleased/config-lack-of-sharding-role.md
- changelogs/unreleased/config-schema-deep-merge.md
- changelogs/unreleased/gh-10347-proper-instance-duplicates-messages.md
- changelogs/unreleased/gh-10561-anon-replicas-dont-participate-in-elections.md
- changelogs/unreleased/gh-10707-fix-vinyl-abort-writers-on-ddl.md
- changelogs/unreleased/gh-10855-schema-get-set-changes-path.md
- changelogs/unreleased/gh-10870-fix-vinyl-tx-stmt-overwrite-multikey.md
- changelogs/unreleased/gh-10879-fix-vinyl-cache-invalidation-on-rollback.md
- changelogs/unreleased/gh-10895-fix-vinyl-deferred-delete-compaction.md
- changelogs/unreleased/gh-10934-fix-roles-on_event-config-argument.md
- changelogs/unreleased/gh-9923-fix-invalid-iproto-name-mapping-on-the-server-side.md
- src/box/lua/upgrade.lua
Also remove unreleased/ entries and add a new downgrade version to the downgrade versions list.
> [release/3.3] Generate changelog for 3.3.1

- .github/workflows/static_build_cmake_linux.yml
- test/CMakeLists.txt
> ci: use cmake 3.17 in static_build_cmake_linux

- test/app-luatest/gh_7000_compat_module_test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/11020
> [Backport 3.3] test: fix app-luatest/gh_7000_compat_module_test.lua

- cmake/BuildLuaTests.cmake
- src/box/CMakeLists.txt
- test/fuzz/CMakeLists.txt
> Reuse Lua fuzzing tests

- src/box/lua/connpool.lua
connpool: add internal pool class
This patch introduces an internal pool abstraction in
`experimental.connpool` module. The idea is quite similar to a cartridge
pool module [1] used in RPC [2]. We need to have a way to work with a
set of connections. But instead of URIs we use instance names now.
This abstraction is useful for #10330. The issue is about making the
connpool check the connections in the background. It includes closing
unused connections automatically to free a few file descriptors. We want
to make `filter()` and `call()` methods open connections that'd be
closed if they remain unused. These functions use a public `connect()`
method internally. Thereby straightforward implementation requires
extending public `connect()` method with an option making the connection …
> connpool: add internal pool class

- changelogs/unreleased/gh-9965-wrong-numbers-comparison.md
Fixing comments from here: https://github.com/tarantool/tarantool/pull/11125.
> changelog: fix grammar in one changelog entry

- test/vinyl-luatest/gh_3638_defer_deletes_and_upserts_test.lua
- test/vinyl/errinj.result
- test/vinyl/errinj.test.lua
- test/vinyl/gh-3395-read-prepared-uncommitted.result
- test/vinyl/gh-3395-read-prepared-uncommitted.test.lua
- test/vinyl/suite.ini
Fix a few tests from the vinyl suites that has recently been reported as flaky.
Closes tarantool/tarantool-qa#202
> Fix a few flaky vinyl tests

- changelogs/unreleased/gh-10647-vy-pp-np-iterator.md
- src/box/box.cc
- src/box/index.cc
- src/box/index.h
- src/box/memtx_bitset.cc
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/sql.c
- src/box/sysview.c
- src/box/vinyl.c
- src/box/vy_read_iterator.c
- test/box/iterator.result
- test/box/iterator.test.lua
- test/engine-luatest/gh_9994_next_prefix_iterator_test.lua
See the doc ticket https://github.com/tarantool/doc/issues/4218 for the description of the 'pp' and 'np' iterators.
This PR basically copies the implementation of 'pp' and 'np' iterators from memtx.
Closes #10647
> vinyl: support PP/NP iterator type

- changelogs/unreleased/gh-10089-raft-meta-join.md
- changelogs/unreleased/gh-10846-fix-vinyl-replica-join-degradation-under-write-load.md
These changes were proposed during a preparation of the 2.11.6 release notes in gh-11188.
> [release/3.2] changelog: apply suggestions from @lenkis for 3.2

- changelogs/unreleased/gh-9965-wrong-numbers-comparison.md
These changes were proposed during a preparation of the 2.11.6 release notes in gh-11188.
> changelog: apply suggestions from @lenkis

- test/vinyl-luatest/select_consistency_test.lua
The test fails now and then on CI with:
```
[035] vinyl-luatest/select_consistency_test.lua                     [ fail ]
[035] Test failed! Output from reject file /tmp/t/rejects/vinyl-luatest/select_consistency.reject:
[035] Tarantool version is 2.11.7-entrypoint-10-g130294905b
[035] TAP version 13
[035] 1..2
[035] # Started on Thu Feb 27 09:21:34 2025
[035] # Starting group: vinyl.select_consistency.defer_deletes:false
[035] ok     1	vinyl.select_consistency.defer_deletes:false.test_select_consistency
[035] # Starting group: vinyl.select_consistency.defer_deletes:true
[035] not ok 2	vinyl.select_consistency.defer_deletes:true.test_select_consistency
[035] #   ...tarantool/test/vinyl-luatest/select_consistency_test.lua:296: expected: 675, actual: 1094
[035] #   stack traceback:
[035] # …
```
> test/vinyl/select_consistency: make garbage check more robust

- src/box/alter.cc
- src/box/errcode.h
- test/box/error.result
EE part: https://github.com/tarantool/tarantool-ee/pull/1179
> Refactoring needed for banning change of indexed fields by space upgrade

- changelogs/unreleased/gh-11171-fix-crash-on-oom-statement-rollback.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_engine.cc
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/txn.c
- src/box/txn.h
- src/lib/core/errinj.h
- test/box-luatest/memtx_oom_test.lua
- test/box/errinj_index.result
- test/box/errinj_index.test.lua
- test/fuzz/lua/test_engine.lua
Backport of https://github.com/tarantool/tarantool/pull/11395.
> [backport 3.3] memtx: handle OOM on statement rollback

- test/box-luatest/gh_8204_fast_offset_test.lua
The tests used to check a lot of key, iterator and offset combinations. This introduces a lot of useless overhead. Let's cover important cases explicitly instead. Let's separate selection consistency and conflict tests, rename `check_spaces' to `check_space' and drop some debugging artefacts by the way.
Closes #10774
NO_DOC=test update
NO_CHANGELOG=test update
> test: simplify the log(n) count and offset test

- changelogs/unreleased/gh-11180-wal-spurious-wakeup.md
- src/box/journal.c
- src/box/journal.h
- src/box/wal.c
- test/app-luatest/gh_7888_store_compiler_id_and_version_in_compiler_info_test.lua
- test/box-luatest/gh_11180_wal_spurious_wakeup_test.lua
- test/replication-luatest/gh_11180_wal_join_with_rollback_test.lua
This is a part of #11180. The ticket is going to be quite large. There are at least 8 bugs counted so far inside of it.
The idea is to submit fixes for them in portions, when possible. So they don't get stale and already fix some problems, while the next bugs are being fixed.
This MR is a part of #11605 which seems not to cause any questions and is highly unlikely to require any rework to fix the further bugs of #11180.
> WAL spurious wakeup bug

- src/box/journal.c
- test/box-luatest/gh_11180_wal_spurious_wakeup_test.lua
> WAL queue invalid previous entry fix

- .github/actions/install-deps-debian/action.yml
- .github/workflows/packaging_build_test_deploy.yml
- .gitignore
- debian/copyright
- test/CMakeLists.txt
- test/app-luatest/CMakeLists.txt
- test/app-luatest/gh_7311_malloc_info_test.lua
- test/app-luatest/gh_8782_yaml_decode_char_code_test.lua
- test/app-luatest/version_module_test.lua
- test/box-luatest/CMakeLists.txt
- test/box-luatest/gh_4349_transactional_ddl_test.lua
- test/box-luatest/gh_7231_memtx_hash_idx_gt_iter_deprecation_test.lua
- test/box-luatest/gh_7904_export_box_schema_version_to_public_api_test.lua
- test/box-luatest/gh_9309_errors_in_triggers_test.lua
- test/box-luatest/gh_9797_netbox_on_disconnect_error_hangs_server_test.lua
- test/box-luatest/ghs_135_check_iterator_when_loading_gc_consumers_test.lua
- test/box-luatest/iproto_request_handlers_overriding_test.lua
- test/box-luatest/memtx_mvcc_unsupported_features_test.lua
- test/config-luatest/CMakeLists.txt
- test/config-luatest/jsonschema_config_test.lua
- test/engine-luatest/CMakeLists.txt
- test/metrics-luatest/CMakeLists.txt
- test/replication-luatest/CMakeLists.txt
- test/replication-luatest/cluster_name_test.lua
- test/replication-luatest/gh_10088_apply_deletion_of_replica_from_cluster_on_deleted_replica_test.lua
- test/replication-luatest/instance_name_test.lua
- test/replication-luatest/replicaset_name_test.lua
- test/sql-luatest/CMakeLists.txt
- test/vinyl-luatest/CMakeLists.txt
The new test-run version is shipped without luatest so we have to install it from rocks.
> test: bump test-run to new version

- changelogs/unreleased/gh-10708-fix-setting-error-name.md
- doc/rfc/1148-stacked-diagnostics.md
- src/box/applier.cc
- src/box/errcode.h
- src/box/error.cc
- src/box/error.h
- src/box/index.cc
- src/box/index.h
- src/box/lua/error.cc
- src/box/memtx_engine.h
- src/box/recovery.cc
- src/box/user.cc
- src/lib/core/diag.h
- src/lib/core/exception.cc
- src/lib/core/exception.h
- test/app/fiber.result
- test/box-luatest/error_subsystem_improvements_test.lua
- test/box/error.result
- test/unit/error.c
- test/unit/mp_error.cc
Backport of https://github.com/tarantool/tarantool/pull/11747.
> [backport 3.2] box: fix setting box error name

- test/box-luatest/gh_10847_memtx_sort_data_test.lua
We used to have all supported and unsupported index types in different tests. This has a downside of slowing down the suite execution time as a lot of time is wasted during the Tarantool boot-up. This commit has merged some tests:
1. Supported and unsupported indexes are tested in `test_index_build`. This one creates local and vinyl spaces and does a few inserts in the WAL, so the corresponding separated tests are dropped.
2. The cases prohibiting the new SK build approach (index and space `before_replace` triggers, unexisting sort data file) are tested in `test_fallback_cases`.
3. Snapshot creation when one or both of .snap and .sortdata files are absent is tested in the `test_checkpoint` instead of separate tests.
4. The snapshot failures both on .snap write fail and .sortdata file …
> test: speed-up the sort data machinery test
