tarantool/tarantool

- src/box/iproto_port.cc
This will simplify client library construction cause it will allow to use
streaming MsgPack decoding.
If reply has variable part count, then request decoder which uses streaming
decoder, need to wait next part to analize: is it belongs to this reply
(body map) or start of next reply (ie length integer)? So that, if request
(ping) were single request, request decoder will stuck.
Even in case of non-streaming decoder, tarantool-python, for example, pays a price
of throwing and catching exception for ping request.
> make iproto answer to be 3 part even for ping

- include/fiber.h
- include/mutex.h
- src/admin.cc
- src/admin.rl
- src/box/box_lua.cc
- src/box/request.cc
- src/box/txn.cc
- src/coeio.cc
- src/coio.cc
- src/fiber.cc
- src/ipc.cc
- src/iproto.cc
- src/log_io.cc
- src/lua/bsdsocket.cc
- src/lua/init.cc
- src/lua/session.cc
- src/memcached-grammar.cc
- src/memcached-grammar.rl
- src/memcached.cc
- src/recovery.cc
- src/replica.cc
- src/replication.cc
- src/say.cc
- src/session.cc
- src/tarantool.cc
- src/util.cc
For use with gdb and avoidance of ambiguity with `struct fiber`
> Rename global `fiber` into `fiber_ptr`

- src/lua/msgpackffi.lua
This PR aims to fix an issue with packing boundary negative values, e.g. `-128` is packed as `d1ff80` instead of `d080`.
> Tweak msgpack.encode_int

- src/coio.cc
ev_io data get overwritten on the next line by ev_io_init
> Remove redundant coio_init call

- src/lib/salad/rope.c
You alredy checked if node is not NULL at string 640 in "if else" condition https://github.com/tarantool/tarantool/blob/1.7/src/lib/salad/rope.c#L640 so you don't really need to check it again
> The condition is redundant

- third_party/lua-cjson/lua_cjson.c
According to this issue: https://github.com/tarantool/tarantool/issues/1689, I've lost clean work with int64-types. Awfully sorry!
> Fix work with int64_t in lua-cjson.c

- src/box/index.cc
- src/box/index.h
- src/box/info.h
- src/box/lua/index.c
- src/box/lua/info.c
- src/box/lua/info.h
- src/box/lua/schema.lua
- src/box/vinyl.c
- src/box/vinyl.h
- src/box/vinyl_index.cc
- src/box/vinyl_index.h
- test/vinyl/coalesce.result
- test/vinyl/coalesce.test.lua
- test/vinyl/compact.result
- test/vinyl/compact.test.lua
- test/vinyl/ddl.result
- test/vinyl/ddl.test.lua
- test/vinyl/errinj_gc.result
- test/vinyl/errinj_gc.test.lua
- test/vinyl/gc.result
- test/vinyl/gc.test.lua
- test/vinyl/info.result
- test/vinyl/info.test.lua
- test/vinyl/recover.result
- test/vinyl/recover.test.lua
- test/vinyl/split.result
- test/vinyl/split.test.lua
- test/vinyl/update_optimize.result
- test/vinyl/update_optimize.test.lua
Extract and refactor vy_info implementation from Vinyl in order to implement index:info() introspection.
```
tarantool> box.space.vinyl.index.primary:info()
---
- page_size: 8192
size: 0
run_avg: 0
range_count: 1
run_histogram: '[0]:1'
page_count: 0
run_count: 0
memory_used: 3400
count: 100
range_size: 1073741824
...
```
Short history of previous reviews:
See #1662
> Implement index:info() introspection

- src/box/xlog.cc
- test/xlog/header.result
- test/xlog/header.test.lua
* Add `Version: 1.7.x` to XLOG header to use in the future versions.
* Add the test cases for XLOG header.
See #2100 and #2297
> Add Tarantool version to XLOG header

- src/box/lua/net_box.lua
- test/box/access_bin.result
- test/box/access_bin.test.lua
- test/box/function1.result
- test/box/function1.test.lua
- test/box/net.box.result
- test/box/net.box.test.lua
- test/replication/hot_standby.result
- test/replication/hot_standby.test.lua
Change conn:call() and conn:eval() API to accept Lua table instead of
varargs for function/expression arguments:
conn:call(func_name, arg1, arg2, ...)
=>
conn:call(func_name, {arg1, arg2, ...}, opts)
conn:eval(expr, arg1, arg2, ...)
=>
conn:eval(expr, {arg1, arg2, ...}, opts)
This breaking change is needed to extend call() and eval() API with
per-requests options, like `timeout` and `buffer` (see #2195):
c:call("echo", {1, 2, 3}, {timeout = 0.2})
c:call("echo", {1, 2, 3}, {buffer = ibuf})
ibuf.rpos, result = msgpack.ibuf_decode(ibuf.rpos)
result
Tarantool 1.6.x behaviour can be turned on by `call_16` per-connection option:
c = net.connect(box.cfg.listen, {call_16 = true})
c:call('echo', 1, 2, 3)
This is a breaking change for 1.7.x.
Needed for #2285
Closes #2195
> net.box: remove varargs from call() and eval()

- src/lua/init.c
* src/lua/init.c: Explicitly include <ctype.h>.
`isspace` is used in source. Normally <ctype.h> is included
through <readline/readline.h>, nut native `Readline` on OSX doesn't
include <ctype.h>.
> Explicitly include <ctype.h> in src/lua/init.c

- extra/dist/tarantool@.service.in
Using %I is incorrect, because it is a result of unescaping, but
escaping never occured.
Even if we would use escaping inside tarantoolctl, it would be
inconvenient to use systemctl to operate instances.
Fixes #2552, makes unneeded tarantool/doc#276.
> Fix inability to operate with instances containing dash in its names.

- src/lua/tap.lua
Implement ':isfunction()' test function  in Tap testing framework
that checks whether type of an argument is 'function'.
Closes #1859
> tap: add ':isfunction()' test function

- src/box/lua/console.c
Don't add to input history empty lines and two same lines together (to achieve behavior as in bash, python, etc.)
> Input history improvements.

- src/main.cc
With this changes stderr output may look like:
```
Segmentation fault
code: SEGV_MAPERR
addr: 0x14049f048
context: 0x7f2bcd01f840
siginfo: 0x7f2bcd01f970
rax      0xa                10
rbx      0x409e7960         1084127584
rcx      0xffffffb0         4294967216
rdx      0x4049f098         1078587544
rsi      0x0                0
rdi      0x7f2bcd01f870     139826099779696
rsp      0x7f2bcd01fdd0     139826099781072
rbp      0x4067c378         1080542072
r8       0x0                0
r9       0xa                10
r10      0x0                0
r11      0x246              582
r12      0x0                0
r13      0x0                0
r14      0x4067d000         1080545280
r15      0x4049f098         1078587544
rip      0x519b7d           5348221
eflags   0x10206            66054
cs …
```
> Details on SIGSEGV added

- src/lua/fio.lua
Empty strings should be ignored, rather than throw an error.
```lua
fio.pathjoin('foo', '', 'bar') -- "foo/bar"
```
**Note:** I have more changes coming. Please wait on merging this.
> fix(fio): empty path part in pathjoin

- .travis.mk
The reason of the failures is TLSv1.0/TLSv1.1 brownout on the PyPI side,
see [1] for more information.
[1]: pypa/packaging-problems#130
> Fix PyPI TLS connection failures in CI on OS X

- extra/dist/tarantoolctl.in
The subcommands are used to create binary rock distributions.
In context of #3525
> Add tarantoolctl rocks pack/unpack subcommands

- cmake/BuildLibYAML.cmake
No more `include/yaml.h` and `lib/libyaml_static.a` installs.
closes gh-3547
Also need to be merged into 1.10/2.0(?)
> Exclude install targets of libyaml from CMake

- extra/exports
- src/lua/init.h
- src/lua/utils.c
- src/lua/utils.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
* `lua_tostring`/`lua_tolstring` ignores metatable/boolean/nil and return NULL, but sometimes it's needed to have similar behaviour, like lua functions tostring. Lua 5.1 and LuaJIT ignores it by default, Lua 5.2 introduced auxilary function `luaL_to(l)string` with support of `__tostring`. This function is backport of Lua 5.1 "lauxlib.h"s `luaL_tostring` in the `luaT_` namespace.
* Using `luaT_tolstring` in conversion function, instead lua_tostring.
We can throw any Lua object as Lua error, but current behaviour won't convert it to string. So `diag` error's object will have `NULL`, instead of string.
`luaT_tolstring` honors `__tostring` metamethod and thus can convert table to it's string representation.
> Introduce luaT_tostring and use it in luaT_toerror

- extra/dist/tarantoolctl.in
Allow exploring rocks documentation locally with
`tarantoolctl rocks doc ...`
In context of #3753
> Add tarantoolctl rocks doc subcommand

- .editorconfig
Editorconfig is a standard of defining indentation style and other
settings such as newline types for different file types in a project.
See https://editorconfig.org/
It is achieved by introducing a simple .editorconfig dotfile with
glob expressions and settings per fiile type. Editors then can read
this file and decide which indentation style they should use for a
given project file.
Fixes #3892
> Add .editorconfig to properly detect indentation in editors

- README.md
The tarantool.org domain now redirects to tarantool.io, so I think the readme file should link to the new domain. Additionally, some of the older links were broken, leading to 404 pages - that should be fixed now.
> Update external links in README.md

- src/httpc.c
- src/httpc.h
- src/lua/httpc.c
- src/lua/httpc.lua
- test/app-tap/http_client.test.lua
- test/app-tap/httpd.py
Title: 'follow_location' http.client option
It allows disable follow location behavior used by default by set 0
For additional info see https://curl.haxx.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html
> Add option for disable follow location behavior

- src/lua/init.lua
- test/app/loaders.result
- test/app/loaders.test.lua
**Intro**:
By default, Lua uses package.path/cpath to load dependencies when user
calls `require("something")`. It also allows to add custom loaders to
extend its functionality. Tarantool transforms default behavior by
injecting some custom loaders into `package.loaders`.
Firstly, it allows to load modules from CWD. Secondly, it looks for
rocks modules starting from CWD and traversing up to root "/"
directory. This "start from CWD" behaviour is hardcoded and not
customizable.
**Problem**:
Let say we have a lua app with all dependencies under myapp directory.
If you start your application like this, you won't be able to load any
of them unless you specify myapp in every require call:
$ tarantool myapp/init.lua
To allow user scripts require dependencies relatively, user has to first …
> Let user define search root for packages

- src/main.cc
Notify socket used to be initialized during `box.cfg()`.
There is no apparent reason for that, because we can write tarantool
apps that don't use box api at all, but still leverage the event loop
and async operations.
This patch makes initialization of notify socket independent.
Instance can notify entering event loop even if box.cfg wasn't called.
Closes #4305
> tarantoolctl: always initialize notify_socket

- .travis.mk
- .travis.yml
travis-ci APT repository update failed on Debian 10 (Buster)
with command 'apt-get update', like:
Get:1 http://deb.debian.org/debian buster InRelease [118 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [46.8 kB]
Reading package lists... Done
N: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Version' value from '' to '10'
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: Repository 'http://deb.debian.org/debian buster InRelease' …
> travis-ci: apt-get fails to update the APT repos

- test/box/net.box.result
- test/box/net.box.test.lua
box/net.box test flaky failed on grepping the log file
for 'ER_NO_SUCH_PROC' pattern on high load running hosts,
found that the issue can be resolved by updating the
grep_log to wait_log function to make able to wait the
needed message for some time.
[008] Test failed! Result content mismatch:
[008] --- box/net.box.result	Tue Jul  9 17:00:24 2019
[008] +++ box/net.box.reject	Tue Jul  9 17:03:34 2019
[008] @@ -1376,7 +1376,7 @@
[008]  ...
[008]  test_run:grep_log("default", "ER_NO_SUCH_PROC")
[008]  ---
[008] -- ER_NO_SUCH_PROC
[008] +- null
[008]  ...
[008]  box.schema.user.revoke('guest', 'execute', 'universe')
[008]  ---
Closes #4329
> test: box/net.box test flaky fails on grep_log

- src/lua/init.c
- test/app-tap/info.test.lua
There is compile time option PACKAGE in cmake to define
current build distribution info. By default it's
"Tarantool" for the community version and "Tarantool Enterprise"
for the enterprise version.
It's displayed in console greeting and in `box.info().package`,
but, unfortunately, it can't be accessed from Lua before `box.cfg`.
This patch exposes `require('tarantool').package`.
Close #4408
> Expose tarantool_package value to lua api

- src/httpc.c
- src/httpc.h
- src/lua/httpc.c
- src/lua/httpc.lua
Added support for the following curl options:
* CURLOPT_PROXY
* CURLOPT_PROXYPORT
* CURLOPT_PROXYUSERPWD
* CURLOPT_NOPROXY
Title: httpc: proxy server options
Use 'proxy' option to specify the proxy server host or IP-address
(optionally may be prefixed with a scheme - e.g. http:// or https://).
'proxy_port' and 'proxy_user_pwd' options may be used to specify the
proxy port (443 for https proxy and 1080 for others by default) and
user credentials (format: [user name]:[password]) respectively.
If 'proxy' option is not set a value from the corresponding
environment variable will be used. Environment variable names are:
'http_proxy', 'https_proxy', 'ftp_proxy' etc. 'all_proxy' variable
is used if no protocol specific proxy was set.
Setting 'proxy' option to an empty …
> httpc: add proxy server options for curl

- Dockerfile.staticbuild
Found that 'openssl-1.1.0h' is EOL and its external link was removed.
Fixed static build based on Dockerfile with the new link to the external
openssl version 'openssl-1.1.1f'.
Close #4830
> build: Fix static build based on Dockerfile

- src/box/raft.c
- test/replication/gh-5426-election-on-off.result
- test/replication/gh-5426-election-on-off.test.lua
When an instance is configured as candidate, it has a leader death timer
ticking constantly to schedule an election as soon as leader disappears.
When the instance receives the leader's heartbeat, it resets the timer
to its initial value.
When being a voter, the instance ignores heartbeats, since it has
nothing to wait for. So its timer must be stopped. Otherwise it'll try
to schedule a new election and fail.
Stop the timer on transition from candidate to voter.
> raft: fix an assertion failure on transition to voter

- .github/workflows/coverity.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/luacheck.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
Due to current testing schema uses separate pipelines per each testing
job then workflow names should be the same as jobs to make it more
visible on github actions results page [1].
[1] - https://github.com/tarantool/tarantool/actions
> github-ci: set same workflow name as job

- .github/workflows/coverity.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/luacheck.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
Initially decided to use external module:
```
fkirc/skip-duplicate-actions
```
but after some additional investigation [1], decided to use simple check
```
github.event.pull_request.head.repo.full_name != github.repository
```
instead of this module. This solution was found in github.com/h2o/h2o
repository [2].
Co-authored-by: Alexander Turenko <alexander.turenko@tarantool.org>
[1] - https://github.com/tarantool/tarantool/pull/5638#discussion_r549248841
[2] - https://github.com/h2o/h2o/commit/1c79d79e8b7686145975bc1cb04201e78b875924
> github-ci: check the other way of duplication jobs

- .github/workflows/debian_11.yml
- debian/control
- tools/update_repo.sh
Allow packpack's build for Debian 11 (bullseye).
Make build dependency on dh-systemd optional, as this package is deprecated
and removed from Debian 11. It part of debhelper (>= 9.20160709) now.
No new dependencies, as tarantool already depends on debhelper (>= 9).
> Allow packpack's build for Debian 11 (bullseye)

- src/box/memtx_tx.c
Hotfix of 88b768005a492b956591c6a9a454f4305e75b0fa
Fix an obvious bug - tuple ref/unref manipulation must be done only
when we handle the primary index. Even code comment states that.
Part of #5628
> txm: fix tuple ownership strategy

- test/unit/fiber_channel.cc
Found issues building on Fedora 33:
```
test/unit/fiber_channel.cc: In function ‘fiber_channel_basic’:
test/unit/fiber_channel.cc:40:2: error: ‘ptr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
40 |  ok(ptr == &dummy, "fiber_channel_get()");
|  ^
test/unit/fiber_channel.cc:37:8: note: ‘ptr’ was declared here
37 |  void *ptr;
|        ^
test/unit/fiber_channel.cc: In function ‘fiber_channel_get’:
test/unit/fiber_channel.cc:63:2: error: ‘ptr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
63 |  ok(ptr == &dummy, "fiber_channel_get(0)");
|  ^
test/unit/fiber_channel.cc:61:8: note: ‘ptr’ was declared here
61 |  void *ptr;
|        ^
```
To fix the issue set ptr to NULL during initialization.
Needed for #5502
Part of #5697
> build: fix uninitialized ptr before use

- .gitlab-ci.yml
Found issue:
```
pkg: No packages available to install matching 'py27-yaml' have been found in the repositories
pkg: No packages available to install matching 'py27-gevent' have been found in the repositories
```
Happened at .travis.mk file target:
```
deps_freebsd:
sudo pkg install -y git cmake gmake icu libiconv \
python27 py27-yaml py27-six py27-gevent \
autoconf automake libtool
```
It happened because Python 2 is end of life and all OS distributions
changed to use Python 3. Also all repositories removed its copies of
the Python 2 packages.
Due to FreeBSD 12 is testing using VBox VM image which already has
all the needed Python 2 packages, the current fix is to change the
gitlab-ci job to use instead of 'test_freebsd' target, which calls
'deps_freebsd' target with calls to install …
> gitlab-ci: FreeBSD 12 lack of python 2 packages

- .gitlab-ci.yml
OSX 13 was tested for homebrew commit criteria. But a month ago
criteria list changed and OSX 13 was removed [1]. So we don't
need it any more in our commit criteria - removing.
[1] - https://github.com/Homebrew/homebrew-core/actions/runs/465259174
> gitlab-ci: remove OSX 13 from testing

- .github/workflows/coverity.yml
- .github/workflows/debian_11.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
Found that artifacts uses storage space which is limited to 0,5 GiB.
To avoid of lack of the space there decided to decrease the retention
days option for artifacts from default 90 days to 21 days (3 weeks).
> github-ci: decrease retention days for artifacts

- cmake/BuildZSTD.cmake
- static-build/test/static-build/exports.test.lua
**Use for master, 2.7, 2.6 release, branch:   avtikhon/gh-5502-fedora-33-zstd
use for 1.10 release, branch:                        avtikhon/gh-5502-fedora-33-zstd_1.10**
Found issue building on Fedora 33:
```
third_party/zstd/lib/decompress/zstd_decompress.c: In function ‘ZSTD_findFrameCompressedSize’:
third_party/zstd/lib/decompress/zstd_decompress.c:1502:18: error: ‘zfh.headerSize’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1502 |         ip += zfh.headerSize;
|                  ^
```
Also found that later releases of third_party/zstd submodule already
fixed it. Decided to bump third_party/zstd submodule from v1.3.3 to
v1.4.8. Added to zstd cmake build rules new files appeared on bumping.
**For master, 2.7, 2.6:**
Found that some checking in static-build …
> build: update cmake for zstd submodule build

- rpm/tarantool.spec
Enabled replication/ suite in packaging testing. After major number of
issues were resolved in test-run tool and in frequently failing flaky
tests replication/ suite can be tested within packaging testing.
Closes #4798
> test: enable replication/ suite in packaging

- .travis.mk
- debian/control
- rpm/tarantool.spec
After cURL was changed to use cmake in commit
2b07601922138fee02554ba69c989bee567e812e ('build: enable cmake in curl build')
there is no need to set dependencies to autotools. So removed it.
> build: remove autotools from builds

- rpm/tarantool.spec
Removed CentOS 6 from packages build jobs, due to it reached
end of lifetime [1].
[1] - https://wiki.centos.org/About/Product
> gitlab-ci: remove CentOS 6

- .github/workflows/fedora_33.yml
- rpm/tarantool.spec
- tools/update_repo.sh
1.    github-ci: add Fedora 33 to packaging
Added jobs for testing and deploying Fedora 33 packages.
Added Fedora 33 at update_repo tool to make able to save packages
in S3 buckets.
Closes #5502
2. build: enable packaging for Fedora 33
Since Python 2 was deprecated then new OS do not have repositories
with its packages. It is not good way to create all these packages
manually and store it as backported. Let's wait when Python 3 will
be used for testing and for now the testing disabled for Fedora 33
packaging.
Also found that %cmake macros used in build spec was changed - new
option was added:
-B x86_64-redhat-linux-gnu
It changed the build path and broke the build, to fix it these
options was additionally locally reset to:
-B .
Found that LTO was set by default in Fedora 33, check …
> github-ci: enable Fedora 33 packaging

- test/unit/swim_test_transport.c
Building on FreeBSD 12 using VM VBox with commands:
```
cmake . && gmake -j
```
got issue in test build:
```
[ 72%] Building C object test/unit/CMakeFiles/swim_proto.test.dir/swim_test_transport.c.o
/home/vagrant/tnt/test/unit/swim_test_transport.c:55:13: error: incomplete definition of type 'struct sockaddr'
assert(addr->sa_family == AF_INET);
~~~~^
/usr/include/assert.h:56:21: note: expanded from macro 'assert'
#define assert(e)       ((e) ? (void)0 : __assert(__func__, __FILE__, \
^
/usr/include/netinet/in.h:586:8: note: forward declaration of 'struct sockaddr'
struct sockaddr;
^
/home/vagrant/tnt/test/unit/swim_test_transport.c:55:28: error: use of undeclared identifier 'AF_INET'
assert(addr->sa_family == AF_INET);
^
2 errors generated.
gmake[2]: *** …
```
> build: FreeBSD no definition of 'struct sockaddr'

- CMakeLists.txt
- cmake/lto.cmake
- cmake/luajit.cmake
LTO wasn't enabled on Tarantool 1.10. Also was added packages build for Fedora 33 in:
[github-ci: add Fedora 33 to packaging](https://github.com/tarantool/tarantool/commit/44fcf3fef8e0ef38e74cc6907e85bdf88ac605f9)
which uses by default LTO in build. It broke the testing:
https://github.com/tarantool/tarantool/runs/1776978079#step:3:4134
with error:
```
/build/usr/src/debug/tarantool-1.10.9.16/src/reflection.h:124:33: error: type of ‘METHODS_SENTINEL’ does not match original declaration [-Werror=lto-type-mismatch]
124 | extern const struct method_info METHODS_SENTINEL;
|                                 ^
/build/usr/src/debug/tarantool-1.10.9.16/src/reflection.c:35:26: note: ‘METHODS_SENTINEL’ was previously declared here
35 | const struct method_info METHODS_SENTINEL = {
| …
```
> Enable LTO on 1.10 and disable 'lto-type-mismatch' warning on linking

- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/coverity.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/luacheck.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/source.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .gitlab-ci.yml
Added condition in gitlab-ci and github actions to skip testings
when branch names ends with '-notest'.
Removed jobs that already testing in Github Actions:
debug
release
release_clang
release_lto
release_lto_clang11
release_asan_clang11
osx_15_release
and templates:
deploy_*
> github-ci: skip testing on -notest branches

- .github/actions/send-telegram-notify/README.md
- .github/actions/send-telegram-notify/action.yml
- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/coverity.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/luacheck.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/source.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
Used Telegram public channel to send notifications for failed Github
Actions workflows. Created new Github Action based on Python:
.github/actions/send-telegram-notify/action.yml
with the ability to send messages in MarkdownV2 format [1]. To make
able to run standalone Github Action used its 'composite' type [2].
Also added ability to logout Github environment variables in this
action.
[1] - https://core.telegram.org/bots/api#markdownv2-style
[2] - https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
Result looks like the following markdown format message in Telegram:
----------------------------------------------------------------------
🔴 Workflow testing failed:
Job:  [release](https://github.com/tarantool/tarantool/actions/runs/533640919)
Commit: …
> github-ci: send Telegram notifications on failures

- .github/actions/environment/README.md
- .github/actions/environment/action.yml
- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/coverity.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
After commit ['test: update test-run (pass timeouts via env)'](https://github.com/tarantool/tarantool/commit/a598f3f5f73133d56b9e1782cda4a9051bf60af2)
The following variables added to github actions with testing:
```
REPLICATION_SYNC_TIMEOUT
TEST_TIMEOUT
NO_OUTPUT_TIMEOUT
```
and cumulative variable to pass environment to pack/deploy jobs:
```
PRESERVE_ENVVARS=REPLICATION_SYNC_TIMEOUT,TEST_TIMEOUT,NO_OUTPUT_TIMEOUT
```
These variables added within newly added local action:
```
.github/actions/environment
```
Patch really works - it can be seen that [environment variables were successfully set](https://github.com/tarantool/tarantool/pull/5785/checks?check_run_id=1828857435#step:5:3685)
> github-ci: add test-run timeouts to actions

- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_10_15_lto.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/out_of_source.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/static_build_cmake_osx_15.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .gitlab-ci.yml
- .travis.mk
1. Artifacts paths for pack/deploy/osx based jobs corrected.
2. Moved from gitlab-ci to github-ci 'default_gcc_centos_7' job for
building/testing Tarantool on default GCC installed in CentOS 7.
Removed not used after movement templates from gitlab-ci config.
3. Moved from gitlab-ci to github-ci 'out-of-source' job for
building/testing Tarantool in standalone build path while
source path is not writable.
4. Moved from gitlab-ci to github-ci 'static_build*' jobs for
building/testing Tarantool on Linux and OSX. Added targets
in .travis.mk file for static build on OSX on Github hosts.
5. Moved from gitlab-ci to github-ci 'osx_10_15_lto' job for
building/testing Tarantool on OSX with LTO.
> github-ci: move more jobs from gitlab-ci 2.x

- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_10_15_lto.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/static_build.yml
- .github/workflows/static_docker_build.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .gitlab-ci.yml
- .travis.mk
1. Artifacts paths for pack/deploy/osx based jobs corrected.
2. Moved from gitlab-ci to github-ci 'default_gcc_centos_7' job for
building/testing Tarantool on default GCC installed in CentOS 7.
Removed not used after movement templates from gitlab-ci config.
3. Moved from gitlab-ci to github-ci 'osx_10_15_lto' job for
building/testing Tarantool on OSX with LTO.
4. Moved from gitlab-ci to github-ci 'static_build' job for
building/testing Tarantool using build flag 'BUILD_STATIC=ON'.
5. Moved from gitlab-ci to github-ci 'static_docker_build' job for
building/testing Tarantool based on local 'Dockerfile.staticbuild'
docker build file. Set testing in make file instead of use from
docker file due to not possible to pass artifacts from it, check [1].
[1] - …
> github-ci: move more jobs from gitlab-ci 1.10

- .github/actions/send-telegram-notify/action.yml
1. github-ci: correct Telegram message for OSX
The processing of the message to be sent via Telegram is separated for
OSX and other platforms for two reasons:
* there is no need to wrap newline symbol with a single quote marks
* backslashes used in the message haven't to be escaped
2. github-ci: add link to log in Telegram message
The link to the failed job log is not saved in other GitHub Actions
links. At the same time this link can be obtained via the following
command using GitHub API:
$ curl -s https://api.github.com/repos/tarantool/tarantool/actions/runs/${{  github.run_id }}/jobs | jq -r '.jobs[0].html_url'
The obtained link for the particular run has the following format:
https://github.com/tarantool/tarantool/runs/<id\>, where 'id' is the
number of the job.
This link is added to …
> github-ci: add link to log in Telegram message

- .github/workflows/freebsd.yml
- .gitlab-ci.yml
Ported from gitlab-ci FreeBSD 12 build as a standalone Github
Actions workflow. Used sh4/sh8 local hosts as self-runners with
label 'freebsd-sh'. These hosts based on CentOS 7 with FreeBSD
12.1 installed in VBox VM. It was tried to use runners from
Github Actions which based on OSX, but failed to build FreeBSD 12
there, created additional issue to investigate the issue [1].
Closes #5754
[1]: https://github.com/tarantool/tarantool-qa/issues/81
> github-ci: port from gitlab-ci FreeBSD 12 build

- .github/workflows/jepsen-cluster-txm.yml
- .github/workflows/jepsen-cluster.yml
- .github/workflows/jepsen-single-instance-txm.yml
- .github/workflows/jepsen-single-instance.yml
- .gitlab-ci.yml
- .travis.mk
- tools/run-jepsen-tests.sh
Moved from gitlab-ci to github-ci 'jepsen*' jobs for
testing Tarantool with long Jepsen tests.
Closes tarantool/tarantool-qa#79
Found issues and resolved:
- Added '$PROJECT_BINARY_DIR/build/' path creation before use.
- Set always ssh-agent restart before add new SSH key, because
found that in some situations it may fail to add w/o it.
- Found mistake in TF_VAR_id variable setup, inverted ${CI_JOB_ID}
variable check for it.
Also made improvements in script:
- Added all needed checks for all externally set mandatory variables.
- Added usage message with the list of mandatory and optional variables.
- Added comments to all script steps.
- Added step with checking nodes that they are reachable by SSH.
Found issue:
```
root@hpalx:/source# make run-jepsen
[  0%] Performing update step for …
```
> github-ci: add jepsen* test jobs

- .github/actions/perf/README.md
- .github/actions/perf/action.yml
- .github/actions/send-telegram-notify/action.yml
- .github/workflows/perf_cbench.yml
- .github/workflows/perf_linkbench_ssd.yml
- .github/workflows/perf_nosqlbench_hash.yml
- .github/workflows/perf_nosqlbench_tree.yml
- .github/workflows/perf_sysbench.yml
- .github/workflows/perf_tpcc.yml
- .github/workflows/perf_tpch.yml
- .github/workflows/perf_ycsb_hash.yml
- .github/workflows/perf_ycsb_tree.yml
- .gitlab-ci.yml
Perf jobs checked at
https://github.com/tarantool/tarantool/runs/1913758190
Added Github local Action 'perf' to be used for perf docker images
preparations and benchmarks runs. Ported jobs from gitlab-ci:
- perf_cbench
- perf_linkbench_ssd
- perf_nosqlbench_hash
- perf_nosqlbench_tree
- perf_sysbench
- perf_tpcc
- perf_tpch
- perf_ycsb_hash
- perf_ycsb_tree
Closes #5663
Also made fix in Telegram action to avoid failure on packages installations.
Pip and jq installations may fail if the host is real, in this way it should be
manually pre-installed.
> github-ci: port perf jobs from gitlab-ci

- .github/workflows/jepsen-single-instance-txm.yml
- .github/workflows/jepsen-single-instance.yml
- .github/workflows/perf_cbench.yml
- .github/workflows/perf_linkbench_ssd.yml
- .github/workflows/perf_nosqlbench_hash.yml
- .github/workflows/perf_nosqlbench_tree.yml
- .github/workflows/perf_sysbench.yml
- .github/workflows/perf_tpcc.yml
- .github/workflows/perf_tpch.yml
- .github/workflows/perf_ycsb_hash.yml
- .github/workflows/perf_ycsb_tree.yml
Found that in commits:
c53c650e4c0b9c122e86767e45d073eb88b344bd ("github-ci: port perf jobs from gitlab-ci")
5c68884a6ea2d8807ffed0845e94fa64744c1d29 ("github-ci: add jepsen* test jobs")
was mistakenly missed "or" check "if:" condition, fixed.
Follows up #5663
Follows up tarantool/tarantool-qa#79
> github-ci: missed or symbol in if check (2.x & master)

- .github/workflows/perf_cbench.yml
- .github/workflows/perf_linkbench_ssd.yml
- .github/workflows/perf_nosqlbench_hash.yml
- .github/workflows/perf_nosqlbench_tree.yml
- .github/workflows/perf_ycsb_hash.yml
- .github/workflows/perf_ycsb_tree.yml
Found that in commits:
c53c650e4c0b9c122e86767e45d073eb88b344bd ("github-ci: port perf jobs from gitlab-ci")
5c68884a6ea2d8807ffed0845e94fa64744c1d29 ("github-ci: add jepsen* test jobs")
was mistakenly missed "or" check "if:" condition, fixed.
Follows up #5663
Follows up tarantool/tarantool-qa#79
> github-ci: missed or symbol in if check (1.10)

- .github/workflows/fuzzing.yml
- changelogs/unreleased/oss-fuzz-in-ci.md
Tarantool has been integrated to OSS-Fuzz infrastructure [1], and
implemented fuzzers are passed now [1]. Patch adds a new workflow that
will execute fuzzers on each push to a master branch using OSS-Fuzz
infrastructure [2]. To reduce a load on testing machines job triggers on
changes in directory with Tarantool's source code, fuzzers source code,
corpus files and GH Actions workflow file for fuzzing.
OSS-Fuzz provides web interface with fuzzing
statistics, found errors and other useful information. Access to OSS-Fuzz
UI is available for persons whose email addresses specified in
project.yml, committed to oss-fuzz repository [4]. Bugs found in OSS-Fuzz
reported to bugtracker [5].
Using fuzzing testing documented in Tarantool's wiki [6].
1. https://github.com/google/oss-fuzz/pull/4723
2. …
> github-ci: add workflow to run fuzzing testing

- .github/actions/perf/action.yml
Decided to use performance image with pre-installed benchmarks from
docker.io repository instead of gitlab-ci.
> github-ci: use perf image from docker.io

- src/CMakeLists.txt
- src/main.cc
- src/ssl_cert_paths_discover.c
- src/ssl_cert_paths_discover.h
- test/app-tap/ssl-cert-paths-discover.test.lua
The static build isn't as portable as it should be. In fact, the OPENSSLDIR is configured at build time, but in runtime, it may (and do) differ:
```
$ strace tarantool -e 'require("http.client").get("https://...")'
...
openat(AT_FDCWD, "/__w/sdk/sdk/build/tarantool/static-build/"
"openssl-prefix/ssl/cert.pem", O_RDONLY) =
-1 ENOENT (No such file or directory)
...
stat("/__w/sdk/sdk/build/tarantool/static-build/"
"openssl-prefix/ssl/certs/...", ...) =
-1 ENOENT (No such file or directory)
...
```
As a result, statically build tarantool can't open some https links with an error:
```
tarantool> http_client = require('http.client').new({max_connections = 5})
tarantool> http_client:get('https://..../', {verbose = true})
*   Trying X.Y.Z.W:443...
* TCP_NODELAY set
* Connected to .... (X.Y.Z.W) …
```
> Lookup openssl certs at tarantool startup

- src/lib/core/fiber.h
On my ARM system __CC_ARM is not defined. Checking whether we don't run on non-x86 may also make supporting other architectures (like POWER or RISC-V) easier.
> Properly check for non-x86 architectures

- src/box/lua/net_box.lua
- test/box/gh-5451-netbox-path-index-schema.result
- test/box/gh-5451-netbox-path-index-schema.test.lua
Seems previously "path" wasn't installed to index schema. This
patch fixes it and introduces a test.
Closes #5451
> netbox: add "path" to index schema

- src/ssl_cert_paths_discover.c
- test/app-tap/ssl-cert-paths-discover.test.lua
* Remove unnecessary `#include "tt_static.h"` from
src/ssl_cert_paths_discover.c
* Fix typo at test/app-tap/ssl-cert-paths-discover.test.lua
call `os.exit` instead of `os:exit`
A follow up on #5615
> ssl_cert_paths_discover: delete unused headers

- src/box/relay.cc
Changed aligned_alloc to posix_memalign because in some
macOS systems aligned_alloc function is not available.
> Change aligned_alloc to posix_memalign

- .github/actions/environment/action.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .travis.mk
github-ci: switch off swap use
Github Actions provides hosts for Linux base runners in the following
configurations:
```
2 Cores
7 Gb memory
4 Gb swap memory
```
To avoid of issues with hanging/slowing tests on high memory use
like [1], hosts configurations must avoid of swap memory use. All
of the tests workflows run inside dockers containers. This patch
sets in docker run configurations memory limits based on current
github actions hosts - 7Gb memory w/o swap memory increase.
Checked 10 full runs (29 workflows in each run used the change) and
got single failed test on gevent() routine in test-run. This result much
better than w/o this patch when 3-4 of workflows fail on each full run.
It could happen because swap began to be used after 40% of RAM was used:
```
cat …
```
> github-ci: switch off swap use

- .github/workflows/debug_coverage.yml
- .github/workflows/luacheck.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .travis.mk
Changed the following workflows:
```
luacheck
debug_coverage
release*
static_build
static_build_cmake_linux
```
It was changed the OS in which the test run from debian to ubuntu.
Also changed the way how this OS was booted - before the change it
was booted as docker container using Github Actions tag from inside
the worklfows. And it caused all the workflow steps to be run inside
it. After the change no container run anymore on the running host.
Github Actions host uses for now with its native OS set in 'runs'
tag. It was decided to use the latest one OS `ubuntu-20.04` which is
already the default for 'ubuntu-latest' tag.
This change gave us the abilities to:
- Remove extra container step in workflow.
- Switch off swap using 'swapoff' command.
- Use the same OS as Github Actions uses by …
> github-ci: avoid of use container tags in actions

- .travis.mk
Got warning message:
```
[014] WARGING: unix socket's "/home/ubuntu/actions-runner/_work/tarantool/tarantool/test/var/014_box/gh-5422-broken_snapshot.socket-iproto" path has length 108 symbols that is longer than 107. That likely will cause failing of tests.
```
It caused the following fail:
```
[038] Starting instance autobootstrap_guest1...
[038] Start failed: builtin/box/console.lua:865: failed to create server unix/:/home/ubuntu/actions-runner/_work/tarantool/tarantool/test/var/038_replication/autobootstrap_guest1.socket-admin: No buffer space available
```
To avoid of it use vardir option in tests runs to decrease paths length.
Closes tarantool/tarantool-qa#104
> github-ci: use vardir option in tests runs

- Dockerfile.staticbuild
Issue initially happened after commit:
6d220fede1a50dc7d3cbef1b9b810896e4026065 ('github-ci: switch off swap use')
Issue happened on docker build command:
https://github.com/tarantool/tarantool/runs/2255728324#step:4:14232
`Step 8/18 : RUN set -x && ... make -j && make install`
Failed like:
https://github.com/tarantool/tarantool/runs/2255728324#step:4:18129
```
make: *** [test_static_docker_build] Killed
.travis.mk:204: recipe for target 'test_static_docker_build' failed
```
Seems that w/o swap available happened OOM on ICU build. To avoid of
such situation better to limit the build with less parallel make.
Closes tarantool/tarantool-qa#109
> github-ci: static_docker_build fails on build icu

- changelogs/unreleased/fix-tuple-leak-in-lua-key_def.md
- src/box/lua/key_def.c
- test/box-tap/gh-5388-lua-key_def-leak.test.lua
- test/box-tap/key_def.test.lua
The key difference between lbox_encode_tuple_on_gc() and
luaT_tuple_encode() is that the latter never raises a Lua error, but
passes an error using the diagnostics area.
Aside of the tuple leak, the patch fixes fiber region's memory 'leak'
(till fiber_gc()). Before the patch, the memory that is used for 
serialization of the key is not freed (region_truncate()) when the 
serialization fails. It is verified in the gh-5388-<...> test.
While I'm here, added a test case that just verifies correct behaviour
in case of a key serialization failure (added into key_def.test.lua).
The case does not verify whether a tuple leaks and it is successful as
before this patch as well after the patch. I don't find a simple way to
check the tuple leak within a test. Verified manually using the 
reproducer …
> lua: fix tuple leak in <key_def>.compare_with_key

- .github/actions/environment/action.yml
We should remove a tag after fetching of a remote repository.
Ported the following commits:
0f575e01a20a2da76d73e72e77f6ebd0080ef1b1 ('gitlab-ci: fix tag removal for a branch push job')
0f564f3497e6a8afd42da2175104118ba5213593 ('gitlab-ci: remove tag from pushed branch commit')
Drop a tag that points to a current commit (if any) on a job triggered
by pushing to a branch (as against of pushing a tag). Otherwise we may
get two jobs for the same x.y.z-0-gxxxxxxxxx build: one is run by
pushing a branch and another by pushing a tag. The idea is to hide the
new tag from the branch job as if a tag would be pushed strictly after
all branch jobs for the same commit.
Closes tarantool/tarantool-qa#103
> github-ci: drop not needed tag on branches commits

- test/box/gh-5422-broken_snapshot.result
- test/box/gh-5422-broken_snapshot.test.lua
Test checks the possibility of recovery with force_recovery option.
For these purpose, snapshot is damaged in test and possibility of
recovery is checked. In previous version snapshot damaged during
server worked, which sometimes made it impossible to recover.
Since such scenario is not considered, now snapshot corruption
occurs only when server is turned off.
Follow-up #5422
Related QA issue: https://github.com/tarantool/tarantool-qa/issues/93
> Fixed force_recovery test.

- .github/workflows/coverity.yml
Workflow 'coverity' produces and uploads results to 'coverity.com' web
site. Message about it can be shown in PR within each run was done.
This patch adds the ability to send message in available PR otherwise
it is skipped.
Part of #5644
> github-ci: add result message from coverity in PR

- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/coverity.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/luacheck.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/out_of_source.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/source.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
For self-host runners, where work path with sources is saving between
different workflows runs, it is needed to be sure that all permissions
correct for running user to be sure that later call to sources checkout
by 'actions/checkout' action run by the same user won't fail on sources
cleanup.
Closes tarantool/tarantool-qa#102
> github-ci: add work path permissions correction

- tools/update_repo.sh
Found that running package removement command from S3:
`  ./tools/update_repo.sh -o=fedora -d=30 -b=s3://tarantool_repo/live/1.10 -r=tarantool-1.10.9.108`
it searched to remove:
`  Searching to remove: s3://tarantool_repo/live/1.10/fedora/30/SRPMS/Packages/tarantool-1.10.9.108-1.fedora30.src.rpm`
while it had to be:
`  Searching to remove: s3://tarantool_repo/live/1.10/fedora/30/SRPMS/Packages/tarantool-1.10.9.108-1.fc30.src.rpm`
where 'fc30' had to be instead of 'fedora30'. This patch fixes it.
> update_repo: fix remove functionality for fedora

- .github/actions/environment/action.yml
- .github/actions/pack_and_deploy/README.md
- .github/actions/pack_and_deploy/action.yml
- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/fedora_28.yml
- .github/workflows/fedora_29.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .gitlab.mk
- tools/update_repo.sh
Patch set consists of 2 commits:
1. Created local composite action 'pack_and_deploy' for Tarantool packages
creation and deployment. It was created using local scripts in packages
workflows. It let to change common parts of packages creations and
deployment in each packaging workflow to call for this action. It helped
to consolidate all the instructions on packages creation and deployment
in a single place.
2. Enabling ubuntu-20.04 hosts for packaging workflows found that DEB
package Github Actions workflows do not need to install createrepo
tool. Also found that createrepo is not ready for ubuntu-20.04 as
described in (till ubuntu-21.04 where it is available as the new
version of this tool named as 'createrepo_c' as DEB package):
3a7c21023367424baa9bf2d4d823102cb2b3c751 ('github-ci: …
> github-ci: enable ubuntu-20.04 hosts for packaging

- .github/actions/environment/action.yml
For self-hosted runners run w/o restart may need to kill hanged
processes that could be leaved from the previous workflows runs.
This patch implements in cleanup with kill for such processes in
'environment' actions which is called for all workflows and runs
before main steps. Cleanup searches for two names patterns of
running processes:
- ' tarantool '
- 'test-run.py '
Closes tarantool/tarantool-qa#114
> github-ci: kill hanged processes on self runners

- changelogs/unreleased/fix-cmake3-build.md
- cmake/BuildLibCURL.cmake
`cmake` command was hardcoded for configuring libcurl, however only
`cmake3` may be installed in a system. Now we use the same cmake command
for configuring libcurl as one that is used for configuring tarantool
itself.
The problem exists since 2.6.0-196-g2b0760192 ('build: enable cmake in
curl build').
Fixes #5955
> build: fix configuring using cmake3 command

- .github/actions/environment/action.yml
gitub-ci: add more cleanup for running WS
Found that 'actions/checkout' does not remove all temporary files from
previous runs in submodules [1], it runs only 'git clean -xffd' [2]:
```
libgcov profiling error:/home/ubuntu/actions-runner/_work/tarantool/tarantool/src/lib/small/CMakeFiles/small.dir/small/small_class.c.gcda:overwriting an existing profile data with a different timestamp
```
To avoid of it added:
```
git submodules foreach --recursive 'git clean -xffd'
```
to 'actions/environment' which is run after each 'actions/checkout'.
Part of #5986
[1]: https://github.com/tarantool/tarantool/runs/2318244478?check_suite_focus=true#step:5:4012
[2]: https://github.com/actions/checkout/issues/358
> github-ci: add more cleanup for running WS

- src/box/memtx_engine.c
- test/box/gh-5610-dirty-restart.lua
- test/box/gh-5610-dirty-restart.result
- test/box/gh-5610-dirty-restart.test.lua
Usually during final recovery, when .xlog files are loaded and
applied, a special memtx_space_replace_primary_key function is
used for faster recovery. The function only updates primary key
while all other indexes are scheduled to build at the end of
recovery.
This approach doesn't work with MVCC engine and synchro spaces:
When transactions appear in xlog and they may or may not be
committed, we should process the in normal mode throught all
indexes in order to leave transaction history in each index.
Fixes #5610 #5973
> txm: switch to normal mode earlier durion recovery with MVCC

- asan/lsan.supp
Found that after patch set of 5 commits:
aa97a18575a5fba29550e131c4764b81841612b9 ("feedback_daemon: count and report some events")
e9c9832a0f3635fa0179a2cc1bfd334dea8cdc64 ("feedback_daemon: generate report right before sending")
bc15e0f070c89e00cd76b0432d906697aae25202 ("feedback_daemon: send feedback on server start")
670acf0d163436a6853dc54d521ff7f037acba8d ("feedback_daemon: rename `send_test` to `send`")
c5d595bcae1a539604895b186cdda86a212909e8 ("feedback_daemon: include server uptime in the report")
began to leak feedback demon on using cURL. To avoid of it decided to
add LSAN suppresions:
1. for /lib/x86_64-linux-gnu/libcrypto.so
leak:libcrypto.so*
2. for /lib/x86_64-linux-gnu/libssl.so
leak:libssl.so*
Needed for tarantool/tarantool-qa#116
> test: ASAN leak on feedback demon call using cURL

- .travis.mk
Changing the way of running debug build with coverage collecting at
tarantool/tarantool#5949 was found that for paths based on src/ root
directory make routine automatically adds additional src/ directory
prefix in the meta data path at creating .gcda files for src/ paths.
Issue was found running 'lcov' tool command which collects results
from "*.gcda" files:
```
Processing lib/uri/CMakeFiles/uri.dir/uri.c.gcda
Cannot open source file src/lib/uri/uri.rl
Cannot open source file src/lib/uri/uri.c
```
To fix it was added workaround - created link to the needed path before
'lcov' call for master and 2.x:
`  ln -s ${PWD}/src src/lib/uri/src`
but on Tarantool 1.10 it should be:
`  ln -s ${PWD}/src src/src`
This patch fixes it for Tarantool 1.10 branch.
Follows up tarantool/tarantool-qa#101
> build: coverage needs workaround with link

- debian/control
- rpm/tarantool.spec
The reason of the update is to protect us against possible MITM attack
from a malicious HTTPS proxy server with trusted certificate when TLS
1.3 is used ([CVE-2021-22890][1]). libcurl versions prior to 7.76.0 can
skip a TLS handshake with a target host in this circumstances.
Other vulnerabilities fixed in the (7.71.1; 7.76.0] version range do not
look relevant to our built-in http client. See [here][2] for the full list.
The CMake version requirement is updated from 3.1 to 3.2, because curl's
CMakeLists.txt has the following clause at beginning:
```cmake
cmake_minimum_required(VERSION 3.2...3.16 FATAL_ERROR)
```
(It was there in vanilla curl 7.71.1 too and we had to remove it in
order to support CMake 2. Now we don't support CMake 2, so it is good
time to get rid of the extra patch upward …
> security: update libcurl from 7.71.1 to 7.76.0

- src/box/xrow_update_array.c
- src/box/xrow_update_field.c
- src/box/xrow_update_field.h
- test/engine/update.result
- test/engine/update.test.lua
tuple: do not allow autofill of nested arrays with nulls
In previous version there was inconsistent/ behaviour for update
operations to nested arrays. When user try to update non existent
field of nested array along with previous update existent field,
it's works, otherwise no. For example we create tuple and two
update operations:
`t = box.tuple.new({1, 2, {11, 22}})`
`op1 = {'=', '[3][1]', 11}`
`op2 = {'=', '[3][4]', 44}`
Then in case we apply operations separately `t:update({op1})` and
then `t:update({op2})`, second operation fails but is case we apply
them together t:update({op1, op2}) they both complete successfully.
Follow up #3378
> update: don't allow to autofill with nulls not root array

- test/box/alter.result
- test/box/alter.test.lua
- test/box/alter_limits.result
- test/box/alter_limits.test.lua
- test/box/ddl_collation.result
- test/box/ddl_collation.test.lua
- test/box/sequence.result
- test/box/sequence.test.lua
ER_TUPLE_FOUND error message depends on the previous tests, so we can
just check error code in these tests to avoid it.
> Fix nondeterminism of ER_TUPLE_FOUND error

- src/lib/core/errinj.h
- src/lua/init.c
Our coverity (scan.coverity.com) reports about dead code (CWE-561)
in cases where variable of type `struct errinj *` is compared with
NULL at if condition. Dead code appears due to function-like macro
`errinj()` always returns NULL at non-debug version, so execution
never goes into if block.
Added macroses ERROR_INJECT_INT and ERROR_INJECT_DOUBLE which solves
this problem like it does ERROR_INJECT macro with boolean errinj type.
Usage you can see on example of ERRINJ_STDIN_ISATTY fix in this commit.
Follows up #5040
> coverity: add errinj macroses to fix dead code

- .gitlab.mk
To trigger release packages creation on tagged commits need to check
GITHUB_REF environment variable if it starts with 'refs/tags/' prefix.
> github-ci: trigger release packages creation

- changelogs/unreleased/gh-6069-json-update-crash.md
- src/box/xrow_update_array.c
- test/box/update.result
- test/box/update.test.lua
Update of an absent field could crash when had 2 operations in
reversed order both on not specified fields.
The problem was that the rope item was created incorrectly.
Rope item is a range of array fields and consists of 2 parts:
xrow_update_field and a tail. The xrow field should describe
exactly one array field (first in the given range) and its update
operation. When no operation, it is NOP.
The tail includes the rest of the array fields not affected by
any operations yet.
But in the code it was so the rope item was created with its xrow
field covering multiple array fields, and with zero tail. As a
result, split of that item didn't work because it can't split an
xrow field.
The bug was in the nil-autofill for absent array fields. The patch
fixes it so the newly created item with nils …
> tuple: fix crash in reversed nullable json update

- third_party/coro/coro.c
There are a few issues concerning build of coro on Mac M1.
Firstly, Mach-O assembler does not support .type directive. So let's put
it under ifndef __APPLE__ preprocessing guard.
Secondly, for some reason linker fails to resolve unmangled symbols
referenced in inlined assembly:
Undefined symbols for architecture arm64:
"_coro_startup", referenced from:
_coro_create in libcoro.a(coro.c.o)
The same concerns "abort" function call. I suspect that clang by default
mangle each function's name with "_" (in GCC this option can be turned
on/off by -f[no]leading-underscore). So to call function from assembly
inline we have to specify exact name (i.e. mangled). However, in case of
user-defined function, we can force function name placing asm() after
its declaration. Still have to patch abort name. …
> build: fix coro build for Apple ARM M1

- .github/workflows/debug_coverage.yml
- .travis.mk
Workflow 'debug_coverage' produces and uploads results to 'coveralls.io'
web site. Message about it can be shown in PR within each run was done.
This patch adds the ability to send message in available PR otherwise it
is skipped. Also added 'coverage.info' file to artifacts list.
Found that used 'coverallsapp/github-action' action checks if the
trigger was 'pull_request' used to run the workflow [1]. And only in
this way it writes results message to PR. Previously 'pull_request'
trigger was blocked to avoid duplication with 'push' trigger. To make
able to run workflow by any single trigger and to send message to PR
if it exits, it was implemented the following logic:
- run workflows on both triggers 'push' and 'pull_request';
- for workflow with 'push' trigger check if PR exists then skip …
> github-ci: add result message from coveralls in PR

- tools/run-jepsen-tests.sh
Script used to run Jepsen tests uses Terraform to prepare test environment.
When I made this script I had a wrong assumption about working directory
used by Terraform. Due to this sometimes job with Jepsen tests
failed on cleanup with message:
```
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
Failed to instantiate provider …
```
> tools: fix script to run jepsen tests

- changelogs/unreleased/gh-5799-add-info-to-fiber-object.md
- changelogs/unreleased/gh-5799-set-csw-is-0-for-new-fibers.md
- src/lib/core/fiber.c
- src/lua/fiber.c
- test/app/gh-5799-fiber-info.result
- test/app/gh-5799-fiber-info.test.lua
Add `fiber_object:csw()` function to get `csw` from both alive or dead fiber.
Add `fiber_object:info()` function to get `info` from alive fiber.
> fiber: add fiber_object:csw() and fiber_object:info() functions

- test/app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua
- test/app-tap/gh-5040-inter-mode-isatty-via-errinj.test.lua
Occasionally, test/app-tap/gh-5040-inter-mode-isatty-via-errinj.test.lua
failed because it used output file with the same name as
test/app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua and the last one
didn't remove file after usage.
Added removal of output file to test for 4983 and also changed file names
to distinguish outputs of these tests better in case of failure.
Fixes tarantool/tarantool-qa#122
> test: fix flaky tests for -e and iteractive mode

- .github/actions/environment/action.yml
- .github/actions/send-telegram-notify/action.yml
Patch set consists of 4 commits:
1. github-ci: port send-telegram-notify to python3
For now python3 is used as the default python on all OS and it is
needed to enable it in send-telegram-notify action.
Found issue:
```
Traceback (most recent call last):
File "<string>", line 3, in <module>
AttributeError: module 'urllib' has no attribute 'quote_plus'
```
In Python 3 quote_plus included into urllib.parse.
Check documentaion [1]:
```
Note The urllib module has been split into parts and renamed in Python 3 to urllib.request, urllib.parse, and urllib.error.
```
Check the same issue [2].
This patch changes use of all needed routines just from 'urllib'.
Closes tarantool/tarantool-qa#112
[1]: https://docs.python.org/2/library/urllib.html
[2]: https://github.com/web2py/web2py/issues/1822
2. …
> github-ci: port send-telegram-notify to python3

- changelogs/unreleased/fix-error-on-return-bin-from-funcs.md
- src/box/sql/mem.c
- test/sql-tap/CMakeLists.txt
- test/sql-tap/gh-6024-funcs-return-bin.c
- test/sql-tap/gh-6024-funcs-return-bin.test.lua
This patch-set allows VARBINARY to be returned for user-defined functions. For user-defined LUA functions there is no values that can be interpreted as VARBINARY by serializer, so the only way to return VARBINARY is to return a DECIMAL or UUID, since both types are not supported by SQL and treated as VARBINARY.
Closes #6024
> sql: VARBINARY result for user-defined C functions

- changelogs/unreleased/add-check-for-user-input-of-the-number-of-iproto-threads.md
- changelogs/unreleased/fix-undeleted-unix-socket-path-and-multiple-socket-closing.md
- src/box/box.cc
- src/box/box.h
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/cfg.cc
- src/lib/core/evio.c
- src/lib/core/evio.h
- test/box/box-cfg-unix-socket-del.lua
- test/box/box-cfg-unix-socket-del.result
- test/box/box-cfg-unix-socket-del.test.lua
- test/box/gh-5645-several-iproto-threads.lua
- test/box/gh-5645-several-iproto-threads.result
- test/box/gh-5645-several-iproto-threads.test.lua
- test/box/net.box_reconnect_after_gh-3164.result
- test/box/net.box_reconnect_after_gh-3164.test.lua
At the moment, user can set any number of iproto threads, which leads
to incorrect behavior if the specified number of threads is less than
or equal to zero or too large. Add check for user input of the number
of iproto threads, value must be > 0 and less then or equal to 1000.
Follow-up #5645
> iproto: add check for user input of the number of iproto threads

- src/box/vy_tx.c
- test/vinyl/gh-5934-dupicate-tx-writers.result
- test/vinyl/gh-5934-dupicate-tx-writers.test.lua
Subj. Turns out that commit (59fed2d1d567c5d49d09d006777261ede34f8e6c) in master already fixes this problem. So let's simply cherry-pick it and add corresponding test.
Test case can be also cherry-picked to master branch.
Closes #5934
> vinyl: fix adding the same tx twice to the list of writers

- .github/workflows/osx_10_15.yml
- .github/workflows/osx_10_15_lto.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/osx_arm64_11_2.yml
- .github/workflows/osx_debug_arm64_11_2.yml
- .travis.mk
Added new Github Action workflow to check the M1 with Tarantool builds:
```
Release: .github/workflows/osx_arm64_11_2.yml
Debug: .github/workflows/osx_debug_arm64_11_2.yml
```
Added in Github Action workflow prefix to run all commands from
makefile 'arch -arm64', otherwise found that Github Action uses
'arch -x86_64' prefix by default.
In .travis.mk makefile created new targets to test Tarantool
on M1:
```
Release: test_osx_arm64_github_actions
Debug: test_osx_debug_arm64_github_actions
```
Also added test target 'test_osx_arm64_only' with LuaJIT test target:
```
PUC-Rio-Lua-5.1-tests
```
Found that on M1 hosts running python3 installation python3.9 is
installing by default. But we need to install gevent as test
required package, which fails to be installed with python3.9.5
and …
> github-ci: add build check on M1 with ARM64

- test/replication/suite.ini
- test/replication/transaction.result
- test/replication/transaction.test.lua
On heavy loaded hosts found the following issue:
[046] --- replication/transaction.result	Wed Sep 30 17:19:32 2020
[046] +++ /tmp/tnt/rejects/replication/transaction.reject	Tue Nov 24 04:39:29 2020
[046] @@ -234,7 +234,7 @@
[046]  ...
[046]  box.info.replication[1].upstream.status
[046]  ---
[046] -- follow
[046] +- disconnected
[046]  ...
[046]  test_run:cmd("switch default")
[046]  ---
[046]
It happened because box.cfg was not ready to provide information. In
real there is no need to use local check for replication information
parts availablity, due to wait_upstream() function used below, do it
itself.
Closes #5563
> test: fix status check in replication/transaction

- test/replication/election_basic.result
- test/replication/election_basic.test.lua
- test/replication/suite.ini
Found that on slow test hosts like FreeBSD VMware test flaky failed, like:
[001] @@ -153,7 +153,7 @@
[001]   | ...
[001]  assert(leader_count == 1)
[001]   | ---
[001] - | - true
[001] + | - error: assertion failed!
[001]   | ...
[001]  -- All nodes have the same leader.
[001]  r1_leader = test_run:eval('election_replica1', leader_id_cmd)[1]
It happened because there was not enough time right after wait_fullmesh()
call and before check of the current leader to make any of the replicas
leader. Later in the code was not correct logic when checked who is the
leader and choosed 'election_replica3' if not the others, it caused the
later fails in the test. Decided to wait after wait_fullmesh() when any
of the replicas became leader using test_cond() routine.
Closes #5368
> test: flaky election_basic.test.lua test

- test/vinyl/gh.result
- test/vinyl/gh.test.lua
- test/vinyl/suite.ini
Found that in one previous commit
```
42c64d06d5d1a3ec937b3c596af083a672a68ad8 ('test: fix hanging of vinyl/gh.test.lua')
```
Was mistakenly made such change:
```
-while finished ~= 2 do fiber.sleep(0.01) end
+test_run:wait_cond(function() return finished ~= 2 end)
```
And the logic of the check was broken. This patch fixes it.
Part of #5141
Fixes tarantool/test-run#261
Part of tarantool/tarantool-qa#106
> test: vinyl/gh.test.lua fix mistake

- cmake/BuildZSTD.cmake
Seems CMakeLists.txt contains the same line as inside
BuildZSTD.cmake. Seems we don't need to duplicate this logic
twice let's remove it.
> build: cleanup BuildZSTD.cmake

- .github/actions/environment/action.yml
- .github/workflows/coverity.yml
- .github/workflows/debug_coverage.yml
- .github/workflows/freebsd.yml
- .github/workflows/osx_10_15.yml
- .github/workflows/osx_10_15_lto.yml
- .github/workflows/osx_11_0.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang11.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang11.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/static_build_cmake_osx_15.yml
- .gitlab.mk
Found that after change:
474eda49b90176406eac6684c8b502e05e49af04 ('github-ci: use vardir option in tests runs')
where 'vardir' was changed. It was forgot to update the Github Actions
workflows with the same change to be able to collect artifacts. This
patch fixes it.
Closes tarantool/tarantool-qa#125
> github-ci: correct artifacts paths

- test/box/suite.ini
- test/engine/suite.ini
- test/vinyl/suite.ini
1.     test: remove fixed tests from fragile lists
Checked and found that:
#4353 -> tarantool/tarantool-qa#13:
engine/ddl.test.lua fixed in #6102.
#4926, tarantool/tarantool#115:
box/alter_limits.test.lua fixed in
tarantool/tarantool-qa#126.
#5547 -> tarantool/tarantool-qa#50:
box/net.box_schema_change_gh-2666.test.lua fixed in
tarantool/tarantool-qa#126.
#5583 -> tarantool/tarantool-qa#22:
box/net.box_methods_gh-3107.test.lua fixed in
tarantool/tarantool-qa#126.
Closes tarantool/tarantool-qa#13
Closes tarantool/tarantool-qa#115
Closes #4926
Closes tarantool/tarantool-qa#50
Closes tarantool/tarantool-qa#22
2. test: unblock vinyl tests from fragile list
Found that the root cause of the issues happened with vinyl tests were
backside effects of the not correct test 'vinyl/gh.test.lua' which …
> test: unblock tests from fragile list after fix with Tarantool server restart

- changelogs/unreleased/gh-4235-dont-show-idle-in-fiber-info.md
- src/lib/core/fiber.h
- src/lib/core/fiber_pool.c
- src/lua/fiber.c
- test/app/gh-4235-dont-show-idle-in-fiber-info.result
- test/app/gh-4235-dont-show-idle-in-fiber-info.test.lua
`FIBER_IS_IDLE` flag is added to track fibers from fiber pool.
These fibers are still present in the `fiber.info` but without their stacks. 
Closes #4235
> fiber: hide backtraces of idle fibers from fiber.info

- .github/workflows/odroid_arm64.yml
- .github/workflows/odroid_debug_arm64.yml
- .travis.mk
Odroid is GNU/Linux ARM64 platform. In scope of this commit new GitHub
Actions workflows for testing Tarantool on Odroid hosts are added:
```
Release: .github/workflows/odroid_arm64.yml
Debug: .github/workflows/odroid_debug_arm64.yml
```
Introduced new targets in .travis.mk Makefile:
```
deps_odroid: Installs needed dependencies.
build_odroid: Builds Tarantool with the following flags set
in env of .github/workflows/odroid_debug_arm64.yml file:
1. to avoid of issue #6142:
-DENABLE_BACKTRACE=OFF
2. to avoid of issue #6143:
-DCMAKE_C_FLAGS="-Wno-type-limits "
-DCMAKE_BUILD_TYPE=Debug
test_odroid: Builds and tests on Odroid `LuaJIT-test` suite.
```
Also v1 version of GitHub checkout action is used, because action
version v2 was introduced in git version 2.18.0 [1]. The latest
available …
> github-ci: add GitHub Actions workflow for Odroid

- src/box/memtx_engine.c
- test/box/gh-5422-broken_snapshot.result
- test/box/gh-5422-broken_snapshot.test.lua
In the test, there is a place, where it was checked that the amount
of valid data in snapshot in case when it was truncated is less than
in case we write garbage to it. Often it's really so, but depends on
the place of truncation/garbage location. Removed this check, because
on different systems, snapshot size is slightly different each time
you run test, so check will not pass every time.
Follow-up #5422
> test: fix flaky force_recovery test

- changelogs/unreleased/gh-6131-fix-crash-update-conflict.md
- src/box/memtx_tx.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
The problem was in case when mvcc engine was enabled and a transaction
that was sent to read view due to conflict was trying to read a key that
was the cause of the conflict.
Closes #6131
> txm: fix a crash in conflict collection

- src/box/memtx_engine.c
- src/box/memtx_space.c
- src/box/memtx_tx.c
- src/box/vinyl.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
With MVCC a case may happen:
TX1 does something with some space and yields.
TX2 deletes the space and commits.
TX1 rolls back.
The problem was that TX1 does something with already deleted space.
This commit fixes that.
Part of #6140
After merge the issue must remain open
> txm: fix a crash in rollback when the space was deleted

- src/lib/core/backtrace.cc
Fix build errors on arm64 when backtraces being enabled.
**Q:** Will it always work?
**A:** No, most probably it'll crash somewhere inside libunwind. This is due to the bug in libunwind, fixed not so long ago in https://github.com/libunwind/libunwind/pull/221 and not yet even released, not to mention availability in various distributives.
But with current libunwind master it gives nice and shiny backtrace:
Code:
```
local fiber = require ('fiber')
local log = require('log')
log.error(fiber.info())
```
Result:
```
{
"102":{
"csw":0,
"backtrace":[
],
"fid":102,
"memory":{
"total":516448,
"used":0
},
"name":"on_shutdown"
},
"101":{
"csw":1,
"backtrace":[
{
"C":"#0  0x7d9d1c29548 in +116"
}
],
"fid":101,
"memory":{
"total":516448,
"used":0
},
"name":"lua"
},
"103":{
"csw":1,
"backtrace":[
{ …
```
> build: Fix build with backtraces enabled on arm64 (aarch64)

- changelogs/unreleased/gh-6193-assertion-with-mass-replace.md
- test/box/tx_man.result
- test/box/tx_man.test.lua
The problem was fixed in #5515, this commit just verifies that the
test case works fine.
Closes #6193
> txm: add a test that makes tons of concurrent replaces

- changelogs/unreleased/gh-6229-crash-in-snapshot-with-uncommitted-transaction.md
- src/box/memtx_tx.c
- test/box/tx_man_recovery.result
- test/box/tx_man_recovery.test.lua
At some point memtx_tx_tuple_clarify_slow was changed in terms of
its signarure - index ID was replaced with pointer to index.
Unfortunately one of calls of this function was not fixed - zero
was passed as index ID which compiles successfully with the new
API.
This patch fixes that place as well and adds a bunch of tests.
Closes #6229
> txm: fix memtx_tx_tuple_clarify_slow call args

- src/box/memtx_tx.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
Read gap is a fact that a search by key in index found nothing.
In order to remember that fact a record is stored in the nearest
(to the right) tuple in that index; in case of no such tuple -
in special place in struct index.
In other words a gap record means that its transaction can be
vulnerable to inserts into that place in index. If something is
inserted into that gap - its transaction must fall into read view
or be aborted.
Further, if a tuple is inserted into that place of index, we have
to decide to which interval (or to both) that gap belongs. If its
owner transaction is vulnerable to both subintervals - the gap
record is splitted into two parts.
There's a special case when the search key is NULL, that stands
for index:select{} call (with empty table as an argument).
Obviously …
> txm: fix a dangerous misprint in gap handling

- test/app-tap/tarantoolctl.test.lua
Before the patch, instead of checking stdout, the return result is checked.
> Fix stdout check in tarantoolctl test

- src/box/vy_lsm.c
- src/box/vy_range.h
- src/box/vy_scheduler.c
- src/box/vy_write_iterator.c
- src/lib/salad/heap.h
- test/unit/heap.c
- test/unit/heap_iterator.c
Fix fedora-34 build 
cherry-picked from master
Now heap API works with struct heap_node only, which forces a
user to constantly call container_of. Such a code looks really
awful. This commit makes heap taking and returning user defined
structures, and removes container_of clue.
It is worth noting, that the similar API rb-tree and b-tree
have. Even rlist has its rlist_*_entry() wrappers, and mhash
provides macroses to define your own value type.
> salad: make heap struct more friendly to use

- changelogs/unreleased/gh-6247-broken-error-message.md
- src/box/memtx_tx.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
At some point ER_TUPLE_FOUND error message was extended to contain
old tuple and new tuple. It seems that after rebase this change
was ignored in MVCC code that used prevous format. This patch
fixes that.
Closes #6247
> txm: fix ER_TUPLE_FOUND error message in MVCC

- .github/actions/environment/action.yml
Found that Github actions/checkout@v2, when Github Actions triggers
a job upon the tag push, it makes the following calls [1]:
```
git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
git fetch origin +$HASH:refs/tags/$TAG
```
While the first call is fine, the second one spoils the tag and makes
it non-annotated.
Later, Tarantool calls git describe without --tags flag, and the
spoiled tag is ignored. This patch handles it by fetching all the
tags once again explicitly.
Also explained the next step, where we remove the tag. The Github
Actions may runs twice the same job on branch push and on new tag
if it was created on this push. To avoid of fails on saving the
commonly named packages, we drop a tag that points to a current
commit (if any) on a job triggered by …
> github-ci: pull all available tags

- changelogs/unreleased/gh-6143-arm64-debug-build
- src/lib/http_parser/http_parser.c
Fix build errors on arm64 with CMAKE_BUILD_TYPE=Debug.
Despite doubts about the correctness of http parser, keep the principle of its work and unify behavior whether plain char is signed or unsigned.
Closes #6143
> build: fix build on Linux ARM64 with CMAKE_BUILD_TYPE=Debug

- test/box/net.box_iproto_transactions_over_streams.result
- test/box/net.box_iproto_transactions_over_streams.test.lua
Currently, when calling 'close' method for connection,
unsent requests are lost. Disable appropriate check until
corresponding (#6338) issue will be resolved.
> test: disable checking the complete requests processing.

- src/lua/table.lua
- test/app-tap/gh-6330-table-new.test.lua
Import of `table.new` module was removed as a part of net.box
refactoring in commit 954194a1ca5c2cd1826a8a689663c827313dbbef.
The `table.new` method became unavailable in Tarantool.
This commit returns it back and adds a corresponding regression test.
Closes #6330
> lua: return back table.new() method

- changelogs/unreleased/gh-6266-fix-crash-in-lua-triggers.md
- src/lua/trigger.c
- test/box/gh-6266-crash-in-lua-triggers.result
- test/box/gh-6266-crash-in-lua-triggers.test.lua
There are two cases in lua trigger implementation, which leads
to access to freed memory: if trigger removes itself and if
trigger yields and someone destroy it. These problems was fixed
by remembering the necessary fields from the trigger structure
in local variables before calling trigger function.
Closes #6266
> lua: fix several possibility crashes in lua triggers implementation.

- changelogs/unreleased/gh-6266-fix-crash-in-lua-triggers.md
- src/lua/trigger.c
- test/box/gh-6266-crash-in-lua-triggers.result
- test/box/gh-6266-crash-in-lua-triggers.test.lua
There are two cases in lua trigger implementation, which leads
to access to freed memory: if trigger removes itself and if
trigger yields and someone destroy it. These problems was fixed
by remembering the necessary fields from the trigger structure
in local variables before calling trigger function.
Closes #6266
> lua: fix several possibility crashes in lua triggers implementation. (2.7)

- changelogs/unreleased/gh-6266-fix-crash-in-lua-triggers.md
- src/lua/trigger.c
- test/box/gh-6266-crash-in-lua-triggers.result
- test/box/gh-6266-crash-in-lua-triggers.test.lua
There are two cases in lua trigger implementation, which leads
to access to freed memory: if trigger removes itself and if
trigger yields and someone destroy it. These problems was fixed
by remembering the necessary fields from the trigger structure
in local variables before calling trigger function.
Closes #6266
> lua: fix several possibility crashes in lua triggers implementation. (2.8)

- changelogs/unreleased/gh-6325-not-serializable-read-before-rollback.md
- src/box/memtx_tx.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
RW transactions used to commit without problems after rollback of transactions holding stories responsible to track their reads.
That behaviour led to unserializable results. This patch fixes this problem.
Closes #6325
> txm: rebind read trackers of rollbacked txns

- changelogs/unreleased/gh-6325-not-serializable-read-before-rollback.md
- src/box/memtx_tx.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
RW transactions used to commit without problems after rollback
of transactions holding stories responsible to track their reads.
That behaviour led to unserializable results.
This patch fixes this problem.
Closes #6325
(cherry picked from commit f77d2869db559d59c68e97f7e490a85600fcac9d)
> txm: rebind read trackers of rollbacked txns (2.8)

- changelogs/unreleased/gh-6325-not-serializable-read-before-rollback.md
- src/box/memtx_tx.c
- test/box/tx_man.result
- test/box/tx_man.test.lua
RW transactions used to commit without problems after rollback
of transactions holding stories responsible to track their reads.
That behaviour led to unserializable results.
This patch fixes this problem.
Closes #6325
(cherry picked from commit f77d2869db559d59c68e97f7e490a85600fcac9d)
> txm: rebind read trackers of rollbacked txns (2.7)

- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/fedora_34.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/ubuntu_14_04.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .github/workflows/ubuntu_20_10.yml
- .github/workflows/ubuntu_21_04.yml
- .gitlab.mk
1) Publishing LIVE packages is no longer supported 
According to the new release policy live packages are not allowed.
Only releases and pre-releases would be published to the S3.
Needs for: #6185
2) Publishing packages to series repo 
New release policy provides new rules for publishing packages.
Now, only major version is defining bucket repo, for more convenience
use next naming series-<MAJOR_VERSION>.
Needs for: #6185
3) Enable publish pre-release tags 
Closed: #6185
> Setup series repo

- changelogs/unreleased/gh-6239-fix-double-for-quote.md
- src/box/sql/func.c
- test/sql-tap/engine.cfg
- test/sql-tap/gh-6239-quote-with-double-arg.test.lua
- test/sql-tap/trigger5.test.lua
- test/sql/types.result
After this patch SQL built-in function QUOTE() will return the argument
in case DOUBLE value is given. If the argument is not number, string
representation of the argument will be returned.
Closes #6239
Title: QUOTE() and DOUBLE argument
After this patch function QUOTE() will return argument in case it
receives DOUBLE value as an argument. The same for all other numeric
types. In case it was given value of non-numeric type, it will return
string representation of the argument.
> sql: fix quote() function

- cmake/BuildLibCURL.cmake
To be able to configure libcurl for ARM64 CPU
on Fedora distros with linker hardening it is
necessary to enable `-fPIC`. It fails with wrong
relocation type for glibc symbols (e.g. socket)
otherwise.
Closes #6366
> build: build libcurl with PIC enabled

- src/lib/core/xmalloc.h
- test/unit/CMakeLists.txt
- test/unit/xmalloc.c
- test/unit/xmalloc.result
This patch adds xmalloc, xcalloc, xrealloc, xstrdup, and xstrndup helper
functions. Each of them calls the corresponding memory allocation
function and panics if it fails. See the issue description for the full
justification.
Closes #3534
> core: add x* memory allocation functions

- changelogs/unreleased/gh-6217-fix-net-box-connect-error.md
- src/box/lua/misc.cc
- src/box/tuple_dictionary.c
- src/box/tuple_dictionary.h
- src/box/tuple_format.c
- src/box/tuple_format.h
- test/box/net.box_reuse_tuple_formats_gh-6217.result
- test/box/net.box_reuse_tuple_formats_gh-6217.test.lua
The number of tuple formats is limited by 65K. Each net.box connection creates a few formats for schema. So if one opens/closes connections in a loop, they will soon run out of formats unless they manually invoke the garbage collector. Let's reuse formats exported to Lua to avoid that. All the infrastructure is already there - it was introduced for ephemeral spaces. We just need to extend it a little bit.
Closes #6217
> Reuse tuple formats in Lua

- changelogs/unreleased/gh-6292-fix-dropping-messages-in-case-when-connection-closing.md
- src/box/iproto.cc
- test/box/gh-6292-fix-dropping-msg-when-connection-closing.result
- test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua
Fixed dropping incoming messages when connection is closed or SHUT_RDWR
received and net_msg_max or readahead limit is reached. Now we don't close
connection if an error occurred while writing response, but only set a
special flag to stop further writing. Connection will be closed when we
read 0 from socket and process all requests. 
Closes #6292
> iproto: fix dropping messages when connection is closed with SHUT_RDWR.

- changelogs/unreleased/fiber-access-optimization.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
This patch reworks approach to fiber management in Lua. Before
this patch each action that should return fiber led to new
userdata creation that was quite slow and made GC suffer. This
patch introduces new field in struct fiber to store a reference to
userdata that was created once for a fiber. It allows speedup
operations as fiber.self() and fiber.id().
Simple benchmark shows that access to fiber storage is faster in
two times, fiber.find() - 2-3 times and fiber.new/create functions
don't have any changes.
---
Benchmark:
```lua
local clock = require('clock')
local fiber = require('fiber')
local start = clock.time()
for _ = 1, 1e6 do
fiber.self().storage['a'] = 'b'
end
print('fiber.self().storage', clock.time() - start)
collectgarbage()
collectgarbage()
local start = clock.time()
for _ = …
```
> fiber: keep reference to userdata if fiber created once

- doc/changelogs.md
* Fixed a typo in a link anchor.
* Added an alternative process (to better highlight why we stick with our one).
> doc: changelog.md updates

- test/box/net.box_reconnect_after_gh-3164.result
- test/box/net.box_reconnect_after_gh-3164.test.lua
The test is flaky, supposedly because of a bug in Lua JIT.
Disabling Lua JIT makes the test pass.
Workaround for #5081
> test: disable Lua JIT for net.box_reconnect_after_gh-3164

- changelogs/unreleased/gh-5977-build-index-in-background-with-hash-primary.md
- src/box/memtx_space.c
- test/box/gh-5977-inconsistency-on-shadow-build-with-hash-pk.result
- test/box/gh-5977-inconsistency-on-shadow-build-with-hash-pk.test.lua
If we insert a tuple in space with an index that is being built in background,
new tuple will or will not be inserted into new index depending on the result of
lexicographical comparison with tuple which was inserted into new index last.
The problem is hash index is unordered, so background build will not work properly
if primary key is HASH index.
To avoid this, disable building index in background if primary index is hash.
Closes #5977
> memtx: disable building index in background if primary index is hash

- src/box/lua/net_box.c
- src/box/lua/net_box.lua
We will need to store net.box watchers (see #6257) in a C struct. We already have a C struct per net.box connection, but it has an unfortunate name - netbox_registry - because initially it was introduced to only store the requests hash table. This patch renames it to netbox_transport. While we are at it, let's also move the send/recv buffers to this struct (which is now aptly named), because they fit well in there (this would be a part of #6291).
> net.box: doing some renames and moving send/recv buffers to C

- .travis.mk
- cmake/os.cmake
OSX workflows use brew for install openssl.
There was a new release of openssl@3.0 and
homebrew updated the openssl formula.
Close #6468
> github-ci: use openssl@1.1

- changelogs/unreleased/gh-6293-implement-detailed-iproto-requests-stats.md
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/info.c
- src/box/lua/stat.c
- test/box-tap/feedback_daemon.test.lua
- test/box/gh-6293-implement-new-net-stat.lua
- test/box/gh-6293-implement-new-net-stat.result
- test/box/gh-6293-implement-new-net-stat.test.lua
Add new  metrics `REQUESTS_IN_PROGRESS`, `REQUESTS_IN_STREAM_QUEUE`
and `REQUESTS_IN_CBUS_QUEUE` to `box.stat.net`, which contain detail statistics for iproto requests. These metrics contains same counters as other metrics in `box.stat.net`: current, rps and total.
Add new  metric `STREAM_QUEUE_MAX` to `box.stat.net`. This metric contain two counters `current` (displays the current length of the longest stream queue) and `total` (displays the maximal length of the stream queue for all time).
> Add new metrics to `box.stat.net`

- changelogs/unreleased/gh-6203-implement-fiber-join-with-timeout.md
- src/lua/fiber.c
- test/app/gh-6203-fiber-join-with-timeout.result
- test/app/gh-6203-fiber-join-with-timeout.test.lua
Implement ability to pass timeout to 'fiber:join' function.
If timeout expired, join fails with 'timed out' error.
Closes #6203
Title: ability to set timeout for 'fiber:join' function was implemented
Implement ability to pass timeout to 'fiber:join' function.
If timeout expired, join fails with 'timed out' error.
> lua: implement timeout for 'fiber:join'

- .github/workflows/centos_7_aarch64.yml
- .github/workflows/centos_8_aarch64.yml
- .github/workflows/debian_10_aarch64.yml
- .github/workflows/debian_11_aarch64.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/fedora_33_aarch64.yml
- .github/workflows/fedora_34_aarch64.yml
- .github/workflows/osx_arm64_11_2.yml
- .github/workflows/osx_debug_arm64_11_2.yml
- .github/workflows/ubuntu_20_04_aarch64.yml
- .github/workflows/ubuntu_20_10_aarch64.yml
We have limited amount of arm64 runners and arm64 jobs are often queued
for hours. So I disabled running of arm64 jobs on developer branches and
external PRs. Now we run them on master, release branches, tags and for
branches named as 'something-full-ci'.
While I'm here, disabled those jobs explicitly on forks: I guess
otherwise it'll be it a 'waiting a runner' state infinitely.
> ci: reduce number of arm64 job runs

- .github/actions/send-telegram-notify/action.yml
To be honest, I have not proceeded with necessary actions to receive
personal Telegram notifications for my branches, because GitHub already
sends them to my email.
I kept this feature (I don't know, whether someone uses it), but let the
action ignore failures in the case.
A failed attempt to send the notification from `master`, a release
branch (`1.10`, `2.8`, ...) or a tag will fail the job as before. The
change affects only personal notifications for developer branches.
Fixes https://github.com/tarantool/tarantool-qa/issues/130
> ci: don't fail job on failed personal Telegram notification

- .github/workflows/integration.yml
and the 'checks' module.
Part of #5265
Part of #6056
Closes #6562
Depends on tarantool/checks#27
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1399155369)
> ci: add integration check for 'checks' module

- .github/workflows/integration.yml
and the mysql module.
Part of #5265
Part of #6056
Closes #6577
Depends on tarantool/mysql#61
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1409106252)
> ci: add integration check for mysql module

- .gitlab.mk
- changelogs/unreleased/gh-6390-resolve-lintian-warnings.md
- debian/control
- debian/copyright
- debian/rules
- debian/source/lintian-overrides
- debian/tarantool.lintian-overrides
Closes #6390 
Remove duplicate pattern from copyright.
Remove outdated tags override.
Ignore embedded library lintian errors for curl and libyaml.
Ignore lintian warning. This warning triggers when debhelper minimal required version is less than compat level. Ubuntu Xenial repos do not contain debhelper 10. This warning also triggers on Ubuntu Bionic and Debian Stretch and Buster despite using debhelper 10 or newer, which highly likely is a lintian bug. Debian Bullseye and Ubuntu newer that Bionic
pipelines do not yield this warning.
Add PackPack to uploaders. Before this patch all PackPack-builded packages was treated as non-maintainer updates.
Add PackPack to uploaders. Before this patch all PackPack-builded packages was treated as non-maintainer updates.
Remove Windows binaries from …
> debian: resolve lintian warnings

- debian/copyright
Add missing third party licenses to debian/copyright. Update copyright dates for modules. Remove license entries for unused modules.
Closes #6391
> debian: actualize licenses

- .github/workflows/integration.yml
and tarantool-c connector.
Part of #5265
Part of #6056
Closes #6582
Depends on tarantool/tarantool-c#153
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1443997343)
> ci: add check for tarantool-c connector

- .github/workflows/integration.yml
and tarantool-python connector.
Part of #5265
Part of #6056
Closes #6584 
Depends on tarantool/tarantool-python#192
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1446356476)
> ci: add check for tarantool-python connector

- .github/workflows/integration.yml
and the tarantool-php/client connector.
Part of tarantool/tarantool#5265
Part of tarantool/tarantool#6056
Closes tarantool/tarantool#6594
Depends on tarantool-php/client#74
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1446280386)
> ci: add integration check for tarantool-php/client

- debian/copyright
Add missing third party licenses to debian/copyright. Update copyright
dates for modules. Remove license entries for unused modules.
Closes #6391
master: #6542
> debian: actualize licenses for 2.8

- debian/copyright
Add missing third party licenses to debian/copyright. Update copyright
dates for modules. Remove license entries for unused modules.
Closes #6391
> debian: actualize licenses for 1.10

- .github/workflows/integration.yml
and the tarantool-php/queue connector.
Part of tarantool/tarantool#5265
Part of tarantool/tarantool#6056
Closes tarantool/tarantool#6595
Depends on https://github.com/tarantool-php/queue/pull/18
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1446230838)
> ci: add integration check for tarantool-php/queue

- src/box/applier.cc
- src/box/lua/console.c
- src/box/xrow_io.cc
- src/lib/core/CMakeLists.txt
- src/lib/core/coio.c
- src/lib/core/coio.cc
- src/lib/core/coio.h
- src/lib/core/coio_buf.h
- src/lib/core/popen.c
- test/unit/coio.cc
To convert the net.box state machine to C, I need `coio_connect` to take host and service as strings (not as URI) and be exception-free. While we are at it, let's also convert `coio.cc` to C.
Closes #4881
> coio refactoring

- .github/workflows/integration.yml
and the expiration module.
Part of #5265
Part of #6056
Closes #6528
Depends on tarantool/expirationd#88
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1452521713)
> ci: add integration check for expirationd module

- debian/changelog
- rpm/tarantool.spec
Actualize changelog based on GitHub release pages changelogs. Some entries were skipped since they are not relevant to modern packages. Versions 1.8.1 and 2.0.4 changelogs were merged to 2.1.1 changelog.
Closes #6397
> actualize debian and rpm changelog

- debian/changelog
- rpm/tarantool.spec
Actualize changelog based on GitHub release pages changelogs. Some entries were skipped since they are not relevant to modern packages. Version 1.8.1 changelog was skipped since its changes is related to 2.x branches.
1.10 version of #6536
> actualize debian and rpm changelog for 1.10

- test/unit/CMakeLists.txt
- test/unit/watcher.c
Watcher unit test linked with libbox and included
core_test_utils.c. Both contain cord_on_yield() symbol.
It is defined as a stub in core_test_utils and checks being inside
of GC in libbox.
Somehow it managed to link all this time just fine. And moreover
the linker selected the correct symbol - the one from
core_test_utils.
But while making another patch (not submitted yet), some other
unit test was changed a bit and the watcher unit test link stage
started failing with 'cord_on_yield()' duplicate symbol.
The patch drops core_test_utils from the test and makes it work
with libbox correctly. To support that the test now needs to
initialize the global Lua state.
> test: fix watcher unit test duplicate symbol

- changelogs/unreleased/gh-3554-several-listening-sockets.md
- changelogs/unreleased/gh-6535-fix-error-in-listening-to-numerical-uri-after-listening-to-unix-socket.md
- src/box/box.cc
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/info.c
- src/box/lua/load_cfg.lua
- src/lib/core/coio.c
- src/lib/core/evio.c
- src/lib/core/evio.h
- src/lib/core/sio.c
- src/lib/core/sio.h
- src/lib/swim/swim_transport_udp.c
- test/box-tap/gh-6535-listen-update-numeric-uri.test.lua
- test/box-tap/several-listening-sockets.test.lua
- test/box/cfg.result
- test/box/cfg.test.lua
iproto: implement ability to open several listening sockets
Previously, iproto could only open one socket for listening
only. This patch change this behaviour, now user can open
several listening sockets (up to 20). Also in addition to
ability to pass uri as a number or string, as  previously,
ability to pass uri as a table of numbers or strings has
been added.
```lua
box.cfg { listen = {3301, 3302, 3303} }
box.cfg { listen = {"127.0.0.1:3301", "127.0.0.1:3302"} }
```
> Multilisten in opensource

- test/box/net.box_tx_timeout.result
- test/box/net.box_tx_timeout.test.lua
The problem was that when we wanted to check that
the transaction rolled back after the timeout, we
called `fiber.sleep` on the local instance, while
the timeout for transaction counted on the remote
instance. Fix the text, so now we call `fiber.sleep`
on remote server, ensuring that timeout for transaction
expires.
Closes #6586
> test: fix flaky net.box_tx_timeout.test

- static-build/test/static-build/exports.test.lua
It got broken in 54be00b6aa0f4320e3dbdfa0b539c5e73cd0143f
("error: use error_payload in Lua"). 2 symbols were dropped from
the exports but not from this test.
Follow-up #5568
> test: fix static build exports test

- src/lib/swim/swim_proto.c
I was playing with libFuzzer and found heap-buffer-overflow.
`**pos` is dereferenced before it is checked via `*pos == end`. This leads
to out of bounds access when `*pos == end`.
You can build Docker from [oss-sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/tarantool) to reproduce the crash. Copy
[crash-090cbc46c3a13cd05fceb2fe55cccaab870d6795.txt](https://github.com/tarantool/tarantool/files/7546134/crash-090cbc46c3a13cd05fceb2fe55cccaab870d6795.txt)
to current directory before docker build. Then run inside docker:
```
/swim_proto_member_fuzzer /fuzz/crash-090cbc46c3a13cd05fceb2fe55cccaab870d6795.txt
```
Result:
```
=================================================================
==15==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000051 at pc …
```
> swim: fix out of bounds access in proto decode

- test/replication-luatest/gh_5568_read_only_reason_test.lua
The test sometimes failed the test cases
test_read_only_reason_synchro_no_uuid and
test_read_only_reason_election_has_leader_no_uuid.
Both relied on an instance being gone from 'replicaset' global
internal object in C once it is gone from _cluster. But it wasn't
true.
If an instance is not visible in _cluster, it could still be not
deleted from 'replicaset' because it is done only on WAL write
end. So this was a dirty read - the check about an id absent in
_cluster.
The more reliable way is to check that the replica is gone from
box.info.replication - it is built from this 'replicaset' object.
Closes #6621
> test: fix flaky read_only_reason test

- src/lib/core/coio.c
- test/unit/coio.cc
- test/unit/coio.result
coio_accept, coio_read, coio_write, coio_writev used to handle spurious
wakeups correctly: if the timeout hasn't passed yet, they would simply
retry reading (or writing) and fall asleep once again if no data is
ready.
This behaviour changed in the following patches:
577a640a7fdec986d19101ed04d2afa80e951c78 ("coio: pass fd to
coio_accept") and 4f84859dcdd6126b0bdcda810b7f5f58386bdac6 ("Introduce
iostream wrapper for socket I/O").
Now the functions timeout on the very first spurious wakeup.
Fix this, add the appropriate unit tests and a test_iostream
implementation for the ease of testing.
> coio: handle spurious wakeup correctly

- src/trivia/util.h
Before this patch test build failed with following error:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/memory:2666:26: error: unexpected type name '_CompressedPair': expected expression
struct _ALIGNAS_TYPE(_CompressedPair) _Storage {
```
This patch seems to be fix this issue.
The root of the problem is in "trivia/util.h" module. It defines
alignas macros: `#define alignas(_n)
__attribute__((aligned(_n)))`. And it seems causes some issues in
stdlib internals. To fix this issue let's unconditionally include
stdalign.h for C++. According [1] this header should internally
define __alignas_is_defined macro.
[1] https://en.cppreference.com/w/cpp/language/alignas
Part of #6576
> test: fix bloom test build on MacOS

- changelogs/unreleased/gh-6220-reduce-snapshot-verbosity.md
- src/box/applier.cc
- src/box/memtx_engine.cc
- src/box/recovery.cc
- src/lib/core/say.h
On big instances core produces too much logs related to shapshotting,
which feels redudant: reduce snapshot verbosity.
Closes #6220
> xlog: reduce snapshot verbosity

- changelogs/unreleased/gh-6086-log-cfg-must-not-be-updated-on-box-cfg-error.md
- src/box/lua/load_cfg.lua
- src/lua/log.lua
- test/app-tap/logger.test.lua
- test/box-tap/gh-6086-log-cfg-must-not-be-updated-on-box-cfg-error.test.lua
- test/box/reconfigure.result
If 'box.cfg' fails with error, 'log.cfg' still gets updated: instead,
update 'log.cfg' after verifying 'box.cfg', and rollback if update of
'log.cfg' fails.
Closes #6086
> box: 'box.cfg' error behaviour

- .github/workflows/centos_7_aarch64.yml
This commit actually reverts 2.10.0-beta1-136-gaa2a6bc83 ('ci:
temporarily disable deploy for CentOS 7 for aarch64').
I built packages necessary for testing for CentOS 7 on aarch64 and
placed them into packpack backports [1].
The source packages are from CentOS 8 [2] and are the following:
* Cython-0.29.14-4.module_el8.3.0+441+3b561464.src.rpm
* python-gevent-1.2.2-4.el8.src.rpm
* PyYAML-5.3.1-1.module_el8.3.0+441+3b561464.src.rpm
* python-six-1.12.0-9.module_el8.3.0+441+3b561464.src.rpm
[1]: https://packagecloud.io/packpack/backports
[2]: https://vault.centos.org/8.3.2011/AppStream/Source/SPackages/
If you're curious about steps to re-build the packages for CentOS 7,
read below.
----
Build steps are the following:
```sh
$ ssh <aarch64 machine>
$ docker run -it -v <...>:/src -v <...>:/res …
```
> ci: enable CentOS 7 on aarch64

- .github/workflows/integration.yml
Problem:
For now, the integration testing runs only on a push of changes/tags
to the 'master' and release branches. This approach is not good enough
because we become aware of integration issues after the changes were
merged already to the target branch.
So this patch adds the facility to run the integration testing on a dev
branch to catch integration issues before the changes are merged to the
target branch. Now it can be done via naming the branch as `*-full-ci`
and pushing it to the main repository or setting the 'full-ci' label on
the pull request.
> ci: run 'integration.yml' WF in pre-commit testing

- src/box/lua/net_box.c
- src/lib/core/exception.cc
- src/lib/core/exception.h
- src/lib/core/say.c
- src/lua/fio.c
- test/app/on_shutdown.result
- test/app/on_shutdown.test.lua
- test/box/cfg.result
- test/box/func_reload.result
- test/box/func_reload.test.lua
- test/box/gh-6092-invalid-listen-uri.result
- test/box/gh-6092-invalid-listen-uri.test.lua
- test/unit/fiber.result
- test/unit/fiber_stack.result
- test/vinyl/errinj.result
Commit c13b3a31a9b04d4e3fbf0be88f76285b2cc103a7 changed error messages reported by net.box on IO errors, which caused integration/cartridge test failure. The net.box state machine used to return `strerror(errno)`, e.g. something like `Connection refused`, while now it returns `error::errmsg`, which lacks `strerror(errno)`, e.g. `connect, called on fd 55, aka 127.0.0.1:34138`. The old error message is arguably more useful, because it explains *why* the failure happened, not *what* failed. In PR https://github.com/tarantool/tarantool/pull/6643 I tried to restore the original error messages. This would fix cartridge test, but the code looked confusing. In review of the aforementioned PR @Gerold103 suggested to append `strerror(errno)` to `error::errmsg` for `SystemError` and `SocketError`. …
> net.box: fix IO error messages - alternative approach

- .github/workflows/freebsd-12.yml
- .github/workflows/freebsd-13.yml
- .gitlab.mk
- .travis.mk
- README.FreeBSD
- extra/mkexports
FreeBSD images for MCS was created. Now we can run tests directly from
MCS instances.
There are no official github runner for FreeBSD, but we can use
unofficial runner that supports FreeBSD:
https://github.com/ChristopherHX/github-act-runner.
It has limitation:
You won't be able to run steps after a failure without using continue-on-error: true
So steps: artifacts and Telegram message on failure was removed.
> Move FreeBSD CI to MCS

- tools/check_push_master.sh
Sometimes to fix an issue we need to patch our submodule, update it
in tarantool and then patch tarantool using changes in submodule.
During development and review stages we have to create a branch (S)
in submodule and a branch (T) in tarantool that references head of
(S) branch.
When the fix is merged to mater it's very simple to make a mistake:
merge-and-push submodule's branch S and then tarantool's branch T.
It sounds obvious, but that's wrong: tarantool's master should
reference a commit from submodule's master, not a commit from
temporary developer's branch.
It's not hard to fix it but still a maintainer must always remember
that problem. In order to simplify their life it was decided to
create a script that is designed to check such thing before pushing
tarantool to origin/master. …
> tools: add a script that checks submodules' commits

- changelogs/unreleased/gh-6568-replica-initial-join-removal-of-compacted-run-files.md
- src/box/vinyl.c
- src/box/vy_run.c
- src/box/vy_run.h
- src/box/vy_scheduler.c
- test/vinyl-luatest/gh_6568_replica_initial_join_removal_of_compacted_run_files_test.lua
- test/vinyl-luatest/suite.ini
On completion of compaction tasks we remove compacted run files created
after the last checkpoint immediately to save disk space. In order to perform this
optimization we compare the unused runs' dump LSN with the last
checkpoint's one.
But during replica's initial JOIN stage we set the LSN of all rows
received from remote master to 0 (see
box/box.cc/boostrap_journal_write). Considering that the LSN of an
initial checkpoint is also 0, our optimization stops working, and we
receive a huge disk space usage spike (as the unused run files will
only get removed when garbage collection occurs).
We should check the vinyl space engine's status and perform
our optimization unconditionally if we are in replica's initial JOIN
stage.
Closes #6568
> vinyl: optimize deletion of compacted run files

- changelogs/unreleased/gh-6198-max-cnt-of-tuple-fields-insert-overflow-error-msg.md
- src/box/errcode.h
- src/box/xrow_update_array.c
- test/box-tap/gh-6198-max-cnt-of-tuple-fields-insert-overflow-err-msg.test.lua
- test/box/error.result
Tuple field count overflow is not handled: before inserting, explicitly
compare the current tuple size to box.schema.FIELD_MAX and set a newly
introduced diagnostic message if overflow occurs.
Closes #6198
> box: fix tuple field count overflow handling

- src/lib/core/crash.c
- src/lib/core/popen.c
`vfork` got deprecated on macOS:
* refactor crash signal hander: change `vfork` to more portable `posix_spawn`.
* `popen`: for now, change `vfork` deprecation error to a warning until we find a suitable solution. We plan to review
`popen`'s design and get rid of `vfork` completely, or change `vfork` to `posix_spawn` only on macOS (#6674).
Closes #6576
> vfork on macOS

- test/replication/gh-3160-misc-heartbeats-on-master-changes.result
- test/replication/gh-3160-misc-heartbeats-on-master-changes.test.lua
- test/replication/suite.ini
The test fails quite often with one of the following results.
Either
[001] @@ -60,7 +60,7 @@
[001]  ...
[001]  test_timeout()
[001]  ---
[001] -- true
[001] +- false
[001]  ...
[001]  test_run:cmd("switch default")
[001]  ---
[001]
Or
[034]  test_timeout()
[034]  ---
[034] -- true
[034] +- error: 'replicas are not in the follow status'
[034]  ...
Both errors are caused by wait_cond checking saved
`box.info.replication` values instead of actual `box.info.replication`
output. Fix this.
Also, the test's quite long for no reason.
The wait_cond waiting for replication to break lasts a whole
`replication_timeout`, which is excess.
The test's idea, as stated in the commit that has introduced it
(195d4462: Send relay heartbeat if wal changes won't be send) is to
constantly relay some data to the …
> replication: fix flaky gh-3160-misc... test

- cmake/BuildLibCURL.cmake
```
[100%] Linking C static library libcurl-d.a
<...>
make[3]: *** No rule to make target `build/curl/dest/lib/libcurl.a',
needed by `test/unit/luaL_iterator.test'. Stop.
```
The problem appears on Mac OS. It is a bit strange that we don't see it
on Linux. However I didn't dig into this, just fixed the observed
problem.
Related: https://github.com/curl/curl/issues/2121
Fixes #6656
> build: fix linking of debug curl library

- src/lib/swim/swim_proto.c
- test/unit/swim_proto.c
- test/unit/swim_proto.result
assert(cur < end) after mp_load_u8 in mp_check_binl was failing
This PR fixes abort found with libFuzzer target in #6627
> swim: fix debug assertion abort in proto decode

- test/box-tap/suite.ini
Test for #6198 handles an edge case (`box.schema.FIELD_MAX` tuple
field count), hence consuming a huge amount of memory (see #6684): mark
it as `long run`.
Closes #6684
> test: mark #6198 test `long run`

- test/replication-luatest/gh_6123_truncate_temp_space_test.lua
Replication of data in the test should happened before the data presence
test on the replica. Wait for lsn helper is used.
Closes #6663
> test: fix flaky test on temp space truncate

- .github/workflows/integration.yml
and go-tarantool connector.
Part of #5265
Part of #6056
Closes #6607
Depends on tarantool/go-tarantool#112
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/1555764437)
> ci: add check for go-tarantool connector

- changelogs/unreleased/gh-6167-select-with-dict.md
- src/box/lua/tuple.lua
- test/box/gh-6167-select-with-dict.result
- test/box/gh-6167-select-with-dict.test.lua
Currently, select/pairs/get look at an :array part of passed table,
that is why different problems occurs when passed to select() table
is not a regular array.
Now we will check if passed table is not "clear dict"
(not empty table without array part). Invalid queries
like s:select{key = 'value'} will fail with an appropriate
error, but the problems with dicts containing array part
still remain (for example, s:select{1, key = 'value'} is
the same as s:select{1}).
Closes #6167
> memtx: raise an error if argument of select() is a "clear" dict

- changelogs/unreleased/debian-remove-binutils-dependency.md
- debian/control
tarantool debian package MUST NOT depends on binutils package.
This is due to the fact that binutils include linker and assembler,
what in most cases forbidden on production servers.
Fixes #6699
> debian: eliminate dependency from binutils package

- .github/workflows/debug_aarch64.yml
There was a build problem with CMAKE_BUILD_TYPE=Debug build on ARM64. It
was fixed in 224cb68c4ddca83f0e95daa4e97a393b3a89c471 (build: fix
build on Linux ARM64 with CMAKE_BUILD_TYPE=Debug), before this fix
'-DCMAKE_C_FLAGS="-Wno-type-limits "' was used to avoid the issue,
implemented by 72c77166344e0a42293aaaed7d838dff000de746 (github-ci:
add GitHub Actions workflow for Odroid).
Follow-up #6143
> github-ci: delete option in odroid debug workflow

- test/app-tap/datetime.test.lua
`test/app-tap/datetime.test` is flaky on Graviton runners
(Linux/Ubuntu/aarch64) so we disable this test for a while.
Part of #6599
Follow-up to #5941
> datetime: disable datetime.test.lua on Graviton

- src/lib/bit/bit.h
- src/pickle.h
Now there's a lot of load_*/store_* functions that are designed
for unaligned access to variables in data stream. Unfortunately
they are written in a way that makes new compilers to warn about
outside bounds.
Rewrite it in the most safe, cross-platform and efficient way -
using memcpy. Note that memcpy with compile-time-defined size is
recognized by the magority of compilers and they make the most
efficient operation.
Closes #6703
> lib: use memcpy for unaligned load/store

- .github/workflows/lint.yml
- changelogs/unreleased/change-transaction-behaviour-after-rollback-on-yield.md
- changelogs/unreleased/drop-net-box-console.md
- changelogs/unreleased/gh-5814-memprof-group-allocation-on-traces.md
- changelogs/unreleased/gh-6242-net-box-drop-conn-timeout.md
It should make development a bit more friendly: CI will assist with keeping release notes buildable.
The `gen-release-notes` script is written with care to error messages and if it raises an error it should be quite easy to find a cause and fix it. It does not check Markdown syntax and spelling, though: just ability to build the document from files.
The most often mistake is around section header format: `## feature/<...>` or `## bugfix/<...>`.
Just a reminder: if you want to see how your changelog entry will look in a future release notes, just run `./tools/gen-release-notes`. Don't hesitate to the changelog after a push to master: it is information for our users and there is nothing bad in making it better.
> ci: verify changelog entries in CI

- test/replication/long_row_timeout.result
- test/replication/long_row_timeout.test.lua
- test/replication/suite.ini
On heavy loaded hosts either slow machines like VMware found the
following issues:
```
[010] --- replication/long_row_timeout.result   Fri May  8 08:56:08 2020
[010] +++ var/rejects/replication/long_row_timeout.reject       Mon Jun 21 04:39:08 2021
[010] @@ -23,7 +23,7 @@
[010]  ...
[010]  box.info.replication[2].downstream.status
[010]  ---
[010] -- follow
[010] +- stopped
[010]  ...
[010]  -- make applier incapable of reading rows in one go, so that it
[010]  -- yields a couple of times.
[010]
[026] --- replication/long_row_timeout.result Fri Sep 25 19:08:46 2020
[026] +++ replication/long_row_timeout.reject Fri May  8 08:23:39 2020
[026] @@ -80,7 +80,7 @@
[026]  ...
[026]  ok
[026]  ---
[026] -- true
[026] +- false
[026]  ...
[026]  s:drop()
[026]  ---
[026]
```
It happened because …
> test: flaky replication/long_row_timeout.test.lua

- src/CMakeLists.txt
This commit defines two cmake variables:
- EXTRA_REEXPORT_LIBRARIES: list of libraries appended to reexport_libraries.
- EXTRA_EXPORTS_FILE_SOURCES: list of exports file sources appended to export_file_sources.
Needed to export extra symbols in [Tarantool EE](https://github.com/tarantool/tarantool-ee) build.
> cmake: allow to add extra export symbols

- src/lua/uri.lua
- test/app-tap/uri.test.lua
After updating the uri library, the "params" table was added
to the URI structure. It breaks backward compatibility in
case when URI passed to "uri.format" function in old way,
without params table.
> uri: fix break of backward compatibility

- src/lua/uri.lua
- test/app-tap/uri.test.lua
`uri.parse` always creates params table even if there's no query parameters in the given uri:
```
tarantool> require('uri').parse('localhost:3301')
---
- host: localhost
service: '3301'
params: []
...
```
This is confusing and inconsistent with other uri properties, which are created only if they actually exist. Let's create the params table only if the given uri actually has any params.
> uri: don't create params table in parse if there's no params

- extra/exports
- src/lib/core/datetime.c
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
> #6453 has created `datetime` module. Here we add intervals support, but not yet with daylight saving time information, 
> or transitions thru human-readable time-zones, which will be added in a future as a separate step.
This pull-request is following this RFC https://hackmd.io/hJU7rbnGQv6CSJCJl7KUiA?view#%D0%AD%D1%82%D0%B0%D0%BF-2-%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%B0%D1%82%D1%8B
* One could create interval object via
```lua
local ival = datetime.interval{ year=123, hour=565 }
```
where `year` and `hour` are of a list of allowed attributes, similar to date constructor.
* interval arithmetics is accessible either via `:add{}`/':sub{}` methods without interval object:
```lua …
```
> datetime: intervals implementation - step.2

- changelogs/unreleased/func-multikey-opt-without-sub-table.md
- changelogs/unreleased/gh-3349-func-takes-raw-args.md
- changelogs/unreleased/gh-4861-net-box-return-raw.md
- changelogs/unreleased/gh-5316-msgpack-object.md
- src/box/func_def.c
- src/box/func_def.h
- src/box/lua/call.c
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- src/box/lua/schema.lua
- src/box/lua/tuple.c
- src/lua/msgpack.c
- src/lua/msgpack.h
- src/lua/serializer.h
- test/app-luatest/msgpack_test.lua
- test/box-luatest/func_test.lua
- test/box-luatest/net_box_test.lua
- test/box-luatest/suite.ini
- test/box/function1.result
This pull request introduces a new userdata Lua object `msgpack.object` that stores arbitrary msgpack data. A msgpack object can be created from any Lua object, including another msgpack object. A msgpack object can be passed to net.box or inserted into a database space. It's possible to configure net.box to return a msgpack object from call/eval and other methods (`return_raw` option). It's also possible to configure a function to take a msgpack object (`takes_raw_args` option).
For more details, see the commits comments and the [design document](https://docs.google.com/document/d/11mbV5fRlcrmTz_tE1tanCwaXjFmHM7mcUfaUzkhcG8w).
Closes #1629
Closes #3349
Closes #3909
Closes #4861
Closes #5316
> MsgPack object

- changelogs/unreleased/gh-6686-build-with-glibc-2-34.md
- test/unit/guard.cc
Macros SIGSTKSZ used to be an integral constant but
in glibc-2.34 it turned into a runtime function so it
cannot be used as constant known size for arrays anymore.
Beyond this, SIGSTKSZ is not enough for alt. signal stack size
when you use ASAN, so the size was increased.
Closes #6686
> build: fix build with glibc-2.34

- src/box/iproto.cc
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- src/lib/core/coio.c
- src/lib/core/coio.h
- src/lib/core/evio.c
- src/lib/core/evio.h
- src/lib/uri/uri.c
- src/lib/uri/uri.h
- src/lua/uri.c
- src/lua/uri.h
- test/unit/uri.c
- test/unit/uri.result
Currently, iproto and net.box don't know the full uri used to listen/connect, only host and port. This PR replaces host/port with a full uri. We will use it later to pass connection options in uri parameters (e.g. to setup encryption). No user-visible changes are expected.
> Pass uri to net.box and iproto

- src/box/box.cc
We assume that no one touches the instance's WALs, once it has taken the
wal_dir_lock. This is not the case when upgrading from an old setup
(running tarantool 1.7.3-6 or less). Such nodes either take a lock on
snap dir, which may be different from wal dir, or don't take the lock at
all.
So, it's possible that during upgrade an old node is not stopped
properly before a new node is started in the same data directory.
The old node might even write some extra data to WAL during new node's
startup.
This is obviously bad and leads to multiple issues. For example, new node
might start local recovery, scan the WALs and set replicaset.vclock to
some value {1 : 5}. While the node recovers WALs they are appended by the old
node up to vclock {1 : 10}.
The node finishes local recovery with replicaset …
> recovery: panic in case of recovery and replicaset vclock mismatch

- .github/workflows/source.yml
For now, source packages are deployed to our repositories with the wrong
version. It is due to the actions/checkout bug with not preserving tag
annotations [1].
This issue was fixed from our side by adding a workaround [2] to the
.github/actions/environment action. But for some reason, invocation of
this action was not added to the 'source.yml' workflow. This patch fixes
that.
[1] https://github.com/actions/checkout/issues/290
[2] https://github.com/tarantool/tarantool/pull/6197
Closes tarantool/tarantool-qa#146
> cd: deploy source packages with the right version

- src/lib/bit/bit.h
- test/unit/bit.c
- test/unit/bit.result
Now scan.coverity.com reports "Overrunning buffer pointed to by
&map of 4 bytes by passing it to a function which accesses it at
byte offset 7" in bit_iterator_init call.
Add an unit test that verifies that bit iterator works correctly
with small size bitmaps (like uint32_t).
Change condition a bit hoping that it will calm down the checker.
No functional changes.
> lib: insignificant change to calm down coverity checker

- .github/workflows/integration.yml
and the memcached module.
Part of #5265
Part of #6056
Closes #6563
Depends on tarantool/memcached#74
Manual [test run](https://github.com/tarantool/tarantool/runs/4650789830?check_suite_focus=true)
> ci: add integration check for memcached module

- .github/workflows/fuzzing.yml
Now it is not possible to run fuzzing on CI without merge to master
branch. Last time we missed [1] a broken compilation on merging new
fuzzers to master [2]. This patch enables fuzzing for branches with
postfix 'full-ci'.
1. https://github.com/tarantool/tarantool/pull/6757
2. https://github.com/tarantool/tarantool/pull/6627
> ci: enable fuzzing for *-full-ci branches

- tools/gen-release-notes
Several changes are there:
* Always keep the `changelogs/unreleased` directory.
* Gracefully handle situations, when there is no changelog entries or when only bugfixes (or only features) are present.
* Properly handle title/mixed case in headers: group sections case insensitively and prettify only lowercased headers.
First two bullets resolve problems in CI, when the script is used as linter (see PR #6701). It is a bit more general alternative for PR #6755.
The third bullet allows to write `## feature/SQL` instead of `## feature/sql` in a changelog entry. The restriction was artificial and hard to remember, so it worth to relax it to easy developer's life.
> gen-release-notes: relax validation rules

- .github/workflows/osx_11_aarch64.yml
- .github/workflows/osx_11_aarch64_debug.yml
This patch brings consistency to OSX workflow names with other workflow 
names.
The following changes were made:
* Arch suffix changed (arm64 -> aarch64)
* Minor OS version removed (11_2 -> 11)
* Specific options moved to the end of the workflow name
(osx_debug_xyz.yml -> osx_xyz_debug.yml)
Closes tarantool/tarantool-qa#149
> ci: make osx workflow names consistent

- src/box/CMakeLists.txt
- src/box/applier.cc
- src/box/applier.h
- src/box/box.cc
- src/box/iproto.cc
- src/box/lua/console.c
- src/box/lua/load_cfg.lua
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- src/box/mp_error.cc
- src/lib/core/CMakeLists.txt
- src/lib/core/coio.c
- src/lib/core/coio.h
- src/lib/core/evio.c
- src/lib/core/evio.h
- src/lib/core/iostream.c
- src/lib/core/iostream.h
- src/lib/core/popen.c
- src/lib/core/ssl.c
- src/lib/core/ssl.h
- src/lib/core/ssl_error.cc
- src/lib/core/ssl_error.h
- src/trivia/config.h.cmake
- test/box-luatest/net_box_test.lua
- test/box-luatest/transport_test.lua
- test/unit/coio.cc
- test/unit/mp_error.cc
- test/unit/mp_error.result
This PR adds a new URI parameter: `transport`. In open-source builds, the parameter is useless - it can only be set to `'plain'`, otherwise an error will be raised. In EE builds, it can, however, it can also be set to `'ssl'`, in which case the connection will be encrypted. The parameter is used by `box.cfg.listen`, `box.cfg.replication`, and `net.box`.
EE part: https://github.com/tarantool/tarantool-ee/pull/4
> Add IPROTO SSL encryption stub

- .travis.mk
Now the tarantool/testing:debian-stretch image from Docker Hub is used.
Closes tarantool/tarantool-qa#136
> ci: drop using testing docker image from GitLab

- .github/workflows/lint.yml
- tools/check-commits
This PR adds a new script, tools/check-commits. The script takes git revisions in the same format as git-rev-list (actually, it feeds all its arguments to git-rev-list) and runs some checks on each of the commits.
For example, to check the head commit, run:
```
./tools/check-commits -1 HEAD
```
To check the last five commits, run:
```
./tools/check-commits HEAD~5..HEAD
```
Currently, there are only two checks, but in future we may add more checks, e.g. check diffs for trailing spaces:
- The commit message contains a documentation request. Can be suppressed with `NO_DOC=<reason>` in the commit message.
- A new changelog entry is added to changelog/unreleased by the commit. Can be suppressed with `NO_CHANGELOG=<reason>` in the commit message.
This PR also adds a new workflow triggered on …
> Add workflow to check commits

- README.md
readme: actualize without much changes
Well, the diff is not nice, so I'll summarize the changes for humans.
General changes:
* Moved patch submission and so on to the end of the document.
* Reformatted to usual 80 columns, inlined and actualized links.
* Reformatted lists: start from a capital letter, end with a period.
* Minor wording tweaks to make it sound better.
Badges:
* Travis CI and GitLab CI -> GitHub Actions.
* Removed Slack and Gitter.
* Google Groups -> GitHub Discussions.
* Added Stack Overflow.
Define Tarantool as in-memory computing platform as on the website.
Added license information.
Appserver:
* Rewrote the sentence regarding compatibility with Lua 5.1 and
highlighted key LuaJIT features instead. There are doubts within the
team about declaring 100% compatibility with …
> readme: actualize without much changes

- changelogs/unreleased/gh-6199-schema-priv-resolve-existence-check.md
- src/box/lua/schema.lua
- test/box-luatest/gh_6199_schema_priv_resolve_existence_check_test.lua
When resolving privileges passed to box.schema.user.grant, we do not
check that all of them have been resolved: check that all privileges
have been resolved and throw an error otherwise.
Closes #6199
> box: check for existence when resolving privileges

- static-build/CMakeLists.txt
To solve #6052 we have to replace `libunwind.dylib` with `libunwind.tbd` for macOS BigSur or higher.
> Fix static build for macOS Bug Sur

- changelogs/unreleased/gh-6786-func-index-iterator-stable.md
- src/box/key_list.c
- src/box/key_list.h
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_tree.cc
- src/box/tuple.c
- src/box/tuple.h
- src/box/tuple_format.h
- src/box/vy_stmt.c
- test/box-luatest/gh-6786_func_index_iterator_stable_test.lua
A memtx tree iterator remembers the last tuple returned to the user and its hint so that it can restore iteration if the index is changed. To prevent the tuple from being freed, it references it. The problem is it's not enough for a functional index, because the latter allocates key parts separately from tuples (it stores pointers to them in memtx tree hints). As a result, if a tuple is deleted from the tree, its key parts will be immediately freed, even if the tuple itself is referenced. Since key parts are necessary to restore an iterator, this results in a use after free bug.
To fix the issue, let's store a copy of the current tuple key part in the iterator along with the tuple. If a key part is small, the copy is stored in a preallocated fixed-size buffer, otherwise it's allocated …
> Fix crash in functional index iterator

- perf/tuple.cc
- src/box/msgpack.c
- test/box/errinj.result
- test/box/errinj.test.lua
- test/unit/CMakeLists.txt
- test/unit/mp_print_unknown_ext.c
- test/unit/mp_print_unknown_ext.result
This patch set includes several fixes:
- fix incorrect resource release in preformance test
- fixed incorrect print of msgpack field with MP_UNKNOWN_EXTENTION type
- add filters in test to remove dependence on tuple size
> Several fixes before implement tuple compression

- changelogs/unreleased/gh_6344_mvcc_txm_story_gc_breaks_memtx_tree_iter.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_6344_mvcc_txm_story_gc_breaks_memtx_tree_iter_test.lua
The MVCC transaction manager story garbage collection introduced a
subtle code dependency: TREE index iterators can get broken (see
definition of “broken” at struct bps_tree_iterator), because the
elements they are referencing can change during story garbage
collection.
We coined the notion “MVCC TRANSACTION MANAGER STORY GARBAGE
COLLECTION BOUND” to refer to this issue explicitly: iterators must not
be used after this point in code.
Closes #6344
> memtx: fix MVCC breaking TREE index iterators

- test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
- test/luatest_helpers/server.lua
Currently, one can only specify a work directory that will be directly
passed to box.cfg (via workdir option passed to luatest.Server, via the
TARANTOOL_WORKDIR environment variable, or via explicitly specifying
work_dir in box.cfg), which implies that the test server will be run in
the specified directory.
One might need to start a Tarantool instance from a certain snapshot or
set of xlogs — for instance, to test Tarantool over an older schema
version.
For diff-tests the test-run harness provided a 'workdir=' option when
calling inspector:cmd('create server ...'), which solved this issue by
copying the specified directory's contents into the test server's
actual working directory (see tarantool/test-run/blob/
d16cbdc2702e7d939d5d34e41730fd83d2c65879/lib/preprocessor.py#L274-L284).
To …
> luatest helpers: add copy directory semantics

- changelogs/unreleased/gh-6817-console-memory-leak.md
- src/box/lua/console.c
- test/app-luatest/gh_6817_console_memory_leak_test.lua
According to the [readline library documentation](https://tiswww.case.edu/php/chet/readline/readline.html#SEC41), the callback passed to `rl_callback_handler_install` is supposed to free the string passed to it:
> As with readline(), the handler function should free the line when it it finished with it.
Our callback leaks it.
Closes #6817
> console: fix memory leak

- src/box/relay.cc
As soon as replica subscribes, relay starts scanning the first requested
WAL file to find the position from which to start replication. While the
scan is in progress, relay never sends heartbeats to the replica, so a
really long scan can make the replica timeout before relay finally finds
the point to replicate from.
Two similar problems were already addressed in
30ad4a5 ("relay: yield explicitly every
N sent rows") and 1728944 ("recovery: make it
yield when positioning in a WAL")
These patches do not fix the issue completely for relay: even though now
it yields while scanning a WAL, it doesn't send heartbeats anyway.
Fix the issue by not only yielding, but sending heartbeats as well while
WAL scan is in progress.
Follow-up #5979
Closes #6706
> Relay: send heartbeats while scanning a WAL

- changelogs/unreleased/gh-4789-net-box-fetch-schema.md
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- test/box-luatest/net_box_test.lua
Before this patch each connection reload server schema if it
changed. However in some cases it's actually redundant e.g. user
performs only call and eval operations. This patch introduces
"fetch_schema" option (true by default to keep backward
compatibility) that allows to ignore schema changes on the server.
As result remote spaces are unavailable and on_schema_reload
trigger doesn't work.
Title: Document fetch_schema netbox option
Currently user could specify "fetch_schema" flag in netbox
connection to control schema fetching from remote instance.
In case if this option is false remote spaces will be unavailable
and on_schema_reload trigger won't work.
```
c = netbox.connect(uri, {fetch_schema = false})
c.space -- always will be nil
c:on_schema_reload(function() …
```
> netbox: allow to disable schema fetch

- tools/gen-release-notes
We're going to reuse the existing [tools/gen-release-notes script](https://github.com/tarantool/tarantool/blob/master/tools/gen-release-notes) for generation of Enterprise Edition (EE) changelogs. To do that, we need to
1. Add `enterprise` to the head of the sections list. The new section will be used by EE changelog entries. We want them to go before open-source changelog entries.
2. Gather changelog entries from the `changelog/unreleased` directory of the superproject directory. EE uses the open-source repository as its submodule.
Needed for https://github.com/tarantool/tarantool-ee/issues/14
> Adapt tool/gen-release-notes for Enterprise Edition changelogs

- src/box/sql.c
The function of the question (`tarantoolsqlIdxKeyCompare()`) compares a
tuple with a key. It extracts necessary fields from the tuple and runs
the compare function, which is basically `memcmp()` of two buffers (for
`varbinary` values -- numeric comparisons are different).
In the Debug build the function also re-verifies the result using a
separate comparison code. And here we compare two `memcmp()` return
values.
We shouldn't do it directly, because `memcmp()` only guarantees sign of
the result. Please, consider the linked issue for details.
NO_DOC=only debug build is affected
NO_CHANGELOG=only debug build is affected
NO_TEST=hard to create a stable reproducer
Fixes #6849
> sql: fix assert when compare a tuple with a key

- test/app-tap/suite.ini
- test/app/suite.ini
- test/box-py/suite.ini
- test/box-tap/suite.ini
- test/box/suite.ini
- test/engine/suite.ini
- test/engine_long/suite.ini
- test/replication-py/suite.ini
- test/replication/suite.ini
- test/sql-tap/suite.ini
- test/sql/suite.ini
- test/swim/suite.ini
- test/vinyl/suite.ini
- test/wal_off/suite.ini
- test/xlog/suite.ini
We have recently dropped 'checksum' machinery in test-run
(tarantool/test-run#321) and now there is no need to keep
checksums in suite.ini config files. So removing them.
Closes tarantool/tarantool-qa#152
> test: remove checksums from suite.ini config files

- src/box/mp_error.cc
- test/unit/mp_error.cc
- test/unit/msgpack.result
Msgpuck is a submodule for tarantool and is needed while packaging.
Moved function of mp_encode_str0() from mp_error.cc into a common
place is msgpuck.h.
Needed for packaging workflow in tarantool/tarantool:
tarantool/tarantool#6260
> Add mp_encode_str0() into msgpuck.h

- changelogs/unreleased/gh-6386-fix-table-equals-for-booleans.md
- src/lua/table.lua
- test/app-tap/table.test.lua
Before this patch comparison of two `false` values produced
incorrect result. That because nil and false are consieded in the
same way by if operator. This patch fixes an issue and introduces
corresponding tests.
Closes #6386
> lua: fix table.equals result when booleans compared

- changelogs/unreleased/inherit-strict-mode-for-tap-subtests.md
- src/lua/tap.lua
- test/app-tap/tap.result
- test/app-tap/tap.test.lua
Previous behaviour was quite illogical and unexpected. If user
once defined strict mode at start of tests it's expected that all
subtests also will have strict mode. However before this patch it
wasn't so. And wasn't clear at start why enabled strict mode
didn't work.
After this patch subtests strict mode will be the same as for
parent. This behaviour wasn't tested anyhow and wasn't documented.
Follow-up #4125
Title: clarify 'strict' behaviour in tap tests
Defined for root tap object strict mode will be the same for all
subtests.
Example:
```lua
t = require('tap').test('123')
t.strict = true
t:is_deeply({a = box.NULL}, {}) -- false
t:test('subtest', function(t)
t:is_deeply({a = box.NULL}, {}) -- also false
end)
```
> tap: inherit strict mode in subtests

- changelogs/unreleased/show-linking-in-tarantool-info.md
- src/lua/init.c
- src/trivia/config.h.cmake
- test/app-tap/info.test.lua
```
tarantool> require('tarantool').build.linking
---
- dynamic
...
```
Useful to run some tests only on static build.
> Show linking type in tarantool.build.linking

- src/CMakeLists.txt
- src/lib/core/CMakeLists.txt
- src/lib/core/ssl.c
- src/lib/core/ssl.h
- src/lib/crypto/crypto.c
- src/lib/crypto/crypto.h
- src/main.cc
- test/unit/CMakeLists.txt
- test/unit/crypto.c
Currently, the library is initialized in lib/crypto. Let's move it to lib/core/ssl, because:
- lib/crypto links lib/core/ssl so it looks more logical to have OpenSSL initialized in the core lib.
- We need to extend the OpenSSL initialization code in the EE build, which doesn't affect lib/crypto, but replaces lib/core/ssl.
While we are at it, let's also allow the EE build to link extra libraries to lib/core by setting `EXTRA_CORE_LINK_LIBRARIES`.
Needed for https://github.com/tarantool/tarantool-ee/issues/40
> Move OpenSSL initialization to lib/core/ssl

- changelogs/unreleased/gh-6664-limit-in-oder-by.md
- src/box/sql/expr.c
- src/box/sql/parse.y
- src/box/sql/select.c
- src/box/sql/sqlInt.h
- test/sql-luatest/gh_6664_allow_limit_in_order_by_test.lua
- test/sql-luatest/suite.ini
- test/sql-tap/orderby8.test.lua
This patch allows LIMIT to be used with a different sort order in
ORDER BY. This is a temporary solution and should be changed after
issue #3309 is fixed.
Closes #6664
> sql: allow LIMIT with different sorting order

- changelogs/unreleased/gh-6778-vinyl-recovery-crash.md
- src/box/vinyl.c
- test/vinyl-luatest/gh_6778_recovery_crash_test.lua
A secondary index creation proceeds as follows:
1. Build the new index by inserting statements from the primary index, see `vinyl_space_build_index()`.
2. Dump the new index and wait for the dump to complete.
3. Commit the index creation record to the WAL.
While the new index is being dumped at step 2, new statements may be inserted into the space. We need to insert those statements during recovery, see `vy_build_recover()`. We identify such statements by comparing LSN to `vy_lsm::dump_lsn`, see `vy_build_recover_stmt()`.
It might occur that the newly built index is empty while the primary index memory level isn't - if all statements cancel each other. In this case, the secondary index won't be dumped during creation and its `dump_lsn` will be set to -1, see the `vy_lsm_is_empty()` check …
> vinyl: fix crash during secondary index recovery

- src/lib/core/fiber.h
Technically the box region always was fiber local. However we had an
idea to make it global in a future, so we left a room in the guarantees
stated by the documentation.
Now I think that we should make it officially fiber local. If it is
global, one can't use it across fiber yields (say, to collect something
from a network).
Also I don't like so vague guarantees. Just hard to use an object, which
is either global or fiber local. Need to interpret a code in the head
twice.
Follows up commit c61179092c08ab1c3e693d4e17b479e119d1b07b ('module api:
expose box region').
Follows up #5273
> module api/doc: bless box region as a fiber region

- changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md
- src/box/sql/vdbe.c
In some cases, when calling a user-defined function, some of the memory
allocated earlier could be lost. This patch fixes this problem.
NO_DOC=No need for doc in this case
NO_TEST=Currently there is no proper way to catch the missing memory
Closes #6789
> sql: fix memory leak when calling user functions

- test/CMakeLists.txt
To build EE tests, we need to add some new CMake variables:
- Set `EXTRA_TEST_SUITES_{BINARY,SOURCE}_DIR` to the binary/source directory that contains extra test suites.
- Set `EXTRA_TEST_SUITES` to the list of extra test suites to build.
For how the new options will be used, see https://github.com/tarantool/tarantool-ee/pull/46
> cmake: allow to add extra test suites to build

- src/lib/core/CMakeLists.txt
- Remove zstd and lz4 from link libraries, because they can be linked by EE via `EXTRA_CORE_LINK_LIBRARIES`.
Follow-up commit 55f968b4474c.
- Add OpenSSL include directories unconditionally, because they are used in the open-source build since commit e5ec324da2b2.
> Cleanup core cmake config

- src/box/memtx_engine.cc
- test/box-luatest/gh_6634_different_log_on_tuple_new_and_free_test.lua
The problem is memtx_tuple_new() says address of memtx_tuple, while
memtx_tuple_delete() says address of an actual tuple (field of memtx_tuple).
Different addresses in logs may be confusing so this patch fixes the problem.
Closes #6634
> memtx: say address of memtx_tuple in memtx_tuple_delete()

- changelogs/unreleased/gh-6882-fix-negative-datetime-intervals.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
Normalization was unnecessary in negative interval values
close to 0. This led to extra second in result, like:
```
tarantool> date.now() - date.now()
---
- -1.000026000 seconds
...
```
We do need to normalize when assign to datetime values, but not for
intermediate intervals.
Closes #6882
> datetime: removed redundant normalization in date intervals

- src/lua/msgpack.c
- test/app-luatest/msgpack_test.lua
The new method copies the given number of msgpack values starting from the iterator cursor position to a new msgpack array object. On success it returns the new msgpack object and advances the iterator cursor. If there isn't enough values to decode, it raises a Lua error and leaves the iterator cursor unchanged.
This function could be implemented in Lua like this:
```lua
function take_array(iter, count)
local array = {}
for _ = 1, count do
table.insert(array, iter:take())
end
return msgpack.object(array)
end
```
Usage example:
```lua
local mp = msgpack.object({10, 20, 30, 40})
local it = mp:iterator()
it:decode_array_header()       -- returns 4
it:decode()                    -- returns 10
local mp2 = it:take_array(2)
mp2:decode()                   -- returns {20, 30}
it:decode() …
```
> msgpack: add iterator.take_array

- .travis.mk
Run `docker run` with `--rm` to prevent wasting disk space
on CI runners.
> Remove stopped docker containers in CI

- src/box/memtx_engine.cc
- src/box/memtx_space.c
- src/box/memtx_tx.c
- src/box/memtx_tx.h
There was no zeroing of the number of compressed tuples in the case of
space truncation. This patch fix this problem.
Follow up #2695
> memtx: fixed incorrect calculation of the number of compressed tuples

- changelogs/unreleased/gh-6144-incorrect-timeout-error.md
- src/box/lua/net_box.c
- test/box/net.box_count_inconsistent_gh-3262.result
- test/box/net.box_discard_gh-3107.result
- test/box/net.box_fiber-async_gh-3107.result
- test/box/net.box_methods_gh-3107.result
- test/box/net.box_raw_response_gh-3107.result
- test/box/net.box_schema_change_gh-3107.result
- test/box/net.box_timeout-gh-3107.result
Fixed bug with the type of the error that occurs when timeout expires in net.box functions.
Closes #6144
> net.box: fix bug with the timeout error type

- changelogs/unreleased/gh-6766-fix-error-in-extension-via-netbox.md
- src/box/bind.c
- test/sql-luatest/gh_6766_mp_ext_via_netbox_test.lua
This patch fixes an assertion or segmentation fault when getting the
value of MP_EXT via netbox.
Closes tarantool#6766
NO_DOC=Bugfix
> sql: fix assert when MP_EXT received via netbox

- changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md
- src/box/schema.cc
- src/box/txn.c
- src/box/txn.h
- test/box/on_replace.result
During ddl operations triggers of old space and new created space
are swapped. This leads to crash in case if this swap occurs from
space on_replace triggers. This patch banned all ddl operations
from on_replace triggers.
Closes #6920
> Fix crash in space on_replace triggers.

- changelogs/unreleased/gh-2717-noquit-on-sigint.md
- src/box/lua/console.c
- src/main.cc
- src/main.h
- test/app-tap/gh-2717-no-quit-sigint.test.lua
- test/app-tap/suite.ini
- test/unit/CMakeLists.txt
- test/unit/box_test_utils.c
Tarantool console quits if you type Ctrl+C.
This patch fixes console behavior on typing Ctrl+C. The patch is intended to make user experience of using tarantool console better.
Relates to #2717
> lua: avoid tarantool console quit if sigint signal sending

- changelogs/unreleased/gh-6305-net-box-autocomplete.md
- src/box/lua/console.c
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- test/app-luatest/gh_6305_autocomplete_metamethod_test.lua
- test/box-luatest/gh_6305_net_box_autocomplete_test.lua
Provide console tab completion support for net.box objects of 'stream' and 'future'.
Closes #6305
> net.box: support tab complete for stream and future v2

- changelogs/unreleased/gh-4675-move-info-messages-to-info-logging-level.md
- src/box/box.cc
- src/box/memtx_engine.cc
- src/box/relay.cc
- src/main.cc
Information messages have been moved from the critical logging level
to info to avoid false alarms when reading logs.
Closes #4675
> log: move info messages to info logging level

- .gitmodules
- CMakeLists.txt
- changelogs/unreleased/add-libunwind-submodule.md
- cmake/BuildLibUnwind.cmake
- cmake/FindLibUnwind.cmake
- cmake/GetLibUnwindVersion.cmake
- cmake/compiler.cmake
- rpm/tarantool.spec
- src/CMakeLists.txt
- src/lib/core/CMakeLists.txt
- static-build/CMakeLists.txt
Investigation of GNU libunwind problems on the aarch64-linux-gnu
platform drive us to the conclusion that libunwind-1.2.1 provided by
major distribution packages is broken. Not to mention that its test
suite fails with SEGFAULTs.
Last but not least, some distributions, e.g. CentOS 8 (see #4611) do
not provide a libunwind package.
Hence, bundle libunwind: bundling is enabled by default on all
platforms, except for macOS — a system package can be used if its
version is greater or equal than 1.3.0 (minimal version that does not
seem to be broken on aarch64-linux-gnu).
* Add new submodule: bump it to current master
* Refactor libunwind package search logic out of compiler.cmake.
* Add CMake script for building bundled libunwind
* Add CMake script for extracting version of libunwind
* …
> libunwind: add new submodule

- .github/actions/environment/action.yml
- .luacheckrc
Bump test-run to new version with the following improvements:
- Add timeout for starting tarantool server (tarantool/test-run#302)
- Kill hanging processes of not started servers (tarantool/test-run#332)
- Rerun all failed tests, not only marked as fragile (tarantool/test-run#329)
Also, set tarantool server start timeout to 290 secs and exclude test-run
tests from validation by luacheck.
NO_DOC=testing
> test-run: bump to new version

- perf/CMakeLists.txt
We should link box_test_utils to tuple perf test to
prevent this error.
Follow up #2717
NO_CHANGELOG=build fix
NO_DOC=build fix
NO_TEST=build fix
> Fix undefined reference to `set_sigint_cb` function

- .travis.mk
The newly released 0.26.0 emits a warning on the `_box` variable.
From luacheck v.0.26.0 release notes:
"Function arguments that start with a single underscore get an "unused hint".
Leaving them unused doesn't result in a warning.
Using them, on the other hand, is a new warning (№ 214)."
NO_DOC=testing
> ci: freeze luacheck version at 0.25.0

- src/lib/core/say.c
- src/lib/core/say.h
> say: move log_vsay to header

- static-build/CMakeLists.txt
zlib.net is unavailable, so we have to download zlib distributions
from a backup storage on VKCS S3.
> build: in static-build download zlib from backup storage

- test/app-luatest/http_client_test.lua
This change tries to fix the following sporadic test error:
[007] not ok 4	http_client.sock_family:"AF_INET".test_cancel_and_errinj
[007] #   ...arantool/tarantool/test/app-luatest/http_client_test.lua:221: Timeout check - status
[007] #   expected: 408, actual: 200
Fixes tarantool/tarantool-qa#154
NO_DOC=testing
> test: fix flaky test_cancel_and_errinj

- src/box/memtx_bitset.cc
- src/box/memtx_bitset.h
- src/box/memtx_engine.cc
- src/box/memtx_hash.cc
- src/box/memtx_hash.h
- src/box/memtx_rtree.cc
- src/box/memtx_rtree.h
- src/box/memtx_space.c
- src/box/memtx_space.h
- src/box/memtx_tree.cc
- src/box/memtx_tree.h
- src/box/memtx_tx.c
- src/box/memtx_tx.h
The PR fixes two issues with tuple compression:
1. Invalid assertion in the memtx transaction manager.
2. Bug in index vtab selection logic.
Needed for https://github.com/tarantool/tarantool-ee/issues/61
Enterprise PR: https://github.com/tarantool/tarantool-ee/pull/62
> Tuple compression fixes

- changelogs/unreleased/gh-6260-add-builtin-events.md
- src/box/alter.cc
- src/box/box.cc
- src/box/box.h
- src/box/lua/watcher.c
- src/box/raft.c
- src/box/replication.cc
- test/box-luatest/gh_6260_add_builtin_events_test.lua
Added predefined system events: box.status, box.id, box.election and
box.schema.
Closes #6260
Title: Built-in events for pub/sub
Built-in events are needed, first of all, in order to learn who is the
master, unless it is defined in an application specific way. Knowing who
is the master is necessary to send changes to a correct instance, and
probably make reads of the most actual data if it is important. Also
defined more built-in events for other mutable properties like leader
state change, his election role and election term, schema version change
and instance state.
Built-in events have a special naming schema - their name always starts
with box.. The prefix is reserved for built-in events. Creating new events
with this prefix is banned. Below is a list of all the …
> net.box: add predefined system events for pub/sub

- src/box/box.h
- src/box/index.h
- src/box/key_def.h
- src/box/lua/tuple.h
- src/box/tuple.h
- src/lib/core/coio.h
- src/lua/utils.h
- src/on_shutdown.h
- src/trivia/util.h
Some fixes have been made according to issue [#6061](https://github.com/tarantool/tarantool/issues/6061):
scenarious is changed to scenarios in `src/box/lua/tuple.h`
Arrat is changed to Array in `src/box/box.h`
Retrive is changed to Retrieve、interator is changed to iterator in `src/box/index.h`
byffer is changed to buffer、zerod-based is changed to zero-based、Interator is changed to iterator in  `src/box/tuple.h`
timeoout  is changed to timeout in `src/lib/core/coio.h`
convertable  is changed to  convertible in `src/lua/utils.h`
macroses is changed to macros、strucrs is changed to structs、indepedent is changed to independent in `src/trivia/util.h`
othrewise is changed to otherwise、hadler is changed to handler in `src/on_shutdown.h`
Absense  is changed to Absence  in ` src/box/key_def.h` …
> Spelling errors in module.h

- cmake/BuildLibCORO.cmake
- cmake/compiler.cmake
- src/lib/core/backtrace.cc
- third_party/coro/coro.c
Fiber call-chains end at `coro_{init, startup}`, but unwinders don't
stop there, trying to use `coro_{init, startup}` stack frame's return
address (which points to some garbage) and, in turn, failing. A similar
issue was experienced by seastar and julia (see JuliaLang/julia#23074
and scylladb/scylla#1909).
In order to make unwinding stop at `coro_{init, startup}`'s stack frame
we need to annotate it with CFI assembly: previously, annotation was
provided only for gcc on x86_64 — also provide it for clang.
For some reason unwinders ignore platform ABIs regarding ending of
call-chains: instead of trying to follow platform ABIs, explicitly
invalidate the topmost (`coro_{init, startup}`) stack frame information
for both x86_64 and AARCH64.
During the context switch required for backtracing a …
> libcoro fibers unwind information fixes

- static-build/CMakeLists.txt
Use a new storage bucket, made specifically for open-source
third-party software distributions.
NO_DOC=testing
> build: in static-build download openSSL from backup storage

- src/lua/digest.c
- src/lua/digest.lua
- test/app-luatest/digest_crc32_recording_test.lua
- test/app/digest.result
There are some issues with crc32 digest builtins implemented via FFI, so
they are rewritted line by line via Lua C API.
NO_DOC=no visible changes
NO_CHANGELOG=no visible changes
> lua: rewrite crc32 digest via Lua C API

- test/replication-py/init_storage.skipcond
Disable the init_storage.test.py test due to the bug #6966.
After a bug fix the test should be enabled again.
> test: disable init_storage.test.py due to bug

- test/replication-py/init_storage.skipcond
Disable the init_storage.test.py test due to the bug #6966.
After a bug fix the test should be enabled again.
NO_DOC=testing stuff
NO_CHANGELOG=testing stuff
NO_TEST=testing stuff
> [1.10] Backport test: disable init_storage.test.py due to bug

- test/replication-py/init_storage.skipcond
Disable the init_storage.test.py test due to the bug #6966.
After a bug fix the test should be enabled again.
NO_DOC=testing stuff
NO_CHANGELOG=testing stuff
NO_TEST=testing stuff
> [2.8] Backport test: disable init_storage.test.py due to bug

- src/lua/digest.c
- src/lua/digest.lua
- test/app-luatest/digest_crc32_recording_test.lua
- test/app/digest.result
As a result of recording <crc32:update> method or <digest.crc32>
function wrong semantics is compiled (strictly saying, the resulting
trace produces the different result from the one yielded by
interpreter). The easiest solution is disabling JIT for particular
functions, however, such approach drops the overall platform
performance. Hence, the mentioned functions are rewritten line by line
via Lua C API to avoid JIT misbehaviour.
NO_DOC=no visible changes
NO_CHANGELOG=no visible changes
(cherry picked from commit 6b9131981f57e72c790561f0b7fdbf9b4a72e787)
> [backport/2.8] lua: rewrite crc32 digest via Lua C API

- changelogs/unreleased/gh-6966-readonly-bootstrap.md
- src/box/applier.cc
- src/box/box.cc
- test/replication-luatest/gh_6966_readonly_bootstrap_test.lua
- test/replication-py/cluster.test.py
- test/replication-py/init_storage.skipcond
- test/replication/gh-5613-bootstrap-prefer-booted.result
- test/replication/gh-5613-bootstrap-prefer-booted.test.lua
- test/replication/suite.ini
When the master is just starting up it's possible for replica's JOIN
request to arrive right in time to bypass ER_LOADING check (after master
is fully recovered) but still fail due to ER_READONLY: box.cfg.read_only
is only read and set after box_cfg() (its C part) returns.
In this case the joining replica simply exits with an error and doesn't
retry JOIN.
Let's fix that. Make ER_READONLY a recoverable error and let replica
retry joining after receiving ER_READONLY.
Anonymous nodes relied on ER_READONLY to forbid replication from
anonymous to normal replicas. That check doesn't work anymore.
So introduce explicit checks banning replication from anonymous nodes.
Note, there were some alternatives to this fix.
First of all, theoretically, we could stop firing ER_LOADING later,
after …
> replication: fix bootstrap failing with ER_READONLY

- changelogs/unreleased/gh-5941-datetime-type-support.md
- cmake/BuildCDT.cmake
- extra/exports
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- src/lib/tzcode/CMakeLists.txt
- src/lib/tzcode/strftime.c
- src/lib/tzcode/strptime.c
- src/lib/tzcode/timelocal.c
- src/lib/tzcode/timelocal.h
- src/lib/tzcode/tzcode.h
- src/lua/datetime.lua
- src/lua/tnt_datetime.c
- test/app-tap/datetime.test.lua
- test/fuzz/CMakeLists.txt
- test/fuzz/datetime_parse_full_fuzzer.c
- test/fuzz/datetime_strptime_fuzzer.c
- test/unit/datetime.c
> _Work in progress - extensive testing to be added!_
`datetime` method to parse date/time iso-8601 (and their extensions) strings. 
`datetime.parse` function expect 1 required argument - which is
input string, and set of optional parameters passed as table
in 2nd argument.
Allowed attributes in this optional table are:
* `format` - should be either 'iso8601', 'rfc3339' or `strptime()`
format string. [strptime format will be added as part of next
commit];
* `tzoffset` - to redefine offset of input string value, if there
is no timezone provided.
* `tz` - human-readable, Olson database, timezone identifier, e.g.
'Europe/Moscow'. Not yet implemented in this commit.
```
tarantool> T = date.parse('1970-01-01T00:00:00Z')
tarantool> T
tarantool> T = …
```
> datetime: parse date/time string - step.3

- src/box/audit.c
- src/box/audit.h
- src/box/box.cc
- src/box/lua/load_cfg.lua
- src/lib/core/util.c
- src/trivia/util.h
- test/app-tap/init_script.result
- test/box/admin.result
- test/box/cfg.result
This PR adds a new configuration option, `box.cfg.audit_format`. The value of this option is never used in the open-source version. It is needed to configure the audit log format in the enterprise version.
EE PR: https://github.com/tarantool/tarantool-ee/pull/70
Needed for https://github.com/tarantool/tarantool-ee/issues/66
> Add box.cfg.audit_format configuration option

- test/CMakeLists.txt
We need to include EXTRA_CORE_INCLUDE_DIRS in order to build unit tests. Including it into test/CMakeLists.txt is useless. Moreover, it may break EE build in case EXTRA_CORE_INCLUDE_DIRS includes a system directory that contains a file that has the same name as one of our internal headers, see https://github.com/tarantool/tarantool-ee/issues/71.
> cmake: don't include EXTRA_CORE_INCLUDE_DIRS in test/CMakeLists.txt

- changelogs/unreleased/gh-6988-support-of-int-dec-to-round.md
- src/box/sql/func.c
- test/sql-luatest/gh_6988_add_round_implementations_test.lua
- test/sql-tap/built-in-functions.test.lua
- test/sql-tap/func.test.lua
- test/sql-tap/metatypes.test.lua
This patch fixes an issue with the implicit cast of INTEGER and DECIMAL
values to DOUBLE when they are passed as the first argument to the
ROUND() function.
Closes #6988
Title: ROUND() now properly supports INTEGER and DECIMAL
INTEGER and DECIMAL values passed as the first argument now will not be
cast to DOUBLE and the result will be of the same type as the first
argument. Also, the default type for the ROUND() is now DECIMAL.
> sql: add support of DECIMAL and INTEGER to ROUND()

- src/box/audit.c
- src/box/audit.h
- src/box/box.cc
- src/box/box.h
- src/box/lua/load_cfg.lua
- test/app-tap/init_script.result
- test/box/admin.result
- test/box/cfg.result
This PR adds a new configuration option, `box.cfg.audit_filter`. The value of this option is never used in the open-source version. It is needed to configure the audit log filter in the enterprise version.
EE PR: https://github.com/tarantool/tarantool-ee/pull/72
Needed for https://github.com/tarantool/tarantool-ee/issues/67
> Add box.cfg.audit_filter configuration option

- test/replication-py/cluster.test.py
In commit c1c77782215e ("replication: fix bootstrap failing with ER_READONLY") seek_once was changed to seek_wait. Seek_once returned a non-negative int on success and -1 if failed, seek_wait returns True on success and False if failed. Therefore no need to compare it to 0 anymore.
> test: fix comparing bool to int in cluster.test.py

- changelogs/unreleased/gh-5747-crash-multiple-args.md
- src/main.cc
- test/app-luatest/gh_5747_crash_multiple_args_test.lua
Tarantool used to crash if launched with multiple -e or -l options without
a space between the option and the value, e.g.: `tarantool -ea -eb`.
It happened because optv[] was allocated for argc==3 items, while 4
options were written to it after parsing (-e, a, -e, b).
This patch allocates optv[] for the maximum possible number of options:
(argc - 1) * 2.
Closes #5747
> app: fix crash with multiple -e -l options

- changelogs/unreleased/gh-7005-session-on-commit-rollback.md
- src/box/session.h
- src/box/txn.c
- test/box-luatest/gh_7005_session_on_commit_rollback_test.lua
- test/luatest_helpers/misc.lua
Commit/rollback triggers are run asynchronously, upon receiving the write status from WAL. We can't run them in the original fiber that submitted the WAL request, because it would open a time window between writing a transaction to WAL and committing it in tx, which could lead to violating the cascading rolback principles. As a result, commit/rollback triggers run with admin privileges.
Let's fix this issue by temporarily setting session and credentials to the original fiber's for running commit/rollback triggers.
Closes #7005
> tx: set session and user for commit/rollback triggers

- .github/workflows/perf_sysbench.yml
- .travis.mk
Unlimited number of make jobs may lead to OOM. We should use
`make -j $(nproc)` instead of `make -j` on Linux. Note, on OSX
and FreeBSD the `nproc` command is unavailable out of the box.
So using `sysctl -n hw.ncpu` instead.
Closes #7020
> ci: specify number of jobs when executing `make`

- changelogs/unreleased/gh-6983-fix-command-in-help-messages.md
- extra/dist/tarantoolctl.in
- test/app-tap/tarantoolctl.test.lua
Currently `tarantoolctl rocks --help` generate such help message:
NAME
/usr/bin/tarantoolctl - LuaRocks main command-line interface
SYNOPSIS
/usr/bin/tarantoolctl [<flags...>] [VAR=VALUE]...
This is wrong.
This patch makes the output look like this:
NAME
/usr/bin/tarantoolctl rocks - LuaRocks main command-line interface
SYNOPSIS
/usr/bin/tarantoolctl rocks [<flags...>] [VAR=VALUE]...
NO_DOC=bugfix
> tarantoolctl: fix command in help messages

- src/box/call.c
- src/box/call.h
- src/box/func.c
- src/box/func.h
- src/box/lua/console.c
- src/box/lua/console.h
- src/box/lua/console.lua
The new triggers will be used in the Enterprise version for logging CALL/EVAL events.
Enterprise part: https://github.com/tarantool/tarantool-ee/pull/83
Needed for https://github.com/tarantool/tarantool-ee/issues/68
> Add CALL/EVAL triggers

- changelogs/unreleased/gh-7014-session-disconnect-peer.md
- src/box/iproto.cc
- src/box/lua/session.c
- src/box/session.cc
- src/box/session.h
- test/box-luatest/gh_7014_session_disconnect_peer_test.lua
- test/box-tap/session.test.lua
`iproto_connection_close()` closes the connection fd and then pushes the disconnect message to tx, which runs session disconnect triggers. As a result, `box.session.peer()` return nil, when called from a `box.session.on_disconnect()` trigger, which prevents us from using the trigger for auditing the disconnect event in the EE version.
Postponing `close()` until after the disconnect triggers have finished wouldn't help, because on OS X and BSD, in contrast to Linux, `getpeername()` fails if the socket was closed by the other end.
To fix this issue, let's store the peer address in the session meta.
Note, we need to remove `box.session.peer()` check from `box-tap/session` test. The check was added by commit https://github.com/tarantool/tarantool/commit/d68050b9b408ceb2accc78b5d66957027d231a43 …
> Fix box.session.peer in box.session.on_disconnect triggers

- .github/workflows/perf_sysbench.yml
This change adds publishing the performance metrics to InfluxDB database
measured by the `sysbench` benchmark.
NO_DOC=ci
NO_TEST=ci
> ci: add publishing perf metrics (perf_sysbench)

- changelogs/unreleased/box-runtime-info-tuple.md
- src/box/lua/slab.cc
- src/box/tuple.c
- src/box/tuple.h
- test/box-luatest/box_runtime_info_tuple_test.lua
It allows to track memory allocated for tuples on runtime arena. It does
not count tuples owned by memtx and vinyl, but tracks so called runtime
tuples. The most common example is a tuple created by the
`box.tuple.new(<...>)` function.
Example:
```lua
tarantool> box.runtime.info().tuple -- 0
tarantool> box.tuple.new({})
tarantool> box.runtime.info().tuple -- 160
tarantool> box.tuple.new({})
tarantool> box.runtime.info().tuple -- 320
tarantool> collectgarbage()
tarantool> box.runtime.info().tuple -- 160
```
Fixes #5872
> lua: track memory occupied by runtime tuples

- .github/workflows/perf_sysbench.yml
This patch makes the perf_sysbench.yml workflow run against the '2.8'
branch. Unfortunately, we need to keep the logic for the '2.8' branch
in the 'master' branch workflow because scheduled workflows cannot be
run on non-default branches even they reside in them [[1]](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule).
So 'matrix' is used to support workflow runs against the '2.8' branch.
Also, let's run the sysbench benchmark 10 times in a row to get average 
numbers and minimise fluctuations in results. 10 iterations take about 1h 
which is more than an acceptable result.
> ci: run sysbench against 2.8 branch

- src/box/box.cc
To audit DML events, we need to install triggers on user spaces not only when a space is created, but also when it's recovered. Let's move audit log initialization before recovery so we can handle it.
Needed for https://github.com/tarantool/tarantool-ee/issues/68
> box: init audit log before recovery

- test/replication/election_qsync_stress.result
- test/replication/election_qsync_stress.test.lua
The test ran for ~40 seconds, and instance logs were filled with
"on_shutdown triggers timed out" messages on each node shutdown.
This is because the test left a lingering netbox connection with a started
but not finished insert into a synchronous space with huge
replication_synchro_quorum. Since the introduction of graceful shutdown
Tarantool tries to wait for a timeout (3 seconds by default) before
stopping the instance, when there are unfinished requests.
There is always an unfinished request in this test by design, so there's
no point in waiting for its completion.
Close the connection explicitly to save a lot of time.
The test includes stopping instances 10 times in a loop, so the test was
slowed down by 30 seconds.
At the moment of writing, the only replication* test, which also has …
> test: speedup replication/election_qsync_stress

- src/box/alter.cc
- src/box/ck_constraint.c
- src/box/field_def.c
- src/box/field_def.h
- src/box/space_def.c
- src/box/space_def.h
- src/box/sql.c
- src/box/sql.h
- src/box/sql/build.c
- src/box/sql/delete.c
- src/box/sql/expr.c
- src/box/sql/fk_constraint.c
- src/box/sql/insert.c
- src/box/sql/parse.y
- src/box/sql/prepare.c
- src/box/sql/resolve.c
- src/box/sql/select.c
- src/box/sql/trigger.c
- src/box/sql/update.c
- src/box/sql/wherecode.c
- src/box/sql/whereexpr.c
- src/box/tuple_format.c
- src/box/tuple_format.h
`field_def`, like any other `_def` struct, is supposed to be plain and simple - it should map data stored in the `_space` system spaces as is. Complex data structures produced from it, like field dictionary or compiled SQL expression should be stored in tuple_field. This simplifies reasoning about the lifetime of this structure:
- If it's allocated on the region, as it is the case, when the structure is created from MsgPack data, it will live until the
region is truncated. It doesn't need to be destroyed in this case.
- If it's allocated on malloc (by a dup function), it should be explicitly deleted with a delete function.
Why we are doing this now: to implement space upgrade, we'll need to add a new member to `space_opts` struct. The new member will be a struct that may store an array of …
> Move default_value_expr from field_def to tuple_field

- changelogs/unreleased/gh-6961-foreign-key-same-space.md
- src/box/lua/schema.lua
- src/box/space.c
- src/box/space_cache.c
- src/box/space_cache.h
- src/box/tuple_constraint_fkey.c
- src/box/tuple_format.c
- test/engine-luatest/gh_6961_fkey_same_space_test.lua
This patch enables creation of a space with a foreign key pointing
to the same space. Such spaces are marked with a `selfpin` flag in
the `space_cache_pin_list`. If a space is pinned only by selfpins,
it is allowed to be deleted from the space cache.
When an old space is replaced by the new one, it's self-pinned for the
second time, then all old pins are moved to the new space's pin list
(see `space_cache_repin_pinned`), then the first self-pin is removed
by `space_cleanup_constraints` of the old space.
Closes https://github.com/tarantool/tarantool/issues/6961
NO_DOC=bugfix
> box: fix space creation with fkey pointing to itself

- src/box/field_def.c
- test/box-luatest/gh_6042_uuid_and_scalar_test.lua
This patch fixes an error that occurred when a UUID index was created
on a SCALAR field or a SCALAR index was created on a UUID field.
Follow-up #6042
NO_DOC=Follow up.
NO_CHANGELOG=Follow up.
> box: fix problem with SCALAR and UUID

- changelogs/unreleased/gh-6923-interval-arithmetic.md
- extra/exports
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- src/lua/datetime.lua
- src/lua/tnt_datetime.c
- src/lua/utils.c
- test/app-tap/datetime.test.lua
- test/luajit-test-init.lua
* All ffi-related defines, necessary for intervals, now created from C-side;
* "Stringization" facilities at `interval_tostring` moved to C;
* Core interval arithmetic routine `datetime_increment_by` moved to C;
Part.1 of #6751 
Followup to b0463da834784cc3b1545661a2ca48900ef54569, as part of #5941
> datetime: move interval arithmetics to C from Lua

- src/box/alter.cc
- src/box/field_def.c
- src/box/field_def.h
- src/box/space.c
- src/box/space_def.c
- src/box/space_def.h
- src/box/sql.c
- src/lib/salad/grp_alloc.h
- test/unit/grp_alloc.c
- test/unit/grp_alloc.result
To implement space upgrade, we need a function that duplicates `field_def` array, because we will store a new space format in space options. To factor out `field_def_array_dup` from `space_def_dup`, let's allocate it with a separate `malloc` rather than after `struct space_def`.
Needed for https://github.com/tarantool/tarantool-ee/issues/94
> Factor out field_def_array_dup

- changelogs/unreleased/gh-5813-resolving-of-c-symbols.md
- src/CMakeLists.txt
- src/lua/init.c
LuaJIT submodule is bumped to introduce the following changes:
* memprof: enrich symtab with newly loaded symbols
* memprof: extend symtab with C symbols
Within this changeset the new Lua module providing minimalistic AVL tree
implementation required for processing C symbols is introduced:
* utils/avl.lua: minimalistic AVL tree implementation
Closes #5813
> luajit: bump new version

- changelogs/unreleased/gh-7025-mvcc-dirty-range.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
MVCC must track a read set of transaction, including cases when
the select returns an empty result. In this case MVCC has two
options: to store a point key if the select has a full key or
to store a gap otherwise.
By a mistake the second variant was not implemented. Fix it now.
Closes #7025
> mvcc: track nothing-found range read

- changelogs/unreleased/gh-6539-log-user-space-empty-or-nil-select.md
- src/box/lua/schema.lua
- src/lua/log.lua
- test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
Introduce module-local S_CRIT alias and add crit function to log module
API.
Needed for #6539
Empty or nil `select` calls on user spaces tend to be
dangerous: we see Tarantool crashing with OOM, or Tarantool becoming
unacceptably slow and its transaction thread utilizing 100% CPU usage.
Also, debugging of such killer-requests is often too painful and
exhausting.
To mitigate this, a critical log entry containing the current stack
traceback is created upon such function calls — a user can explicitly
request a full scan though by passing `fullscan = true` to `select`'s
`options` table argument in which a case a log entry will not be created.
Closes #6539
> Log empty or nil `select` calls

- changelogs/unreleased/gh-7046-fix-nullable-complex-fkeys.md
- src/box/tuple_constraint_fkey.c
- test/engine-luatest/gh_7046_complex_fkey_nullable_test.lua
If a foreign key consists of multiple fields with `is_nullable=true`
attribute, it's OK to insert a tuple with all-zero key, however a
combination of zero and non-zero fields is not allowed.
> box: fix complex foreign keys with nullable fields

- changelogs/unreleased/changed-signedness-of-time64-functions.md
- src/lib/core/clock.c
- src/lib/core/clock.h
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/clock.lua
- src/lua/fiber.lua
- test/app-tap/clock.test.lua
Changed return value type in Lua for the following functions
from `uint64_t` to `int64_t`:
* clock.time64
* clock.realtime64
* clock.monotonic64
* clock.process64
* clock.thread64
* fiber.time64
* fiber.clock64
Changed return value type in Module API for the following functions
from `uint64_t` to `int64_t`:
* fiber_time64
* fiber_clock64
Also enhanced clock.test.lua tap test with more testcases
Due to unsigned values returned from time64 family function time calculations
may lead to undesired value overflows. Having two 64-bit timestamps I cannot
just subtract them without prior comparison. It is used often, for example when
calculating time to a deadline (in queues or for expiration).
Let's measure time, that pass between two sequential clock.time calls:
```lua
tarantool> clock.time() - …
```
> Changed signedness of time64 functions from uint64_t to int64_t

- extra/tf/main.tf
Fix the following error:
{"badRequest": {"message": "The requested availability zone is not
available", "code": 400}}
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/2235977097) for `jepsen-single-instance`.
Manual [test run](https://github.com/tarantool/tarantool/actions/runs/2235964851) for `jepsen-single-instance-txm`.
> ci: fix jepsen testing

- changelogs/unreleased/fix-string-dequoting.md
- src/box/sql/util.c
- test/sql-luatest/gh_7063_dequote_test.lua
Current commit fixes issue #7063 with an incorrect column name in a sub-query projection. For example,
```sql
select "t1".a from (select * from t1) as "t1";
```
returned a result column name `t1` instead of `t1.a` because of incorrect work of a dequoting function. The reason was that
previously `sqlDequote()` function finished its work when found the first closing quote.
Old logic worked for simple selects where the column name doesn't contain an explicit scan name (`"a" -> a`). But for the sub-queries results `sqlDequote()` finished its work right after the scan name (`"t1"."a" -> t1`). Now the function continues its deqouting till it gets the null terminator at the end of the string.
> sql: fix string dequoting

- src/box/sql/sqlInt.h
The problem was detected on MacOS llvm with `-DCMAKE_BUILD_TYPE=Debug` option. Tarantool fails to build because of `-Wnull-pointer-subtraction` warning in `EIGHT_BYTE_ALIGNMENT` macros.
```
/Users/darthunix/git/tarantool/src/box/sql/malloc.c:125:9: error: performing pointer subtraction with a null pointer has undefined behavior [-Werror,-Wnull-pointer-subtraction]
assert(EIGHT_BYTE_ALIGNMENT(p));        /* IMP: R-11148-40995 */
^~~~~~~~~~~~~~~~~~~~~~~
/Users/darthunix/git/tarantool/src/box/sql/sqlInt.h:839:49: note: expanded from macro 'EIGHT_BYTE_ALIGNMENT'
#define EIGHT_BYTE_ALIGNMENT(X)   ((((char*)(X) - (char*)0)&7)==0)
^ ~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/assert.h:99:25: note: expanded from macro …
```
> build: clang fails because of -Wnull-pointer-subtraction

- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/lua/index.c
- src/box/lua/schema.lua
Box read operations (select, min, max, random, pairs) may call a Lua function via Lua C API if space upgrade (EE feature) is in progress. This is forbidden if the original function was called via FFI, see https://github.com/tarantool/luajit/commit/4f4fd9ebeb10d53c8e67f45170938f052818e64e. Let's add helper functions to disable FFI for box read operations. We will use them in EE code.
Needed for https://github.com/tarantool/tarantool-ee/issues/94
> box: add option to disable Lua FFI for read operations

- src/box/alter.cc
`space_upgrade_check_alter()` must be called after the new space definition is updated.
Follow-up commit 38b25832f9fb ("box: add space upgrade stubs").
Needed for https://github.com/tarantool/tarantool-ee/issues/94
> alter: fix space upgrade check

- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .github/workflows/ubuntu_21_04.yml
- .github/workflows/ubuntu_21_10.yml
- .gitlab.mk
- rpm/tarantool.spec
It looks like the simplest solution to deliver gc64 tarantool builds
is to have a separate repo for it. So this patch removes old stuff
related to the 'tarantool-gc64' package and adds the new logic to
store gc64 packages in a separate repo.
Closes: https://github.com/tarantool/tarantool-qa/issues/161
NO_DOC=ci
NO_TEST=ci
Co-authored-by: Yaroslav Lobankov <y.lobankov@tarantool.org>
> ci: use separate repo for gc64 packages 

- .github/workflows/integration.yml
Sometimes we would like to run only integration testing and not touch
other tests. Now it can be done by setting the 'integration-ci' label
on a pull request.
> ci: run integration WF on 'integration-ci' label

- .github/workflows/centos_7.yml
- .github/workflows/centos_8.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_9.yml
- .github/workflows/fedora_30.yml
- .github/workflows/fedora_31.yml
- .github/workflows/fedora_32.yml
- .github/workflows/fedora_33.yml
- .github/workflows/fedora_34.yml
- .github/workflows/fedora_35.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .github/workflows/ubuntu_21_04.yml
- .github/workflows/ubuntu_21_10.yml
- .gitlab.mk
- debian/rules
- rpm/tarantool.spec
This change contains the following improvements:
1. Prettify view in the job list.
Before:
- centos_7 / centos_7 (GC64=OFF)
- centos_7 / centos_7 (GC64=ON)
After:
- centos_7 / centos_7
- centos_7 / centos_7 (gc64)
2. Change possible values for the ${GC64} env variable to
`true/false` instead of `ON/OFF` which is more traditional.
3. Use `-DLUAJIT_ENABLE_GC64=ON` flag in the `debian/rules` and
`rpm/tarantool.spec` files directly instead of providing it
in the workflow files.
Follows-up tarantool/tarantool-qa#159
Follows-up tarantool/tarantool-qa#161
> ci: follow-up improvements for gc64 builds

- src/box/lua/init.c
- src/box/lua/schema.lua
- src/lib/core/fiber_cond.h
- Add `func_id_by_name` to `box.internal`. It will be used in EE.
- Don't call `box.internal.space.upgrade` from `box.schema.space.upgrade` - we will redefine box.schema.space.upgrade in EE instead.
- Add static initializer for `fiber_cond`. It will be used in EE, but it's good to have anyway.
Needed for https://github.com/tarantool/tarantool-ee/issues/94
> Space upgrade related fixes

- test/luatest_helpers/server.lua
It doesn't work, because `fio.rmtree` doesn't accept wildcards. Let's delete the whole server working tree on cleanup.
> test: fix luatest server cleanup

- changelogs/unreleased/gh-7076-tz-attributes.md
- extra/exports
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- src/lib/tzcode/strftime.c
- src/lua/datetime.lua
- src/lua/tnt_datetime.c
- test/app-tap/datetime.test.lua
Since recently we partially support timezone names (e.g. as
abbreviations) so we may modify `tz` attribute support for
datetime constructors or `:set()` operations.
Closes #7076
Relates to #7007
> datetime: handle timezone names in tz

- .github/workflows/perf_sysbench.yml
Since analyzing the performance test results via the workflow artifacts
is quite inconvenient (we need to download the artifact, unpack it, look
through results), we need a more human approach to see the test report.
Moreover, it would be cool to see the performance difference between the
commits.
So this patch adds reporting the performance test results to MyTeam chat
and mailing list. Furthermore, the comparison of test results is added
to the report. Seeing the test report in the chat or mail is very simple
and convenient, plus forever results history as a bonus.
The test report looks something like this:
+----------------------+----------+----------+----------+
|Sysbench              | Curr(rps)| Prev(rps)|     Ratio|
+----------------------+----------+----------+----------+ …
> ci: add performance test reporting for sysbench

- .github/workflows/perf_sysbench.yml
The `${{ github.ref_name }}` expression is always evaluated to 'master'
because the workflow is running on the 'master' branch. But it is wrong
in the case of the '2.10' branch. Now it's fixed.
> ci: fix email subject in perf_sysbench.yml

- changelogs/unreleased/gh-4763-introduce-map-to-sql.md
- src/box/sql/expr.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/box/sql/parse.y
- src/box/sql/sqlInt.h
- src/box/sql/tokenize.c
- src/box/sql/vdbe.c
- test/sql-luatest/bind_test.lua
- test/sql-luatest/map_test.lua
- test/sql-tap/misc1.test.lua
- test/sql/iproto.result
This patch introduces the syntax for the MAP value constructor in SQL.
> sql: syntax for map

- README.FreeBSD
- README.OpenBSD
The unauthenticated git protocol on port 9418 is no longer supported.
> readme: fix repository url

- changelogs/unreleased/gh-6793-datetime-set-with-tzoffset.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
Constructor date.new() and modifier date:set() should always produce same
result for all attributes combinations. Fixed the problem for
`timestamp` with `tzoffset`.
```
tarantool> date.new{ tzoffset = '+0800', timestamp = 1630359071 }
---
- 2021-08-30T21:31:11+0800
...
tarantool> date.new():set{ tzoffset = '+0800', timestamp = 1630359071 }
---
- 2021-08-30T21:31:11+0800
...
```
> Discovered that there was a similar problem with `:set{}` using `tzoffset` attribute not only 
> for `timestamp` but with all the rest date or time attributes. So have modified code flow to
> always "delocalize"/localize time zone upon any relevant attribute manipulation.
Fixes #6793
> datetime: make date.new{} and date:set{} equivalent

- .github/workflows/ubuntu_22_04.yml
- .github/workflows/ubuntu_22_04_aarch64.yml
Add the ubuntu_22_04.yml and ubuntu_22_04_aarch64.yml workflow files to
build Tarantool packages for x86_64 and aarch64 systems.
Closes tarantool/tarantool-qa#237
NO_DOC=ci
NO_TEST=ci
Co-authored-by: Yaroslav Lobankov <y.lobankov@tarantool.org>
> ci: add Ubuntu Jammy (22.04) workflow

- .github/workflows/ubuntu_21_04_aarch64.yml
- .github/workflows/ubuntu_21_10_aarch64.yml
Add the ubuntu_21_04_aarch64.yml and ubuntu_21_10_aarch64.yml workflow
files to build Tarantool packages for the aarch64 system.
Follows-up tarantool/tarantool#5825
Follows-up tarantool/tarantool#6566
NO_DOC=ci
NO_TEST=ci
> ci: add Ubuntu Hirsute/Impish aarch64 workflows

- .github/workflows/ubuntu_20_10.yml
- .github/workflows/ubuntu_20_10_aarch64.yml
Add the ubuntu_20_10.yml and ubuntu_20_10_aarch64.yml workflow files to
build Tarantool packages for x86_64 and aarch64 systems.
Actually, it was already added in https://github.com/tarantool/tarantool/commit/980d7676b97e130b68f945e363e7e8ee08274a33 (2.9.0-100-g980d7676b) in the
scope of https://github.com/tarantool/tarantool/issues/5824 and removed then in https://github.com/tarantool/tarantool/commit/19a161b5f675d628dad2f376fc05b86ea7a81bc1 (2.10.0-beta2-4-g19a161b5f)
and https://github.com/tarantool/tarantool/commit/dc19be406e36bbfa5761a64c2fb53f7c3dd346b1 (2.10.0-beta2-5-gdc19be406).
But, eventually, it was decided to add this workflow again to release
Tarantool packages for Ubuntu Groovy as well.
Follows-up https://github.com/tarantool/tarantool/issues/5824
NO_DOC=ci
NO_TEST=ci …
> ci: add Ubuntu Groovy (20.10) workflow

- src/box/iproto.cc
- test/box-luatest/gh_6890_iproto_error_use_after_free_test.lua
`iproto_write_error()` may reset diag (for example, if the client closes the socket), thus invalidating the error we are going to log and leading to a use after free bug. We must log the error before trying to send it to the client.
The bug was introduced by commit 9b4ab9fe0ef05, which switched `iproto_write_error()` from plain `write()` to the `iostream_write()`, which may set diag.
Closes #6890
Needed for https://github.com/tarantool/tarantool-ee/issues/109
Needed for 2.10
> iproto: log error before iproto_write_error

- changelogs/unreleased/gh-7089-applier-vclock-race.md
- perf/gh-7089-vclock-copy/Makefile
- perf/gh-7089-vclock-copy/Readme.md
- perf/gh-7089-vclock-copy/speedtest.lua
- perf/gh-7089-vclock-copy/swarm.lua
- src/box/applier.cc
- src/box/applier.h
When applier ack writer was moved to applier thread, it was overlooked
that it would start sharing replicaset.vclock between two threads.
This could lead to the following replication errors on master:
relay//102/main:reader V> Got a corrupted row:
relay//102/main:reader V> 00000000: 81 00 00 81 26 81 01 09 02 01
Such a row has an incorrectly-encoded vclock: `81 01 09 02 01`.
When writer fiber encoded the vclock length (`81`), there was only one
vclock component: {1: 9}, but at the moment of iterating over the
components, another WAL write was reported to TX thread, which bumped
the second vclock component {1: 9, 2: 1}.
Let's fix the race by delivering a copy of current replicaset vclock to
the applier thread.
Closes #7089
Part-of tarantool/tarantool-qa#166
NO_DOC=internal fix …
> replication: fix race in accessing vclock by applier and tx threads

- src/box/sql/expr.c
- src/box/sql/mem.c
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- test/sql-luatest/datetime_test.lua
This patch contains one fix and 3 new casts for DATETIME and INTERVAL values.
> Follow-ups for DATETIME and INTERVAL in SQL

- src/box/box.cc
- src/box/index.cc
- src/box/memtx_space.c
- src/box/result.h
If the space is being upgraded, UPDATE/UPSERT requests matching the new space format should work. However, currently they wouldn't work unless the target tuple has already been upgraded, because we don't apply the upgrade function to a tuple fetched from the space before applying UPDATE operations. Fix this.
The fix is only for memtx, because vinyl doesn't support space upgrade yet, see https://github.com/tarantool/tarantool-ee/issues/103.
Needed for https://github.com/tarantool/tarantool-ee/issues/111
> box: apply space upgrade function before updating tuple

- changelogs/unreleased/gh-7113-rev-tree-iters-gap-tracking.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_7113_rev_tree_iters_gap_tracking_test.lua
Apparently, the current implementation of `tree_iterator_start_raw` is
buggy for reverse iterators: instead of tracking gaps for successors of
keys, it tracks gaps for tuples shifted by one to the left of the
successor: reorder the code of `tree_iterator_start_raw` to get
the successor tuple prior to shifting done for reverse iterators and
simplify the implementation to make it more straightforward and thus
comprehensible.
Closes #7073
Closes #7113
> mvcc: fix reverse tree iterators gap tracking

- .github/workflows/fedora_36.yml
- .github/workflows/fedora_36_aarch64.yml
- changelogs/unreleased/add-fedora-36-ci-cd.md
- changelogs/unreleased/add-ubuntu-jammy-ci-cd.md
- rpm/tarantool.spec
Add the fedora_36.yml and fedora_36_aarch64.yml workflow files to build
Tarantool packages for x86_64 and aarch64 systems.
Closes https://github.com/tarantool/tarantool-qa/issues/239
> ci: add Fedora 36 workflow 

- changelogs/unreleased/gh-6251-operator-brackets.md
- extra/addopcodes.sh
- src/box/sql/expr.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/box/sql/parse.y
- src/box/sql/vdbe.c
- test/sql-luatest/containers_test.lua
This patch introduces operator [] that allows to get elements from MAP
and ARRAY values.
Closes #4762
Closes #4763
Part of #6251
Title: Operator [] in SQL
Operator `[]` allows to get an element of MAP and ARRAY values.
Examples:
```
tarantool> box.execute([[SELECT [1, 2, 3, 4, 5][3];]])
---
- metadata:
- name: COLUMN_1
type: any
rows:
- [3]
...
tarantool> box.execute([[SELECT {'a' : 123, 7: 'asd'}['a'];]])
---
- metadata:
- name: COLUMN_1
type: any
rows:
- [123]
...
```
The returned values is of type ANY.
If the operator is applied to a value that is not a MAP or ARRAY or is
NULL, an error is thrown.
Example:
```
tarantool> box.execute([[SELECT 1[1];]])
---
- null
- Selecting is only possible from map and array values
...
```
However, if there are two or more …
> sql: introduce operator []

- CMakeLists.txt
- extra/exports
- src/lua/init.c
luajit: bump submodule
LuaJIT submodule is bumped to introduce the following changes:
* sysprof: change C configuration API
* sysprof: enrich symtab on a new trace or a proto
* sysprof: fix SYSPROF_HANDLER_STACK_DEPTH
* sysprof: make internal API functions static
* sysprof: add LUAJIT_DISABLE_SYSPROF to Makefile
* symtab: check the _GNU_SOURCE definition
Within this changeset Tarantool-specific backtrace handler is introduced
and set to be used by sysprof machinery.
Besides, all new public Lua C API introduced within this changeset is
added to extra/exports.
Follows up #781
NO_CHANGELOG=LuaJIT submodule bump
> luajit: bump submodule

- src/box/applier.cc
- src/box/errcode.h
- src/box/error.cc
- src/lib/core/ssl_error.cc
- src/lib/core/ssl_error.h
- test/box/error.result
- test/unit/CMakeLists.txt
- test/unit/error.c
- test/unit/error.result
A certificate used for an encrypted replication connection may expire, in which case the user will be forced to reconfigure the connection both on the master and on the replica to use the new certificate. If the replica completes the reconfiguration first, it will fail to connect to the master and never retry, even though the master should complete its reconfiguration in a moment.
To avoid that, we should make the applier retry to connect on `SSLError`, just like it does on `SocketError`.
Needed for https://github.com/tarantool/tarantool-ee/issues/107
Needed for 2.10
A test is added in the EE PR: https://github.com/tarantool/tarantool-ee/pull/125
> applier: make SSLError retryable

- changelogs/unreleased/gh-7132-sql-insertion-crash.md
- src/box/sql/insert.c
- test/sql-luatest/gh_7132_insertion_crash_test.lua
Previously SQL didn't validate for all cases, that the amount of the source and destination columns during insertion is equal. The problem was detected when we insert an incorrect amount of values into the table. For example, the query
```sql
insert into t(a) select a, b from t
```
produced an instance crash. Fixed.
NO_DOC=bug fix
> sql: fix insertion crash

- changelogs/unreleased/gh-7125-export-fiber_join_timeout.md
- extra/exports
- test/app-luatest/gh_7125-export-fiber_join_timeout_test.lua
By a mistake it was marked as API_EXPORT but was forgotten to
be added to exports.
Closes #7125
> ffi: export forgotten fiber_join_timeout symbol

- changelogs/unreleased/gh-7210-backtrace-for-fiber_obj-info.md
- src/lua/fiber.c
- test/app-luatest/gh_7210_backtrace_for_fiber_obj_info_test.lua
In b18dd47f50e817be5ef91013c5514fd6226d836d there was introduced a
way to skip backtraces in fiber.info() calls. 9da7e03e88e29b8d38ff8368fda1da4d87f6460b
was introduced `options` function for fiber object that ignored
passed options.
This patch fixed it. Currently fiber:info({backtrace = false})
returns info without backtrace.
Closes #7210
> fiber: don't skip fiber_obj:info() arguments

- changelogs/unreleased/gh-7204-replication-greeting-timeout.md
- src/box/applier.cc
- test/replication-luatest/gh_7204_greeting_timeout_test.lua
A Tarantool server is supposed to send a greeting message right after accepting a new client so the first thing an applier does after connecting to the master is reads the greeting. It does this without timeouts. The problem is that if by mistake we connect to a wrong instance, which doesn't send anything to clients, the applier will hang forever (until the remote closes the socket), without logging any errors.
This may happen even with a valid Tarantool instance - if SSL encryption is enabled on the master, but not on the client, because the SSL protocol assumes that the client initiates a connection by writing to the socket first (before the server).
Let's add a timeout to the operation reading the greeting. The timeout is set to replication_disconnect_timeout(), after which a …
> applier: add timeout to greeting read

- CONTRIBUTING.md
- README.md
GitHub suggests to look on the document, when it is present. The banner is shown for visitors of issues and pull requests pages. We can use this feature to highlight typical stones on the contributor's road.
My goal is to leave suggestions for typical points of a confusion in a short document (don't bury into details) and leave links for further reading.
I hope we should move most of content of the 'open a pull request' section to a wiki page and possibly merge it with [Code-review-procedure][1] and [How to get involved in Tarantool][2]. It requires more work and I would consider it as a future step toward good developer guidelines.
[1]: https://github.com/tarantool/tarantool/wiki/Code-review-procedure
[2]: https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines
> doc: add contributing guide

- .github/workflows/centos_7.yml
- .github/workflows/centos_7_aarch64.yml
- .github/workflows/centos_8.yml
- .github/workflows/centos_8_aarch64.yml
- .github/workflows/debian_10.yml
- .github/workflows/debian_10_aarch64.yml
- .github/workflows/debian_11.yml
- .github/workflows/debian_11_aarch64.yml
- .github/workflows/debian_9.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/fedora_34.yml
- .github/workflows/fedora_34_aarch64.yml
- .github/workflows/fedora_35.yml
- .github/workflows/fedora_35_aarch64.yml
- .github/workflows/fedora_36.yml
- .github/workflows/opensuse_15_1.yml
- .github/workflows/opensuse_15_2.yml
- .github/workflows/ubuntu_16_04.yml
- .github/workflows/ubuntu_18_04.yml
- .github/workflows/ubuntu_20_04.yml
- .github/workflows/ubuntu_20_04_aarch64.yml
- .github/workflows/ubuntu_21_10.yml
- .github/workflows/ubuntu_22_04.yml
- .gitlab.mk
In PR #7090 we forgot to update the path to gather failure artifacts for
many packaging workflows. Now it is fixed.
NO_DOC=ci
NO_TEST=ci
> ci: fix artifacts gathering for package workflows

- changelogs/unreleased/gh-7225-net-box-graceful-shutdown-hang.md
- src/box/lua/net_box.lua
- test/box-luatest/graceful_shutdown_test.lua
- test/box-luatest/net_box_test.lua
The graceful shutdown protocol works as follows:
1. The server sends a shutdown request (the box.shutdown event) to all its clients that subscribed to it.
2. Upon receiving a shutdown request, a client is supposed to close its connection.
3. The server waits for all clients subscribed to box.shutdown event to exit.
4. The server exits.
In net.box, the box.shutdown event is processed by `remote._callback`. The problem is it may occur that `remote._callback` is garbage collected while the `remote` object isn't. If this happens, the shutdown request will never get processed, and the server won't exit until the `remote` object is garbage collected, which may take forever.
Let's fix this issue by breaking the worker loop if we see that the callback was garbage collected.
Closes #7225
> net.box: fix hang in graceful shutdown protocol

- changelogs/unreleased/gh-7045-interval-nanoseconds.md
- src/lib/core/datetime.c
- test/app-tap/datetime.test.lua
- test/sql-luatest/interval_test.lua
Do not even try to humanize secs/nsec output, but rather
output them directly as is, without any [de]normalization.
Closes #7045
> datetime: do not mess with nsec in interval

- test/replication-py/suite.ini
- test/swim/suite.ini
To reduce the chance to encounter the tarantool/test-run#141 issue in
replication-py/swim tests, let's switch to using unix sockets instead
of TCP ports for tarantool console.
NO_DOC=testing stuff
NO_TEST=testing stuff
NO_CHANGELOG=testing stuff
> test: use unix sockets in replication-py tests

- changelogs/unreleased/gh-6377-decimal-index-comparison.md
- src/box/tuple_compare.cc
- test/engine-luatest/gh_6377_decimal_compare_inf_crash_test.lua
There was an assertion failure when inserting  a decimal into an index
which contained double Inf or NaN.
The reason for that was never checking decimal_from_*() return values,
and decimal_from_double() not being able to handle NaN or Inf, because
these values are not representable in decimal numbers.
Start handling decimal_from_<type> return values and fix decimal
comparison with Inf, NaN.
Closes #6377
> decimal: fix index comparison with Inf, NaN

- changelogs/unreleased/gh-7043-ephem-space-format.md
- src/box/sql/select.c
- test/sql-luatest/gh_7043_temp_space_format_test.lua
This patch fixes format building when an ephemeral space was used in
ORDER BY and ORDER BY uses at least two variables from the list of
selected columns.
Closes #7042
NO_DOC=Bugfix
> sql: fix wrong ephemeral space format

- changelogs/unreleased/gh-7256-iostream-shutdown.md
- src/lib/core/iostream.c
- test/box-luatest/graceful_shutdown_test.lua
- test/instances/default.lua
If a socket fd is shared by a child process, closing it in the parent will not shut down the underlying connection. As a result, the server may hang executing the graceful shutdown protocol. Fix this problem by explicitly shutting down the connection socket fd before closing it.
This is a recommended way to terminate a Unix socket connection, see http://www.faqs.org/faqs/unix-faq/socket/#:~:text=2.6.%20%20When%20should%20I%20use%20shutdown()%3F
While we are at it, let's also set the shutdown timeout for instances created by Luatest to infinity so that we can catch bugs like this early.
Closes #6820
Closes #7256
> iostream: shutdown socket fd before close

- test/vinyl/tx_gap_lock.result
- test/vinyl/tx_gap_lock.test.lua
The `cmp_tuple` helper function is broken - it assumes that all tuple fields, including the payload, are numeric. It isn't true - the payload field is either nil or string. This results in a false-positive test failure:
```
error: '[string "function cmp_tuple(t1, t2)     for i = 1, PAY..."]:1:
attempt to compare nil with string'
```
Closes #6336
> test: fix flaky viny/tx_gap_lock test

- changelogs/unreleased/gh-7238-fix-conflicted-txs-in-memtx-ro-operations.md
- changelogs/unreleased/gh-7240-conflicted-transactions-error-on-all-crud-operations.md
- src/box/txn.c
- src/box/txn.h
- src/box/vy_tx.c
- test/box-luatest/gh_6246_mvcc_different_select_behavior_test.lua
- test/box-luatest/gh_6930_mvcc_isolation_levels_test.lua
- test/box-luatest/gh_6930_mvcc_net_box_iso_test.lua
- test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
- test/box/tx_man.result
- test/engine-luatest/gh_7238_memtx_fix_conflicted_txs_ro_operations_test.lua
- test/engine-luatest/gh_7239_rv_txs_conflict_on_dml_test.lua
- test/vinyl/deferred_delete.result
- test/vinyl/hermitage.result
- test/vinyl/iterator.result
Currently, there is a fundamental logical inconsistency with read-view and
conflicted states of transactions.
Conflicted transactions see all prepared changes (e.g., #7238), because
they are handled differently than read-view ones. At the same time, one
does not know the state of the transaction until `box.commit` is called.
A similar problem arises with read-view transactions: if such transactions
do any DML statements, they are de-facto conflicted, but this will only be
determined at preparation stage:
https://github.com/tarantool/tarantool/blob/79245573dabf3c1eb4eb904fd80ee84270360476/src/box/txn.c#L1006-L1013
Fix this inconsistency by the following changes:
1. Conflict "read-view" transactions on attempt to perform DML statements
immediately — guarantee this with an assertion at …
> box: fix transaction "read-view" and "conflicted" states

- changelogs/unreleased/fix-relay-being-stuck.md
- changelogs/unreleased/gh-5295-split-brain-detection.md
- src/box/applier.cc
- src/box/box.cc
- src/box/errcode.h
- src/box/memtx_engine.cc
- src/box/raft.c
- src/box/relay.cc
- src/box/relay.h
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- test/box/error.result
- test/replication-luatest/gh_5295_split_brain_test.lua
- test/replication-luatest/gh_6036_qsync_order_test.lua
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/suite.ini
- test/replication/gh-5140-qsync-casc-rollback.result
- test/replication/gh-5140-qsync-casc-rollback.test.lua
- test/replication/gh-5163-qsync-restart-crash.result
- test/replication/gh-5163-qsync-restart-crash.test.lua
- test/replication/gh-5288-qsync-recovery.result
- test/replication/gh-5288-qsync-recovery.test.lua
- test/replication/gh-5298-qsync-recovery-snap.result
- test/replication/gh-5298-qsync-recovery-snap.test.lua
- test/replication/gh-5874-qsync-txn-recovery.result
- test/replication/gh-5874-qsync-txn-recovery.test.lua
- test/replication/suite.cfg
Split-brain machinery: filters that monitor PROMOTE, DEMOTE, CONFIRM, ROLLBACK coming from remote nodes, and raise an error, when the requests are conflicting with the node's local state.
Note, any asynchronous transaction coming from an obsolete journal term is treated as a sign of split-brain.
Closes #5295
Closes #6133
> Split brain detection

- changelogs/unreleased/gh-5843-fiber-wakeup.md
- src/lib/core/fiber.c
- test/unit/fiber.cc
- test/unit/fiber.result
When fiber has finished its work it ended up in two cases:
1) If no "joinable" attribute set then the fiber is
simply recycled
2) Otherwise it continue hanging around waiting to be
joined.
Our API allows to call fiber_wakeup() for dead but joinable
fibers (2) in release builds without any side effects, such
fibers are simply ignored, in turn for debug builds this
cause assertion to trigger. We can't change our API for
backward compatibility sake but same time we must not
preserve different behaviour between release and debug
builds since this brings inconsistency. Thus lets get
rid of assertion call and allow to call fiber_wakeup
in debug build as well.
Fixes #5843
NO_DOC=bug fix
Signed-off-by: Cyrill Gorcunov <gorcunov@gmail.com>
> fiber: don't crash on wakeup with dead fibers

- .travis.mk
- cmake/BuildAres.cmake
- cmake/BuildLibCURL.cmake
- cmake/BuildLibUnwind.cmake
- cmake/BuildNghttp2.cmake
- cmake/rpm.cmake
NOTE: For building Tarantool with Ninja it is needed to apply patch to LuaJIT - 
https://lists.tarantool.org/tarantool-patches/ee1a1146963fe6aad5bff59884e00b6cf24eaf1a.1653307030.git.sergeyb@tarantool.org/T/#u
Branch: https://github.com/tarantool/luajit/tree/ligurio/ninja-support
----------------
By default, CMake generates Makefiles for building a project. However, it
allows generating Ninja files. Ninja [1] may build project a bit faster
than Make, see [2]. Patch adds fixes for CMake files allowing to use
Ninja for building Tarantool.
There are two kind of fixes:
1. Fix dependencies in `ExternalProject_Add()`, see explanation in [3]
2. Fix '$' symbols in `cmake/rpm.cmake`
How-to build wit Ninja:
```sh
$ cmake -G Ninja -B build -S .
$ ninja -C build/
```
On my laptop Ninja reduces …
> cmake: support build using Ninja

- src/box/vy_tx.c
- test/vinyl-luatest/gh_7240_abort_yielding_dml_test.lua
Commit 4d52199e9041 updated `vy_tx_send_to_read_view` so that now it aborts all RW transactions right away instead of sending them to read view and aborting them on commit. It also updated `vy_tx_begin_statement` to fail if a transaction sent to a read view tries to do DML. With all that, we assume that there cannot possibly be an RW transaction sent to read view so we have an assertion checking that in `vy_tx_commit`.
However, this assertion may fail, because a DML statement may yield on disk read before it writes anything to the write set. If this is the first statement in a transaction, the transaction is technically read-only and we will send it to read-view instead of aborting it. Once it completes the disk read, it will apply the statement and hence
become read-write, breaking our …
> vinyl: fix `!vy_tx_is_in_read_view` assertion failure in `vy_tx_prepare`

- .github/workflows/luajit-integration.yml
- .travis.mk
This patch introduces reusable workflow used by integration testing
machinery run within tarantool/luajit repository.
For the first attempt GitHub action has been used, but its fetch (or
more precisely unpack) phase fails due to test/test-run.py symlink into
test-run submodule (the action being used doesn't fetch it while packing
tarantool repository). As the alternative for removing this symlink, it
was decided to use reusable workflows despite its known limitations
(e.g. inability to use the testing matrix) until the issue with symlink
is resolved in any possible way.
NO_DOC=ci
NO_TEST=ci
---
You can find the usage of the new workflow [here](https://github.com/tarantool/luajit/commit/765a0ce).
> ci: add workflow for LuaJIT integration tests

- src/box/memtx_tx.c
- test/box-luatest/gh_7221_memtx_tx_dml_self_conflict_after_fsc_in_hash_idx_test.lua
- test/box-luatest/memtx_tx_dml_self_conflict_after_selecting_same_key_test.lua
When full scans are checked on writes, we must only conflict transactions
other than the one that did the full scan.
Closes #7221
On insertion, when point holes are checked on insertion, we must only
conflict transactions other than the one that read the hole.
NO_CHANGELOG=internal bugfix
NO_DOC=bugfix
Closes #7234
Closes #7235
We assume that a transaction cannot conflict itself and that only a
non-prepared transaction can be conflicted: track these assumptions with
appropriate assertions.
> memtx: fix self-conflicting of transactions

- changelogs/unreleased/gh-5861-exclude-null.md
- src/box/index.cc
- src/box/index.h
- src/box/key_def.h
- src/box/memtx_tree.cc
- src/box/tuple_extract_key.cc
- src/box/vinyl.c
- src/box/vy_stmt.h
- test/engine-luatest/gh_5861_exclude_null_test.lua
- test/engine/null.result
- test/engine/null.test.lua
`exclude_null` is a special index option, which makes the index ignore tuples that contain null in any of the indexed fields. Currently, it doesn't work for json and multikey indexes, because:
1. `index_filter_tuple` ignores json path.
2. `index_filter_tuple` ignores multikey index.
Issue no. 1 is easy to fix - we just need to use `tuple_field_by_part` instead of `tuple_field` when checking if a key field is null.
Issue no. 2 is more complicated, because when we call `index_filter_tuple` we don't know the multikey index. We address this issue by pushing the `index_filter_tuple` call down to engine-specific index implementation.
For Vinyl, we make `vy_stmt_foreach_entry`, which iterates over multikey tuple entries, skip entries that contain nulls.
For memtx, we move the check to …
> box: fix exclude_null for json and multikey indexes

- changelogs/unreleased/gh-7207-backtrace-perf-degrade.md
- cmake/BuildLibUnwind.cmake
- src/lib/core/CMakeLists.txt
- src/lib/core/backtrace.c
- src/lib/core/backtrace.h
- src/lib/core/proc_name_cache.cc
- src/lib/core/proc_name_cache.h
Procedure name hash table was removed during refactoring in 8ce76364 based
off the interpretation that libunwind caches procedure names internally —
turned out it only caches unwinding info, which causes a severe performance
downgrade (gh-7207): return procedure name hash table to speed up frame
resolving.
Closes #7207
> core: return procedure name hash table to speed up frame resolving

- src/box/raft.c
- src/box/txn_limbo.c
- src/lib/core/fiber.c
See commit messages.
Part of #7166
> Get rid of fiber_set_cancellable in txn_limbo and raft

- changelogs/unreleased/gh-5358-net-box-sync-request-in-trigger.md
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- test/box-luatest/net_box_test.lua
Net.box triggers (`on_connect`, `on_schema_reload`) are executed by the net.box connection worker fiber so a request issued by a trigger callback can't be processed until the trigger returns execution to the net.box fiber. Currently, an attempt to issue a synchronous request from a net.box trigger leads to a silent hang of the connection, which is confusing. Let's instead raise an error until #7291 is implemented.
We need to add the check to three places in the code:
1. `luaT_netbox_wait_result` for `future:wait_result()`
2. `luaT_netbox_iterator_next` for `future:pairs()`
3. `conn._request` for all synchronous requests.
(We can't add the check to `luaT_netbox_transport_perform_request`, because `conn._request` may also call `conn.wait_state`, which would hang if called from `on_connect` …
> net.box: explicitly forbid synchronous requests in triggers

- changelogs/unreleased/gh-7298-datetime-set-with-hour-nil.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
We did not retain correctly `hour` attribute if modified
via `:set` method attributes `min`, `sec` or `nsec`.
```
tarantool> a = dt.parse '2022-05-05T00:00:00'
tarantool> a:set{min = 0, sec = 0, nsec = 0}
--
- 2022-05-05T12:00:00Z
...
```
Closes #7298
> datetime: fix for setting when `hour=nil`

- src/box/box.cc
- src/lib/core/fiber.c
- src/main.cc
Fiber module was not destroyed before return from `main()`. That made all the resources allocated for the main cord leak. Apparently, it was either fine for ASAN for quite some time, or it wasn't and the problem was noticed just now. Anyway, fiber `on_stop` trigger was reported as leaking. The patchset fixes this particular issue.
But it also discovers a much bigger problem with what a mess is our current process cleanup code. Here is a cite from the second commit's message with first and biggest problems which I could spot:
```
There are still a lot of other modules whose freeing is not that
easy. A few hard to untangle knots, and there are more:
- Session, credentials, iproto, and fibers are tied together via
the latter. Each fiber potentially has a session, its current
credentials …
```
> Destroy main cord on return from main()

- changelogs/unreleased/gh-4573-implement-fiber-top-for-arm.md
- changelogs/unreleased/gh-5869-fix-crash-without-rdtscp.md
- changelogs/unreleased/gh-5869-remove-fiber-top-cpu_misses.md
- src/lib/core/clock.c
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
- test/app/fiber.result
- test/app/fiber.test.lua
clock_gettime(CLOCK_MONOTONIC) is implemented via the RDTSCP instruction
on x86 an has the following advantages over the raw instruction:
* It checks for RDTSCP availability in CPUID.
If RDTSCP is not supported, it switches to RDTSC.
* Linux guarantee that clock is monotonic, hence, the CPU miss
detection is not needed.
* It works on ARM.
As for disadvantage, this function is about 2x slower compared to a
single RDTSCP instruction. Performance degradation measured by the
[fiber switch benchmark](https://github.com/tarantool/tarantool/issues/2694#issuecomment-546381304) is about 7% for num_fibers = 100/1000.
Closes #4573
Closes #5869
> Fix a crash on x86 systems without `RDTSCP` instruction

- changelogs/unreleased/gh-7292-fix-gcc-build-with-libbpf-installed.md
This will fix compilation on recent Archlinux. The issue is this distro
installs libbpf in base configuration and nghttp2 1.46.0 tries to
compile eBPF code if this library is present and failed if compiler is
gcc.
Closes #7292
> third_party: update nghttp2 from 1.46.0 to 1.47.0

- changelogs/unreleased/gh-3638-vy-defer-deletes-and-upserts.md
- src/box/vinyl.c
- test/vinyl-luatest/gh_3638_defer_deletes_and_upserts_test.lua
Normally, there shouldn't be any upserts on disk if the space has secondary indexes, because we can't generate an upsert without a lookup in the primary index hence we convert upserts to replace+delete in this case. The deferred delete optimization only makes sense if the space has secondary indexes. So we ignore upserts while generating deferred deletes, see `vy_write_iterator_deferred_delete`.
There's an exception to this rule: a secondary index could be created after some upserts were used on the space. In this case, because of the deferred delete optimization, we may never generate deletes for some tuples for the secondary index, as demonstrated in #3638.
We could fix this issue by properly handle upserts in the write iterator while generating deferred delete, but this wouldn't be …
> vinyl: disable deferred deletes if there are upserts on disk

- changelogs/unreleased/gh-6548-luajit-fixes.md
* Avoid conflict between 64 bit lightuserdata and ITERN key.
* Reorganize lightuserdata interning code.
* test: fix path storage for non-concatable objects
* ARM64: Fix assembly of HREFK.
* FFI/ARM64: Fix pass-by-value struct calling conventions.
* test: set DYLD_LIBRARY_PATH environment variable
* x64/LJ_GC64: Fix fallback case of asm_fuseloadk64().
* FFI: Handle zero-fill of struct-of-NYI.
* Fix interaction between profiler hooks and finalizers.
* Flush and close output file after profiling run.
* Fix debug.debug() for non-string errors.
* Fix write barrier for lua_setupvalue() and debug.setupvalue().
* Fix FOLD rule for strength reduction of widening.
* Fix bytecode dump unpatching.
* Fix tonumber("-0") in dual-number mode.
* Fix tonumber("-0").
* Give expected results for negative …
> [backport/2.10] luajit: bump new version

- changelogs/unreleased/gh-6548-luajit-fixes.md
* test: fix path storage for non-concatable objects
* test: set DYLD_LIBRARY_PATH environment variable
* x64/LJ_GC64: Fix fallback case of asm_fuseloadk64().
* FFI: Handle zero-fill of struct-of-NYI.
* Fix interaction between profiler hooks and finalizers.
* Flush and close output file after profiling run.
* Fix debug.debug() for non-string errors.
* Fix write barrier for lua_setupvalue() and debug.setupvalue().
* Fix FOLD rule for strength reduction of widening.
* Fix bytecode dump unpatching.
* Fix tonumber("-0") in dual-number mode.
* Fix tonumber("-0").
* Give expected results for negative non-base-10 numbers in tonumber().
* Add missing LJ_MAX_JSLOTS check.
* Add stricter check for print() vs. tostring() shortcut.
Closes #6548
Fixes #4614
Fixes #4630
Fixes #5885
Fixes …
> [backport/1.10] luajit: bump new version

- changelogs/unreleased/gh-5700-vy-fix-read-stalled-by-write.md
- src/box/vy_read_iterator.c
The Vinyl read iterator, which is used for serving range select requests, works as follows:
1. Scan in-memory sources. If found an exact match or a chain in the cache, return it.
2. If not found, scan disk sources. This operation may yield.
3. If any new data was inserted into the active memory tree, go to step 1, effectively restarting the iteration from the same key.
Apparently, such an algorithm doesn't guarantee any progress of a read operation at all - when we yield reading disk on step 2 after a restart, even newer data may be inserted into the active memory tree, forcing us to restart again. In other words, in presence of an intensive write workload, read ops rate may drop down to literally 0.
It hasn't always been like so. Before commit 83462a5cf163, we only restored the memory …
> vinyl: fix read stalled by write

- test/replication-luatest/election_pre_vote_test.lua
The test failed at the moment when one of the followers disconnects from
the leader and expects its `box.info.election.leader_idle` to grow.
It wasn't taken into account that this disconnect might lead to leader
resign due to fencing, and then a new leader would emerge and
`leader_idle` would still be small.
IOW, leader resumes fencing, once it has connected to at least one
replica in this test. If this replica happens to be the one we
disconnect, the leader might fence, since it hasn't yet connected to the
other replica and has thus lost the quorum of connections.
Fix this by waiting until everyone follows everyone in the test.
The test, of course, could be fixed by turning fencing off, but this
might hide any possible future problems with fencing.
Follow-up #6654
Follow-up #6661 …
> test: fix election_pre_vote flaky failure

- cmake/profile.cmake
- src/main.cc
- src/trivia/util.h
__gcov_flush was removed in gcc11.
Since gcc11 __gcov_dump calls __gcov_lock at the start and __gcov_unlock before returning. Same is true for __gcov_reset. Because of that using __gcov_reset right after __gcov_dump since gcc11 is the same as using __gcov_flush before gcc11.
Closes #7302
> gcov: use __gcov_dump + __gcov_reset instead of __gcov_flush

- changelogs/unreleased/gh-5226-tuple-access-by-any-token.md
- src/lib/json/json.h
- test/box-luatest/gh_5226_tuple_access_by_any_token_test.lua
- test/unit/json.c
If a nested tuple field is indexed, it can be accessed by [*] aka multikey or any token:
```Lua
s = box.schema.create_space('test')
s:create_index('pk')
s:create_index('sk', {parts = {{2, 'unsigned', path = '[1][1]'}}})
t = s:replace{1, {{1}}}
t['[2][1][*]'] -- returns 1!
```
If a nested field isn't indexed (remove creation of the secondary index in the example above), then access by [*] returns nil.
Call graph:
```
lbox_tuple_field_by_path:
tuple_field_raw_by_full_path
tuple_field_raw_by_path
tuple_format_field_by_path
json_tree_lookup_entry
json_tree_lookup
```
And `json_tree_lookup` matches the first node if the key is [*]. We shouldn't match anything to [*].
Closes #5226
> json: don't match any nodes if there's [*] in the path

- changelogs/unreleased/gh-6565-vy-hot-standby-unsupported.md
- src/box/recovery.cc
- src/box/vinyl.c
- test/vinyl-luatest/gh_6565_hot_standby_unsupported_test.lua
Vinyl doesn't support the hot standby mode. There's a ticket to implement it, see #2013. The behavior is undefined if running an instance in the hot standby mode in case the master has Vinyl spaces. It may result in a crash or even data corruption.
Let's raise an explicit error in this case.
Closes #6565
> vinyl: explicitly disable hot standby mode

- .github/workflows/reusable_build.yml
- .gitignore
- debian/control
- debian/rules
- rpm/tarantool.spec
- test/CMakeLists.txt
- test/small
Now the test-run dependencies (pyyaml, gevent) have the corresponding
deb packages installable via the 'apt' package manager and finally it's
time to enable running tests in the package build process.
Closes #1341
> ci: enable tests for Debian

- changelogs/unreleased/gh-7286-false-positive-split-brain.md
- src/box/applier.cc
- src/box/txn_limbo.h
- test/replication-luatest/gh_7286_split_brain_false_positive_test.lua
Our txn_limbo_is_replica_outdated check works correctly only when there
is a stream of PROMOTE requests. Only the author of the latest PROMOTE
is writable and may issue transactions. No matter synchronous or
asynchronous.
So txn_limbo_is_replica_outdated assumes that everyone but the node with
the greatest PROMOTE/DEMOTE term is outdated.
This isn't true for DEMOTE requests. There is only one server which
issues the DEMOTE request, but once it's written, it's fine to accept
asynchronous transactions from everyone.
Now the check is too strict. Every time there is an asynchronous
transaction from someone, who isn't the author of the latest PROMOTE or
DEMOTE, replication is broken with ER_SPLIT_BRAIN.
Let's relax it: when limbo owner is 0, it's fine to accept asynchronous
transactions from …
> Fix false-positive ER_SPLIT_BRAIN after processing a DEMOTE request.

- src/box/CMakeLists.txt
- src/box/applier.cc
- src/box/iproto.cc
- src/box/lua/session.c
- src/box/session.c
- src/box/session.h
- src/box/space_cache.h
- src/box/user.h
- src/lib/core/diag.h
- src/trivia/util.h
`current_session()` is called from C code so it must not throw, but it may if it fails to allocate a session. Practically, this is hardly possible, because we don't limit the runtime arena, which is used for allocation of session objects. Still, this looks potentially dangerous.
Gracefully handling an allocation failure in all places where `current_session()` may be called would be complicated. Since it's more of a theoretical issue, let's panic on a session allocation error, like we do if we fail to allocate other mission critical system objects.
Closes #4735
> session: panic if failed to allocate session

- .travis.mk
- src/box/lua/net_box.lua
Since 0.26.0 luacheck emits a warning on the `_box` variable.
From luacheck v.0.26.0 release notes:
"Function arguments that start with a single underscore get an "unused hint". Leaving them unused doesn't result in a warning. Using them, on the other hand, is a new warning (№ 214)."
Renamed `_box` to `__box`, which works just fine and updated luacheck to 0.26.1 in CI.
Closes #7304
> luacheck: fix W214 for src/box/lua/net_box.lua

- test/vinyl-luatest/select_consistency_test.lua
- test/vinyl-luatest/suite.ini
The idea behind the new test is the same as the one used by `vinyl/select_consistency.test.lua`: create a space with a few
compound secondary indexes that share the first part, then run SELECT requests under heavy write load and check that results match. However, in comparison to its predecessor, the new test has a few improvements:
1. It generates DML requests in multi-statement transactions.
2. It checks non-unique indexes.
3. It checks multikey indexes.
4. It triggers L0 dumps not by box.snapshot, but by exceeding the `box.cfg.vinyl_memory` limit.
5. It starts 20 write and 5 read fibers.
6. It reruns the test after restart to check that recovery works fine.
7. It checks that there's no phantom statements stored in the space indexes after the test.
8. It runs the test with deferred …
> test: add improved test for SELECT consistency

- test/vinyl-luatest/update_optimize_test.lua
Normally, if a server created by a test isn't stopped it should be forcefully killed by luatest or test-run. For some reason, it doesn't happen sometimes, which may lead to the next test failing to bind, because all test servers that belong to the same luatest suite and have the same alias share the same socket path (although they use different
directories). This looks like a test-run or luatest bug.
The `vinyl-luatest/update_optimize` test doesn't stop the test server so because of this test-run/luatest bug, the next vinyl-luatest test fails occasionally:
```
[001] vinyl-luatest/update_optimize_test.lua                          [ pass ]
[001] vinyl-luatest/gh_6568_replica_initial_join_rem>                 [ fail ]
[001] Test failed! Output from reject file …
```
> test: stop server started by `vinyl-luatest/update_optimize` test

- changelogs/unreleased/gh-7214-repeatable-replace-assertion.md
- changelogs/unreleased/gh-7217-repeatable-{in, up}sert-memtx-tx-conflict.md
- src/box/memtx_tx.c
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/gh_7214_repeatable_replace_assertion_test.lua
- test/box-luatest/gh_7217_repeatable_{in, up}sert_memtx_tx_conflict_test.lua
Current implementation of tracking statements that delete a story has a
flaw, consider the following example:
tx1('box.space.s:replace{0, 0}') -- statement 1
tx2('box.space.s:replace{0, 1}') -- statement 2
tx2('box.space.s:delete{0}') -- statement 3
tx2('box.space.s:replace{0, 2}') -- statement 4
When statment 1 is prepared, both statements 2 and 4 will be linked to the
delete statement list of {0, 0}'s story, though, apparently, statement 4
does not delete {0, 0}.
Let us notice the following: statement 4 is "pure" in the sense that, in
the transaction's scope, it is guaranteed not to replace any tuple — we can
retrieve this information when we check where the insert statement violates
replacement rules, use it to determine "pure" insert statements, and skip
them later on when, during …
> memtx: fix story delete statement list

- test/app-tap/gh-2717-no-quit-sigint.test.lua
If readline 'show-mode-in-prompt' is on then test fails because it does
not handle prefix added to prompt in this mode. Let's use default
(compiled in) readline configuration instead of the one provided by
user or system config.
NO_DOC=test changes
NO_CHANGELOG=test changes
NO_TEST=test changes
> test: use default readline configuration for a test

- .travis.mk
This patch fixes the following issue:
Installing collected packages: greenlet, gevent
Attempting uninstall: greenlet
Found existing installation: greenlet 0.4.15
ERROR: Cannot uninstall 'greenlet'. It is a distutils installed
project and thus we cannot accurately determine which files
belong to it which would lead to only a partial uninstall.
make: *** [.travis.mk:86: deps_tests] Error 1
Error: Process completed with exit code 2.
This happens because the `python3-gevent` package is installed via the
`apt` package manager in some test targets. Let's install test-run deps
via `pip` everywhere.
NO_DOC=ci
NO_TEST=ci
> ci: install test-run deps via pip instead of apt

- src/lib/core/coio.c
- test/unit/coio.cc
coio_fill_addrinfo allocates ai_local->ai_addr, which should be freed in case of error.
This makes the test more real-life, and allows not to bother in the child process with the memory allocated prior to fork.
Closes #7370
> coio: fix memory leaks

- .travis.mk
This patch fixes the following error:
[ 35%] Performing configure step for 'bundled-libcurl-project'
*** Do not use buildconf. Instead, just use: autoreconf -fi
./buildconf: 8: exec: autoreconf: not found
To resolve this issue we need to install the `autoconf` and `automake`
packages before building.
NO_DOC=ci
NO_TEST=ci
> ci: add autoconf and automake deps to make targets

- changelogs/unreleased/bump-libcurl-to-7.84.0.md
Changelog: https://curl.se/changes.html#7_84_0
New release contains fixes for 4 security problems [1].
1. https://curl.se/docs/releases.html
NO_DOC=libcurl submodule bump
NO_CHANGELOG=libcurl submodule bump
NO_TEST=libcurl submodule bump
> [1.10] Bump curl 7.84.0 1.10

- src/box/memtx_allocator.cc
- src/box/memtx_allocator.h
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/tuple.h
- test/box/gh-3633-tuple-size-increasing.result
- test/box/reconfigure.result
- test/box/upsert_errinj.result
- test/wal_off/tuple.result
The main goal of this PR is to move allocator-specific stuff from `memtx_engine` to `MemtxAllocator`.
See commit descriptions for more details.
Needed for #7364.
> memtx: move allocator stuff from `memtx_engine` to `MemtxAllocator`

- .travis.mk
The issue was in the `deps_freebsd` target that installed test-run deps
(py38-yaml, py38-six, py38-gevent) via the `pkg` package manager.
At some moment these packages were upgraded to 39 version on the mirrors
and became not available for installation anymore.
Now test-run deps are installed via `pip` package installer to avoid
such issues in the future. Installation via `pip` is more robust because
we have deps versions pinned in test-run and also we have python version
pinned to 3.8.
Also, this change adds missing `libtool` package dependency.
Installing the `autoconf` and `automake` packages is not enough.
We need to install the `libtool` package as well to avoid errors
like this:
configure:7323: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
If this token and others are …
> ci: fix deps installation for FreeBSD systems

- changelogs/unreleased/gh-7226-admin-grant-error.md
- src/box/lua/schema.lua
- test/box-luatest/gh_7226_admin_grant_error_test.lua
We use LuaJIT 'bit' module for bitwise operations. Due to platform
interoperability it truncates arguments to 32bit and returns signed
result. Thus on granting rights using bit.bor to admin user which
have 0xffffffff rights (from bootstrap snapshot) we get -1 as a result.
This leads to type check error given in issue later in execution.
Closes #7226
NO_DOC=minor bugfix
> box: fix unexpected error on granting privileges to admin

- changelogs/unreleased/gh-7319-fix-http.client-reply-proto-parser.md
- src/lib/http_parser/http_parser.c
- src/lib/http_parser/http_parser.h
- src/lua/httpc.c
- test/fuzz/http_parser_fuzzer.c
- test/unit/CMakeLists.txt
- test/unit/http_parser.c
Handle status header response like 'HTTP/2 200' with version without
dot.
Closes #7319
NO_DOC=bugfix
> http_parser: fix parsing HTTP protocol version

- test/vinyl-luatest/gh_6565_hot_standby_unsupported_test.lua
The `gh_6565` test doesn't stop the hot standby replica it started, because the replica should fail to initialize and exit eventually
anyway. However, if the replica lingers until the next test due to https://github.com/tarantool/test-run/issues/345, the next test may successfully connect to it, which is likely to lead to a failure, because UNIX socket paths used by luatest servers are not randomized.
For example, here `gh_6568` test fails after `gh_6565`, because it uses the same alias for the test instance ('replica'):
```
[008] vinyl-luatest/gh_6565_hot_standby_unsupported_>                 [ pass ]
[008] vinyl-luatest/gh_6568_replica_initial_join_rem>                 [ fail ]
[008] Test failed! Output from reject file /tmp/t/rejects/vinyl-luatest/gh_6568_replica_initial_join_removal_of …
```
> test: fix cleanup in `vinyl-luatest/gh_6565_hot_standby_unsupported` test

- test/unit/CMakeLists.txt
This patch fixes the following error while tarantool build on
FreeBSD 13.1:
[100%] Linking CXX executable watcher.test
ld: error: undefined symbol: set_sigint_cb
>>> referenced by console.c:261 (lua/console.c:261)
>>>               console.c.o:(lbox_console_readline) in
archive ../../src/box/libbox.a
>>> referenced by console.c:342 (lua/console.c:342)
>>>               console.c.o:(lbox_console_readline) in
archive ../../src/box/libbox.a
>>> referenced by console.c:352 (lua/console.c:352)
>>>               console.c.o:(lbox_console_readline) in
archive ../../src/box/libbox.a
>>> referenced 1 more times
c++: error: linker command failed with exit code 1
(use -v to see invocation)
gmake[2]: *** [test/unit/CMakeFiles/watcher.test.dir/build.make:152:
test/unit/watcher.test] Error 1
gmake[1]: …
> build: fix error on FreeBSD 13.1

- changelogs/unreleased/gh-7166-box_latch_lock-order.md
- src/lib/core/latch.h
- test/unit/CMakeLists.txt
- test/unit/latch.c
- test/unit/latch.result
Currently the latch doesn't guarantee the order in which it is acquired
by fibers, which requested it. E.g. it is possible to wake up spuriously
a fiber which is yielding in the latch_lock, it will be removed from
l->queue by fiber_make_ready, then it will be inserted to l->queue
again, but for this time, to the head of the list instead of its
original place in the queue.
Fix this by using latch_waiter structure, which is linked into l->queue.
Part of #7166
> core: fix potential misorder of latch waiters

- src/box/tuple_update.c
Newer compilers have -Wunused-but-set-variable check enabled by default:
our codebase requires necessary fixes to satisfy it.
Follow up adf8779e, 760319ea, 678e47ee.
Closes #7386
NO_DOC=build
NO_TEST=build
> build: satisfy -Wunused-but-set-variable check

- changelogs/unreleased/add-https-certificate-validation-back.md
- cmake/BuildLibCURL.cmake
Without CA certificates the HTTP client will unable to verify server's
certificate, so the only way to perform an HTTPS request would be use
the `verify_peer = false` option -- disable certificate validation at
all.
The runtime search of system CA bundle/certificates was unintentionally
disabled in 2.10.0 (PR #7119). The patch enabled is back.
The main motivation behind the runtime search is difference in paths on
different systems. Since we ship Tarantool Enterprise Edition as
executable with ability to run on different Linux distributions, we
can't choose one particular path at build time. See details in #5746.
The `CURL_CA_BUNDLE_SET` and `CURL_CA_PATH_SET` options were removed,
because they are not 'real' curl configuration options, but rather
cached values to don't repeat …
> http client: return back CA certificates search

- src/box/key_list.c
- src/box/key_list.h
- src/box/memtx_allocator.h
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_tree.cc
- src/box/tuple_compare.cc
- test/wal_off/alter.result
Functional index keys are allocated and freed with `MemtxAllocator`'s `alloc` and `free` methods. In contrast to tuples, which are allocated and freed with `alloc_tuple` and `free_tuple`, freeing a functional index key happens immediately, irrespective of whether there's a snapshot in progress or not. It's acceptable, because snapshot only uses primary indexes, which can't be functional. However, to reuse the snapshot infrastructure for creating general purpose user read views, we will need to guarantee that functional index keys stay alive until all read views using them are closed.
To achieve that, this commit turns functional index keys into tuples, which automatically makes them linger if there's an open read view. We use the same global tuple format for allocating functional keys, …
> memtx: allocate functional index key parts as tuples

- changelogs/unreleased/gh-7232-upgrade-script-work-dir.md
- src/box/lua/load_cfg.lua
- test/xlog/gh-5894-pre-1.7.7-upgrade.result
- test/xlog/gh-5894-pre-1.7.7-upgrade.test.lua
- test/xlog/upgrade.lua
The upgrade script first tries to determine if the node is booted from
old snaps not recoverable on current Tarantool versions. If this is the
case, it sets up special triggers so that snaps are automatically
converted to a suitable format.
This happens before box.cfg{}, so the workdir is not set at this point
in time, and the upgrade script should take configured work_dir into
account explicitly. Fix this.
Closes #7232
NO_DOC=bugfix
> box: fix finding snapshot in upgrade script

- changelogs/unreleased/gh-6934-nonprintable-error-message.md
- src/box/lua/console.c
- src/box/lua/console.lua
- src/box/lua/serialize_lua.c
- test/box-luatest/gh_6934_nonprintable_error_message_test.lua
- third_party/lua-yaml/lyaml.cc
This patch adds a missed check for `lua_yaml_encode` return value,
similar to the check in `console_dump_plain`.
Now Lua error is raised if YAML encoding failed for any reason.
Before:
```
tarantool> box.error.new(box.error.ILLEGAL_PARAMS, '\x80')
~/test$ echo $?
0
~/test$
```
After:
```
tarantool> box.error.new(box.error.ILLEGAL_PARAMS, '\x80')
---
- error: 'console: an exception occurred when formatting the output: expected SCALAR,
SEQUENCE-START, MAPPING-START, or ALIAS'
...
tarantool>
```
Currently the call to `internal.format_yaml` in `output_handlers["yaml"]`
is covered by `pcall` only for `status == true`, however the opposite
case also can raise an exception. This patch adds the missed exception
handling. Two distinct calls are required, because it is not possible to
assing …
> Fix Tarantool terminations on non-printable error messages

- changelogs/unreleased/gh-7288-txn-and-eval-error.md
- changelogs/unreleased/gh-7413-use-streams-in-binary-console.md
- src/box/lua/console.lua
- test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua
- test/box/transaction.result
- test/box/transaction.test.lua
- test/luatest_helpers/server.lua
- test/replication-luatest/gh_4669_applier_reconnect_test.lua
The issue is if in binary remote console a error is thrown in expression like "box.begin() error('something') box.commit()" then it is overwritten by iproto check for active transactions at the end of eval. The solution is to rollback active transaction in this case in console code before iproto check.
Closes #7288
Closes #7413
> console flavours vs txn

- changelogs/unreleased/bump-openssl-to-111q.md
- static-build/CMakeLists.txt
- static-build/openssl-111q-gh-18720.patch
Just regular update to bring openssl security fixes into tarantool.
Added a patch for Mac OS to fix a build failure, see
https://github.com/openssl/openssl/issues/18720.
Changelog: https://www.openssl.org/news/cl111.txt
Vulnerabilities: https://www.openssl.org/news/vulnerabilities.html
> static-build: bump openssl from 1.1.1n to 1.1.1q

- changelogs/unreleased/gh-7109-fix-ctrl-c-in-multiline-input-mode.md
- src/box/lua/console.c
- src/box/lua/console.lua
- test/app-tap/gh-2717-no-quit-sigint.test.lua
This patch fixes the ctrl+c behavior in multiline mode.
The old behavior was ignoring sigint in this mode.
The new behavior is quitting this mode and printing the new
default prompt.
Added a new test for covering the mentioned case.
Follows up #2717
Closes #7109
> lua: fix sigint behavior in multiline input mode

- test/unit/coio.cc
According to man 3 exec: "The first argument, by convention, should point to the filename associated with the file being executed.". Using empty string as the first argument while calling `true` program, provided by coreutils led to error message being printed to stderr, which failed the test.
This patch passes 'true' as the first argument.
Closes #7452.
> test: fix execpl call in unit/coio test

- changelogs/unreleased/gh-7200-use-0-as-space-id-for-self-fkey.md
- src/box/lua/schema.lua
- src/box/lua/space.cc
- src/box/tuple_constraint_def.c
- src/box/tuple_constraint_fkey.c
- test/engine-luatest/gh_6436_field_foreign_key_test.lua
- test/engine-luatest/gh_7200_fkey_without_space_id_test.lua
It is inconvenient to create self-referencing FK constraints, as the
space ID will only be generated during space creation. This is
especially useful for SQL, since the format for the space is created
at compile time, and the space ID is only obtained at run time.
Closes #7200
> box: use 0 as a space id for FK that refer to the same space

- changelogs/unreleased/get-tuple-field-by-json-path-from-c.md
- extra/exports
- src/box/lua/tuple.c
- src/box/request.c
- src/box/tuple.c
- src/box/tuple.h
- src/box/tuple_extract_key.cc
- src/box/tuple_format.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
Added a function, which reflects the `tuple[json_path]` Lua API (see #1285).
```c
/**
* Return a raw tuple field in the MsgPack format pointed by
* a JSON path.
*
* The JSON path includes the outmost field. For example, "c" in
* ["a", ["b", "c"], "d"] can be accessed using "[2][2]" path (if 
* index_base is 1, as in Lua). If index_base is set to 0, the 
* same field will be pointed by the "[1][1]" path.
*
* The first JSON path token may be a field name if the tuple
* has associated format with named fields. A field of a nested
* map can be accessed in the same way: "foo.bar" or ".foo.bar".
*
* The return value is valid until the tuple is destroyed, see 
* box_tuple_ref().
*
* Return NULL if the field does not exist or if the JSON path is
* malformed or invalid. Multikey JSON path token …
```
> tuple: add JSON path field accessor to module API

- .github/workflows/integration.yml
This patch fixes the integration.yml workflow by calling the
reusable_build.yml workflow from the 1.10 branch. This commit
should be reverted before cherry-picking commits related to
the `.pack.mk` file changes [1] as the cherry-pick will fix
the problem.
Of course, we can cherry-pick [1] and resolve conflicts.
But it is better to keep historical timeline: first merge openssl
fixes [2], then enable testing on Debian [3], then cherry-pick
`.pack.mk` file changes [1]. Merging commits in this order will
not produce merge conflicts.
[1] https://github.com/tarantool/tarantool/pull/7406
[2] https://github.com/tarantool/tarantool/pull/7475
[3] https://github.com/tarantool/tarantool/pull/7462
> ci: call reusable_build.yml from 1.10 branch

- src/lib/core/CMakeLists.txt
- src/lib/core/backtrace.c
- src/lib/core/backtrace.h
- src/lib/core/clock_lowres.c
- src/lib/core/crash.c
- src/lib/core/tt_sigaction.c
- src/lib/core/tt_sigaction.h
- test/unit/CMakeLists.txt
- test/unit/tt_sigaction.c
- test/unit/tt_sigaction.result
Currently, tarantool is not designed to allow user to spawn his
own threads with unblocked signals in new modules, applications 
using tarantool and so on. This patch adapts tarantool to this possibility.
This is supposed to solve the problem, described in #7408.
Closes #7408
> Multithread friendly signals

- changelogs/unreleased/gh-7309-check-fkey-on-truncate.md
- src/box/alter.cc
- test/engine-luatest/gh_7309_check_fkey_on_truncate_test.lua
Add a missed check to on_replace_dd_truncate, similar to
on_replace_dd_space and on_replace_dd_index.
Closes #7309
> box: check for foreign keys on space:truncate()

- .github/workflows/reusable_build.yml
- .gitignore
- debian/control
- debian/rules
- rpm/tarantool.spec
- test/CMakeLists.txt
- test/small
Just a regular backport to bring new infra/test fixes into tarantool 1.10.
> [1.10] ci: enable tests while building deb packages

- .github/workflows/luajit-integration.yml
If Tarantool tests fail in LuaJIT integration workflow used in
tarantool/luajit repository and LuaJIT submodule is already bumped in
tarantool/tarantool repository, one can't rerun the failed job since
"LuaJIT bump" step brings down the whole pipeline with "nothing to
commit" reason.
There are still many flaky tests, so to make these integration workflow
rerunnable from tarantool/luajit repository --allow-empty option is
added to git commit command.
NO_DOC=ci
NO_TEST=ci
> ci: make LuaJIT integration workflow rerunnable

- changelogs/unreleased/gh-7196-fix-box-stat-net-thread.md
- src/box/lua/stat.c
- test/box/gh-6293-implement-new-net-stat.result
- test/box/gh-6293-implement-new-net-stat.test.lua
The valid range for `thread_id` is `[0, iproto_threads_count - 1]`.
Closes #7196
> box: fix `thread_id` check in `box.stat.net.thread[]`

- src/box/memtx_engine.cc
- src/box/memtx_hash.cc
- src/box/memtx_space.c
- src/box/memtx_tree.cc
- src/box/memtx_tuple_compression.h
Compressed tuples aren't supposed to be seen outside memtx internals: we always decompresses tuples before returning them to the user; tuples are written decompressed to xlog. We should also decompress tuples before writing them to a snapshot or sending them to a remote replica, but currently we don't, which results in a crash trying to recover from a snapshot that contains compressed spaces.
This patch fixes this by decompressing all tuples in snapshot iterator. Since the decompressed tuples are allocated on the region, we should also call `fiber_gc()` after each snapshot iterator iteration. Note that the decompression is unconditional, i.e. we try to decompress all tuples stored in an index. In general we can't figure out if a tuple is compressed, because its format may be unavailable …
> memtx: decompress tuples in snapshot iterator

- .github/workflows/submodule_update.yml
Bump tarantool submodule in tarantool-ee via pull requests:
* tarantool@master -> tarantool-ee@TarantoolBot/update-tarantool-master
* tarantool@2.10 -> tarantool-ee@TarantoolBot/update-tarantool-2.10
If there is an open PR already, it will be updated every time when
a new commit is pushed to tarantool@master or tarantool@2.10.
This workflow uses action https://github.com/tarantool/actions created especially for this workflow. 
Closes https://github.com/tarantool/tarantool-ee/issues/175
> Add new workflow for updating parent repository

- changelogs/unreleased/bump-ncurses-to-6.3-20220716.md
- static-build/CMakeLists.txt
Just regular update to bring ncurses security fixes into tarantool.
New version brings a number of functional and security fixes:
- ncurses 6.3 before patch 20220416 has an out-of-bounds read and
segmentation violation in convert_strings in tinfo/read_entry.c in the
terminfo library (CVE-2022-29458).
- ncurses through v6.2-1. _nc_captoinfo in captoinfo.c has a heap-based
buffer overflow (CVE-2021-39537).
CVE-2022-29458 Detail: https://nvd.nist.gov/vuln/detail/CVE-2022-29458
CVE-2021-39537 Detail: https://nvd.nist.gov/vuln/detail/CVE-2021-39537
Release announcement: https://lists.gnu.org/archive/html/bug-ncurses/2022-07/msg00008.html
NO_TEST=security update of a dependency
NO_DOC=security update of a dependency
> static-build: bump ncurses from 6.2 to 6.3-20220716

- changelogs/unreleased/bump-readline-to-80p1.md
- static-build/CMakeLists.txt
- static-build/readline80-001.patch
Just regular update to bring readline security fixes into tarantool.
Added a patch to fix file descriptor leak with zero-length history file.
Source of patch: https://ftp.gnu.org/gnu/readline/readline-8.0-patches/
Announcement: https://lists.gnu.org/archive/html/bug-readline/2019-08/msg00004.html
NO_TEST=security update of a dependency
NO_DOC=security update of a dependency
> static-build: bump readline from 8.0 to 8.0p1

- changelogs/unreleased/bump-libyaml-with-cve-fix.md
PR in tarantool/libyaml: https://github.com/tarantool/libyaml/pull/1
Updated version contains fixes of security issues:
- Security issue: https://github.com/yaml/libyaml/issues/107
- PR in upstream with original patch: https://github.com/yaml/libyaml/pull/127
> build: bump libyaml

- .github/workflows/osx_12_static_cmake.yml
- changelogs/unreleased/static-build-fix-on-mac-os-11-and-newer.md
- static-build/CMakeLists.txt
Without `-isysroot <SDK_PATH>` the build fails:
```
/Library/Developer/CommandLineTools/usr/bin/make[4]: Making `all' in   \
`makeconv'
/Library/Developer/CommandLineTools/usr/bin/c++ -O2 -W -Wall -pedantic \
-Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++11          \
-Wno-ambiguous-reversed-operator     -o ../../bin/makeconv         \
gencnvex.o genmbcs.o makeconv.o ucnvstat.o -L../../lib -licutu     \
-L../../lib -licui18n -L../../lib -licuuc -L../../stubdata         \
-licudata -lpthread -lm
ld: library not found for -lpthread
clang: error: linker command failed with exit code 1 (use -v to see    \
invocation)
```
ICU is written on C++, so we should pass `CXXFLAGS`, not only `CFLAGS`.
Note: `CPPFLAGS` stands for C preprocessor flags, not C++ flags.
Fixes #7459
> static build: fix icu build on Mac OS 11 and newer

- CMakeLists.txt
- changelogs/unreleased/bump-zstd.md
- cmake/BuildZSTD.cmake
- src/box/txn.h
Updated third_party/zstd submodule from v1.5.0 to 1.5.2 version. The new version fixes a few bugs found by fuzzing testing.
Note, the new zstd version contains a .S source file so we need to include ASM to the CMake project languages.
> build: bump zstd submodule

- static-build/test/CheckDependencies.cmake
Commit ed16c1e5780cf355ab9bf923ee6f9daf5b6363f8 ("build: fix bundled
libcurl and c-ares build on OS X") fixed building libcurl with ares by
adding a dependency on libresolv for Mac OS X. It was forgotten to add
libresolv to check-dependencies exceptions for static build. Do this now.
NO_DOC=CI stuff
NO_TEST=CI stuff
NO_CHANGELOG=CI stuff
> build: fix check-dependencies test on OS X

- .github/workflows/submodule_update.yml
This patch fixes the following issue: the submodule_update.yml workflow
always updated the tarantool submodule in the tarantool-ee repo to the
last commit from the `master` branch, even if it was tarantool-ee 2.10.
Now it is fixed.
NO_DOC=ci
NO_TEST=ci
> ci: fix submodule bump for tarantool-ee 2.10

- cmake/module.cmake
The GENERATED and HEADER_FILE_ONLY source file properties should be
followed by a boolean value. CMake 3.20+ warns if it is not so, see [1].
It seems, the module.h properties do not actually change anything
visible in our case.
[1]: https://cmake.org/cmake/help/latest/policy/CMP0118.html
> cmake: eliminate warning about source properties

- src/CMakeLists.txt
- src/box/box.cc
This list contains several header files, which has no
`/** cond public */` and `/** \endcond public */` instructions.
While I'm on it, drop `/** \endcond public */` from box.cc.
> cmake: clean up list of API headers

- src/lib/core/prbuf.c
- test/unit/prbuf.c
- test/unit/prbuf.result
prbuf_check, which is called by prbuf_open, proceeds to scanning the buffer even if it's empty. On debug build, this results in prbuf_open reporting that the buffer is corrupted, because we trash the buffer in prbuf_create. On a release build, this may lead to a hang, in case the buffer is zeroed out. Let's fix this by returning success from prbuf_check if the buffer is empty. Note, prbuf_iterator_next doesn't call prbuf_first_record if the buffer is empty, either.
Needed for https://github.com/tarantool/tarantool-ee/issues/187
> prbuf: fix prbuf_open for empty buffer

- changelogs/unreleased/gh-7477-memtx-hash-idx-gt-iter-dirty-reads.md
- src/box/memtx_hash.cc
- test/box-luatest/gh_7477_memtx_hash_idx_gt_iter_dirty_reads_test.lua
The `next` method of memtx HASH index 'GT' iterator is initially set to
'GT' and is supposed to be set to 'GE' after first iteration: it is
mistakenly set to the 'base' method instead of the full method which also
does tuple clarification — this allows dirty reads. Move the `next` method
change on first iteration to `WRAP_ITERATOR_METHOD` for clarity and
correctness.
Closes #7477
> memtx: fix HASH index 'GT' iterator `next` method set incorrectly

- changelogs/unreleased/gh-4709-rev-iters-phantom-reads.md
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- test/box-luatest/gh_7409_rev_iters_phantom_reads_test.lua
In case of reverse iterators, due to index limitations, we need to clarify
the successor tuple early: this implies that the successor's story is not
always at the top of the history chain, whilst we need to add the gap item
to the story currently present in index — fix this by explicitly retrieving
the top story in the successor's history chain.
CLoses #7409
NO_DOC=bugfix
> memtx: fix reverse iterators gap tracking

- changelogs/unreleased/gh-7512-raft-leader-hang.md
- src/box/relay.cc
- test/replication-luatest/gh_7512_raft_leader_hang_test.lua
It's possible to hang an instance by some non-yielding request. The
simplest example is `while true do end`. A more true to life one would
be a `select{}` from a large space, or `pairs` iteration over a space
without yields.
Any such request makes the instance unresponsive - it can serve neither
reads nor writes. At the same time, the instance appears alive to other
cluster members: relay thread used to communicate with others is not
hung and continues to send heartbeats every replication_timeout.
The problem is the most severe with Raft leader elections: followers
believe the leader is fine and do not start elections despite leader
being unable to serve reads or writes.
Closes #7512
NO_DOC=bugfix
> raft: make followers notice leader hang

- changelogs/unreleased/decimal-lua-module-api.md
- extra/exports
- src/CMakeLists.txt
- src/box/lua/info.c
- src/box/lua/net_box.c
- src/box/sql/mem.c
- src/lua/decimal.c
- src/lua/decimal.h
- src/lua/msgpack.c
- src/lua/utils.c
- src/lua/utils.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
Added the following functions to the module API:
```c
/**
* Allocate a new decimal on the Lua stack and return
* a pointer to it.
*/
API_EXPORT box_decimal_t *
luaT_newdecimal(struct lua_State *L);
/**
* Allocate a new decimal on the Lua stack with copy of given
* decimal and return a pointer to it.
*/
API_EXPORT box_decimal_t *
luaT_pushdecimal(struct lua_State *L, const box_decimal_t *dec);
/**
* Check whether a value on the Lua stack is a decimal.
*
* Returns a pointer to the decimal on a successful check,
* NULL otherwise.
*/
API_EXPORT box_decimal_t *
luaT_isdecimal(struct lua_State *L, int index);
```
This pull request also contains several preparatory changes. One is worth to highlight: we had a set of `luaT_pushfoo()` function, which allocates `cdata<struct foo>` on the Lua stack. …
> lua/decimal: add Lua value accessors to module API

- .test.mk
LuaJIT tests are disabled in the scope of the issue [1].
[1] https://github.com/tarantool/tarantool/issues/4819
NO_DOC=ci
NO_TEST=ci
> ci: disable LuaJIT tests for OSX arm64 builds

- changelogs/unreleased/gh-7432-fix-iter-next-clarify-after-track-gap.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_7432_fix_iter_next_clarify_after_gap_track_test.lua
The problem is described in #7073. It was fixed only for
`tree_iterator_start_raw` next method, but other methods used for reverse
iterators are also subject to this bug: move tuple clarification from the
wrapper of iterator `next` methods to individual iterator methods.
Closes #7432
> memtx: fix tree iterator `next` result clarification

- changelogs/unreleased/gh-7375-fix-gap-tracking-corner-cases.md
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- test/box-luatest/gh_7375_fix_gap_tracking_corner_cases_test.lua
Gap tracking does not handle gap writes when the key has the same value as
the gap item: review the whole gap write handling process, refactor it and
fix handling of corner cases along the way.
Closes #7375
> memtx: fix handling of corner cases gap tracking in transaction manager

- changelogs/unreleased/gh-7539-mvcc-dirty-data-written-to-snapshot.md
- src/box/memtx_hash.cc
- test/box-luatest/gh_7539_mvcc_dirty_data_written_to_snapshot_test.lua
The hash index doesn't create a snapshot clarifier, which is used for filtering out uncommitted tuples from a snapshot. Fix this. Also fix a bug in hash_snapshot_iterator_next, where we passed a wrong argument to tuple_data_range. It hasn't fired, because the clarifier didn't work.
Fixes commit ee8ed0653993 ("txm: clarify all fetched tuples").
Fixes commit f167c1afb38e ("memtx: decompress tuples in snapshot iterator").
Closes #7539
> memtx: fix dirty data written to snapshot for hash index

- CMakeLists.txt
- src/box/lua/serialize_lua.c
- src/box/sql.c
- src/box/sql/build.c
- src/box/sql/select.c
- src/box/sql/tokenize.c
- src/box/xlog.c
- src/box/xrow.c
- src/lib/core/popen.c
- src/lib/core/sio.c
- src/lib/core/util.c
- src/lib/tzcode/localtime.c
- src/lib/tzcode/strptime.c
- src/lib/tzcode/timezone.c
- src/proc_title.c
- src/systemd.c
- src/trivia/config.h.cmake
- src/trivia/util.h
- test/unit/CMakeLists.txt
- test/unit/string.c
- test/unit/string.result
**util: introduce strlcat utility function**
strlcat is a function from BSD, which is designed to be safer, more
consistent, and less error prone replacement for strcat and strncat.
**Use size-bounded versions of sprintf, strcpy and strcat**
To avoid potential buffer overflows and to make static analyzers happy.
Fixed CWE-120:
- sprintf: does not check for buffer overflows
- strcpy: does not check for buffer overflows when copying to destination
- strcat: does not check for buffer overflows when concatenating to
destination
Closes https://github.com/tarantool/tarantool/issues/7534
> Use size-bounded versions of sprintf, strcpy and strcat

- changelogs/1.10.14.md
doc: proofread changelog 1.10.14
Resolves https://github.com/tarantool/doc/issues/3045
Fix wording, punctuation, and formatting.
> doc: proofread 1.10.14 changelog

- changelogs/unreleased/gh-5064-ignore-i-flag-without-tty.md
- src/lua/init.c
- test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua
- test/box/gh-4703-on_shutdown-bug.result
- test/box/gh-4703-on_shutdown-bug.test.lua
The interactive mode has been overruled by isatty check and is no more.
Now results of another command can be handled by tarantool.
For example:
```
$ echo 42 | tarantool -i
Tarantool 2.5.0-130-ge3cf64a6c
type 'help' for interactive help
tarantool> 42
---
- 42
...
tarantool> $
```
NO_DOC=bugfix
Closes #5064
> console: fix `-i` being overruled by `!isatty()`

- changelogs/2.10.1.md
> doc: fix 2.10.1 changelog text

- changelogs/unreleased/strict_fencing.md
- src/box/box.cc
- src/box/box.h
- src/box/lua/cfg.cc
- src/box/lua/load_cfg.lua
- src/box/raft.c
- src/box/raft.h
- src/box/replication.cc
- src/box/replication.h
- test/app-tap/init_script.result
- test/box/admin.result
- test/box/cfg.result
- test/luatest_helpers/proxy/connection.lua
- test/luatest_helpers/proxy/proxy.lua
- test/luatest_helpers/server.lua
- test/replication-luatest/election_fencing_test.lua
- test/replication/election_replica.lua
- test/replication/gh-3055-election-promote.result
- test/replication/gh-3055-election-promote.test.lua
- test/replication/gh-5445-leader-inconsistency.result
- test/replication/gh-5445-leader-inconsistency.test.lua
Current leader fencing implementation didn't really guarantee that old
leader would resing it's leadership before new leader could be elected.
That made it possible for several "leaders" coexist in cluster for some
time.
I changed replication_disconnect_timeout so that it is twice
as short for current raft leader (2*replication_timeout) if strict
fencing is enabled. Assuming that replication_timeout is the same for every
replica in replicaset this guarantees that leader will resign it's
leadership before anyone could start elections.
Old fencing behaviour can be enabled by setting fencing to soft mode.
This is useful when connection death timeouts shouldn't be affected
(e.g. different replication_timeouts are set to prioritize some replicas
as leader over the others).
Closes #7110
> Strict fencing

- .github/actions/environment/action.yml
This patch adds a temporary workaround for LuaJIT profiling tests to
avoid runners shutdown due to no space left on the disk. The profiling
tests may produce profiles until fully fill up the runner [1].
The workaround is based on implementing disk quotas.
In two words, it creates a 1GB file (disk image), formats this file as
an ext4 filesystem, mounts this filesystem to some mount pont and sets
`LUAJIT_TEST_VARDIR=<mount point>`. In this case LuaJIT tests will use
this dir for storing various test data/profiles and not be able to fill
up the runner.
[1] https://github.com/tarantool/tarantool/issues/7472
NO_DOC=ci
NO_TEST=ci
> ci: add workaround for LuaJit profiling tests

- src/box/CMakeLists.txt
- src/box/key_def.h
- src/box/tuple_compare.cc
- src/box/tuple_compare.h
- src/trivia/config.h.cmake
Format-less tuple comparison is required to do lookups in a memtx index read view, see https://github.com/tarantool/tarantool-ee/issues/191. The feature itself will be done in EE. This PR just does some preparations necessary for the EE part.
EE part: https://github.com/tarantool/tarantool-ee/pull/195
> Preparations for format-less tuple comparison

- static-build/CMakeLists.txt
Currently `make` in `static-build` doesn't rebuild Tarantool when source
files are changed. Fix this by setting BUILD_ALWAYS option, which forces
rescan for changes of the external project [1]:
> This option is not normally needed unless developers are expected to
> modify something the external project's build depends on in a way that
> is not detectable via the step target dependencies (e.g. SOURCE_DIR is
> used without a download method and developers might modify the sources
> in SOURCE_DIR).
It is available since CMake 3.1, so update cmake_minimum_required, as we
already require it (fa8d70c).
[1] https://cmake.org/cmake/help/latest/module/ExternalProject.html
Part of #7536
> cmake: detect changes in source files upon static build

- changelogs/unreleased/gh-7489-concurrent-fiber-join.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
- test/app-luatest/gh_7489_concurrent_fiber_join_test.lua
- test/unit/fiber.cc
- test/unit/fiber.result
**fiber: introduce fiber_wait_on_deadline()**
It is separated from fiber_join_timeout(), and will be used
in lbox_fiber_join() too.
**fiber: do not crash on concurrent fiber:join()**
If two or more fibers are yielding in fiber_join_timeout(), one of them
will eventually join and recycle the fiber, while the rest will crash
on accessing the recycled fiber's struct. Fix this by doing fiber_find()
again after each waiting attempt in lbox_fiber_join().
**fiber: do not crash on concurrent C fiber_join()**
Like a previous commit, but fix C module API instead of Lua.
Closes https://github.com/tarantool/tarantool/issues/7489
Closes https://github.com/tarantool/tarantool/issues/7531
> Fix a crash on concurrent `fiber:join()`

- changelogs/unreleased/gh-7581-downstream-lag-calculation-fix.md
- src/box/relay.cc
- test/replication-luatest/gh_7581_downstream_lag_test.lua
downstream lag is the difference in time between the moment a
transaction was written to master's WAL and the moment an ack for it
arrived.
Its calculation is supported by replicas sending the last applied row
timestamp. When there is no replication, the last applied row timestamp
stays the same, so downstream lag grows as time passes.
Once an old master is replaced by a new one, it notices changes in peer
vclocks and tries to update downstream lag unconditionally. This makes
the lag appear to be growing indefinitely, showing the time since the
last transaction on the old master:
```
downstream:
status: follow
idle: 0.018218606001028
vclock: {1: 3, 2: 2}
lag: 34.623061401367
```
The commit 56571d83172f ("raft: make followers notice leader hang")
made relay exchange information with tx …
> replication: fix downstream lag growing when there's no new transactions

- src/box/CMakeLists.txt
- src/box/blackhole.c
- src/box/engine.c
- src/box/engine.h
- src/box/memtx_engine.cc
- src/box/read_view.c
- src/box/read_view.h
- src/box/service_engine.c
- src/box/sysview.c
- src/box/vinyl.c
Currently, we create a database read view only to create a memtx snapshot or join a replica, but there's already quite a bit of code duplication between these two scenarios. In the future, we will need the same functionality to create a user read view. So let's factor out this code into a separate module - `read_view`.
The API of the `read_view` module is quite simple - there are just two methods: open and close a read view. The user can pass a space and index filter while opening a read view to skip certain spaces. E.g. we skip all temporary spaces and secondary indexes when we create a memtx snapshot. A `read_view` object has a list of `space_read_view` objects, one per each space included into the read view. A `space_read_view` object, in turn, has a map of all `index_read_view` …
> Introduce internal database read view API

- test/app-luatest/http_client_test.lua
- test/app-luatest/httpd.py
- test/app-luatest/suite.ini
- test/app-tap/suite.ini
- test/box-tap/suite.ini
In commit 5710204804 ("test: migrate app-tap/http_client test to
luates") app-luatest/http_client.test.lua has been rewritten for luatest
and tickets were blindly migrated to a new test suite too.
Rarely test failed with exception "Address already in use":
```
[007] ok     9  http_client.sock_family:"AF_INET".test_special_methods
[007] Traceback (most recent call last):
[007]   File "/home/sergeyb/sources/MRG/tarantool/test/app-luatest/httpd.py", line 142, in <module>
[007]     sock.bind(sock_addr)
[007]   File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 563, in bind
[007]     return self._sock.bind(address)
[007] OSError: [Errno 98] Address already in use
```
Failure could be reproduced with following command line:
"./test/test-run.py $(yes …
> test: fix flakiness in app-luatest/http_client_test.lua

- .github/actions/report-job-status/README.md
This patch adds a warning about using the action in pull requests
created from forks. GitHub secrets are not passed to workflows in
this case [1] and due to this limitation the action will not work
correctly for such pull requests.
[1] https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
NO_DOC=ci                                         
NO_TEST=ci                                        
> ci: improve `report-job-status` README

- changelogs/unreleased/gh-7320-restore-multiline-history.md
- src/box/lua/console.c
When multiline commands were loaded from .tarantool_history, they were
treated as a bunch of oneline commands. Now readline is configured to
write timestamps in .tarantool_history as delimiters and multiline
commands are handled correctly.
If there is already a .tarantool_history file, readline will set
timestamps automatically, nothing will be lost.
Closes #7320
NO_DOC=bugfix
NO_TEST=impossible to check readline history from lua
> console: fix multiline commands saved as oneline

- src/box/read_view.c
- test/box-luatest/memtx_gc_after_snapshot_test.lua
This is a degradation introduced by commit 26f7056f9c12: tuple garbage collection is never resumed after a snapshot. This happens, because we don't add engine read views to the read view engine list on read view construction. As a result, `read_view_close()` never closes the memtx engine read view.
> memtx: fix tuple garbage collection not resumed after snapshot

- .github/actions/report-job-status/action.yml
Report workflow failures in PRs made by TarantoolBot to the same chat
as with stable branches. Such PRs are used for automated integration
testing, so it's important for the team to notice failures in them.
There is no personal chat for TarantoolBot and no need to make one.
NO_DOC=CI reporting
NO_TEST=CI reporting
NO_CHANGELOG=CI reporting
> ci: report PRs from TarantoolBot to main chat

- .github/actions/report-job-status/action.yml
Report workflow failures in PRs made by TarantoolBot to the same chat
as with stable branches. Such PRs are used for automated integration
testing, so it's important for the team to notice failures in them.
There is no personal chat for TarantoolBot and no need to make one.
NO_DOC=CI reporting
NO_TEST=CI reporting
NO_CHANGELOG=CI reporting
(cherry picked from commit 8ebfa6113898ccc69e9f6513e2a205d8f99536ff)
> [1.10] ci: report PRs from TarantoolBot to main chat

- changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md
- src/box/alter.cc
- src/box/lua/call.c
- src/box/lua/space.cc
- src/box/vinyl.c
- src/lib/core/coio_task.c
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lib/core/trigger.cc
- src/lib/core/trigger.h
- src/lua/trigger.c
- src/main.cc
- test/box-luatest/gh_4264_recursive_trigger_test.lua
- test/unit/CMakeLists.txt
- test/unit/trigger.c
- test/unit/unit.h
This patch fixes a number of issues with trigger_clear() while the
trigger list is being run:
1) clearing the next-to-be-run trigger doesn't prevent it from being run
2) clearing the next-to-be-run trigger causes an infinite loop or a
crash
3) swapping trigger list head before the last trigger is run causes an
infinite loop or a crash (see space_swap_triggers() in alter.cc, which
had worked all this time by miracle: space _space on_replace trigger
swaps its own head during local recovery, and that had only worked
because the trigger by luck was the last to run)
This is fixed by adding triggers in a separate run list on trigger_run.
This list may be iterated by `rlist_shift_entry`, which doesn't suffer
from any of the problems mentioned above.
While being bad in a number of ways, old …
> core: fix crashes after altering trigger list while it is run

- changelogs/unreleased/gh-7605-fix-qsort.md
- test/box-luatest/gh_7605_qsort_recovery_test.lua
- test/box-luatest/suite.ini
- test/unit/CMakeLists.txt
- test/unit/qsort_arg.cc
- test/unit/qsort_arg.result
- third_party/qsort_arg_mt.c
In commit (35334ca13b) qsort was fixed but unfortunatelly a small
typo was introduced. Due to that typo the qsort made its job wrong.
Add unit test.
Fortunatelly the wrong case happened rather seldom. Unfortunatelly
a test that shows that problem runs extremely long, so it should
go to long-tests.
Closes #7605
> Fix a bug in qsort

- perf/CMakeLists.txt
- perf/debug_warning.h
- perf/light.cc
- perf/tuple.cc
Subj. It also contains a few benches for std::unordered_map (nevertheless it's chain hash-table, it's the only option provided by std lib) just to make number more relative. For particular results and details see commit message.
> perf: add Light benchmarks

- .github/workflows/coverity.yml
- .github/workflows/fuzzing.yml
- .github/workflows/jepsen-cluster-txm.yml
- .github/workflows/jepsen-cluster.yml
- .github/workflows/jepsen-single-instance-txm.yml
- .github/workflows/jepsen-single-instance.yml
The `ubuntu-18.04` environment is deprecated, so let's switch to
`ubuntu-latest` where it is safe. For more details see [1].
[1] https://github.com/actions/virtual-environments/issues/6002
> ci: use `ubuntu-latest` instead of `ubuntu-18.04`

- changelogs/unreleased/gh-7473-system-fibers.md
- src/box/applier.cc
- src/box/gc.c
- src/box/lua/net_box.c
- src/box/memtx_engine.cc
- src/box/raft.c
- src/box/recovery.cc
- src/box/vinyl.c
- src/box/vy_log.c
- src/box/vy_scheduler.c
- src/box/watcher.c
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lib/swim/swim.c
- src/lua/fiber.c
- src/main.cc
- test/app-luatest/system_fiber_test.lua
Currently if we kill worker fiber of the connection, which was
initialized with `reconnect_after` option, we get `error_reconnect`
state. But reconnect obviously doesn't happen.
Let's try to solve that problem) 
Closes #7448
Closes  #7473
> net.box: fix connection's `error_reconnect` state

- .github/workflows/publish-module-api-doc.yaml
`make api` generates `src/module.h`. `make module_api` is the target for
compiling a library for testing of the module API:
`test/app-tap/module_api.so`. It depends on the `api` target.
Both works for generating `module.h`, but `make api` don't do extra
unneeded actions.
> ci: make module.h generation command more specific

- changelogs/unreleased/gh-7614-fix-nullable-from-format.md
- src/box/lua/schema.lua
- test/box-luatest/gh_7614_fix_nullable_from_format_test.lua
If index parts are specified using old syntax like:
parts = {1, 'number', 2, 'string'},
then (except if parts count is 1) index options set in space format
are not taken into account. Solution is to continue after parsing 1.6.0
style parts so to use code that check format options.
Closes #7614
>  box: fix inheriting format options for old-style parts

- src/box/index.cc
- src/box/index.h
- src/box/lua/misc.cc
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/read_view.c
- src/box/read_view.h
- src/box/sequence.c
- src/box/tuple.c
- src/box/tuple.h
To support accessing tuple fields by name from the read view Lua API (EE-only), we need to create a runtime tuple format for each space read view, using the space field names to initialize the field dictionary. This PR does the trick. To conveniently access the format from a read view iterator, it also adds back pointers to read view iterator and index read view objects. Since the feature isn't required for snapshot creation or joining a replica, we create tuple formats for space read views only if the corresponding flag was set at the time of read view creation, otherwise we just use the global name-less runtime format.
Needed for https://github.com/tarantool/tarantool-ee/issues/207
EE part: https://github.com/tarantool/tarantool-ee/pull/219
> Add tuple format to read view

- changelogs/2.10.2.md
- changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md
- changelogs/unreleased/gh-4450-logger-sigsegv.md
- changelogs/unreleased/gh-7320-restore-multiline-history.md
- changelogs/unreleased/gh-7473-system-fibers.md
- changelogs/unreleased/gh-7489-concurrent-fiber-join.md
- changelogs/unreleased/gh-7581-downstream-lag-calculation-fix.md
- changelogs/unreleased/gh-7605-fix-qsort.md
- changelogs/unreleased/gh-7614-fix-nullable-from-format.md
- changelogs/unreleased/ghs-5-fix-auth-check-on-truncate.md
Generate changelog for 2.10.2 release.
Also, clean changelogs/unreleased folder.
> Generate changelog for 2.10.2

- src/box/memtx_allocator.cc
- src/box/memtx_allocator.h
- test/unit/memtx_allocator.cc
- test/unit/memtx_allocator.result
This PR address a few issues that the current implementation of `MemtxAllocator::ReadView` has, namely:
- #7185
- #7412
- #7189
This is needed to make the memtx tuple read view infrastructure suitable for creating user read views.
> memtx: tuple read view improvements

- src/box/alter.cc
- src/box/func.c
- src/box/func.h
- src/box/func_def.c
- src/box/func_def.h
- src/box/lua/call.c
- src/box/lua/call.h
- src/box/sql/func.c
- src/box/sql/func.h
- test/unit/func_cache.c
To handle space upgrade in read view, we'll need to make a copy of the space upgrade function. This PR is to refactors `func` and `func_def` construction to make it easy to do.
Needed for https://github.com/tarantool/tarantool-ee/issues/163
> `func` and `func_def` construction refactoring

- changelogs/unreleased/gh-6801-high-cpu-usage-by-on_shutdown-triggers.md
- changelogs/unreleased/gh-7434-yield-in-on_shutdown-trigger.md
- src/lua/init.lua
- src/main.cc
- test/box-luatest/gh_7434_child.lua
- test/box-luatest/gh_7434_yield_in_on_shutdown_trigger_test.lua
**main: run an event loop for on_shutdown triggers**
When Tarantool is stopped by Ctrl+D or by reaching the end of the
script, run_script_f() breaks the event loop, then tarantool_exit()
is called from main(), however the fibers that execute on_shutdown
triggers can not be longer scheduled, because the event loop is
already stopped. Fix this by starting an auxiliary event loop for
such cases.
Closes https://github.com/tarantool/tarantool/issues/7434
**box: fix high CPU usage while on_shutdown triggers are running**
Currently this script causes 100% CPU usage for 10 sec, because
os.exit() infinitely yields to the scheduler until on_shutdown
fiber completes and breaks the event loop. Fix this by a sleep.
```
box.ctl.set_on_shutdown_timeout(100)
box.ctl.on_shutdown(function() …
```
> Fix on_shutdown triggers

- changelogs/unreleased/gh-6126-retry-join-automatically.md
- src/box/applier.cc
- src/box/applier.h
- src/box/box.cc
- src/box/replication.cc
- test/replication-luatest/gh_6126_auto_rejoin_test.lua
- test/replication/anon.result
- test/replication/anon.test.lua
If the error is non-critical, the instance retries join
automatically.
Title: Retry join automatically (for a timeout)
If the error is non-critical, the instance retries join automatically.
For example, if automatic election is used, then a new instance can
find the leader, but while it is sending a join request, the leader
can resign. The join will fail saying the former leader is read-only.
The waiting make sense in this case.
Closes #6126
> replication: retry join automatically

- changelogs/unreleased/igrishnov/gh-7479-bug-fix-uri-lib.md
- src/box/lua/net_box.lua
- src/lib/uri/uri.c
- test/app-luatest/gh_7479_bug_fix_uri_lib_test.lua
- test/app-tap/uri.test.lua
Made host=localhost by default for tarantoolctl connect. Now, when specifying only the port, the connection is made to localhost.
Fixes #7479
> tarantoolctl: fix default host for connect

- test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua
- test/app-tap/gh-2717-no-quit-sigint.test.lua
The tests fail on dev installation if it's readline configuration
(.inputrc) changes prompt. Use default readline configuration for
the tests.
Closes #7620
NO_DOC=test changes
NO_TEST=test changes
NO_CHANGELOG=test changes
> test: fix readline dependent tests

- .github/workflows/redos_7_3.yaml
- changelogs/unreleased/add-redos-7.3-ci-cd.md
Add the redos_7.3.yml workflow to build Tarantool packages (x86_64) for
the RedOS 7.3 system.
Packages are created by https://github.com/packpack/packpack.
Closes tarantool/tarantool-qa#260
> Add build RedOS linux package

- changelogs/unreleased/gh-7166-deprecate-fiber_set_cancellable.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
- src/main.cc
- test/app-luatest/gh_7166_wakeup_on_shutdown_fiber_test.lua
- test/luatest_helpers/fiber.lua
- test/unit/fiber.cc
- test/unit/latch.c
Currently this function is not used inside Tarantool, however it is
available via C module API. Deprecate it, because it is very confusing
and has nothing to do with the fiber cancellation.
[Approved by PM here](https://github.com/tarantool/tarantool/issues/7166#issuecomment-1212069052).
Closes #7166
> fiber: make fiber_set_cancellable a no-op

- src/box/index.h
- src/box/memtx_engine.cc
- src/box/read_view.c
- src/box/read_view.h
- src/box/space_upgrade.h
If a read view is created while a space upgrade is in progress (both are EE features), then we need to apply the upgrade function to all tuples fetched from the read view. This PR adds function stubs to the CE repository that will allow us to fix the issue in the EE repository.
EE part: https://github.com/tarantool/tarantool-ee/pull/229
Needed for https://github.com/tarantool/tarantool-ee/issues/163
> Space upgrade in read view handling - CE part

- changelogs/unreleased/gh-7253-fiber-hang-on-fencing.md
- changelogs/unreleased/gh-7253-split-brain-early-vote.md
- changelogs/unreleased/promote-hang.md
- changelogs/unreleased/promote-multiple-infinite.md
- src/box/box.cc
- src/box/errcode.h
- src/box/raft.c
- src/box/raft.h
- src/box/txn_limbo.c
- src/lib/raft/raft.c
- src/lib/raft/raft.h
- test/box/error.result
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_7253_election_long_wal_write_test.lua
- test/replication-luatest/suite.ini
- test/replication/election_basic.result
- test/replication/election_basic.test.lua
- test/unit/raft.c
- test/unit/raft.result
The patchset fixes several unrelated bugs. 2 of them are from the ticket #7253. The ticket contains 3 issues whose solution was designed in an RFC, but one of the bugs couldn't be fixed like proposed. Explanation why and possible solutions will come soon in that RFC and maybe in the ticket.
At the moment of submission I get "error 500" when open any CI job and "debug" just hangs in yellow state. Sending it for review now hoping the debug CI passes later.
Part-of #7253
> Fix several bugs: in raft, in qsync, in box.ctl.promote()

- changelogs/unreleased/popen-mac-os-race.md
- src/lib/core/popen.c
- src/lua/popen.c
- test/app-tap/popen.skipcond
In brief: `vfork()` on Mac OS 12 and newer doesn't suspend the parent
process, so we should wait for `setpgrp()` to use `killpg()`. See more
detailed description of the problem in a comment of the
`popen_wait_group_leadership()` function.
The solution is to spin in a loop and check child's process group. It
looks as the most simple and direct solution. Other possible solutions
requires to estimate cons and pros of using extra file descriptor or
assigning a signal number for the child -> parent communication.
There are the following alternatives and variations:
* Create a pipe and notify the parent from the child about the
`setpgrp()` call.
It costs extra file descriptor, so I decided to don't do that.
However if we'll need some channel to deliver information from the
child to the parent …
> popen: fix a race between setpgrp() and killpg()

- CMakeLists.txt
- changelogs/unreleased/strerror-mt-safe.md
- extra/exports
- src/box/lua/info.c
- src/lib/core/CMakeLists.txt
- src/lib/core/backtrace.c
- src/lib/core/crash.c
- src/lib/core/evio.c
- src/lib/core/exception.cc
- src/lib/core/say.c
- src/lib/core/say.h
- src/lib/core/tt_strerror.c
- src/lib/core/tt_strerror.h
- src/lua/errno.lua
- src/main.cc
- src/module_header.h
- src/trivia/config.h.cmake
- test/unit/say.c
`strerror()` is MT-Unsafe, because it uses a static buffer under the hood. We should use `strerror_r()` instead, which takes a user-provided buffer. The problem is there are two implementations of `strerror_r()`: XSI and GNU. The first one returns an error code and always writes the message to the beginning of the buffer while the second one returns a pointer to a location within the buffer where the message starts. Let's introduce a macro `HAVE_STRERROR_R_GNU` set if the GNU version is available and define `tt_strerror()` which writes the message to the static buffer, like `tt_cstr()` or `tt_sprintf()`.
Note, we have to export `tt_strerror()`, because it is used by Lua via FFI. We also need to make it available in the module API header, because the `say_syserror()` macro uses …
> Use MT-Safe `strerror_r` instead of `strerror`

- changelogs/unreleased/gh-6833-decode-body-http-response.md
- changelogs/unreleased/gh-6833-encode-body-http-request.md
- src/lua/httpc.lua
- test/app-luatest/http_client_test.lua
- test/app-luatest/http_client_unit_test.lua
- test/app-luatest/httpd.py
- `client_object:request()` could pass a body as a string value when HTTP
POST request is used. 
- Added method `reponse:json()` that decodes HTTP body.
RFC: https://www.notion.so/tarantool/HTTP-body-531cfa0f4edb4012ba73b4fa14493864
Closes #6833
> lua/http: serialize and deserialize http body

- src/box/engine.c
- src/box/engine.h
- src/box/memtx_engine.cc
- src/box/read_view.c
- src/box/read_view.h
- Filter out temporary spaces on read view creation unless the `read_view_opts::needs_temporary_spaces` flag is set and drop temporary space filter from checkpoint and join code.
- Pass `read_view_opts` to `engine_create_read_view`. In case of memtx, delay garbage collection of temporary tuples if the flag is set.
Needed for https://github.com/tarantool/tarantool-ee/issues/213
> read_view: add option to include temporary spaces

- changelogs/unreleased/gh-7493-memtx-hash-idx-repeatable-read-violation.md
- src/box/memtx_tx.c
- test/box-luatest/gh_7493_memtx_hash_idx_repeatable_read_violation_test.lua
When conflicting transactions that made full scans in
`memtx_tx_handle_gap_write`, we need to also track that the conflicted
transaction has read the inserted tuple, just like we do in gap tracking
for ordered indexes — otherwise another transaction can overwrite the
inserted tuple in which case no gap tracking will be handled.
Closes #7493
NO_DOC=bugfix
> memtx: track read story in when conflicting full scans due to gap write

- changelogs/unreleased/merger-use-after-free-in-gen.md
- src/box/lua/merger.c
- test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua
All merge sources (including the merger itself) share the same `<merge source>:pairs()` implementation, which returns `gen, param, state` triplet. `gen` is `lbox_merge_source_gen()`, `param` is `nil`, `state` in the merge source.
The `lbox_merge_source_gen()` returns `source, tuple`. The returned source is supposed to be the same object as one passed to the function (`gen(param, state)`), so the function assumes the object as alive and don't increment source's refcounter at entering, don't decrease it at exitting.
This logic is perfect, but there was a mistake in the implementation: the function returns a new cdata object (which holds the same pointer to the merge source structure) instead of the same cdata object.
The new cdata object neither increases the source's refcounter at pushing …
> lua/merger: fix use-after-free during iteration

- test/CMakeLists.txt
- test/unit/CMakeLists.txt
Commit 9adedc ("test: add new `make` test targets") introduced new
targets for running test-run.py with unit tests. However, this target
doesn't depend on changes in tested libraries and changes in unit tests.
Proposed patch introduces a function that creates a build targets for
unit tests and fixes the described problem with dependencies.
Additionally, patch added missed dependence for popen and popen-child.
> Make unit testing depending on source changes

- changelogs/unreleased/gh-7449-tuple-is-dirty-assertion-on-replace.md
- src/box/memtx_bitset.cc
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- test/box-luatest/gh_7449_tuple_is_dirty_assertion_on_replace_test.lua
`directly_replaced` stories can potentially get garbage collected in
`memtx_tx_handle_gap_write`, which is unexpected and leads to 'use after
free': in order to fix this, limit garbage collection points only to
external API calls.
Wrap all possible garbage collection points with explicit warnings (see
https://github.com/tarantool/tarantool/commit/c9981a567c74d494064499e555c5a995133d7019).
Closes https://github.com/tarantool/tarantool/issues/7449
> memtx: fix 'use after free' of garbage collected MVCC stories

- CMakeLists.txt
- changelogs/unreleased/gh-7536-add-cmake-enable_hardening-option.md
- cmake/BuildAres.cmake
- cmake/BuildLibCURL.cmake
- cmake/BuildLibUnwind.cmake
- cmake/BuildNghttp2.cmake
- debian/rules
- rpm/tarantool.spec
- static-build/CMakeLists.txt
Introduce cmake option ENABLE_HARDENING, which is TRUE by default for
regular and static builds. It passess compiler flags that harden Tarantool
(including the bundled libraries) against memory corruption attacks.
The following flags are passed:
* `-Wformat` - Check calls to printf and scanf, etc., to make sure that
the arguments supplied have types appropriate to the format string
specified.
* `-Wformat-security -Werror=format-security` - Warn about uses of format
functions that represent possible security problems. And make the
warning into an error.
* `-fstack-protector-strong` - Emit extra code to check for buffer
overflows, such as stack smashing attacks.
* `-fPIC` - Generate position-independent code (PIC). It allows to take
advantage of Address Space Layout Randomization (ASLR).
* …
> cmake: add extra security compiler options

- test/app/suite.ini
- test/box-py/suite.ini
- test/box/suite.ini
- test/engine/suite.ini
- test/engine_long/suite.ini
- test/long_run-py/suite.ini
- test/replication-py/cluster.test.py
- test/replication-py/init_storage.test.py
- test/replication-py/multi.test.py
- test/replication-py/suite.ini
- test/replication-py/swap.test.py
- test/replication/suite.ini
- test/vinyl/suite.ini
- test/wal_off/suite.ini
- test/xlog-py/suite.ini
- test/xlog/suite.ini
Bump test-run to new version with the following improvements:
- Report job summary on GitHub Actions [1]
- Free port auto resolving for TarantoolServer and AppServer [2]
- Improve getting iproto port for tarantool < 2.4.1 [3]
Also, this patch includes the following changes:
- removing `use_unix_sockets` option from all suite.ini config files
due to permanent using Unix sockets for admin connection recently
introduced in test-run
- switching replication-py tests to Unix sockets for iproto connection
- fixing replication-py/swap.test.py test
[1] tarantool/test-run#341
[2] tarantool/test-run#348
[3] tarantool/test-run#349
> [1.10] test: bump test-run to new version

- src/box/tuple_constraint_def.c
- test/engine-luatest/gh_6436_complex_foreign_key_test.lua
- test/engine-luatest/gh_6436_field_constraint_test.lua
- test/engine-luatest/gh_6436_field_foreign_key_test.lua
- test/engine-luatest/gh_6436_tuple_constraint_test.lua
Currently, it is possible to create a constraint with a name that does
not match the rules for identifiers. Fix this by validating them by
identifier_check.
Closes #7201
> box: check constraint name against identifier rules

- changelogs/unreleased/gh-6832-httpc-params-encoding.md
- changelogs/unreleased/gh-6832-uri-values.md
- src/lua/httpc.lua
- src/lua/uri.lua
- test/app-luatest/http_client_test.lua
- test/app-luatest/uri_unit_test.lua
Closes #6832
Spec: https://www.notion.so/tarantool/http-add-support-of-encoding-table-with-parameters-to-query-string-in-request-c192bdeeaf5c46b2bb7f1e5731f42ed8
> Implemention of encoding params in http client

- changelogs/unreleased/gh-7685-memtx-tree-idx-get-with-nullable-field-phantom-read.md
- src/box/index_def.c
- src/box/memtx_tree.cc
- test/box-luatest/gh_7685_memtx_tree_idx_get_with_nullable_field_phantom_read_test.lua
**memtx: fix TREE index `get` check for part count**
If TREE index `get` result is empty, the key part count is incorrectly
compared to the tree's `cmp_def->part_count`, though it should be compared
with `cmp_def->unique_part_count`. But we can actually assume that by the
time we get to the index's `get` method the part count is equal to the
unique part count (partial keys are rejected and `get` is not
supported for non-unique indexes): change check to correct assertion.
Closes #7685
**memtx: refactor `index_def_new`**
Since `key_def_merge` sets the merged key definition's unique part count
equal to the new part count, the extra assignment in case the index is not
unique is redundant: remove it.
> memtx: fix TREE index `get` check for part count

- changelogs/unreleased/gh-7670-memtx-tx-manager-idx-rand-inconsistency.md
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- test/box-luatest/gh_7670_memtx_tx_manager_idx_rand_inconsistency_test.lua
- test/box-luatest/suite.ini
TREE (HASH) index implements `random` method: if `random` returns nothing, i.e. the space is empty, add gap tracking of whole range (full scan tracking), since this result is equivalent to `index:select{}`, otherwise clarify result.
Closes #7670
> memtx: track `index:random` reads and clarify result

- test/app-luatest/gh_6817_console_memory_leak_test.lua
- test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua
- test/app-luatest/http_client_test.lua
- test/app-luatest/http_client_unit_test.lua
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box-luatest/gh_6260_add_builtin_events_test.lua
- test/replication-luatest/election_split_vote_test.lua
- test/replication-luatest/gh_5295_split_brain_test.lua
- test/replication-luatest/gh_5568_read_only_reason_test.lua
Some luatest framework tests use Lua assertions which are incomprehensible when failed (the only information provided is 'assertion failed!'), making debugging difficult: replace them with luatest assertions and their context-specific varieties.
Closes #7713
> test: replace Lua assertions with luatest assertions in luatest tests

- changelogs/unreleased/gh-7343-unserializable-read-tracked-incorrectly-after-rollback.md
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box-luatest/gh_7343_unserializable_read_tracked_incorrectly_after_rollback_test.lua
- test/box-luatest/gh_7490_memtx_tx_manager_mvcc_invariant_violation_test.lua
- test/box/tx_man.result
- test/box/tx_man.test.lua
When we rollback a transaction statement, we relink its read trackers
to a newer story in the history chain, if present (6c990a7), but we do not
handle the case when there is no newer story.
In order to fix this, we need to retain stories added by rollbacked
transactions, because they store the reader list needed for conflict
resolution.
There are several nuances we need to account for:
Firstly, such stories must be impossible to read from an index: this is
ensured by `memtx_tx_tuple_clarify`.
Secondly, rollbacked transactions need to be treated as prepared with
stories that have `add_psn == del_psn` the stories they add need to be
'sunk' to the level of prepared transactions, so now we have the following
totally ordered set over tuple stories: …
> memtx: rework transaction rollback

- changelogs/unreleased/hide-show-prompt.md
- src/CMakeLists.txt
- src/box/lua/console.c
- src/lib/core/say.c
- src/lib/core/say.h
- src/lua/init.c
- src/lua/print.lua
- test/box-luatest/hide_show_prompt_test.lua
- test/luajit-test-init.lua
- test/luatest_helpers/interactive_tarantool.lua
The idea is borrowed from [1]: hide and save prompt, user's input and
cursor position before writing to stdout/stderr and return everything
back afterwards.
Not every stdout/stderr write is handled this way: only tarantool's
logger (when it writes to stderr) and tarantool's print() Lua function
performs the prompt hide/show actions. For example,
`io.stdout:write(<...>)` Lua call or `write(STDOUT_FILENO, <...>)` C
call may mix readline's prompt with actual output. However the logger
and print() is likely enough for the vast majority of usages.
The readline's interactive search state (usually invoked by Ctrl+R) is
not covered by this patch. Sadly, I didn't find a way to properly save
and restore readline's output in this case.
Implementation details
----------------------
Several words …
> console: don't mix stdout/stderr with readline prompt

- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/errcode.h
- src/box/index.cc
- src/box/index.h
- src/box/iproto.cc
- src/box/lua/misc.cc
- src/box/lua/schema.lua
- src/box/memtx_bitset.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/session_settings.c
- src/box/sysview.c
- src/box/tuple_compare.cc
- src/box/tuple_extract_key.cc
- src/box/vinyl.c
- test/box/error.result
- test/engine-luatest/pagination_test.lua
- test/unit/CMakeLists.txt
- test/unit/iterator_position.c
- test/unit/key_def.c
This patchset adds helpers, needed for pagination, new options after and fetch_pos for select (both FFI and LuaC), and pagination to memtx tree. All the types of tree indexes (multikey, functional) are suported.
Documentation will be added in a later patchset.
Closes #7633
Closes #7635
Closes #7636
> Memtx tree pagination

- changelogs/unreleased/gh-7584-missing-xlog-fix.md
- src/box/wal.c
- src/lib/vclock/vclock.h
- test/replication-luatest/gh_7584_missing_xlog_test.lua
When using vclockset_psearch, the resulting vclock may be incomparable to the search key. For example, with a vclock set { } (empty vclock), {0: 1, 1: 10}, {0: 2, 1:11} vclockset_psearch(set, {0:2, 1: 9}) might return {0: 1, 1: 10}, and not { }.
This is known and avoided in other places, for example recover_remaining_wals(), where vclockset_match() is used instead. vclockset_match() starts with the same result as vclockset_psearch() and then unwinds the result until the first vclock which is less or equal to the search key is found.
Having vclockset_psearch in wal_collect_garbage_f could lead to issues even before local space changes became written to 0-th vclock component. Once replica subscribes, its' gc consumer is set to the vclock, which the replica sent in subscribe request. This …
> gc: replace vclockset_psearch with _match in wal_collect_garbage_f

- src/box/lua/load_cfg.lua
- src/box/lua/net_box.lua
In most places (schema.lua for example) we use box.error() to throw error after error return from C function. Function is supposed to set diag and box.error() will throw error based on the diag. For example (crypto.lua):
local ctx = ffi.C.crypto_stream_new(algo, mode, direction)
if ctx == nil then
box.error()
end
This code is nice in case C function does not forget to set a diag.
But we have a different usage idiom of box.error().
local result = pcall(module.cfg)
if not result and oldvals ~= nil then
rollback_module(module, oldcfg, keys, oldvals)
return box.error()
end
How it can go wrong? module.cfg is not necessary a C function. If it is a Lua function it can throw error without diag. And if diag is not set then box.error() is NOOP. So if there is a bug in code then Lua generates error …
> box: fix usage of pcall/box.error idiom

- changelogs/unreleased/add-redos-7.3-ci-cd.md
- changelogs/unreleased/gh-4450-logger-sigsegv-revert.md
- changelogs/unreleased/gh-7086-box_issue_promote_demote_asserts.md
- changelogs/unreleased/gh-7253-split-brain-early-vote.md
- changelogs/unreleased/gh-7343-unserializable-read-tracked-incorrectly-after-rollback.md
- changelogs/unreleased/gh-7434-yield-in-on_shutdown-trigger.md
- changelogs/unreleased/gh-7449-tuple-is-dirty-assertion-on-replace.md
- changelogs/unreleased/gh-7493-memtx-hash-idx-repeatable-read-violation.md
- changelogs/unreleased/gh-7670-memtx-tx-manager-idx-rand-inconsistency.md
- changelogs/unreleased/gh-7685-memtx-tree-idx-get-with-nullable-field-phantom-read.md
- changelogs/unreleased/gh-7705-json-update-crash.md
- changelogs/unreleased/igrishnov/gh-7479-bug-fix-uri-lib.md
- changelogs/unreleased/merger-use-after-free-in-gen.md
- changelogs/unreleased/popen-mac-os-race.md
- changelogs/unreleased/promote-hang.md
- changelogs/unreleased/strerror-mt-safe.md
Fix wording, punctuation, and formatting.
> doc: proofread 2.10.3 changelog

- changelogs/2.10.3.md
- changelogs/unreleased/add-redos-7.3-ci-cd.md
- changelogs/unreleased/gh-4450-logger-sigsegv-revert.md
- changelogs/unreleased/gh-6801-high-cpu-usage-by-on_shutdown-triggers.md
- changelogs/unreleased/gh-7086-box_issue_promote_demote_asserts.md
- changelogs/unreleased/gh-7253-fiber-hang-on-fencing.md
- changelogs/unreleased/gh-7253-split-brain-early-vote.md
- changelogs/unreleased/gh-7343-unserializable-read-tracked-incorrectly-after-rollback.md
- changelogs/unreleased/gh-7434-yield-in-on_shutdown-trigger.md
- changelogs/unreleased/gh-7449-tuple-is-dirty-assertion-on-replace.md
- changelogs/unreleased/gh-7493-memtx-hash-idx-repeatable-read-violation.md
- changelogs/unreleased/gh-7536-add-cmake-enable_hardening-option.md
- changelogs/unreleased/gh-7584-missing-xlog-fix.md
- changelogs/unreleased/gh-7670-memtx-tx-manager-idx-rand-inconsistency.md
- changelogs/unreleased/gh-7685-memtx-tree-idx-get-with-nullable-field-phantom-read.md
- changelogs/unreleased/gh-7705-json-update-crash.md
- changelogs/unreleased/igrishnov/gh-7479-bug-fix-uri-lib.md
- changelogs/unreleased/merger-use-after-free-in-gen.md
- changelogs/unreleased/popen-mac-os-race.md
- changelogs/unreleased/promote-hang.md
- changelogs/unreleased/promote-multiple-infinite.md
- changelogs/unreleased/strerror-mt-safe.md
Generate changelog for 2.10.3 release.
Also, clean changelogs/unreleased folder.
> Generate changelog for 2.10.3

- changelogs/unreleased/gh-7712-loss-of-commited-tuple-in-secondary-index.md
- src/box/memtx_tx.c
- test/box-luatest/gh_7712_loss_of_commited_tuple_in_secondary_index_test.lua
Concurrent transactions can try to insert tuples that intersect only by parts of secondary index: in this case when one of them gets prepared, the others get conflicted, but the committed story does not get retained (because the conflicting statements are not added to the committed story's delete statement list as opposed to primary index) and is lost after garbage collection: retain stories if there is a newer uncommitted story in the secondary indexes' history chain.
Closes #7712
> memtx: fix loss of committed tuple in secondary index

- src/box/lua/index.c
- src/box/lua/schema.lua
- test/box-luatest/box_read_ffi_disable_test.lua
This PR fixes a minor error reporting bug when `box_read_ffi_is_disabled` is set, which was introduced by commit 7f2c760967e40. It also adds a bunch of tests that ensure that FFI and Lua C version of index read operations are equivalent.
Fixes https://github.com/tarantool/tarantool-ee/issues/254
> box: fix usage error messages if FFI is disabled for index read ops

- changelogs/unreleased/gh-7231-memtx-hash-idx-gt-iter-deprecation.md
- src/box/memtx_hash.cc
- test/box-luatest/gh_7231_memtx_hash_idx_gt_iter_deprecation_test.lua
For reasons described in #7231 HASH index 'GT' iterator type is deprecated: print a warning exactly once about the deprecation.
Closes #7231
> memtx: deprecate HASH index 'GT' iterator type

- src/lua/datetime.lua
- test/app-luatest/gh_7273_dt_new_err_on_cdata_test.lua
dt.new() will raise a clear error on wrong timestamp type.
Closes #7273
NO_DOC=bugfix
> lua/datetime: clearer error msg for new()

- changelogs/unreleased/fix-bootstrap-with-er-readonly.md
- src/box/applier.cc
- test/replication-luatest/gh_7377_bootstrap_connection_failure_test.lua
The commit c1c77782215e ("replication: fix bootstrap failing with ER_READONLY") made applier retry connection infinitely upon receiving a ER_READONLY error on join. At the time of writing that commit, this was the only way to make join retriable. Because there were no retries in scope of bootstrap_from_master. The join either succeeded or failed.
Later on, bootstrap_from_master was made retriable in commit f2ad1deecbea ("replication: retry join automatically"). Now when bootstrap_from_master fails, replica reconnects to all the remote nodes, thus updating their ballots, chooses a new (probably different from the previous approach) bootstrap leader, and retries booting from it.
The second approach is more preferable, and here's why. Imagine bootstrapping a cluster of 3 nodes, A, B and C in …
> replication: make ER_READONLY non-retriable for applier

- tools/gen-bootstrap.sh
By design after patching update.lua, introducing new data version, a developer needs to update bootstrap.snap, which would have the new data version.
Generation of bootstrap.snap is a bit tricky, there's a manual: https://github.com/tarantool/tarantool/wiki/How-to-generate-new-bootstrap-snapshot
This commit presents a simple script that automates the process. Just run it in tarantool build directory and check its output. Check --help for script options.
Follow-up of tarantool/security#14
NO_DOC=internal tool
NO_TEST=internal tool
NO_CHANGELOG=internal tool
> tools: add a srcipt that updates bootstrap.snap

- changelogs/unreleased/gh-7253-split-brain-old-term-txn.md
- src/box/applier.cc
- src/box/applier.h
- src/box/box.cc
- src/box/relay.cc
- src/box/xrow.c
- src/box/xrow.h
- src/lib/raft/raft.c
- src/lib/raft/raft.h
- test/luatest_helpers/misc.lua
- test/luatest_helpers/server.lua
- test/replication-luatest/gh_5295_split_brain_test.lua
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_6036_qsync_order_test.lua
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/gh_7086_box_issue_promote_assert_test.lua
- test/replication-luatest/gh_7253_election_long_wal_write_test.lua
- test/replication/gh-5195-qsync-replica-write.result
- test/replication/gh-5195-qsync-replica-write.test.lua
- test/replication/gh-5213-qsync-applier-order-3.result
- test/replication/gh-5213-qsync-applier-order-3.test.lua
The patchset gets rid of a potential split-brain case, which could happen if an old leader would make a txn and CONFIRM it while a new term was already going on #7253.
In the last commit I update test 6036, but it doesn't seem related to #7785. The latter fails extremely rare and in logs I can see something about split brain.
Also the linearizable read test fails occasionally, it is a known problem.
> Fix split-brain on a late CONFIRM from an old leader

- .gitmodules
- cmake/compiler.cmake
- src/lib/core/backtrace.c
- src/trivia/config.h.cmake
**libunwind: bump new version**
libunwind/libunwind@f67ef28 adds the ability for libunwind to unwind a
stack where the return address obtained from the AARCH6 link register (x30)
has a pointer authentication code (PAC).
Needed for #7285
**core: remove workaround for backtracing with PAC on AARCH64**
With libunwind/libunwind@f67ef28 we can now use `unw_backtrace` with
PAC enabled on AARCH64 and remove the workaround with glibc's `backtrace` for
this case.
Closes #7285
> Remove workaround for backtracing with PAC on AARCH64

- .github/workflows/luajit-integration.yml
It's quite inconvenient to extend LuaJIT integration workflow now: one need to patch GitHub workflow file in Tarantool repository and then setup integration testing in LuaJIT repository.
This patch introduces a new workflow parameter that can replace several existing paramters (e.g. buildtype and GC64) and allow to easy extend integration CI in LuaJIT (with rare little touches in Tarantool).
NO_DOC=ci
NO_TEST=ci
P.S. Test results of the changes made can be found here: tarantool/luajit@c807be7.
P.P.S Examples of `CMAKE_EXTRA_PARAMS` usage can be found here: tarantool/luajit@227d1b0 and tarantool/luajit@65b7d7c.
> ci: add CMAKE_EXTRA_PARAMS to LuaJIT workflow

- changelogs/unreleased/gh-7698-datetime-subtraction-with-tz.md
- changelogs/unreleased/gh-7700-interval-arithmetic-across-dst.md
- src/lib/core/datetime.c
- test/app-tap/datetime.test.lua
Interval arithmetic across DST boundaries
===========================
We did not take into consideration the fact that as result of date/time arithmetic we could get in a different timezone, if DST boundary has been crossed during operation.
```
tarantool> datetime.new{year=2008, month=1, day=1, tz='Europe/Moscow'} + datetime.interval.new{month=6}
---
- 2008-07-01T01:00:00 Europe/Moscow
...
```
Now we resolve tzoffset at the end of operation if tzindex is not 0.
Fixes #7700
Timezone differences in subtraction
=======================
We used to ignore timezone difference (im `tzoffset`) for datetime subtraction operation:
```
tarantool> datetime.new{tz='MSK'} - datetime.new{tz='UTC'}
---
- +0 seconds
...
tarantool> datetime.new{tz='MSK'}.timestamp - datetime.new{tz='UTC'}.timestamp
---
- …
```
> datetime: fix interval arithmetic across DST boundaries

- changelogs/unreleased/gh-7155-uri-optimize-add-param-and-add-param-value.md
- src/lib/uri/uri.c
- src/lib/uri/uri.h
- src/lua/uri.lua
**uri: add warnings about exposure of structs in Lua via FFI**
`struct uri_param` and `struct uri` are exposed in Lua via FFI
(see src/lua/uri.lua): add warnings about the necessity of reflecting
changes to them in `ffi.cdecl`.
**uri: optimize allocation of parameters and their values dynamic arrays**
Allocation of URI parameters and their values dynamic arrays is done
inefficiently: they are reallocated each time a new parameter or parameter
value is added — grow them exponentially instead.
Closes #7155
> uri: optimize allocation of parameters and their values dynamic arrays

- src/box/index.h
- src/box/memtx_engine.cc
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/sequence.c
This is a straightforward patch that makes the read view iterator struct fixed-size so that it can be allocated on stack. This is a pre-requisite for the raw C API for read views: the function that creates an iterator should allocate no memory.
Closes #7813
EE part: https://github.com/tarantool/tarantool-ee/pull/266
> index: make index_read_view_iterator fixed size

- changelogs/unreleased/ghs_16_user_enumeration.md
- src/box/applier.cc
- src/box/authentication.cc
- src/box/errcode.h
- test/box-luatest/ghs_16_user_enumeration_test.lua
- test/box/error.result
- test/box/net.box_incorrect_iterator_gh-841.result
- test/box/net.box_uri_first_arg_gh-398.result
If we raise different errors in case of entering an invalid password and entering the login of a non-existent user during authorization, it will open the door for an unauthorized person to enumerate users. So let's unify raised errors in the cases described above.
Closes #tarantool/security#16
> box: unify errors about mismatch of password and login during auth

- .gitignore
Add missing .gitignore entry for autogenerated .lua.c translation units located in <third_party/lua> directory.
Follows up #7593
NO_DOC=.gitignore
NO_TEST=.gitignore
NO_CHANGELOG=.gitignore
Signed-off-by: Igor Munkin <imun@tarantool.org>
> .gitignore: add .lua.c suppression in third party

- .github/workflows/coverage.yml
After we switched from the `coverallsapp/github-action` action to the
`coveralls-lcov` utility, the following issue started to happen while
uploading coverage results to coveralls.io:
/var/lib/gems/2.7.0/gems/coveralls-lcov-1.7.0/lib/coveralls/lcov/converter.rb:64:
in `initialize': No such file or directory @ rb_sysopen - /opt/actions-runner/_work/tarantool/tarantool/src/src/uri.rl (Errno::ENOENT)
from /var/lib/gems/2.7.0/gems/coveralls-lcov-1.7.0/lib/coveralls/lcov/converter.rb:64:in `open'
from /var/lib/gems/2.7.0/gems/coveralls-lcov-1.7.0/lib/coveralls/lcov/converter.rb:64:in `generate_source_file'
from /var/lib/gems/2.7.0/gems/coveralls-lcov-1.7.0/lib/coveralls/lcov/converter.rb:17:in `block in convert'
from /var/lib/gems/2.7.0/gems/coveralls-lcov-1.7.0/lib/coveralls/lcov/converter.rb: …
> [1.10] ci: fix uploading coverage results to coveralls.io

- changelogs/unreleased/gh-7797-untrusted-input-validation.md
- src/box/lua/console.c
- src/box/module_cache.c
- src/box/sql/os_unix.c
- src/find_path.c
- src/lib/core/coio_file.c
- src/lib/core/coio_file.h
- src/lib/core/errinj.c
- src/lib/core/util.c
- src/lua/init.c
- src/lua/utils.c
- src/main.cc
- src/systemd.c
- src/trivia/util.h
- test/unit/CMakeLists.txt
- test/unit/getenv_safe.c
As seen in error reports from [TNT-601](https://jira.vk.team/browse/TNT-601), `getopt_long`, `getopt` and `realpath` are subject to internal buffer overflows (at least they used to be some time ago).
The suggestion is to either not use them, or provide them with correct input.
Speaking of `realpath`, we have 2 places that use it:
```console
sergey@sergey-pc:~/Source/sptnt$ grep -rn realpath ./src --include *.c --include *.h --include *.cc --include *.cpp --include *.hpp --exclude *.lua.c --include *.lua
./src/box/module_cache.c:119:	if (realpath(lua_tostring(L, -1), resolved) == NULL) {
./src/box/module_cache.c:120:		diag_set(SystemError, "realpath");
./src/box/module_cache.c:126:	 * is guaranteed by realpath call.
./src/find_path.c:79:	if (realpath(buf, path) == NULL)
```
Both these …
> Validate untrusted user input

- changelogs/unreleased/gh-7814-box-error-in-thread.md
- src/lib/core/CMakeLists.txt
- src/lib/core/cord_on_demand.cc
- src/lib/core/cord_on_demand.h
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lib/core/say.c
- test/unit/error.c
We're planning to introduce a basic C API for user read views (EE-only). Like all other box C API functions, the new API functions will use the existing box error C API for reporting errors. The problem is that a read view created using C API should be usable from user threads (started with the pthread lib) while the box error C API doesn't work in user threads, because those threads don't have the cord pointer initialized (a diagnostic area is stored in a cord object).
To address this issue, let's create a new cord object automatically on first use of `cord()` if it wasn't created explicitly. Automatically created object is destroyed at thread exit (to achieve that, we use the C++ RAII concept).
Closes #7814
> fiber: initialize thread-local cord on demand

- changelogs/unreleased/gh-7255-box-info-before-cfg.md
- src/box/box.cc
- src/box/lua/load_cfg.lua
- test/box-luatest/gh_7255_box_info_before_cfg_test.lua
So one can easily check current box status.
See discussion in previous [PR](https://github.com/tarantool/tarantool/pull/7407) on why box.info() and not box.is_configured.
Closes #7255
> box: expose box.info() before box.cfg()

- changelogs/unreleased/gh-7818-msgpack-0xc1-fix.md
- test/app-luatest/msgpack_test.lua
- test/unit/msgpack.result
0xc1 isn't a valid MsgPack header, but it was allowed by mp_check. As a result, `msgpack.decode` crashed while trying to decode it. This commit updates the msgpuck library to fix this issue.
Closes #7818
> msgpack: fix crash on decode of 0xc1

- src/box/index.cc
- src/box/index.h
- src/box/memtx_allocator.cc
- src/box/memtx_allocator.h
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/read_view.c
- src/box/read_view.h
- src/box/sequence.c
- src/box/sequence.h
- test/unit/memtx_allocator.cc
This PR adds an internal option that makes read view read methods skip decompression of compressed tuples. If this flag is set, the user is supposed to decompress the `MP_COMPRESSION` message pack extension manually. The purpose of this option is to eliminate all memory allocations in the raw read view API (decompressed data is stored on the fiber region), which is a prerequisite for the basic public read view C API.
Apart from adding the new option, this PR also does some code cleanup: renames a few read view options; drops `memtx_read_view_opts` in favor of the generic `read_view_opts` structure.
Closes #7815
EE part: https://github.com/tarantool/tarantool-ee/pull/268
> Add option to disable decompression of read view tuples

- changelogs/unreleased/gh-7583-txn-stat.md
- src/box/txn.c
- test/box-luatest/gh_7583_txn_stat_test.lua
This commit fixes `BEGIN`, `COMMIT`, and `ROLLBACK` counters in the `box.stat()` output. Before this commit, they always showed 0. Now, they report the number of started, committed, and rolled back transactions, respectively.
Closes #7583
> txn: account started, committed, and rolled back transactions

- .github/workflows/coverity.yml
Fixes tarantool/tarantool-qa#281
Coverity job: https://github.com/tarantool/tarantool/actions/runs/3360841659/jobs/5570516149. It successfully passed the checkout stage, but failed because of `secrets.COVERITY_TOKEN` being unavailable in a fork-based PR.
> ci: recursive checkout in coverity action

- changelogs/unreleased/gh-4450-fix-crash-on-logrotate-and-exit.md
- src/lib/core/say.c
- src/lib/core/say.h
- test/unit/say.c
`say_logrotate` does not rotate logs synchronously. It posts tasks to
coio which executes them in it's pool thread. On application exit we
destroy logs calling `log_destroy`. This function waits for rotate task
to finish because if it will free resources immediately then unfinished
rotate task can have use-after-free issues. Waiting crashes because at
this moment event loop is not running which is required for
`fiber_cond_wait` to work.
Note that if there is no crash then we will hang forever waiting in
`log_destroy` because event loop is not running and
`log_rotate_async_cb` will never be executed.
Let's use mutexes and conditions instead. It solves both problems with
crash and hang. Thanks Vladimir Davydov for idea.
Fixes #4450
NO_DOC=bugfix
> app: fix crash on logrotate and immediate exit

- test/replication/transaction.result
- test/replication/transaction.test.lua
The test is expected the replication is broken by the time of the server switch. Apparently, switch won the race, so the expectation is changed for waiting.
Closes https://github.com/tarantool/tarantool-qa/issues/271
NO_DOC=testing
> test: replication/transaction flakiness fix

- changelogs/unreleased/gh-7652-complex-fkey-new-field-name.md
- src/box/alter.cc
- test/engine-luatest/gh_6436_field_constraint_test.lua
- test/engine-luatest/gh_7652_complex_fkey_new_field_name_test.lua
- test/engine/ddl.result
- test/engine/json.result
- test/vinyl/errinj_ddl.result
If a complex (tuple) foreign key is added along with a new field name that participates in that foreign key, the foreign key does not work correctly. This happens because the new name of a local field is added to `new_space->def->dict` only in `ModifySpace::alter()`, while before that, `new_space->def->dict` points to the old dictionary with old names (see `ModifySpace::alter_def()`). So when `local_field_no` is initialized earlier in `alter_space_do` -> `space_create` -> `tuple_constraint_fkey_init`, it's unable to find the new field number in the old dictionary.
Fix this by moving `new_def->dict = alter->old_space->def->dict;` from `ModifySpace::alter_def()` to `ModifySpace::alter()`. Note that, as before, we refer to the old dictionary from the new space (just put new names into it), …
> box: fix fkey creation together with new field names

- changelogs/unreleased/gh-7447-fix-panic-on-invalid-log.md
- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/lua/load_cfg.lua
- src/lib/core/say.c
- src/lib/core/say.h
- src/lua/log.lua
- src/lua/utils.c
- src/lua/utils.h
- src/main.cc
- static-build/test/static-build/exports.test.lua
- test/app-tap/gh-5130-panic-on-invalid-log.test.lua
- test/app-tap/logger.test.lua
- test/app-tap/logmod.test.lua
- test/unit/CMakeLists.txt
- test/unit/lua_utils.c
- test/unit/memtx_allocator.cc
- test/unit/popen.c
- test/unit/raft_test_utils.c
- test/unit/say.c
- test/unit/swim_proto.c
- test/unit/swim_test_utils.c
- Log configuration on first configuration thru box.cfg() is really painful:
1. check log cfg validity in scope of private.cfg_check (1)
2. set log option values to log.cfg in update_module_cfg. We also check log cfg validity (2) here in api.cfg_set and have rollback logic (why he have to?)
3. make actual log initialization in private.cfg_load()
4. update dynamic options of log cfg once again. Why? Probably only to make conversions like for log_level from 'warn' to number. We make cfg validity checks here too! (3)
I guess we'd better have only one validity check and don't run step 4 which actually reconfigure log once again only to perform conversion.
- Log API is painfully bloated:
- log.level - to set log level by user
- log.box_api.cfg_get - private API to just get log level (why not …
> Refactoring of log.cfg() and box.cfg() from the POV of log configuration

- src/CMakeLists.txt
- src/box/lua/init.c
- src/lua/builtin_modcache.c
- src/lua/builtin_modcache.h
- src/lua/init.c
- test/app-luatest/tnt_debug_getsources_test.lua
We did not support box lua modules, while were supporting lua sources embedded into `libserver.a`. Now we extended `tarantool.debug.getsources()` to support both cases:
```lua
local files = {
'strict',
'debug',
'errno',
'fiber',
'env',
'datetime',
'box/session',
'box/tuple',
'box/key_def',
'box/schema',
'box/xlog',
'box/net_box',
'box/console',
'box/merger',
}
local tnt = require('tarantool')
local luadebug = tnt.debug
for _, file in pairs(files) do
local src1 = luadebug.getsources(file)
local src2 = luadebug.getsources(('@builtin/%s.lua'):format(file))
print(file, src1 ~= nil, src2 ~= nil)
end
os.exit(0)
``` 
```
strict  true    true
debug   true    true
errno   true    true
fiber   true    true
env     true    true
datetime        true    true
box/session     true    true
box/tuple …
```
> debugger: extend tarantool.debug.getsources for box modules

- test/sql-tap/select1.test.lua
SQL select1:1-8.4 test didn't have any rationale in modern tarantool SQL and had been turned off since 2017.
Closes: #5737
NO_DOC=test
> test: remove outdated sql-tap test

- test/app-luatest/console_debugger_session_test.lua
Appeared that ASAN build could return nil values from child process executed via popen. Which sporadically produces error messages:
```
not ok 1 ..console_debugger_session.test_interactive_debugger_session
```
Due to used timeouts we are ok to receive nil at one of a loop cycle - we simply repeat read to popen object. So handle this case gracefully.
Closes #7882
> ci, debugger: gracefully handle nil values from popen

- src/lib/core/decimal.c
- test/unit/decimal.c
decimal_unpack() and hence mp_decode_decimal() didn't check length of digits array, overflowing the output structure.
Fix that and a couple of typos in comments as well.
Closes https://github.com/tarantool/security/issues/17
NO_DOC=security
NO_CHANGELOG=security
> decimal: fix buffer overflow in decimal_unpack()

- changelogs/unreleased/ghs-17-fix-decimal-unpack-overflow.md
Add a forgotten changelog entry.
Follow-up https://github.com/tarantool/security/issues/17
> A changelog for buffer overflow in decimal_unpack

- changelogs/unreleased/ghs-18-mp-check-overflow-fix.md
- test/unit/msgpack.result
The bug was fixed in https://github.com/tarantool/msgpuck/pull/24. This commit just bumps the submodule.
Closes https://github.com/tarantool/security/issues/18
> msgpack: fix integer overflow in mp_check

- test/replication/qsync_basic.result
- test/replication/qsync_basic.test.lua
The async transactions should always wait for LSN from the master after switch to replica. Surprising, there was a place where replica expected to have data from master, that master rolls back.
Closes tarantool/tarantool-qa#274
NO_DOC=testing
> test: fix flakiness of replication/qsync_basic

- test/replication/qsync_basic.result
- test/replication/qsync_basic.test.lua
The async transactions should always wait for LSN from the master after switch to replica.
Closes tarantool/tarantool-qa#274
NO_DOC=testing
(cherry picked from commit 0fbdfd0f031c28a35aa7bb20099def7d8422c8a5)
> [2.10] test: fix flakiness of replication/qsync_basic

- src/CMakeLists.txt
The module API header (module.h) is generated automatically by extracting everything between '\cond public' and '\endcond public' from headers listed in the api_headers CMake variable. We're planning to extend the module API in Tarantool EE. To achieve that, this commit includes all files listed in the new CMake variable EXTRA_API_HEADERS into api_headers.
Needed for https://github.com/tarantool/tarantool-ee/issues/265
> build: add EXTRA_API_HEADERS variable

- cmake/compiler.cmake
- src/box/tuple_compare.cc
- src/box/xlog.c
- test/sql-luatest/gh_6572_nan_is_not_null_test.c
- third_party/tarantool_ev.h
After revisiting the list of currently disabled compiler warnings it seems like the following are unjustifiably disabled:
* `-Wunknown-pragmas`;
* `-Wstrict-aliasing`;
* `-Wunused-value`;
* `-Wchar-subscripts`;
* `-Wformat-truncation`.
Enable them for the sake of code health.
Closes #7862
NO_DOC=build
NO_TEST=build
> build: enable unjustifiably disabled compiler warnings

- src/lib/core/say.c
- src/lib/salad/stailq.h
**stailq: add non empty list assertion to stailq_shift**
stailq_shift expects list to be non empty. Let's add assertion.
This patch addresses coverity complain [1526815](https://scan7.scan.coverity.com/reports.htm#v43693/p13437/fileInstanceId=129122176&defectInstanceId=18601010&mergedDefectId=1526815).
Closes #7913
**say: check size before write**
We potentially pass negative size to safe_write in say_default if total
is negative. We can't hit this issue currently because formatting
functions currently do not return -1. Yet let's check total value where
appropriate.
By the way fix restoring errno in log_vsay. format_log_entry_full is
introduced for this purpuse as SNPRINT macro returns in case of error.
Also add assertion to safe_write.
This patch addresses coverity complain …
> address latest coverity complains

- changelogs/unreleased/gh-7757-memtx-space-drop-triggers-assertion.md
- src/box/memtx_tx.c
- test/box-luatest/gh_7757_memtx_space_drop_triggers_assertion_test.lua
`memtx_tx_story_unlink_both` is called in two separate contexts: on space delete and on rollback. In the former case we need to simply unlink the story, while in the latter case we need to rebind read and gap trackers, and, perhaps do some other logic in the future. Calling `memtx_tx_story_unlink_both` in the former context can trigger assertion: split the function and its helpers into two separate functions for each case, grouping the common logic into third `*_common` functions.
Closes #7757
> memtx: split `memtx_tx_story_unlink_both` logic in two separate contexts

- src/box/memtx_tx.c
- test/box-luatest/gh_7343_unserializable_read_tracked_incorrectly_after_rollback_test.lua
Gap trackers are stored in the story at the top of the history chain (see `memtx_tx_story_{un}link_top_light`): following this logic, during rollback we need to rebind them to the older story. We already maintain this in 8c24259, since a story is not retained iff it has a newer story (which means it does not store trackers) or if it has an older story (in which case rebinding is done in `memtx_tx_story_{un}link_top_light`): add an assertion that a story deleted during rollback does not have any gap trackers and a test for this case.
Follow-up 8c24259
> memtx: add assertion and test for gap tracker retention during rollback

- changelogs/unreleased/gh-7761-memtx-sk-index-uniqueness-violation.md
- src/box/memtx_tx.c
- test/box-luatest/gh_7761_memtx_sk_index_uniqueness_violation_test.lua
memtx: fix conflict handling of stories in secondary indexes
If we find a newer story in the secondary index, the statement of which
deletes a story added in the same transaction, there can be two cases: if
the secondary index is not unique, this is impossible (since it's `cmp_def`
is extended with the primary index's `key_def` and there can only be story
chains in the primary index). Otherwise, the prepared story conflicts the
newer one: remove the incorrect check.
Closes https://github.com/tarantool/tarantool/issues/7761
> memtx secondary index uniqueness violation

- src/lua/fio.lua
- test/app-luatest/gh_4963_fio_pread_err_msg_test.lua
fh:pread() will raise a clear error on wrong arguments.
Closes #4963
NO_DOC=bugfix
> lua/fio: clearer error msg for pread()

- test/box-luatest/gh_7917_log_row_on_recovery_error_test.lua
The test fails with:
```
master | 2022-11-11 09:03:32.093 [4128822] main/103/default.lua F> can't initialize storage: unlink, called on fd 30, aka unix/:(socket), peer of unix/:(socket): Address already in use
```
Looks like it happens, because both test cases share the socket path. The fix is the same as in commit 3f86cd045527 ("test: fix flaky 'test_ignore_with_force_recovery'") - use different socket paths.
Follow-up commit b2dab5f4270d ("memtx: log bad row on snapshot recovery error").
> test: fix flaky box-luatest/gh_7917_log_row_on_recovery_error_test

- changelogs/unreleased/gh-7523-sigsegv-on-m1-macs.md
- third_party/coro/coro.c
Currently AArch64 version of `coro_transfer` stores `x19-x30` and `d8-d15` registers to the stack, but only after that it updates the stack pointer. If a `SIGALRM` signal is delivered during the execution of `coro_transfer`, the signal handler will use the stack starting from current `sp`, thus corrupting the saved registers.
Fix this by updating the stack pointer at the beginning of `coro_transfer`.
`x2` register is still required, because `str sp, [x0, #0]` is invalid in the A64 instruction set.
Closes #7484
Closes #7523
> coro: update `sp` before saving registers to a stack frame

- changelogs/unreleased/gh-7904-export-box_schema_version-to-public-api-and-lua.md
- src/CMakeLists.txt
- src/box/errcode.h
- src/box/iproto.cc
- src/box/lua/feedback_daemon.lua
- src/box/lua/info.c
- src/box/lua/net_box.c
- src/box/lua/schema.lua
- src/box/schema.cc
- src/box/schema.h
- src/box/sql/sqlInt.h
- src/box/sql/vdbeInt.h
- src/box/sql/vdbeapi.c
- src/box/xrow.c
- src/box/xrow.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
- test/box-luatest/gh_7904_export_box_schema_version_to_public_api_test.lua
- test/box/info.result
- test/box/schema_reload.result
- test/box/schema_reload.test.lua
- test/engine/ddl.result
- test/engine/ddl.test.lua
- test/unit/vy_point_lookup.c
`box_schema_version` symbol is currently exposed via `exports`, but it is not part of the public API: export it to public API and Lua.
Closes #7904
> box: export `box_schema_version` to public API and Lua

- test/replication/qsync_basic.result
- test/replication/qsync_basic.test.lua
Two more places where replica didn't wait until data is replicated.
Follow-up to tarantool/tarantool-qa#274
> flaky: follow-up for qsync_basic test

- changelogs/unreleased/gh-7099-fix-format-description-tarantoolctl-cat.md
- extra/dist/tarantoolctl.in
Added a description for the `--format` flag of the `tarantoolctl cat` command.
Fixes #7099
> tarantoolctl: add man of flag --format for cat command

- changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md
- src/box/relay.cc
- test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua
If you shut down the replica and delete all xlog files on it, and it reconnect to the master, may occur the restore error. Because there are intermediate xlog files between the snap on the replica and the last xlog on the master. When restoring xlog files on the replica, it can be occurred that `prev_signature < signature` and this will lead to the crash of the master.
Closes #5158
NO_DOC=bugfix
> replication: invalid recovery from xlog
