- changelogs/unreleased/gh-7592-write-to-local-spaces-with-synchro.md
- src/box/txn.c
- src/box/txn.h
- src/box/txn_limbo.c
- test/replication-luatest/gh_7592_local_write_with_syncro_test.lua
Local spaces can be written to on any replica, even on a read-only one.
This makes sense, because local space data isn't replicated, so it can't
lead to a conflict or violate consistency anyhow.
However, when used together with synchronous replication, local spaces
can't be written to by anyone but the synchro queue owner:
```
tarantool> box.info.synchro.queue.len
---
- 1
...
tarantool> box.space.loc:replace{2}
---
- error: Found uncommitted sync transactions from other instance with id 1
...
```
Fix this and allow to put transactions touching local spaces to the
synchro queue even if it is claimed by someone else.
Note, we can't let local transactions bypass the synchro queue completely.
This would lead to consistency loss in a case when synchro queue
contains a transaction [sync_row, …
> replication: fix local space writes failing when synchro queue isn't empty

- changelogs/unreleased/gh-5104-inherit-index-collation-from-format.md
- src/box/lua/schema.lua
- test/engine-luatest/gh_5104_inherit_index_collation_from_format_test.lua
If `create_index('...', {parts = {...}})` is called without the `collation` option, then use collation from the space format.
Closes #5104
> box: inherit index collation from the space format

- test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
The test fails with:
```
not ok 2 box-luatest.gh_6539_log_user_space_empty_or_nil_select.test_log_entry_presence_for_memtx_user_space
gh_6539_log_user_space_empty_or_nil_select_test.lua:122: log must contain a critical entry about `box.space.test_memtx:select({0}, {limit = 1001, iterator = "ALL"})` call on a memtx user space
expected: a value evaluating to true, actual: nil
```
Looks like it happens, because `g.server:grep_log()` is executed before `g.server:eval(call)` completes writing to the log. In other tests `grep_log()` is wrapped into `t.helpers.retrying()` in order to avoid such issues, so do the same here.
May _close tarantool/tarantool-qa#264
Let's commit it and wait a bit to see whether it stops flaking.
> test: fix flaky gh_6539_log_user_space_empty_or_nil_select_test

- src/box/tuple_format.c
Discovered by Coverity:
https://scan7.scan.coverity.com/reports.htm#v43693/p13437/fileInstanceId=130384650&defectInstanceId=18636974&mergedDefectId=1527607
Follow-up #5665
NO_TEST=nit
NO_CHANGELOG=nit
NO_DOC=nit
> box: fix typo in tuple_field_map_create_plain

- changelogs/unreleased/gh-7894-export-iproto-constants-and-features.md
- src/box/CMakeLists.txt
- src/box/iproto_constants.h
- src/box/iproto_features.h
- src/box/lua/init.c
- src/box/lua/iproto.c
- src/box/lua/iproto.h
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/box/misc.result
Export IPROTO constants and feature to Lua: for now, simply copy-paste all
constants from `src/box/iproto_{constants, features}.h` — it would be nice
to generate them in the future (#7103).
Closes #7894
> box: export IPROTO constants and features to Lua 

- changelogs/unreleased/gh_7846_before_replace_crash_on_replica_id_alter.md
- src/box/box.cc
- test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua
Currently, there is an assertion that checks if replica_id haven't been changed after it's registration. Let's replace this assertion with warning message about id being altered - new id will be used for affected replica.
Closes #7846
> replication: say warning if before_replace trigger changed replica_id

- changelogs/unreleased/gh-3159-recovery-triggers.md
- src/box/box.cc
- src/box/box.h
- src/box/lua/ctl.c
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- test/instances/default.lua
- test/luatest_helpers/server.lua
- test/replication-luatest/recovery_triggers_test.lua
Introduce triggers which are run during various stages of box.cfg{}.
See the docbot request below for more info.
Part-of #5272
Part-of #3159
Title: new triggers -- `box.ctl.on_recovery_state`
`box.ctl.on_recovery_state` is a handle to register triggers that will
be executed on different stages of recovery/initial configuration.
A trigger registered this way is run on each of the supported recovery
stages, and receives the stage name as a parameter. The possible stages
are:
- "snapshot_recovered": the node has recovered the snapshot file. This
is the fist state seen by triggers.
- "wal_recovered": the node has recovered all the .xlog files.
- "indexes_built": the node has built secondary indexes for memtx spaces.
Depending on a number of box.cfg options, …
> Triggers on recovery state

- changelogs/unreleased/gh-7755-memtx-rev-iters-repeatable-read-violation.md
- changelogs/unreleased/gh-7756-memtx-crash-on-series-of-txs.md
- src/box/memtx_bitset.cc
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- test/box-luatest/gh_7755_memtx_rev_iters_repeatable_read_violation_test.lua
- test/box-luatest/gh_7756_memtx_crash_on_series_of_txs_test.lua
We assumed that the successor tuple's story could not get garbage collected on clarify of result tuple in `tree_iterator_start`, since they coincide in case of regular iterators. But this is not the case for reverse iterators: the result tuple is of-by-one from the successor, which means the successor's story can get garbage collected along with the tuple itself getting deleted, leading to use-after-free of successor: remove garbage collection from `memtx_tx_tuple_clarify` and call it manually.
The crash in #7756 revealed that the `put` in transaction manager's story hash table was performed incorrectly: fix it and add an assertion that nothing was replaced.
Closes #7755
Closes #7756
> memtx: fix use-after-free of successor in `tree_iterator_start`

- changelogs/unreleased/gh-7828-rollback_rebind_read_tracker_wrong_idx_mask.md
- src/box/memtx_tx.c
- test/box-luatest/gh_7828_rollback_rebind_read_tracker_wrong_idx_mask_test.lua
During rollback read trackers are rebound to newer or older story, if
present. The problem with the current logic is that read trackers are
basically rebound in the first available index: all information about key
parts read from other indexes gets lost — rebind read trackers in all
indexes.
Closes #7828
NO_DOC=bugfix
> memtx: fix logic of read tracker rebinding during rollback

- changelogs/unreleased/gh-7523-sigsegv-on-m1-macs.md
- src/lib/core/backtrace.c
`backtrace_collect()` is suffering from the same issue as `coro_transfer()`, see commit https://github.com/tarantool/tarantool/commit/215630e6f6c429f96c7d210b200d9d241c374f9a ("coro: update sp before saving registers to a stack frame").
It stores `x19-x30` and `d8-d15` registers to the stack, but only after that it updates the stack pointer. If a `SIGALRM` signal is delivered during the execution of `backtrace_collect`, the signal handler will use the stack starting from current `sp`, thus corrupting the saved registers.
Fix this by updating the stack pointer at the beginning of `backtrace_collect`. The constraint of the input operand `bt` is changed from `"m"` to `"r"` to force `bt` always be passed to the inline assembly via the register. Passing on stack will not work after this fix. …
> backtrace: update `sp` before saving registers to a stack frame

- changelogs/unreleased/gh-7495-wrong-arch-reported-on-m1-macs.md
- cmake/arch.cmake
- test/app-luatest/gh_7495_tarantool_build_target_test.lua
This patch removes an old CMake kludge, which sets `CMAKE_SYSTEM_PROCESSOR` to `x86_64` on all 64-bit architectures, even on ARM (on Darwin).
Closes https://github.com/tarantool/tarantool/issues/7495
> cmake: fix wrong CPU architecture reported on M1/M2 Macs

- .gitmodules
- cmake/BuildLibUnwind.cmake
- debian/control
- rpm/tarantool.spec
Now we base on on some unreleased state of libunwind. This is by itself not a good practice. Yet the main motivation is that in the current version of libunwind fast path for backtrace detection on x86_64 does not work. I guess it is because of f67ef2867bc5 (" x86_64: Stop aliasing RSP and CFA"). See libunwind/libunwind#440. Fortunately this commit is not present it the latest release.
Using fast or slow path has a great impact on performance of debug build where collecting fiber gc allocation backtrace is turned on by default. It surely depends on frequency and pattern of allocation. Test sql/delete3 depends on backtrace performance most dramatically. On some installations collecting backtraces slowed down the test up to 10 times.
If fast path is available then collecting backtrace does …
> libunwind: use latest release v1.6.2 as a base

- src/box/tuple_dictionary.c
- src/lib/core/assoc.h
- src/lua/msgpack.c
- src/lua/msgpack.h
- test/unit/CMakeLists.txt
- test/unit/lua_msgpack.c
> msgpack: add translation of first-level `MP_MAP` keys during encoding

- changelogs/unreleased/gh-8017-on-auth-no-such-user.md
- changelogs/unreleased/ghs-21-user-enumeration.md
- src/box/authentication.cc
- src/box/authentication.h
- src/box/lua/session.c
- test/box-luatest/gh_8017_on_auth_no_such_user_test.lua
- test/box-luatest/ghs_16_user_enumeration_test.lua
This PR fixes two authentication-related issues:
- `box.session.on_auth` not invoked if the user doesn't exist.
- Different error is raised for existing and non-existing users if the authentication request is malformed.
Closes #8017
Closes https://github.com/tarantool/security/issues/21
> Authentication fixes

- CMakeLists.txt
Since we are going to introduce zlib compression in enterprise version, we need to find zlib package there, so let's search for zlib package only if it has not been found before.
> zlib CE part

- src/box/applier.cc
- src/box/box.cc
- src/box/memtx_engine.cc
- src/box/raft.c
- src/box/relay.cc
- src/box/request.c
- src/box/txn.c
- src/box/vy_log.c
- src/box/vy_stmt.c
- src/box/xlog.c
- src/box/xrow.c
- src/box/xrow.h
- src/box/xrow_io.cc
- test/unit/xrow.cc
An encoder function may only fail if it fails to allocate memory from `fiber->gc`. The amount of memory it allocates is fairly small. It's used as an extra stack to return the encoded data. This should never fail, because there's no hard limit for runtime memory (and we're not planning to ever add one). Let's make all encoder functions return `void` and drop the untested checks for OOM.
To avoid confusion, we make `xrow_header_encode`, `xrow_encode_dml`, and `xrow_to_iovec` return the number of io vectors in a new out argument, because a return value of type `int` is usually used to indicate an error.
See also #3534
> xrow: use `xregion_alloc` in encoders

- CMakeLists.txt
- cmake/compiler.cmake
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
- src/trivia/config.h.cmake
- test/unit/fiber.cc
**cmake: add -fasynchronous-unwind-tables compiler flag**
This option enables emission of the DWARF CFI (Call Frame Information) directives to the assembler.
It is enabled by default on most compilers, but on GCC 7 for AArch64 and older it wasn't [^1], so turn it on explicitly.
When enabled, the compiler emits `.cfi_*` directives that are required for the stack unwinding, and defines `__GCC_HAVE_DWARF2_CFI_ASM`.
**cmake: enable leak backtraces on AArch64**
This feature was disabled due to a crash in libunwind. After commit https://github.com/tarantool/tarantool/commit/5b08d71ab47474f4278cdddf481bb8e50df074a5 ("libunwind: use latest release v1.6.2 as a base") the crash is gone.
Closes https://github.com/tarantool/tarantool/issues/7960
[^1]: …
> cmake: enable leak backtraces on AArch64

- changelogs/unreleased/gh-3211-per-module-log_level.md
- extra/exports
- src/box/lua/load_cfg.lua
- src/lib/core/say.c
- src/lib/core/say.h
- src/lua/init.lua
- src/lua/log.lua
- test/box-luatest/gh_3211_module/testmod.lua
- test/box-luatest/gh_3211_per_module_log_level_test.lua
- test/box-luatest/gh_7860_syslog_json_test.lua
- test/box-tap/gh-4785-syslog.test.lua
- test/unit/say.c
**log: add log.new() function that creates a new logger**
It allows to create a new instance of a log module, with a custom name, e.g.:
```lua
local my_log = require('log').new('my_module')
```
The name is added to the log message after fiber name:
```
YYYY-MM-DD hh:mm:ss.ms [PID]: CORD/FID/FIBERNAME/MODULENAME LEVEL> MSG
```
**log: add per-module log level setting via log.cfg() or box.cfg()**
Now it is possible to specify the log level for each module separately, e.g.:
```lua
box.cfg {
log_level = 5,
log_modules = {
['foo.bar'] = 1,
expirationd = 'debug'
}
}
```
The name of a module is determined automatically, or it is possible to create a logger with a custom name by using `log.new()`.
**log: implement automatic module name deduction**
The name of a module is determined automatically …
> log: introduce per-module `log_level`

- test/app-tap/tarantoolctl.test.lua
The `recursive_rmdir` can start execution while tarantool instance started by the tarantoolctl is in the process of shutdown. As a result the instance pid file can be available at the name collection, but by the time of its removal the instance deletes it by itself.
NO_DOC=test
> test: tarantoolctl.test flakiness fixup

- changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md
- src/lua/compat.c
- src/lua/compat.lua
- src/lua/serializer.c
- src/lua/serializer.h
- test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua
- third_party/lua-cjson/lua_cjson.c
For unknown reason in upstream lua_cjson '/' was escaped
while according to the standard [rfc4627] it is unnecessary and is
questionably compatible with other implementations.
It was decided that the change will be introduced using
tarantool.compat (https://github.com/tarantool/tarantool/issues/7000). The patch adds json-escape-forward-slash
option to compat and its logic in lua_cjson and msgpuck.
Requires changes in tarantool.compat [1].
[1]: https://github.com/tarantool/tarantool/pull/7060
Fixes https://github.com/tarantool/tarantool/issues/6200
See also https://github.com/tarantool/tarantool/issues/7000
NO_DOC=[docs on tarantool.wiki](https://github.com/tarantool/tarantool/wiki/compat%3Ajson_escape_forward_slash)
> lua_cjson: fix encode() escaping slash

- changelogs/unreleased/gh-3012-yaml-prettier-multiline-output
- src/lua/compat.c
- src/lua/compat.lua
- test/app-luatest/gh_3012_yaml_prettier_multiline_output_test.lua
- third_party/lua-yaml/lyaml.cc
- third_party/lua-yaml/lyaml.h
Added tarantool.compat option that allowes yaml.encode() to encodes all
strings containing a newline in a more convenient block scalar style.
This is a breaking change, programs that rely on precise lyaml encoding
may fail if the new behavior is selected.
Closes https://github.com/tarantool/tarantool/issues/3012
Requires https://github.com/tarantool/tarantool/pull/7060
Title: YAML formatter improvement
Now yaml.encode() can encode strings with a newline in block scalar style,
see https://yaml.org/spec/1.2-old/spec.html#style/block/literal and
https://github.com/tarantool/tarantool/wiki/compat%3Ayaml_pretty_multiline
old:
```
tarantool> compat.yaml_pretty_multiline = 'old'
---
...
tarantool> return "Title: xxx\n- Item 1\n- Item 2\n"
---
- 'Title: xxx
- Item 1
- Item …
```
> lua-yaml: improve multiline string output

- rpm/tarantool.spec
Support for OpenSUSE 15.1/15.2 has been recently dropped. There is no sense to keep the dead code. So removing it.
Follows up #8021
> cd: eliminate OpenSUSE related code from RPM spec

- test/app-tap/tarantoolctl.test.lua
The `recursive_rmdir` can start execution while tarantool instance started by the tarantoolctl is in the process of shutdown. As a result the instance pid file can be available at the name collection, but by the time of its removal the instance deletes it by itself.
NO_DOC=test
> [2.10] test: tarantoolctl.test flakiness fixup

- test/app-tap/tarantoolctl.test.lua
The `recursive_rmdir` can start execution while tarantool instance started by the tarantoolctl is in the process of shutdown. As a result the instance pid file can be available at the name collection, but by the time of its removal the instance deletes it by itself.
NO_DOC=test
> [1.10] test: tarantoolctl.test flakiness fixup

- .github/workflows/freebsd-12.yml
- .github/workflows/freebsd-13.yml
ChristopherHX/github-act-runner@0.4.1, which we use on FreeBSD,
is incompatible with newest actions/checkout@v3.2.0, aliased to @v3.
Until this is resolved, FreeBSD workflows will use fixed version
actions/checkout@v3.1.0.
actions/checkout@v3.2.0 fails with an unclear error:
> ⭐  Run actions/checkout@v3
>   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
> Error: Unable to resolve v3: unsupported object type
> Error: Unable to resolve v3: unsupported object type
> Error:   ❌  Failure - actions/checkout@v3
> Error: unsupported object type
> ci: use actions/checkout@v3.1.0 with FreeBSD

- .github/workflows/freebsd-12.yml
- .github/workflows/freebsd-13.yml
ChristopherHX/github-act-runner@0.4.1, which we use on FreeBSD, is incompatible with newest actions/checkout@v3.2.0, aliased to @v3. Until this is resolved, FreeBSD workflows will use fixed version actions/checkout@v3.1.0.
actions/checkout@v3.2.0 fails with an unclear error:
> ⭐  Run actions/checkout@v3
>   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
> Error: Unable to resolve v3: unsupported object type
> Error: Unable to resolve v3: unsupported object type
> Error:   ❌  Failure - actions/checkout@v3
> Error: unsupported object type
(cherry picked from commit a79d32b107d7958a772c11fc739c36ec0c1e571e)
> [2.10] ci: use actions/checkout@v3.1.0 with FreeBSD

- changelogs/unreleased/fix-libunwind-h-search.md
- debian/control
- rpm/tarantool.spec
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/symbols.c
- test/app-luatest/tnt_internal_symbol_test.lua
- test/box-tap/CMakeLists.txt
- test/box-tap/check_merge_source.c
- test/fuzz/CMakeLists.txt
- test/unit/CMakeLists.txt
- test/unit/uri.c
Case: a build host has no libunwind installed into the system. Dispite that tarantool has libunwind bundled as a git submodule (see PR #6877), the build fails in the case:
```c
In file included from <...>/src/lib/core/fiber.h:47,
from <..some test/**/*.{c,cc} file..>:
<...>/src/lib/core/backtrace.h:14:10: fatal error: libunwind.h: No such file or directory
14 | #include "libunwind.h"
|          ^~~~~~~~~~~~~
```
The problem appears when `ENABLE_BACKTRACE` and `ENABLE_BUNDLED_LIBUNWIND` CMake options are enabled. They're enabled by default for most targets.
The compilation fails for testing files, which include `fiber.h`. The `fiber.h` header includes `backtrace.h`, which includes `libunwind.h`. The `libunwind.h` header couldn't be found if appropriate include directory is not passed to a …
> build: fix libunwind.h search in testing files

- src/box/applier.cc
- src/box/box.cc
- src/box/box.h
- src/box/lua/cfg.cc
- src/box/lua/load_cfg.lua
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- src/box/lua/schema.lua
- test/app-tap/init_script.result
- test/box-luatest/gh_7988_auth_type_test.lua
- test/box/admin.result
- test/box/cfg.result
This commit adds configuration options that allow to use different authentication mechanisms:
- For generating user authentication data in `box.schema.user.passwd` - `box.cfg.auth_type`.
- For configuring replication - new uri param `auth_type`.
- For connecting via net.box - new connection option `auth_type`.
The only authentication method supported by Community Edition (CE) is 'chap-sha1' so we don't document or announce this feature in CE. More methods and tests will be added to Enterprise Edition (EE).
Closes #7988
> Allow to specify different auth mechanisms

- src/box/CMakeLists.txt
- src/box/authentication.c
- src/box/box.cc
- src/box/security.h
- src/trivia/config.h.cmake
This PR adds a stub function that will add extra authentication methods in Tarantool Enterprise Edition. Also, it fixes a bug in `authenticate()` that can result in a crash if there's more than one authentication method available.
Needed for https://github.com/tarantool/tarantool-ee/issues/295
Follow-up #7986
> box: add stub function to register extra security methods

- extra/exports
- src/lib/core/say.c
- src/lua/log.lua
Before commit 243234483ae8 ("log: add log.new() function that creates a new logger"), `log_write_flightrec()` was called from `log_vsay()` regardless of the log level. After, the log level is checked in Lua, so `log_vsay()` may not be called.
This patch restores the original behaviour by moving `log_write_flightrec()` calls to `say_default()` and `say()`.
Part of https://github.com/tarantool/tarantool-ee/issues/320
> log: call log_write_flightrec regardless of the log level

- src/lib/core/backtrace.c
- src/lib/core/backtrace.h
- src/lib/core/proc_name_cache.cc
- src/lib/core/proc_name_cache.h
- src/lua/backtrace.c
- test/fuzz/CMakeLists.txt
- test/unit/CMakeLists.txt
The only reason why `libunwind.h` is included into `backtrace.h` (and then transitively into `fiber.h`) is use of `unw_word_t` type. Let's replace it with `uintptr_t` and use `unw_word_t` only for interacting with the unwind library.
This commit partially reverts commit 6d088b56ac34, because we don't need to include libunwind.h into tests anymore.
Fixes #8025
> Eliminate dependency of core lib headers on `libunwind.h`

- src/box/applier.cc
- src/box/auth_chap_sha1.c
- src/box/authentication.c
- src/box/authentication.h
- src/box/lua/net_box.c
- src/lib/core/iostream.h
If an IO stream is encrypted, it should set flag `IOSTREAM_IS_ENCRYPTED`. If an authentication method requires the channel to be encrypted, it should set flag `AUTH_METHOD_REQUIRES_ENCRYPTION`. An attempt to use an authentication method that requires encryption over an unencrypted IO stream will raise an error `ER_UNSUPPORTED("Authentication method '%s' does not support unencrypted connection")`. This check is performed by both net.box and applier.
Needed for https://github.com/tarantool/tarantool-ee/issues/322
> box: let authentication method require encryption

- changelogs/unreleased/gh-6647-yield-gc-hook.md
- src/lua/utils.c
- test/box-luatest/gh_6647_yield_gc_hook_test.lua
Before the patch, fiber->storage.lua.stack is used for `panic` calls. However, some fibers don't have any Lua state saved in their storage (for example, space
triggers).
After the patch, the Lua state pointed by `cur_L` is used to make those calls, as it is always present.
As proposed by @Totktonada in https://github.com/tarantool/tarantool/pull/7976, I've checked a few cases, that could lead to the same behavior.
- fiber_new() from C -- Can't occur here, either no lua_State at all, or it is invoked from a lua fiber.
- IPROTO_CALL for a C function -- Again, no lua_State here at all.
- IPROTO_EXECUTE for a query that calls a Lua function -- Handled well for 2.x.x, not present for 1.10
- IPROTO_INSERT for a space with a trigger -- fails, added corresponding test
> lua: use cur_L in cord_on_yield

- changelogs/unreleased/gh-7989-iproto-id-auth-type.md
- src/box/applier.cc
- src/box/box.cc
- src/box/box.h
- src/box/iproto.cc
- src/box/iproto_constants.c
- src/box/iproto_constants.h
- src/box/lua/load_cfg.lua
- src/box/lua/net_box.c
- src/box/xrow.c
- src/box/xrow.h
- test/box-py/iproto.result
- test/box-py/iproto.test.py
- test/replication-luatest/iproto_id_error_test.lua
This PR adds a new key to the `IPROTO_ID` response: `IPROTO_AUTH_TYPE`. Its code is 0x5b, its type is `MP_STR`. It contains the name of the default authentication method used by the server (value of `box.cfg.auth_type`). A client can use this information to properly select the default authentication method in case it isn't specified explicitly with the user credentials. In the scope of this PR, we also patch net.box and applier code to use this feature.
Notes:
- Before this PR, applier didn't send `IPROTO_ID` request to the master at all, now it does. This may be useful for other things, too, e.g. retrieving the master instance name.
- Tarantool CE supports the only authentication method - 'chap-sha1'. So the feature can't be tested properly in CE. The test will be added to the EE …
> Include default auth method into `IPROTO_ID` response

- test/app-tap/datetime.test.lua
- test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
- test/box-luatest/pagination_netbox_test.lua
- test/engine-luatest/pagination_test.lua
JIT has been disabled for these 3 tests on arm64 to avoid weird fails, but they are still flaky in CI. Perhaps the JIT traces from other tests affect them. Let's try to do `jit.flush()` together with `jit.off()`.
Also disable JIT for pagination_netbox_test.lua, which suffers from the same problem as pagination_test.lua.
Part of https://github.com/tarantool/tarantool-qa/issues/162
Part of #7739
Part of #8011
> test: do `jit.flush()` after `jit.off()` on arm64

- .github/workflows/submodule_update.yml
Workflow submodule_update now brings latest commits in stable branches
further to tarantool/sdk, where integration tests can run with other
enterprise products and modules.
In tarantool/tarantool-ee a pull request is still opened, so the
maintainers can merge it at any time.
In tarantool/sdk the test branches are named in the following pattern:
`TarantoolBot/test-ce-master`
`TarantoolBot/test-ce-2.10`
and so on. This pattern can be easily distinguished by workflows,
which run integration tests and alert developers on failures.
It is also consistent with branches with the same purpose of integration
testing, that are created by the sdk_test workflow:
`TarantoolBot/test-ce-{feature_branch_name}`
Resolves tarantool/sdk#355
* Test workflows: …
> ci: test stable branches with SDK

- changelogs/unreleased/gh-7886-dont-close-xlog-fd-atfork.md
- src/box/box.cc
- src/box/box.h
- src/box/wal.c
- src/box/wal.h
- src/box/xlog.c
- src/box/xlog.h
- src/main.cc
**box: do not close xlog file descriptors in the atfork handler**
Use `O_CLOEXEC` flag instead.
If Tarantool is forked before executing `box.cfg{}`, e.g. using `io.popen()`, the child process could start with `stdin` linked to `/dev/urandom`. This happens because `wal_writer_singleton` and `vy_log_writer` are not yet initialized, i.e. `fd` fields are 0, then atfork child handler `wal_atfork()` is called. It checks that xlog is opened (the check succeeded as 0 != -1) and closes its fd 0, in fact closing `stdin` (twice). Next, Tarantool opens the file `/dev/urandom` during initialization, and it receives the lowest unused file descriptor, which is 0. Then `luaL_loadfile()` loads `stdin` as a Lua chunk, in effect reading random numbers.
This happens on glibc 2.28 and older, as newer versions …
> Don't replace `stdin` with `/dev/urandom` after fork

- changelogs/unreleased/gh_7339_fk_drop_in_one_txn.md
- src/box/alter.cc
- src/box/space.c
- src/box/space.h
- src/box/tuple_constraint.c
- src/box/tuple_constraint.h
- src/box/tuple_constraint_fkey.c
- src/box/tuple_constraint_func.c
- test/engine-luatest/gh_7339_drop_fk_in_same_txn_test.lua
Currently, core constraints are dropped on commit. That is why it is impossible to drop constraint and drop objects it references to at the same transaction. Let's drop constraints in two steps - detach them when DDL occurs, then reattach on rollback or delete on commit.
Closes #7339
> core: drop constraints in two phases

- test/app-tap/gh-5983-jit-library-smoke-tests.test.lua
A jiggle in tarantool's initialization code can lead to trace numbers
above 9. We can either:
* accept trace numbers above 9 in the test
* or drop traces from the initialization code in the test and assume
that the new trace will have number 1.
Igor Munkin suggested to stick with the second approach to avoid
dependency on the initialization code.
> test: stabilize jit.dump() smoke test

- changelogs/unreleased/gh-7746-fiber-channel-graceful-close.md
- src/lib/core/fiber_channel.c
- src/lib/core/fiber_channel.h
- src/lua/compat.c
- src/lua/compat.lua
- test/app-luatest/gh_7746_fiber_channel_close_test.lua
- test/unit/fiber_channel.cc
- test/unit/fiber_channel.result
Before the change there was an unexpected behavior when using
channel:close(), as it closed the channel entirely and discarded all
unread events.
This commit introduces graceful channel close option in tarantool.compat
(https://github.com/tarantool/tarantool/issues/7000) that allowes to select new or old behavior.
With the new behavior `close()` marks channel as closed for writing.
Only when all events are extracted, the channel is closed entirely. If
there are no events in the channel, it is closed as usual.
Document that describes new API can be found on notion:
https://www.notion.so/fiber-channel-graceful-close-53b2788ed1f144598c4c0e1229c2eb69
Requires https://github.com/tarantool/tarantool/pull/7060
Closes https://github.com/tarantool/tarantool/issues/7746
See also …
> fiber: add channel graceful close option to compat

- changelogs/unreleased/gh-7931-httpc-params-escaping.md
- src/lua/httpc.lua
- src/lua/uri.lua
- test/app-luatest/http_client_test.lua
- test/app-luatest/uri_unit_test.lua
**Requires commits in #3682 and thus blocked by #3682**
Commits to be reviewed:
```
commit 1950807fdf18fadac99a592eaf9ee238d4bf745a (HEAD -> ligurio/gh-7931-encode-query-params)
Author: Sergey Bronnikov <sergeyb@tarantool.org>
Date:   Mon Dec 12 15:50:42 2022 +0300
http: escape encoded params
Title: Document a percent-encoding of params passed to http client
The HTTP client has `params` option, where a user may provide a table of
query parameters (added in #6832). Those parameters are encoded into a
`?foo=bar&twedledoo=tweedledee` string verbatim. If a name or a value of
a query parameter contains `&`, `=` (or any another symbol with specific
meaning in the URI query component), the query may be interpreted
incorrectly by a server. Now key and values passed in a …
```
> http: escape encoded params

- src/tarantool-gdb.py
Supported extensions:
- decimal
- uuid
- datetime
- error
- compression (only shows compression type and raw/compressed data size)
- interval
This functionality is similar to 'mp_str' function, but 'mp_str' can be
invoked from gdb only when a process is alive, so to be able to print
MsgPack during post-mortem analysis of core dump, 'mp_str' and all
subsequent functions that decode and convert MsgPack into human-readable
string were adapted to Python and put into the extension.
In order to simplify implementation and maintenance of the gdb-extension
implementation of the most of functions is kept as close to possible to
their 'C'-counterparts (original 'C'-name can be found as a comment at
the end of 'def' string)
Closes #7729 
NO_TEST=gdb …
> gdb: add command 'tt-mp' to print MsgPack (with tt extensions)

- .github/workflows/integration.yml
Add workflow for integration testing of ddl
and crud modules.
Part of #6619, #6620
Integration workflow: https://github.com/tarantool/tarantool/actions/runs/3799692185/jobs/6462450346
>  [2.10] ci: add integration testing for ddl and crud 

- .github/workflows/coverage.yml
The coverage workflow is a part of the default testing, so there is no sense to run this workflow when the 'full-ci' label is set. Moreover, it cancelled the run of the default testing and started the run of the full testing due to workflow `concurrency`.
By default, a workflow only runs when a `pull_request` event's activity type is `opened`, `synchronize`, or `reopened`. That's why there is no sense in the following construction:
```yml
pull_request:
types: [ opened, reopened, synchronize ]
```
So just removed the line related to event's activity type.
> ci: fix pull_request trigger for coverage workflow

- changelogs/unreleased/gh-8043-net-box-error.md
- src/box/xrow.c
- test/box-luatest/gh_8043_net_box_error_test.lua
> xrow: fix crash in xrow_decode_error if msg contains printf specifiers

- .github/workflows/osx_11.yml
- .github/workflows/osx_11_aarch64.yml
- .github/workflows/osx_11_aarch64_debug.yml
- .github/workflows/osx_11_lto.yml
- .github/workflows/osx_12.yml
- .github/workflows/osx_12_static_cmake.yml
Change runner label 'macos-11' to 'macos-11-self-hosted' and 'macos-12' to 'macos-12-self-hosted' to distinguish between self-hosted and GitHub-hosted runners. We want to use only self-hosted macOS runners because of test-run problems with python3.11 on GitHub-hosted macOS runners.
NO_DOC=ci
NO_TEST=ci
> ci: change macos runners labels

- changelogs/unreleased/clang-15.md
- cmake/thread.cmake
- extra/lemon.c
- src/box/sql/vdbeaux.c
Fixed pthread-related CMake checks. The checks code is built with `-pedantic-errors` and it leads to errors of the following kind on clang 15:
```c
<...>/CMakeFiles/CMakeScratch/TryCompile-78KaOK/src.c:4:17: error: a
function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
int main() { pthread_setname_np(pthread_self(), ""); }
^
void
```
Fixed a warning in the SQL code (it's an error in Debug build):
```c
<...>/src/box/sql/vdbeaux.c:170:13: error: variable 'n' set but not used
[-Werror,-Wunused-but-set-variable]
static int n = 0;
```
Fixed several warnings from lemon.c of the following kind:
```c
<...>/extra/lemon.c:173:6: warning: a function declaration without a
prototype is deprecated in all versions of C and is treated as a …
```
> build: fix build fail on clang 15

- .github/workflows/luajit-integration.yml
Before the patch the LuaJIT integration workflow was dispatched to the runner with the name given via <inputs.host> parameter. Unfortunately, as a result of runners renaming we can't continue to dispatch the workflow this way.
As a result of the patch there are two new workflow parameters: <inputs.arch> to pass the host architecture name (i.e. x86_64 or ARM64) and <inputs.os> to pass the OS family name (either Linux or macOS). Considering two values we can choose the proper runner in LuaJIT integration workflow. Besides, this change bring LuaJIT CI closer to matrix usage for its integration workflow.
All three workflow parameters are not obligatory for now to avoid tarantool/luajit CI break on both long-term and working branches. When all branches are rebased on the new approach, …
> ci: change runner dispatch for LuaJIT testing

- third_party/coro/coro.c
> coro: fix dereferencing of `void *` pointer warning

- changelogs/unreleased/gh-8027-txn-handle-abort-in-trigger.md
- src/box/lua/space.cc
- src/lua/trigger.c
- src/lua/trigger.h
- test/box-luatest/gh_8027_txn_handle_abort_in_trigger_test.lua
`lbox_push_event_f` and `lbox_push_event_f` callback functions used for passing the statement between txn and space on/before replace Lua triggers don't assume that the transaction may be aborted by yield after the current statement began (this may happen if a trigger callback yields). In this case, all statements in txn would be rolled back and `txn_current_stmt` would return `NULL`, leading to a crash.
Let's fix this by checking if the transaction is still active and raising an error immediately if it isn't, thus skipping Lua triggers.
Notes:
- We merged `lbox_pop_txn_stmt_and_check_format` into `lbox_pop_txn_stmt`, because the latter is only called by the former.
- Since `lbox_push_event_f` callback may now fail, we have to update `lbox_trigger_run` to handle it.
Closes #8027
> lua: gracefully fail space on/before replace trigger if txn was aborted

- src/lib/core/backtrace.c
Every libunwind error during backtrace collection is reported with `say_error`. Since commit 19abfd2a3920 ("misc: get rid of fiber_gc") backtraces are collected on each fiber gc allocation, of which there are plenty.
For some reason (https://github.com/tarantool/tarantool/issues/7980) each unw_step fails on mac, and an error is spammed to instance logs, even though the backtrace is actually collected.
Silence the errors, since there is no much use for them anyway. And silence all of them just to be consistent.
This doesn't close https://github.com/tarantool/tarantool/issues/7980, because that issue still needs a proper fix. Although its severity is ameliorated now.
In-scope-of https://github.com/tarantool/tarantool/issues/7980
NO_DOC=bugfix
NO_TEST=nothing to test
> core: silence libunwind errors

- CMakeLists.txt
- cmake/BuildLibUnwind.cmake
- cmake/ext_project_autotools.cmake
- cmake/utils.cmake
Currently we use ExternalProject_Add to build libunwind subproject. The usecases it supports are not quite aligned with our. Configuration and build steps are rerun in case download step sees updated sources. But we use git submodules to fetch third-party projects and thus subproject is not rebuild when it's files are changed on disk. Either because of we doing some sort of experiments locally or because the new sources are brought by git pull.
Actually libunwind has a CMakeList.txt so that we could try to build it just as project subdirectory. But it requires quite a fresh CMake version, currently supports only build on Visual Studio and probably is not up to date given it's package version variables. Keeping CMakeLists.txt in sync with main autotools build is additional maintenace …
> libunwind: improve incremental build/rebuild

- cmake/BuildLibUnwind.cmake
- cmake/ext_project_autotools.cmake
The EE CMakeConfig.txt adds CE as a sub-directory. For this to work, we should use project dir instead of cmake dir in CE cmake files, see commit d80973259779 ("cmake: align folders dependencies").
Fixes commit 14f93aee86b8 ("libunwind: improve incremental build/rebuild").
Follow-up #8019
> cmake: use project dir instead of cmake dir when building libunwind

- src/lua/init.lua
- test/app-luatest/gh_8158_start_from_root_dir_test.lua
- test/app-luatest/per_module_log_unit_test.lua
The function `remove_root_directory`, which is used for obtaining module names for per-module logging, throws an error when current working directory is `/`. Rewrite it to fix the bug and rename it to `strip_cwd_from_path` to make the name more clear.
Closes #8158
> log: fix inability to start from the root directory

- .github/workflows/luajit-integration.yml
- .test.mk
Small changes to remove the old code from LuaJIT integration CI:
* Removed the obsolete `inputs.host` parameter
* Enabled `CMAKE_EXTRA_PARAMS` for .test.mk (since #8026 has been fixed)
---
P.S. LuaJIT CI is [green](https://github.com/tarantool/luajit/commit/52ff4c3) as a result of this patch.
> Maintenance of LuaJIT integration CI

- test/app-luatest/gh_3012_yaml_prettier_multiline_output_test.lua
- test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua
- test/app-luatest/gh_7746_fiber_channel_close_test.lua
Before the change all tarantool.compat options' tests were running on the same instance, and because luatest uses multiple threads, they could interfere with compat configuration at the same time as other test checks default behavior. This could cause such tests to flack.
Now all options' tests are being run in a separate instance via server:exec().
Closes #8033
> test: update compat options tests with server:exec

- changelogs/unreleased/bump-libcurl-to-7.87.0.md
- cmake/BuildLibCURL.cmake
- debian/control
- debian/prebuild.sh
Changelog: https://curl.se/changes.html#7_87_0
New release contains fixes for 7 security problems [1]:
https://curl.se/docs/CVE-2022-35252.html
https://curl.se/docs/CVE-2022-32221.html
https://curl.se/docs/CVE-2022-35260.html
https://curl.se/docs/CVE-2022-42915.html
https://curl.se/docs/CVE-2022-42916.html
https://curl.se/docs/CVE-2022-43551.html
https://curl.se/docs/CVE-2022-43552.html
Patch adds a new option ENABLE_WEBSOCKETS defined in curl build
infrastructure with it's default value used in 7.87.0.
1. https://curl.se/docs/releases.html
Closes #8150 
**NOTE:** CodeQL alerts found in libcurl have been dismissed, I found them not important.
See details in https://github.com/tarantool/tarantool/pull/8151/checks?check_run_id=10613562871
**NOTE:** Depends on PR with fixes in smtp module …
> third_party: update libcurl from 7.84.0 to 7.87.0

- src/box/applier.cc
- src/box/errcode.h
- test/box/error.result
- test/replication-luatest/gh_8185_dont_connect_to_nil_uuid_test.lua
The title is pretty self-explanatory. That's all this commit does. Now a couple of words on why this is needed.
Commit 2a0c4f2bb137 ("replication: make replica subscribe to master's ballot") changed replica connect behaviour: instead of holding a single connection to the master, replica may have two: master's ballot retrieval is now performed in a separate connection owned by a separate fiber called ballot_watcher.
First connection to master is initialized as always and then applier fiber creates the ballot_watcher, which connects to the same address on its own.
This lead to some unexpected consequences: random cartridge integration tests started failing with the following error:
tarantool/tarantool/cartridge/test-helpers/cluster.lua:209: "localhost:13303": Replication setup failed, …
> replication: refuse to connect to master with nil UUID

- .github/workflows/reusable_build.yml
The approach
- name: Set output 
run: echo "::set-output name={name}::{value}"
is deprecated [1].
Switching to the new approach:
- name: Set output 
run: echo "{name}={value}" >> $GITHUB_OUTPUT
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
> ci: use new approach for returning step output

- src/box/box.cc
- src/box/box.h
- src/box/flightrec.h
- src/box/lua/cfg.cc
- src/main.cc
We define `flight_recorder_cfg` struct, `box_get_flightrec_cfg` function, and `box.internal.cfg_configure_flightrec` Lua function in the CE repository although they are actually needed only in the EE repository. Let's drop them all from the CE repository and instead define stub functions `box_check_flightrec` and `box_set_flightrec` that would check/apply `box.cfg` flight recorder parameters.
While we are at it, add missing comments to flightrec function stubs.
EE part: https://github.com/tarantool/tarantool-ee/pull/351
> box: move flightrec configuration out of CE repository

- changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md
- src/lib/raft/raft.c
- test/unit/raft.c
There is a false assertion in raft_stop_candidate(): it assumes that the node must always have a running timer whenever it sees the leader. This is not true when the node is busy writing the new term on disk.
Cover the mentioned case in the assertion.
Closes #8169
NO_DOC=bugfix
Co-authored-by: Sergey Ostanevich <sergos@tarantool.org>
> raft: fix an assertion failure in raft_stop_candidate

- changelogs/unreleased/gh-8168-double-term-bump-on-promote.md
- src/lib/raft/raft.c
- test/replication-luatest/gh_8168_extra_term_bump_test.lua
- test/unit/raft.c
A node configured in 'manual' mode and promoted by `box.ctl.promote()` stays in is_candidate state for the whole term, even though it is not is_cfg_candidate.
If such a node is the first one to notice leader death or to hit the election timeout, it bumps the term excessively, then immediately becomes a mere follower, because its is_candidate is reset with is_cfg_candidate.
This extra term bump (one term after the node was actually promoted) is unnecessary and might lead to strange errors:
tarantool> box.ctl.promote()
---
- error: 'The term is outdated: old - 3, new - 4' ...
Fix this by checking if a node is configured as a candidate before trying to start new elections.
Closes #8168
NO_DOC=bugfix
> raft: fix 'manual' nodes bumping the term excessively

- src/box/applier.cc
Currently all ballot_watcher fibers for different appliers have identical names: "applier_ballot_watcher". It's hard to distinguish them in logs and to know which ballot_watcher belongs to which applier, and that complicates debugging quite a bit.
Let's fix this and name the fibers properly. With master's uri at the end.
NO_DOC=no behaviour changed
NO_CHANGELOG=no behaviour changed
NO_TEST=doesn't need one
> applier: name ballot_watcher fiber properly

- src/box/box.cc
- src/box/box.h
- src/box/flightrec.h
- src/box/lua/cfg.cc
- src/box/lua/feedback_daemon.lua
- src/lib/core/crash.c
- src/lib/core/crash.h
- src/main.cc
- src/main.h
- test/unit/box_test_utils.c
Flight recorder uses mmapped file for performance reasons. Unfortunately if for some reason mapping is not possible we got SIGBUS on accessing mmapped memory.
We already handle this issue on flight recorder start in [1]. But if we got SIGBUS in the meanwhile we currently got a crash. Let's just panic.
[1] https://github.com/tarantool/tarantool-ee/commit/e68b84768f3ae76aa9f03d36dd6f0587b884e1bb
EE Part: https://github.com/tarantool/tarantool-ee/pull/344
> box: handle SIGBUS in flightrec (CE Part)

- changelogs/unreleased/gh-7166-deprecate-fiber_set_cancellable.md
https://www.notion.so/tarantool/fiber-make-fiber_set_cancellable-a-no-op-28101defb64b4df39baf7afbfd61e540
> changelog: don't mark `fiber_set_cancellable` deprecation as breaking

- changelogs/unreleased/gh-3211-per-module-log_level.md
https://www.notion.so/tarantool/log-implement-automatic-module-name-deduction-92198a0f86d342dbbec0da32f27863fe
> changelog: don't mark additional module name in the log as breaking

- changelogs/unreleased/gh-5869-remove-fiber-top-cpu_misses.md
- src/lua/fiber.c
- test/app/fiber.result
- test/app/fiber.test.lua
https://www.notion.so/tarantool/fiber-get-rid-of-cpu_misses-in-fiber-top-f5c3af62cb7d4fb1bb09dbf575c2109f
> fiber: return always-zero `cpu_misses` entry to `fiber.top()`

- test/replication-luatest/election_pre_vote_test.lua
test_promote_no_quorum testcase in election_pre_vote test started flaky hanging after commit 5765fdc4e4ec ("raft: fix 'manual' nodes bumping the term excessively").
Disable it until the issue (#8217) is resolved.
In-scope-of #8217
NO_DOC=tests
NO_CHANGELOG=tests
> test: partially disable election_pre_vote test

- changelogs/unreleased/gh-5665-get-rid-of-fiber_gc.md
As it is unlikely to break anyone.
Follow-up #5665
> changelog: don't report dropping fiber_gc as breaking change

- changelogs/unreleased/gh-5522-vy-tx-isolation-level.md
[Link to the discussion](https://www.notion.so/tarantool/vinyl-implement-transaction-isolation-levels-ccb542efa0b24b5b8eb99d7365ae086d)
The transaction isolation level used by Tarantool by default is 'best-effort' so adding support of transaction isolation levels to Vinyl effectively switched the isolation level used by Vinyl transactions from 'read-committed' to 'best-effort', which potentially may cause more conflicts. Let's mention it in the changelog and mark this change as breaking.
Follow-up commit 588170a77c9a ("vinyl: implement transaction isolation levels")
Follow-up #5522
> changelog: mark vinyl transaction isolation level support as breaking

- changelogs/unreleased/gh-7930-memtx-mvcc-loss-of-committed-tuple-after-prepared-tx-rollback.md
- changelogs/unreleased/gh-8104-memtx-mvcc-assertion-failure-during-stmt-preparation.md
- src/box/memtx_tx.c
- src/box/txn.c
- test/box-luatest/gh_7930_memtx_mvcc_loss_of_committed_tuple_after_prepared_tx_rollback_test.lua
- test/box-luatest/gh_8104_memtx_mvcc_assertion_failure_during_stmt_preparation_test.lua
Backport of [gh-8104-prepared-del-stmt ](https://github.com/tarantool/tarantool/pull/8167) to 2.10.
> Gh 8104 prepared del stmt 2 10

- extra/exports
- src/box/box.cc
- src/box/lua/schema.lua
- static-build/test/exports.test.lua
Recently, ffi select was broken on M1 - it turned out that ffi on M1 poorly supports a big quantity of arguments, which was used for pagination. Fortunately, there is a workaround - we can pass only 64-bit integer arguments beyond the 8th argument. Let's do it.
Closes #7946
> box: make ffi select work on M1

- changelogs/unreleased/gh-8108-adjust-xlog_read_ahead.md
- src/box/xlog.c
- src/box/xlog.h
- test/unit/CMakeLists.txt
- test/unit/xlog.c
`XLOG_READ_AHEAD` defines the number of bytes added to the `count` argument
of the `pread` syscall, currently it equals to 16 KB. However xlog and snap
files are written by 128 KB chunks of data, which turn into ~80 KB chunks
after compression (in average, depending on the data), so the 16 KB read-
ahead doesn't make any sense.
According to performance experiments, 8 MB readahead gives the best results
for large files. However, 8 MB read buffers would increase memory
consumption of the replication relays, which usually read small portions of
data and does not need such a big buffers. For this reason, dynamically-
sized read buffer is implemented by this patch. The minimum readahead is
now 128 KB, and the maximum is 8 MB. As a result, the recovery time of a
900 MB snapshot decreased from …
> box: dynamically adjust xlog readahead size

- .github/workflows/alpine_3_16.yml
- .github/workflows/alpine_3_16_aarch64.yml
Generate a test build key when the ALPINE_BUILD_KEY secret is empty.
It is needed for fork PRs where secrets are unavailable.
> ci: fix alpine workflows for fork pull requests

- changelogs/unreleased/gh-8216-tuple-update-crash.md
- src/box/xrow_update_field.h
- src/box/xrow_update_route.c
- test/box/update.result
- test/box/update.test.lua
```
xrow: fix bar new field update crash
A tuple update with the first operation creating a new field
somewhere deep in the tuple and the second operation trying to go
into that new field could crash. This happened because the route
branching function xrow_update_route_branch() missed this case.
It can be detected when see that the bar path is already fully
used (the next JSON token is END), and the new operation's path
is still not END.
```
```
xrow: fix array new field update crash
A tuple update with the first operation creating a new field
inside an array and the second operation trying to go into that
field could crash. This happened because the branching function
xrow_update_op_do_field_##op_type() didn't take into account newly
set scalar fields and an `unreachable()` was hit.
Part …
```
> Fix a couple of crashes in tuple update

- test/box-luatest/gh_7394_memtx_mvcc_space_cnt_bug_test.lua
Closes #7394
If you want to verify that this test fails, you need to checkout commit 88203d4f or older.
> test: add test for #7394 (`space:count` bug in memtx MVCC)

- changelogs/unreleased/gh-7031-configure-eos-in-lua-console.md
- src/box/lua/console.lua
- test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- test/app-luatest/gh_8136_fix_print_wrapper_not_handling_errors_thrown_from_print_test.lua
- test/box-luatest/hide_show_prompt_test.lua
- test/interactive_tarantool.lua
There used to be ';' as a default printed End Of Statement in Lua, which
could be confusing for a human. Now the default printed EOS is '' and it
can be configured per session with `\set output lua,eos=`. Works on both
local and remote consoles.
Closes https://github.com/tarantool/tarantool/issues/7031
Title: configure printed End Of Statement symbol in Lua console
The old behavior was:
```
tarantool> \set output lua
true;
tarantool> 123
123;
```
Now default EOS is '', you can set it like this:
```
tarantool> \set output lua
true
tarantool> 123
123
tarantool> \set output lua,eos=/
true/
tarantool> 123
123/
tarantool> \set output lua,eos=
true
tarantool> 123
123
```
EOS can be only one non-space symbol. If you don't provide a symbol, it
would be configured to ''.
>  console: configure printed EOS symbol in Lua console 

- src/box/raft.c
- src/lib/raft/raft.c
- test/replication-luatest/election_pre_vote_test.lua
- test/replication-luatest/gh_8168_extra_term_bump_test.lua
- test/unit/raft.c
Fixing a bug with nodes in 'manual' election mode bumping the term excessively revealed a hang in election_pre_vote test. Turns out the test passed thanks to the previous buggy behaviour.
The following behaviour is expected: when a node is configured in manual election mode, calling box.ctl.promote() on it should make it bump term once, try to gather votes and fail on timeout.
Once the extra term bump on timeout was removed in commit 5765fdc4e4ec ("raft: fix 'manual' nodes bumping the term excessively"), box.ctl.promote() without a quorum started hanging.
Let's return the correct behaviour: 'manual' nodes should transition back to follower if an election timeout passes after the promotion without any term outcome.
Enable the test_promote_no_quorum testcase of election_pre_vote test back, …
> raft: fix box.ctl.promote() hanging when cannot gather a quorum

- test/box-py/iproto.test.py
- test/box-py/suite.ini
To improve the stability of the tests, let's use unix sockets for iproto connection instead of ports.
> test: use unix sockets for iproto in box-py tests

- src/lua/utils.c
- src/lua/utils.h
The function was replaced by luaT_newmodule(). See commit e3cf5a5d636f ("lua: add built-in module registration function") for the motivation and details.
Now all luaL_register_module() usages are eliminated (including Tarantool Enterprise source code) and we can safely drop it.
Part of #7774
Follows up PR #8173
> lua: drop luaL_register_module()

- changelogs/unreleased/fix-datetime-width-overflow.md
- src/lib/tzcode/strftime.c
- test/app-tap/datetime.test.lua
We didn't take into consideration the fact, that precision
value passed to control the width of nanoseconds part in
datetime_object:format could be more than maximum positive
value, integer may have. Currently it leads to segfault.
```
tarantool> require('datetime').new{}:format('%2147483648f')
```
We should check errno in order to find out, if overflow
occurs. The problem is the fact, that `width` variable must
have int type due to snprintf requirements ("%*d") and
strtol returns long. Errno won't be set if returned value
is in bounds [INT_MAX, LONG_MAX], but it will overflow
int resulting in inconsistent behavior.
So, let's save the result of strotl to the temp value.
If this value doesn't belong to the above-mentioned set,
or errno was set, we assign to `width` maximum value, it
may …
> datetime: fix precision overlflow

- test/replication-luatest/bootstrap_strategy_auto_test.lua
The test started hanging after commit d560fb3f0fed ("Revert "replication: set default replication_sync_timeout to 0"") because it still expected a zero replication_sync_timeout. This wasn't caught by PR's full-ci for some reason.
Follow-up #8223
> test: fix bootstrap_strategy_auto_test hang

- src/tt_uuid.c
- src/tt_uuid.h
This patch fixes compilation on macOS 12.6.3 with AppleClang 14.0.0:
```
$ cmake .. -DENABLE_WERROR=ON
$ cmake --build .
[ 47%] Building CXX object src/box/CMakeFiles/tuple.dir/tuple_compare.cc.o src/box/tuple_compare.cc:31:
src/box/tuple_compare.h:38:
src/box/tuple.h:37:
src/tt_uuid.h:127:2: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
sprintf(out, "%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x",
^
```
In Tarantool 2.x this is fixed by commit 368766e697fd ("Fix static buffer align").
Closes #8277
> [1.10] uuid: use `snprintf` instead of `sprintf`

- changelogs/unreleased/log-build-target-triplet.md
- src/main.cc
This is useful for example for the analysis of performance complaints from users, when they claim that one version of Tarantool is slower than another, in fact comparing debug and release builds.
The log format is approved by @Mons and @unera.
> log: print build target triplet alongside with the version

- .github/workflows/osx_12_static_cmake.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
Sometimes, we only need to test static-build, e.g. when we apply a patch to a third party sub-project. Let's introduce a new label to run the ci checks faster in this case.
> ci: run static-build workflows on 'static-build-ci' label

- src/box/memtx_space.c
Now, delete in ephemeral space is obviously incorrect - if we try to delete a tuple, which is not present in index, NULL dereference will happen. Fortunately, ephemeral spaces are used for internal purposes only, so, most likely, this never happens. Let's fix this part not to confuse code analyzers.
Closes https://github.com/tarantool/security/issues/38
> memtx: fix potential NULL dereference in memtx_space_ephemeral_delete

- static-build/cmake/AddDependencyProjects.cmake
- static-build/patches/openssl-tarantool-security-54.patch
tls_construct_ctos_session_ticket() has a potential NULL pointer dereference.
Closes tarantool/security#54
NO_DOC=security
NO_TEST=security
NO_CHANGELOG=security
> static-build: fix potential NULL deref in openssl

- src/CMakeLists.txt
- src/box/lua/console.lua
- src/box/lua/init.c
- src/box/lua/net_box.lua
- src/box/lua/xlog.lua
- src/lua/fio.c
- src/lua/fio.lua
- src/lua/init.c
- src/lua/init.lua
- src/lua/loaders.lua
- src/lua/minifio.c
- src/lua/minifio.h
- src/lua/minifio.lua
- src/lua/utils.c
- src/lua/utils.h
- test/app/fio.result
This patchset continues the [series][1] of preliminary commits for implementing the built-in module overriding (so called dual-life modules, see #7774 for the problem statement).
The core idea of the future functionality is that if there is the `override.foo` module on the filesystem, it automatically replaces the built-in module `foo`.
Several changes are needed to implement the overriding:
* Move Lua loaders implementation into its own file `loaders.lua`.
* Split `fio` to `minifio` (needed by the loaders) and `fio`.
* Move the loaders into an early initialization stage.
* Eliminate direct `package.loaded` assignments in src/box/lua/*.lua files.
* Hide built-in module registration process behind a function (to modify it later).
The overriding itself will go as a separate pull request. …
> lua: preliminary refactoring for built-in modules overloading [2/2]

- static-build/cmake/AddDependencyProjects.cmake
The problem is if `cat` fails, because a patch file doesn't exist `PATH_COMMAND` written like this won't detect it, because the last command (`patch`) will complete successfully (apply existing patches found by `cat`):
```
cat XXX.patch YYY.patch | patch -p1
```
The proper way is to use `PATCH_COMMAND` continuation:
```
PATCH_COMMAND patch -p1 -i XXX.patch
COMMAND       patch -p1 -i YYY.patch
```
> static-build: don't use cat to apply multiple patches

- src/lib/core/fiber.c
- src/main.cc
The main cord's event loop is initialized by fiber_init(), but for some reason successful initialization is only checked in main() after other initialization code might try to use the event loop already.
For example, some of the loop users are coio_enable(), signal_init(), tarantooL_lua_init(), and they are all run before we actually check that loop is not NULL.
Closes https://github.com/tarantool/security/issues/28
> core: check event loop creation in fiber_init()

- static-build/cmake/AddDependencyProjects.cmake
- static-build/patches/openssl-tarantool-security-27.patch
> static-build: fix potential NULL dereference in openssl

- src/box/recovery.cc
> recovery: check return value of `fiber_new_system` for watcher fiber

- src/lib/mpstream/mpstream.c
- src/lib/mpstream/mpstream.h
> mpstream: fix NULL dereference in `mpstream_encode_double`

- src/box/box.cc
Sometimes the return value of `cfg_gets()` is checked for NULL, and sometimes not. Actually this is intended, although a bit confusing. If an option can have a nil value, it must be checked for NULL, but if it can't be nil, there is no sense in it. The nil value can be assigned only by default, it cannot be set via `box.cfg{}`.
This patch removes the NULL checks for `cfg_gets("election_mode")` and `cfg_gets("election_fencing_mode")` because they are not nil by default. All other non-nil options (e.g. `cfg_gets("bootstrap_strategy")`) are already implemented without the NULL checks.
Follow-up tarantool/security#75
> box: don't check return values of some cfg_gets() for NULL

- .gitmodules
- changelogs/unreleased/gh-7726-embed-checks.md
- debian/copyright
- src/CMakeLists.txt
- src/box/lua/init.c
- test/app-luatest/checks_test.lua
- test/app-luatest/tnt_debug_getsources_test.lua
[tarantool/checks](https://github.com/tarantool/checks) is a lua module (distributed as a separate rock) for function input validation.
After this patch, it will a part of the tarantool binary.
Closes #7726
Needed for #7725
> lua: embed checks module

- changelogs/unreleased/gh-8240-yaml-alias-serialize-fix.md
- src/lua/serializer.c
- src/lua/serializer.h
- test/app-luatest/gh_8240_yaml_alias_serialize_test.lua
- test/swim/swim.result
- third_party/lua-yaml/lyaml.cc
YAML format supports aliases, which are useful in case the same object is referenced more than once (for instance spaces are referenced by name and id in the `box.space` table):
```
tarantool> x = {}
---
...
tarantool> {a = x, b = x}
---
- a: &0 []
b: *0
...
```
The implementation has two bugs:
1. Aliases aren't detected in objects returned by the `__serialize` method:
```
tarantool> x = {}
---
...
tarantool> setmetatable({}, {
>     __serialize = function() return {a = x, b = x} end,
> })
---
- a: []
b: []
...
```
2. An object that implements the `__serialize` method isn't aliased:
```
tarantool> x = setmetatable({}, {
>     __serialize = function() return {} end,
> })
---
...
tarantool> {a = x, b = x}
---
- a: []
b: []
...
```
This PR fixes both issue.
Needed for …
> Fix alias detection in YAML serializer in case `__serialize` method is available

- changelogs/unreleased/downgrade.md
- src/box/lua/upgrade.lua
- test/box-luatest/downgrade_helper.lua
- test/box-luatest/downgrade_test.lua
See documentation below for details.
By the way fix `grant_rw_access_on__session_settings_to_role_public` of upgrade to be idempotent. The changes made by the function are not reverted on downgrade thus we need this fix to be able to downgrade and then upgrade back.
Part of #7718
Title: Document box.schema.downgrade etc
Downgrade makes possible to run database on older versions on Tarantool.
Typical usage is next (running on 2.11.0 in the example below):
```
tarantool> box.schema.downgrade('2.10.0')
tarantool> box.snapshot()
tarantool> os.exit()
```
After this command you can run database on Tarantool version 2.10.0
or later. `box.schema.downgrade` only takes version listed in
`box.schema.downgrade_versions()` which is a list of all releases
since 2.8.2.
`downgrade` …
> box: support downgrading of system spaces

- src/tarantool-gdb.py
New implementation works correctly when MsgPack and Tuple expressions in the mentioned commands contain spaces
Closes #8299
> gdb: reimplement arguments parsing for 'tt-mp' and 'tt-tuple'

- src/box/lua/load_cfg.lua
- src/box/lua/schema.lua
Commit 3fb0f7f1b713 ("fix gh-362 and lots of error messages fixes") intriduces an option "dont_check" that disables checks for a certain parameter. This option is not documented anywhere and looks unusable. This commit removes it.
Follows up #362
> box: remove dont_check option

- src/box/xlog.c
- src/lib/core/fiber.c
**box: check return value of `obuf_alloc()` in `xlog_tx_write_zstd()`**
`obuf_alloc(&log->zbuf, XLOG_FIXHEADER_SIZE)` can potentially fail, because there is no `obuf_reserve()` prior to it.
Closes https://github.com/tarantool/security/issues/74
---
**core: replace `sysconf(_SC_PAGESIZE)` with `small_getpagesize()`**
Bump the small submodule and use `small_getpagesize()`, which is a wrapper over `sysconf(_SC_PAGESIZE)` with a proper error checking.
Closes https://github.com/tarantool/security/issues/78
> 2 minor fixes

- changelogs/unreleased/gh-8269-log-syslog-incorrect-facility.md
- src/lib/core/say.c
~Fixes syslog facility. Multiplying does not need there because `LOG_MAKEPRI` will make it byself or defined constants already have bit offset, depending on the OS.~
See the linked issue for the problem description. Affects musl based Linux distros (Apline), distros with glibc prior to 2.17 (CentOS 6) and OpenBSD.
Fixes #8269
> Fixes syslog facility

- test/engine-luatest/pagination_test.lua
We have a mechanism for detecting runtime memory leaks, see commit 19abfd2a3920 ("misc: get rid of fiber_gc") so there's no need to test it manually. The test is inherently flaky, because the size of runtime memory depends on test case execution order so let's drop it.
Follow-up commit ec1a71ffed2aa ("box: introduce pagination to memtx_tree and tuple position methods").
> test: drop engine-luatest/pagination_test:test_runtime_memory_leak

- src/box/lua/upgrade.lua
Sometimes we need to disable system triggers to perform a tricky change in system spaces. Later we enable them back. But in case of error in between we miss the enabling. With system triggers off the application behaviour will be quite surpising. Let's fix it.
Follow-up #7718
NO_DOC=minor
NO_TEST=minor
> upgrade: enable system triggers back on errors

- static-build/cmake/AddDependencyProjects.cmake
- static-build/patches/openssl-tarantool-security-90.patch
n_ssl3_mac(): Fix possible divide by zero.
Fixed in openssl3:
https://github.com/openssl/openssl/commit/624efd2ba6f1dabdcdecf17c77bd206c421efdaf
Closes tarantool/security#90
NO_DOC=security
NO_TEST=security
NO_CHANGELOG=security
> static-build: fix possible div-by-zero in openssl

- src/box/lua/load_cfg.lua
- src/lua/compat.lua
We plan to provide compat options information via the website. It was requested by Kirill Yukhin instead of the wiki pages (and I don't mind it).
> compat: use tarantool.io URLs for compat options

- static-build/cmake/AddDependencyProjects.cmake
- static-build/patches/readline-tarantool-security-95.patch
This patch fixes potential read of uninitialized variable in history_truncate_file()
Fixed in upstream:
https://git.savannah.gnu.org/cgit/readline.git/commit/?h=devel&id=b4ebdc06601fb54297435d2e286d901cba1cd6c6
Closes tarantool/security#95
NO_DOC=security
NO_TEST=security
NO_CHANGELOG=security
> static-build: fix readline read of uninit variable

- src/box/tuple_format.c
Let's use `xregion_alloc` instead of `region_alloc`, because memory allocations from fiber region shouldn't normally fail, see #3534.
Closes tarantool/security#97
> box: handle `region_alloc` failure in `tuple_field_map_create_plain`

- test/box-luatest/gh-6786_func_index_iterator_stable_test.lua
Check allocation and deallocation of different sizes of of functional index function result.
Follow-up of of #6786
NO_DOC=test
> memtx: add one more test for functional index

- changelogs/unreleased/gh-6786-crash-func-index.md
- src/box/memtx_engine.cc
- test/box-luatest/gh-6786_func_index_iterator_stable_test.lua
When function of a functional index is called, the result is stored in memtx allocator chunks among data tuples. By design, memtx allocator requires size of allocation for deallocation, so the size has to be stored along with the data (actually right before it). By a mistake, when being deleted, the size of data was retrieved slightly wrong, giving the value of 4 bytes less. Due to the allocator specific design the size error leads to a rare crashes when the size of functional index function result was about 160 bytes (157..160 bytes with default config). It seems that sizes about 320 etc are affected to.
Fix it by correct size evaluation of functional index chunks.
Hotfix of https://github.com/tarantool/tarantool/issues/6786
> [2.10] memtx: fix size calculation in functional index chunks

- changelogs/unreleased/fix-error-throw-from-__gc.md
- changelogs/unreleased/gh-6786-crash-func-index.md
- src/box/memtx_engine.c
- test/box-luatest/gh-6786_func_index_iterator_stable_test.lua
This PR incorporates two hotfixes:
- protecting call to lj_gc_step on trace exit
- size calculation in functional index chunks
> [2.8] Hot fix Tarantool and LuaJIT

- changelogs/unreleased/gh-8182-module-search-next-to-script.md
- src/lua/init.c
- src/lua/init.h
- src/lua/loaders.lua
- src/lua/minifio.c
- src/lua/minifio.h
- src/lua/minifio.lua
- src/main.cc
- test/app-luatest/module_search_test.lua
It eliminates a need to call `package.setsearchroot()` in the main script to find modules in the application's directory.
Such layout is typical for cartridge based applications. It it also used, when different versions of modules are in use in different applications and installing the modules into the system is not an option.
Let's assume that there is an application in the directory /path/to/myapp with modules inside:
```
+ /path/to/myapp/
+- .rocks/share/tarantool/
+- foo.lua
+- init.lua
+- myapp/
+- bar.lua
```
Now the following command automatically adds the path to the main script directory to search paths for modules:
```sh
$ tarantool /path/to/app/init.lua
```
So `require('foo')` and `require('myapp.bar')` works without any additional work.
Follows up #7774
Fixes #8182
> lua: search modules next to the main script

- src/lua/init.c
- src/lua/init.h
- src/lua/loaders.lua
- src/main.cc
- test/app-luatest/override_misc_test.lua
Use case: an override module is designed to replace a built-in module only when the module is required from an application, not from the platform itself.
Now it is possible:
```lua
-- override/fio.lua
local loaders = require('internal.loaders')
if loaders.initializing then
loaders.no_package_loaded.fio = true
return loaders.builtin.fio
end
return {
whoami = 'override.fio',
}
```
Follows up #7774
> lua: allow to override a module only for application's code

- src/lua/utils.c
- src/lua/utils.h
- test/app-luatest/override_panic_test.lua
- test/justrun.lua
- test/treegen.lua
The built-in module registration process performs several assertions:
- luaT_newmodule() checks for attempts to register an already registered module.
- luaT_setmodule() does the same, but it allows the same value be 'registered' several times.
Attempt to register different values as the same built-in module is definitely an error. Once a module is registered, it may be required and captured. If its value is changed afterwards, different parts of tarantool's code will capture different values for the same built-in module. It is very unlikely that such effect may be intended.
Anyway, tarantool's code doesn't do this. However, now, after implementing the override modules feature, it is possible to influence tarantool's initialization from a user provided code.
It means that we can't assume …
> lua: panic on suspicious built-in modules manipulations

- changelogs/unreleased/gh-8249-lual_checkcdata-with-upvalues.md
- src/lua/serializer.c
- src/lua/utils.c
- src/lua/utils.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
We have a code that performs calculations to obtain the address from the
given index, the address is then passed to `cdataV()` to get cdata value from
the stack. But this doesn't work for pseudo-indexes (e.g. upvalue indexes).
This patch brings `index2adr()` from `luajit/src/lj_api.c`, which accepts all
kinds of indexes, so that the calculations are no longer needed. Also the
helper function `luaL_tocpointer()` is introduced.
Closes #8249
> lua/utils: use `index2adr()` instead of index arithmetic

- changelogs/unreleased/gh-7845-httpc-stream-io-interface.md
- src/curl.c
- src/curl.h
- src/httpc.c
- src/httpc.h
- src/lua/httpc.c
- src/lua/httpc.lua
- test/app-luatest/http_client_test.lua
Add a streaming data input/output object for http.client. The input/output object can be created using the same methods and the same options as a normal request, but with a new option {chunked = true}.
An uncompleted io object has only headers and cookies fields. A completed io object has the same fields as a normal request, but without the `body` field.
The io object interface looks like the socket object interface and should have the same description:
```
io_object:read(chunk[, timeout])
io_object:read(delimiter[, timeout])
io_object:read({chunk = chunk, delimiter = delimiter}[, timeout])
io_object:write(data[, timeout])
```
The difference is in the method `finish`. Unlike socket:close() it has an optional parameter `timeout`:
```
io_object:finish([timeout])
```
Be careful, the call may …
> httpc: introduce stream input/output interface

- src/lib/core/say.c
- src/lua/log.lua
- test/box-luatest/gh_3211_per_module_log_level_test.lua
Currently it's possible to set the log level for a particular Lua module, or to change the default log level, however there is no way to change it only for Tarantool system messages. This patch introduces a fake module name "tarantool" for this purpose.
Closes #8320
> log: allow "tarantool" as module name in `box.cfg{log_modules = {...}}`

- changelogs/unreleased/gh-7456-console-debugger-option.md
- src/lua/init.c
- src/lua/init.h
- src/main.cc
- test/app-luatest/console_debugger_session_test.lua
- test/app-luatest/debug-self-target.lua
- test/app-luatest/debug-target.lua
- test/box-py/args.result
- third_party/lua/README-luadebug.md
- third_party/lua/luadebug.lua
Added `-d` option for convenient activation of a debugger shell:
- it calls `luadebug.lua::start` instead of  `console.lua::start` for interactive shell.
> **NB!** 84b54be is temporal, while there is no
> yet committed #7790 where behaviour of commands `cmd_up`/`cmd_down` have been
> properly fixed.
Part of #7456
> debugger: `tarantool -d` option, step.4

- changelogs/unreleased/gh-6085-log-and-limit-iteration.md
- src/lib/core/fiber.h
- src/lua/fiber.c
- src/lua/fiber.lua
- test/app-luatest/fiber_slice_test.lua
This PR adds the new `compat` option [`fiber_slice_default`](https://tarantool.io/compat/fiber_slice_default). The old default is no limit. The new default is `{warn = 0.5, err = 1.0}`.
Apart from adding the option, this PR also fixes errors raised on invalid slice argument and adds the current value of the max slice to `fiber.info()`, which is useful for introspection and testing.
[Link](https://www.notion.so/tarantool/Fiber-slice-3673c044cb3b445f886970b8e5229bb9) to the discussion behind this decision.
Follow-up #6085
> Add compat option for default fiber slice

- changelogs/unreleased/gh-5869-fix-crash-without-rdtscp.md
- src/lib/core/fiber.c
clock_gettime(CLOCK_MONOTONIC) is implemented via the RDTSCP instruction on x86 an has the following advantages over the raw instruction:
* It checks for RDTSCP availability in CPUID. If RDTSCP is not supported, it switches to RDTSC.
* Linux guarantee that clock is monotonic, hence, the CPU miss detection is not needed.
* It works on ARM.
As for disadvantage, this function is about 2x slower compared to a single RDTSCP instruction. Performance degradation measured by the fiber switch benchmark [1] is about 3-7% for num_fibers == 10-1000.
Backport of #5869
[1] https://github.com/tarantool/tarantool/issues/2694#issuecomment-546381304
(cherry picked from commit 2fb7ffc502888c173484ec3fe594cee81cac0e8d)
> [2.8] fiber: use `clock_monotonic64` instead of `__rdtscp`

- test/app-luatest/console_debugger_session_test.lua
In Tarantool EE the version string is "Tarantool Enterprise", not just "Tarantool".
Fixes commit a984fc0d530b ("debugger: use option -d for debugger activation")
> test: fix app-luatest/console_debugger_session_test for EE

- src/box/lua/net_box.c
When calculating `rows_index` in `netbox_decode_execute` etc we use implementation defined behavior of compiler. `i < mapsize` and this is fine according to standard as unsigned arithmetic is well defined on overflows. But then we cast the result to int and this is implementation defined as the result can not be represented by int.
Closes https://github.com/tarantool/security/issues/98
NO_DOC=minor
NO_TEST=minor
> net_box: don't use integer implementation defined

- .github/ISSUE_TEMPLATE/2-11-0-rc.md
We want to explicitly collect feedback that regards 2.11 release candidates.
The template automatically adds `2.11.0-rc` label to the new issue, so it'll be easier to filter issues relevant for the release candidates.
> Add 2.11.0-rc issue template

- src/box/vinyl.c
- test/vinyl-luatest/gh_8372_key_alloc_error_in_iter_ctor_test.lua
Error labes got mixed up. Fix the order and add a test.
Fixes commit 3f0263395bee ("vinyl: implement iterator pagination").
Closes #8372
> vinyl: fix use after free on key alloc error in iterator constructor

- cmake/BuildNghttp2.cmake
Updating libcurl from 7.84.0 to 7.87.0 in commit 09f4eca1ef79 ("third_party: update libcurl from 7.84.0 to 7.87.0") made it impossible to built tarantool with bundled curl with nghttp2, because nghttp2 was not updated to fit libcurl 7.87.0, this led to missing function `nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation` during linking step.
https://github.com/nghttp2/nghttp2/releases/tag/v1.51.0
Closes #8268
NO_DOC=there is no known behavior changes, consider the change as not
visible for a user
NO_TEST=can only reproduce in specific environment
NO_CHANGELOG=see NO_DOC
> third_party: update nghttp2 from 1.48.0 to 1.52.0

- changelogs/unreleased/gh-8363-unable-decode-body.md
- src/lua/httpc.lua
- test/app-luatest/http_client_test.lua
- test/app-luatest/http_client_unit_test.lua
- test/app-luatest/httpd.py
Patch fixes a bug when body in response couldn't be decoded:
```
tarantool> httpc = require('http.client').new()
tarantool> response = httpc:get('https://jsonplaceholder.typicode.com/todos/1')
tarantool> response:decode()
---
- error: 'builtin/http.client.lua:301: attempt to index field ''decoders'' (a nil
value)'
...
```
Reported-by: Alexander Turenko <alexander.turenko@tarantool.org>
Fixes #8363
NO_DOC=bugfix
> httpc: added a decoders to a http response

- changelogs/unreleased/gh-7954-sort-spaces-in-snapshot-by-id.md
- src/box/space.c
- src/box/space.h
- src/box/space_cache.c
- src/box/space_cache.h
- test/box-luatest/gh_7954_sort_spaces_in_snap_by_id_test.lua
This also changes the order in which spaces are stored in `.snap` files.
Currently `space_foreach()` iterates over spaces in the following order:
1. Spaces with id in the range [256..510], ordered by id;
2. All other (non-system) spaces in unspecified order.
This patch changes the order to:
1. Spaces with id in the range [256..511], ordered by id;
2. All other (non-system) spaces, ordered by id.
Strict ordered of non-system spaces is required by users who iterate over `.snap` files with `xlog.pairs()`.
Closes #7954
NO_DOC=[[1]](https://www.tarantool.io/en/doc/latest/dev_guide/internals/file_formats/#the-snapshot-file-format) already contains: "the .snap file’s records are ordered by space id"
> box: make `space_foreach()` strictly ordered

- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
The test fails with
```
fail | 2023-03-01 15:54:30.550 [3724975] main/103/server_instance.lua F> can't initialize storage: unlink, called on fd 63,  aka unix/:(socket), peer of unix/:(socket): Address already in use
```
We fixed a similar issue in commit 3d3e9dea137e by using unique instance names. Let's do the same here.
Fixes commit b1095c1c3254
Follow-up #7974
> test: fix gh_7974_force_recovery_bugs flaky test

- test/app-luatest/digest_crc32_recording_test.lua
Add missing `server:drop()` to digest_crc32_recording_test.lua to avoid running tarantool processes after the test.
> test: add cleanup to digest_crc32_recording_test

- changelogs/unreleased/gh-7294-long-reconnection-fix.md
- src/box/applier.cc
- test/replication-luatest/gh_7294_dont_connect_infinitely_test.lua
We use coio_connect() to connect the replica to a remote peer. It implies no timeout, and does a non-blocking connect() to the peer and then waits for the socket to become writable indefinitely.
When the remote peer changes its IP address, connect() might try connecting to the old address for as long as ~ 2 minutes (given the default tcp_syn_retries value of 6).
This blocks replica from trying to reconnect to the updated address and is pretty inconvenient.
Let's use coio_connect_timeout() instead and use
replication_disconnect_timeout() as a timeout, like everywhere else in master-replica communication.
Closes #7294
NO_DOC=bugfix
> replication: add remote peer connection timeout

- src/lib/core/say.c
- src/lib/core/say.h
- src/main.cc
- test/app-luatest/gh_8287_wrong_initial_log_level_printed_test.lua
The `log_level` configuration parameter can be set as a number or a string. When it is a string, `cfg_geti()` returns 0.
Closes #8287
> main: fix wrong log level printed during first `box.cfg{}`

- src/box/memtx_tree.cc
- test/engine-luatest/pagination_test.lua
If the tuple pointed to by 'after' isn't in the space, eq pagination would skip it because of the broken 'equals' flag update in the memtx iterator.
Closes #8373
> memtx: fix eq pagination in case after tuple is absent

- src/box/box.cc
- src/box/index.cc
- src/box/index.h
- src/box/key_def.h
- src/box/tuple_compare.cc
- src/box/vy_range.c
- src/box/vy_stmt.h
- test/box-luatest/pagination_netbox_test.lua
- test/engine-luatest/pagination_test.lua
- test/unit/key_def.c
If the 'after' key is less than the search key in case of ge/gt or greater than the search key in case of le/lt, the iterator either
crashes (vinyl) or returns invalid result (memtx). This happens because the engine implementation doesn't expect an invalid 'after' key. Let's fix this by raising an error at the top level in case the 'after' key doesn't meet the search criteria.
Closes #8403
Closes #8404
> box: check iterator position against search criteria

- src/httpc.c
This patch addresses coverity complain 1535241.
Follow-up #8047
NO_TEST=nit
NO_CHANGELOG=nit
NO_DOC=nit
> httpc: check region_join result

- changelogs/unreleased/gh-7294-long-reconnection-fix.md
- changelogs/unreleased/gh-7974-force-recovery-without-user-spaces.md
- changelogs/unreleased/gh-8252-disable-jit-on-macOS-by-default.md
- changelogs/unreleased/gh-8363-unable-decode-body.md
- changelogs/unreleased/gh-8391-bump-zstd.md
Proofread changelogs for 2.11.0-rc2
> Proofread changelogs for 2.11.0-rc2

- test/replication-luatest/gh_4669_applier_reconnect_test.lua
In the test we start replicas only with master in box.cfg.replication. We cannot use bootstrap_strategy = 'auto' mode, which is default, as it properly works only when all participants of the cluster are listed in replication parameter. Sometimes, when one replica connects to the master, the other one has already successfully joined, so the first replica sees in ballot, that it doesn't have all nodes from cluster in box.cfg.replication and fails to start.
Let's use 'legacy' boostrap strategy for now.
Closes tarantool/tarantool-qa#310
NO_DOC=test-fix
NO_CHANGELOG=test-fix
> test: fix fail of gh_4669_applier_reconnect_test

- src/box/alter.cc
- static-build/cmake/AddDependencyProjects.cmake
- static-build/patches/icu-tarantool-security-96.patch
There are two cases when class method is used to calculate an argument for base
class constructor when it is not built yet. Fortunately, they does not
use class fields - let's make them static to use them before class
initialization legitimately.
Closes tarantool/security#96
> Fix calling class method before it is initialized 

- changelogs/unreleased/gh-8069-luajit-fixes.md
* ARM64: Avoid side-effects of constant rematerialization.
* ARM64: Fix {AHUV}LOAD specialized to nil/false/true.
* ARM64: Fix pcall() error case.
* Fix math.min()/math.max() inconsistencies.
* test: add test case for math.modf
Closes #6163
Part of #8069
Follows up #7230
> [backport/2.11] luajit: bump new version

- test/unit/msgpack.result
This update pulls the following commits:
* Add mp_memcpy and mp_memcpy_safe
* Add mp_encode_*_safe family that handles buffer overflow
Required for refactoring emerged when fixing issues:
https://github.com/tarantool/tarantool-ee/issues/357
https://github.com/tarantool/tarantool-ee/issues/358
Depends on PR https://github.com/tarantool/msgpuck/pull/29
> Bump msgpuck submodule

- src/box/sql/vdbe.c
```c
<...>/src/box/sql/vdbe.c:378:11: error: variable 'nVmStep' set but not
used [-Werror,-Wunused-but-set-variable]
unsigned nVmStep = 0;      /* Number of virtual machine steps */
^
```
The usage of the variable was removed in commit dbad19ef0aae ("sql: drop unused functions").
See also #8110.
> build: drop unused variable detected by clang 15

- src/box/CMakeLists.txt
- src/box/alter.cc
- src/box/blackhole.c
- src/box/index.cc
- src/box/index.h
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_space.c
- src/box/memtx_space_upgrade.c
- src/box/memtx_space_upgrade.h
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/read_view.c
- src/box/read_view.h
- src/box/sequence.c
- src/box/sequence.h
- src/box/session_settings.c
- src/box/space.c
- src/box/space.h
- src/box/space_upgrade.c
- src/box/space_upgrade.h
- src/box/sysview.c
- src/box/vinyl.c
- test/box-luatest/space_upgrade_test.lua
If a read view is created while a space upgrade is in progress, the space upgrade function should be applied to all tuples retrieved from the space read view. A tuple passed to the space upgrade function should have proper field names: tuples that had been upgraded by the time when the read view was created should have new field names while tuples that hadn't been upgraded should have old field names. Currently, all tuples use new field names. This works fine as long as fields aren't renamed (e.g. a new field is appended), but if a field is renamed (e.g. a new field is inserted in the middle), the space upgrade function will see invalid field names and, as a result, may not work as expected.
This PR is intended to fix this issue.
Needed for …
> space_upgrade: use old format for non-upgraded read view tuples - CE part

- src/box/lua/merger.c
- test/box-tap/merger.test.lua
The `merger.new()` call has the following code in the `luaT_merger_new_parse_sources()` function:
```c
uint32_t source_count = lua_objlen(L, idx);
for (uint32_t i = 0; i < source_count; ++i) {
<...>
}
lua_pop(L, source_count);
```
It is possible that zero amount of sources are passed:
```lua
merger.new(kd, {})
```
In this case the `source_count` variable is zero.
`lua_pop()` is a macro defined this way:
```c
#define lua_pop(L,n)		lua_settop(L, -(n)-1)
```
It means that `n` in the `-(n)-1` expression is an unsigned 32 bit zero. Unsigned overflow is okay: it has defined behavior by the C standard and has the result 2^32-1 in the given case.
The `lua_settop()` function is defined as follows:
```c
LUA_API void  (lua_settop) (lua_State *L, int idx);
```
We pass the `-(n)-1` value as `int idx` …
> merger: fix signed integer overflow

- changelogs/unreleased/gh-4632-net-box-unknown-field-type.md
- src/box/lua/misc.cc
- test/box-luatest/gh_4632_net_box_unknown_field_type_test.lua
This commit fixes the following assertion failure that happens on a client in case a remote schema contains an unknown field type:
```
src/box/lua/misc.cc:395: int lbox_tuple_format_new(lua_State*): Assertion `fields[i].type != field_type_MAX' failed.
```
To fix the bug we remove the code that tries to set field types from `box.internal.new_tuple_format`. Actually, the format is used solely for providing field names so types are ignored anyway.
Closes #4632
> net.box: fix crash when remote space field has unknown type

- changelogs/unreleased/gh-6119-fix-number-mp-encode.md
- src/lua/msgpackffi.lua
- test/app-luatest/gh_6119_number_mp_encode_test.lua
- test/engine-luatest/gh_6119_select_big_numbers_test.lua
Due to a typo some big numbers were coded as MP_(U)INT.
Since msgpackffi is used in selectffi, which is used for memtx, that could lead to strange select results with big number keys.
Closes #6119
NO_DOC=bugfix
> box: fix big number encoding by msgpackffi

- changelogs/unreleased/gh-8463-crash-on-create-function
- src/box/func_def.c
- test/box-luatest/func_test.lua
`func_opts_reg` definition misses a `OPT_END` termintator item. This leads to UB on iterating it. Particularly when `func_opts_reg` is used as argument to `opts_decode` in `func_def_new_from_tuple`.
Closes #8463
NO_DOC=bugfix
> box: fix a crash on unknown function option

- src/box/index_def.c
- src/box/index_def.h
- src/box/memtx_tree.cc
Currently, we use space to get primary key definition for extracting
iterator position in functional index. It was not a good solution - we
are not allowed to use space for pagination over read view because
space can be dropped. Let's add primary key defintion to `index_def`
and use it.
Part of tarantool/tarantool-ee#285
> box: do not use space for extracting iterator position

- changelogs/unreleased/gh-8448-box-stat-memtx-func.md
- src/box/lua/stat.c
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
`box.stat.memtx` is a table that contains the 'tx' function. This is confusing because other stat entries are callable: `box.stat.net()`, `box.stat.vinyl()`, `box.stat.sql()`.
Let's make `box.stat.memtx` callable for consistency. The function returns a table with the only field 'tx'. Note, we can't drop `box.stat.memtx.tx()` without breaking backward compatibility so we now return `box.stat.memtx().tx` when it's called.
Also, let's use `info_handler` instead of pushing statistics directly to Lua for better encapsulation.
Needed for https://github.com/tarantool/tarantool-ee/issues/143
Closes #8448
> memtx: refactor statistics reporting

- changelogs/unreleased/gh-7515-syncing-follower-notices-leader-hang.md
- src/box/applier.cc
- src/box/relay.cc
- test/replication-luatest/gh_7515_sync_node_sees_leader_hang_test.lua
There was a problem with the leader's relay continuing to ping the remote followers even when the leader's tx thread is hung. This tricked the followers into thinking the leader is alive and well, even though it couldn't serve any new requests.
The problem was partially fixed by commit 56571d83172f ("raft: make followers notice leader hang"): that commit made relay thread stop sending heartbeats in case tx thread is unresponsive.
Up to now we didn't differentiate between heartbeats and data rows: the receipt of both was considered a sign the master is alive. So if some replicas are not up to date with the master, they will continue thinking it's alive until they are fully synced and notice there are no more heartbeats from it.
In order to fix this, stop treating all data as heartbeats and …
> relay: send heartbeats on top of replication stream

- perf/light.cc
- src/box/memtx_bitset.cc
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/sequence.c
- src/box/vy_cache.c
- src/box/vy_mem.c
- src/lib/salad/bps_tree.h
- src/lib/salad/light.h
- src/lib/salad/rtree.c
- src/lib/salad/rtree.h
- test/box-luatest/gh_934_memory_info_test.lua
- test/unit/bps_tree.cc
- test/unit/bps_tree_iterator.cc
- test/unit/bps_tree_view.c
- test/unit/light.cc
- test/unit/light_view.c
- test/unit/rtree.cc
- test/unit/rtree_iterator.cc
- test/unit/rtree_multidim.cc
This PR bumps the small submodule to pull matras statistics and makes memtx use the new statistics for `box.info.memory()`.
Needed for https://github.com/tarantool/tarantool-ee/issues/143
Related PRs: https://github.com/tarantool/small/pull/60 https://github.com/tarantool/small/pull/61 https://github.com/tarantool/tarantool-ee/pull/424
> Use matras statistics for memtx memory info

- .github/workflows/publish-module-api-doc.yaml
- Doxyfile
- src/box/box.h
- src/box/decimal.h
- src/box/error.h
- src/box/field_def.h
- src/box/index.h
- src/box/key_def.h
- src/box/lua/tuple.h
- src/box/schema.h
- src/box/tuple.h
- src/box/tuple_format.h
- src/box/xrow_update.c
- src/lib/core/clock.h
- src/lib/core/coio.h
- src/lib/core/coio_task.h
- src/lib/core/fiber.h
- src/lib/core/say.h
- src/lua/error.h
- src/lua/utils.h
- src/trivia/util.h
src: fix formatting comments for Doxygen
- remove < and > around function names to make them resolvable
- place @sa and \sa to the new lines and remove round parenthesis around
- add missed dots
- added comments for box_tuple_upsert, box_tuple_update, luaT_pusherror
etc.
- replace \example tags with \code and \endcode, because \example
requires a file name with example, when \code allows to place a code
inline
- comments for macroses alignof and likely/unlikely looks a bit ugly,
but I couldn't find a better way to resolve doxygen warning
Closes #8194
NO_CHANGELOG=fix doxygen
NO_DOC=fix doxygen
NO_TEST=fix doxygen
> module api: fix formatting in comments for Doxygen

- changelogs/unreleased/gh-8374-local-print-accepts-non-strings.md
- src/box/lua/console.lua
There used to be a rare error when failed to connect via tarantoolctl to listening cartridge console. It was caused by unclear console.local_print() contract. Starting from gh-7031 fix, the function assumed string-only arguments, while in some cases cdata error was passed.
Now console.local_print() prints all non-string arguments as is, without modifying potential local_eos.
Closes #8374
NO_DOC=bugfix
NO_TEST=very hard to test
> console: fix :endswith() err in tntctl connection

- changelogs/unreleased/gh-8501-memtx-read-view-stats.md
- src/box/memtx_engine.cc
- test/box-luatest/gh_8501_memtx_read_view_stats_test.lua
New entries have been added to `box.stat.memtx()` output:
```
tarantool> box.stat.memtx().data
---
- garbage: 0
total: 24986
read_view: 0
...
tarantool> box.stat.memtx().index
---
- read_view: 0
total: 933888
...
```
`data` shows how much memory is allocated for memtx tuples:
- `data.total` - total amount of memory allocated for data tuples. This includes `data.read_view` and `data.garbage` plus tuples that are actually stored in memtx spaces.
- `data.read_view` - memory held for read views.
- `data.garbage` - memory that is unused and scheduled to be freed (freed lazily on memory allocation).
`index` shows how much memory is allocated for memtx index extents:
- `index.total` - total amount of memory allocated for indexing data. This includes `index.read_view` plus memory used for …
> memtx: introduce read view statistics

- test/app-luatest/gh_4317_console_backslash_test.lua
Currently test can fail if in developer environment .inputrc is custom.
Follow-up #4317
NO_TEST=test fix
> test: fix 4317_console_backslash_test to use defaut .inputrc

- test/fuzz/sql_fuzzer/CMakeLists.txt
Depends on PR https://github.com/tarantool/tarantool/pull/8487 (fixed memleak in SQL)
Fixes #8529
> test/fuzz: get rid of custom cflags

- .github/actions/s3-upload-artifact/action.yml
* Add an extra step that should be considered as a workaround for the
runner agent [ChristopherHX/github-act-runner](https://github.com/ChristopherHX/github-act-runner) that is used on FreeBSD
machines. Without it, env.ARTIFACT_EXISTS will be undefined for some
reason.
* In the s3-upload-artifact action change `if: env.ARTIFACT_EXISTS` to
`if: env.ARTIFACT_EXISTS == 'true'` to be compatible with the FreeBSD
runner agent.
Follows up https://github.com/tarantool/multivac/issues/116
> ci: fix saving artifacts to S3 for FreeBSD

- changelogs/unreleased/gh-4632-net-box-unknown-field-type.md
- changelogs/unreleased/gh-6119-fix-number-mp-encode.md
- changelogs/unreleased/gh-6668-ordering-incomparable-types.md
- changelogs/unreleased/gh-7515-syncing-follower-notices-leader-hang.md
- changelogs/unreleased/gh-7725-embed-metrics.md
- changelogs/unreleased/gh-8070-collation-for-any.md
- changelogs/unreleased/gh-8441-remove-vinyl-root-directory-after-gc.md
- changelogs/unreleased/gh-8448-box-stat-memtx-func.md
- changelogs/unreleased/gh-8457-downgrade-handle-takes-raw-args.md
- changelogs/unreleased/gh-8460-wrong-int-to-dec-convertion-in-arithmetic.md
- changelogs/unreleased/gh-8463-crash-on-create-function.md
- changelogs/unreleased/gh_5997_get_rid_of_schema_max_id.md
- changelogs/unreleased/gh_8036_mix_explicit_and_implicit_space_id.md
- changelogs/unreleased/luajit-grammar-fuzzer.md
- changelogs/unreleased/no-gh-add-tt-dependency.md
> doc: proofread changelogs for the latest version

- changelogs/unreleased/gh-4632-net-box-unknown-field-type.md
- changelogs/unreleased/gh-6119-fix-number-mp-encode.md
- changelogs/unreleased/gh-6668-ordering-incomparable-types.md
- changelogs/unreleased/gh-7515-syncing-follower-notices-leader-hang.md
- changelogs/unreleased/gh-7725-embed-metrics.md
- changelogs/unreleased/gh-8069-luajit-fixes.md
- changelogs/unreleased/gh-8070-collation-for-any.md
- changelogs/unreleased/gh-8441-remove-vinyl-root-directory-after-gc.md
- changelogs/unreleased/gh-8448-box-stat-memtx-func.md
- changelogs/unreleased/gh-8457-downgrade-handle-takes-raw-args.md
- changelogs/unreleased/gh-8460-wrong-int-to-dec-convertion-in-arithmetic.md
- changelogs/unreleased/gh-8463-crash-on-create-function.md
- changelogs/unreleased/gh_5997_get_rid_of_schema_max_id.md
- changelogs/unreleased/gh_8036_mix_explicit_and_implicit_space_id.md
- changelogs/unreleased/ghs-73-unsafe-extensions-decoding.md
- changelogs/unreleased/no-gh-add-tt-dependency.md
> doc: proofread 2.11 changelogs

- src/lib/core/tweaks.c
- src/lib/core/tweaks.h
- src/lua/tweaks.c
- test/unit/lua_tweaks.c
- test/unit/tweaks.c
Allow to register tweaks for variables of type double. Such tweak can be set to any integer or double value.
We need it to add the error factor tweak for the new tuple sorting algorithm (#3389).
Follow-up #7883
> core: add TWEAK_DOUBLE

- src/box/memtx_engine.cc
This may result in invalid statistics if there's more than 4 GB allocated for index extents.
Fixes commit a75f4b7eee823 ("memtx: introduce read view statistics")
Follow-up #8501
Coverity report [1537026](https://scan7.scan.coverity.com/reports.htm#v41662/p13437/fileInstanceId=138568189&defectInstanceId=18798966&mergedDefectId=1537026), [1537027](https://scan7.scan.coverity.com/reports.htm#v41662/p13437/fileInstanceId=138568189&defectInstanceId=18798985&mergedDefectId=1537027).
> memtx: fix integer overflow in memtx index statistics

- test/box-luatest/gh_4264_recursive_trigger_test.lua
- test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
- test/box-luatest/gh_7800_recover_snap_without_spaces_test.lua
- test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua
- test/box-luatest/gh_7917_log_row_on_recovery_error_test.lua
- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
- test/replication-luatest/bootstrap_strategy_test.lua
- test/replication-luatest/election_fencing_test.lua
- test/replication-luatest/gh_5295_split_brain_test.lua
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_6036_qsync_order_test.lua
- test/replication-luatest/gh_6754_promote_before_new_term_test.lua
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/gh_7086_box_issue_promote_assert_test.lua
- test/replication-luatest/gh_7253_election_long_wal_write_test.lua
- test/replication-luatest/gh_7377_bootstrap_connection_failure_test.lua
- test/replication-luatest/gh_7515_sync_node_sees_leader_hang_test.lua
- test/replication-luatest/gh_8168_extra_term_bump_test.lua
- test/replication-luatest/linearizable_test.lua
Bump test-run to new version with the following improvements:
- Bump luatest to 0.5.7-33-g8523e5c [1]
[1] tarantool/test-run@7db594d
Server API from the luatest has been changed: `server:clean()` method has been removed. Use `server:drop()` instead.
Follows up tarantool/luatest#296
> test: bump test-run to version w/ updated luatest and fix tests

- src/CMakeLists.txt
- src/box/lua/init.c
- test/app-luatest/checks_test.lua
- test/app-luatest/tnt_debug_getsources_test.lua
Prepare for checks PR https://github.com/tarantool/checks/pull/54. Without this patch, after https://github.com/tarantool/checks/pull/54 merge master and 2.11 branch integration CI would start to fail, so we need to deal with it first. This patch also bumps embedded `checks` version.
> Checks override prepare

- changelogs/unreleased/gh-7999-bootstrap-strategy-config.md
- changelogs/unreleased/gh-8374-local-print-accepts-non-strings.md
- changelogs/unreleased/gh-8502-fix-buffer-overflow-in-tnt_strptime.md
- changelogs/unreleased/gh-8511-pagination-validate-cmp-def.md
Proofread 3.0 changelogs that were pushed before switching
to new process (reviewing changelogs in PRs).
> doc: proofread 3.0 changelogs

- changelogs/unreleased/gh-7981-fio-read-write-permissions.md
- src/lua/fio.lua
- test/app/fio.result
- test/app/fio.test.lua
For an unknown reason default fio.open() mode used to be set as 0777 & umask that basicly equals to 18, meaning no read/write/execute rights for anyone.
Now the default is 0666 before umask, meaning read and write access.
Closes #7981
NO_DOC=bugfix
> fio: fix default mode for files created by open()

- src/box/tuple_extract_key.cc
- test/unit/key_def.c
Function tuple_extract_key_raw for nullable partially sequential key_def can extract wrong key from tuples without trailing nils. Fortunately, it does not affect tarantool - tuple_extract_key_raw is used only with cmp_def, which ends with non-nullable primary key definition, hence contains no trailing nils.
Closes #8504
> tuple_extract: correctly extract key from tuples without trailing nils

- CMakeLists.txt
- changelogs/unreleased/gh-7311-malloc-info.md
- src/CMakeLists.txt
- src/box/lua/load_cfg.lua
- src/box/lua/slab.cc
- src/lua/init.c
- src/lua/xml.c
- src/lua/xml.h
- src/trivia/config.h.cmake
- test/app-luatest/gh_7311_malloc_info_test.lua
- test/app-luatest/xml_test.lua
- test/box/misc.result
This commit adds two new Lua functions:
- `box.malloc.info()` is a public function that returns the total memory usage of internal data structures allocated with [`malloc()`][1]. This information is extracted from the [`malloc_info()`][2] output.
- `box.malloc.internal.info()` is an internal function that returns a parsed XML document returned by `malloc_info()` as is. It isn't documented. We may need it to get the detailed information about the system memory allocator.
Both functions are available only on Linux and only if ASAN is disabled because otherwise `malloc_info()` is unavailable. On other platforms `box.malloc.info()` reports zero memory usage while `internal.info()` returns an empty table.
Both functions may be used before `box.cfg()` is called.
`box.malloc.info()` returns a …
> lua: add malloc info

- test/app-luatest/gh_8445_crash_during_crash_report_test.lua
The test was disabled in master and 2.11 due to #8572.
That issue is not applicable to 2.10, hence `gh_8445_crash_during_crash_report_test.lua` can be enabled.
> [2.10] test: don't skip gh_8445_crash_during_crash_report_test.lua on AArch64 Linux

- changelogs/unreleased/gh-7356-populate-index-with-keydef.md
- src/box/lua/key_def.c
- src/box/lua/key_def.h
- src/box/lua/merger.c
- src/box/lua/space.cc
- test/box-luatest/gh_7356_index_parts_methods_test.lua
- test/box-tap/key_def.test.lua
**box: populate index_object.parts with key_def module methods**
This patch adds 4 methods of the `key_def` module instance to the
`index_object.parts`, see the docbot request for details. The rest
methods (`new()` and `totable()`) are not applicable here, because the
instance is already created and pushed to the stack as a table.
Title: `index_object.parts` methods
Product: Tarantool
Since: 3.0
Root document: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_index/parts/
`index_object.parts` has the following methods: `extract_key()`, `compare()`, `compare_with_key()`, `merge()`.
For their description and usage examples, refer to [Module key_def](https://www.tarantool.io/en/doc/latest/reference/reference_lua/key_def/#lua-object.key_def.key_def_objec …
> box: populate `index_object.parts` with `key_def` module methods

- src/box/applier.cc
- src/box/applier.h
- src/box/box.cc
- src/box/iproto.cc
- src/box/lua/load_cfg.lua
- src/box/memtx_engine.cc
- src/box/replication.cc
- src/box/replication.h
- src/lib/core/evio.c
- src/lib/core/evio.h
- src/lib/core/iostream.c
- src/lib/core/iostream.h
- src/lib/core/ssl.h
- src/lib/uri/uri.c
- src/lib/uri/uri.h
- test/unit/uri.c
Currently, `box.cfg` doesn't call an option handler if the option value is unchanged (in Lua). This means that
```Lua
box.cfg{listen = box.cfg.listen}
box.cfg{replication = box.cfg.replication}
```
are no-ops. Since paths to SSL certificate files are stored in URI parameters, this means that one can't reload SSL certificate files by resetting the configuration to the same values, which is inconvenient.
We tried to unconditionally call the option handler even if the old and new option values are the same, see #8552, but this broke some integration tests. In particular, it broke vshard tests, as explained in https://github.com/tarantool/tarantool/issues/8551#issuecomment-1505503984, so we refused from this approach.
In this PR, apart from removing the Lua `box.cfg` check, we also patch the …
> Always reload URIs when listen/replication is reconfigured

- src/box/replication.cc
In case `box.cfg.replication` isn't update by `box.cfg`, we don't try to reestablish replication connections, but we still need to reload URIs (recreate IO stream contexts created from URIs) because a URI parameter may store a path to an SSL certificate file, which could change. This was done in commit 655290aa7a8b3 ("replication: always reload URIs on reconfiguration").
There's a bug in the commit: it works as expected for appliers that already connected in the past and received UUID but it ignores anonymous appliers, i.e. appliers that never connected, as a result the following code fails:
```Lua
-- Configure replication using a wrong SSL certificate.
-- This leaves anonymous appliers reconnecting in the background.
box.cfg{replication = {...}}
-- Update the SSL certificate file and …
```
> replication: reload URIs of anon replicas on reconfiguration

- test/replication-luatest/linearizable_test.lua
The test flaked a lot on FreeBSD and Mac OS due to some proxy problems which were fixed in scope of tarantool/luatest@5b704ac.
Another possible failure looked like this:
NO_WRAP
[006] not ok 5  linearizable-read.test_leader_change
[006] #   Can't modify data on a read-only instance - it is an orphan
[006] #   stack traceback:
[006] #         ...tarantool/test/replication-luatest/linearizable_test.lua:196: in function 'linearizable-read.test_leader_change'
[006] #         ...
[006] #         [C]: in function 'xpcall'
NO_WRAP
Fix it by waiting for the server to follow its upstreams.
Closes tarantool/tarantool-qa#277
> test: re-enable linearizable test after fix

- .github/workflows/lango-stale-reviews.yml
- tools/stale_pr_date_setter.py
This patch adds a Python script, that uses GitHub's GraphQL API to provide automatic last update date for PR items on any specified GitHub ProjectsV2 board.
Since there is no versatile enough  way to automate a GitHub ProjectV2 by its own means, that is done via standard mechanism of on schedule workflow, which runs the script every hour.
NO_DOC=workflow
NO_TEST=workflow
NO_CHANGELOG=workflow
> workflow: add stale PR last update setter

- src/box/lua/key_def.c
There was a typo in the commit 55295f5f1be7 ("box: populate index_object.parts with key_def module methods"):
the function `luaT_push_key_def()` was erroneously used instead of `luaT_push_key_def_nodup()`.
> box: fix memory leak in `lbox_key_def_new` and `luaT_key_def_merge`

- .github/workflows/lango-stale-reviews.yml
The setup-python action defaults to searching for
a dependency file (requirements.txt or pyproject.toml for pip, Pipfile.lock for pipenv or poetry.lock for poetry) in the repository, and uses its hash as a
part of the cache key. We don't have one, so the
caching option is disabled.
NO_DOC=Workflow fix
NO_TEST=Workflow fix
NO_CHANGELOG=Workflow fix
> ci: fix PR update timestamp setter

- test/replication/qsync_advanced.result
- test/replication/qsync_advanced.test.lua
- test/replication/suite.ini
Add necessary wait for replication to appear on the replica/master,
remove the test from the fragile list.
Closes tarantool/tarantool-qa#292
> flaky: fix the qsync_advanced test

- changelogs/unreleased/gh-8393-iproto-watch-sync.md
- src/box/iproto.cc
- src/box/iproto_constants.h
- src/box/session.c
- src/box/session.h
- src/box/xrow.c
- src/box/xrow.h
- test/box-py/iproto.result
- test/box-py/iproto.test.py
Initially the sync number sent by a client in an `IPROTO_WATCH` request was ignored and `IPROTO_EVENT` packet didn't have a sync number. There were complaints about it from users so we consider this to be a bug. Now the server sends the same sync number in an `IPROTO_EVENT` packet as the one sent by the client in the last corresponding `IPROTO_WATCH` request.
We don't use this functionality in net.box (sync number is always 0 for all watch/event packets), but other clients may actually use it.
Closes #8393
> iproto: send `IPROTO_WATCH` sync number in `IPROTO_EVENT` packet

- changelogs/unreleased/gh-8530-alter-space-snapshot-fix.md
- src/box/alter.cc
- src/box/memtx_tx.c
- src/box/space.c
- src/box/space.h
- test/box-luatest/gh_8530_alter_space_snapshot_test.lua
With MVCC off (`box.cfg.memtx_use_mvcc_engine = false`), a memtx space read view may include a dirty (not committed to WAL) record. To prevent such records from being written to a snapshot, we sync WAL after creating a read view for a snapshot. The problem is that it doesn't work for long (yielding) DDL operations, such as building a new index, because such operations yield before waiting on WAL. As a result, a dirty DDL record may make it to a snapshot even though it may fail eventually. To fix that, let's keep track of all yielding DDL statements and exclude them from a read view using the memtx snapshot cleaner.
Closes #8530
> box: exclude uncommitted alter records from snapshot

- changelogs/unreleased/gh-8583-fix-datetime-set-with-nsec.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
This patch fixes a case when timestamp is passed to datetime.set function at the same time with nsec, usec or msec. It works fine for datetime.new but some logic was missed for set function. Here we fix that and introduce a test.
Closes #8583
> datetime: fix error when timestamp is set with nsec/usec/msec

- changelogs/unreleased/gh-8509-bootstrap-strategy-supervised.md
- src/box/alter.cc
- src/box/alter.h
- src/box/applier.cc
- src/box/applier.h
- src/box/box.cc
- src/box/box.h
- src/box/lua/ctl.c
- src/box/replication.cc
- src/box/replication.h
- src/box/schema.cc
- src/box/schema_def.h
- test/replication-luatest/bootstrap_strategy_test.lua
This commit adds another possible bootstrap_strategy to accompany "auto" and "config": "supervised".
Such a strategy may be useful to pin the desired bootstrap leader on an active cluster (so that the user may join the replicas from the desired node without changing their box.cfg) or to manually set the bootstrap leader among the nodes that managed to start without issues.
More details are in the docbot request.
Closes #8509
Title: new bootstrap strategy - "supervised"
The `bootstrap_strategy` configuration option may now be set to "supervised".
This strategy works as follows:
When bootstrapping a new replicaset, the nodes do not choose a bootstrap leader and wait for it to be appointed by the user: the user may appoint a bootstrap leader by calling …
> replication: add bootstrap_strategy "supervised"

- changelogs/unreleased/gh-8570-fix-datetime-str-negative-nsec.md
- src/lib/core/datetime.c
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
> datetime: fix cases when datetime nanoseconds could be represented incorrectly

- .github/workflows/lango-stale-reviews.yml
Default token for actions provided by GitHub lacks read and write permissions for private projects. This commit changes the token used for the stale PRs workflow to the dedicated token with needed permissions.
NO_DOC=Workflow fix
NO_TEST=Workflow fix
NO_CHANGELOG=Workflow fix
> ci: dedicated token for Lango stale PRs

- changelogs/unreleased/gh-8433-raft-is-candidate.md
- src/box/replication.cc
- test/replication-luatest/gh_8433_raft_is_candidate_test.lua
This is a backport of #8506 to 2.10.
Currently on applier death `is_candidate` is updated after trying to start election. So, raft assumes it has healthy quorum and bumps term even when there's not enough healthy nodes to do that.
Trigger on updating above-mentioned flag is run in `replicaset_on_health_change`. So, let's move it before executing `raft_notify_is_leader_seen`, which tries to start election.
Closes #8433
NO_DOC=bugfix
(cherry picked from commit f077ebf60fde411e1d49eea7c8cb08c71d6e14b3)
> [2.10] raft: fix prevote with different replication_timeout

- changelogs/unreleased/gh-8604-support-square-brackets-in-procedure-resolution-for-lua-calls.md
- src/box/lua/call.c
- test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua
Fefactor lua name resolution, simplify and comment. Add an ability to specify path with brackets, for example in 'box.space[512]:get' or 'box.space["test"]:get'.
Only literals (strings and numbers) are supported.
Closes #8604
Title: square brackets in procedure resolution for Lua calls
Square brackets are now supported in Lua call procedure resolution. This is applicable to `net.box` connection objects `call` method as well as `box.schema.func.call`.
Examples of function calls with square brackets can be found in the test to this patch.
> box: support brackets in name resolution for Lua calls

- .github/workflows/integration.yml
The next major release of Tarantool (3.0.0) will not support Cartridge. So tet's be ready in advance. This patch removes the cartridge and crud integration test runs to make the integration tests pass for #8289.
> ci: rm cartridge and crud integration test runs

- src/box/sql/expr.c
This patch fixes the check for invalid negation, which was found by [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) in `box/sql/expr.c:3202`.
The error occurred because the value of `value` var can be equal to `INT64_MIN` (which is equal to `(uint64_t) INT64_MAX + 1`), and it won't be handled by corresponding check. To fix this it is enough just to change the check to `>=` instead of `>` to parse this value as well.
How to reproduce:
1. Build and run docker container from [here](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/tarantool):
sudo docker build -t oss-sydr-fuzz-tarantool
sudo docker run --rm --privileged -v `pwd`:/fuzz -it oss-sydr-fuzz-tarantool /bin/bash
2. Run target `/sql_fuzzer` on this input
[tarantool-neg.txt](https://github.com/tarantool/tarantool/files …
> sql: fix invalid negation.

- changelogs/unreleased/gh-8605-add-gethostname.md
- src/box/lua/info.c
- test/box-luatest/gh_8605_add_box_info_hostname_test.lua
- test/box/info.result
- test/box/info.test.lua
Hostname is a useful piece of information in state reports. So it was decided to add it to box.info.
Hostname is obtained on requested and is not cached.
Closes #8605
Title: Add hostname to box.info
This patch adds hostname to box.info, it can be useful e.g. to supplement various instance state reports. It is not cached and is requested on each call.
> box: add hostname to box.info

- changelogs/2.10.7.md
- changelogs/unreleased/fix-bootstrap-with-er-readonly.md
- changelogs/unreleased/gh-6126-retry-join-automatically.md
- changelogs/unreleased/gh-7590-replicaset-assert.md
- changelogs/unreleased/gh-8069-luajit-fixes.md
- changelogs/unreleased/gh-8393-iproto-watch-sync.md
- changelogs/unreleased/gh-8418-asserton-on-select-from-_space.md
- changelogs/unreleased/gh-8433-raft-is-candidate.md
- changelogs/unreleased/gh-8445-crash-during-crash-report.md
- changelogs/unreleased/gh-8516-luajit-fixes.md
- changelogs/unreleased/gh-8530-alter-space-snapshot-fix.md
- changelogs/unreleased/gh-8570-fix-datetime-str-negative-nsec.md
- changelogs/unreleased/gh-8583-fix-datetime-set-with-nsec.md
- changelogs/unreleased/gh-8606-static-build-enable-optimization.md
- changelogs/unreleased/gh-8661-assertion-in-xferOptimization.md
- changelogs/unreleased/ghs-119-too-long-mem-values.md
- changelogs/unreleased/ghs-121-too-big-buffer-size.md
- changelogs/unreleased/ghs-122-allocations-in-printf.md
Generate changelog for 2.10.7 release.
Also, clean changelogs/unreleased folder.
> Generate changelog for 2.10.7

- changelogs/unreleased/gh-8069-luajit-fixes.md
- changelogs/unreleased/gh-8516-luajit-fixes.md
Just a regular backport of #8683 via a pull request to verify changes.
> [2.11] test: bump test-run to new version

- changelogs/unreleased/gh-5279-system-space-removal.md
- src/box/alter.cc
- test/box/alter.result
- test/box/alter.test.lua
The patch adds a new check to the _space on_replace trigger failing on attempt to drop a system table.
Closes #5279
NO_DOC=bugfix
**PROBLEMS**
1. The check duplicates the one in the _index on_replace trigger: [src/box/alter.cc](https://github.com/tarantool/tarantool/blob/93b3bba9bf907f9199f31d4071b0e3a5616a243a/src/box/alter.cc#L2335). But if we remove it then we gonna have to fix a lot of tests checking system space drop, because removal of an entry from the _space space happens only after index drop: [src/box/lua/schema.lua](https://github.com/tarantool/tarantool/blob/1e02e0506f89f01d386fdaaed01ca04c54943de5/src/box/lua/schema.lua#L911), so the removal of the check invalidates the system space we attempted to drop making the lua code remove indexes of the space.
**OTHER POSSIBLE …
> box: do not allow to drop system spaces

- changelogs/unreleased/gh-8497-promote-atomic.md
- changelogs/unreleased/gh-8698-spurious-split-vote.md
- src/lib/raft/raft.c
- test/replication-luatest/gh_6036_qsync_order_test.lua
- test/replication-luatest/gh_8497_atomic_promote_test.lua
- test/replication/election_basic.result
- test/replication/election_basic.test.lua
- test/unit/raft.c
Fix a couple of bugs regarding election stability:
1. Make candidates write and broadcast term and vote for self atomically. This reduces possible split-vote scenarios where other candidates vote for themselves unnecessarily.
2. Do the same for `box.ctl.promote()`
3. Fix a bug in split-vote detector.
Closes #8497
Closes #8698
> Improve election stability and reproducibility

- test/app-luatest/http_client_test.lua
We'll enable it when #8718 is fixed.
> test: disable Lua JIT in `app-luatest/http_client_test`

- changelogs/unreleased/gh-7991-relay-crash.md
- src/box/relay.cc
All the code outside of relay.cc judges about relay's liveliness looking
only at relay state. When relay->state is RELAY_FOLLOW, the relay is
considered operational.
This is not always true: for example, both relay_push_raft() and
relay_trigger_vclock_sync() are only possible after relay thread pairs
with tx via the cbus. This happens **after** the relay enters
RELAY_FOLLOW state.
Fix the possible access to uninitialized cpipe by
relay_trigger_vclock_sync(): make it a nop until the relay is paired
with tx.
Closes #7991
> Fix access to uninitialized cpipe between tx and relay

- test/helper.lua
- test/metrics-luatest/helper.lua
- test/replication-luatest/bootstrap_strategy_test.lua
- test/replication-luatest/linearizable_test.lua
Direct call and configuration of the runner instance is prohibited. Now if you need to test something with specific configuration use a server instance please (see luatest.Server module).
In-scope-of tarantool/luatest#245
NO_DOC=ban calling box.cfg
NO_TEST=ban calling box.cfg
NO_CHANGELOG=ban calling box.cfg
> test: ban direct calling of box.cfg()

- test/helper.lua
- test/metrics-luatest/helper.lua
- test/replication-luatest/linearizable_test.lua
Just a regular backport of #8709 via a pull request to verify changes.
> [2.11] test: ban direct calling of box.cfg()

- .github/actions/environment/action.yml
- .github/workflows/publish-module-api-doc.yaml
After this patch, the workaround for LuaJIT profiling tests to avoid runner's shutdown due to no space left on the disk is going to be used in all relevant workflows. Previously, we applied it only for the coverage test, but we noticed that other jobs may be affected as well after tarantool/tarantool#8737 is merged.
Follows up tarantool/tarantool#7472
> ci: use workaround for LuaJIT profiling tests in all workflows

- src/box/replication.cc
- test/replication-luatest/gh_8675_applier_pause_assert_test.lua
Clear applier on_state triggers before stopping appliers due to configuration failure in replicaset_connect().
This is needed to prevent triggers from running during applier_stop(), when cleaning up after a configuration error.
Closes #8675
NO_CHANGELOG=wasn't released
NO_DOC=bugfix
> replication: fix assertion failure on unsuccessful configuration

- changelogs/unreleased/gh-8539-bootstrap-leader-name.md
- src/box/box.cc
- src/box/iproto_constants.h
- src/box/replication.cc
- src/box/replication.h
- src/box/xrow.c
- src/box/xrow.h
- test/box-luatest/builtin_events_test.lua
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/replication-luatest/bootstrap_strategy_test.lua
Make it possible to specify the bootstrap leader via an instance name in addition to its URI and UUID.
Closes #8539
Title: `box.cfg.bootstrap_leader` accepts instance names now
The option `box.cfg.bootstrap_leader`, which specifies the desired bootstrap leader when bootstrap_strategy is "config" now accepts instance names.
For example, this is a valid config without replication:
```lua
box.cfg{
instance_name = 'main-server',
bootstrap_strategy = 'config',
bootstrap_leader = 'main-server'
}
```
When `box.cfg` contains some entries in `replication`, the node will bootstrap from whatever node which has its `box.cfg.instance_name` set to the same value as specified in `box.cfg.bootstrap_leader`.
This is an addition to tarantool/doc#3432
> replication: allow to pass instance name as bootstrap_leader

- .github/workflows/submodule_update.yml
Fix the `test-sdk` job in the `submodule_update.yml` workflow according to the new name policy for supported branches (2.10 -> release/2.10, 2.11 -> release/2.11).
> ci: fix test-sdk job in submodule_update.yml

- src/box/xrow_update_array.c
- src/lib/salad/rope.h
- test/unit/rope.c
- test/unit/rope.result
- test/unit/rope_basic.c
- test/unit/rope_basic.result
- test/unit/rope_common.h
- test/unit/rope_stress.c
- test/unit/rope_stress.result
We are going to use rope for representation of string field on tuple update. It will help to handle multiple updates of the same string field in the single update operation.
Currently rope erase operation can only remove single element at a time which make erase complexity `S*log2(N)`. Here `S` is number or deleted elements and `N` is number of nodes in the rope. This patch changes rope API to delete given number of elements at a time. Now complexity is `K*log2(N)` when `K` is number of nodes where deleted elements resides.
Note that implementation is still suboptimal for the case when deleted elements reside in more then a single node. First the implementation searches every next node from the root of the tree. Second the balancing rotations are performed on every node deletion.
As for …
> salad: make rope_erase erase more then a single element

- .github/workflows/lango-stale-reviews.yml
If one uses mail notifications about failed ci workflows, he can see tons of the following notifications for his fork of Tarantool: 
`[Buristan/tarantool] Run failed: lango-stale-reviews - master`
This job failed due to unknown credentials.
This patch adds the condition to run this workflow only for main Tarantool repo.
NO_DOC=Workflow fix
NO_TEST=Workflow fix
NO_CHANGELOG=Workflow fix
> ci: restrict Lango stale PRs workflow

- test/box-tap/gh-5602-environment-vars-cfg.result
Bump test-run to new version with the following improvements:
- lint: update flake8 to 5.* [1]
- app: write test output directly to files [2]
- app: disable stdout bufferization [3]
- luatest: fix luatest command description [4]
- luatest: split stdout and stderr [5]
- luatest: write stdout to a file directly [6]
- luatest: drop a dead code [7]
- luatest: disable stdout buffering [8]
- Prettify messages about log files [9]
[1] tarantool/test-run@4916351
[2] tarantool/test-run@7b3c003
[3] tarantool/test-run@48ccad8
[4] tarantool/test-run@2756eb2
[5] tarantool/test-run@3dab8dc
[6] tarantool/test-run@0c24557
[7] tarantool/test-run@036e6b6
[8] tarantool/test-run@e65a5f8
[9] tarantool/test-run@7a1ec4f
> test: bump test-run to new version

- changelogs/unreleased/gh-8157-default-field-value.md
- src/box/CMakeLists.txt
- src/box/errcode.h
- src/box/field_def.c
- src/box/field_def.h
- src/box/request.c
- src/box/request.h
- src/box/space.c
- src/box/sql.c
- src/box/sql/build.c
- src/box/sql/insert.c
- src/box/sql/pragma.c
- src/box/sql/show.c
- src/box/tuple_builder.c
- src/box/tuple_builder.h
- src/box/tuple_format.c
- src/box/tuple_format.h
- test/box/error.result
- test/engine-luatest/gh_8157_default_field_value_test.lua
- test/unit/CMakeLists.txt
- test/unit/tuple_builder.c
Now a field can be assigned a default value in the space format. When a new tuple is inserted into a space, and some of the fields contain null values, those fields will be filled with their respective default values.
Closes https://github.com/tarantool/tarantool/issues/8157
Title: Document default field values
Root document: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/format/
The format clause contains, for each field, a definition within braces: `{name='...',type='...'[,is_nullable=...][,default=...]}`, where:
* the optional `default` value contains a default value for the field. Its type must be compatible with the field type. If default value is set, it is applied regardless of whether `is_nullable` is true or false.
Example:
```lua …
```
> box: support default field values in the space format

- changelogs/unreleased/gh-8716-pagination-invalid-after-pos-bug.md
- src/box/lua/schema.lua
- test/engine-luatest/pagination_test.lua
> box: fix typo in pagination `after` position option validation

- changelogs/unreleased/gh-8757-crash-on-bootstrap.md
- src/box/applier.cc
- test/replication-luatest/gh_8757_bootstrap_crash_test.lua
There was a problem in applier_wait_bootstrap_leader_uuid_is_set():
* it didn't set an error cause when the ballot watcher was dead, leading to a segfault when trying to diag_add() to the cause.
* it didn't expect the ballot watcher to exit without an error before the bootstrap leader uuid is known, hanging forever.
The first issue could be reproduced by trying to bootstrap a replicaset consisting of both "old" (Tarantool 2.10 or less) and "new" instances. Or by user intervetion, when the user manually broadcasts the "internal.ballot" event with no data during bootstrap.
The second issue could be reproduced only by manually broadcasting an empty "internal.ballot" event.
Fix both issues. The first one by setting an ER_UNKNOWN error when the ballot watcher fiber is dead. And the second one …
> replication: fix waiting for remote ballot updates during bootstrap

- changelogs/unreleased/gh-8704-wal-exit-empty-xlog.md
- src/box/wal.c
- test/box-luatest/gh_8704_extra_empty_xlog_on_exit_test.lua
- test/replication-luatest/gh_8675_applier_pause_assert_test.lua
After the commit a392eb765c12 ("box: destroy its modules even if box.cfg not done") wal_free() on exit is called even if box.cfg() isn't finished yet, and thus wal isn't yet enabled. This leads to a bug when wal would unconditionally write a 00...0.xlog regardless of the actual xlog directory contents or the actual vclock.
Let's fix this by not writing an empty xlog on exit if wal writer's vclock is zero. It means the writer either wasn't enabled yet, or was enabled, but hasn't written anything. In both cases writing the empty xlog is extraneous.
Closes #8704
NO_DOC=bugfix
> core: fix wal saving an empty xlog during startup failure

- changelogs/unreleased/gh-8704-wal-exit-empty-xlog.md
- src/box/wal.c
- test/box-luatest/gh_8704_extra_empty_xlog_on_exit_test.lua
After the commit a392eb765c12 ("box: destroy its modules even if box.cfg not done") wal_free() on exit is called even if box.cfg() isn't finished yet, and thus wal isn't yet enabled. This leads to a bug when wal would unconditionally write a 00...0.xlog regardless of the actual xlog directory contents or the actual vclock.
Let's fix this by not writing an empty xlog on exit if wal writer's vclock is zero. It means the writer either wasn't enabled yet, or was enabled, but hasn't written anything. In both cases writing the empty xlog is extraneous.
Closes #8704
NO_DOC=bugfix
(cherry picked from commit f78908c98c67d01440a76176f7faa24cc17735f6)
> [2.11] core: fix wal saving an empty xlog during startup failure

- .gitignore
- src/box/CMakeLists.txt
- src/box/lua/config/utils/log.lua
- src/box/lua/init.c
- test/config-luatest/log_wrapper_test.lua
- test/config-luatest/suite.ini
The future config module works with hierarchical data a lot and needs a way to show a table as a part a log message. The config module issues log messages at different log levels and it is undesirable to perform JSON encoding for messages that will be filtered out by the current log level.
It is complicated to achieve the goal using the `log` module. Let's add a wrapper as the temporary solution. The wrapper can be eliminated after solving the problems in the `log` module that are linked in the wrapper's code.
The wrapper also simplifies debugging of the config module itself.
> config: add logger wrapper with JSON encoding

- src/box/CMakeLists.txt
- src/box/lua/config/utils/schema.lua
- src/box/lua/init.c
- test/config-luatest/schema_test.lua
The module offers a schema definition format and provides a bunch of functions to validate and manipulate hierarchical data.
See the API description in #8725.
The module is part of the new declarative configuration initiative, see #8724.
This pull request doesn't add any public API: the module is for internal use and its API can be changed later.
Fixes #8725
> config: add schema-aware data processing module

- changelogs/unreleased/gh-8744-fix-chunked-with-content-length.md
- src/httpc.c
- src/httpc.h
- test/app-luatest/http_client_test.lua
- test/app-luatest/httpd.py
The description of CURLOPT_UPLOAD [1] is confusing:
If you use PUT to an HTTP 1.1 server, you can upload data without
knowing the size before starting the transfer if you use chunked
encoding. You enable this by adding a header like
"Transfer-Encoding: chunked" with CURLOPT_HTTPHEADER.
In fact, libcurl adds this header itself. Actually we need to avoid
adding this header by libcurl with CURLOPT_INFILESIZE [2].
The CURLOPT_UPLOAD documentation has been updated [3].
1. https://github.com/curl/curl/blob/555bacd6d522bcca497573765056354f4d5d7b33/docs/libcurl/opts/CURLOPT_UPLOAD.3
2. https://curl.se/libcurl/c/httpput.html
3. https://github.com/curl/curl/pull/11300
Closes https://github.com/tarantool/tarantool/issues/8744
NO_DOC=bugfix
> httpc: fix content-length with a stream

- changelogs/unreleased/gh-8326-mvcc-lost-gap-record.md
- changelogs/unreleased/gh-8648-mvcc-broken-rollback-of-prepared.md
- changelogs/unreleased/gh-8654-mvcc-abort-readers-of-prepared-and-rollbacked.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_space.c
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box-luatest/gh_8326_mvcc_lost_gap_record_test.lua
- test/box-luatest/gh_8648_memtx_mvcc_rollback_prepared_test.lua
- test/box/tx_man.result
- test/box/tx_man.test.lua
- test/engine-luatest/gh_8654_memtx_mvcc_abort_readers_of_prepared_test.lua
A huge refactoring of MVCC engine.
Closes https://github.com/tarantool/tarantool/issues/8654
Closes https://github.com/tarantool/tarantool/issues/8648
Closes https://github.com/tarantool/tarantool/issues/8326
(backport from master).
> Gh 8654 memtx mvcc abort readers of prepared 2.11

- .github/workflows/lango-stale-reviews.yml
This patch fixes the crontab expression in the
Lango team stale PRs workflow, so it runs not every minute, but every hour.
Also, python version is updated to 3.11, since the script is reliant onto `datetime.fromisoformat' changes, that were introduced in that version.
NO_DOC=Workflow fix
NO_TEST=Workflow fix
NO_CHANGELOG=Workflow fix
> ci: fix lango stale PRs workflow

- changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md
- test/app-luatest/gh_6128_background_mode_test.lua
**lua: fix crash on running in background mode**
Tarantool with background mode enabled via environment variable could lead a crash:
```
$ TT_PID_FILE=tarantool.pid TT_LOG=tarantool.log TT_BACKGROUND=true TT_LISTEN=3301 tarantool -e 'box.cfg{}'
$ tail -3 tarantool.log
2021-11-02 16:05:43.672 [2341202] main init.c:696 E> LuajitError: cannot read stdin: Resource temporarily unavailable
2021-11-02 16:05:43.672 [2341202] main F> fatal error, exiting the event loop
2021-11-02 16:05:43.672 [2341202] main F> fatal error, exiting the event loop
```
Patch fixes a crash.
**src: disable raise in cfg**
Needed for #6128
**lua: use https protocol in a crash report message**
-------
Other testcases were tested too:                                                 
``` …
```
> Fix start of Tarantool with passed TT_BACKGROUND=true

- changelogs/unreleased/gh-8733-ddl-memory-leaks.md
- src/box/memtx_space.c
> box: fix memory leaks on `ER_MULTISTATEMENT_TRANSACTION` in DDL

- src/box/CMakeLists.txt
- src/box/lua/func_adapter.c
- src/box/lua/func_adapter.h
- src/lib/core/func_adapter.h
- test/unit/CMakeLists.txt
- test/unit/lua_func_adapter.c
We are going to introduce universal triggers registry and use it for
tarantool triggers (e.g. space.on_replace). However, when trigger is set
to the registry, we do not know which arguments will be passed there
from C. That is why current implementation of triggers in tarantool is not
suitable for use in universal registry.
We decided to introduce func_adapter interface which allows to call
functions from any programming language. Now we support only one
language, which is Lua, so for the most part this interface is needed
to invert dependencies.
The patch introduces func_adapter interface and its implementation for
Lua functions.
Part of https://github.com/tarantool/tarantool/issues/8657
> core/lua: introduce func_adapter for Lua

- test/app-luatest/gh_6128_background_mode_test.lua
> test: fix for gh_6128 test to avoid flakiness

- changelogs/unreleased/gh-7873-func-priv-check.md
- src/box/alter.cc
- src/box/key_list.c
- src/box/tuple_constraint_func.c
- test/box-luatest/gh_7873_func_perm_check_test.lua
Function execution permissions should only be checked on functional index creation and on functional index function set. This is also true for constraints.
Closes #7873
> Do not check permissions on functions if functions are used in a constraint or in a function index

- changelogs/unreleased/gh-8782-yaml-decode-char-code-fix.md
- test/app-luatest/gh_8782_yaml_decode_char_code_test.lua
The bug was fixed in the libyaml repository by PR https://github.com/tarantool/libyaml/pull/3 This commit just updates the submodule and adds a test.
Closes #8782
> yaml: fix decoding single-byte char codes >= 0x80

- src/box/lua/config/init.lua
- src/box/lua/config/source/env.lua
- src/box/lua/config/source/file.lua
This patch reworks the way the meta is populated. This is done to incrementally populate the metadata, instead of set the metadata at the end of reading data from the source. This allows to get the correct meta in cases where getting data from the source failed.
Follow-up #8789
> config: rework the way the meta is populated

- changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md
- src/box/memtx_tx.c
When a space is altered, we abort all in-progress transactions and delete all stories related to that space: the problem is we don't delete the stories' read gaps, which are also linked to the stories' transactions, which get cleaned up on transaction destruction — this, in turn, results in heap-use-after-free. To fix this, clean up stories' read gap in `memtx_on_space_delete` — we don't do this in `memtx_tx_story_delete` since it expects the story to not have any read gaps (see `memtx_tx_story_gc_step`).
Tested this patch manually against Nick Shirokovskiy's experimental small-ASAN integration branch.
Closes #8781
NO_DOC=bugfix
NO_TEST=<already covered by existing tests, but was not detectable by ASAN>
(cherry picked from commit e1ed31bbe450c775d48d27055434cdd527338500)
> memtx: fix heap-use-after-free of tuple stories caused by space alter

- changelogs/unreleased/gh-7873-func-priv-check.md
- src/box/alter.cc
- src/box/key_list.c
- src/box/tuple_constraint_func.c
- test/box-luatest/gh_7873_func_perm_check_test.lua
Backport of m.kostoev/gh-7873-check-constraint-and-func-index-func-once
> Gh 7873 check constraint and func index func once 2.11

- test/app-luatest/gh_6128_background_mode_test.lua
**NOTE**: PR 2.10 - https://github.com/tarantool/tarantool/pull/8834
Previous attempt to fix flakiness in commit 6a2c73f8 ("test: fix flakiness in gh_6128_background_mode_test") used a constant buffer size in check_err_msg function. Tarantool 2.10 has a bit bigger log before a desired message that other versions of Tarantool and it leads to a this resulted in a truncated message ("entering the even" instead of "entering the event loop"). Patch replaces check_err_msg() implementation to grep_log used in luatest, it reads the whole log.
Also patch renames check_err_msg to check_msg, because "entering the event loop" is not an error message.
Follows up #6128
NO_CHANGELOG=fix test
NO_DOC=fix test
> [master] test: fix flakiness in gh_6128_background_mode_test (again)

- src/box/read_view.c
- src/box/read_view.h
See also EE-part: tarantool/tarantool-ee#489.
Follows-up #4693
> box: use format data instead of field def array in space read view

- changelogs/unreleased/gh-8516-luajit-fixes.md
* test: fix flaky <unit-jit-parse.test.lua>
* Fix use-def analysis for vararg functions.
* Fix use-def analysis for BC_VARG.
* Fix TNEW load forwarding with instable types.
* Fix memory probing allocator to check for valid end address, too.
* Another fix for lua_yield() from C hook.
* Fix lua_yield() from C hook.
* Fix saved bytecode encapsulated in ELF objects.
* x64: Fix 64 bit shift code generation.
* Fix canonicalization of +-0.0 keys for IR_NEWREF.
* test: add utility for parsing `jit.dump`
* test: split utils.lua into several modules
* test: rewrite lj-49-bad-lightuserdata test in C
* test: rewrite misclib-sysprof-capi test in C
* test: rewrite misclib-getmetrics-capi test in C
* test: introduce utils.h helper for C tests
* test: introduce module for C tests
* test: fix setting of …
> [backport/release/2.11] luajit: bump new version

- changelogs/unreleased/gh-8516-luajit-fixes.md
* test: fix flaky <unit-jit-parse.test.lua>
* Fix use-def analysis for vararg functions.
* Fix use-def analysis for BC_VARG.
* Fix TNEW load forwarding with instable types.
* Fix memory probing allocator to check for valid end address, too.
* Another fix for lua_yield() from C hook.
* Fix lua_yield() from C hook.
* x64: Fix 64 bit shift code generation.
* Fix canonicalization of +-0.0 keys for IR_NEWREF.
* test: add utility for parsing `jit.dump`
* test: split utils.lua into several modules
* test: rewrite lj-49-bad-lightuserdata test in C
* test: rewrite misclib-sysprof-capi test in C
* test: rewrite misclib-getmetrics-capi test in C
* test: introduce utils.h helper for C tests
* test: introduce module for C tests
* test: fix setting of {DY}LD_LIBRARY_PATH variables
* build: fix build …
> [backport/release/2.10] luajit: bump new version

- changelogs/unreleased/gh-7483-ignore-mpack-types.md
- src/box/field_def.c
- src/box/key_def.h
- src/box/tuple_bloom.c
- src/box/tuple_compare.cc
- src/box/tuple_hash.cc
- test/engine-luatest/gh_7483_insert_int_into_double_field_test.lua
- test/engine/insert.result
- test/engine/insert.test.lua
- test/sql-tap/cast.test.lua
- test/unit/msgpack.result
- test/vinyl/upsert.result
- test/vinyl/upsert.test.lua
**Overview**
Make double-formatted fields accept all integer and float values.
Make indices compare double key fields (being int, uint, float or double) as doubles.
Make indices hash double key fields (being int, uint, float or double) as doubles.
So we are able to insert any number into a double-formatted field and it's interpret by indices appropriately.
Closes https://github.com/tarantool/tarantool/issues/7483
Closes https://github.com/tarantool/tarantool/issues/5933
Unblocks https://github.com/tarantool/crud/issues/298
**Changes in tuple_compare.cc:**
Comparators cast any value placed in double key field to double and compare them as doubles.
Since now `mp_compare_double` casts any value placed in field to double it was renamed to `mp_compare_as_double` to not semantically conflict …
> box: compare and hash msgpack value of double key field as double

- changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md
- src/box/lua/console.lua
- test/box-luatest/gh_8817_bug_set_language_shared_test.lua
Before this fix, result of `\set language` is shared between clients via `console.connect`, despite the fact that clients have different `box.session.id`. Now the parameter of the selected language is stored by each client in his own `box.session.storage`.
Fixes #8817
> box: fix set language shared between clients via console.connect

- test/config-luatest/suite.ini
All the tests are independent and nothing prevents running them in parallel. The option to enable the parallel running was just forgotten.
Part of #8862
> test: run tests in config test suite in parallel

- changelogs/unreleased/gh-8861-cluster-config-error-message.md
- src/box/lua/config/init.lua
- test/config-luatest/reload_test.lua
Prior to this patch, if a cluster configuration was not present or an instance was not found in the configuration during a reload, the error would begin with 'Startup failure'. Now it starts with 'Reload failure' in these cases.
Part of https://github.com/tarantool/tarantool/issues/8862
> config: fix error message during reload

- changelogs/unreleased/gh-8861-vinyl-options.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patch introduces all remaining vinyl options that have not been introduced before.
Part of https://github.com/tarantool/tarantool/issues/8861
> config: introduce remaining vinyl options

- changelogs/unreleased/gh-8807-compat-is-new-old.md
- src/lua/compat.lua
- test/app-luatest/gh_7000_compat_module_test.lua
It used to be somewhat complicated to check the effective value of a compat option, because `<option_name>.current` could contain 'default' state.
This patch introduces helper functions that take care of that.
The following alternatives were considered:
* `compat.<option_name>.effective` - it is excessive in the presence if `current` and `default`, and is visible in serialization
* `compat.<option_name>.get()` - while it is a function, it does only half of the work required, user still has to compare result to 'new'
Closes #8807
Title: Add `:is_new/old()` helpers to tarantool.compat options
`compat.<option_name>.current` can be 'new', 'old' or 'default', thus when it is default there must be an additional check if `compat.<option_name>.default` is 'new'. It is …
> compat: add is_new and is_old to options

- changelogs/unreleased/gh-3680-export-all-luajit-public-symbols.md
- extra/exports
- test/app-luatest/gh_3680_export_all_luajit_symbols_test.lua
There was a little mess in exports file regarding LuaJIT symbols to be visible from Tarantool binary, so some functions (e.g. `<lua_tonumberx>` and `<lua_tointegerx>`) were hidden unintentionally. As a result of the patch almost all public LuaJIT symbols are exported from Tarantool binary; there are still several functions reasonably hidden (you can find the rationale around the corresponding cases in the test file).
Closes #3680
> exports: clean up LuaJIT public interfaces

- src/lua/compat.lua
- test/app-luatest/gh_7000_compat_module_test.lua
In the original patch https://github.com/tarantool/tarantool/commit/5f6d367c51f7545a940119e7a393baf982b80f3f ("compat: add is_new and
is_old to options") `compat.<option_name>:is_new()` and `:is_old()`
were introduced, but by mistake they contained different usage
messages. This patch updates `:is_new()` usage msg to more
informative one from `:is_old()`.
Follows up https://github.com/tarantool/tarantool/issues/8807
NO_CHANGELOG=changelog from 5f6d367 is valid
NO_DOC=doc from 5f6d367 is valid
> compat: fix err msg in compat.<option>:is_new()

- CMakeLists.txt
- changelogs/unreleased/add-fiber-stack-size-option-to-cmake.md
- cmake/SetFiberStackSize.cmake
- src/lib/core/fiber.c
- test/unit/fiber_stack.c
In scope of the commit https://github.com/tarantool/tarantool/commit/82f4b4a3b1fbf91cb9e048d76408973933fddec6 ("lib/core/fiber: Increase default stack size") the default value of fiber stack size is increased up to 512 Kb (you can find the reasons in the aforementioned commit message and in https://github.com/tarantool/tarantool/issues/3418 description).
Some of the tests in test/PUC-Rio-Lua-5.1-test suite in LuaJIT repo (e.g. some cases with deep recursion in errors.lua or pm.lua) have already been tweaked according to the limitations mentioned in https://github.com/tarantool/tarantool/issues/5782, but the crashes still occurs while running LuaJIT tests with ASan support enabled.
To make the testing routine more convenient, FIBER_STACK_SIZE option is introduced to Tarantool CMake …
> cmake: introduce FIBER_STACK_SIZE option

- test/fuzz/luaL_loadbuffer/luaL_loadbuffer_fuzzer.cc
- test/fuzz/luaL_loadbuffer/serializer.cc
- test/fuzz/luaL_loadbuffer/serializer.h
- test/static/corpus/luaL_loadbuffer/timeout-0952c452a9b293fbd1bb3ad989b4627976d27e97
- test/static/corpus/luaL_loadbuffer/timeout-337b9efb6b00c9363e9ca290cd09e8d7caba54bb
- test/static/corpus/luaL_loadbuffer/timeout-53c0a03d2fa042bda3c544569c387086295af2a5
- test/static/corpus/luaL_loadbuffer/timeout-5fef580e9368ed8fc12db09db214241d3c353377
- test/static/corpus/luaL_loadbuffer/timeout-7fa44b92f42baec7b4d5029123d005bf8e6ece19
- test/static/corpus/luaL_loadbuffer/timeout-81c222fd009c8604a860ab967143637f94276d68
- test/static/corpus/luaL_loadbuffer/timeout-8a7111c13961d300ba0d55fd9411e9a0f7b1b606
- test/static/corpus/luaL_loadbuffer/timeout-a0aa27253eafb4ab8c975ad981bdc013d85b8c21
- test/static/corpus/luaL_loadbuffer/timeout-a383120b323bf8da86fa78919f1f2999154c581e
- test/static/corpus/luaL_loadbuffer/timeout-b02e909f524a1990690994e84d6dbc93581c0557
- test/static/corpus/luaL_loadbuffer/timeout-b0e5846adaa872aedb8c142620b3a7775c785ea3
- test/static/corpus/luaL_loadbuffer/timeout-c0e43bf73dbe687a743986309beb9683ccac018e
- test/static/corpus/luaL_loadbuffer/timeout-c9a028495b4422da26c910b64f0249a69668de48
LuaJIT fuzzer used to stop due to timeout caused by infinite cycles and
recursions. Counters were introduced for every cycle and function to
address LuaJIT fuzzer timeouts.
The idea is to add unique counters for every cycle and function to
ensure finite code execution, if it wasn't already. For while, repeat,
for cycles, local and global named, anonymous functions, counters will
be initialized before the code generated from protobuf, and checked
in the first body statement. An entry point for the serializer was
created to count cycles and functions for counter initialization.
The idea was taken from a paper "Program Reconditioning: Avoiding
Undefined Behaviour When Finding and Reducing Compiler Bugs".
Link: https://www.doc.ic.ac.uk/~afd/homepages/papers/pdfs/2023/PLDI.pdf
I noticed that …
> test/fuzz: fix luaJIT fuzzer timeout

- changelogs/unreleased/gh-8852-vy-read-iterator-use-after-free-fix.md
- src/box/vy_history.c
- src/box/vy_history.h
- src/box/vy_read_iterator.c
A read source iterator stores statements in a `vy_history object` using `vy_history_append_stmt()`. If a statement can be referenced, it's reference counter is incremented. If it can't, i.e. it belongs to a memory source, it's stored in a `vy_history` object without referencing.
This works fine because memory sources are append-only. A problem arises only when we get to scanning disk sources. Since we yield while reading disk, a dump task may complete concurrently dropping the memory sources and possibly invalidating statements stored in the iterator history. Although we drop the history accumulated so far and restart the iteration from scratch in this case, there's still an issue that can result in a use-after-free bug in `vy_read_iterator_next()`.
The problem is that we access the …
> vinyl: fix use-after-free in `vy_read_iterator_next`

- changelogs/unreleased/gh-5616-temp-space-truncate-ro.md
- src/box/alter.cc
- src/box/box.cc
- src/box/box.h
- test/box-luatest/gh_5616_temp_space_truncate_ro_test.lua
- test/replication/anon.result
- test/replication/anon.test.lua
DML operations on temporary and local spaces can be performed even if the instance is in the read-only mode, but DDL operations (such as `alter`) are forbidden in this case[^1]. Technically, `truncate` is a DDL operation so initially it was forbidden as well. However, it should be safe to perform this operation on a temporary or local space because logically it only modifies the data stored in the space (like DML) and it isn't replicated (see #4263). So starting from Tarantool 2.11.1 we allow users to truncate temporary spaces in the read-only mode.
To achieve that, we bypass the read-only check for the `_truncate` system space in `box_process1()` and perform it in the `on_replace` system trigger instead, when we know which space is truncated.
Closes #5616
[^1]: …
> Allow to truncate temporary and local spaces in the read-only mode

- test/justrun.lua
This fixes gh_8613_new_cli_behaviour_test run with my custom .inputrc
(I use vi-cmd-mode-string/vi-ins-mode-string).
We already reset readline configuration in interactive_tarantool.lua.
Follows up ground works done for #7774
> test: reset readline configuration for justrun too

- changelogs/unreleased/gh-8878-interval-boundaries-fix.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
Before this patch, one couldn't create new datetime interval with boundary value from Lua. At the same time, it was possible to create such interval from Lua through addition and subtraction. C range verification allow to create boundary value intervals, error message also implies that they should be allowed. (See #8878 for more info.)
Closes #8878
NO_DOC=small bug fix
> datetime: allow boundary values for interval.new

- src/lua/utils.c
`api_check()` is LuaJIT internal assertion. To prevent inconsistency during internal assertion changing (for example during backporting) use glibc's `assert()` instead.
> lua: replace `api_check()` with `assert()`

- changelogs/unreleased/gh-8887-fix-interval-int64.md
- src/lib/core/mp_interval.c
- test/app-tap/datetime.test.lua
- test/unit/interval.c
It is possible for interval to have days, hours, minutes and seconds bigger than INT_MAX (or less than INT_MIN). Before this patch, msgpack decoding had failed to parse intervals with msgpack int64 and uint64. int64_t should be enough to store any value allowed for datetime intervals.
Closes #8887
NO_DOC=small bug fix
> msgpack: fix decoding intervals with int64

- .gitattributes
This improves diff hunk name detection. Needed for checkpatch to correctly detect if patched code belongs to a function.
> git: add diff=cpp attribute for C/C++ source files

- changelogs/unreleased/box-speed-up-select-with-pagination.md
- perf/lua/box_select.lua
- perf/lua/compare.lua
- src/box/lua/schema.lua
The `normalize_position()` internal function is called by select/pairs to prepare a position specified by the caller in the `options.after` argument to be passed to C over FFI. The function encodes the position passed as a table or a tuple in a temporary buffer obtained with `cord_ibuf_take()`. The problem is the cord buffer is already taken by the calling function (select/pairs) to encode the search key. As a result, `cord_ibuf_take()` allocates a new temporary buffer with malloc.
Let's avoid this extra buffer allocation by passing the taken buffer to `normalize_position()`. Let's also remove the out arguments because they are always set to `iterator_pos` and `iterator_pos_end` and instead set `iterator_pos` and `iterator_pos_end` directly. To make this behavior clear, we rename …
> box: speed up select/pairs with pagination by reusing ibuf

- src/box/box.cc
- src/box/relay.cc
- src/box/relay.h
- test/replication/anon_register_gap.result
- test/replication/anon_register_gap.test.lua
Currently if tarantool exits during relay's final join stage,
corresponding thread isn't terminated. This cause the flakiness
of the replicaset_ro_mostly.test.lua.
Let's make a pointer to a relay, which is started during final join
stage, in the replica structure and cancel it, if it exists, via
replication_free() alongside with the subscribe thread.
Closes https://github.com/tarantool/tarantool/issues/8082
Closes https://github.com/tarantool/tarantool-qa/issues/272
NO_DOC=not user-visible
NO_TEST=fix flaky test
NO_CHANGELOG=not user-visible
> relay: fix unterminated final_join thread

- .github/actions/pack-and-deploy/action.yml
- .github/workflows/static_build_packaging.yml
- .pack.mk
- static-build/make_packages.sh
Modify .pack.mk for deploying static packages. Change the CI/CD process for creating and publishing packages to the repository. 
This PR connected with https://github.com/tarantool/rws/pull/79. It is needed to support static packages by RWS.
> Modify CI/CD for static packages

- test/replication-luatest/gh_5568_read_only_reason_test.lua
The test has two groups, in front of each of which, a cluster is created. Sometimes, it fails on the first test in every group: either ro_reason is explicitly checked and it equals to `orphan`, not nil, or we try to write to a still read-only instance and get the error, that it's orphan.
The problem is the fact, that we don't wait until the connections are established in a cluster. Let's add waiting for full mesh in cluster creation.
Closes tarantool/tarantool-qa#320
> test: fix flakiness in gh_5568_read_only_reason

- src/box/applier.cc
Applier thread uses lsregion to allocate the messages for tx thread. The
messages are freed upon return to the applier thread using a
corresponding lsr_id.
Due to a typo, one of the lsregion allocations was made with a postfix
increment of lsr_id instead of the prefix one. Essentially, part of a
new message was allocated with an old lsr_id, and might be freed early
by a return of a previous message.
Fix this.
Closes https://github.com/tarantool/tarantool/issues/8848
NO_DOC=bugfix
NO_TEST=covered by asan in https://github.com/tarantool/tarantool/pull/8901
> applier: fix use after free

- changelogs/unreleased/gh-8861-security-options.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
The following box.cfg options were described in instance_config with defaults similar to ones in box.cfg:
* auth_type
* auth_delay
* disable_guest
* password_lifetime_days
* password_min_length
* password_enforce_uppercase
* password_enforce_lowercase
* password_enforce_digits
* password_enforce_specialchars
* password_history_length
Part of #8861
> config: add security section to schema

- test/app-luatest/http_client_test.lua
This patch reverts the temporary fix introduced in commit 53c94bc79ecfc0451bc3ffa57ffb88e3217671ff ("test: disable Lua JIT in app-luatest/http_client_test") since the issues with invalid traces generation for vararg functions are resolved, so JIT machinery can be enabled back then.
Follows up #8718
Relates to #8516
NO_DOC=test
> test: enable JIT back in app-luatest/http_client_test

- src/box/lua/config/init.lua
The instance config schema was modified in commit 8ee2b0d8c9a44 ("config: start singleton instance in RW by default"): the `database.rw` (boolean) parameter was replaced by the `database.mode` parameter (enum of `ro` and `rw`).
However, in the same commit, the default mode of an instance that is the only one in its replicaset was modified: it starts in the read-write mode by default. As result, the parameter is actually unneeded in the minimal configuration example.
These changes were not reflected in the 'instance not found' error message, which contains the minimal configuration example. It is fixed here.
Part of #8862
Follows up #8810
> config: fix 'instance not found' failure message

- static-build/cmake/AddDependencyProjects.cmake
Change BACKUP_STORAGE URL for static build in static-build/cmake/AddDependencyProjects.cmake. Change URL from hb.bizmrg.com to hb.vkcs.cloud.
> change BACKUP_STORAGE URL for static build

- .github/workflows/release_clang.yml
- .github/workflows/release_lto_clang.yml
- bump Clang version to 16 in release build testing
- bump Clang version to 16 in release build LTO testing
Closes https://github.com/tarantool/tarantool-qa/issues/317
Closes https://github.com/tarantool/tarantool-qa/issues/318
> ci: bump Clang version in release build testing

- src/box/lua/config/instance_config.lua
- src/box/lua/tuple.lua
- src/lua/compat.lua
- test/app-luatest/gh_7000_compat_module_test.lua
- Move the `is_old` and `is_new` compat option methods to a metatable.
- Use them where appropriate.
Follow-up #8807
> compat: follow-up `is_old` / `is_new`

- changelogs/unreleased/config-low-priority-env-source.md
- src/box/lua/config/init.lua
- src/box/lua/config/source/env.lua
- src/box/lua/config/source/file.lua
- test/config-luatest/sources_test.lua
The usual environment configuration source is useful for parametrized run:
```sh
TT_MEMTX_MEMORY=<...> tarantool --name <...> --config <...>
```
However, sometimes a user may need to set a default value, which doesn't rewrite one that is provided in the configuration. Now, it is possible to do using the environment variables with the `_DEFAULT` suffix.
```sh
TT_MEMTX_MEMORY_DEFAULT=<...> tarantool --name <...> --config <...>
```
This feature may be especially useful for wrappers that run tarantool internally with some default paths for data directories, socket files, pid file. We likely will use it in the `tt` tool.
Part of #8862
----
Tarantool EE part: https://github.com/tarantool/tarantool-ee/pull/504
> config: add low priority env source

- changelogs/unreleased/config-get-configuration-from-app.md
- src/box/lua/config/applier/app.lua
- src/box/lua/config/init.lua
- test/config-luatest/app_test.lua
- test/config-luatest/appliers_test.lua
- test/config-luatest/basic_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/helpers.lua
It is convenient to access configuration using `config:get()` from the application script (`app.file` or `app.module`).
However, before this commit, it was not possible, because the configuration was not considered as applied before the application script is loaded.
Now, the script loading is moved into the post-apply phase.
The resulting sequence of steps on startup/reload is the following.
* collect configuration information (from all the sources)
* \<if the previous step is failed, set `check_errors` status and break>
* apply the configuration (call all the appliers)
* \<if the previous step is failed, set `check_errors` status and break>
* \<set the new successful status: `ready` or `check_warnings`>
* call post-apply hooks (including application script loading)
* \<if the previous …
> config: allow to call config:get() from app script

- .test.mk
- asan/lsan.supp
- cmake/luajit.cmake
All LuaJIT related LSan warnings were suppressed in scope of the commit 985548e4815a4cd73beb33acc60cf354e6eadd01 ("asan: suppress all LSAN warnings related to LuaJIT") since all compiler flags tweaks were enclosed in LuaJIT CMake machinery. As a result of the commit in LuaJIT submodule tarantool/luajit@a86e376 ("build: introduce LUAJIT_USE_ASAN option") ASan and LSan support has been finally added to LuaJIT runtime, so it was decided to remove LSan suppressions for LuaJIT functions. Unfortunately, it was not so easy as it looked like.
At first, Lua global state is not closed properly at Tarantool instance exit (see `tarantool_free` in src/main.cc and `tarantool_lua_free` in src/lua/init.c for more info), so LSan false-positive leaks are detected (for more info, see #3071). Hence the …
> asan: enable ASan and LSan support for LuaJIT back

- changelogs/unreleased/gh-8861-metrics-options.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patch introduces all metrics configuration.
Part of #8861
NO_DOC=tarantool/doc#3544 links the most actual schema,
no need to update the issue.
> config: add metrics section to schema

- .github/workflows/release_asan_clang11.yml
- .test.mk
Remove hard-coded compiler version for the `test-release-asan` target in the .test.mk file.
> make: fix hard-coded compiler version in .test.mk

- changelogs/unreleased/gh-8926-popen-inherit-fds.md
- src/lib/core/popen.c
- src/lib/core/popen.h
- src/lua/popen.c
- test/app-luatest/popen_test.lua
The new option takes an array of file descriptor numbers that should be left open in the child process if the `close_fds` flag is set. If the `close_fds` flag isn't set, the option has no effect because in this case none of the parent's file descriptors are closed anyway.
The option may be useful for establishing a communication channel between a Tarantool instance and a process spawned by it with `popen.new`, for example, using `socket.socketpair`.
Closes #8926
> lua/popen: introduce `inherit_fds` option for `popen.new`

- changelogs/unreleased/gh-8946-foreign-key-disables-truncate.md
- src/box/alter.cc
- src/box/space_cache.h
- test/engine-luatest/gh_6436_complex_foreign_key_test.lua
- test/engine-luatest/gh_6436_field_foreign_key_test.lua
- test/engine-luatest/gh_8946_foreign_key_disables_truncate_test.lua
- test/sql/delete.result
- test/sql/delete.test.lua
In #7309 a truncation of a space that was referenced by foreign key from some other space was prohibited.
It appeared that this solution is too bothering since a user can't truncate a space even if he truncated referring space before that.
Fix it by allowing space truncate if referring spaces are empty.
Note that by design space truncate is implemented quite similar to space drop. Both delete all indexes, from secondary to primary. Since this patch allows deletion of the primary index (which is the action that actually deletes all data from the space), this patch changes the result of space drop too: the space remains alive with no indexes, while before this patch it remained alive with no secondary indexes but with present primary. In both cases the behaviour is quite strange and must be …
> box: loose truncate check in case of foreign key

- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
This should suppress the following coverity issues:
- https://scan7.scan.coverity.com/reports.htm#v39198/p13437/fileInstanceId=146712118&defectInstanceId=18978766&mergedDefectId=1563095
- https://scan7.scan.coverity.com/reports.htm#v39198/p13437/fileInstanceId=146712113&defectInstanceId=18978750&mergedDefectId=1563094
While we are at it, let's use `space_by_id` instead of `space_cache_find` because read view creation is a rare operation affecting all spaces so caching the last space by id doesn't make any sense.
> memtx: assert that space is not `NULL` in `index_read_view_create`

- changelogs/unreleased/gh-8946-foreign-key-disables-truncate.md
- src/box/alter.cc
- src/box/space_cache.h
- test/engine-luatest/gh_6436_complex_foreign_key_test.lua
- test/engine-luatest/gh_6436_field_foreign_key_test.lua
- test/engine-luatest/gh_8946_foreign_key_disables_truncate_test.lua
- test/sql/delete.result
- test/sql/delete.test.lua
In #7309 a truncation of a space that was referenced by foreign key from some other space was prohibited.
It appeared that this solution is too bothering since a user can't truncate a space even if he truncated referring space before that.
Fix it by allowing space truncate if referring spaces are empty. Also allow drop of the primary index in the same case with the same reason: logically the index along with all space data is not needed for consistency if there's no referring data.
Note that by design space truncate is implemented quite similar to space drop. Both delete all indexes, from secondary to primary. Since this patch allows deletion of the primary index (which is the action that actually deletes all data from the space), this patch changes the result of space drop too: the space …
> box: loose truncate check in case of foreign key 2.11

- changelogs/unreleased/gh-8946-foreign-key-disables-truncate.md
- src/box/alter.cc
- src/box/space_cache.h
- test/engine-luatest/gh_6436_complex_foreign_key_test.lua
- test/engine-luatest/gh_6436_field_foreign_key_test.lua
- test/engine-luatest/gh_8946_foreign_key_disables_truncate_test.lua
- test/sql/delete.result
- test/sql/delete.test.lua
In #7309 a truncation of a space that was referenced by foreign key from some other space was prohibited.
It appeared that this solution is too bothering since a user can't truncate a space even if he truncated referring space before that.
Fix it by allowing space truncate if referring spaces are empty. Also allow drop of the primary index in the same case with the same reason: logically the index along with all space data is not needed for consistency if there's no referring data.
Note that by design space truncate is implemented quite similar to space drop. Both delete all indexes, from secondary to primary. Since this patch allows deletion of the primary index (which is the action that actually deletes all data from the space), this patch changes the result of space drop too: the space …
> box: loose truncate check in case of foreign key 2.10

- changelogs/unreleased/gh-8936-foreign-keys-with-temporary-and-local.md
- src/box/alter.cc
- src/box/tuple_constraint_fkey.c
- test/engine-luatest/gh_8936_foreign_key_wrong_reference_test.lua
There must be a couple of rules:
* foreign key from non-temporary space to temporary space must be
forbidden since after restart all existing links will be broken.
* foreign key from non-local space to local space must be forbidden
on any replica all existing can be broken.
This patch implements the rules.
Closes #8936
> box: forbid foreign keys for incompatible temp/local spaces

- src/box/alter.cc
- src/box/box.cc
- src/box/iproto.cc
- src/box/user.h
- src/lib/core/coio_buf.h
- src/lib/core/fiber.h
- src/trivia/util.h
Small library currently depends on Tarantool core thru 'exception.h'. This is not the way to go. Let's drop this dependency and instead of moving _xc functions to Tarantool repo we can just stop using them. Our current policy is to panic on OOM in case of runtime allocation.
Part of #7327
> misc: get rid of small _xc functions

- changelogs/unreleased/gh-8927-socketpair.md
- src/lua/socket.lua
- test/app-luatest/socket_test.lua
This PR adds two socket module functions and one socket object method:
- `socket.from_fd(fd)`: constructs a socket object from the file descriptor number. Returns the new socket object on success. Never fails. Note, the function doesn't perform any checks on the given file descriptor so technically it's possible to pass a closed file descriptor or a file descriptor that refers to a file, in which case the new socket object methods may not work as expected.
- `socket:detach()`: like `socket:close()` but doesn't close the socket file descriptor, only switches the socket object to the closed state. Returns nothing. If the socket was already detached or closed, raises an exception.
Along with `socket.from_fd`, this method may be used for transferring file descriptor ownership from one socket …
> lua/socket: introduce `socket.from_fd`, `socket:detach`, `socket.socketpair`

- changelogs/unreleased/gh-8899-compare-with-key-slowpath-invalid-memory-access.md
- src/box/tuple_compare.cc
- test/box-luatest/gh_8899_tuple_compare_with_key_slowpath_last_loop_test.lua
Since number type was introduced we can not assume if tuples are equal by comparison then their sizes are equal too. So the place the assumption is used is fixed.
Closes #8899
NO_DOC=bugfix
> box: fix invalid memory access in tuple_compare_with_key_sequential

- changelogs/unreleased/gh-4544-segfault-if-i-delete-a-collation.md
- src/box/alter.cc
- src/box/coll_id.c
- src/box/coll_id.h
- src/box/coll_id_cache.c
- src/box/coll_id_cache.h
- src/box/errcode.h
- src/box/index_def.c
- src/box/index_def.h
- src/box/key_def.c
- src/box/lua/key_def.c
- src/box/space.c
- src/box/space.h
- src/box/sql/show.c
- test/box/net.box_is_nullable_gh-3256.result
- test/box/net.box_is_nullable_gh-3256.test.lua
- test/engine-luatest/gh_4544_collation_drop_test.lua
- test/sql-luatest/show_create_table_test.lua
- test/sql/collation.result
**box: reference collation by `key_def` parts**
It was possible to delete a collation, which is in use by a `key_def`.
---
**box: pin coll_id by space format and by indexes**
Pin in cache the collation identifiers that are referenced by space format and/or indexes, so that they can't be deleted.
Closes https://github.com/tarantool/tarantool/issues/4544
> Fix a crash when a collation, used by a space, is deleted

- changelogs/unreleased/config-help-env-list.md
- src/box/CMakeLists.txt
- src/box/lua/config/init.lua
- src/box/lua/config/source/env.lua
- src/box/lua/config/utils/schema.lua
- src/box/lua/config/utils/tabulate.lua
- src/box/lua/init.c
- src/lua/init.c
- src/lua/init.h
- src/main.cc
- test/box-py/args.result
- test/config-luatest/cli_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/schema_test.lua
- test/config-luatest/tabulate_test.lua
It lists environment variables that are taken into account by the config module.
Part of #8862
----
Current output is the following.
<details>
<summary>Click to expand.</summary>
| ENVIRONMENT VARIABLE                      | TYPE           | DEFAULT                         | AVAILABILITY       |
| ----------------------------------------- | -------------- | ------------------------------- | ------------------ |
| TT_INSTANCE_NAME                          | string         | N/A                             | Community Edition  |
| TT_CONFIG                                 | string         | nil                             | Community Edition  |
| ----------------------------------------- | -------------- | ------------------------------- | ------------------ |
| TT_APP_CFG …
> config: add `--help-env-list` CLI option

- changelogs/unreleased/gh-8802-box-session-push-deprecation.md
- src/box/box.cc
- src/box/errcode.h
- src/box/lua/session.c
- src/box/session.c
- src/box/session.h
- src/lib/core/say.h
- src/lua/compat.lua
- test/box-luatest/gh_8802_box_session_push_deprecation_test.lua
- test/box/error.result
The `box.session.push` Lua function and `box_session_push` C API function are deprecated starting from Tarantool 3.0. Calling any of these functions for the first time results in printing a warning message to the log.
The new compat module option `box_session_push_deprecation` was introduced to control whether the functions are still available. With the old behavior, which is the default in Tarantool 3.0, `box.session.push` is still available. With the new behavior, any attempt to use it raises an exception.
We are planning to switch the compat option to the new behavior starting from Tarantool 4.0 with the ability to revert to the old behavior. Starting from Tarantool 5.0 we are planning to drop `box.session.push` completely.
Closes #8802
> box: deprecate box.session.push

- src/lib/core/popen.c
The `popen_new()` function may be called with inherit_fds = NULL, nr_inherit_fds = 0. The lua/popen.c code actually does this.
It leads to the following memcpy() call.
```c
memcpy(dst, NULL, 0);
```
According to the C11 standard (n1256, 7.21.1), the pointer argument should have a valid value, which means pointing to some area in the program's address space, not NULL. The standard doesn't make an exception for a zero size array.
Personally I doubt that any memcpy() implementation attempts to dereference the source pointer in case of a zero size, but it is my assumption, while the standard is the standard.
The problem is found by Coverity.
Follows up #8926
> popen: fix memcpy(dst, NULL, 0)

- changelogs/unreleased/gh-8975-box-iproto-override-without-cfg.md
- src/box/box.cc
- src/box/box.h
- src/box/errcode.h
- src/box/lua/iproto.c
- src/box/lua/load_cfg.lua
- src/box/lua/session.c
- test/box-luatest/iproto_request_handlers_overriding_test.lua
- test/box/error.result
The function can't be called on an unconfigured instance because it needs IPROTO threads up and running. Let's raise an error to avoid a crash.
Since we have two other places where we need to raise the same error (`box.session.su` and `box.__index`), let's introduce the new code `ER_UNCONFIGURED` for this error.
Closes #8975
> box: fix `box.iproto.override` crash if used before `box.cfg`

- src/box/alter.cc
- src/box/box.cc
Coverity complained about a couple of places. The patch silences them.
> Silence coverity in instance names code

- changelogs/unreleased/ghqa-321-segfault-with-clang-16-asan.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
The `__sanitizer_start_switch_fiber()` function takes a pointer as the first argument to store the current fake stack if there is one (it is necessary when stack-use-after-return detection is enabled). When leaving a fiber definitely, `NULL` must be passed so that the fake stack is destroyed.
Before this patch, `NULL` was passed for dead fibers, however this is wrong for dead fibers that are recycled and resumed. In such cases ASAN destroys the fake stack, and the fiber crashes trying to use it in `fiber_yield()` upon return from `coro_transfer()`.
Closes tarantool/tarantool-qa#321
> core: fix `ASAN_START_SWITCH_FIBER()` usage

- changelogs/unreleased/gh-8801-iproto-session-from-fd.md
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/iproto.c
- src/box/lua/session.lua
- src/lib/core/cbus.c
- src/lib/core/cbus.h
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/box-luatest/gh_8801_iproto_session_from_fd_test.lua
- test/unit/cbus_call.c
The new function creates a new session given a table of options:
- `type`: string, optional. Default: "binary". [Type][session-type] of the new session. Currently, only "binary" is supported, which creates a new IPROTO session.
- `fd`: number, mandatory. File descriptor number (fd) to be used for the new connection input-output. The fd must refer to a [socket] and be switched to the [non-blocking mode][socket-nonblock] but this isn't enforced, i.e. the user may pass an invalid fd, in which case the connection won't work as expected.
- `user`: string, optional. Default: "guest". Name of the user to authenticate the new session as. Note, this doesn't prevent the other end to perform explicit [authentication].
- `storage`: table, optional. Default: empty table. Initial value of the …
> Introduce `box.session.new`

- changelogs/unreleased/gh-8899-compare-with-key-slowpath-invalid-memory-access.md
- src/box/tuple_compare.cc
- test/box-luatest/gh_8899_tuple_compare_with_key_slowpath_last_loop_test.lua
1. Since number type was introduced we can not assume if tuples are equal by comparison then their sizes are equal too. So the place the assumption is used is fixed. These changes has been taken from [#8922](https://github.com/tarantool/tarantool/pull/8922).
2. Partially applied the ca832f278855554f2741e54a997cece9bb7e2197 commit. Effectively it just introduced the `key_compare_and_skip_parts` function that is required for [#8922](https://github.com/tarantool/tarantool/pull/8922) and created the key_def test. Changes to the commit in details:
src/box/tuple_compare.cc:
- Omitted the `func_index_compare_with_key` update.
test/unit/key_def.c:
- Omitted four tests that checked the `func_index_compare_with_key` update.
> box: fix invalid memory access in tuple_compare_with_key_sequential (2.10 special)

- .gitignore
- changelogs/unreleased/gh-7593-console-debugger.md
- test/app-luatest/console_debugger_session_test.lua
- test/interactive_tarantool.lua
- third_party/lua/README-luadebug.md
- third_party/lua/luadebug.lua
Implemented readline history and autocomplete via reusing of Tarantool console readline facilities. They were hidden once Lua 'console' module loaded, now they kept visible as 'console_internal'.
Followup #7593 
Closes #7738
> debugger: proper readline support, step.3

- changelogs/unreleased/gh-8649-always-set-exclude_null-to-true-or-false.md
- src/box/lua/key_def.c
- test/box-luatest/gh_7356_index_parts_methods_test.lua
- test/box-tap/key_def.test.lua
- test/box/alter.result
- test/box/errinj.result
- test/box/gh-5998-one-tx-for-ddl.result
- test/box/lua.result
- test/box/misc.result
- test/box/rtree_misc.result
- test/box/tx_man.result
- test/engine/ddl.result
- test/engine/null.result
- test/sql/types.result
- test/vinyl/ddl.result
Currently the `exclude_null` field of `index_object.parts` is inconsistent between local `box` and `net.box` connection. It returns the following values:
- locally: true / null
- net.box: true / false
This mismatch makes it difficult to compare schemas on the storage and via the net.box connection on the router (see tarantool/crud#361).
Closes #8649
> box: always set `index.parts.exclude_null` to `true` or `false`

- src/trivia/util.h
- test/unit/guard.cc
`test/unit/guard.cc` calls `stack_break_f()` recursively until the stack overflows and a signal is fired, however it relies on undefined behavior when compares pointers to local variables. Fixed by comparing `__builtin_frame_address()` instead.
One of the examples of this UB is when ASAN allocates local variables on fake stacks, in that case the test completes without the stack overflow.
Also this patch disables ASAN for `stack_break_f()` to keep the array on the fiber stack (see the corresponding comment) and marks it as volatile to avoid optimizing it away by the compiler.
Closes tarantool/tarantool-qa#323
> test: fix fiber stack overflow test not overflowing

- changelogs/unreleased/gh-8861-config-privilege-sync.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/credentials_applier_test.lua
- test/interactive_tarantool.lua
Before this patch, credentials applier used to just grant all privileges and permissions with {if_not_exists = true}. It didn't allow removing a permission, nor setting only new permissions.
Now credentials applier converts box configuration and desired config to an intermediate representation, calculates diff for them and only after that applies the diff.
Part of #8967
NO_DOC=yet
> config: rework credentials to support priv sync

- changelogs/unreleased/config-dont-persist-group-name.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/basic_test.lua
- test/config-luatest/helpers.lua
We agreed that it is up to a user how to draw a line between one set of instances that is considered as a separate cluster and another set of instances that is assumed as a different cluster. This line is virtual and there is no sense to impose restrictions until we add some certain (and consistent) semantic to word 'cluster' in context of tarantool.
Part of #8862
> config: don't persist group name as cluster_name

- changelogs/unreleased/config-create-parent-directories.md
- src/box/lua/config/applier/mkdir.lua
- test/config-luatest/mkdir_test.lua
Before this patch an attempt to set, say, `wal.dir` option to a non-existent directory `foo` succeeds, while the same with `foo/bar` directory fails.
Part of #8862
> config: create parent directories in mkdir applier

- changelogs/unreleased/config-change-default-paths.md
- changelogs/unreleased/config-create-parent-directories.md
- changelogs/unreleased/config-lua-module-search-paths.md
- src/box/lua/config/applier/mkdir.lua
- src/box/lua/config/instance_config.lua
- src/main.cc
- test/config-luatest/appliers_test.lua
- test/config-luatest/basic_test.lua
- test/config-luatest/cli_test.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/helpers.lua
- test/config-luatest/instance_config_schema_test.lua
- test/config-luatest/mkdir_test.lua
This patchset accumulates a set of bug fixes and enhancements around tarantool directory layout.
* Parent directories are now created for `console.socket` and `log.file` when appropriate.
* `process.work_dir` is also created if provided.
* All the created directories are calculated relative to `process.work_dir` at startup and reload.
* The new `cartridge-cli` and `tt` inspired directory layout is in effect by default.
```
+ var/
+ lib/
+ instance-001/
- *.xlog
- *.snap
- *.vylog
+ log/
+ instance-001/
- tarantool.log
+ run/
+ instance-001/
- tarantool.control
- tarantool.pid
```
* Config's directory is added into Lua module search paths.
Part of #8862
> config: directory layout enhancements

- doc/examples/config/etcd/remote.yaml
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/instance_config_schema_test.lua
- test/interactive_tarantool.lua
The patches mostly add something that was forgotten in previous commits in regard to test cases that are run as part of Tarantool EE test suite.
See details in the commit messages.
Part of #8862
Part of #8967
> test/config: test suite fixes for Tarantool Enterprise Edition

- src/box/bind.c
- src/box/sql/mem.c
- src/lua/msgpack.c
- src/trivia/util.h
We have a few functions that decode MsgPack data assuming it was previously checked with `mp_check()`. This means it's safe to expect that `MP_EXT` contains valid data because we install a custom checker for `MP_EXT` in `msgpack_init`. So let's replace errors with assertions, removing the dead code.
> msgpack: remove dead code handling invalid MP_EXT

- src/box/alter.cc
- src/box/sql.h
- src/box/sql/select.c
- test/sql/view.result
- test/sql/view.test.lua
The function update_view_references is called when an SQL view
is created or dropped. The goal of this function is to modify
(increment or decrement) view_ref_count member of spaces that
the view references.
There were a several issues that deserves to be refactored:
* By design in case of error it left the job partially done, so
some space references were modified while some other - not.
Although there was no bug since special steps were made in case
of error, this pattern is inconvenient and should be avoided.
* In case of error the failing space name was returned via special
argument which is not flexible and even requires allocation.
* Another argument - suppress_error - has actually never
suppressed any error because the only case when an error could
occur is creation of a view, …
> sql: refactor update_view_references a bit

- .github/workflows/fuzzing.yml
- .github/workflows/publish-module-api-doc.yaml
Follows up https://github.com/tarantool/tarantool/pull/8904
Author: Sergey Bronnikov <sergeyb@tarantool.org>
Date:   Wed Aug 16 11:16:55 2023 +0300
ci: update paths in a workflows
When using the push and pull_request events, one can configure a
workflow to run based on what file paths are changed.
Fuzzing is a heavyweight job, we can reduce a set of paths used for
triggering this job. The patch replaces `.github/workflows/**` to
`.github/workflows/fuzzing.yml` because workflows are independent and
changes in other workflows does not affect fuzzing at all and patch adds
Lua files (`**.lua`) to ignores because fuzzing focused on C/C++ code.
Module API documentation is described in Doxygen comments in C/C++ files
in src. The patch changes paths in workflow accordingly.
See syntax of `paths` …
> ci: update paths in workflows

- changelogs/unreleased/gh-6860-demote-in-off-mode.md
- src/box/box.cc
- test/replication-luatest/gh_6842_qsync_applier_order_test.lua
- test/replication-luatest/gh_6860_election_off_demote_test.lua
box.ctl.demote() used not to do anything with election_mode='off' if the synchro queue didn't belong to the caller in the same term as the election state.
The reason could be that if the synchro queue term is "outdated", there is no guarantee that some other instance doesn't own it in the latest term right now.
The "problem" is that this could be workarounded easily by just calling promote + demote together.
There isn't much sense in fixing it for the off-mode because the only reasons off-mode exists are 1) for people who don't use synchro at all, 2) who did use it and want to stop. Hence they need demote just to disown the queue.
The patch "legalizes" the mentioned workaround by allowing to perform demote in off-mode even if the synchro queue term is old.
Closes #6860
NO_DOC=bugfix
> election: fix box.ctl.demote() nop in off-mode

- changelogs/unreleased/gh-8688-zero-part_count-crash.md
- src/box/alter.cc
- src/box/index_def.c
- src/box/key_def.c
- test/engine-luatest/gh_8688_wrong_index_parts_test.lua
`part_count` was checked in `index_def_check()`, which was called too late.
Before that check:
1. `malloc(sizeof(*part_def) * part_count)` can fail for huge `part_count`;
2. `key_def_new()` can crash for zero `part_count` because of out of bound access in:
```
- #1 key_def_contains_sequential_parts (def=0x5555561a2ef0) at src/box/tuple_extract_key.cc:26
- #2 key_def_set_extract_func (key_def=0x5555561a2ef0) at src/box/tuple_extract_key.cc:442
- #3 key_def_set_func (def=0x5555561a2ef0) at src/box/key_def.c:162
- #4 key_def_new (parts=0x7fffc4001350, part_count=0, for_func_index=false) at src/box/key_def.c:320
```
Closes #8688
> box: validate `key_def->part_count` prior to memory allocation

- changelogs/unreleased/gh-8656-trigger-registry.md
- src/box/CMakeLists.txt
- src/box/lua/func_adapter.c
- src/box/lua/func_adapter.h
- src/box/lua/init.c
- src/box/lua/trigger.c
- src/box/lua/trigger.h
- src/lib/core/CMakeLists.txt
- src/lib/core/event.c
- src/lib/core/event.h
- src/lib/core/func_adapter.h
- src/main.cc
- test/app-luatest/trigger_module_test.lua
- test/unit/CMakeLists.txt
- test/unit/event.c
- test/unit/lua_func_adapter.c
New module allows users to set arbitrary handlers on arbitrary events.
All the existing tarantool triggers will be moved to this module later.
**NB**: despite the fact that it was written that `set` method returns old trigger in the design document, I decided to do another way - `set` returns new trigger. Rationale: firstly, for the sake of consistency with `space:insert` which returns new tuple. Secondly, only with such API user can check if the trigger was set (we will introduce `trigger.on_change` trigger which will be able to throw an error to disallow to set the trigger, and ability of such check will be helpful then).
Closes https://github.com/tarantool/tarantool/issues/8656
> lua: introduce module triggers

- changelogs/unreleased/gh-8921-memory-leak-in-xrow_decode_error.md
- src/box/mp_error.cc
- test/unit/xrow.cc
Memory is leaked in the following scenario:
- `MP_ERROR_STACK` with 2 errors is passed to `error_unpack_unsafe()`:
1. A correct `MP_MAP` with `MP_ERROR_*` fields;
2. Something unexpected, e.g. `MP_INT`;
- This first call to `mp_decode_error_one()` allocates memory for the first error in `error_build_xc()` -> `new ClientError()`;
- The second call to `mp_decode_error_one()` returns `NULL`, and `error_unpack_unsafe()` returns `NULL` too. Memory from the previous step is leaked.
Closes #8921
> box: fix memory leak on `error_unpack_unsafe()` failure

- test/replication-luatest/gh_7515_sync_node_sees_leader_hang_test.lua
The test checks, whether the instance notices leader hang during sync. For that it stops server2 and generates some data on the master (server1). The problem is, when connection to server3 flakes, server1 resigns and becomes read only due to fencing enabled.
Let's disable fencing for this test, as we don't want automatic leader resigning here.
Closes tarantool/tarantool-qa#325
NO_DOC=test
> test: fix flaky gh_7515_sync_node_sees_leader_hang

- test/unit/CMakeLists.txt
- test/unit/bps_tree_view.c
- test/unit/crypto.c
- test/unit/event.c
- test/unit/json.c
- test/unit/lua_func_adapter.c
- test/unit/lua_utils.c
- test/unit/prbuf.c
- test/unit/raft.c
- test/unit/swim.c
- test/unit/swim_errinj.c
- test/unit/tuple_bigref.c
- test/unit/tweaks.c
- test/unit/unit.c
- test/unit/unit.h
- test/unit/vclock.cc
- test/unit/vy_mem.c
- test/unit/vy_point_lookup.c
- test/unit/xmalloc.c
- test/unit/xrow.cc
The main goal of this PR is to make the message argument of ok/is/isnt unit test helpers optional because it's really annoying to specify it after each check.
Along the way, it also does some cleanup:
- Removes duplicated code from `unit.h`.
- Adds missing trailing semicolons after ok/is/isnt.
> test: allow to omit message in ok/is/isnt unit test helpers

- .github/workflows/fuzzing.yml
Commit f14cb97d ("ci: update paths in a fuzzing workflow") breaks fuzzing workflow because one may only define one of `paths` and `paths-ignore` for a single event. The patch fixes that.
NO_DOC=ci
NO_TEST=ci
> ci: fix an error in workflow

- src/lua/msgpack.c
- test/unit/lua_msgpack.c
`*type_out` was set to uninitialized value for `field->type == MP_EXT`.
This was introduced by commit 9f9142d64289 ("box: cleanup on tuple encoding failure")
Closes #9023
> lua: fix uninitialized var usage in `luamp_encode_with_translation`

- changelogs/unreleased/gh-9020-fix-use-after-free-on-fiber-finish.md
- src/lib/core/fiber.c
When fiber region is freed/destroyed and ENABLE_BACKTRACE is set then `fiber_on_gc_truncate` callback is called. At this time both `used` argument and `fiber->gc_initial_size` are equal to 0. Thus `fiber->first_alloc_bt` is accessed which is already freed.
With a bad luck freeing fiber region can put slab back into slab arena. So writing after free can change memory used by another thread.
Closes #9020
> fiber: fix use-after-free on fiber destroy/recycle

- changelogs/unreleased/gh-9037-fix-heap-use-after-free.md
- src/box/iproto.cc
`msg` is used after it is freed in `iproto_msg_delete`.
Close #9037
> iproto: fix use-after-free in net_end_join

- changelogs/unreleased/gh-9026-fix-heap-buffer-overflow.md
- src/lib/core/fiber.c
- test/unit/fiber_stack.c
- test/unit/suite.ini
Fiber flags are initialized after fiber stack creation. As result currently check for custom stack in fiber_stack_watermark_create does not work. This leads to heap-buffer-overflow on putting watermark if custom stack size is less than `FIBER_STACK_SIZE_WATERMARK`.
Close #9026
> fiber: fix heap-buffer-overflow in fiber_stack_watermark_create

- test/box/tx_man.skipcond
For some unknown reason ASAN crashes with SIGSEGV on this test during shutdown.
See tarantool/tarantool-qa#324 for details.
> test: disable ASAN for `box/tx_man.test.lua`

- test/interactive_tarantool.lua
(Similar to PR #9060, but for the 2.10 branch.)
Cherry-picked the following changes from the master branch.
* 11dddb65d7ea1344d36f3239fc3422fd2792e6fe ("test: update interactive_tarantool for dbgr tests")
* 5053f286f8c5fca49a5e3428df3cfbc570e448d2 ("test: add roundtrip() to interactive_tarantool")
* 130335e43e95403d92edbb840bbcedc8e031fe23 ("test: accept env in interactive_tarantool.new()")
* 793713e655ddc9f952e819009ea79efe4eed2e74 ("test: add error rethrow to :read_response() in `it`")
It simplifies future backports of updates of the helpers and backports of updates of the tests that are using the helpers.
Note: The first commit has no much value in the 2.10 branch at the first glance, because there is no readline support in the interactive debugger and there is no the corresponsing …
> [backport 2.10] test: update interactive_tarantool helper

- .github/workflows/release_asan_clang.yml
- .github/workflows/release_lto_clang.yml
Run release build ASAN testing inside a Docker container created from the `tarantool/testing:ubuntu-jammy-clang16` Docker image with Clang 16 installed.
Closes https://github.com/tarantool/tarantool-qa/issues/319
> ci: bump Clang version to 16 in release build ASAN testing

- .github/workflows/release_asan_clang.yml
- .github/workflows/release_lto_clang.yml
- test/box/tx_man.skipcond
Just a regular cherry-pick of test/infra changes via a pull request to verify changes.
> [2.11] ci: bump Clang version to 16 in release build ASAN testing

- .github/workflows/packaging.yml
- .github/workflows/static_build_pack_test_deploy.yml
This patch finally brings desired testing for static build packages.
How it works:
In a few words, we have two workflow files: calling and callable. The
callable workflow (static_build_pack_test_deploy.yml) is parametrized
and contains all the logic with the building, testing, and deploying
packages. It takes just two inputs: package platform and JSON matrix
for testing. The calling workflow (packaging.yml) just runs callable
one with specific parameters and contains all the logic related to
triggering by events and concurrency.
The static_build_pack_test_deploy.yml workflow consists of three jobs:
`build`, `test`, and `deploy`. Artifacts between jobs are passed via
the `upload-artifact` and `download-artifact` actions. The `test` job
is a matrix one and verifies packages on provided …
> Add tests for static build to CI

- changelogs/unreleased/gh-8485-vy-tuple-stat.md
- src/box/vinyl.c
- src/box/vy_stmt.c
- src/box/vy_stmt.h
- test/vinyl-luatest/gh_8485_tuple_stat_test.lua
- test/vinyl/stat.result
- test/vinyl/stat.test.lua
Vinyl tuples returned to the user are allocated with `malloc`. They may be pinned by Lua indefinitely. Currently, there's no way to figure out how much memory is occupied by these tuples. This commit adds a statistic to `box.stat.vinyl()` that accounts them.
The new statistic is named `memory.tuple` and shows the total size of memory in bytes occupied by Vinyl tuples. It includes cached tuples and tuples pinned by the Lua world.
Closes #8485
> vinyl: add statistic for total size of memory occupied by tuples

- changelogs/unreleased/add-asan-flag-to-tarantool-build.md
- src/lua/init.c
- src/lua/init.lua
- src/lua/utils.c
- test/app-luatest/gh_7311_malloc_info_test.lua
- test/app-luatest/tarantool_package_test.lua
We already use this info in one of the test and going to use it more.
Let's also move initializing tarantool package before initializing other packages implemented in Lua. This way we will have access to build info in those packages. In particularly build.asan flag is going to be used in buffer.lua in scope of #7327.
Part of #7327
> lua: provide whether ASAN build in tarantool.build.asan

- test/wal_off/wal.lua
If a lot of tests are running in parallel, 50 sec limit may not be enough. Let's increase it to 120 sec.
Closes #7580
Closes tarantool/tarantool-qa#273
> test: increase maximum fiber slice for `wal_off` tests

- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/helpers.lua
- test/treegen.lua
When the configuration changes and the instance is reloaded with it,
some roles or users may be removed from the config. In such case,
it would be destructive to delete/disable them on the instance, so
this test checks that all users and roles removed in config stay
on the instance.
Part of #8967
> test/config: verify that user/role is not deleted

- test/fuzz/luaL_loadbuffer/serializer.cc
Revised:
1. The serializer no longer generates `return` and `break` statements without a corresponding function or loop, so they are now skipped.
2. The serializer was generating `else if` instead of `elseif`. Due to this typo, several errors occurred as a result of unclosed `if` statements.
I generated a set of 50,000 protobuf struct samples and tested the fuzzer on this set. Here are my results:
  | Before | After | Diff (% of errors of the kind)
-- | -- | -- | --
TOTAL | 27775 | 18294 | -34.14%
attempt to call | 5897 | 6963 | 18.08%
attempt to index | 4735 | 5790 | 22.28%
'for' initial value must be a | 1825 | 2820 | 54.52%
attempt to perform arithmetic on | 1636 | 1214 | -25.79%
attempt to compare | 524 | 502 | -4.20%
cannot use '...' outside a vararg function near '...' | 311 | 272 | …
> Lua fuzzer fixes (return and break statements)

- cmake/FindLibUnwind.cmake
This patch fixes the following warning:
```
CMake Warning (dev) at cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
The package name passed to `find_package_handle_standard_args`
(GetLIBUNWINDVersion.cmake) does not match the name of the calling package
(LibUnwind).  This can lead to problems in calling code that expects
`find_package` result variables (e.g., `_FOUND`) to follow a certain
pattern.
Call Stack (most recent call first):
cmake/FindLibUnwind.cmake:82 (find_package_handle_standard_args)
CMakeLists.txt:552 (find_package)
```
Closes #6998
> cmake: fix warning in `FindLibUnwind.cmake`

- test/replication-luatest/gh_7581_downstream_lag_test.lua
The test starts the cluster and immediately tries to create a space on master. Sometimes it fails with "Can't modify data on a read-only instance - it is an orphan" error.
When the instance is not in sync with sufficient number of nodes it has orphan status, which means the instance is read-only. Sometimes, the instance doesn't have enough time to connect to all instances and get out of orphan state.
Let's add waiting until every node is connected to every other node in the replica set.
Closes tarantool/tarantool-qa#326
NO_DOC=test
> test: fix flaky gh_7581_downstream_lag_test

- src/box/errcode.h
- test/box/net.box_iproto_transactions_over_streams.result
- test/engine-luatest/gh_6436_tuple_constraint_test.lua
- test/engine-luatest/gh_6986_c_constraint_test.lua
- test/engine-luatest/gh_7339_drop_fk_in_same_txn_test.lua
- test/engine-luatest/gh_7645_ck_fk_constraints_test.lua
- test/sql-luatest/constraint_test.lua
- test/sql-luatest/datetime_test.lua
- test/sql-luatest/interval_test.lua
- test/sql-luatest/sql_func_expr_test.lua
- test/sql-tap/alter2.test.lua
- test/sql-tap/check.test.lua
- test/sql-tap/decimal.test.lua
- test/sql-tap/table.test.lua
- test/sql-tap/uuid.test.lua
- test/sql/boolean.result
- test/sql/gh-2981-check-autoinc.result
The wording "Check constraint 'constr_name' failed for tuple" implies that the tuple should follow. This patch adds the missed "a" article.
Closes #9045
> box: improve error message for constraint violation

- changelogs/unreleased/gh-8931-box-info-election-leader-name.md
- src/box/lua/info.c
- test/replication-luatest/gh_8931_box_info_election_leader_name_test.lua
Prior to this patch, the table had no information about the leader other than his id in the "leader" field. It may not be convenient for the user to search for a name corresponding to a given id. Much more convenient to see the leader's name in box.info.election.
Closes #8931
Title: Document `box.info.election`
box.info.election now contains one more field: `leader_name`: string. There are several possible values ​​for this field:
- `nil`, if there is no leader in a cluster.
- `box.NULL`, if there is a leader, but he does not have a name.
- `some string`, if there is a leader and he has a name.
Example:
```console
tarantool> box.info.election
---
- leader_idle: 0
leader_name: node1
state: leader
vote: 1
term: 3
leader: 1
...
```
[box-info-election] …
> box: add "leader_name" field to the box.info.election

- changelogs/unreleased/gh-8967-creds-restore-defaults-for-default-user.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/credentials_applier_test.lua
All user-defined users and roles are not being removed and their privileges are not being revoked when this user or role is removed from config. This is done to prevent extreme repercussions of misconfiguration, e.g. empty config is provided to cluster and it breaks up.
Default users and roles are not supposed to be changed, so this rule does not apply to them. Now all of non-default privileges will be revoked if such user or role is removed from config.
Default users:
* guest
* admin
Default roles:
* super
* public
* replication
Part of #8967
> config: revoke privs for default users and roles

- changelogs/unreleased/gh-4265-printing-a-finished-fiber-stops-the-program.md
- src/lua/fiber.c
- test/app-luatest/fiber_test.lua
- test/app/fiber.result
- test/app/fiber.test.lua
An attempt to print a dead fiber raised a fatal error, which is quite unexpected.
This patch updates `__tostring` metamethod of `fiber_object` so that it pushes the `fiber: <fid> (dead)` string instead of the error. The `__serialize` metamethod is patched similarly.
Closes #4265
> lua/fiber: do not raise on printing a dead fiber

- changelogs/unreleased/gh-9098-out-of-bound-write-in-error_payload_destroy.md
- src/lib/core/error_payload.c
- src/lib/core/error_payload.h
- src/lua/error.lua
- test/unit/xrow.cc
If `strlen(name)` is 1, `value_size` is 1, and `extra` is 0, then 15 bytes are allocated for `struct error_field` in `error_payload_prepare()`. However, the size of this structure is 16 because of the padding for the alignment. Thus `TRASH()` in `error_payload_destroy()` writes 1 byte beyond the structure.
Closes #9098
> box: fix out of bound write in `error_payload_destroy()`

- test/fuzz/xrow_header_decode_fuzzer.c
On 2.10 branch xrow_header_decode_fuzzer fails with segmentation fault [^1] in diag.c:diag_get() due to a missed fiber structure. This happens in 2.10 only because commit 508138b79472 ("fiber: initialize thread-local cord on demand") was not backported to 2.10.
The patch adds initialization of fiber like we do in unit tests and thus fixes segmentation fault.
NO_DOC=testing
[^1]: https://github.com/tarantool/tarantool/actions/runs/6123773569/job/16623579367
> test/fuzz: fix xrow_header_decode_fuzzer

- changelogs/unreleased/gh-9049-schema-downgrade-replication.md
- src/box/alter.cc
- src/box/lua/upgrade.lua
- src/box/schema.cc
- src/box/schema.h
- test/replication-luatest/gh_9049_schema_downgrade_test.lua
Some downgrade operations are performed with disabled system space triggers because they were prohibited recently (creation of SQL built-in functions) or never allowed (dropping a system space). This works fine on the instance running downgrade but apparently fails on replicas.
To fix this issue, let's disable the checks the operations that prevent downgrade in the following scenarios:
- in the fiber that is currently running a schema upgrade or downgrade;
- in the applier fiber so that it can replicate changes done by upgrade or downgrade on the master;
- during recovery so that DDL records written to the WAL can be replayed.
We already have all the necessary infrastructure in-place - we use it for allowing DDL operations with an old schema for upgrade.
Closes #9049
> box: fix schema downgrade replication

- changelogs/unreleased/gh-9049-schema-downgrade-replication.md
- extra/exports
- src/box/alter.cc
- src/box/errcode.h
- src/box/lua/upgrade.lua
- src/box/schema.cc
- src/box/schema.h
- test/box/error.result
- test/replication-luatest/gh_9049_schema_downgrade_test.lua
Backport of #9092 to Tarantool 2.11.
NOTE: We don't have the commit that disables DDL operations with an old schema in 2.11 so we have to backport bits of it from 3.0, see commit 97c2c9a4fb58b ("box: disable DDL with old schema").
> [2.11] box: fix schema downgrade replication

- changelogs/unreleased/gh-7968-mp-check-diag.md
- src/box/mp_error.cc
- src/box/msgpack.c
- src/lib/core/exception.cc
- src/lib/core/exception.h
- src/lua/msgpack.c
- src/main.cc
- test/app-luatest/msgpack_test.lua
With this patch, `mp_check` sets diag with detailed information about the MsgPack decoding error. The diag includes the error reason, which is appended to the error message, and the data offset, which is stored in an error payload field. Possible error reasons are: truncated input, junk after input, illegal code, invalid extension. In case of truncated input, the error also includes the `trunc_count` payload field, which is set to the number of missing MsgPack values. Failing to decode a MsgPack
extension adds two payload fields, `ext_type` and `ext_len`, and also an error cause, which is set by the extension decoder. For all extensions except the error extension, the error cause is just "cannot unpack FOO". For the error extension, it includes a detailed cause pointing to the error in …
> lua/msgpack: add details to msgpack.decode error

- src/box/authentication.c
- src/box/error.cc
- src/box/error.h
- src/box/iproto.cc
- src/box/lua/func_adapter.c
- src/box/lua/session.c
- src/box/lua/trigger.c
- src/box/lua/trigger.h
- src/box/schema.h
- src/box/session.c
- src/box/session.h
- src/lib/core/func_adapter.h
- test/box-luatest/triggers_old_api_test.lua
- test/fuzz/sql_fuzzer/sql_fuzzer.cc
- test/unit/luaT_tuple_new.c
- test/unit/lua_func_adapter.c
- test/unit/tuple_format.c
The patch populates submodule session with an event for each public
trigger - they will be used for user-defined triggers. Old triggers are
not removed beacause they are used for internal purposes - audit from EE
uses them, for instance. Also, the commit introduces a test for all
triggers that use old API. It checks only session triggers now - all the
other triggers will be included there after they will be moved to the
trigger registry.
In order to have an opportunity to move user-defined triggers to trigger
registry, the commit introduces helper luaT_event_reset_trigger that
supports two different ways to set triggers - key-value API and positional
API. The first one is a new API that allows to set or delete trigger only
by name. The second API is implemented for the sake of backward …
> box: move session triggers to trigger registry

- .github/actions/environment/action.yml
This patch is intended to resolve the following issue that appears while
calling `cmake` for submodules from time to time:
fatal: No tags can describe '<sha>'.
Try --always, or create some tags.
This happens because the `actions/checkout` GitHub action fetches the
repository with the `--unshallow` option, but it doesn't do the same for
submodules. So this leads to the error above while using `git describe`
for submodules.
This is fixed by converting a shallow submodule to a complete one.
> ci: convert shallow submodules to complete ones 

- changelogs/unreleased/gh-9136-null-dereference-in-error_set_prev.md
- src/box/mp_error.cc
- test/app-luatest/msgpack_test.lua
- test/unit/xrow.cc
If `MP_ERROR` map contains two `MP_ERROR_STACK` keys, then the second to call to `error_set_prev(effect, cur)` will crash, because `effect` is NULL, but `err == NULL` is false, because it is assigned on the first iteration. This patch raises an error if more than one `MP_ERROR_STACK` key is present.
Closes #9136
> box: fix NULL pointer dereference in error_unpack_unsafe

- tools/gen-release-notes
We decided not to merge entries from Tarantool CE changelog to Tarantool EE changelog. Instead we now add a link to CE release notes to EE release notes. Update the script accordingly.
> tools/gen-release-notes: update for enterprise edition

- changelogs/unreleased/gh-8967-creds-postope-sync-when-RO-till-RW.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/credentials_applier_test.lua
Before this patch credentials applier used to just skip if Tarantool was in Read Only mode. Now it starts a fiber that waits for instance to be switched to Read Write mode and then applies in the background.
Part of #8967
NO_DOC=documentation request will be filed manually for the whole
credentials
> config: postpone creds applier when in RO till RW

- src/box/lua/config/instance_config.lua
- src/box/lua/load_cfg.lua
- test/box/box.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
The new option is backed by `box.cfg.auth_retries`. It is available only in Enterprise Edition builds.
For the implementation see https://github.com/tarantool/tarantool-ee/pull/560.
Needed for tarantool/tarantool-ee#541
> config: add `security.auth_retries` option

- static-build/cmake/AddDependencyProjects.cmake
Because some of the sites and servers don't work properly, sources cloned to S3 storage. Especially readline and libiconv.
> build: get readline/libiconv from backup storage

- static-build/cmake/AddDependencyProjects.cmake
Just a regular backport of #9167 via a pull request to verify changes.
> [2.11] build: get readline/libiconv from backup storage

- static-build/cmake/AddDependencyProjects.cmake
Just a regular backport of https://github.com/tarantool/tarantool/pull/9167 via a pull request to verify changes.
> [2.10] build: get readline/libiconv from backup storage

- src/lib/mpstream/mpstream.c
- src/lib/mpstream/mpstream.h
- test/unit/lua_msgpack.c
Proposed ASAN implementation of region allocator does not support double reservation for the sake of simplicity. Every reservation is supposed to be followed by one or more allocations.
This restiction does not work well with mpstream currently. The issue is mpstream_init/mpstream_reserve do reservation of size 0. For example In case of region slab of min order is reserved (a chunk of memory of page size currently). If the first data we want to write to mpstream is larger then the reservation done then we make reservation again.
Let's get rid of this reservation at the beginning as it is suboptimal behaviour. Moreover let's get rid of mpstream_reset as mpstream_init is lightweight and we can create a new mpstream instead of reusing exiting.
Also while we at it avoid allocation of 0 size …
> mpstream: get rid of mpstream_reset

- tools/rebase-release-notes
The goal of the script is to assist with removing changelog entries that are already included into a release of another development branch.
For example, if a bug fix is released as part of 2.11.3, there is no reason to highlight that it is fixed in 3.0.0. It is better to describe changes comparing to the latest present 2.11 release.
The script was initially written for personal use and there are obvious points for improvements. However, it seems that it already simplifies some tasks, so I'm going to share it as is and improve later. I'll leave the relevant issue open.
Part of #9135
> tools: add rebase-release-notes script

- src/box/memtx_engine.cc
- src/box/vy_log.c
- src/box/vy_run.c
- src/box/wal.c
- src/box/xlog.c
- src/box/xlog.h
- test/unit/xlog.c
The goal of this patch is to make the xlog writer API less confusing. It does the following changes:
- Rename `xlog_rename` to `xlog_materialize`. The function strips the .inprogress suffix from an xlog file name. Usually it's called after the xlog was sealed (by writing the EOF marker) and closed but it may also be called before `xlog_close` in case the xlog file is going to be appended to (used in WAL).
- Make `xlog_sync` private. It's called by `xlog_close` so there's no point in calling it manually. Make `xlog_close` fail if it fails to sync the file.
- Make `xlog_close` flush the buffer so that the caller doesn't need to call `xlog_flush` manually before closing an xlog file.
- Drop the `reuse_fd` argument of `xlog_close`. Instead, introduce a new function `xlog_close_reuse_fd` that …
> xlog: rework writer API

- src/box/alter.cc
- src/box/sequence.c
- src/box/sequence.h
Allocations from fiber region and heap should never fail so it's okay to use xmalloc for them.
This fixes the following coverity report complaining about unchecked region_alloc result:
https://scan7.scan.coverity.com/reports.htm#v39198/p13437/fileInstanceId=149497639&defectInstanceId=19021351&mergedDefectId=1525560
> sequence: use xmalloc where appropriate

- changelogs/unreleased/gh-8996-spurious-spit-brain-detected.md
- src/box/alter.cc
- src/box/box.cc
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- test/replication-luatest/gh_8996_synchro_filter_enable_test.lua
Our split-brain detection machinery relies among other things on all nodes tracking the synchro queue confirmed lsn. This tracking was only added together with the split-brain detection. Only the synchro queue owner tracked the confirmed lsn before.
This means that after an upgrade all the replicas remember the latest confirmed lsn as 0, and any PROMOTE/DEMOTE request from the queue owner is treated as a split brain.
Let's fix this and only enable split-brain detection on the replica set once the schema version is updated. Thanks to the synchro queue freeze on restart, this can only happen after a new PROMOTE or DEMOTE entry is written by one of the nodes, and thus the coorect confirmed lsn is propagated with this PROMOTE/DEMOTE to all the cluster members.
Closes #8996
NO_DOC=bugfix
> box: disable split-brain detection until schema is upgraded

- src/box/CMakeLists.txt
- src/box/lua/config/configdata.lua
- src/box/lua/config/init.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/failover.h
- src/box/lua/init.c
- src/lua/init.c
- src/lua/init.h
- src/main.cc
- src/trivia/config.h.cmake
- test/app-luatest/gh_8613_new_cli_behaviour_test.lua
- test/box-py/args.result
- test/config-luatest/cli_test.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patchset prepares declarative configuration collecting code to be used in the failover coordinator service, adds `--failover` option, adds failover module stubs.
The failover agent is to be implemented as part of Tarantool Enterprise Edition.
Part of https://github.com/tarantool/tarantool-ee/issues/564
> Add failover coordinator stubs

- changelogs/unreleased/gh-9173-box-info-crash.md
- src/box/lua/info.c
- test/box-luatest/gh_9173_box_info_before_box_cfg_test.lua
Before this patch if one called `vinyl`, `sql`, `gc` and `memory` functions from box.info() instance crashed. It's interesting that `replication_anon` functions worked ok.
This patch fixes that crashes.
Closes #9173
NO_DOC=bugfix
> box: fix crashes if some box.info functions called before box.cfg

- changelogs/unreleased/gh-4799-consistent-c-functions-calls.md
- changelogs/unreleased/gh-8576-set-compat-options-to-new.md
- src/box/port.c
- src/box/port.h
- src/box/sql/port.c
- src/lua/compat.lua
- test/box-luatest/CMakeLists.txt
- test/box-luatest/gh_4799_fix_c_stored_functions_call.c
- test/box-luatest/gh_4799_fix_c_stored_functions_call_test.lua
- test/box/func_reload.result
- test/box/function1.result
- test/box/function1.test.lua
- test/box/push.result
The first commit introduces the `c_func_iproto_multireturn` option (when set to new, the results of the stored C function aren't wrapped in an additional msgpack array, see below). By default, it is set to 'old', to avoid conflicts.  Also, this makes the first patch backportable to 2.11 as is (except conflict with compatibility options in compat.lua, see #9144). The second commit switches the behaviour to 'new' and fixes some diff tests.
As described in the commit message to the first patch, the SQL mechanism depends on the `port_dump_msgpack()` too, so just using the introduced flag in `port_c_dump_msgpack()` isn't good. As an alternative option, we can introduce 2 new fields (say `encode_call_results16`, `encode_call_results`) in `port_vtab` to call them and use the flag only there. But …
> Fix inconsistent multireturn values for stored C functions

- changelogs/unreleased/gh-4799-consistent-c-functions-calls.md
- src/box/port.c
- src/box/port.h
- src/box/sql/port.c
- src/lua/compat.lua
- test/box-luatest/CMakeLists.txt
- test/box-luatest/gh_4799_fix_c_stored_functions_call.c
- test/box-luatest/gh_4799_fix_c_stored_functions_call_test.lua
This patch backports the first commit from #9143 for backward compatibility. See the description there.
I've avoided the note in the commit message about cherry-pick:
```
(cherry picked from commit f70fde8f483ded8a0345ff9b91e53a55951aa428)
```
due to the lack of a commit hash in the main repository.
> [backport 2.11] box: introduce c_func_iproto_multireturn in compat

- changelogs/unreleased/gh-8967-set-creds-in-lazy-way.md
- src/box/lua/config/applier/credentials.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/helpers.lua
- test/config-luatest/instance_config_schema_test.lua
Before this patch privileges for space, function and sequence alone
were disabled. Only permission for universe could be granted. It was
done because there wasn't a way to grant or revoke a privilege when
subjecting object hasn't been created yet.
This patch allows grants and revokes for objects that will be created
after the applier. These actions will be postponed and executed via
on_commit trigger after the object is registered in the according system
space of box.space._space/_func/_sequence.
Now permission can be granted to space/function/sequence from within the
config.
Part of #8967
NO_DOC=documentation request will be filed manually for the whole credentials
> config: allow postponing object grants till creation

- src/lib/core/event.c
- test/app-luatest/trigger_module_test.lua
New event named 'tarantool.trigger.on_change' is called when any event is modified (trigger.set or trigger.del). All the handlers are called with one argument - name of the modified event. Returned value of each handler is ignored. Handlers are fired after the event is changed (the event contains inserted trigger, if any, and does not contain deleted one, if any). All thrown errors are logged with error level and do not stop execution of triggers.
Closes #8664
> trigger: introduce tarantool.trigger.on_change triggers

- changelogs/unreleased/gh-8996-spurious-spit-brain-detected.md
- src/box/alter.cc
- src/box/box.cc
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- test/replication-luatest/gh_8996_synchro_filter_enable_test.lua
Our split-brain detection machinery relies among other things on all nodes tracking the synchro queue confirmed lsn. This tracking was only added together with the split-brain detection. Only the synchro queue owner tracked the confirmed lsn before.
This means that after an upgrade all the replicas remember the latest confirmed lsn as 0, and any PROMOTE/DEMOTE request from the queue owner is treated as a split brain.
Let's fix this and only enable split-brain detection on the replica set once the schema version is updated. Thanks to the synchro queue freeze on restart, this can only happen after a new PROMOTE or DEMOTE entry is written by one of the nodes, and thus the correct confirmed lsn is propagated with this PROMOTE/DEMOTE to all the cluster members.
Closes #8996
NO_DOC=bugfix …
> [2.11] box: disable split-brain detection until schema is upgraded

- changelogs/unreleased/gh-8996-spurious-spit-brain-detected.md
- src/box/alter.cc
- src/box/box.cc
- src/box/txn_limbo.c
- src/box/txn_limbo.h
Our split-brain detection machinery relies among other things on all nodes tracking the synchro queue confirmed lsn. This tracking was only added together with the split-brain detection. Only the synchro queue owner tracked the confirmed lsn before.
This means that after an upgrade all the replicas remember the latest confirmed lsn as 0, and any PROMOTE/DEMOTE request from the queue owner is treated as a split brain.
Let's fix this and only enable split-brain detection on the replica set once the schema version is updated. Thanks to the synchro queue freeze on restart, this can only happen after a new PROMOTE or DEMOTE entry is written by one of the nodes, and thus the correct confirmed lsn is propagated with this PROMOTE/DEMOTE to all the cluster members.
Closes #8996
NO_DOC=bugfix …
> [2.10] box: disable split-brain detection until schema is upgraded

- changelogs/unreleased/gh-8472-decimal-compare-float-assertion.md
- src/box/tuple_compare.cc
- test/engine-luatest/gh_6377_decimal_compare_inf_crash_test.lua
mp_compare_decimal_any_number erroneously assumed that any float or double from which a decimal can't be created is either infinite or NaN. This is not true. Any float greater than 1e38 can't fit into our decimal representation. When such a float got compared to a decimal, an assertion fired, which was wrong. Luckily, on release build the comparison was correct. Only the assertion is wrong. Fix it.
Closes #8472
NO_DOC=bugfix
> core: fix a wrong assertion on decimal comparison with double

- changelogs/unreleased/gh-9182-disable-downgrade-more-recent-schema.md
- src/box/lua/upgrade.lua
- test/box-luatest/downgrade_test.lua
In this case we don't have knowledge how to downgrade correctly.
Close #9182
> downgrade: fail if schema version is more recent than application

- test/box-luatest/downgrade_test.lua
It is not convenient that `test_downgrade_from_more_recent_version` breaks if we create tag for new version and do not add next version to the downgrade versions list. If the version is released we should add it to the list anyway but it is not matter of this test.
Follow up #9182
> downgrade: fix test to downgrade on available version

- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/configdata.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
Implemented `"replication.failover"` = `"supervised"` mode, where instances basically starts in the read-only mode and waits for commands from an external coordinator.
Added `lease_interval` into the `failover` section to control how long a supervised master waits for a renew command from the coordinator before going to the read-only mode.
Added `renew_interval` into the `failover` section to control how often the coordinator should send the renew commands.
The failover coodrinator is to be implemented as part of Tarantool Enterprise Edition.
Part of https://github.com/tarantool/tarantool-ee/issues/564
Follows up PR #9189
> Add more failover coordinator stubs

- changelogs/unreleased/gh-9159-fix-memleak-in-sql-column-default-parser.md
- src/box/sql/parse.y
If token is referenced in C code then destructor for token is not called. Thus we don't need to duplicate. Otherwise we got a memory leak.
See https://www.sqlite.org/cgi/src/doc/trunk/doc/lemon.html#destructor
Close #9159
> sql: fix memory leak in SQL parser for column default

- changelogs/unreleased/gh-8657-move-triggers-to-trigger-registry.md
- changelogs/unreleased/gh-8664-trigger-on-change.md
The commit adds missing changelogs for tarantool.trigger.on_change and triggers that were moved to the trigger registry. The second changelog is especially important because it describes a breaking change of space triggers behavior.
Follow-up #8664
Part of #8657
> misc: add missing changelogs for trigger registry

- changelogs/unreleased/gh-8958-remove-transaction-nop.md
- src/box/applier.cc
- src/box/box.cc
- src/box/relay.cc
- src/box/txn.c
- src/box/wal.c
- test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua
commit 04aef9a9e0b9e6e3550e9413a0022cf3956f48d6
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Thu Aug 24 11:28:39 2023 +0300
box: fix force recovery for transactions with local rows
Force recovery first tries to collect all rows of a transaction into a
single list, and only then applies those rows.
The problem was that it collected rows based on the row replica_id. For
local rows replica_id is set to 0, but actually such rows can be part
of a transaction coming from any instance.
Fix recovery of such rows
Follow-up #8746
Follow-up #7932
NO_DOC=bugfix
NO_CHANGELOG=the broken behaviour couldn't be seen due to bug #8746
commit ce9444bfee4ccc08c6629d064a9a28393cccfaf5
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Wed Aug 23 14:10:59 2023 +0300
box: get rid of …
> Fix transaction boundaries in WAL and replication

- perf/CMakeLists.txt
- perf/memtx.cc
- src/box/tuple_format.c
- src/box/user.cc
The tuple format and access subsystems have static variables holding their
states which don't get reset during cleanup: initialize them explicitly in
`*_init` functions — that way we can re-initialize these subsystems
multiple times (e.g., when setting up and tearing down benchmarks). Opted
for initializing them in `*_init` functions rather than resetting them in
`*_free` functions for logical consistency.
Needed for #6964
This first version is quite basic and only benchmarks random `get`s of
existing keys and `select`s of all keys for a tree index (these benchmarks
are needed for #6964) — its main goal is to provide a foundation (i.e., all
the necessary initialization logic) for benchmarking memtx. Extending this
benchmark using the provided memtx singleton and fixture should be fairly …
> memtx benchmark

- .github/workflows/integration.yml
The patch returns integration test run with `crud`. The test run was removed earlier [1] because the `crud` did not support tests with Tarantool 3.0. But now it supports [2].
1. https://github.com/tarantool/tarantool/commit/7316d8165e80b3678b45fd1b42823a8f92b734f6
2. https://github.com/tarantool/crud/pull/381
NO_DOC=ci
NO_TEST=ci
> ci: add crud integration test run

- .github/workflows/debug_asan_clang.yml
- .test.mk
- asan/lsan.supp
- src/box/vy_cache.c
- test/app-tap/gh-2717-no-quit-sigint.test.lua
PR for master branch https://github.com/tarantool/tarantool/pull/9225
Commit https://github.com/tarantool/tarantool/commit/232c28f333ac75be26abb54dc308e2e5813b7acd is dropped because it depends on https://github.com/tarantool/tarantool/commit/230123566f5c4502cf346c75a1e941a0440e016b. Anyway we don't need it because slice check is turned off by default in 2.11.
We also need to take https://github.com/tarantool/tarantool/commit/bf62170fc03883426b156e917f606eee356c056e (PR https://github.com/tarantool/tarantool/pull/9161) to pass debug_asan_clang CI.
> Backport of "ci: add debug_asan_clang workflow" PR to 2.11

- test/unit/prbuf.c
The test start to fail in CI on osx_debug (x86_64) workflow
```
[033]  	*** test_buffer_foreach_copy_number ***
[033] -ok 13 - prbuf(size=256, payload=16, iterations=16) has been validated
[033] -ok 14 - prbuf(size=256, payload=16, iterations=32) has been validated
[033] -ok 15 - prbuf(size=256, payload=16, iterations=64) has been validated
[033] +ok 13 - prbuf(size=256, payload=4294967312, iterations=16) has been validated
[033] +ok 14 - prbuf(size=256, payload=4294967312, iterations=32) has been validated
[033] +ok 15 - prbuf(size=256, payload=4294967312, iterations=64) has been validated
[033]  	*** test_buffer_foreach_copy_number: done ***
```
> unit: fix undefined behaviour in prbuf test

- .github/workflows/debug_asan_clang.yml
- .test.mk
- asan/lsan.supp
- src/box/sql/select.c
- src/box/vy_cache.c
- test/app-tap/gh-2717-no-quit-sigint.test.lua
This is basically port of PR https://github.com/tarantool/tarantool/pull/9241 (`Backport of "ci: add debug_asan_clang workflow" PR to 2.11`).
Yet we have to add `"sql: fix memory leak in sqlColumnsFromExprList"` to pass debug asan workflow.
> Backport of "ci: add debug_asan_clang workflow" PR to 2.10

- changelogs/unreleased/gh-8657-move-triggers-to-trigger-registry.md
- src/box/box.cc
- src/box/box.h
- src/box/lua/ctl.c
- src/box/raft.c
- src/box/raft.h
- src/box/schema.cc
- src/lib/core/trigger.cc
- src/main.cc
- src/on_shutdown.c
- src/on_shutdown.h
- test/box-luatest/triggers_old_api_test.lua
The patch moves all triggers from `box.ctl` to the trigger registry.
Closes https://github.com/tarantool/tarantool/issues/8657
> box: move all box.ctl triggers to the trigger registry

- changelogs/unreleased/gh-8657-move-triggers-to-trigger-registry.md
- src/box/alter.cc
- src/box/lua/space.cc
- src/box/lua/trigger.c
- src/box/lua/trigger.h
- src/box/space.c
- src/box/space.h
- src/lib/core/event.c
- src/lib/core/event.h
- test/box-luatest/gh_4264_recursive_trigger_test.lua
- test/box-luatest/gh_8027_txn_handle_abort_in_trigger_test.lua
- test/box/before_replace.result
- test/box/before_replace.test.lua
- test/box/on_replace.result
- test/box/on_replace.test.lua
- test/box/push.result
- test/box/push.test.lua
- test/engine-luatest/space_triggers_test.lua
- test/engine/savepoint.result
- test/engine/savepoint.test.lua
- test/sql/iproto.result
- test/sql/iproto.test.lua
- test/unit/event.c
- test/vinyl/on_replace.result
- test/vinyl/on_replace.test.lua
Attaching triggers to space id instead of space object is a significant pitfall. The users who haven't discovered new triggers may not expect the triggers of a dropped space will be fired by a new one. So let's drop triggers that were set with old API along with the space.
Closes #9223
> space: drop space with its triggers set with old API

- changelogs/unreleased/gh-7017-display-message-on-console-exit.md
- src/box/lua/console.c
- src/box/lua/console.h
- src/box/lua/console.lua
- src/main.cc
- test/app-luatest/gh_7017_message_on_console_exit_test.lua
Consider the following example:
```
tarantool -e "box.cfg{} require('console').start()"
```
When a local console is exited by pressing Ctrl+D, Tarantool seemingly freezes - console stops to work, typed characters are not echoed. But the event loop is not stopped because there are background fibers running. This patch adds a message that Ctrl+C should be pressed in such a case.
Closes #7017
> main: display a message when local console is exited

- changelogs/unreleased/gh-9247-fix-space-bsize-handling-on-space-alter.md
- src/box/alter.cc
- src/box/blackhole.c
- src/box/memtx_space.c
- src/box/session_settings.c
- src/box/space.c
- src/box/space.h
- src/box/sysview.c
- src/box/vinyl.c
- test/box-luatest/gh_9247_bsize_on_concurrent_dml_and_alter_test.lua
During building an index in background, some transaction can perform a dml request that affects space size (e.g. a replace), but the size will remain the same, because `bsize` is moved from the old space to the new space in `memtx_space_prepare_alter()` prior to `space_execute_dml()`. Fix this issue by calling `space_finish_alter()` in `alter_space_do()`. In fact, this patch partially reverts commit https://github.com/tarantool/tarantool/commit/9ec3b1a445a6335b0e25f9fefdaaaf7f7f17cd7d (`alter: zap space_vtab::commit_alter`).
Closes #9247
> box: fix `space:bsize()` handling on space alter

- changelogs/unreleased/gh-8967-add-lua_eval-lua_call-sql.md
- src/box/lua/config/applier/credentials.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/instance_config_schema_test.lua
With #8906 the object types mentioned above were introduced. They control access to code execution over IPROTO.
This patch adds such object types support to credentials applier. Now 'execute' can be granted to a user or role for 'lua_eval', 'lua_call' and 'sql'. Note that similar to 'universe', objects can't be specified in the config, only 'all' is allowed.
Part of #8967
NO_DOC=documentation request will be filed manually for the whole
credentials
> config: add lua_eval, lua_call and sql support to creds

- changelogs/unreleased/gh-8967-creds-consider-auth-type.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/credentials_applier_test.lua
User password is stored in a system space is a form of hash when 'chap-sha1' auth type is set, and in a form of hash with salt when 'pap-sha256' is set.
Now, if a user is set inside config, and the current auth type is different from the type the users password is stored in, the password hash will be regenerated.
Part of #8967
NO_DOC=documentation request will be filed manually for the whole
credentials
> config: update password hashes after auth_type change

- src/box/lua/console.lua
Tarantool supports two console protocols: text and binary. The binary protocol is implemented with IPROTO EVAL request so the console module reuses the net.box module to establish and maintain a binary connection. Currently, instead of passing the original URI specified by the user to net.box.connect as is, the console module parses the URI and passes the host and port. As a result, extra information that may be specified in URI parameters is lost. This prevents the user from connecting to the binary console using the SSL transport because to use the SSL transport the user must specify transport=ssl URI parameter.
Needed for tarantool/tarantool-ee#567
> console: forward original URI to net.box when connecting over IPROTO

- changelogs/unreleased/gh-9266-fix-on-shutdown-and-osexit-from-cmd-expr.md
- src/lua/init.c
- test/box-luatest/gh_9266_fix_on_shutdown_and_osexit_from_cmd_expr_test.lua
The motivation is to reduce time slip on Tarantool startup before running init scripts. Internal ev time is set in `fiber_init`/`ev_default_loop` and is not get updated until starting event loop. This causes timeouts slip up to 0.3 in debug ASAN build in init script (see #9261).
Let's run event loop right at the beginning of the `run_script_f` before executing any script. This way besides updating internal ev time we make an explicit place of starting script event loop. Currently it is started lazily when config script yields.
This will fix CI for PR https://github.com/tarantool/tarantool-ee/pull/572 for debug ASAN workflow.
We can also remove `start_loop condition`. It does not make sense now. It was added in the commit 3a851430a19c ("Fix tarantool -e "os.exit()" hang") but since then we …
> app: start init script event loop explicitly

- changelogs/unreleased/bump-libcurl-to-8.4.0.md
The patch updates curl module to the version 8.4.0 [1] that brings a number of functional fixes and security fix of SOCKS5 heap buffer overflow (CVE-2023-38545), see description in [2] and commit fb4415d8aee6 ("socks: return error if hostname too long for remote resolve") in [3].
1. https://curl.se/changes.html#8_4_0
2. https://curl.se/docs/CVE-2023-38545.html
3. https://github.com/curl/curl/commit/fb4415d8aee6c1045be932a34fe6107c2f5ed147
NO_DOC=libcurl submodule bump
NO_TEST=libcurl submodule bump
> third_party: update libcurl from 8.3.0 to 8.4.0

- perf/memtx.cc
- src/box/box.cc
- src/box/field_default_func.c
- src/box/field_default_func.h
- src/box/memtx_engine.cc
- src/box/tuple_format.c
- test/unit/tuple_format.c
There are four problems we have to address to make this possible:
1. `memtx_engine_shutdown` may delete the tuple referenced by `box_tuple_last` so that `tuple_free`, which is called later by `box_free`, will crash trying to free it. Fix this by clearing `box_tuple_last` in `memtx_engine_shutdown`.
2. `tuple_format_destroy` and `tuple_field_delete`, called by it, expect all constraints to be detached. Let's destroy the constraints if this isn't the case. This effectively reverts commit 7a87b9a594ee5.
3. `tuple_field_delete`, called by `tuple_format_destroy`, expects the default value function to be unpinned. Let's unpin it if this isn't the case. To avoid linking dependencies between the tuple and box libraries, we have to introduce a virtual destructor for `field_default_func`.
4. The …
> box: call `tuple_free` from `box_free`

- src/box/lua/config/applier/credentials.lua
- test/luatest_helpers/server.lua
With this patch the following log/alert structure is introduced:
* all informational messages (e.g. some privs granted) use `log.verbose()`
* all warnings about postponed apply use `config:_alert{type = 'warn'}`
* all apply errors are reported with `config:_alert{type = 'error'}`
Debug logs are removed.
Part of #8967
> config: unify logs and alerts inside creds applier

- src/box/tuple_compare.cc
- src/trivia/util.h
The macro expands to inline keyword and always_inline attribute if it's supported. This attribute forces the compiler to inline the function if it's possible and raise a diagnostic if it's not.
Needed for https://github.com/tarantool/tarantool-ee/issues/580
> util: introduce the ALWAYS_INLINE macro

- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/lint.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/release.yml
- .github/workflows/release_lto.yml
- .github/workflows/source.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/submodule_update.yml
Modify Linux workflows for running jobs inside Docker containers. It helps isolate the building and testing environment from the runner's system and other workflows.
Closes tarantool/tarantool-qa#327
> ci: dockerize linux workflows

- changelogs/unreleased/gh-9222-sigaltstack.md
- src/lib/core/crash.c
- src/lib/core/fiber.c
- test/unit/guard.cc
We install a signal handler that prints the stack trace on SIGSEGV, SIGBUS, SIGILL, SIGFPE. The signal handler uses the current stack. This works fine for most issues, but not for stack overflow, because the latter makes the current stack unusable, leading to a crash in the signal handler. Let's install an alternative signal stack in each thread so that we can print the stack trace on stack overflow.
Closes #9222
> fiber: use alternative signal stack

- src/box/errcode.h
- test/replication-luatest/cluster_name_test.lua
- test/replication-luatest/instance_name_test.lua
- test/replication-luatest/replicaset_name_test.lua
The error message was not quite clear in case instance has any name defined and config provides a different one.
Closes #8692
NO_CHANGELOG=no previous release with this error message
NO_DOC=not needed since no changes to the public API
> replication: improve name conflict error message

- test/sql-tap/selectG.test.lua
The test is quite a flacky in debug ASAN CI workflow. The issue is test check upper boundary of it's execution time. I run many instances of this test on in parallel and got average time of 40s for memtex and 70s for vinyl.
The time quota is already changed by the commit 84cb1e049272 ("sql: increase time quota for selectG test on vinyl") for laptops with HDD. I did not check execution time for HDD though. I guess the bottleneck for debug ASAN is CPU.
Follow-up #7327
> test: increase expected selectG execution time for debug ASAN build

- src/box/iproto.cc
- src/box/lua/merger.c
- src/box/lua/net_box.c
- src/box/lua/schema.lua
- src/box/lua/tuple.lua
- src/httpc.c
- src/lib/core/coio_buf.h
- src/lib/core/prbuf.c
- src/lib/core/prbuf.h
- src/lua/buffer.lua
- src/lua/httpc.lua
- src/lua/socket.lua
We have several places where we move ibuf.wpos pointer directly without using ibuf API. As a result we don't poison the area that is known to be unallocated.
Let's introduce `ibuf_discard` to discard given number of bytes from write end of the buffer.
Follow-up #7327
> misc: use ibuf API to discard/allocate/consume.

- changelogs/unreleased/gh-7962-log-cfg-modules-fix.md
- src/box/lua/load_cfg.lua
- src/lua/log.lua
- test/box-luatest/gh_3211_per_module_log_level_test.lua
Configuring log modules work differently with `log.cfg` and `box.cfg`: `box.cfg{log_modules=...}` overwrites the current config completely while `log.cfg{modules=...}` overwrites the currently config only for the specified modules. Let's fix this inconsistency by making `log.cfg` behave exactly as `box.cfg`.
Closes #7962
> log: make `log.cfg{modules=...}` work as `box.cfg{log_modules=...}`

- changelogs/unreleased/gh-9277-space-execute-priv.md
- src/box/lua/load_cfg.lua
- src/box/lua/schema.lua
- test/box-luatest/gh_9277_space_execute_priv_test.lua
- test/box-py/iproto.result
- test/box-py/iproto.test.py
- test/box/access.result
- test/box/access.test.lua
- test/box/access_misc.result
- test/box/access_misc.test.lua
- test/box/access_sysview.result
- test/box/access_sysview.test.lua
- test/box/net.box_field_names_gh-2978.result
- test/box/net.box_field_names_gh-2978.test.lua
- test/box/net.box_get_connection_object.result
- test/box/net.box_get_connection_object.test.lua
- test/sql/triggers.result
- test/sql/triggers.test.lua
Historically, it was possible to grant the `execte` privilege on a space although this action had no effect. Since Tarantool 3.0 it isn't allowed anymore. The new `compat` module option `box_space_execute_priv` was added to revert to the old behavior.
Example:
```
tarantool> box.cfg{log_level = 'error'}
---
...
tarantool> box.schema.user.create('alice')
---
...
tarantool> box.schema.user.grant('alice', 'execute', 'space')
---
- error: Unsupported space privilege 'execute'
...
tarantool> require('compat').box_space_execute_priv = 'old'
---
...
tarantool> box.schema.user.grant('alice', 'execute', 'space')
---
...
```
Closes #9277
> box: disallow granting execute privilege on space

- test/wal_off/oom.result
- test/wal_off/oom.test.lua
We hit #3807 in release/2.11 for release ASAN build with ASAN-friendly small allocators.
Follow-up #7327
> test: add WA for #3807 to wal_off/oom.test

- changelogs/unreleased/config-validate-names.md
- src/box/lua/config/cluster_config.lua
- src/box/lua/config/init.lua
- test/config-luatest/cli_test.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/justrun.lua
Recently added persistent instance/replicaset/cluster names have certain validation rules (see #5029 and #9148). An instance name and a replicaset name that are provided in a declarative configuration are stored in the database, so they should follow the same rules.
This patch implements the validation for instance/replicaset/group names, for `--name` CLI option and `TT_INSTANCE_NAME` environment variable.
The validation rules are described in https://github.com/tarantool/doc/issues/3466, https://github.com/tarantool/doc/issues/3467 and https://github.com/tarantool/doc/issues/3468.
Part of #8862
Related to #9148
> config: validate instance/replicaset/group names

- changelogs/unreleased/fiber-basic-api.md
- extra/exports
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- test/app-tap/module_api.c
- test/app-tap/module_api.test.lua
Closes #9237
Add exports for fiber_set_name_n, fiber_get_name, fiber_get_id, fiber_get_csw & fiber_find.
Title: add basic fiber api to ffi exports.
5 basic functions can now be used via ffi api, which were previously only accessible via lua api: fiber_set_name_n, fiber_get_name, fiber_get_id, fiber_get_csw & fiber_find.
> fiber: basic api exports

- src/box/lua/config/applier/box_cfg.lua
At the last itaration of review it was decided to throw an alerts, when no UUID was passed to config and name is not set in _cluster.
This leads to alerts, thrown during replicaset bootstrap. However, _cluster:on_replace trigger wasn't updated for that change, it asssumed that when insert of a new replica is done, no alerts was thrown.
Let's fix the behavior of on_replace trigger so that it deletes alerts as soon as replica joined with name.
Follow-up #8978
> config: fix hanging alert about missing name

- changelogs/unreleased/gh-8054-lua-iproto-encoder.md
- src/box/iproto.cc
- src/box/iproto_constants.h
- src/box/lua/iproto.c
- test/app-luatest/iproto_encoder_test.lua
- test/box-luatest/ghs_16_user_enumeration_test.lua
The following new constants and functions were added to the `box.iproto` namespace:
- `GREETING_SIZE`: Size of a Tarantool greeting message
- `GREETING_PROTOCOL_LEN_MAX`: Max length of a protocol string that can be encoded in a Tarantool greeting message.
- `GREETING_SALT_LEN_MAX`: Max length of a salt string that can be encoded in a Tarantool greeting message.
- `box.iproto.encode_greeting({version = x, uuid = x, salt = x})`: Encodes a Tarantool greeting message. Takes a table. Returns a string. Raises on error. The protocol is set to "Binary" (IPROTO).
- `box.iproto.decode_greeting(string)`: Decodes a Tarantool greeting message. Takes a string. Returns a table with the following fields: `protocol`, `version`, `uuid`, `salt`. Raises on error. The input string must be exactly …
> lua: add helpers for encoding/decoding IPROTO packets

- tools/tarantool-gdb.py
> gdb: fix tt-list filtering with predicate (-p option)

- test/unit/tuple_format_map.c
This patch fixes build warnings issued by GCC 12.
> test: fix number to string conversion in tuple format map test

- src/main.cc
- test/box-py/args.result
Follows up commit d5c874e1bd82 ("main: rewrite help message").
Thanks to Mergen Imeev (@ImeevMA) for pointing it out!
Part of #8862
> main: fix typo in the help message

- changelogs/unreleased/config-replicaset-group-name-templates.md
- src/box/lua/config/configdata.lua
- test/config-luatest/vars_test.lua
The declarative configuration supports `{{ instance_name }}` template variable from the beginning.
Now, two more ones were added: `{{ replicaset_name }}` and `{{ group_name }}`.
All the template variables are set according to the instance/replicaset/group topology from the given configuration.
Example:
```yaml
console:
socket: '{{ group_name }}/{{ replicaset_name }}/{{ instance_name }}.admin'
groups:
g:
replicasets:
r:
instances:
i: {}
```
The admin console will be at `g/r/i.admin` for instance `i`.
Part of #8862
> config: support {{ replicaset_name }} and {{ group_name }}

- changelogs/unreleased/gh-6762-add-tuple-info-and-space-stat.md
- perf/memtx.cc
- src/box/allocator.h
- src/box/lua/schema.lua
- src/box/lua/space.cc
- src/box/lua/tuple.c
- src/box/lua/tuple.lua
- src/box/memtx_engine.cc
- src/box/memtx_space.c
- src/box/memtx_space.h
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/tuple.c
- src/box/tuple.h
- src/box/tuple_format.h
- src/box/vy_stmt.c
- test/box-luatest/gh_6762_tuple_and_space_size_test.lua
- test/unit/memtx_allocator.cc
Returns a table with the following fields:
* `data_size` - Size of the MessagePack data in the tuple.
This number equals to number returned by `tuple_object:bsize()`.
* `header_size` - Size of the internal tuple header.
* `field_map_size` - Size of the field map.
Field map is used to speed up access to indexed fields of the tuple.
* `waste_size` - The amount of excess memory used to store the tuple in mempool.
* `arena` - Type of the arena where the tuple is allocated.
Possible values are: "memtx", "malloc", "runtime".
---
Returns a table with the cumulative statistics on the memory usage by tuples in the space.
The statistics is grouped by arena types: "memtx" or "malloc".
For a detailed description of each field see `tuple_object:info()`.
Note: The statistics is collected only for memtx …
> box: introduce `tuple:info()` and `space:stat()`

- test/unit/coio.cc
in test/unit/coio.cc if rc at coio.cc:95 equals to 0 (no errors occured) then test crashes with SIGSEGV at this line:
```c
const char *errmsg = diag_get()->last->errmsg;
```
I ran into this by accident while running tests on a machine with an unusual network setup. I understand that this is not the expected branch code execution, but i think it good to fix it anyway.
> test: fix null pointer dereference in `coio::test_getaddrinfo`

- changelogs/unreleased/gh-9118-box-space-max.md
- src/box/schema_def.c
- src/box/schema_def.h
- src/lib/core/tweaks.c
- src/lib/core/tweaks.h
- src/lua/compat.lua
- src/lua/tweaks.c
- test/box-luatest/fully-temporary_spaces_test.lua
- test/box-luatest/gh_8036_create_space_with_explicit_and_implicit_id_test.lua
- test/box-luatest/gh_9118_space_max_test.lua
- test/box/alter_limits.result
- test/unit/lua_tweaks.c
- test/unit/tweaks.c
Currently, `BOX_SPACE_MAX` equals `BOX_ID_NIL`, which is used as an error indicator in the box C API. As a result, if `box_space_id_by_name()` returns `BOX_ID_NIL`, it's impossible to figure out whether there's no space with the give name or the space exists and has the id equal to `BOX_SPACE_MAX`.
Let's decrement `BOX_SPACE_MAX` to fix this issue. Since this may break recovery, let's also introduce the new compatibility module option `box_space_max` to allow the user revert to the old behavior.
Closes #9118
> box: decrement `BOX_SPACE_MAX`

- changelogs/unreleased/gh-4962-box-cfg-forbid-infinite-numbers.md
- src/box/lua/load_cfg.lua
- test/box-luatest/gh_4962_cfg_infinite_numbers_test.lua
Setting a `box.cfg` option to `inf` or `nan` can result in a crash or invalid behavior. For example, setting `box.cfg.checkpoint_interval` to `0/0` triggers an assertion failure. Let's add a check against `inf` and `nan` for all options. These special numbers don't make any sense as configuration option values anyway.
Closes #4962
> box: add check against setting `box.cfg` options to `inf` and `nan`

- changelogs/unreleased/gh-7562-fiber_join.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- test/unit/fiber.cc
- test/unit/fiber.result
Prior to this patch a bunch of illegal conditions were possible:
1. The joinability of a fiber could be changed while the fiber is being joined by someone. This could lead to double recycling: the first one happened on the fiber finish, and the second one in the fiber join.
2. The joinability of a dead joinable fiber could be altered, this led to inability jo join the dead fiber and free its resources.
3. A running fiber could be joined concurrently by two or more fibers, so the fiber could be recycled more than once (once per each concurrent join).
4. A dead joined fiber could be made joinable and joined once more leading to a double recycle.
Fixed these issues by adding a new FIBER_IS_JOINED flag and using it where appropriate: now the `fiber_join` detects the double join and …
> fiber: make the concurrent fiber_join safer

- src/box/call.c
- src/box/call.h
- src/box/func.c
- test/box-luatest/gh_8803_exec_priv_test.lua
Currently, the `lua_call` privilege simply doesn't work for registered functions. This patch fixes this issue: now, it grants access to any registered function that is written in Lua unless it's a built-in function, such as `dostring`, or a persistent function.
Note, this patch renames `access_check_call` to `access_check_lua_call` to avoid confusion because this function is now global. It also renames `access_check_eval` to `access_check_lua_eval` for consistency.
Closes #9363
> box: allow `lua_call` priv owners to call registered Lua functions

- changelogs/unreleased/gh-8803-exec-priv.md
- src/box/alter.cc
- src/box/call.c
- src/box/lua/schema.lua
- src/box/user.cc
- src/box/user.h
- src/box/user_def.h
- test/box-luatest/gh_9360_lua_call_exec_priv_test.lua
Now, one can specify a function name when configuring the `lua_call` privilege to a user or role. If omitted, the privilege will grant access to any global Lua function except for built-ins and stored procedures. If specified, the privilege will be applied only to the given function name, which may be a built-in, but still not a stored procedure. The function doesn't need to be defined at the time the privilege is granted.
Since global Lua functions aren't stored in the database and hence have no numeric ids, we store string names in the `_priv` system table. Fortunately, it's already allowed for entity access so we don't need to update the system schema. The cached runtime access information is stored in a global hash table. Entries in the hash table are created on demand and removed if …
> box: allow to grant `lua_call` privilege to function name

- changelogs/unreleased/gh-7810-run-triggers-on-rollback-to-savepoint.md
- changelogs/unreleased/gh-9340-fix-on_rollback-function-args.md
- src/box/alter.cc
- src/box/applier.cc
- src/box/lua/init.c
- src/box/txn.c
- src/box/txn.h
- src/box/vinyl.c
- test/engine-luatest/gh_9340_on_rollback_trigger_args_test.lua
- test/engine/savepoint.result
- test/engine/savepoint.test.lua
Currently `on_rollback` triggers are called on rollback of the whole transaction. To make it possible to invoke them on rollback to a savepoint, we need to pass a statement at which the savepoint was created.
Currently, if a transaction is aborted by a fiber yield or by a timeout, `txn_rollback_to_svp()` is called to rollback all statements of the txn. After that the transaction is completely aborted on attempt to commit it. If an `on_rollback` trigger is set, it is called from `txn_complete_fail()`, however it receives an empty iterator, because at this point the statements are already destroyed. This patch invokes `on_rollback` triggers directly from `txn_rollback_to_svp()` for abort-by-yield, and postpones the rollback for abort-by-timeout.
Currently, if a statement is rolled back …
> txn: fix `on_rollback` trigger arguments for transactions aborted by yield or timeout

- test/sql-luatest/suite.ini
Just a regular backport of #9336 via a pull request to verify changes.
> [2.11] tests: run tests from sql-luatest/ in parallel

- test/sql-luatest/suite.ini
Just a regular backport of #9336 via a pull request to verify changes.
> [2.10] tests: run tests from sql-luatest/ in parallel

- CMakeLists.txt
- cmake/CheckPatch.cmake
Patch introduces a new CMake target "checkpatch", that checks patches on top of the master branch using script checkpatch.pl [1]. By default CMake looking for checkpatch.pl in a directory "checkpatch" in Tarantool's repository root directory and in a directories specified in PATH.
1. https://github.com/tarantool/checkpatch
> cmake: introduce target checkpatch

- .github/workflows/source.yml
In this commit, we're fixing a problem with Docker in the workflow
`.github/workflows/source.yml`.
The mentioned workflow uses the `.github/actions/environment` action
that needs a permission to make a loopback device for [1]. We didn't
allow for that before due to missing container args, and it caused the
following error:
```
umount: /tmp/luajit-test-vardir: must be superuser to unmount.
256000+0 records in
256000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 1.36702 s, 767 MB/s
mount: /tmp/luajit-test-vardir: mount failed: Operation not permitted.
Error: Process completed with exit code 1.
```
The problem started since commit https://github.com/tarantool/tarantool/commit/af996bbb920372f0323fcb68b5a47b8727c172ee ("ci: dockerize
linux workflows"). The simplest way to fix the …
> ci: remove using Docker container in source.yml 

- changelogs/unreleased/gh-9120-space-drop-rollback.md
- src/box/lua/space.cc
- src/box/space.c
- src/box/space.h
- test/box-luatest/gh_9120_space_drop_rollback_test.lua
- test/box/errinj.result
- test/box/errinj.test.lua
Before this commit the space rollback had been treated as a new space creation, so it caused creation of a new space object in the the Lua's box.space namespace. Since the preceding space drop removed the space object from the namespace, on the space rollback all the Lua users of the space loosed the track of its changes: the original space object is never updated anymore.
This is fixed by detecting the space rollback and restoring the old space object instead of creating a new one.
Closes #9120
NO_DOC=bugfix
> box: revert the lua space object on the space drop rollback

- changelogs/unreleased/gh-9406-fix-use-after-free-on-shutdown.md
- src/lib/core/fiber.c
- test/app-luatest/fiber_test.lua
On Tarantool shutdown we destroy all the fibers in some sequence. We don't require that all the fibers are finished before shutdown. So it may turn out that we first destroy some alive fiber and then destroy another alive fiber which joins the first one. Currently we have use-after-free issue in this case because clearing `link` field of the second fiber changes `wake` field of the first fiber.
Close #9406
> fiber: fix use-after-free on shutdown with lingering fiber join

- src/lib/core/crash.c
- src/lib/core/crash.h
- src/lib/core/errinj.h
- test/app-luatest/gh_8445_crash_during_crash_report_test.lua
Test suite run can produce coredumps in case of bugs. Unfortunately coredumps related to bugs are mixed with coredumps produced related to special test conditions, like when we test Tarantool response to deadly signal. Avoid producing coredumps in correct test suite run.
> test: do not produce coredumps in tests

- changelogs/unreleased/gh-9405-wal-error-event.md
- src/box/box.cc
- src/box/journal.c
- test/box-luatest/gh_9405_wal_error_event_test.lua
The new event is broadcast whenever Tarantool fails to commit a transaction to the write-ahead log (WAL), which usually means there's a problem with the underlying disk storage. The new event's payload is a table that currently contains the only field `count` that stores the number of WAL errors happened so far or nil if there hasn't been any WAL errors.
Closes #9405
> journal: broadcast `box.wal_error` event on write error

- changelogs/unreleased/gh-8650-add-is_sync-option.md
- extra/exports
- src/box/applier.cc
- src/box/iproto.cc
- src/box/iproto_constants.h
- src/box/lua/init.c
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- src/box/lua/schema.lua
- src/box/txn.c
- src/box/txn.h
- src/box/xrow.c
- src/box/xrow.h
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/box-luatest/gh_8650_add_is_sync_option_test.lua
Added the new is_sync parameter to `box.begin()`, `box.commit()`, and `box.atomic()`. To make the transaction synchronous, set the `is_sync` option to `true`. If to set any value other than `true/nil`, for example `is_sync = "some string"`, then an error will be thrown. Examples:
```Lua
-- Sync transactions
box.atomic({is_sync = true}, function() ... end)
box.begin({is_sync = true}) ... box.commit({is_sync = true})
box.begin({is_sync = true}) ... box.commit()
box.begin() ... box.commit({is_sync = true})
-- Async transactions
box.atomic(function() ... end)
box.begin() ... box.commit()
```
Closes https://github.com/tarantool/tarantool/issues/8650
> box: add is_sync option

- changelogs/unreleased/gh-9401-anon-replica-synchro.md
- src/box/applier.cc
- src/box/box.cc
- src/box/xrow.c
- src/box/xrow.h
- test/replication-luatest/gh_9401_anon_replica_synchro_queue_state_test.lua
Starting with commit f1c2127d4367 ("replication: add META stage to JOIN") replication master appends a special section, called IPROTO_JOIN_META to the initial snapshot sent to the replica. This section contains the latest raft term and synchronous transaction queue owner and term.
The section is only sent to nodes, which have a non-zero version_id. For some reason, version_id encoding for FETCH_SNAPSHOT (analog of JOIN for anonymous replicas) wasn't added in that commit, so anonymous replicas do not receive synchronous queue state.
This leads to them raising ER_SPLIT_BRAIN errors later after join, when the first synchronous row arrives.
In order to fix this, start encoding version_id in FETCH_SNAPSHOT requests.
Closes #9401
Title: new field in …
> replication: send anonymous replica version id

- changelogs/unreleased/config-fix-etcd-prefix-validation.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
If `config.etcd` is present and non-empty, `config.etcd.prefix` is required.
This validation check was not performed due to a mistake in a schema node wrapper that adds a validator that checks an attempt to use an Enterprise Edition option on Community Edition.
Part of #8862
> config: verify config.etcd.prefix presence

- changelogs/unreleased/gh-9426-func-cache.md
- src/box/func_cache.c
- test/box-luatest/gh_9426_func_cache_test.lua
Before this patch it could happen that deletion of a function from the function cache didn't delete it from the funcs_by_name map. The reason is that the check if the function exists in the map performs the comparison of the search result with the `end` backet id of the wrong hash table.
The situation in which this could happen is the following:
1. Insertion of a new function into the cache triggers resize of thefuncs_by_value map, but the size of the funcs map remains the same.
2. Then user deletes a function. This removes the function from the funcs map. Then we check if the function exists in thefuncs_by_value map. The function exists there, but it so happens that it's bucket id equals to the funcs map bucket count, so the incorrect check if the function exists in the funcs_by_value …
> box: fix the comparison in the functions cache

- src/box/relay.cc
Relay sometimes decodes the PROMOTE packets to be sent in order to conditionally delay their despatch. It was believed that own WALs can't be corrupted and hence there is no point in checking that decoding succeeds.
Let's be more strict here and check the decoding result before proceeding.
Closes #9265
NO_DOC=bugfix
NO_TEST=hard to test
NO_CHANGELOG=not user-visible
> relay: check return value of xrow_decode_synchro

- changelogs/unreleased/config-anonymous-replica.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/configdata.lua
- test/config-luatest/anonymous_replica_test.lua
`replication.anon: true` option is now working.
Mostly, it is the only thing that a user needs to know about this changeset.
However, technically speaking, several related configuration checks are introduced here and dependent defaults were adjusted to make usage of anonymous replicas smoother.
The new configuration constrainsts are the following.
* A replicaset must contain at least one non-anonymous instance.
* An anonymous replica can't be configured as writable instance using `database.mode` or `<replicaset>.leader` options.
* An anonymous replica can't be configured with `replication.election_mode` equals to `candidate`, `voter` or `manual` (only `off` is allowed).
A few more nuances about anonymous replicas:
* Anonymous replicas are filtered out from default upstream list.
* A …
> config: allow to configure an anonymous replica

- changelogs/unreleased/gh-9345-fix-iproto-override-double-request-account.md
- src/box/iproto.cc
- test/box-luatest/iproto_request_handlers_overriding_test.lua
We need to call `tx_accept_msg` in `tx_process_override` before we pass message to the override handler. Unfortunately if handler response with `IPROTO_HANDLER_FALLBACK` we call the builtin handler for message that calls `tx_accept_msg` again which is not expected. Some actions of this function are idempotent and some are not.
Let's make the function NOP if it called once again.
Closes #9345
> iproto: don't account message twice in case of override fallback

- tools/gen-release-notes
Some changes are not new features, rather developer tools updates and improvements. There are also number of tweaks we can introduce to improve testing and tests backporting across branches, which also are not considered neither feature nor bug fix.
(cherry picked from commit 4d6937ef69a55b72ce1c8194cf9c42b913752a73)
> [backport 2.11] changelog: add new topics 'tools' and 'testing'

- changelogs/unreleased/gh-9235-assertion_in_box_wait_limbo_acked.md
- src/box/box.cc
- test/replication-luatest/gh_9235_assertion_in_box_wait_limbo_acked_test.lua
Before this patch there was an execution sequence in which the assertion in box_wait_limbo_acked would fail. The assertion is that the lsn of the last entry in limbo is always positive after wal_sync. Fix it.
Closes #9235
NO_DOC=bugfix
> wal: fix failing assertion in box_wait_limbo_acked

- changelogs/unreleased/gh-9235-assertion_in_box_wait_limbo_acked.md
> changelog: reword gh-9235 changelog

- test/app-luatest/gh_9411_fix_graceful_shutdown_break_on_script_exit_test.lua
- test/box-luatest/gh_9266_fix_on_shutdown_and_osexit_from_cmd_expr_test.lua
I got four fails on the given tests in a row on debug-asan job in CI for tarantool-ee.
It seems, tarantool-ee is more sensitive to small timeouts, when the address sanitizer slows down the execution. Or I'm just lucky.
Anyway, the given tests don't really need small timeouts: increasing it doesn't break any test logic, doesn't increase duration of the test in a successful case and doesn't increase it in case of a failure.
The tests are more stable after the change: I verified it locally by running each of the tests in parallel many times on tarantool built with enabled address sanitizer.
See the following commits for details about the given test cases and the problems behind.
* commit 1fcfb8c2bc8f ("app: start init script event loop explicitly")
* commit 786eb2acdd0a ("main: don't break …
> test: increase timeouts in on_shutdown tests

- changelogs/unreleased/gh-9480-dont-rollback-on-quorum-wait-cancel.md
- src/box/txn.c
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- test/replication-luatest/gh_9480_dont_rollback_on_quorum_wait_cancel_test.lua
During iproto graceful shutdown which is WIP we cancel all iproto request in progress. This causes election_qsync_stress test failure.
We shutdown master on waiting transaction confirmation from quorum (which is never exist in this test). Currently on shutdown we rollback transaction in this state. So that when previous master is restarted after electing new master we don't expect the rollback on previous master.
Let's keep the transaction in limbo if fiber is cancelled as our direction is to do only quorum rollbacks.
Part of #8423
Closes #9480
> replication: don't rollback qsync limbo wait on fiber cancel

- .github/actions/bump-submodule/action.yml
- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/freebsd-12.yml
- .github/workflows/freebsd-13.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/luajit-integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/osx_debug.yml
- .github/workflows/osx_release.yml
- .github/workflows/osx_release_lto.yml
- .github/workflows/osx_static_cmake.yml
- .github/workflows/out_of_source.yml
- .github/workflows/packaging.yml
- .github/workflows/perf_micro.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/reusable_build.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/static_build_pack_test_deploy.yml
Currently, if there is a need to test submodule integration with Tarantool and its integration, it is required to create a PR. That is inconvenient, so this patch introduces the option to run the same jobs that are triggered by the `full-ci` label as reusable workflows with the desired submodule revision. This allows for integration testing of submodules within their designated repositories.
> integration testing

- test/app-tap/datetime.test.lua
- test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
JIT has been disabled for these 2 tests on arm64 to avoid failing due to side-effects of constant rematerialization:
* <app-tap/datetime.test.lua>
* <box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua>
The problem was solved via the commit
c4ec0c7b7a32273b194709934247e81c61b55f06 ("luajit: bump new version"). So, enable JIT compilation for these tests back.
Closes #6599
Closes #8011
NO_CHANGELOG=tests
NO_DOC=tests
(cherry picked from commit 915e0b3a4475b12ec49320421569524dc8488aed)
---
#8446 wasn't backported to the 2.10 branch due to the conflict of pagination tests. So create a separate PR.
> [backport 2.10] test: enable JIT again for flaky tests on arm64

- src/box/lua/ctl.c
The new option is backed by `box.ctl.iproto_lockdown`. It is available only in Enterprise Edition builds.
Needed for tarantool/tarantool-ee#585
NO_DOC=will be added to Enterprise Edition
NO_CHANGELOG=see NO_DOC
> box.ctl: add security.iproto_lockdown option

- src/box/CMakeLists.txt
- src/box/lua/config/instance_config.lua
- src/box/lua/init.c
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patchs adds config options for tarantool config storage, as fhis feature will be implemented in EE.
Also, adds the source file to the build.
Part of https://github.com/tarantool/tarantool-ee/issues/593
> config: introduce options for storage, add source file to the build

- src/box/lua/config/applier/box_cfg.lua
It may contain passwords in box.cfg.replication option and the changed options are printed to logs anyway. No much sense to keep printing the full table.
> config: don't show box.cfg table in debug logs

- src/box/box.cc
- src/box/iproto.cc
- src/box/iproto.h
Also we now can free all resources allocated in iproto threads.
Part of #8423
> iproto: don't use cord_cancel_and_join for iproto shutdown

- changelogs/unreleased/config-relative-config-path.md
- src/box/lua/config/init.lua
- test/config-luatest/work_dir_test.lua
- test/luatest_helpers/server.lua
Before this change the following conditions lead to an error on `config:reload()`.
* `--config <...>` CLI option is passed with a relative config path
* `process.work_dir` config option is set to a non-null value
It is fixed by calculating of an absolute config path on startup.
Part of #8862
> config: support relative path in --config

- changelogs/unreleased/config-compat-options.md
- src/box/CMakeLists.txt
- src/box/lua/config/applier/compat.lua
- src/box/lua/config/init.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/init.c
- src/lua/compat.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/compat_test.lua
The new section `compat` is added to the declarative configuration.
The options are the same as ones provided by the `compat` module. Each can be set to `old` or `new`.
Example:
```yaml
compat:
json_escape_forward_slash: old
```
The list of currently supported options with their defaults:
```yaml
compat:
json_escape_forward_slash: new
yaml_pretty_multiline: new
fiber_channel_close_mode: new
box_cfg_replication_sync_timeout: new
sql_seq_scan_default: new
fiber_slice_default: new
box_info_cluster_meaning: new
binary_data_decoding: new
box_tuple_new_vararg: new
box_session_push_deprecation: old
sql_priv: new
c_func_iproto_multireturn: new
box_space_execute_priv: new
box_tuple_extension: new
box_space_max: new
...
```
The `box_cfg_replication_sync_timeout` option is non-dynamic and it can't …
> config: add compat options

- changelogs/unreleased/config-better-corrupted-snap-diagnostic.md
- src/box/lua/config/configdata.lua
If a given snapshot has no instance or replicaset UUID, give a meaningful diagnostic and fail.
Part of #8862
> config: better diagnostic for a corrupted snapshot

- extra/exports
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/mkversion.lua
- src/box/schema.cc
- test/config-luatest/names_upgrade_test.lua
Each config reload on a node with old schema (less than 3.0.0) lead to the error ER_SCHEMA_NEEDS_UPGRADE. This happened because the relevant code didn't check for schema version before trying to apply the names.
Fix this.
Closes #9502
NO_DOC=bugfix
NO_CHANGELOG=fix in a not yet released behavior
> config: fix automatic names apply before schema upgrade

- src/box/lua/config/applier/sharding.lua
- src/box/lua/config/configdata.lua
- test/config-luatest/basic_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/vars_test.lua
- test/config-luatest/vshard_test.lua
Vshard now supports names instead of UUIDs in configuration. Let's use them and finally drop generating UUIDs in config.
From now on we can recover instances without explicitly passing UUIDs to configuration.
> config: introduce vshard named identification

- .github/actions/bump-submodule/action.yml
It turns out, GitHub actions don't allow `env` usage in their definition. This patch fixes this issue in submodule bump action by moving the environment definition into the executed shell script.
NO_DOC=CI
NO_TEST=CI
> ci: fix action for submodule bump

- src/lua/init.c
- src/main.cc
- src/proc_title.c
This patchset implements two features related to integrity protection:
* reset environment if integrity check is on
* do not run -e chunk if integrity check is on
See more info in the corresponding commit messages.
Part of tarantool/tarantool-ee#585
> Disable runtime tweaks if integrity checks is enabled

- src/box/lua/config/configdata.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
- test/config-luatest/vshard_test.lua
- test/luatest_helpers/server.lua
I accidentally discarded some changes made by @ImeevMA in PR #9385. The previous version of the patchset goes to the main branch as result. I'm very sorry.
This commit returns the code of the last version of the patchset.
The changes are described in https://github.com/tarantool/tarantool/pull/9385#discussion_r1430935585. Quoted here:
> 1. Reduce code duplication in the validation logic. It also
>    eliminates remaining (dead) code that interprets user@ and
>    user:pass@ syntax. And give better error messages in come cases
>    (comma separates URIs for example).
> 2. Forbid {} as an URI to simplify logic in instance_uri.
> 3. Refresh the comments.
Also added copying of an original URI table before a modification to prevent influence of the original URIs from config. See the second …
> config: TLS options support -- follow up

- src/box/box.cc
- src/box/iproto.cc
- src/box/iproto.h
This is a revert of the commit 26acba832c4e ("iproto: don't use cord_cancel_and_join for iproto shutdown") to fix #9507 before release. We need more time to prepare a good patch dealing with the issue.
Closes #9507
> iproto: revert cord_cancel_and_join drop

- changelogs/unreleased/config-credentials-and-ro-alert.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/basic_test.lua
Before this patch a replica adds an alert regarding inability to write new credentials from config on startup. In most cases these new credentials are applied on a master and the warning becomes obsolete. The problem is that it is not removed at this point. A manual `config:reload()` is needed to flush it.
It makes the warning more confusing than helpful. Let's remove it for now.
We can return the alert back in a future, but we should do it together with a logic that drops the alert if the needed data is received from a master.
Part of #8862
> config: drop alert about credentials and RO mode

- changelogs/unreleased/config-start-console-before-box-cfg.md
- src/box/lua/config/applier/console.lua
- src/box/lua/config/init.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/cbuilder.lua
- test/config-luatest/console_test.lua
- test/config-luatest/replicaset.lua
- test/config-luatest/supervised_bootstrap_test.lua
This commit changes the order of configuration appliers and move `console` before `box_cfg`. The `console` applier is adjusted to correctly interpret the configured socket file path before the first box.cfg().
The main reason to change the order is to allow a user to call `box.ctl.make_bootstrap_leader()` for a replicaset that starts in the `replication.boostrap_strategy: supervised` mode.
Part of #8862
> config: start console before first box.cfg() call

- changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md
- src/box/box.cc
- src/box/errcode.h
- src/box/raft.c
- test/box/error.result
- test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua
Fixed a bug when the assertion in `box_promote_qsync` would fail. The assertion is that at the moment when `box_promote_qsync` is executed, no other promote is executed. It turned out that this assertion is basically incorrect. Now after this patch the newly elected leader is trying to repeat `box_promote_qsync` in `box_raft_update_synchro_queue` until it fails due to the fact that some other promotion is currently being executed.
Closes #9263
NO_DOC=bugfix
> box: fix failing assertion in box_promote_qsync

- changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md
- src/box/box.cc
- src/box/errcode.h
- src/box/raft.c
- test/box/error.result
- test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua
Fixed a bug when the assertion in box_promote_qsync would fail. The assertion is that at the moment when box_promote_qsync is executed, no other promote is executed. It turned out that this assertion is basically incorrect. Now after this patch the newly elected leader is trying to repeat box_promote_qsync in box_raft_update_synchro_queue until it fails due to the fact that some other promotion is currently being executed.
Closes #9263
NO_DOC=bugfix
(cherry picked from commit ebe4cd9bd79b7c724f523935fe80d7bc331594fa)
> [backport release/2.11] box: fix failing assertion in box_promote_qsync

- changelogs/2.11.2.md
The release notes states one change as breaking, but the new behavior was enabled on 3.0 branch, see commit 6cb3911681d6 ("box: set default c_func_iproto_multireturn to new"), and not enabled on 2.11 branch.
Thanks @Mons for the notice!
> doc: drop 'breaking change' mark from 2.11.2 notes

- changelogs/unreleased/gh-9539-box-cfg-env-vars-with-query-params.md
- src/box/lua/load_cfg.lua
- test/box-luatest/box_cfg_env_test.lua
`TT_LISTEN` and `TT_REPLICATION` environment variables were interpreted by `box.cfg()` in a confusing way if query parameters with values are present. For example, `localhost:3301?transport=plain` was interpreted as the following map: `{['localhost:3301?transport'] = 'plain'}`. Later, `box.cfg()` looks into this map for known URI fields like `login`, `password`, `uri`, `host`, `service` and so on. It found nothing and doesn't start a listening socket.
The reason of such a behaviour is that the environment value is interpreted as a mapping in the `key=value,key=value` format, because there is `=` in it.
The patch changes this behavior for an `key=value,key=value` environment variable that contains `?` in a key: now such a value is not interpreted as a mapping.
Note: Everything said above …
> box: support TT_* uri env vars with query params

- changelogs/unreleased/config-handle-old-box-cfg-env-variables.md
- src/box/lua/config/source/env.lua
- test/config-luatest/box_cfg_env_test.lua
- test/config-luatest/helpers.lua
- test/config-luatest/vars_test.lua
There may be some confusion, so let's start with a background information.
There are `TT_*` environment variables introduced in commit 1b330121ec7d ("box: set box.cfg options via environment variables"). They're interpreted by the `box.cfg()` call.
There are `TT_*` environment variables introduced in commit 82b0cff9d63b ("config: introduce env source"). They're interpreted by the declarative configuration logic, when tarantool starts with the `--name <...>` CLI option.
box.cfg's env variables have names deduced from box.cfg option names, while config's env variable names are deduced from the config schema.
Some options have the same names here and there, for example `TT_REPLICATION_ANON` (from `box.cfg.replication_anon` and `replication.anon`). However, there are ones that have different …
> config: handle box.cfg's TT_* env vars

- changelogs/unreleased/gh-5717-transactional-event-triggers.md
- perf/memtx.cc
- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/lua/func_adapter.c
- src/box/space.c
- src/box/space.h
- src/box/txn.c
- src/box/txn.h
- src/box/txn_event_trigger.c
- src/box/txn_event_trigger.h
- src/lib/core/func_adapter.h
- test/engine-luatest/gh_5717_txn_event_triggers_test.lua
- test/unit/lua_func_adapter.c
This patch introduces 3 new transaction-related events, that can be used for setting user-defined triggers:
* `box.before_commit` - triggered when a transaction is ready to commit;
* `box.on_commit` - triggered when a transaction is committed;
* `box.on_rollback` - triggered when a transaction is rolled back.
Each of them have 3 versions, e.g. `box.on_commit` event has:
* `box.on_commit` - global version, called for all transactions;
* `box.on_commit.space.test` - called for transactions that write to space "test";
* `box.on_commit.space[512]` - called for transactions that write to space with id 512.
These triggers are implemented via the [new trigger registry](https://github.com/tarantool/tarantool/pull/8622) and work independently from the core `on_commit` and `on_rollback` triggers. …
> box: introduce transactional event triggers

- src/lib/core/event.c
- src/lib/core/event.h
- src/on_shutdown.c
- test/box-luatest/gh_9275_remove_on_shutdown_trigger_while_run_test.lua
- test/unit/event.c
Since on_shutdown triggers are fired asynchronously in their own fibers, they are not referenced by `event_trigger_iterator`. That's why, if on_shutdown trigger is deleted while it is running (or is scheduled to run), it will be instantly removed, and when it is finished, segmentation fault will happen on its finalizer (`func_adapter_end`). Let's reference all on_shutdown triggers to prevent such situation - they will be deleted soon along with the whole event subsystem.
Closes #9275
> box: fix crash when on_shutdown trigger is removed

- src/httpc.c
Commit 0ea1ba877b8e ("third_party: update libcurl from 8.3.0 to 8.4.0") bumps libcurl version and bringed a regression: http client returns nothing using connection with HTTP/2 protocol. The problem could be reproduced by etcd-client, see description in issue [1]. The problem in http client is due to commit "h2: testcase and fix for pausing h2 streams" [2] in libcurl. With reverted commit in libcurl the problem is gone.
To work around the issue, commit sets HTTP 1.1 as default protocol in http client.
Needed for #9547
1. https://github.com/tarantool/tarantool/issues/9547
2. https://github.com/curl/curl/commit/6b9a591bf7d82031f463373706d7de1cba0adee6
NO_CHANGELOG=workaround
NO_DOC=workaround
NO_TEST=etcd client's tests in Tarantool EE
> [3.0] httpc: use http 1.1 by default

- .test.mk
This reverts commit b471fc97ba0b8e0260585593044c70274a754ccb.
Tests for GC finalizers were patched in the luajit submodule. The submodule was updated in
commit 1a0bafd5250eb8103d46e3437ce3b23c9ccbbdf7.
NO_DOC=Revert CI hack
NO_TEST=Revert CI hack
NO_CHANGELOG=Revert CI hack
> Revert "ci: temporarily patch GC finalizer test"

- src/box/box.cc
- src/box/errcode.h
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/iproto.c
- test/app-luatest/shutdown_test.lua
- test/box/error.result
Also we now can free all resources allocated in iproto threads.
Part of #8423
> iproto: don't use cord_cancel_and_join for iproto shutdown V2

- test/box-luatest/box_cfg_env_test.lua
**This is a backport of a testing scenario from PR #9544 to the `release/2.10` branch.**
----
This commit backports a test from commit dde7342c5207 ("box: support TT_* uri env vars with query params") except JSON and mapping test cases. The excluded test cases require commit cd58c321bc49 ("box: allow to set box.cfg table value via env var"), which is not part of 2.10.
The test aims to verify a problem in `TT_LISTEN` and `TT_REPLICATION` environment variables parsing, when they interpret an URI with query parameters. For example,
```sh
export TT_LISTEN=localhost:3301?transport=plain
```
Tarantool 2.10 is not affected by the problem, but this commit adds a test regarding it into the test suite.
Relates to #9539
Relates to PR #9544
> [backport 2.10] test: verify query params in TT_* uri env vars

- changelogs/unreleased/gh_9572_config_with_uuids.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/gh_9572_config_with_uuids_test.lua
Currently a leader fails to start with `attempt to index a nil value` error, when all UUIDs are specified in config. This is caused by the fact, that we try to apply names to the instance, which have not joined yet, _cluster record doesn't exist.
We must skip such names. Alert will be dropeed automatically as soon as the instance is joined.
Closes #9572
NO_DOC=bugfix
> config: fix leader failing to start when uuids are set

- changelogs/unreleased/gh_9572_config_with_uuids.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/gh_9572_config_with_uuids_test.lua
**This is backport of PR #9573 to the `release/3.0` branch.**
---
Currently a leader fails to start with `attempt to index a nil value` error, when all UUIDs are specified in config. This is caused by the fact, that we try to apply names to the instance, which have not joined yet, _cluster record doesn't exist.
We must skip such names. Alert will be dropeed automatically as soon as the instance is joined.
Closes #9572
> [backport 3.0] config: fix leader failing to start when uuids are set

- test/justrun.lua
- test/treegen.lua
The list of changes:
* f81b1aaca3607664c033392a66301e4746f8b3cc test: return a dir from treegen.prepare_directory()
* 8c3b4c088236161f76955e86e8ce96f24671c973 test: adjust treegen for TMPDIR ending with slash
* 028c65e04389cafd02d31fa70147b1e1b1f93217 test: reset readline configuration for justrun too
* 9b0896d9e63143ce4e894365639c431f682b2958 test: make treegen.clean more durable
* 761273f26deba5911e2e04d2c3b2c855fe864846 test: allow to quote CLI arguments in justrun
> [backport 2.11] test: pull treegen and justrun changes from master

- test/justrun.lua
- test/treegen.lua
The list of changes:
* f81b1aaca3607664c033392a66301e4746f8b3cc test: return a dir from treegen.prepare_directory()
* 8c3b4c088236161f76955e86e8ce96f24671c973 test: adjust treegen for TMPDIR ending with slash
* 028c65e04389cafd02d31fa70147b1e1b1f93217 test: reset readline configuration for justrun too
* 9b0896d9e63143ce4e894365639c431f682b2958 test: make treegen.clean more durable
* 761273f26deba5911e2e04d2c3b2c855fe864846 test: allow to quote CLI arguments in justrun
> [backport 2.10] test: pull treegen and justrun changes from master

- test/box/lua/utils.lua
- test/box/net.box_reconnect_after_gh-3164.result
- test/box/net.box_reconnect_after_gh-3164.test.lua
test: fix flaky tests when JIT is enabled
<box/net.box_reconnect_after_gh-3164.test.lua> and <vinyl/tx_gap_lock.test.lua> checking some objects that should be collected may fail because these objects are referenced as the upvalues for a function inlined on some JIT trace. The objects aren't leaked; tests don't consider the JIT semantics. See more details in [1].
This patch disables JIT for the first test.
The second test itself isn't affected since the commit tarantool/test-run@33fbace8307e64e66b0b2178ac952b2697673917 ("Add default server restart to each test run"). Because of this commit, the `tx.gap_locks` can't be affected by the use of the `create_iterator()` function in other tests.
But to avoid similar situations in the future, the JIT is disabled for the `res.next()` function in …
> test: fix flaky tests when JIT is enabled

- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/index.cc
- src/box/index.h
- src/box/index_weak_ref.c
- src/box/index_weak_ref.h
- src/box/memtx_bitset.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/sql.c
- src/box/sysview.c
- src/box/vinyl.c
An iterator doesn't pin the index it was created for. Instead, it holds a 'weak' reference to it, which is invalidated if the index is dropped. This is achieved by checking if the index can be found in the space cache by id every time the reference is accessed. Let's factor out this weak reference concept into a separate class so that we can reuse it because we'll also need it to implement the index scanner API.
Needed for #9568
> index: introduce weak reference

- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/engine.h
- src/box/index.cc
- src/box/index.h
- src/box/memcs_engine.h
- src/box/memtx_engine.cc
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/sequence.c
- src/trivia/config.h.cmake
- test/wal_off/alter.result
- test/wal_off/alter.test.lua
This PR makes a few changes required to implement the new in-memory column storage engine in Tarantool Enterprise Edition:
- Ability to reuse the memtx checkpoint and join machinery in other engines. The new engine will implement a read view so we'll get checkpoint and join for free because the memtx implementation is effectively generic and depends only on the read view feature.
- Read view iterator destructor. Memtx doesn't need one so it uses the generic implementation, but the new engine will need to some deallocations when a read view iterator is destroyed.
- Memcs engine stubs. The stubs will be implemented in the tarantool-ee repository.
Needed for tarantool/tarantool-ee#617
**EE PART** https://github.com/tarantool/tarantool-ee/pull/626
> In-memory column storage engine stub

- .github/workflows/freebsd.yml
- Drop testing for FreeBSD 12 since FreeBSD 14 is available
- Add testing for FreeBSD 14
> ci: drop testing for FreeBSD 12, add for FreeBSD 14

- src/box/space_cache.c
- src/box/space_cache.h
- test/unit/vy_point_lookup.c
In contrast to `space_cache_find()`, `space_by_id()` doesn't cache the last looked up space to speed up following lookups. This is confusing, because one would expect the only difference between `space_cache_find()` and `space_by_id()` functions to be that the former sets diag while the latter doesn't. Let's move the `prev_space` cache to `space_by_id()` to fix this issue.
To achieve that we need to make `space_by_id()` inline, which is tricky because it's called via FFI. We work around that by defining a macro `space_by_id()` which expands to `space_by_id_fast()` while still keeping the `space_by_id()` symbol for FFI.
Last but not least, we make the last cached space global (currently it's instantiated once per each `space_cache_find()` call site). This is a good thing because we often …
> space: optimize lookup by id

- .github/workflows/freebsd.yml
This patch fixes the following issue:
Error: Unable to retrieve job ID by provided job name
The `${{ github.job }} (${{ join(matrix.*, ', ') }})` expression was evaluated to `freebsd (Object)` instead of proper job name. It looks like the ChristopherHX/github-act-runner agent has a bug somewhere. Now the job name is made manually to bypass the issue.
> ci: fix fail on artifact upload to S3 for freebsd

- .github/actions/report-job-status/action.yml
- .github/workflows/freebsd.yml
The ChristopherHX/github-act-runner agent evaluates expression `join(matrix.*, ', ')` to `Object` instead of `a, b, c`. So let's have the facility to specify the job name manually to avoid the issue.
> ci: fix job name in freebsd failure report

- changelogs/unreleased/fix-lua-loader-error-handling.md
- src/lua/init.c
- src/lua/loaders.lua
- test/app-luatest/fix_lua_loader_error_handling_test.lua
This patchset implements the refactoring of Tarantool `package.loaders` required for Tarantool integrity protection (needed for tarantool/tarantool-ee#585).
**Per-patch review is highly recommended (though GitHub works badly in this mode).**
Since Tarantool follows [Lua 5.1 semantics](https://www.lua.org/manual/5.1/manual.html), the set of routines in package.loaders is used to tweak Lua modules loading. E.g. overriding
machinery has been implemented on top of the `package.loaders`. Unfortunately, `package.loaders` are not such flexible as it's needed and this mechanism is redesigned in [Lua 5.2](https://www.lua.org/manual/5.2/manual.html).
Starting from Lua 5.2 package.loaders has been superseded by `package.searchers`. This is quite natural change, since nobody wants to tweak the …
> Rework Lua module searchers and loaders

- src/box/index_def.c
- src/box/index_def.h
- src/box/memtx_space.c
- src/box/tuple_compare.cc
- src/box/vinyl.c
- test/engine-luatest/gh_9548_fixed_size_numeric_types_test.lua
The types added by commit 2e0f9a3c265e ("box: introduce fixed-size numeric field types") can't be indexed. Fix it.
Closes #9611
> box: allow indexing of fixed-size numeric field types

- changelogs/unreleased/ghe-647-config-etcd-watchers-options.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
These options are needed to properly set up reconnection of etcd watchers.
Needed for https://github.com/tarantool/tarantool-ee/issues/647
> config: introduce config.etcd.watchers options

- .github/workflows/osx.yml
It has been decided to have only release and debug builds for testing on two latest macOS versions (at this momemnt, 13 and 14). Static and LTO builds are dropped.
> ci: update matrix strategy for osx testing

- perf/lua/CMakeLists.txt
- perf/lua/column_scan.lua
- perf/lua/column_scan_module.c
The test creates a space with 1 million rows and 100 columns storing unsigned integer values (both row and column count are configurable) and sums values over the first and the last columns.
By default the test uses the iterator C API but one may switch to the column scanner C API and/or raw read view C API (both features are exclusive to the Enterprise Edition).
It's also possible to specify the engine to use (default is memtx).
Closes tarantool/tarantool-ee#659
> perf: add column scan test

- src/box/tuple_format.c
- src/box/tuple_format.h
- src/box/xrow_update.c
- src/box/xrow_update.h
- src/lib/salad/rope.h
`tuple_field_validate()`, `xrow_update_init()` and `xrow_update_read_ops()` will be used by the `memcs` engine, which is part of Tarantool Enterprise Edition.
Needed for tarantool/tarantool-ee#628
> box: introduce `tuple_field_validate()`

- cmake/CheckDependencies.cmake
- cmake/compiler.cmake
This patch fixes the following error when building tarantool statically with Clang compiler on a Linux system:
clang: error: argument unused during compilation: '-static-libstdc++'
Fixes #9646
> build: fix static build error when compiling with Clang

- src/box/box.cc
- src/box/watcher.c
- src/box/watcher.h
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- test/unit/fiber.cc
- test/unit/watcher.c
Fix an issue with client fibers shutdown and disable client code execution thru watcher callbacks during shutdown.
Part of #8423
> Client fibers shutdown fixes

- src/box/lua/config/init.lua
- test/config-luatest/basic_test.lua
*(This is backport of PR #9623 to the `release/3.0` branch, future 3.0.2 release.)*
----
This patch changes when extras.post_apply() is executed. Previously, it would only run if a _post_apply() was successful and all previous reload steps completed properly. It will now be executed, even if some reload steps failed.
Note that if an error appears during startup, Tarantool will stop and extras.post_apply() will not be executed.
Also note that if the startup or restart is successful, there will be no change in behavior due to this patch.
Needed for https://github.com/tarantool/tarantool-ee/issues/643
> [backport 3.0] config: call extras.post_apply() if reload failed

- changelogs/unreleased/gh-9491-last-local-row-tx-boundary.md
- src/box/recovery.cc
- test/replication-luatest/gh_9491_local_space_tx_boundary_test.lua
We've had numerous problems with transaction boundaries in replication.
They were mostly caused by various cases when either the beginning or
end of the transaction happened to be a local row. Local rows are not
replicated, so the peer saw "corrupted" transactions with either no
beginning or no end flag, even though the transaction contents were
fine.
The problem with starting a transaction with a local row was solved in
commit f41d1ddd5faf ("wal: fix tx boundaries"), and that fix seems to
continue working fine to this day.
The problem with ending transactions with a local row was first fixed
in commit 25382617b957 ("replication: append NOP as the last tx row"),
however there were problems with this approach: when a user tried to
write to local spaces on a replica from a replication …
> Once again fix transaction boundaries in replication for txs ending with a local row

- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/box.h
- src/box/gc.c
- src/box/lua/config/instance_config.lua
- src/box/lua/info.c
- src/box/lua/init.c
- src/box/lua/load_cfg.lua
- src/box/lua/wal_retention_period.h
- src/box/retention_period.h
- src/box/wal.c
- src/box/wal.h
- src/box/xlog.c
- src/box/xlog.h
- src/lib/vclock/vclock.h
- src/trivia/config.h.cmake
- test/box/box.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
- test/unit/vclock.cc
- test/unit/vclock.result
This PR adds a new configuration option wal_retention_period and
function stubs for it. It's needed to avoid rebootstrap on anonymous
replicas, as Tarantool doesn't save xlog for them.
* wal_retention_period. Type: double. Default: 0. Unit: seconds.
Description: When xlog file is closed it won't be immediately
deleted by garbage collector if wal_retention_period is set to
non-zero value. wal_retention_delay determines how many seconds
after closing this file should be saved. During instance restart
the timeout is set to 'wal_retention_period - time' passed since
file modification.
The option is dynamic. Its value is stored and used in C code, so we
define configuration callbacks in EE: cfg_set_wal_retention_period.
Needed for https://github.com/tarantool/tarantool-ee/issues/513
NO_DOC=EE …
> wal: add stubs for wal_retention_period

- changelogs/unreleased/gh-8074-fix-backtraces-on-m1-macs.md
- src/box/lua/console.lua
- src/lib/core/backtrace.c
Just a regular backport of #8818 and #9267 via a pull request to verify changes.
> [2.10] Missing backports needed for OSX testing

- changelogs/unreleased/gh-9649-config-get-in-roles.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
*(This is backport of PR #9651 to the `release/3.0` branch, a future `3.0.2` release.)*
----
Roles are now started and stopped at the "post_apply" stage rather than at the "apply" stage. This allows require('config'):get() to correctly return the configuration that is being applied.
Closes #9649
> [backport 3.0] config: move role start and stop to _post_apply()

- src/box/key_def.c
- src/box/key_def.h
- test/unit/key_def.cc
This function returns a `key_def` part by a field number. However, currently it returns `NULL` for parts that contain a JSON path to indexed data. Fix it.
Needed for tarantool/tarantool-ee#671
> key_def: ignore json path in `key_def_find_by_fieldno`

- src/box/key_def.c
- src/box/key_def.h
- test/unit/key_def.cc
This function returns a key_def part by a field number. However, currently it returns NULL for parts that contain a JSON path to indexed data. Fix it.
Needed for tarantool/tarantool-ee#671
NO_DOC=bugfix
NO_CHANGELOG=not visible in CE
(cherry picked from commit cb0264c3cac00c288f9a0b4614f203d1c4b157ab)
> [backport 3.0] key_def: ignore json path in key_def_find_by_fieldno

- src/box/key_def.c
- src/box/key_def.h
- test/unit/key_def.c
This function returns a key_def part by a field number. However, currently it returns NULL for parts that contain a JSON path to indexed data. Fix it.
Needed for tarantool/tarantool-ee#671
NO_DOC=bugfix
NO_CHANGELOG=not visible in CE
(cherry picked from commit cb0264c3cac00c288f9a0b4614f203d1c4b157ab)
> [backport 2.11] key_def: ignore json path in key_def_find_by_fieldno

- test/app/digest.result
- test/app/digest.test.lua
After we moved osx testing from the per-commit to nightly basis [1], we accidentally enabled running tarantool tests on macOS/M1 for 2.10. So we had some tests failed, and they were fixed by cherry-picking a few commits from the master branch [2]. Also, some tests were fixed by updating test-run to the new version [3] with needed fix [4]. So it's time to fix the last failed test (test/app/digest.test.lua) on macOS/M1 by disabling JIT in it due to the issue [5].
[1] https://github.com/tarantool/tarantool/pull/9571
[2] https://github.com/tarantool/tarantool/pull/9672
[3] https://github.com/tarantool/tarantool/pull/9685
[4] https://github.com/tarantool/test-run/pull/422
[5] https://github.com/tarantool/tarantool/issues/6097
---
Tested on macOS/M1 as well:
```
...
Top 10 longest tests …
```
> [2.10] test: disable JIT in test/app/digest.test.lua

- CMakeLists.txt
- changelogs/unreleased/gh-9580-fix-cpath-for-external-libs.md
In Linux systems based on Debian, libraries are installed in paths depending on the architecture. For example, /usr/lib/x86_64-linux-gnu/, /usr/lib/aarch64-linux-gnu/. Some packages may be installed in these paths, but Tarantool does not look for libraries installed in these paths. This patch solves the problem.
Also remove redundant OS depended `if` branches.
Fix #9580
> build: fix package.cpath for debian based distros

- changelogs/unreleased/gh-8140-crash-in-allocator.md
- changelogs/unreleased/gh-9145-luajit-fixes.md
- changelogs/unreleased/gh-9595-luajit-fixes.md
* test: fix initialization in lj-549-lua-load.test.c
* codehealth: add `nd` to the codespell ignore list
* LJ_GC64: Always snapshot functions for non-base frames.
* Avoid assertion in case of stack overflow from stitched trace.
* Fix recording of __concat metamethod.
* Avoid out-of-range number of results when compiling select(k, ...).
* Consider slots used by upvalues in use-def analysis.
* Only emit proper parent references in snapshot replay.
* Optimize table.new() with constant args to (sinkable) IR_TNEW.
* Followup fix for embedded bytecode loader.
* Fix embedded bytecode loader.
* LJ_GC64: Fix HREFK optimization.
* Fix unsinking of IR_FSTORE for NULL metatable.
* Fix zero stripping in %g number formatting.
* Follow-up fix for stack overflow handling cleanup.
* Cleanup stack overflow …
> [backport/release/3.0] luajit: bump new version

- changelogs/unreleased/gh-9104-allow-to-set-error-payload.md
- src/box/lua/error.cc
- test/box-luatest/error_subsystem_improvements_test.lua
Now it is possible to add a custom payload to the error on error construction. The payload is passed as key-value pairs, where `key` is a string, and `value` is any Lua object. The key name can be arbitrary except it should not be the same as any of the built-in error field name: reason, code, type, base_type, custom_type, errno, message, prev, trace.
E.g.:
```
box.error.new({ reason = string[, code = number, type = string, key1 = value1, ...] }])
```
Or:
```
box.error({ reason = string[, code = number, type = string, key1 = value1, ...] }])
```
Closes #9104
> box/lua: allow to set custom error payload fields

- .github/workflows/almalinux_8.yml
- .github/workflows/almalinux_8_aarch64.yml
- .github/workflows/almalinux_9.yml
- .github/workflows/almalinux_9_aarch64.yml
- rpm/tarantool.spec
Add the `almalinux_8.yml / almalinux_9.yml` and `almalinux_8_aarch64.yml / almalinux_9_aarch64.yml` workflow files to build Tarantool packages for x86_64 and aarch64 platforms.
Closes #9706
Closes #9434
> [2.11] ci: add AlmaLinux 8, 9

- .github/workflows/integration.yml
In commit 3daf2399dd5b ("ci: fix step parameters for reusable runs") the integration workflow was made reusable, but concurrency group pattern modification that was done for other workflows made reusable in the same patch was forgotten. This patch fixes the mentioned issue.
NO_DOC=CI
NO_TEST=CI
> ci: fix integration concurrency group

- changelogs/unreleased/gh-9102-error-new-message-arg.md
- src/box/lua/error.cc
- test/box-luatest/error_subsystem_improvements_test.lua
This patch add a `message` option to the table constructor of `box.error.new`.
Closes #9102
> lua: add `message` argument to table constructor of `box.error.new`

- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/box.h
- src/box/gc.c
- src/box/lua/info.c
- src/box/lua/init.c
- src/box/lua/load_cfg.lua
- src/box/lua/wal_retention_period.h
- src/box/retention_period.h
- src/box/wal.c
- src/box/wal.h
- src/box/xlog.c
- src/box/xlog.h
- src/lib/vclock/vclock.h
- src/trivia/config.h.cmake
- test/box/box.lua
- test/unit/vclock.cc
- test/unit/vclock.result
Renamed to `experimental_wal_retention_period`
> Backport "wal: add stubs for wal_retention_period" to 2.11

- changelogs/unreleased/gh-9694-memory-leak-in-error_object-set_prev.md
- src/lua/error.lua
By design, the error references its cause, see `error_set_prev()` in `diag.c`.
Referencing the error from `error_set_prev()` in `error.lua` is wrong.
Introduced by commit 2e3c81deea50 ("error: use int64_t as reference counter").
Closes #9694
> lua: fix memory leak in `error_object:set_prev()`

- .github/workflows/fedora_39.yml
- .github/workflows/fedora_39_aarch64.yml
Add the fedora_39.yml and fedora_39_aarch64.yml workflow files to build Tarantool packages for x86_64 and aarch64 platforms.
Closes #9705
> [2.11] ci: add `Fedora 39`

- changelogs/unreleased/gh-9694-memory-leak-in-error_object-set_prev.md
- src/lua/error.lua
By design, the error references its cause, see error_set_prev() in diag.c. Referencing the error from error_set_prev() in error.lua is wrong. Introduced by commit 2e3c81deea50 ("error: use int64_t as reference counter").
Closes #9694
NO_DOC=bugfix
NO_TEST=memory leak
(cherry picked from commit d08dbcbf09842a0223887364f2b80caf3c23f129)
> [backport 3.0] lua: fix memory leak in `error_object:set_prev()`

- changelogs/unreleased/gh-9694-memory-leak-in-error_object-set_prev.md
- src/lua/error.lua
By design, the error references its cause, see error_set_prev() in diag.c. Referencing the error from error_set_prev() in error.lua is wrong. Introduced by commit 2e3c81deea50 ("error: use int64_t as reference counter").
Closes #9694
NO_DOC=bugfix
NO_TEST=memory leak
(cherry picked from commit d08dbcbf09842a0223887364f2b80caf3c23f129)
> [backport 2.11] lua: fix memory leak in `error_object:set_prev()`

- src/box/box.cc
- src/box/box.h
- src/main.cc
- test/box-luatest/shutdown_test.lua
We create a snapshot on SIGUSR1 signal in a newly spawned system fiber. It can interfere with Tarantool shutdown. In particular there is an assertion on shutdown during such a snapshot because of cord making snaphshot. Let's just trigger making snapshot in gc subsystem in it's own worker fiber.
```
#5  0x00007e7ec9a54d26 in __assert_fail (
assertion=0x63ad06748400 "pm_atomic_load(&cord_count) == 0",
file=0x63ad067478b8 "./src/lib/core/fiber.c", line=2290,
function=0x63ad06748968 <__PRETTY_FUNCTION__.6> "fiber_free") at assert.c:101
#6  0x000063ad061a6a91 in fiber_free ()
at /home/shiny/dev/tarantool/src/lib/core/fiber.c:2290
#7  0x000063ad05edc216 in tarantool_free ()
at /home/shiny/dev/tarantool/src/main.cc:632
#8  0x000063ad05edd144 in main (argc=1, argv=0x63ad079ca3b0)
```
Part of …
> app: shutdown fiber creating snapshot triggered by signal

- src/box/lua/config/applier/credentials.lua
- src/box/lua/config/utils/aboard.lua
- test/config-luatest/credentials_applier_test.lua
*(This is backport of PR #9691 to the `release/3.0` branch -- future `3.0.2` release.)*
----
Before this patch, it was possible that the config status could change to 'ready' even if there were pending alerts. This could happen if there were 'missed_privilege' warnings. Before this patch, warnings were cleared and then refilled if necessary. However, after clearing all these warnings, if there were no other warnings, the status was set to 'ready'. And if new warnings were added during the 'refilling' stage, the status did not change from 'ready' to 'check_warnings' or 'check_errors'.
Part of #9689
> [backport 3.0] config: fix wrong status after setting permissions

- changelogs/unreleased/gh-9103-error-new-prev-arg.md
- src/box/lua/error.cc
- test/box-luatest/error_subsystem_improvements_test.lua
Currently, it's only possible to set an error cause with the set_prev method. This isn't very convenient, because one has to construct a new error without raising it, then set its cause, and only then raise it. To simplify this, a new argument `prev` is added to the error constructor.
Closes #9103
[Link to the design document](https://www.notion.so/tarantool/Error-subsystem-improvements-90faa0a4714b4143abaf8bed2c10b2fc?pvs=4#c72c870f24734020aae1fbf34e2b8569)
> box/lua: allow to set error cause via `prev` argument

- src/box/box.cc
- src/box/iproto.cc
- src/box/iproto.h
- src/box/lua/ctl.c
- src/box/lua/feedback_daemon.lua
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- test/box-luatest/shutdown_test.lua
- test/unit/fiber.cc
Let's panic in such a case.
Part of #8423
Testing of `iproto_drop_connections()` is done in EE PR https://github.com/tarantool/tarantool-ee/pull/691.
> handle iproto request or client fiber hang on shutdown

- src/box/box.cc
- src/lib/core/fiber.c
- test/unit/fiber.cc
- test/vinyl-luatest/shutdown_test.lua
In the commit d40ce0fa028a ("core: disable fibers creation after shutdown started") we disable creation of new fibers in the process of shutdown. This may cause subsystem shutdown hanging.
The thing is we need fiber pool working during shutdown. For example vinyl engine uses it through "tx" endpoint. Fibers in the pool are finished after idle timeout. So we may have a situation when there is no idle fibers in the pool and we cannot create a new one.
Part of #8423
> fiber: allow creating system fibers during shutdown

- changelogs/unreleased/gh-9717-fix-crash-on-new-connection-drop.md
- src/box/iproto.cc
- test/box-luatest/shutdown_test.lua
We need to handle case of dropping new connection. When `net_send_greeting()` is executed the connection can be closed due to `iproto_drop_connections()` call.
Note that in the test the Tarantool crashes for another reason. Due to access after sleep to the connection that is destroyed so its memory is poisoned. Yet we visit `net_send_greeting()` too in the test with patch so original issue is verified too. We also need to test that such a connection is closed. This will be done in EE version.
Closes #9717
There is an additional test in the EE PR https://github.com/tarantool/tarantool-ee/pull/692
> iproto: fix assertion on dropping of a new connection

- CMakeLists.txt
- changelogs/unreleased/add-test-build-flag-to-tarantool-build.md
- src/lua/init.c
- src/trivia/config.h.cmake
- test/app-luatest/tarantool_package_test.lua
In the commit 22d507d5e968 ("iproto: don't hang on uncancellable iproto request") we used `TEST_BUILD` define which is absent, we only have a CMake build option with such name. Let's add a define too.
While at it let's also show this flag in the `tarantool.build` table.
Follow-up #8423
> build/lua: add TEST_BUILD define/tarantool.build flag

- src/box/alter.cc
- src/box/memtx_space.c
- src/box/vinyl.c
We assume that if the new format can store tuples matching the old format, we can update the space format without calling the engine `check_format` callback. This is true for both memtx and vinyl but not for memcs (EE), which doesn't support extending field types (e.g. changing int16 to int32).
Let's call the engine check_format callback unconditionally and let it decide whether tuple format checking can be skipped.
Needed for tarantool/tarantool-ee#694
> alter: move format compatibility check to `space_check_format`

- rpm/tarantool.spec
- test/app-tap/iconv.skipcond
Enable LTO in the rpm spec file for RedOS 7+. Otherwise, we are getting a compilation error.
> build: enable LTO for RedOS 7

- test/box-py/args.result
- test/box-py/args.test.py
There are two reasons for this changeset:
* The positive one: Tarantool supports -b and -j options to use LuaJIT modules since the commit bf8b76a4dfc9dd62d4131e90e2ae5d83843b6630 ("lua: proxy -j and -b flags"), so the related tests from lua-Harness suite can be partially (since -O option is still not implemented in Tarantool) enabled.
* The negative one: Tarantool diff-based tests for CLI interfaces are hard to maintain, if any change occurs in LuaJIT modules, since the aforementioned tests implement dumb comparison of the output, produced by the current CLI version against the expected one, provided by the .result file. Hence, to rule the tests related to LuaJIT CLI interface in a more convenient way, the corresponding tests should be moved from the tests in Tarantool repository to the …
> Remove LuaJIT-related CLI tests

- cmake/CheckDependencies.cmake
- src/CMakeLists.txt
If we run a static build with ASAN enabled via Clang 16, the build will fail unless `libresolv` is in the white list of static dependencies. It looks like it is a peculiarity of Clang 16 and higher.
Fixes https://github.com/tarantool/tarantool/issues/9740
> cmake: add libresolv to static dependency list

- .github/workflows/lint.yml
It brings newer codespell version: 2.1.0. Ubuntu Focal offers 1.16.0.
Fixes tarantool/checkpatch#70
> ci: use Ubuntu Jammy for checkpatch

- .github/workflows/lint.yml
*(Backport of PR #9752 to `release/2.10`.)*
----
It brings newer codespell version: 2.1.0. Ubuntu Focal offers 1.16.0.
Fixes tarantool/checkpatch#70
> [backport 2.10] ci: use Ubuntu Jammy for checkpatch

- src/box/CMakeLists.txt
- src/box/lua/config/utils/odict.lua
- src/box/lua/init.c
- test/config-luatest/odict_test.lua
In development of the configuration module we met several cases, when an order of appearance of some items is as important as a constant time access using a key.
This commit adds a collection that serves such a need. It is to be used internally in the src/box/lua/config code.
The module is inspired by Python's collections.OrderedDict. See the description in the module code for details.
> config: add ordered dictionary (internal module)

- changelogs/unreleased/gh-9101-hide-error-unpack-redundant-fields.md
- src/box/lua/config/instance_config.lua
- src/lua/compat.lua
- src/lua/error.lua
- test/box-luatest/error_subsystem_improvements_test.lua
- test/config-luatest/cluster_config_schema_test.lua
> Hide redundant fields of box.error.unpack()

- src/box/lua/misc.cc
- test/engine-luatest/gh_6436_tuple_constraint_test.lua
- test/unit/CMakeLists.txt
- test/unit/lua_test_utils.h
- test/unit/port.cc
The patch introduces new `unit/port.cc` test that covers almost all port implementations and almost all port methods. This test was intended as a testing point for future port changes.
Implementations `port_sql` and `port_vdbemem` and method  `dump_vdbemem` are not tested because I don't know much about the sql subsystem. For the same reason, I didn't tested `port_dump_msgpack_with_context`. Method `dump_msgpack_16` is not actually supported, but it is still used for compatibility with very old connectors. The problem is I found a bug in `port_c_dump_msgpack_16` while writing the test, and we don't want to fix it - probably, we will get rid of this method in future. Method `dump_plain` is not tested because it requires functions from `console.lua` file - it is easier to test …
> Cover some implementations of `port` interface with tests

- changelogs/unreleased/fix-yaml-alias-serialization.md
- src/lua/serializer.c
- src/lua/serializer.h
- src/lua/utils.c
- src/lua/utils.h
- test/app-luatest/serializer_test.lua
- test/box/tuple.result
- third_party/lua-yaml/lyaml.cc
The #8350 was introduced by the commit b42302f52ada ("lua-yaml: enable aliasing for objects returned by __serialize") so the patch is effectively reversed.
The idea is to call all object __serialize methods recursively before finding references. The new serialization pass stores the mapping from the original object to the serialized representation.
After this, the reference analysis pass and the encoding pass use this mapping to replace original objects with the serialized representation.
As result, the reference analysis has a complete information about objects and no references are missed.
Closes #8350
Closes #8310
Closes #8321
----
*(This is an alternative implementation of PR #9736.)*
> lyaml: fix alias serialization

- changelogs/unreleased/gh-9105-increase-error-serialization-verbosity.md
- src/box/lua/config/instance_config.lua
- src/lua/compat.lua
- src/lua/error.lua
- src/lua/msgpack.c
- src/lua/serializer.c
- src/lua/serializer.h
- test/box-luatest/error_subsystem_improvements_test.lua
- test/box/net.box_error_extension_feature.result
- test/box/net.box_error_extension_feature.test.lua
- test/config-luatest/cluster_config_schema_test.lua
This patch increases error serialization verbosity.
Closes #9105
> lua: increase error serialization verbosity

- changelogs/unreleased/fix-yaml-alias-serialization.md
- src/lua/serializer.c
- src/lua/serializer.h
- src/lua/utils.c
- src/lua/utils.h
- test/app-luatest/serializer_test.lua
- test/box/tuple.result
- third_party/lua-yaml/lyaml.cc
*(This is a backport of PR #9777 to the `release/3.0` branch, future `3.0.2` release.)*
----
The #8350 was introduced by the commit b42302f52ada ("lua-yaml: enable aliasing for objects returned by __serialize") so the patch is effectively reversed.
The idea is to call all object __serialize methods recursively before finding references. The new serialization pass stores the mapping from the original object to the serialized representation.
After this, the reference analysis pass and the encoding pass use this mapping to replace original objects with the serialized representation.
As result, the reference analysis has a complete information about objects and no references are missed.
Closes #8350
Closes #8310
Closes #8321
> [backport 3.0] lyaml: fix alias serialization

- changelogs/unreleased/ghe-643-set-status-after-post-apply.md
- src/box/lua/config/init.lua
- test/config-luatest/app_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/roles_test.lua
*(This is a backport of PR #9773 to `release/3.0`, future `3.0.2` release.)*
----
Previously, the config status was set after the "apply" phase, and then set again after the "post_apply" phase. This can lead to a situation where the status becomes "ready" after the "apply" phase and changes to "check_errors" or "check_warnings" after the "post_apply" phase. Because of this, it was possible that config:reload() may be called from a role or an app even if though the config loading is not finished.
Note that due to this change, the "startup_in_progress" and "reload_in_progress" statuses are now expanded to include the "post_apply" phase.
Also note that the status still changes before the "extras.post_apply" stage.
Needed for https://github.com/tarantool/tarantool-ee/issues/643
> [backport 3.0] config: set config status after "post_apply" phase

- .github/workflows/integration.yml
In commit d14dce36b153 ("ci: fix step parameters for reusable runs") the integration workflow was made reusable, but concurrency group pattern modification that was done for other workflows made reusable in the same patch was forgotten. This patch fixes the mentioned issue.
NO_DOC=CI
NO_TEST=CI
> [backport/release/3.0] ci: fix integration concurrency group

- .github/workflows/integration.yml
In commit 13ac5dafabbc ("ci: fix step parameters for reusable runs") the integration workflow was made reusable, but concurrency group pattern modification that was done for other workflows made reusable in the same patch was forgotten. This patch fixes the mentioned issue.
NO_DOC=CI
NO_TEST=CI
> [backport/release/2.11] ci: fix integration concurrency group

- test/config-luatest/anonymous_replica_test.lua
- test/config-luatest/cbuilder.lua
- test/config-luatest/cluster.lua
- test/config-luatest/compat_test.lua
- test/config-luatest/console_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/failover_and_election_mode_test.lua
- test/config-luatest/gh_9572_config_with_uuids_test.lua
- test/config-luatest/supervised_bootstrap_test.lua
The patchset improves for our testing helpers: a configuration builder and a replicaset runner. The configuration builder gained support of a configuration with multiple replicasets. The `replicaset` helper is renamed to `cluster` and now supports multiple replicasets too.
The patches are initially created by @locker and adopted by @Totktonada.
> test: support cluster (multiple replicasets) in config testing helpers

- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/reusable_build.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
This patch fixes three issues:
1. It changes the condition for workflows so they can be run not only from the Tarantool repository but from any repository in the Tarantool organization.
2. Reusable workflows substitute the `${{ github.workflow }}` context variable with the name of their top-level workflow. This behavior causes concurrency group clashes when several reusable workflows are called from a single top-level workflow. This patch adds an additional constant part to the concurrency group pattern to solve the issue.
3. The checkout actions use the reference from the repository in which the top-level workflow is located instead of the one where the reusable workflow is located. This patch solves the issue by passing the reference explicitly.
NO_DOC=CI
NO_TEST=CI
> [backport/release/2.10] ci: fix step parameters for reusable runs

- .github/workflows/integration.yml
In commit 3daf2399dd5b ("ci: fix step parameters for reusable runs") the integration workflow was made reusable, but concurrency group pattern modification that was done for other workflows made reusable in the same patch was forgotten. This patch fixes the mentioned issue.
NO_DOC=CI
NO_TEST=CI
> [backport/release/2.10] ci: fix integration concurrency group

- changelogs/unreleased/gh-9309-errors-in-triggers.md
- src/box/error.cc
- src/box/schema.cc
- test/box-luatest/gh_9309_errors_in_triggers_test.lua
Now on_access_denied and on_schema_init triggers do not throw error, so it just sinks into oblivion, which is not good because a thrown error indicates that something went wrong and database administrator should be definitely notified about it.
The commit makes Tarantool log errors thrown from these triggers with error level. Also, the commit adds a test checking if all triggers are either raise an error or log it.
Closes #9309
> trigger: log error in triggers that does not throw an error

- test/config-luatest/anonymous_replica_test.lua
- test/config-luatest/cbuilder.lua
- test/config-luatest/cluster.lua
- test/config-luatest/compat_test.lua
- test/config-luatest/console_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/failover_and_election_mode_test.lua
- test/config-luatest/gh_9572_config_with_uuids_test.lua
- test/config-luatest/supervised_bootstrap_test.lua
*(This is a backport of PR #9798 to `release/3.0`, future `3.0.2` release.)*
----
The patchset improves for our testing helpers: a configuration builder and a replicaset runner. The configuration builder gained support of a configuration with multiple replicasets. The `replicaset` helper is renamed to `cluster` and now supports multiple replicasets too.
The patches are initially created by @locker and adopted by @Totktonada.
> [backport 3.0] test: support cluster (multiple replicasets) in config testing helpers

- changelogs/unreleased/gh-9309-errors-in-triggers.md
- src/box/error.cc
- src/box/schema.cc
- test/box-luatest/gh_9309_errors_in_triggers_test.lua
Now on_access_denied and on_schema_init triggers do not throw error, so it just sinks into oblivion, which is not good because a thrown error indicates that something went wrong and database administrator should be definitely notified about it.
The commit makes Tarantool log errors thrown from these triggers with error level. Also, the commit adds a test checking if all triggers are either raise an error or log it.
Closes #9309
Title: Mention that triggers are guaranteed to throw an error or log it
Now all triggers are either have a direct impact on the execution flow (e.g. close a connection or throw an error) or print a message to error log when they throw an error.
We have a separate entry for triggers in Tarantool documentation, which lists the properties of the …
> [backport 3.0] trigger: log error in triggers that does not throw an error

- changelogs/unreleased/gh-9505-relay-stack-use-after-return.md
- src/box/box.cc
Fixed a bug when it was possible to use the
box_collect_confirmed_vclock stack after return.
Closes #9505
NO_DOC=bugfix
NO_TEST=asan
> relay: fix stack use after return

- changelogs/unreleased/box-speed-up-tuple_new.md
- perf/tuple.cc
- src/box/tuple_format.c
- test/box/alter.result
- test/box/alter.test.lua
- test/box/ddl_collation.result
- test/box/ddl_collation.test.lua
The first 2 patches add the `bench_tuple_new<FORMAT_SPARSE>` benchmark, that creates sparse tuples (1K fields each, 990 of which are nils).
The next 2 patches speed up the benchmark from 7 μs to 2 μs per iteration.
Needed for tarantool/tarantool-ee#711
> box: speed up `tuple_new()` for large sparse tuples by 3.5x

- changelogs/unreleased/gh-9809-config-add-labels.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
- test/config-luatest/labels_test.lua
Closes #9809
Title: New labels in config schema
The new labels are basically maps with string keys and values, that are merged down to instance level. It means that if a replicaset and an instance inside it have label with same key and different value, the actual value is the one instance provided, e.g.
```yaml
groups:
group-001:
replicasets:
replicaset-001:
labels:
foo: 'true'
bar: 'true'
instances:
instance-001:
labels:
baz: 'true'
foo: 'false'
```
Results in:
```
./instance-001.iproto> require('config'):get('labels')
---
- baz: 'true'
foo: 'false'
bar: 'true'
...
```
> config: introduce labels to schema

- changelogs/unreleased/gh-9505-relay-stack-use-after-return.md
- src/box/box.cc
Fixed a bug when it was possible that the `on_relay_thread_start` trigger handler would continue to use `data` allocated on the stack of `box_collect_confirmed_vclock` after returning from it.
Closes #9505
NO_DOC=bugfix
NO_TEST=asan
(cherry picked from commit 40bd0eb1af0f9429bea0086feb7ceaf8c636f57e)
> [backport 2.11] relay: fix stack use after return

- changelogs/unreleased/gh-9489-netbox-wait-connected.md
- src/box/lua/net_box.c
- test/box-luatest/gh_9489_netbox_wait_connected_test.lua
This patch fixes a regression introduced in c13b3a31, which caused the worker fiber to start synchronously, while it should be started asynchronously.
Closes #9489
> net.box: do not start worker fiber synchronously

- changelogs/unreleased/config-retrieve-cluster-config.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/configdata.lua
- src/box/lua/config/init.lua
- test/config-luatest/cluster_config_test.lua
- test/config-luatest/vars_test.lua
List all instances of the cluster.
Returns a table of the following format.
```lua
{
[<instance_name>] = {
instance_name = <...>,
replicaset_name = <...>,
group_name = <...>,
},
<...>
}
```
If an action should be performed for each instance of the given cluster, it can be written this way:
```lua
for instance_name in pairs(config:instances()) do
action(instance_name)
end
```
If replicaset/group names matter, the instances may be filtered this way:
```lua
-- Perform an action for all instances of the given replicaset.
for instance_name, def in pairs(config:instances()) do
if def.replicaset_name == box.info.replicaset.name then
action(instance_name)
end
end
```
The new `instance` option of the `config:get()` method allows to retrieve a configuration value of another instance from the given …
> config: access configuration of other cluster members
