- changelogs/unreleased/gh-9489-netbox-wait-connected.md
- src/box/lua/net_box.c
- test/box-luatest/gh_9489_netbox_wait_connected_test.lua
Due to a regression introduced in c13b3a31, the worker fiber is started synchronously, while it should be started asynchronously, in order for the `wait_connected = false` option of `connect` to work correctly. We already explicitly wait from Lua for the connection to become active via `wait_state` when `wait_connected = true`.
Closes #9489
(cherry picked from commit 0502a1f5249e4f1d14ef6e24628071fc712b7f14)
> [backport 2.11] net.box: do not start worker fiber synchronously

- changelogs/unreleased/gh-9489-netbox-wait-connected.md
- src/box/lua/net_box.c
- test/box-luatest/gh_9489_netbox_wait_connected_test.lua
Due to a regression introduced in c13b3a31, the worker fiber is started synchronously, while it should be started asynchronously, in order for the `wait_connected = false` option of `connect` to work correctly. We already explicitly wait from Lua for the connection to become active via `wait_state` when `wait_connected = true`.
Closes #9489
(cherry picked from commit 0502a1f5249e4f1d14ef6e24628071fc712b7f14)
> [backport 3.0] net.box: do not start worker fiber synchronously

- changelogs/unreleased/gh-9643-credentials-from-app-roles.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/credentials_applier_test.lua
*(This is a backport of PR #9812 to `release/3.0`, future `3.0.2` release.)*
----
Prior to this patch, privileges in the "credentials" section of the configuration could be requested for non-existent spaces, functions, and sequences. However, this was not possible for roles, although essentially the same mechanism is used. The problem is resolved with this patch.
Part of #9643
Title: Assign a non-existent credential role
A non-existent credential role can be assigned to a user or role in `credential` section of the config. The actual assignment will occur when the assigned credential role is created.
> [backport 3.0] config: allow to set non-existent credential role

- .test.mk
After the commit 3daf2399dd5b ('ci: fix step parameters for reusable runs') it is now possible to create Tarantool integration workflows for any repository in the Tarantool organization. Considering this, we don't need to run Tarantool tests under the old target for the LuaJIT integration in .test.mk and we can leave only LuaJIT tests in this target for the sake of exotic Tarantool builds testing.
NO_DOC=CI
NO_TEST=CI
> ci: remove Tarantool tests from LuaJIT integration

- .test.mk
After the commit d14dce36b153 ("ci: fix step parameters for reusable runs") it is now possible to create Tarantool integration workflows for any repository in the Tarantool organization. Considering this, we don't need to run Tarantool tests under the old target for the LuaJIT integration in .test.mk and we can leave only LuaJIT tests in this target for the sake of exotic Tarantool builds testing.
NO_DOC=CI
NO_TEST=CI
> [backport/release/3.0] ci: remove Tarantool tests from LuaJIT integration

- .test.mk
After the commit 3daf2399dd5b ("ci: fix step parameters for reusable runs") it is now possible to create Tarantool integration workflows for any repository in the Tarantool organization. Considering this, we don't need to run Tarantool tests under the old target for the LuaJIT integration in .test.mk and we can leave only LuaJIT tests in this target for the sake of exotic Tarantool builds testing.
NO_DOC=CI
NO_TEST=CI
> [backport/release/2.10] ci: remove Tarantool tests from LuaJIT integration

- .test.mk
After the commit 13ac5dafabbc ("ci: fix step parameters for reusable runs") it is now possible to create Tarantool integration workflows for any repository in the Tarantool organization. Considering this, we don't need to run Tarantool tests under the old target for the LuaJIT integration in .test.mk and we can leave only LuaJIT tests in this target for the sake of exotic Tarantool builds testing.
NO_DOC=CI
NO_TEST=CI
> [backport/release/2.11] ci: remove Tarantool tests from LuaJIT integration

- src/box/lua/schema.lua
- test/box-luatest/gh_9643_priv_origins_test.lua
*(This is a backport of PR #9804 to `release/3.0`, future `3.0.2`.)*
----
This patch adds a new option '_origin' to the 'box.schema.user.grant()', 'box.schema.role.grant()', 'box.schema.user.revoke()' and 'box.schema.role.revoke()' functions. This is a private option that allows to differentiate privileges based on their origin. If this option is not provided an empty string is used by default.
Privileges that were granted using 'grant()' can be revoked using 'revoke()' with the same '_origin'.
The motivation for this change is to avoid actually revoking a privilege granted by two actors if one actor revokes it.
Needed for #9643
> [backport 3.0] box: support _origin in grant() and revoke()

- changelogs/unreleased/gh-9792-error-level.md
- src/box/lua/error.cc
- test/app-luatest/gh_9792_error_level_test.lua
- test/box/error.result
Now, when used with a table argument, `box.error` and `box.error.new` also accept an optional second argument called `level`. It has the same meaning as the `level` argument of the built-in Lua function `error`: it specifies how to get the error location. With level 1 (the default), the error location is where `box.error` / `box.error.new` was called. Level 2 points the error to where the function that called `box.error` / `box.error.new` was called; and so on. Passing level 0 avoids addition of location information to the error.
Example of using `level` with `box.error`:
```lua
local json = require('json')
local function inner(level)
box.error({message = 'test'}, level)    -- line:4
end
local function outer(level)
inner(level)                            -- line:8
end
local ok, err
ok, …
```
> error: allow to specify where to get error location

- changelogs/unreleased/gh-9845-nil-error-on-empty-config.md
- src/box/lua/config/source/file.lua
- test/config-luatest/sources_test.lua
Before this patch, Tarantool, when started with empty configuration file, used to fail with a non verbose error:
```
$ ./src/tarantool -n instance-001 -c single.yaml
LuajitError: [cluster_config] Unexpected data type for a record: "nil"
fatal error, exiting the event loop
```
Now Tarantool instance can be set up with configuration from remote
configuration sources available in Tarantool Enterprise Edition and
run with empty config file. When there is no configuration provided
for the instance an according error is thrown.
Closes #9845
NO_DOC=bugfix
> config: allow empty configuration file

- changelogs/unreleased/gh-9845-nil-error-on-empty-config.md
- src/box/lua/config/source/file.lua
- test/config-luatest/sources_test.lua
*(This is a backport of PR #9846 to `release/3.0`, future `3.0.2` release.)*
----
Before this patch, Tarantool, when started with empty configuration file, used to fail with a non verbose error:
```
$ ./src/tarantool -n instance-001 -c single.yaml
LuajitError: [cluster_config] Unexpected data type for a record: "nil"
fatal error, exiting the event loop
```
Now Tarantool instance can be set up with configuration from remote configuration sources available in Tarantool Enterprise Edition and run with empty config file. When there is no configuration provided for the instance an according error is thrown.
Closes #9845
> [backport 3.0] config: allow empty configuration file

- changelogs/unreleased/gh-9643-credentials-from-app-roles.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/config_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/config-luatest/upgrade_test.lua
*(This is a backport of PR #9852 to `release/3.0`, future `3.0.2` release.)*
----
Now the privileges that were not granted by the configuration, as well as privileges that were not granted solely by the configuration, are not revoked on reload. Privileges only granted by the config module will still be revoked if they are removed from the `credentials` section on reload.
Closes #9643
> [backport 3.0] config: rework privilege revocation

- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
- test/replication-luatest/cluster_name_test.lua
- test/replication-luatest/instance_name_test.lua
- test/replication-luatest/replicaset_name_test.lua
This commit increases a time to wait of the process termination. It may take longer than 5 seconds, when tarantool is built with an address sanitizer. The address sanitizer generates a report at the process termination and it is not always a fast thing.
> test: increase process termination waiting timeout

- test/sql-tap/in2.test.lua
*(This is a backport of PR #9837 to `release/3.0`.)*
----
This patch reduces the number of tests in the in2.test.lua test file. This patch also reduces the number of inserted values. This shouldn't affect the test since it's not really an original Tarantool test, but it will reduce the execution time of this test. Currently this test often fails due to a timeout.
> [backport 3.0] sql: decrease number of tests in in2.test.lua

- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
- test/replication-luatest/cluster_name_test.lua
- test/replication-luatest/instance_name_test.lua
- test/replication-luatest/replicaset_name_test.lua
*(This is a backport of PR #9859 to `release/3.0`, future `3.0.2` release.)*
---
This commit increases a time to wait of the process termination. It may take longer than 5 seconds, when tarantool is built with an address sanitizer. The address sanitizer generates a report at the process termination and it is not always a fast thing.
> [backport 3.0] test: increase process termination waiting timeout

- test/box-luatest/gh_7974_force_recovery_bugs_test.lua
*(This is a backport of PR #9859 to `release/2.11`, future `2.11.3` release.)*
----
This commit increases a time to wait of the process termination. It may take longer than 5 seconds, when tarantool is built with an address sanitizer. The address sanitizer generates a report at the process termination and it is not always a fast thing.
> [backport 2.11] test: increase process termination waiting timeout

- test/config-luatest/cluster.lua
Unlike `cluster:start()` without the options argument, the `cluster:start({})` call has been interpreted as `cluster:start({wait_until_ready = false})`. Now it is equivalent to `cluster:start({wait_until_ready = true})`.
`cluster:start()` has not been waiting for leaving the `'orphan'` status. Now it does this for all the instances of the cluster. The new `wait_until_running` option was added to opt out from this behavior.
The first change doesn't affect existing tests. The second one improves stability of `config-luatest/anonymous_replica_test.lua`.
> test: fix peculiar behavior of cluster:start()

- test/config-luatest/cluster.lua
*(This is a backport of PR #9877 to `release/3.0`, future `3.0.2` release.)*
----
Unlike `cluster:start()` without the options argument, the `cluster:start({})` call has been interpreted as `cluster:start({wait_until_ready = false})`. Now it is equivalent to `cluster:start({wait_until_ready = true})`.
`cluster:start()` has not been waiting for leaving the `'orphan'` status. Now it does this for all the instances of the cluster. The new `wait_until_running` option was added to opt out from this behavior.
The first change doesn't affect existing tests. The second one improves stability of `config-luatest/anonymous_replica_test.lua`.
> [backport 3.0] test: fix peculiar behavior of cluster:start()

- changelogs/unreleased/gh-9863-new-key-def-functions.md
- src/box/lua/key_def.c
- src/box/lua/key_def.h
- src/box/lua/key_def.lua
- src/box/lua/space.cc
- test/app-luatest/key_def_test.lua
- test/box-luatest/gh_7356_index_parts_methods_test.lua
The following new functions were introduced to the `key_def` Lua module:
- `key_def:validate_key(key)`: validates a key against a key definition object. Raises an exception if the key doesn't match. Returns nothing on success. See also `box_key_def_validate_key` C API function.
- `key_def:validate_full_key(key)`: validates a full key against a key definition object. Raises an exception if the key doesn't match. Returns nothing on success. See also `box_key_def_validate_full_key` C API function.
- `key_def:validate_tuple(tuple)`: validates a tuple against a key definition object. Raises an exception if the tuple doesn't match. Returns nothing on success. See also `box_key_def_validate_tuple` C API function.
- `key_def:compare_keys(key_a, key_b)`: compares two keys according to a key …
> lua/key_def: add key validation and comparison functions

- changelogs/unreleased/gh-9629-netbox-async-request-connection-gc.md
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua
This patch fixes a bug that caused a connection with asynchronous requests to get garbage collected prematurely.
Closes #9629
> net.box: reference the connection object from asynchronous requests

- src/box/lua/console.c
- test/app-luatest/gh_6305_autocomplete_metamethod_test.lua
Fixes a regression introduced in cf644abd, which added exception-unsafe code for retrieval of `__autocomplete` metamethod of cdata objects.
I wasn't able to test the orginal reported bug, since the luatest server starts with `box` configured.
Closes #9828
> console: make __autocomplete retrival for cdata exception-safe

- changelogs/unreleased/gh-9629-netbox-async-request-connection-gc.md
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua
In order to prevent the garbage collection of the discarded connection, asynchronous requests must reference the connection object. We must reference the connection object rather than the transport object, because our garbage collection hook is attached to the former.
Closes #9629
(cherry picked from commit fb5bf51ce53eab49c57e5da02c53098fa05afec0)
> [backport 2.11] net.box: reference the connection object from asynchronous requests

- changelogs/unreleased/gh-9629-netbox-async-request-connection-gc.md
- src/box/lua/net_box.c
- src/box/lua/net_box.lua
- test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua
In order to prevent the garbage collection of the discarded connection, asynchronous requests must reference the connection object. We must reference the connection object rather than the transport object, because our garbage collection hook is attached to the former.
Closes #9629
(cherry picked from commit fb5bf51ce53eab49c57e5da02c53098fa05afec0)
> [backport 3.0] net.box: reference the connection object from asynchronous requests

- changelogs/unreleased/gh-9732-func-index-exclude-null.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_9732_func_index_exclude_null_test.lua
Currently, exclude_null option doesn't affect functional indexes at all. It seems that we just forgot to check if tuple should be inserted to the index - the patch simply adds missing check in replace and build_next methods of functional memtx_tree index.
Closes #9732
NO_DOC=bugfix
(cherry picked from commit c56998fad6a7f2cda4252b5cfde1ccef5050fe19)
> [backport 2.11] box: support exclude_null option in functional indexes

- changelogs/unreleased/gh-9732-func-index-exclude-null.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_9732_func_index_exclude_null_test.lua
Currently, exclude_null option doesn't affect functional indexes at all. It seems that we just forgot to check if tuple should be inserted to the index - the patch simply adds missing check in replace and build_next methods of functional memtx_tree index.
Closes #9732
NO_DOC=bugfix
(cherry picked from commit c56998fad6a7f2cda4252b5cfde1ccef5050fe19)
> [backport 3.0] box: support exclude_null option in functional indexes

- .github/workflows/distrib.yml
- .github/workflows/docker_build_push.yml
- .github/workflows/packaging_build_test_deploy.yml
- docker/Dockerfile
- docker/README.md
- docker/config/default-config.yaml
- docker/entrypoint/docker-entrypoint.sh
- docker/example/app/config.yaml
- docker/example/docker-compose.yaml
- docker/tools/console
- docker/tools/status
Bring a base toolset for building official Docker images for
Tarantool 3.0+ version.
Toolset components:
1. Dockerfile for building Docker images (based on Ubuntu 22.04)
2. Docker entrypoint script (docker-entrypoint.sh)
3. Default Tarantool config (default-config.yaml)
4. Auxiliary tools for checking Tarantool instance status and connecting
to admin console
5. Example of a basic Tarantool cluster that can be started via Docker
Compose (a tool for running multi-container applications)
---
Add the Docker image build routine as a part of the release
pipeline.
A word about image tags.
For example, if a release tag is 3.1.0, the resulting Docker image will
be pushed to Docker Hub with the following tags: 3.1.0, 3.1, 3.
If a release tag is 3.1.0-alpha1, the resulting Docker image will be …
> docker/cd: build and push Docker image on release tag

- test/unit/rtree_multidim.cc
Header "unit.h" contains `ok` and `is` macros used to check test cases. The problem is such simple names can be used in C++ STL library headers (it's OK because such short names can be hidden in a namespace), so when including, for example, header "vector" after "unit.h", build can fail because function declaration or definition in the C++ header will turn into a macro invocation. I faced this problem building Tarantool on MacOS with SDK of 14.4 version.
> build: include header "unit.h" after c++ headers

- docker/config/default-config.yaml
This patch changes iproto listen URI setting in default-config.yaml from `localhost:3301` to `0.0.0.0:3301`. Without this change, it's impossible to start container and use a popular way for port publishing:
$ docker run -p 3301:3301 --rm -d tarantool/tarantool
$ tt connect 127.0.0.1:3301
Connecting to the instance...
failed to run interactive console: failed to create new console:
failed to connect: failed to get protocol:failed to read
Tarantool greeting: EOF
> docker: change localhost:3301 to 0.0.0.0:3301

- .github/CODEOWNERS
It has been decided to drop required devx team review for tests.
> codeowners: drop devx team review for tests

- test/unit/rtree_multidim.cc
Header "unit.h" contains `ok` and `is` macros used to check test cases. The problem is such simple names can be used in C++ STL library headers (it's OK because such short names can be hidden in a namespace), so when including, for example, header "vector" after "unit.h", build can fail because function declaration or definition in the C++ header will turn into a macro invocation. I faced this problem building Tarantool on MacOS with SDK of 14.4 version.
NO_TEST=fix build
NO_CHANGELOG=fix build
NO_DOC=fix build
(cherry picked from commit 025ba32f842619b5d2ceb0569b4581396e75550d)
> [backport 2.11] build: include header "unit.h" after c++ headers

- test/unit/rtree_multidim.cc
Header "unit.h" contains `ok` and `is` macros used to check test cases. The problem is such simple names can be used in C++ STL library headers (it's OK because such short names can be hidden in a namespace), so when including, for example, header "vector" after "unit.h", build can fail because function declaration or definition in the C++ header will turn into a macro invocation. I faced this problem building Tarantool on MacOS with SDK of 14.4 version.
NO_TEST=fix build
NO_CHANGELOG=fix build
NO_DOC=fix build
(cherry picked from commit 025ba32f842619b5d2ceb0569b4581396e75550d)
> [backport 3.0] build: include header "unit.h" after c++ headers

- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
These options configure how often a state information is updated by the failover coordinator in a remote state storage and how fast a transient state is expired.
The new options are named as follows.
* `failover.stateboard.renew_interval`
* `failover.stateboard.keepalive_interval`
Part of https://github.com/tarantool/tarantool-ee/issues/564
> config: add failover stateboard options

- changelogs/unreleased/gh-9677-netbox-on_disconnect-error-behaviour.md
- changelogs/unreleased/gh-9679-on_schema_reload-error-behaviour.md
- changelogs/unreleased/gh-9797-netbox-on_disconnect-error-hangs-server.md
- changelogs/unreleased/gh-9827-netbox-on_connect-close.md
- src/box/lua/net_box.lua
- test/box-luatest/gh_9309_errors_in_triggers_test.lua
- test/box-luatest/gh_9677_netbox_on_disconnect_error_behaviour_test.lua
- test/box-luatest/gh_9679_netbox_on_schema_reload_error_behaviour_test.lua
- test/box-luatest/gh_9797_netbox_on_disconnect_error_hangs_server_test.lua
- test/box-luatest/gh_9827_netbox_on_connect_close_test.lua
This patch set fixes several bugs related to `net.box` connection object triggers. It also changes the behaviour of the `on_schema_reload` trigger to make it more logically consistent. Finally, it fixes UB in the connection's `transport:stop` method.
Closes #9677
Closes #9679
Closes #9797
Closes #9827
> `net.box` connection object triggers bugfixes

- changelogs/unreleased/gh-9864-allow-up-to-2-32-tuples-in-hash-index.md
- src/lib/core/random.c
- src/lib/core/random.h
- src/lib/salad/light.h
- test/unit/CMakeLists.txt
- test/unit/light.cc
- test/unit/light.result
This PR increases max capacity of the `light` hash table from 2<sup>31</sup> to 2<sup>32</sup>-8 records.
Closes #9864
<s>Do not merge until https://github.com/tarantool/small/pull/85 is merged!</s>
> Increase max number of tuples in hash index to `2^32 - 8`

- changelogs/unreleased/gh-9806-http-set-version.md
- src/httpc.c
- src/httpc.h
- src/lua/httpc.c
- src/lua/httpc.lua
- test/app-luatest/http_client_http_version_test.lua
The `http_version` option allows to set version of http in functions like
`request()`, `post()`, `get()` and etc using this curl option:
https://curl.se/libcurl/c/CURLOPT_HTTP_VERSION.html
The http_version takes one of the strings listed below or a nil value
and sets the appropriate protocol version.
List of supported values:
1) nil - works as '2-tls' by default.
2) '1.1' - sets HTTP/1.1 version.
3) '2' - sets HTTP/2 version that falls back to HTTP/1.1 if cannot be
negotiated with the server.
4) '2-tls' - works as '2' for HTTPS and as '1.1' for plain text HTTP.
5) '2-prior-knowledge' sets HTTP/2 version without HTTP/1.1 at back.
It requires prior knowledge that the server supports HTTP/2.
Closes #9806
> httpc: HTTP version option for HTTP client

- test/box-luatest/gh_9823_net_replicaset_test.lua
The test checks that net.replicaset connection switches to the new leader when the new leader is elected. Unfortunately the test expects that after successful call of box.ctl.promote() the old leader is guaranteed to be in RO state. Actually this is incorrect: the new leader can legally rely on the quorum with the third instance without even notifying the original leader about new election term started, so the old leader may remain in RW state. Since the replicaset connection updates states of instances asynchronously it also may think (for some time) that the old leader is the only RW instance in replicaset.
Fix it by including check of the new leader into retrying block of the test.
Hotfix #9823
NO_CHANGELOG=fix flaky test
NO_DOC=fix flaky test
> net.replicaset: fix a flaky test

- changelogs/unreleased/gh-9186-7331-forbid-db-access-and-txn-control-in-txn-triggers.md
- src/box/errcode.h
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/gh_9186_7331_forbid_database_access_in_txn_triggers_test.lua
- test/box/error.result
When we are going to start a new statement in transaction, we check if current transaction can continue with a special helper. This helper fails only when the transaction is aborted, but if transaction is committed, it actually cannot be continued as well because it is over. So let's consider committed transactions as non-continuable.
Along the way, let's fix an error thrown when someone tries to access database within on_rollback trigger - now it is reported as "Unknown error", let's use "Transaction was rolled back" instead.
Also, user is not allowed to execute TCL statements in on_commit and on_rollback triggers - it is documented UB. However, this prohibition can be easily overseen: one could, for example, try to rollback current transaction if something is not OK in on_commit …
> box: forbid DDL, DML, DQL, DCL and TCL in transactional triggers

- .github/workflows/coverage.yml
If coverage workflow is triggered via submodule as a part of integration
testing, coverage reports from Tarantool are sent to coveralls as
reports from the submodule. Our fork of LuaJIT as well as Tarantool uses
Coveralls, this will avoid reporting Tarantool's coverage to LuaJIT's
namespace in Coveralls.
To avoid this misbehaviour, run the "upload report" step only when there
is no submodule to bump (specified as `inputs.submodule` [1]) as a part
of the reusable workflow.
[1]: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
NO_DOC=CI
NO_TEST=CI
---
The example: https://coveralls.io/github/tarantool/luajit
> ci: don't send coverage results for submodules

- changelogs/unreleased/gh-9895-forbid-empty-group-or-replicaset.md
- src/box/lua/config/configdata.lua
- test/config-luatest/cbuilder.lua
- test/config-luatest/cluster.lua
- test/config-luatest/cluster_config_test.lua
It is very easy to misplace a config option to a different lever, for
example create an empty replicaset `sharding` with storage role, instead
of configuring sharding option to `storage`:
```yaml
groups:
g-001:
replicasets:
sharding:
roles:
- storage
r-001:
instances:
i-001: {}
```
This patch adds verification that forbids creating a replicaset without
a single instance in it.
Closes https://github.com/tarantool/tarantool/issues/9895
NO_DOC=bugfix
> config: verify replicaset to contain an instance

- changelogs/unreleased/bump-metrics-to-3370f85.md
Bump metrics package submodule. There are 8 new commits, but only two of them affects Tarantool:
- Add election_leader_idle metric [1];
- test: run log capture tests on a separate server [2];
the other 6 affect documentation and CI/CD scripts of the original repo. The latter one is required to bump luatest in test-run [3], since otherwise metrics log capture test fails on a new version.
1. https://github.com/tarantool/metrics/commit/ba9726d9b0cdfb22aa56d852f7fdc7b0aa22756a
2. https://github.com/tarantool/metrics/commit/3370f856efd4172bf24916e66e3846eeb01550a8
3. https://github.com/tarantool/test-run/pull/426
> lua: bump metrics module

- changelogs/unreleased/gh-9895-forbid-empty-group-or-replicaset.md
- src/box/lua/config/configdata.lua
- test/config-luatest/cbuilder.lua
- test/config-luatest/cluster.lua
- test/config-luatest/cluster_config_test.lua
*(This is a backport of PR #9896 to `release/3.0`, future `3.0.2` release.)*
----
It is very easy to misplace a config option to a different level, for example create an empty replicaset `sharding` with storage role, instead of configuring sharding option to `storage`:
```yaml
groups:
g-001:
replicasets:
sharding:
roles:
- storage
r-001:
instances:
i-001: {}
```
This patch adds verification that forbids creating a replicaset without a single instance in it.
Closes #9895
> [backport 3.0] config: verify replicaset to contain an instance

- changelogs/unreleased/gh-9296-fix-memory-leak-when-dropping-fully-temporary-spaces.md
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/fully-temporary_spaces_test.lua
Before this fix we used to leak memory when dropping fully-temporary
spaces. The problem was that the memory is only freed in the on_commit
callback of the transaction, but dropping a temporary space is a NOP
(meta-data is not persisted), and the on_commit triggers used to not be
invoked for NOP transactions.
Closes https://github.com/tarantool/tarantool/issues/9296
NO_DOC=bug fix
> box: fix memory leak when dropping temporary spaces

- changelogs/unreleased/gh-9296-fix-memory-leak-when-dropping-fully-temporary-spaces.md
- src/box/txn.c
- src/box/txn.h
- test/box-luatest/fully-temporary_spaces_test.lua
Before this fix we used to leak memory when dropping fully-temporary spaces. The problem was that the memory is only freed in the on_commit callback of the transaction, but dropping a temporary space is a NOP (meta-data is not persisted), and the on_commit triggers used to not be invoked for NOP transactions.
Closes #9296
NO_DOC=bug fix
(cherry picked from commit a90819bd83dedd2bf0299f30cadcbc05b2f89c43)
> [backport 3.0] box: fix memory leak when dropping temporary spaces

- changelogs/unreleased/bump-metrics-to-3370f85.md
(This is a backport of PR https://github.com/tarantool/tarantool/pull/9901 to release/2.11, future 2.11.3 release.)
----
Bump metrics package submodule. There are 8 new commits, but only two of them affects Tarantool:
- Add election_leader_idle metric [1];
- test: run log capture tests on a separate server [2]; the other 6 affect documentation and CI/CD scripts of the original repo. The latter one is required to bump luatest in test-run [3], since otherwise metrics log capture test fails on a new version.
1. https://github.com/tarantool/metrics/commit/ba9726d9b0cdfb22aa56d852f7fdc7b0aa22756a
2. https://github.com/tarantool/metrics/commit/3370f856efd4172bf24916e66e3846eeb01550a8
3. https://github.com/tarantool/test-run/pull/426
NO_DOC=doc is a part of submodule
NO_TEST=repo runs submodule …
> [backport 2.11] lua: bump metrics module

- src/box/lua/trigger.c
- test/app-luatest/trigger_module_test.lua
It was mistake to return handler from trigger deletion - if the handler is not Lua object, its lifetime is independent from Lua, and we basically return object from its destructor. Let's just return nothing because checking if a trigger was actually deleted seems to be misusage of our trigger paradigm.
NO_CHANGELOG=not documented behavior
NO_DOC=bugfix
(cherry picked from commit c54adc1e1fb71dc4b5e6c1435e3a12a9537ce0e0)
> [backport 3.0] trigger: do not return handler from trigger.del

- changelogs/unreleased/gh-9644-verbose-uri-error.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/configdata.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
Before this patch, it was quite difficult to determine, which URI in config was unsuitable.
Now the subject URI is listed in the error body.
NO_DOC: bugfix
Closes #9644
> config: add subj URI to config verification error

- changelogs/unreleased/gh-9644-verbose-uri-error.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/configdata.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
*(This is a backport of PR #9906 to `release/3.0`, future `3.0.2` release.)*
----
Before this patch, it was quite difficult to determine, which URI in config was unsuitable.
Now the subject URI is listed in the error body.
Closes of #9644
> [backport 3.0] config: add subj URI to config verification error

- cmake/BuildICU.cmake
- cmake/BuildZZIP.cmake
The CI/CD builds are performed on VK Cloud virtual machines, so the access to VK S3 is more reliable than to GitHub archives.
In fact, we experience periodical download problems with source archives on GitHub in Tarantool Enterprise Edition builds in CI/CD and it is the motivation to backup the archives on our side. The problems appear quite frequently last few days.
The download problems are not on VK Cloud side and not on GitHub side. The packet loss is somewhere in the middle. I don't know an exact reason for now.
> build: use VK S3 for icu4c and zziplib archives

- cmake/BuildICU.cmake
- cmake/BuildZZIP.cmake
*(This is a backport of PR #9947 to `release/3.0`.)*
----
The CI/CD builds are performed on VK Cloud virtual machines, so the access to VK S3 is more reliable than to GitHub archives.
In fact, we experience periodical download problems with source archives on GitHub in Tarantool Enterprise Edition builds in CI/CD and it is the motivation to backup the archives on our side. The problems appear quite frequently last few days.
The download problems are not on VK Cloud side and not on GitHub side. The packet loss is somewhere in the middle. I don't know an exact reason for now.
> [backport 3.0] build: use VK S3 for icu4c and zziplib archives

- cmake/BuildICU.cmake
- cmake/BuildZZIP.cmake
*(This is a backport of PR #9947 to `release/2.11`.)*
----
The CI/CD builds are performed on VK Cloud virtual machines, so the access to VK S3 is more reliable than to GitHub archives.
In fact, we experience periodical download problems with source archives on GitHub in Tarantool Enterprise Edition builds in CI/CD and it is the motivation to backup the archives on our side. The problems appear quite frequently last few days.
The download problems are not on VK Cloud side and not on GitHub side. The packet loss is somewhere in the middle. I don't know an exact reason for now.
> [backport 2.11] build: use VK S3 for icu4c and zziplib archives

- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/coverity.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/docker_build_push.yml
- .github/workflows/etcd_integration.yml
- .github/workflows/freebsd.yml
- .github/workflows/fuzzing.yml
- .github/workflows/lango-stale-reviews.yml
- .github/workflows/lint.yml
- .github/workflows/luajit-integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/osx.yml
- .github/workflows/out_of_source.yml
- .github/workflows/packaging_build_test_deploy.yml
- .github/workflows/perf_micro.yml
- .github/workflows/publish-module-api-doc.yaml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/reusable_build.yml
- .github/workflows/source.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
- .github/workflows/submodule_update.yml
Add `timeout-minutes` to workflow jobs to control max duration time. By default, each job in a workflow can run for up to 6 hours of the execution time. If a job reaches this limit, the job is terminated by GitHub automatically and fails to complete. This patch sets job timeouts to 60 minutes to avoid waiting for jobs to complete for 6 hours.
> ci: add timeout for workflows

- changelogs/unreleased/gh-9954-mvcc-crash-with-exclude-null.md
- src/box/memtx_tx.c
- test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Before this patch MVCC engine expected that if index_replace sets `result` to NULL then index_replace sets `successor` to something (NULL or existing tuple, depending on index type). That looked fine because by contract `successor` is set when true insertion was happened.
Unfortunately it was not considered that case of `exclude_null` part in index the insertion can be silently skipped and thus `successor` can be not set. The latter access of it led to UB.
Fix it by explicit check of tuple_key_is_excluded and work on this case correctly.
Note that logically `index_replace` should return a flag whether the new tuple was filtered (excluded) by key_def. But on the other hand this flag is required only for mvcc while the function is already has lots of agruments and it's very cheap to …
> memtx: fix a bug with mvcc and exclude_null option

- changelogs/unreleased/gh-9954-mvcc-crash-with-exclude-null.md
- src/box/memtx_tx.c
- test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Before this patch MVCC engine expected that if index_replace sets `result` to NULL then index_replace sets `successor` to something (NULL or existing tuple, depending on index type). That looked fine because by contract `successor` is set when true insertion was happened.
Unfortunately it was not considered that in case of part with `exclude_null` option in index the insertion can be silently skipped and thus `successor` can be not set. The latter access of it was actually an UB.
Fix it by explicit check of tuple_key_is_excluded and work on this case correctly.
Note that logically `index_replace` should return a flag whether the new tuple was filtered (excluded) by key_def. But on the other hand this flag is required only for mvcc while the function is already has lots of arguments and …
> [Backport 2.11] memtx: fix a bug with mvcc and exclude_null option

- changelogs/unreleased/gh-9954-mvcc-crash-with-exclude-null.md
- src/box/memtx_tx.c
- test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Before this patch MVCC engine expected that if index_replace sets `result` to NULL then index_replace sets `successor` to something (NULL or existing tuple, depending on index type). That looked fine because by contract `successor` is set when true insertion was happened.
Unfortunately it was not considered that in case of part with `exclude_null` option in index the insertion can be silently skipped and thus `successor` can be not set. The latter access of it was actually an UB.
Fix it by explicit check of tuple_key_is_excluded and work on this case correctly.
Note that logically `index_replace` should return a flag whether the new tuple was filtered (excluded) by key_def. But on the other hand this flag is required only for mvcc while the function is already has lots of arguments and …
> [Backport 2.10] memtx: fix a bug with mvcc and exclude_null option

- changelogs/unreleased/gh-7223-add-more-error-details.md
- src/box/errcode.h
- src/box/error.cc
- src/box/field_map.c
- src/box/field_map.h
- src/box/index.cc
- src/box/index.h
- src/box/memtx_hash.cc
- src/box/memtx_space.c
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/session_settings.c
- src/box/space.c
- src/box/space.h
- src/box/sysview.c
- src/box/tuple_format.c
- src/box/vinyl.c
- src/box/vy_stmt.c
- src/box/xrow_update.c
- test/box-luatest/error_subsystem_improvements_test.lua
- test/unit/error.c
Closes #7223
EE part is https://github.com/tarantool/tarantool-ee/pull/776
For example for this setup:
```lua
local test = box.schema.create_space('test')
test:create_index('primary')
test:create_index('second', {parts = {2, 'unsigned', 1, 'unsigned'}})
```
Before we get (note that compat option `box_error_serialize_verbose` is set
to 'new' to show error details in console. It does not affect whether
details are added or not):
```
tarantool> test.index.second:get{1}
---
- error:
code: 19
base_type: ClientError
type: ClientError
message: Invalid key part count in an exact match (expected 2, got 1)
trace:
- file: ./src/box/index.cc
line: 149
...
```
And now we get (see 'space', 'space_id', 'index', 'index_id' and 'key' fields):
```
tarantool> test.index.second:get{1}
---
- error:
code: 19 …
```
> box: add details to DML specific errors

- changelogs/unreleased/gh-9621-netbox-worker-crash.md
- changelogs/unreleased/gh-9826-netbox-on_schema_reload-close.md
- src/box/lua/net_box.c
- test/app-luatest/gh_9621_netbox_worker_crash_test.lua
- test/box-luatest/gh_9826_netbox_on_schema_reload_close_test.lua
- test/box-luatest/net_box_test.lua
This patch fixes a bugs in `net.box` related to the connection being closed unexpectedly to the connection's worker fiber.
Closes #9621
Closes #9826
> netbox: close transport after stopping worker loop and wait for the stop

- changelogs/unreleased/popen-wait-after-close.md
- changelogs/unreleased/popen-wait-busy-loop.md
- changelogs/unreleased/popen-wait-timeout.md
- src/lib/core/popen.c
- src/lib/core/popen.h
- src/lua/popen.c
- test/app-luatest/popen_wait_test.lua
- test/app-tap/popen.test.lua
This patchset solves several problems:
* Eliminates polling with fiber sleeps for a process status in `:wait()`.
Now the method waits for libev's SIGCHLD watcher (via a fiber cond).
* Fixes use-after-free and crash/infinite hang in `:wait()` when the 
handle is closed from another fiber.
* Adds `timeout` parameter to `:wait()`.
Usage example:
```lua
local ph = popen.new(<...>)
local res, err = ph:wait({timeout = 1}) 
if res == nil then
-- Timeout is reached.
assert(err.type == 'TimedOut')
<...>
end
```
Also `:wait()` now has defined behavior when the popen handle is closed
from another fiber: the method returns the `ChannelIsClosed` error.
Fixes #4915
Fixes #7653
Fixes #4916
> popen: add timeout for :wait()

- src/lib/salad/bps_tree.h
Fix the clang warning in the BPS tree with logarithmic offset support.
Closes #9987
NO_DOC=no functional changes
NO_TEST=no functional changes
NO_CHANGELOG=no functional changes
> bps: fix the OS X build

- changelogs/unreleased/gh-9825-space-format-default-func-tuple-arg.md
- src/box/field_default_func.c
- src/box/field_default_func.h
- src/box/sql/func.c
- src/box/tuple_format.c
- src/box/tuple_format.h
- test/engine-luatest/gh_9825_space_format_default_func_tuple_arg_test.lua
This patch adds a source tuple as a second argument to the `default_func` field option to `space:format`.
Closes #9825
> box: pass source tuple to `default_func` field option of `space:format`

- test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- test/app-luatest/gh_8136_fix_print_wrapper_not_handling_errors_thrown_from_print_test.lua
- test/box-luatest/gh_8051_set_box_cfg_thru_env_test.lua
- test/box-luatest/gh_8817_bug_set_language_shared_test.lua
- test/box-luatest/hide_show_prompt_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/interactive_tarantool.lua
This patchset proposes a couple of enhancements for the `test.interactive_tarantool` testing helper.
* `:roundtrip()` now able to verify a response against `nil` and returns the response.
* The hide/show prompt feature (#7169) is now disabled by default.
* The new `connect()` function makes it easier to work with a remote console.
See the commit messages for details.
Part of #9985
> test/interactive: a couple of enhancements

- test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- test/app-luatest/gh_8136_fix_print_wrapper_not_handling_errors_thrown_from_print_test.lua
- test/box-luatest/gh_8051_set_box_cfg_thru_env_test.lua
- test/box-luatest/gh_8817_bug_set_language_shared_test.lua
- test/box-luatest/hide_show_prompt_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/interactive_tarantool.lua
*(This is a backport of PR #9999 to the `release/3.1` branch.)*
----
This patchset proposes a couple of enhancements for the `test.interactive_tarantool` testing helper.
* `:roundtrip()` now able to verify a response against `nil` and returns the response.
* The hide/show prompt feature (#7169) is now disabled by default.
* The new `connect()` function makes it easier to work with a remote console.
See the commit messages for details.
Part of #9985
> [backport 3.1] test/interactive: a couple of enhancements

- test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- test/app-luatest/gh_8136_fix_print_wrapper_not_handling_errors_thrown_from_print_test.lua
- test/box-luatest/gh_8051_set_box_cfg_thru_env_test.lua
- test/box-luatest/gh_8817_bug_set_language_shared_test.lua
- test/box-luatest/hide_show_prompt_test.lua
- test/config-luatest/credentials_applier_test.lua
- test/interactive_tarantool.lua
*(This is a backport of PR #9999 to the `release/3.0` branch.)*
----
This patchset proposes a couple of enhancements for the `test.interactive_tarantool` testing helper.
* `:roundtrip()` now able to verify a response against `nil` and returns the response.
* The hide/show prompt feature (#7169) is now disabled by default.
* The new `connect()` function makes it easier to work with a remote console.
See the commit messages for details.
Part of #9985
> [backport 3.0] test/interactive: a couple of enhancements

- test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- test/app-luatest/gh_8136_fix_print_wrapper_not_handling_errors_thrown_from_print_test.lua
- test/box-luatest/gh_8051_set_box_cfg_thru_env_test.lua
- test/box-luatest/gh_8817_bug_set_language_shared_test.lua
- test/box-luatest/hide_show_prompt_test.lua
- test/interactive_tarantool.lua
*(This is a backport of PR #9999 to the `release/2.11` branch.)*
----
This patchset proposes a couple of enhancements for the `test.interactive_tarantool` testing helper.
* `:roundtrip()` now able to verify a response against `nil` and returns the response.
* The hide/show prompt feature (#7169) is now disabled by default.
* The new `connect()` function makes it easier to work with a remote console.
See the commit messages for details.
Part of #9985
> [backport 2.11] test/interactive: a couple of enhancements

- changelogs/unreleased/console-session-scope-vars.md
- src/box/lua/config/instance_config.lua
- src/box/lua/console.lua
- test/app-luatest/console_session_scope_vars_test.lua
- test/config-luatest/cluster_config_schema_test.lua
It is counter-intuitive that all the non-local assignments in the console affect globals and may interfere with application's logic.
It is also counter-intuitive that the non-local assignments are shared between different console sessions.
Now, each console session has its own variables scope and the non-local assignments use it instead of globals.
Let's consider examples of the new behavior.
Example 1. A console session has a variable scope that is separate from globals.
```lua
console_1> _G.x = 1
console_1> x = 2
console_1> _G.x
---
- 1
...
console_1> x
---
- 2
...
```
Note: A global variable is still accessible using `_G` even if the same named session scope variable exists.
Example 2. A global variable is read if there is no session local variable.
```lua
console_1> _G.x = 1 …
```
> console: create per-session variables scope

- changelogs/unreleased/gh-9995-vy-scheduler-crash-fix.md
- src/box/vy_scheduler.c
Between picking an LSM tree from a heap and taking a reference to it in `vy_task_new()` there are a few places where the scheduler may yield:
- in `vy_worker_pool_get()` to start a worker pool;
- in `vy_task_dump_new()` to wait for a memory tree to be unpinned;
- in `vy_task_compaction_new()` to commit an entry to the metadata log after splitting or coalescing a range.
If a concurrent fiber drops and deletes the LSM tree in the meanwhile, the scheduler will crash. To avoid that, let's take a reference to the LSM tree.
It's quite difficult to write a functional test for it without a bunch of ugly error injections so we rely on fuzzing tests.
Closes #9995
> vinyl: fix use-after-free of LSM tree in scheduler

- perf/lua/column_scan.lua
It was intended to do 1000 inserts per transaction, but by mistake `box.commit()` was called after each insertion.
> perf: speed up column scan test initialization

- changelogs/unreleased/console-autorequire.md
- src/box/lua/console.lua
- test/app-luatest/console_autorequire_test.lua
There are built-in modules that are frequently used for administration or debugging purposes. It is convenient to have them accessible in the interactive console without extra actions.
They're accessible now without a manual `require` call if the `console_session_scope_vars` compat option is set to `new` (see also tarantool/doc#4191).
The list of the autorequired modules is below.
* clock
* compat
* config
* datetime
* decimal
* ffi
* fiber
* fio
* fun
* json
* log
* msgpack
* popen
* uuid
* varbinary
* yaml
See tarantool/tarantool#9986 for motivation behind this feature.
This list forms so called initial environment for an interactive console session. The default initial environment may be adjusted by an application, for example, to include application specific administrator functions. …
> console: autorequire frequently used modules

- changelogs/unreleased/gh-9769-vy-unique-nullable-index-fix.md
- src/box/vy_lsm.c
- test/engine-luatest/gh_9769_tuple_lost_in_unique_nullable_index_test.lua
A unique nullable key definition extended with primary key parts (`cmp_def`) assumes that two tuples are equal *without* comparing primary key fields if all secondary key fields are equal and not nulls, see `tuple_compare_slowpath()`. This is a hack required to ignore the uniqueness constraint for nulls in memtx. The memtx engine can't use the secondary key definition as is (`key_def`) for comparing tuples in the index tree, as it does for a non-nullable unique index, because this wouldn't allow insertion of any duplicates, including nulls. It couldn't use `cmp_def` without this hack, either, because then conflicting tuples with the same secondary key fields would always compare as not equal due to different primary key parts.
For Vinyl, this hack isn't required because it explicitly …
> vinyl: fix bug when tuple not committed to unique nullable index

- changelogs/unreleased/gh-9748-downstream-lag-bug.md
- src/box/applier.cc
- src/box/applier.h
- src/box/relay.cc
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/gh_9748_downstream_lag_test.lua
`box.info.replication[replica_id].downstream.lag` shows how much time it took the latest transaction, acked by the given replica, to be replicated to the replica, be written to its WAL, and be acked by this instance.
It sounds simple, but sometimes the actual behaviour was misleading or hard to use.
The patchset improves the user experience. The main change is that the lag is actually updated on each acked txn. Before that it was only updated for acked txns created by this specific master.
See #9748.
> Improve downstream lag behavior

- changelogs/unreleased/gh-9748-downstream-lag-bug.md
- src/box/applier.cc
- src/box/applier.h
- src/box/relay.cc
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/gh_9748_downstream_lag_test.lua
`box.info.replication[replica_id].downstream.lag` shows how much time it took the latest transaction, acked by the given replica, to be replicated to the replica, be written to its WAL, and be acked by this instance.
It sounds simple, but sometimes the actual behaviour was misleading or hard to use.
The patchset improves the user experience. The main change is that the lag is actually updated on each acked txn. Before that it was only updated for acked txns created by this specific master.
See #9748.
> [backport 2.11] Improve downstream lag behavior

- changelogs/unreleased/gh-9748-downstream-lag-bug.md
- src/box/applier.cc
- src/box/applier.h
- src/box/relay.cc
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/gh_9748_downstream_lag_test.lua
`box.info.replication[replica_id].downstream.lag` shows how much time it took the latest transaction, acked by the given replica, to be replicated to the replica, be written to its WAL, and be acked by this instance.
It sounds simple, but sometimes the actual behaviour was misleading or hard to use.
The patchset improves the user experience. The main change is that the lag is actually updated on each acked txn. Before that it was only updated for acked txns created by this specific master.
See #9748.
> [backport 3.1] Improve downstream lag behavior

- changelogs/unreleased/gh-10026-vy-index-build-crash-on-invalid-upsert-fix.md
- src/box/vinyl.c
- test/engine-luatest/gh_10026_index_build_crash_on_invalid_upsert_test.lua
- test/vinyl/on_replace.result
Like `UPDATE`, `UPSERT` must not modify primary key parts. Unlike `UPDATE`, such an invalid `UPSERT` statement doesn't fail (raise an error) - we just log the error and ignore the statement. The problem is, we don't clear `txn_stmt`. As a result, if we're currently building a new index, the `on_replace` trigger installed by the build procedure will try to process this statement, triggering the assertion in the transaction manager that doesn't expect any statements in a secondary index without the corresponding statement in the primary index:
```
./src/box/vy_tx.c:728: vy_tx_prepare: Assertion `lsm->space_id == current_space_id' failed.
```
Let's fix this by clearing the `txn_stmt` corresponding to a skipped `UPSERT`.
Note, this also means that `on_replace` triggers installed by the user …
> vinyl: fix index build crash on invalid UPSERT

- changelogs/unreleased/gh-5975-vy-duplicate-key-error-fix.md
- src/box/space.c
- src/box/space.h
- src/box/vinyl.c
- test/engine-luatest/gh_5975_duplicate_key_error_test.lua
The code setting `ER_TUPLE_FOUND` uses `index_name_by_id()` to find the index name, but it passes an index in the dense index map to it while the function expects an index in the sparse index map. Apparently, this doesn't work as expected after an index is removed from the middle of the index map. This bug was introduced by commit fc3834c01e9e6.
Instead of just fixing the index passed to `index_name_by_id()`, we do a bit of refactoring. We stop passing `index_name` and `space_name` to `vy_check_is_unique_*()` functions and instead get them right before raising `ER_TUPLE_FOUND`. Note, to get the space name, we need to call `space_by_id()` but it should be fine because (a) the space is very likely to be cached as the last accessed one and (b) this is an error path so it isn't performance …
> vinyl: fix index name in duplicate key error message

- changelogs/unreleased/gh-10013-wal-queue-max-size.md
- src/box/box.cc
- src/box/lua/load_cfg.lua
- test/replication-luatest/gh_10013_wal_queue_max_size_test.lua
wal_queue_max_size took effect only after the initial box.cfg call, meaning that users with non-zero `replication_sync_timeout` still synced using the default 16 Mb queue size. In some cases the default was too big and the same issues described in #5536 arose.
Fix this.
Closes #10013
NO_DOC=bugfix
> wal: fix wal_queue_max_size assignment during initial box.cfg

- changelogs/unreleased/gh-9994-next-prefix-iterator.md
- src/box/iterator_type.c
- src/box/iterator_type.h
- src/box/memtx_tree.cc
- test/box-luatest/gh_9994_next_prefix_iterator_test.lua
Implement 'np' (next prefix) and 'pp' (previous prefix) iterators. They work only in memtx tree and in a nutshell searches for strings with greater ('np') or less ('pp') prefix of size as in given key, comparing with given key.
Closes #9994
Title:'np' and 'pp' (next/previous prefix) iterators
Now there are two more iterators avaialbe: 'np' (next prefix) and 'pp' (previous prefix). They work only in memtx tree. Also, if the last part of key is not a string, they degrade to 'gt' and 'lt' iterators.
These iterators introduce special comparison of the last part of key (if it is a string). In terms of lua, if s is the search part, and t is the corresponding tuple part, 'np' iterator searches for the first tuple with string.sub(t, 1, #s) > s, while 'pp' searches for the …
> box: introduce next and previous prefix iterators

- src/box/alter.cc
The patch fixes crashes on upgrading nullability of trailing fields. If we had nullable one, and we upgrade it to non-nullable, attribute `has_optional_part` of some indexes can be changed (even if no indexed fields are changed). So in order to correctly index both old and new tuples we should set new min_field_count value to the minimal min_field_count of old and new formats. Actual value will be set when space upgrade completes.
This is CE part of the patch. It must be merged after EE part is approved and all tests there are passed.
EE part: tarantool/tarantool-ee#748
Part of tarantool/tarantool-ee#698
Part of tarantool/tarantool-ee#750
> space_upgrade: fix crashes on upgrading nullability

- src/lib/core/coio_task.c
```
/home/shiny/dev/tarantool/src/lib/core/coio_task.c:114:58:
error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument
and not in the later argument [-Werror=calloc-transposed-args]
114 |         struct cord *cord = (struct cord *)calloc(sizeof(struct cord), 1);
```
> core: build fix for recent gcc

- .github/workflows/distrib.yml
We are experiencing some issues with aarch64 runners at this moment, so we have to disable aarch64 packaging job until the issue is resolved. Other aarch64 jobs can be disabled via GitHub UI, so let's do it there.
> ci: temporary disable aarch64 packaging job

- changelogs/unreleased/gh-9997-support-splice-for-varbinary.md
- src/box/xrow_update_field.c
- src/box/xrow_update_field.h
- test/box-luatest/error_subsystem_improvements_test.lua
- test/box-luatest/gh_10032_update_upsert_splice_test.lua
- test/box-luatest/gh_9997_update_splice_test.lua
- test/box-luatest/update_upsert_splice_helper.lua
Just in case splice is an update operation that can modify string
field, deleting a part of it and inserting something instead.
```
tarantool> box.tuple.new{'1234567'}:update{{':', 1, 2, 3, '!'}}
---
- ['1!567']
...
```
In the this example splice operation ':' takes field 1 of tuple,
takes position 2 in string, removes 3 symbols and inserts '!' to
that position.
Both deletion and insertion can naturally degrade to no-op.
Before this patch a splice operation required both field and
inserting argument to be strings.
This patch allows the field and the argument to be varbinary.
```
tarantool> varb = require('varbinary')
tarantool> t = box.tuple.new{varb.new('1234567')}
tarantool> t:update{{':', 1, 2, 3, varb.new('!')}}
---
- [!!binary MSE1Njc=]
...
```
That also allows to insert strings into …
> box: support varbinary in splice update operation

- changelogs/unreleased/box-info-config.md
- src/box/lua/info.c
- test/box-luatest/box_info_config_test.lua
- test/box/info.result
There is the `config:info([version])` method, but in order to access it over iproto an application developer should add something like the following into the application code:
```lua
_G.config = require('config')
```
It is not convenient, at least because it requires an attention from the application developer and it can't be solved solely by an administrator.
Now, the `config:info('v2')` result is reported in the `config` field of the `box.info` table. It is accessible over iproto if appropriate privileges are granted for a calling user.
Fixes #10044
> config: expose configuration status from box.info

- changelogs/unreleased/config-not-a-table-role-error-message.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
An attempt to use a non-table module as a role now reports a more descriptive error:
> Unable to use module <...> as a role: expected table, got <...>
Fixes #10049
> config: give better error if a role is not a table

- changelogs/unreleased/config-not-a-table-role-error-message.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
This is a backport of PR #10052 to `release/3.1`, future `3.1.1` release.
----
An attempt to use a non-table module as a role now reports a more descriptive error:
> Unable to use module <...> as a role: expected table, got <...>
Fixes #10049
> [backport 3.1] config: give better error if a role is not a table

- src/box/CMakeLists.txt
It's used to introduce new data structures in the Tarantool EE.
NO_DOC=no functional changes
NO_TEST=no functional changes
NO_CHANGELOG=no functional changes
> Add the extra include directory for salad library

- changelogs/unreleased/gh-9893-rollback-ddl-on-_space-space.md
- src/box/alter.cc
- src/box/txn.c
- src/box/user.cc
- src/box/user.h
- test/box-luatest/gh_9893_rollback_ddl_on__space_space_test.lua
- test/box-luatest/rollback_ddl_on__priv_space_test.lua
This patch fixes the order of running a transaction statement's `on_rollback` triggers and rolling back the statement itself.
Closes #9893
> txn: run statement `on_rollback` triggers before rolling back statement

- changelogs/unreleased/gh-9855-box-ctl-demote-guarantee-demoting.md
- src/box/box.cc
- src/box/raft.c
- src/box/raft.h
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/replication-luatest/gh_6860_election_off_demote_test.lua
- test/replication-luatest/gh_9855_box_ctl_demote_guarantee_demoting_test.lua
This patch prevents the demoted leader from being a candidate in the next elections.
Closes #9855
> box: prevent demoted leader from being a candidate in the next elections

- test/box-luatest/box_cfg_env_test.lua
- test/box-luatest/box_schema_before_box_cfg_test.lua
- test/box-luatest/gh_6819_iproto_watch_not_implemented_test.lua
- test/config-luatest/config_test.lua
- test/config-luatest/helpers.lua
- test/replication-luatest/gh_8433_raft_is_candidate_test.lua
Backport of 97a801e190e94ae804acc5075ba1f7bfaf7553cc
> [backport 3.1] test: bump test-run to new version

- test/box-luatest/box_cfg_env_test.lua
- test/replication-luatest/gh_8433_raft_is_candidate_test.lua
Backport of 4466deafee4eb424a098653bf1d6b905eeb8163f and 97a801e190e94ae804acc5075ba1f7bfaf7553cc
> [backport 2.11] test: bump test-run to new version 

- test/box-luatest/box_cfg_env_test.lua
- test/replication-luatest/gh_8433_raft_is_candidate_test.lua
Backport of https://github.com/tarantool/tarantool/commit/4466deafee4eb424a098653bf1d6b905eeb8163f and https://github.com/tarantool/tarantool/commit/97a801e190e94ae804acc5075ba1f7bfaf7553cc
> [backport 2.10] test: bump test-run to new version

- src/box/lua/config/utils/odict.lua
- test/config-luatest/odict_test.lua
The problem is found by @ochaton.
> odict: fix ffi.new('void *') as a key

- src/box/lua/config/utils/odict.lua
- test/config-luatest/odict_test.lua
*(This is a backport of PR #10080 to `release/3.1`, future `3.1.1` release.)*
----
The problem is found by @ochaton.
> [backport 3.1] odict: fix ffi.new('void *') as a key

- changelogs/unreleased/gh-10090-tuple-hash-double-fix.md
- src/box/tuple_hash.cc
- test/box-luatest/gh_10090_tuple_hash_double_test.lua
- test/vinyl-luatest/gh_10090_tuple_hash_double_test.lua
`tuple_hash_field()` doesn't advance the MsgPack cursor after hashing a tuple field with the type `double`, which can result in crashes both in memtx (while inserting a tuple into a hash index) and in vinyl (while writing a bloom filter on dump or compaction).
The bug was introduced by commit 51af059c10ff.
Closes #10090
> tuple: fix crash on hashing tuple with double fields

- changelogs/unreleased/gh-10094-vy-index-drop-crash-fix.md
- src/box/vinyl.c
- src/box/vy_lsm.c
- test/vinyl-luatest/gh_10094_index_drop_test.lua
A DML request (insert, replace, update) can yield while reading from the disk in order to check unique constraints. In the meantime the index can be dropped. The DML request can't crash in this case thanks to commit d3e1236956515, but the DDL operation can because:
- It unreferences the index in `alter_space_commit`, which may result in dropping the LSM tree with `vy_lsm_delete`.
- `vy_lsm_delete` may yield in `vy_range_tree_free_cb` while waiting for disk readers to complete.
- Yielding in commit triggers isn't allowed (crashes).
We already fixed a similar issue when `index.get` crashed if raced with index drop, see commit 75f03a50df4a. Let's fix this issue in the same way - by taking a reference to the LSM tree while checking unique constraints. To do that it's enough to move …
> vinyl: fix crash in index drop if there is DML request reading from it

- changelogs/unreleased/gh-10111-provide-key_def-length.md
- src/box/lua/key_def.c
- src/box/lua/key_def.lua
- test/box-tap/key_def.test.lua
The metamethod is a way to key_def length introspection.
Closes #10111
Title: key_def length introspection
To check key_def length (parts count) there is a standard lua operator `#` (`__len` metamethod).
Example:
```lua
function is_full_pkey(space, key)
return #space.key_def == #key
end
```
> key_def: Introduce `__len` metamethod

- changelogs/unreleased/gh-10095-vy-index-update-def-fix.md
- src/box/vinyl.c
- test/vinyl-luatest/gh_10095_update_index_def_test.lua
If a secondary index is altered in such a way that its key parts are extended with the primary key parts, rebuild isn't required because `cmp_def` doesn't change, see `vinyl_index_def_change_requires_rebuild`. In this case `vinyl_index_update_def` will try to update `key_def` and `cmp_def` in-place with `key_def_copy`. This will lead to a crash because the number of parts in the new `key_def` is greater.
We can't use `key_def_dup` instead of `key_def_copy` there because there may be read iterators using the old `key_def` by pointer so there's no other option but to force rebuild in this case.
The bug was introduced in commit 64817066ff60.
Closes #10095
> vinyl: fix crash on extending secondary key parts with  primary

- .github/actions/environment/action.yml
- .github/workflows/distrib.yml
This reverts commit ef3152cdc249045be8250c65d47b1a002e49467e.
We have solved the issues with aarch64 runners, so we can enable back aarch64 jobs.
> Revert "ci: temporary disable aarch64 packaging job"

- changelogs/unreleased/gh-10099-vy-crash-on-invalid-upsert-fix.md
- src/box/vy_upsert.c
- test/vinyl-luatest/gh_10099_invalid_upsert_test.lua
`vy_apply_result_does_cross_pk()` must be called after the new tuple format is validated, otherwise it may crash in case the new tuple has fields conflicting with the primary key definition.
While we are at it, fix the operation cursor (`ups_ops`) not advanced on this kind of error. This resulted in skipped `upsert` statements following an invalid `upsert` statement in a transaction.
Closes #10099
> vinyl: fix crash on invalid upsert

- src/box/lua/call.c
- src/box/lua/index.c
- src/box/lua/init.c
- test/app-tap/msgpack.test.lua
We already do some steps to use `box.error` in these C modules. Let's finish it to make a clear distinction between C modules that are switched to `box.error` and that are not (see #10121).
Follow-up #9996
> error: finish changes to several C modules to use box.error

- changelogs/unreleased/gh-9918-synchro-queue-additional-info.md
- src/box/lua/info.c
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- test/replication-luatest/gh_9918_synchro_queue_additional_info_test.lua
This patch series exposes additional `age` and `confirm_lag` field to `box.info.synchro.queue`.
Closes #9918
> Expose additional info regarding synchronous transaction queue state to `box.info.synchro.queue`

- changelogs/unreleased/gh-10087-update-quorum-in-on_commit-trigger.md
- src/box/alter.cc
- src/box/replication.cc
- test/replication-luatest/gh_10087_update_quorum_in_on_commit_trigger_test.lua
This patch moves the synchronous replication quorum update from the `on_replace` trigger to the  `on_commit` trigger.
Closes #10087
> box: update synchro quorum in on_commit trigger instead of on_replace

- changelogs/unreleased/gh-10109-vy-read-iterator-fix.md
- src/box/vy_cache.c
- src/box/vy_run.c
- test/vinyl-luatest/gh_10109_read_iterator_test.lua
The PR fixes a couple of bugs in the read iterator because of which tuples written to the database could be skipped by a range `select`.
Closes #10109
> vinyl: fix bugs in read iterator

- changelogs/unreleased/gh-10123-vy-tuple-field-lookup-fix.md
- src/box/tuple.h
`key_part::offset_slot_cache` and `key_part::format_epoch` are used for speeding up tuple field lookup in `tuple_field_raw_by_part()`. These structure members are accessed and updated without any locks, assuming this code is executed exclusively in the tx thread. However, this isn't necessarily true because we also perform tuple field lookups in vinyl read threads. Apparently, this can result in unexpected races and bugs, for example:
```
#1  0x590be9f7eb6d in crash_collect+256
#2  0x590be9f7f5a9 in crash_signal_cb+100
#3  0x72b111642520 in __sigaction+80
#4  0x590bea385e3c in load_u32+35
#5  0x590bea231eba in field_map_get_offset+46
#6  0x590bea23242a in tuple_field_raw_by_path+417
#7  0x590bea23282b in tuple_field_raw_by_part+203
#8  0x590bea23288c in tuple_field_by_part+91
#9 …
```
> tuple: don't use offset_slot_cache in vinyl threads

- changelogs/unreleased/gh-10128-vy-invalid-vylog-fix.md
- src/box/vinyl.c
- src/box/vy_log.c
- src/box/vy_log.h
Vinyl run files aren't always deleted immediately after compaction, because we need to keep run files corresponding to checkpoints for backups. Such run files are deleted by the garbage collection procedure, which performs the following steps:
1. Loads information about all run files from the last vylog file.
2. For each loaded run record that is marked as dropped: a. Tries to remove the run files. b. On success, writes a "forget" record for the dropped run, which will make vylog purge the run record on the next vylog rotation (checkpoint).
(see `vinyl_engine_collect_garbage()`)
The garbage collection procedure writes the "forget" records asynchronously using `vy_log_tx_try_commit()`, see `vy_gc_run()`. This procedure can be successfully executed during vylog rotation, because it doesn't …
> vinyl: fix gc vs vylog race leading to duplicate record

- .github/workflows/tree.yml
- tools/check-entrypoint-tag.sh
Check check-entrypoint.sh comment for explanation of what entrypoint tag is. The workflow fails if current branch does not have a most recent entrypoint tag that it should have.
Part of #8319
> ci: add a workflow to check for entrypoint tags

- asan/lsan.supp
Another occurrence similar to  #8890  (CI of release/2.11 of EE version):
```
[007] default | Direct leak of 872 byte(s) in 1 object(s) allocated from:
[007] default |     #0 0x561e52c10a1e in malloc (/__w/tarantool-ee/tarantool-ee/tarantool/src/tarantool+0x121ba1e) (BuildId: 7e480e11e82733cb4922ef2b33f5f463ed9a620f)
[007] default |     #1 0x561e54016026 in BuildFiberSliceIsExceeded /__w/tarantool-ee/tarantool-ee/tarantool/src/lib/core/exception.cc:335:2
[007] default |     #2 0x561e5352a363 in fiber_check_slice() /__w/tarantool-ee/tarantool-ee/tarantool/src/lib/core/fiber.h:1062:3
[007] default |     #3 0x561e5352999c in box_check_slice_slow /__w/tarantool-ee/tarantool-ee/tarantool/src/box/box.cc:350:9
[007] default |     #4 0x561e52cf293b in box_check_slice() …
```
> lsan: add another FP leak suppression

- test/fuzz/luaL_loadbuffer/serializer.cc
- clamp before cleaning string because cleaning is not cheap (O(n), where max n is equal to kMaxStrLength)
- call cleaning for identifiers only, there is no sense to cleaning string literals
- replace symbols disallowed by Lua grammar in indentifier's names with '_'
The patch saves 16 sec on 145k samples (401 sec before the patch and 385 sec after the patch). It is actually not so much, but it is about 2.5 min per hour.
NO_DOC=testing
> test/fuzz: speedup string serialization

- changelogs/unreleased/gh-10005-tuple-get-format.md
- src/box/lua/tuple.c
- src/box/lua/tuple.lua
- src/box/lua/tuple_format.c
- src/box/lua/tuple_format.h
- src/box/lua/tuple_format.lua
- test/app-luatest/gh_10005_tuple_get_format_test.lua
This patch adds `tuple:format()` method to get a format of a tuple.
Closes #10005
Title: New `format` method for `box.tuple`
Product: Tarantool
Since: 3.2
The `tuple:format` method returns a format of a tuple.
> box: feature `tuple:format` to get a format of a tuple

- changelogs/unreleased/config-support-vshard-ee.md
- src/box/lua/config/applier/credentials.lua
- src/box/lua/config/applier/sharding.lua
- src/lua/loaders.lua
- test/app-luatest/require_first_test.lua
- test/box-luatest/upgrade/2.11.0/vshard/storage-gen.lua
- test/config-luatest/vshard_test.lua
- test/config-luatest/vshard_upgrade_test.lua
The new closed-source `vshard-ee` module was recently introduced. It is based on the open-source `vshard` module and, as far as I know, provides the same API.
Let's configure `vshard-ee` in the same way as `vshard` if sharding is enabled in tarantool's configuration.
Prefer `vshard-ee` if both are available.
Fixes https://github.com/tarantool/tarantool-ee/issues/815
> config: use vshard-ee if available

- .github/workflows/downgrade_versions.yml
- src/box/lua/upgrade.lua
- tools/check-downgrade-versions.sh
Tarantool has hardcoded list of versions it can downgrade to. This list should consist of all the released versions less than Tarantool version. This workflow helps to make sure we update the list before release.
When run on the commit with release tag it check the list and fail if it misses some released version less than current. In this case we are supposed to update downgrade list (with required downgrade code) and update the release tag.
Closes #8319
> ci: add workflow to check downgrade versions

- .github/workflows/perf_micro.yml
This patch is the follow-up for the commit
49946a72b72884d4f84269b90e6a61 ("ci: send perf statistics to InfluxDB"). Since secrets are unavailable for fork repositories, the sending step fails due to a missed InfluxDB URL and token. This patch allows to run this step only for on push events or PRs from the main repository itself.
NO_DOC=CI
NO_TEST=CI
> ci: avoid sending perf stat to Influx from forks

- changelogs/unreleased/gh-8130-enable-somaxconn-on-mac.md
- src/lib/core/sio.c
listen() on Mac used to take SOMAXCONN as the backlog size. It is just 128, which is too small when connections are incoming too fast. They get rejected.
Increase of the queue size wasn't possible, because the limit was hardcoded. But now sio takes the runtime limit from kern.ipc.somaxconn sysctl setting.
One weird thing is that when set too high, it seems to have no effect, like if nothing was changed. Specifically, values above 32767 are not doing anything, even though stay visible in kern.ipc.somaxconn.
It seems listen() on Mac internally might be using 'short' or int16_t to store the queue size and it gets broken when anything above INT16_MAX is used. The code truncates the queue size to this value if the given one is too high.
Closes #8130
NO_DOC=bugfix
NO_TEST=requires root …
> sio: use `kern.ipc.somaxconn` for `listen()` on Mac

- changelogs/unreleased/gh-8130-enable-somaxconn-on-mac.md
- src/lib/core/sio.c
listen() on Mac used to take SOMAXCONN as the backlog size. It is just 128, which is too small when connections are incoming too fast. They get rejected.
Increase of the queue size wasn't possible, because the limit was hardcoded. But now sio takes the runtime limit from kern.ipc.somaxconn sysctl setting.
One weird thing is that when set too high, it seems to have no effect, like if nothing was changed. Specifically, values above 32767 are not doing anything, even though stay visible in kern.ipc.somaxconn.
It seems listen() on Mac internally might be using 'short' or int16_t to store the queue size and it gets broken when anything above INT16_MAX is used. The code truncates the queue size to this value if the given one is too high.
Closes #8130
NO_DOC=bugfix
NO_TEST=requires root …
> [backport 2.11] sio: use kern.ipc.somaxconn for listen() on Mac

- changelogs/unreleased/gh-8130-enable-somaxconn-on-mac.md
- src/lib/core/sio.c
listen() on Mac used to take SOMAXCONN as the backlog size. It is just 128, which is too small when connections are incoming too fast. They get rejected.
Increase of the queue size wasn't possible, because the limit was hardcoded. But now sio takes the runtime limit from kern.ipc.somaxconn sysctl setting.
One weird thing is that when set too high, it seems to have no effect, like if nothing was changed. Specifically, values above 32767 are not doing anything, even though stay visible in kern.ipc.somaxconn.
It seems listen() on Mac internally might be using 'short' or int16_t to store the queue size and it gets broken when anything above INT16_MAX is used. The code truncates the queue size to this value if the given one is too high.
Closes #8130
NO_DOC=bugfix
NO_TEST=requires root …
> [backport 3.1] sio: use kern.ipc.somaxconn for listen() on Mac

- changelogs/unreleased/ghe-827-etcd-ssl-cert.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
etcd configuration section allows to connect to TLS-encrypted etcd cluster, providing a way to pass `ssl.ssl_key`. But it is not enough when etcd server have client cert auth enabled and has a CA file, since it requires a ssl_cert as well. Actually, propagating ssl_cert is already a part of the EE connect code [1], we just missing the top-level config option.
Fixes https://github.com/tarantool/tarantool-ee/issues/827
1. https://github.com/tarantool/tarantool-ee/blame/1138443c46e7a6e1bb855277bc6cb3333240131c/src/box/lua/config/source/etcd.lua#L103
Title: config: add missing ssl.ssl_cert for etcd
etcd configuration section already allows to set `ssl.ssl_key`. Now it also allows to pass `ssl.ssl_cert`.
> config: add missing ssl.ssl_cert for etcd

- changelogs/unreleased/ghe-827-etcd-ssl-cert.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
*(This is a backport of PR #10152 to `release/3.1`, future `3.1.1` release.)*
----
etcd configuration section allows to connect to TLS-encrypted etcd cluster, providing a way to pass `ssl.ssl_key`. But it is not enough when etcd server have client cert auth enabled and has a CA file, since it requires a ssl_cert as well. Actually, propagating ssl_cert is already a part of the EE connect code [1], we just missing the top-level config option.
Fixes https://github.com/tarantool/tarantool-ee/issues/827
1. https://github.com/tarantool/tarantool-ee/blame/1138443c46e7a6e1bb855277bc6cb3333240131c/src/box/lua/config/source/etcd.lua#L103
Title: config: add missing ssl.ssl_cert for etcd
etcd configuration section already allows to set `ssl.ssl_key`. Now it also allows to pass …
> [backport 3.1] config: add missing ssl.ssl_cert for etcd

- changelogs/unreleased/gh-10163-fix-functional-index-drop-memleak.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_10163_fix_functional_index_drop_memleak_test.lua
We just don't free functional index keys on functional index drop now. Let's approach keys deletion as in the case of primary index drop ie let's drop these keys in background.
Closes #10163
> box: fix memleak on functional index drop

- changelogs/unreleased/config-expose-config-utils-schema.md
- src/box/lua/config/cluster_config.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/config/source/env.lua
- src/box/lua/init.c
- test/config-luatest/schema_test.lua
The module is renamed from `internal.config.utils.schema` to `experimental.config.utils.schema` without changes.
It is useful for validation of configuration data in roles and applications.
Also, it provides a couple of methods that aim to simplify usual tasks around processing of hierarchical configuration data. For example,
* get/set a nested value
* apply defaults from the schema
* filter data based on annotations from the schema
* transform a hierarchical data using a function
* merge two hierarchical values
* parse environment variable according to its type in the schema
See https://github.com/tarantool/doc/issues/4279 for an in-depth description.
Fixes #10117
> config: expose experimental.config.utils.schema

- changelogs/unreleased/gh-10187-fix-memleaks-on-dead-fiber-usage.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
- test/app-luatest/fiber_test.lua
When fiber is accessed from Lua we create a userdata object and keep the reference for future accesses. The reference is cleared when fiber is stopped. But if fiber is joinable is still can be found with `fiber.find`. In this case we create userdata object again. Unfortunately as fiber is already stopped we fail to clear the reference. The trigger memory that clear the reference is also leaked. As well as fiber storage if it is accessed after fiber is stopped.
Let's add `on_destroy` trigger to fiber and clear the references there.
Note that with current set of LSAN suppressions the trigger memory leak is not reported.
Closes #10187
> fiber: fix leak on dead joinable fiber search

- changelogs/unreleased/gh-10196-fix-fiber-self-join-hang.md
- src/lib/core/fiber.c
- src/lib/core/fiber.h
- src/lua/fiber.c
- test/app-luatest/fiber_test.lua
In this case join will just hang. Instead let's raise an error in case of Lua API and panic in case of C API.
Closes #10196
> fiber: phohibit fiber self join

- changelogs/unreleased/gh-9924-luajit-fixes.md
* ci: checkout integration workflows to release/3.1
* Correct fix for stack check when recording BC_VARG.
* test: remove inline suppressions of _TARANTOOL
* FFI: Fix ffi.alignof() for reference types.
* FFI: Fix sizeof expression in C parser for reference types.
* FFI: Allow ffi.metatype() for typedefs with attributes.
* FFI: Fix ffi.metatype() for non-raw types.
* Maintain chain invariant in DCE.
* build: introduce option LUAJIT_ENABLE_TABLE_BUMP
* ci: add tablebump flavor for exotic builds
* test: allow `jit.parse` to return aborted traces
* Handle all types of errors during trace stitching.
* Use generic trace error for OOM during trace stitching.
* Check for IR_HREF vs. IR_HREFK aliasing in non-nil store check.
* cmake: set cmake_minimum_required only once
* cmake: fix warning about …
> [backport/release/3.1] luajit: bump new version

- src/box/sql/sqlInt.h
- src/trivia/util.h
This patch bumped small to the new version that does not trigger
UBSan with `*_entry*` macros and should support new oss-fuzz builder.
Fixes: https://github.com/tarantool/tarantool/issues/10143
NO_DOC=small submodule bump
NO_TEST=small submodule bump
>  small: bump new version with UBSan fixes 

- changelogs/unreleased/gh-10233-vy-snapshot-hang-fix.md
- src/box/vy_scheduler.c
- test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua
There may be more than one fiber waiting on `vy_scheduler::dump_cond`:
```
box.snapshot
vinyl_engine_wait_checkpoint
vy_scheduler_wait_checkpoint
space.create_index
vinyl_space_build_index
vy_scheduler_dump
```
To avoid hang, we should use `fiber_cond_broadcast`.
Closes #10233
> vinyl: use broadcast instead of signal to notify about dump completion

- changelogs/unreleased/gh-10087-update-quorum-in-on_commit-trigger.md
- src/box/alter.cc
- src/box/replication.cc
- test/replication-luatest/gh_10087_update_quorum_in_on_commit_trigger_test.lua
This is a backport of #10091. ~~Note, that only the first commit was backported (https://github.com/tarantool/tarantool/commit/29d1c0fa6c76ff06d748d8916c5ffbbc9e4a55e9), because the second one (https://github.com/tarantool/tarantool/commit/9b63ced353eaf6c1224358c7d3655ca52f7d21fb) makes the situation worse without an additional backport of #10114~~ nevermind, backported commit https://github.com/tarantool/tarantool/commit/9b63ced353eaf6c1224358c7d3655ca52f7d21fb as well.
Currently, we update the synchronous replication quorum from the `on_replace` trigger of the `_cluster` space when registering a new replica. However, during the join process, the replica cannot ack its own insertion into the `_cluster` space. In the scope of #9723, we are going to enable synchronous replication for most …
> [backport 2.11] box: update synchro quorum in on_commit trigger instead of on_replace

- src/lib/core/sio.c
- src/lib/core/sio.h
- test/unit/sio.c
- test/unit/unit.h
- test/unit/uri.c
Now `sio_bind` function prints adress into error message directly instead of relying on `fd` used in `bind` that failed to execute.
`sio_bind` used `sio_socketname_to_buffer` for error message effectively attempting printing address bound to `fd` while there actually was an error in binding that address to that socket in the first place.
Fixes #5925
> sio: fix error message displaing bind adress

- src/lib/core/sio.c
- src/lib/core/sio.h
- test/unit/sio.c
- test/unit/unit.h
- test/unit/uri.c
Now `sio_bind` function prints address into error message directly instead of relying on `fd` used in `bind` that failed to execute.
`sio_bind` used `sio_socketname_to_buffer` for error message effectively attempting printing address bound to `fd` while there actually was an error in binding that address to that socket in the first place.
Fixes #5925
NO_DOC=bugfix
(cherry picked from commit a5214bfcfefc9c14ff8b0a076afbb05cc01db767)
> [backport 2.11] sio: fix error message displaying bind address

- src/lib/core/sio.c
- src/lib/core/sio.h
- test/unit/sio.c
- test/unit/unit.h
- test/unit/uri.c
Now `sio_bind` function prints address into error message directly instead of relying on `fd` used in `bind` that failed to execute.
`sio_bind` used `sio_socketname_to_buffer` for error message effectively attempting printing address bound to `fd` while there actually was an error in binding that address to that socket in the first place.
Fixes #5925
NO_DOC=bugfix
(cherry picked from commit a5214bfcfefc9c14ff8b0a076afbb05cc01db767)
> [backport 3.1] sio: fix error message displaying bind address

- src/box/applier.cc
- test/replication-luatest/gh_5295_split_brain_test.lua
After receiving async transaction from an old term applier_apply_tx exits without unlocking the latch. If the same applier tries to subscribe for replication, it fails with assertion, as the latch is already locked.
Let's use scope guard in order to avoid leaving the latch locked.
Closes #10073
NO_DOC=bugfix
NO_CHANGELOG=no crash on release version
> applier: fix assertion failure after split brain

- perf/lua/column_scan_module.c
Fix the following warnings (with `ENABLE_READ_VIEW` defined):
```
./perf/lua/column_scan_module.c:59:18: error: unused variable ‘index_id’ [-Werror=unused-variable]
59 |         uint32_t index_id = luaL_checkinteger(L, 2);
|                  ^~~~~~~~
./perf/lua/column_scan_module.c:149:18: error: unused variable ‘index_id’ [-Werror=unused-variable]
149 |         uint32_t index_id = luaL_checkinteger(L, 2);
|                  ^~~~~~~~
```
> perf: fix warnings in `column_scan_module.c`

- src/box/applier.cc
- test/replication-luatest/gh_5295_split_brain_test.lua
After receiving async transaction from an old term applier_apply_tx exits without unlocking the latch. If the same applier tries to subscribe for replication, it fails with assertion, as the latch is already locked.
Let's fix the function, which raises error so that it just sets diag and returns -1.
Closes #10073
NO_DOC=bugfix
NO_CHANGELOG=no crash on release version
(cherry picked from commit 5ce010c5e6d95713dd4344dcaded3920b6d6417d)
> [backport 2.11] applier: fix assertion failure after split brain

- src/box/applier.cc
- test/replication-luatest/gh_5295_split_brain_test.lua
After receiving async transaction from an old term applier_apply_tx exits without unlocking the latch. If the same applier tries to subscribe for replication, it fails with assertion, as the latch is already locked.
Let's fix the function, which raises error so that it just sets diag and returns -1.
Closes #10073
NO_DOC=bugfix
NO_CHANGELOG=no crash on release version
(cherry picked from commit 5ce010c5e6d95713dd4344dcaded3920b6d6417d)
> [backport 3.1] applier: fix assertion failure after split brain

- changelogs/unreleased/config-schema-get-index-any.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/config_get_test.lua
- test/config-luatest/schema_test.lua
`<schema object>:get()` now can access a field inside the `any` type if it is a `table` or `nil`/`box.NULL`. See details in the `<schema object>:get()` section in https://github.com/tarantool/doc/issues/4279.
`config:get()` now can access fields inside `app.cfg.<key>` and `roles_cfg.<key>`.
Fixes #10205
> config/schema: allow to index 'any' type in :get()

- changelogs/unreleased/gh-10278-vy-tuple-format-lookup-fix.md
- src/box/tuple_format.c
- src/box/tuple_format.h
- test/wal_off/alter.result
The tuple formats table may be accessed with `tuple_format_by_id()` from any thread, not just tx. For example, it's accessed by a vinyl writer thread when it deletes a tuple. If a thread happens to access the table while it's being reallocated by tx, see `tuple_format_register()`, the accessing thread may crash with a use-after-free or NULL pointer dereference bug, like the one below:
```
```
To avoid that, let's make the tuple formats table statically allocated. This shouldn't increase actual memory usage because system memory is allocated lazily, on page fault. The max number of tuple formats isn't that big (64K) to care about the increase in virtual memory usage.
Closes #10278
> tuple: allocate formats table statically

- test/box-luatest/gh_4349_transactional_ddl_test.lua
Added more tests for various scenarios of the transactional DLL usage:
1. A DDL transaction which creates a space, formats it to have an integer column, fills it with some data, changes the format to 'any', changes the data values to 'string', and changes the format to 'string'.
2. A DDL transaction that creates a space, user, grants privileges to the user to use the new space and accesses the space on behalf of the new user.
3. Creation of a space and its secondary indexes in one transaction.
4. Creation of a space with a sequence attached in one transaction.
5. A DDL transaction which sets the on_rollback trigger and creates a space, the space triggers, inserts a bunch of data and then commits or rolls back.
6. Transactional drop of a space with various indexes, field and tuple …
> test: add the extended transactional DDL tests

- changelogs/unreleased/config-schema-set-to-null-or-nil.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/cbuilder.lua
- test/config-luatest/schema_test.lua
This commit implements the `<schema object>:set()` algorithm in a more accurate way and it solves several drawbacks of the previous implementation.
* It was impossible to set a field that is nested to a record or a map that has the box.NULL value (#10190).
* It was impossible to set a field to the box.NULL value (#10193).
* It was impossible to delete a field, now `nil` RHS value means the deletion (#10194).
See `<schema object>:set()` section in https://github.com/tarantool/doc/issues/4279 for the documentation.
Fixes #10190
Fixes #10193
Fixes #10194
> config/schema: support field deletion using :set()

- changelogs/unreleased/gh-10277-vy-log-dump-after-gc-fix.md
- src/box/lua/error.cc
- src/box/vy_scheduler.c
- test/vinyl-luatest/gh_10277_dump_after_gc_test.lua
An index can be dropped while a memory dump is in progress. If the vinyl garbage collector happens to delete the index from the vylog by the time the memory dump completes, the dump will log an entry for a deleted index, resulting in an error next time we try to recover the vylog, like:
```
ER_INVALID_VYLOG_FILE: Invalid VYLOG file: Run 2 committed after deletion
```
or
```
ER_INVALID_VYLOG_FILE: Invalid VYLOG file: Deleted range 9 has run slices
```
We already fixed a similar issue with compaction in commit 29e2931c66c5. Let's fix this one in exactly the same way: discard the new run without logging it to the vylog on a memory dump completion if the index was dropped while the dump was in progress.
Closes #10277
> vinyl: do not log dump if index was dropped

- changelogs/unreleased/gh-10088-apply-deletion-of-replica-from_cluster-on-deleted-replica.md
- changelogs/unreleased/gh-10266-async-tx-from-deleted-replica-arrive-on-remaining-cluster.md
- src/box/alter.cc
- src/box/applier.cc
- src/box/applier.h
- src/box/box.cc
- src/box/relay.cc
- src/box/relay.h
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/gh_10088_apply_deletion_of_replica_from_cluster_on_deleted_replica_test.lua
- test/replication-luatest/gh_10266_async_tx_from_deleted_replica_arrive_on_remaining_cluster_test.lua
- test/replication/prune.result
- test/replication/prune.test.lua
This patch series applies deletion of replica from `_cluster` on the deleted replica.
Closes #10088
Closes #10266
> box: apply deletion of replica from `_cluster` on the deleted replica

- test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
- test/box-luatest/gh_7231_memtx_hash_idx_gt_iter_deprecation_test.lua
- test/replication-luatest/gh_10088_apply_deletion_of_replica_from_cluster_on_deleted_replica_test.lua
The test gh_10088 was committed in parallel with the luatest bump and thus slipped from the post-bump tests fixup in commit cfd4bf4685de ("test: adapt tests to the new luatest version"). Fix it now.
NO_TEST=test
NO_DOC=test
> test: fix several more tests after the luatest bump

- perf/lua/column_scan.lua
- perf/lua/column_scan_module.c
Currently the test is capable of measuring memcs engine using iterator and scanner APIs. Let's also add the arrow API support. Since the API can scan data including the validity mask it's useful for testing the accelerated memcs scan.
NO_DOC=perf test
NO_TEST=perf test
NO_CHANGELOG=perf test
> perf: add the arrow API to the column scan test

- changelogs/unreleased/gh-10173-is-sync-feature.md
- src/box/iproto_features.c
- src/box/iproto_features.h
- src/box/lua/net_box.c
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/box-py/iproto.result
- test/box/net.box_iproto_id.result
`IPROTO_IS_SYNC`, which was introduced by commit c3c0d439ce8f ("box: add is_sync option") in Tarantool 3.0.0-beta1, still doesn't have a feature bit. Let's add it finally.
Closes #10173
> iproto: introduce IS_SYNC feature

- changelogs/unreleased/gh-10161-relay-speedup.md
- src/box/iproto.cc
- src/box/lua/net_box.c
- src/box/relay.cc
- src/box/vy_run.c
- src/box/xlog.c
- src/box/xrow.c
- src/box/xrow.h
- src/box/xrow_io.cc
- src/box/xrow_io.h
- src/trivia/util.h
- test/fuzz/xrow_header_decode_fuzzer.c
- test/replication-luatest/gh_7515_sync_node_sees_leader_hang_test.lua
- test/replication/sync.result
- test/replication/sync.test.lua
- test/unit/xrow.cc
relay: batch sent rows
Relay sends rows one by one, issuing one `write()` system call per each
sent row. This hurts performance quite a lot: in the 1mops_write test
[1] on my machine master node is able to reach ~ 1.9 million RPS while
replication performance peaks at ~ 0.5 million RPS.
As shown by a PoC patch, batching the rows allows to remove the
replication bottleneck almost completely. Even sending 2 rows per one
write() call already doubles the performance, and sending 64 rows per
one write() call allows the replica to catch up with master's speed [2].
This patch makes relay buffer rows until the total buffer size reaches a
certain threshold, and then flush everything with a single writev()
call.
The flush threshold is configurable via a new tweak -
xrow_buf_flush_size, which has a …
> relay: batch sent rows

- src/box/memtx_engine.cc
- test/box-luatest/gh_10265_memtx_checkpoint_fail_assertion_test.lua
When checkpoint fails, we abort it in all engines even if it wasn't started succesfully. If it fails right from the start so that checkpoint in memtx wasn't started, assertion in `memtx_engine_abort_checkpoint` fails - memtx doesn't expect that checkpoint will be aborted if it failed to start. Let's do the same thing as vinyl does - no-op if there is no checkpoint in progress.
Closes #10265
> memtx: allow to abort checkpoint if it wasn't started

- .gitattributes
The motivation is to exclude the file from diffs on GitHub's web interface (https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) and to exclude it from checkpatch checks (https://github.com/tarantool/checkpatch/pull/75).
> uri: mark the parser source file as generated

- changelogs/unreleased/gh-9556-fix-uri-ipv6.md
- src/lib/uri/uri.c
- src/lib/uri/uri_parser.c
- src/lib/uri/uri_parser.rl
- src/lua/uri.lua
- test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua
Before this patch `uri.parse(<uri-string-with-ipv6-address>)` did not work correctly. In particular, it did not parse an IPv6 address if it contained `A-F`. It is a regression caused by commit https://github.com/tarantool/tarantool/commit/1376aad9b3fd1fa3c42a220dafeadaa63387f7a2 ("Refactor src/uri.rl to support RFC3986 and add Lua bindings").
This patch fixes a bug where characters `A-F` are not supported in IPv6. Also this patch adds encapsulation for IPv6 addresses in brackets when calling uri.format (as per RFC 2732).
Closes #9556
> uri: fix IPv6 parsing regression, encapsulate IPv6 addresses in brackets []

- .gitattributes
- changelogs/unreleased/gh-9556-fix-uri-ipv6.md
- src/lib/uri/uri.c
- src/lib/uri/uri_parser.c
- src/lib/uri/uri_parser.rl
- src/lua/uri.lua
- test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua
*(This is a backport of PR #10320 and PR #10315 to `release/3.1`, future `3.1.1` release.)*
----
Before this patch `uri.parse(<uri-string-with-ipv6-address>)` did not work correctly. In particular, it did not parse an IPv6 address if it contained `A-F`. It is a regression caused by commit https://github.com/tarantool/tarantool/commit/1376aad9b3fd1fa3c42a220dafeadaa63387f7a2 ("Refactor src/uri.rl to support RFC3986 and add Lua bindings").
This patch fixes a bug where characters `A-F` are not supported in IPv6. Also this patch adds encapsulation for IPv6 addresses in brackets when calling uri.format (as per RFC 2732).
Closes #9556
> [backport 3.1] uri: fix IPv6 parsing regression, encapsulate IPv6 addresses in brackets []

- .gitattributes
- changelogs/unreleased/gh-9556-fix-uri-ipv6.md
- src/lib/uri/uri.c
- src/lib/uri/uri_parser.c
- src/lib/uri/uri_parser.rl
- src/lua/uri.lua
- test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua
*(This is a backport of PR #10320 and PR #10315 to `release/2.11`, future `2.11.14` release.)*
----
Before this patch `uri.parse(<uri-string-with-ipv6-address>)` did not work correctly. In particular, it did not parse an IPv6 address if it contained `A-F`. It is a regression caused by commit https://github.com/tarantool/tarantool/commit/1376aad9b3fd1fa3c42a220dafeadaa63387f7a2 ("Refactor src/uri.rl to support RFC3986 and add Lua bindings").
This patch fixes a bug where characters `A-F` are not supported in IPv6. Also this patch adds encapsulation for IPv6 addresses in brackets when calling uri.format (as per RFC 2732).
Closes #9556
> [backport 2.11] uri: fix IPv6 parsing regression, encapsulate IPv6 addresses in brackets []

- changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
- test/app-tap/lua/serializer_test.lua
- third_party/lua-yaml/lyaml.cc
Since tarantool/luajit@a16313f large exponent double strings are not considered convertable to number. It broke encoding lua objects to YAML because single quotes weren't considered neccessary for decoding.
This fix adds wrapping of every string containing double values equal to infinity into a single quotes.
Closes #10164
> lua-yaml: wrap large doubles in quotes

- changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
- test/app-tap/lua/serializer_test.lua
- third_party/lua-yaml/lyaml.cc
*(This is a backport of PR #10218 to `release/2.11`, future `2.11.4` release.)*
----
Since tarantool/luajit@a16313f large exponent double strings are not considered convertible to number. It broke encoding lua objects to YAML because single quotes weren't considered necessary for decoding.
This commit adds wrapping of every string containing infinite double values into a single quotes.
Closes #10164
> [backport 2.11] lua-yaml: wrap large doubles in quotes

- changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
- test/app-tap/lua/serializer_test.lua
- third_party/lua-yaml/lyaml.cc
*(This is a backport of PR #10218 to `release/3.1`, future `3.1.2` release.)*
----
Since tarantool/luajit@a16313f large exponent double strings are not considered convertible to number. It broke encoding lua objects to YAML because single quotes weren't considered necessary for decoding.
This commit adds wrapping of every string containing infinite double values into a single quotes.
Closes #10164
> [backport 3.1] lua-yaml: wrap large doubles in quotes

- src/box/box.cc
- src/box/engine.c
- src/box/engine.h
- src/box/errcode.h
- src/box/memtx_engine.cc
- src/box/txn.c
- src/box/txn.h
- src/box/vinyl.c
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
- test/box/transaction.result
- test/sql/triggers.result
This patch replaces `txn::engine` with `txn::engines[3]`, so that a multi-statement transaction can involve up to 3 storage engines. However, for now the `ENGINE_SUPPORTS_CROSS_ENGINE_TX` flag is set only for `memtx` engine (when MVCC is off), so there are no user-visible changes.
Needed for #1803
Needed for tarantool/tarantool-ee#823
> txn: first step towards cross-engine transactions

- changelogs/unreleased/gh-10349-func-index-without-sandbox.md
- src/box/alter.cc
- test/box-luatest/gh_10349_functional_index_without_sandbox_test.lua
- test/engine/func_index.result
- test/engine/func_index.test.lua
The requirement for a function used in a functional index to be sandboxed is way too strict because a sandbox environment includes only a handful of Lua built-ins, like `math` or `table`. This makes it impossible for a functional index function to call built-in deterministic functions defined in modules (like `msgpack.encode` or `json.encode`) while this could be useful in certain scenarios (see #10349 for an example). Let's allow users to create functional indexes using non-sandboxed functions at their own risk.
Closes #4765
Closes #10349
> box: don't require functional index function to be sandboxed

- changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
- src/lib/core/datetime.c
- test/app-tap/datetime.test.lua
datetime object can be created using `datetime.new()` and `datetime.parse()`. `datetime.new()` sets values of unspecified fields to appropriate values of fields in a Unix time (00:00:00 UTC on 1 January 1971, Thursday), see commit 43e10ed34949 ("build, lua: built-in module datetime"):
```lua
tarantool> datetime.new()
---
...
tarantool> datetime.new():totable()
---
- sec: 0
min: 0
yday: 1
day: 1
nsec: 0
isdst: false
wday: 5
tzoffset: 0
month: 1
year: 1970
hour: 0
```
The function `datetime.parse` converts an input string with the date and time information into a datetime object. When fields are not specified in a input string their values becomes undefined:
```
tarantool> dt.parse('01:01:01', {format ='%H:%M:%S'}):totable()
---
- sec: -59
min: -58
yday: 366
day: 31 …
```
> datetime: fix values of unspecified fields in dt.parse()

- changelogs/unreleased/gh-9535-close-listen-socket-after-replace.md
- src/box/lua/config/applier/console.lua
- test/config-luatest/console_test.lua
Аfter replacing the `console.socket` in config tarantool keeps listening on the previous socket (by default `var/{{ instance_name }}/run/tarantool.control` or the previous socket set to `console.socket`). This patch closes the old listening sockets on the reconfiguration.
Closes #9535
> config: close old sockets after replacing socket

- changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
- src/lib/core/datetime.c
- test/app-tap/datetime.test.lua
datetime object can be created using `datetime.new()` and `datetime.parse()`. `datetime.new()` sets values of unspecified fields to appropriate values of fields in a Unix time (00:00:00 UTC on 1 January 1971, Thursday), see commit 43e10ed34949 ("build, lua: built-in module datetime"):
```
tarantool> datetime.new()
---
...
tarantool> datetime.new():totable()
---
- sec: 0
min: 0
yday: 1
day: 1
nsec: 0
isdst: false
wday: 5
tzoffset: 0
month: 1
year: 1970
hour: 0
```
The function `datetime.parse` converts an input string with the date and time information into a datetime object. When fields are not specified in a input string their values becomes undefined:
```
tarantool> dt.parse('01:01:01', {format ='%H:%M:%S'}):totable()
---
- sec: -59
min: -58
yday: 366
day: 31 …
```
> [Backport 3.1] datetime: fix values of unspecified fields in dt.parse()

- changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
- src/lib/core/datetime.c
- test/app-tap/datetime.test.lua
datetime object can be created using `datetime.new()` and `datetime.parse()`. `datetime.new()` sets values of unspecified fields to appropriate values of fields in a Unix time (00:00:00 UTC on 1 January 1971, Thursday), see commit 43e10ed34949 ("build, lua: built-in module datetime"):
```
tarantool> datetime.new()
---
...
tarantool> datetime.new():totable()
---
- sec: 0
min: 0
yday: 1
day: 1
nsec: 0
isdst: false
wday: 5
tzoffset: 0
month: 1
year: 1970
hour: 0
```
The function `datetime.parse` converts an input string with the date and time information into a datetime object. When fields are not specified in a input string their values becomes undefined:
```
tarantool> dt.parse('01:01:01', {format ='%H:%M:%S'}):totable()
---
- sec: -59
min: -58
yday: 366
day: 31 …
```
> [Backport 2.11] datetime: fix values of unspecified fields in dt.parse() 

- changelogs/unreleased/gh-9535-close-listen-socket-after-replace.md
- src/box/lua/config/applier/console.lua
- test/config-luatest/console_test.lua
*(This is a backport of PR #10198 to `release/3.1`, a future `3.1.2` release.)*
----
Аfter replacing the `console.socket` in config tarantool keeps listening on the previous socket (by default `var/{{ instance_name }}/run/tarantool.control` or the previous socket set to `console.socket`). This patch closes the old listening sockets on the reconfiguration.
Closes #9535
> [backport 3.1] config: close old socket after replacing socket

- src/box/lua/info.c
- src/box/lua/slab.cc
- src/lua/utils.c
- src/lua/utils.h
Replaced G(L)->gc.total calls to lua_gc().
To ensure better encapsulation, maintainability, and portability of
the code, it is necessary to replace direct access to the fields of
global structures with calls using the Lua C API.
Closes https://github.com/tarantool/tarantool/issues/10284
> refactor: use Lua C API instead of G(L)->gc.total

- changelogs/unreleased/gh-10375-vy-do-not-abort-unrelated-tx-on-ddl.md
- src/box/engine.h
- src/box/memtx_tx.c
- src/box/txn.c
- src/box/txn.h
- src/box/vinyl.c
- test/engine-luatest/gh_10375_ddl_does_not_abort_unrelated_transactions_test.lua
Since commit 8f4be3227635 ("txm: disallow yields after DDL operation in TX"), any DDL operation aborts **all** active transactions, even those that wouldn't be affected by it anyway, see `memtx_engine_prepare()`, `memtx_tx_abort_all_for_ddl()`. Actually, there's no need to do that in Vinyl because it properly handles concurrent DDL operations, see commit d3e123695651 ("vinyl: abort affected transactions when space is removed from cache"). Let's skip Vinyl transactions from consideration by marking the Vinyl engine with a special flag.
Closes #10375
> vinyl: do not abort unrelated transactions on DDL

- src/box/lua/info.c
- src/box/lua/slab.cc
- src/lua/utils.c
- src/lua/utils.h
(This is a backport of PR #10297 to release/3.1, future 3.1.1 release.)
----
To ensure better encapsulation, maintainability, and portability of the code, it is necessary to replace direct access to the fields of global structures with calls using the Lua C API.
Closes #10284
(cherry picked from commit f7bb3fc7a1222107753dc420675ecda043b0a5d2)
> [backport 3.1] refactor: use Lua C API instead of G(L)

- src/box/lua/info.c
- src/box/lua/slab.cc
- src/lua/utils.c
- src/lua/utils.h
*(This is a backport of PR #10297  to `release/2.11`, future `2.11.14` release.)*
----
To ensure better encapsulation, maintainability, and portability of the code, it is necessary to replace direct access to the fields of global structures with calls using the Lua C API.
Closes #10284
(cherry picked from commit f7bb3fc7a1222107753dc420675ecda043b0a5d2)
> [backport 2.11] refactor: use Lua C API instead of G(L)

- src/box/lua/console.c
- src/box/lua/serialize_lua.c
- src/box/lua/serialize_lua.h
This patch fixes a bug found by the ASAN instrumentation of LuaJIT
allocator [1]. The problem is using a Lua serializer object that has
been cleaned up by GC.
Tarantool build:
- Tarantool 3.2.0-entrypoint-84-g9d3859b24
- Target: Linux-x86_64-Debug
- Compiler: Clang-14.0.0
- LuaJIT branch: mandesero/dlmalloc-instr
- CMAKE_FLAGS:
```
-DENABLE_WERROR=ON -DENABLE_ASAN=ON -DENABLE_UB_SANITIZER=ON
-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF -DENABLE_FUZZER=ON
-DTEST_BUILD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
-DFIBER_STACK_SIZE=640Kb -DLUAJIT_ENABLE_GC64=ON
-DCMAKE_BUILD_TYPE=Debug
```
- ASAN_OPTIONS:
```
detect_invalid_pointer_pairs=1:detect_leaks=1:\
dump_instruction_bytes=1:heap_profile=0:\
print_suppressions=0:symbolize=1:unmap_shadow_on_exit=1:\
redzone=32
```
- LSAN_OPTIONS:
``` …
```
> serializer: remove duplicate of lua serializer

- src/box/lua/console.c
- src/box/lua/serialize_lua.c
- src/box/lua/serialize_lua.h
*(This is a backport of PR #10227 to `release/3.1`, a future `3.1.2` release.)*
----
This patch fixes a bug found by the ASAN instrumentation of LuaJIT allocator [1]. The problem is using a Lua serializer object that has been cleaned up by GC.
The crash occurs when executing `tarantool> \set output lua`.
Failing tests:
- ./test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- ./test/app-tap/console.test.lua
- ./test/box/push.test.lua
- ./app-tap/console_lua.test.lua
- ./app-luatest/varbinary_test.lua
The `serializer_lua` static member is removed from `src/box/lua/serialize_lua.c` along with `serializer_lua_init`, because it is not used by any function other than `serializer_lua_init`, which is not needed now too.
[1]: Issue #10231
Closes #10177 (this issue is a duplicate of …
> [backport 3.1] serializer: remove duplicate of lua serializer

- src/box/lua/console.c
- src/box/lua/serialize_lua.c
- src/box/lua/serialize_lua.h
*(This is a backport of PR #10227 to `release/2.11`, a future `2.11.4` release.)*
----
This patch fixes a bug found by the ASAN instrumentation of LuaJIT allocator [1]. The problem is using a Lua serializer object that has been cleaned up by GC.
The crash occurs when executing `tarantool> \set output lua`.
Failing tests:
- ./test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
- ./test/app-tap/console.test.lua
- ./test/box/push.test.lua
- ./app-tap/console_lua.test.lua
- ./app-luatest/varbinary_test.lua
The `serializer_lua` static member is removed from `src/box/lua/serialize_lua.c` along with `serializer_lua_init`, because it is not used by any function other than `serializer_lua_init`, which is not needed now too.
[1]: Issue #10231
Closes #10177 (this issue is a duplicate of …
> [backport 2.11] serializer: remove duplicate of lua serializer

- CMakeLists.txt
- changelogs/unreleased/show-tzdata-version.md
- src/lua/init.c
- src/trivia/config.h.cmake
- src/version.c
- src/version.h
- test/app-tap/info.test.lua
Show tzdata version in `tarantool.build.tzdata_version`.
Title: Document `tarantool.build.tzdata_version`
The option shows a version of tzdata module:
```
tarantool> require('tarantool').build.tzdata_version
---
- 2024a
...
```
Please update the tarantool module documentation:
https://www.tarantool.io/en/doc/latest/reference/reference_lua/tarantool/
> build: show tzdata version in tarantool module

- changelogs/unreleased/gh-10331-tz-in-totable.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
- test/sql-luatest/datetime_test.lua
``` 
datetime: support tz field in :totable()
`datetime` module has a function `:totable()` that converts
the information from a datetime object into the table format.
The commit 43e10ed34949 ("build, lua: built-in module datetime")
added `tzoffset` field to datetime object and to table produced by
`:totable()`. The commit 9ee45289e012
("datetime: datetime.TZ array") added fields `tz` and `tzindex` to
datetime object, but not to a table produced by `:totable()`.
The patch fixes that.
```
tarantool> datetime.parse('2004-12-01T00:00 Europe/Moscow'):totable()
---
- tz: Europe/Moscow
tzindex: 947
sec: 0
min: 0
yday: 336
day: 1
nsec: 0
isdst: false
wday: 4
tzoffset: 180
month: 12
year: 2004
hour: 0
...
```
Note, `tzindex` is not added, because it is an internal field.
Fixes #10331
Follows up …
```
> datetime: support tz field in :totable()

- changelogs/unreleased/gh-9849-grant-revoke-user-right-after-upgrade.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/upgrade_test.lua
This PR:
- Uses `box.space._schema:on_replace()` for automatically granting/revoking user rights after upgrading the scheme without restarting.
- Adds error messages in case granting/revoking credentials broke.
Closes #9849
> box: grant/revoke user right after upgrade

- changelogs/unreleased/gh-9849-grant-revoke-user-right-after-upgrade.md
- src/box/lua/config/applier/credentials.lua
- test/config-luatest/upgrade_test.lua
*(This is a backport of PR #10248 to `release/3.1`, a future `3.1.2` release.)*
----
This PR:
- Uses `box.space._schema:on_replace()` for automatically granting/revoking user rights after upgrading the scheme without restarting.
- Adds error messages in case granting/revoking credentials broke.
Closes #9849
> [backport 3.1] box: grant/revoke user rights after upgrade

- changelogs/unreleased/gh-9723-sync-system-spaces.md
- extra/exports
- src/box/lua/config/instance_config.lua
- src/box/lua/space.cc
- src/box/schema_def.h
- src/box/space.c
- src/box/space.h
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- src/lua/compat.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/replication-luatest/gh_9723_sync_system_spaces_test.lua
- test/replication/qsync_basic.result
- test/replication/qsync_basic.test.lua
- test/unit/snap_quorum_delay.cc
This patch series enables synchronous replication for systems spaces when the synchronous queue is claimed.
Closes #9723
> Enable synchronous replication for systems spaces when the synchronous queue is claimed

- changelogs/unreleased/gh-10318-connpool-sharding-roles-filter.md
- src/box/lua/connpool.lua
- test/config-luatest/rpc_test.lua
Support filtering replicasets by the configured sharding role by adding `sharding_roles` into the `connpool.filter()` and `connpool.call()` options.
Closes #10318
> connpool: support filtering by `sharding.roles`

- changelogs/unreleased/gh-10412-box-begin-is-sync-async-commit-after-recovery.md
- src/box/box.cc
- test/box-luatest/gh_10412_box_begin_is_sync_async_commit_after_recovery_test.lua
This patch fixes a bug that caused synchronous transactions (created with `box.begin{is_sync = true}`) on asynchronous spaces to get committed asynchronously during recovery.
Closes #10412
> box: account for `wait_ack` flag of the tx's last row during recovery

- extra/exports
- src/box/box.cc
- src/box/box.h
- src/box/lua/info.c
- test/box-luatest/gh_10378_export_symbols_test.lua
box_info_lsn
box_is_ro
box_ro_reason
box_wait_ro
Closes #10378
NO_CHANGELOG=minor change
Title: document 4 more symbols in public C API
box_info_lsn
box_is_ro
box_ro_reason
box_wait_ro
Their meaning is identical to lua methods:
box.info.lsn
box.info.ro
box.info.ro_reason
box.wait_ro
(cherry picked from commit f1c76b976077e8078c42990546d9dbbdea315425)
> [backport 3.1] box: export more symbols

- changelogs/unreleased/gh-9401-anon-replica-synchro.md
- src/box/applier.cc
- src/box/box.cc
- src/box/engine.c
- src/box/engine.h
- src/box/iproto_constants.h
- src/box/memtx_engine.cc
- src/box/relay.cc
- src/box/relay.h
- src/box/vinyl.c
- src/box/xrow.c
- src/box/xrow.h
- src/trivia/config.h.cmake
- test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
- test/engine-luatest/checkpoint_test.lua
- test/replication-luatest/gh_9401_anon_replica_synchro_queue_state_test.lua
The last commit https://github.com/tarantool/tarantool/commit/62c49367a2eab6d8008da2d7201ffa03e002c31e will not be backported since it adds a feature with index 10, in 2.11 we have only 4 of them. Moreover, it bumps iproto version to 8, but all previous feature will not be supported.
It's not crucial, server just won't reply, that it has such feature.
Changelogs added in this backport must be marked experimental!!!  But only if they're features
> [backport 2.11] Add stubs for file FETCH_SNAPSHOT

- changelogs/unreleased/gh-10412-box-begin-is-sync-async-commit-after-recovery.md
- src/box/box.cc
- test/box-luatest/gh_10412_box_begin_is_sync_async_commit_after_recovery_test.lua
Currently, we do not account for the `wait_ack` flag of the transaction's last row during recovery, instead relying on the fact the transaction will be made synchronous when applying operations on a synchronous space.
However, this logic is at odds with explicitly created synchronous transactions (created with box.begin{is_sync = true}), which may not have operations on synchronous spaces. As a result, during recovery we do not treat these transactions as synchronous.
Let's fix this by mirroring the applier logic to the recovery.
Closes #10412
(cherry picked from commit c3ed71f37ca1c08ac1134da267866cc5cbaebe60)
> [backport 3.1] box: account for `wait_ack` flag of the tx's last row during recovery

- src/box/lua/execute.c
This patch fixes a bug found by the ASAN instrumentation of LuaJIT allocator [1]. The problem is using `memcpy` beyond the size of the buffer being copied.
Failing tests:
- ./test/sql-luatest/gh_10243_varbinary_bound_variable_test.lua
[1]: Issue https://github.com/tarantool/tarantool/issues/10231
Closes https://github.com/tarantool/tarantool/issues/10398
NO_DOC=bugfix
NO_TEST=rely on existing test (run failing tests with tarantool build described in [1]).
> sql: fix use-after-poison in variable binding

- src/box/lua/execute.c
*(This is a backport of PR #10399 to `release/3.1`, a future `3.1.2` release.)*
----
This patch fixes a bug found by the ASAN instrumentation of LuaJIT allocator [1]. The problem is using `memcpy` beyond the size of the buffer being copied.
Failing tests:
- ./test/sql-luatest/gh_10243_varbinary_bound_variable_test.lua
[1]: Issue #10231
Closes #10398
> [backport 3.1] sql: fix use-after-poison in variable binding

- changelogs/unreleased/gh-10304-allow-specific-function-access.md
- src/box/lua/config/applier/credentials.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/instance_config_schema_test.lua
- test/config-luatest/privileges_test.lua
This patch adds the capability to grant access to specific Lua functions in the declarative configuration. You can now grant access by assigning the function name to `credentials.users.<user>.privileges.lua_call`.
For example, setting
`credentials.users.alice.privileges.lua_call = ['foo']`
allows user 'alice' to execute the `foo` function.
Closes #10304
> config: grant access to specific function in config

- src/box/lua/execute.c
*(This is a backport of PR #10399 to `release/2.11`. It will likely land to `2.11.5`, because the branch is temporarily frozen to prepare the `2.11.4` release.)*
----
This patch fixes a bug found by the ASAN instrumentation of LuaJIT allocator [1]. The problem is using `memcpy` beyond the size of the buffer being copied.
Failing tests:
- ./test/sql-luatest/gh_10243_varbinary_bound_variable_test.lua
[1]: Issue #10231
Closes #10398
> [backport 2.11] sql: fix use-after-poison in variable binding

- CMakeLists.txt
There is BACKUP_STORAGE var to use any source to download dependencies. Convert it to option to make it possible to use it from command line.
NO_DOC=build
NO_TEST=build
> Change cmake variable BACKUP_STORAGE to option

- test/fuzz/CMakeLists.txt
Orig PR: https://github.com/tarantool/tarantool/pull/10431
----
Clang compiler is linking by default against libc++ rather than libstdc++, which the code seems to be built against.
The patch adds "-stdlib=libstdc++" that is required by build on OSS Fuzz and also removes dirty hacks in a build script [2][3] and allows to switch to a static build in OSS Fuzz.
1. https://libcxx.llvm.org/docs/UsingLibcxx.html
2. https://github.com/google/oss-fuzz/commit/92d4e951c3a10b8b3d67ccd061ddaba71f01a328
3. https://github.com/google/oss-fuzz/commit/7a6315db98f574cc8beb4de7f9d2e71c6c589a34
4. https://github.com/google/oss-fuzz/pull/12322
NO_DOC=testing
(cherry picked from commit 79737d9d13d9e473687192be76fe055658b6e0b8)
> [Backport 2.11] test/fuzz: update compiler and library flags

- test/fuzz/CMakeLists.txt
Orig PR: https://github.com/tarantool/tarantool/pull/10431
----
Clang compiler is linking by default against libc++ rather than libstdc++, which the code seems to be built against.
The patch adds "-stdlib=libstdc++" that is required by build on OSS Fuzz and also removes dirty hacks in a build script [2][3] and allows to switch to a static build in OSS Fuzz.
1. https://libcxx.llvm.org/docs/UsingLibcxx.html
2. https://github.com/google/oss-fuzz/commit/92d4e951c3a10b8b3d67ccd061ddaba71f01a328
3. https://github.com/google/oss-fuzz/commit/7a6315db98f574cc8beb4de7f9d2e71c6c589a34
4. https://github.com/google/oss-fuzz/pull/12322
NO_DOC=testing
(cherry picked from commit 79737d9d13d9e473687192be76fe055658b6e0b8)
> [Backport 3.1] test/fuzz: update compiler and library flags

- changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua
Currently, when starting an iterator in memtx tree on a range request, we pass key from `start_data` to memtx MVCC. The problem is `start_data` can contain pagination key that is extracted with `cmp_def`, but MVCC performs all comparisons with `key_def`. Fortunately, first parts of `cmp_def` is actually `key_def` of the index, so let's crop `start_data` by passing `part_count` not greater than `key_def->part_count` to MVCC.
Closes #10448
> memtx: do not pass pagination key to MVCC

- changelogs/unreleased/gh-10396-memtx-mvcc-exclude-null-count.md
- src/box/memtx_tx.c
- test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Excluded tuples actually have their own history chains in MVCC - such chains consist of only one `memtx_story` containing excluded tuple itself. Such chains should be skipped when counting invisible tuples because they are not inserted to the index - that's what the commit does.
Closes https://github.com/tarantool/tarantool/issues/10396
> memtx: skip excluded tuples in index count with MVCC enabled

- perf/memtx.cc
- src/box/alter.cc
- src/box/index.cc
- src/box/index_def.c
- src/box/index_def.h
- src/box/key_list.c
- src/box/schema.cc
- src/box/sql.c
- src/box/sql/build.c
- src/box/sql/where.c
- src/box/vinyl.c
- test/unit/vy_point_lookup.c
This patch fixes a bug that was introduced by commit https://github.com/tarantool/tarantool/commit/8fc59b101c10cf71fbb157b6f98b64eb8155ae63 that adds helper functions for initializing payloads of DML errors related to key validation.
The problem was that after the space was deleted, a situation could occur that the `space.def->name` was still needed to generate an error message if the key format was incorrect in the `get()` call from `read_view`.
This is exactly what happened sometimes in the function `error_set_index`. One of the bug reproducers was to try to `get()` with an incorrect key format (`ER_EXACT_MATCH`) in `read_view` from deleted space.
The problem has been fixed: space name as well as engine name are also `index_def` fields now. There is no need to search for space and get …
> box: store space name and engine name in `index_def` for error reporting

- changelogs/unreleased/gh-10442-vy-exact-match-optimization.md
- src/box/vy_read_iterator.c
- src/box/vy_read_iterator.h
- src/box/vy_stmt.c
- src/box/vy_stmt.h
- test/vinyl-luatest/gh_10442_exact_match_optimization_test.lua
If the iterator type is EQ/REQ/LE/GE and the search key is exact (that is, there may be at most one tuple matching the key in the index), there's no need to scan disk levels if we found a statement for this key in the memory level. We've had this optimization for ages but it worked only for full keys in terms `cmp_def` (key definition extended with primary key parts). Apparently, a lookup in a secondary index performed by the user wouldn't match these criteria unless the secondary index explicitly included all primary key parts.
This commit improves on that. Now, we enable the optimization if the search key is **exact**. We consider a key **exact** if either of the following conditions is true:
- The key statement is a tuple (tuple has all key parts).
- The key statement is a full key in …
> vinyl: enable exact match optimization for unique secondary indexes

- changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua
Currently, when starting an iterator in memtx tree on a range request, we pass key from `start_data` to memtx MVCC. The problem is `start_data` can contain pagination key that is extracted with `cmp_def`, but MVCC performs all comparisons with `key_def`. Fortunately, first parts of `cmp_def` is actually `key_def` of the index, so let's crop `start_data` by passing `part_count` not greater than `key_def->part_count` to MVCC.
Closes #10448
NO_DOC=bugfix
(cherry picked from commit 0dca0076c0fdaee142020cdeddb031bc0e2238cb)
> [backport 2.11] memtx: do not pass pagination key to MVCC

- changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
- src/box/memtx_tree.cc
- test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua
Currently, when starting an iterator in memtx tree on a range request, we pass key from `start_data` to memtx MVCC. The problem is `start_data` can contain pagination key that is extracted with `cmp_def`, but MVCC performs all comparisons with `key_def`. Fortunately, first parts of `cmp_def` is actually `key_def` of the index, so let's crop `start_data` by passing `part_count` not greater than `key_def->part_count` to MVCC.
Closes #10448
NO_DOC=bugfix
(cherry picked from commit 0dca0076c0fdaee142020cdeddb031bc0e2238cb)
> [backport 3.1] memtx: do not pass pagination key to MVCC

- changelogs/unreleased/gh-10396-memtx-mvcc-exclude-null-count.md
- src/box/memtx_tx.c
- test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Excluded tuples actually have their own history chains in MVCC - such chains consist of only one `memtx_story` containing excluded tuple itself. Such chains should be skipped when counting invisible tuples because they are not inserted to the index - that's what the commit does.
Closes #10396
NO_DOC=bugfix
(cherry picked from commit 8947cb04f59423e2944d48b8a1effec2fb11b1db)
> [backport 3.1] memtx: skip excluded tuples in index count with MVCC enabled

- changelogs/unreleased/gh-10396-memtx-mvcc-exclude-null-count.md
- src/box/memtx_tx.c
- test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Excluded tuples actually have their own history chains in MVCC - such chains consist of only one `memtx_story` containing excluded tuple itself. Such chains should be skipped when counting invisible tuples because they are not inserted to the index - that's what the commit does.
Closes #10396
NO_DOC=bugfix
(cherry picked from commit 8947cb04f59423e2944d48b8a1effec2fb11b1db)
> [backport 2.11] memtx: skip excluded tuples in index count with MVCC enabled

- changelogs/unreleased/gh-10452-vy-log-discard-run-after-index-drop-fix.md
- src/box/vy_scheduler.c
- test/vinyl-luatest/gh_10452_discard_run_after_index_drop_test.lua
If an index is dropped while a dump or compaction task is in progress we must not write any information about it to the vylog when the task completes otherwise there's a risk of getting a vylog recovery failure in case the garbage collector manages to purge the index from the vylog.
We disabled logging on successful completion of a dump task quite a while ago, in commit 29e2931c66c5 ("vinyl: fix race between compaction and gc of dropped LSM"), and for compaction only recently, in commit ae6a02ebab0b ("vinyl: do not log dump if index was dropped"), but the issue remains for a dump/compaction failure, when we log a discard record for a run file we failed to write. These results in errors like:
```
ER_INVALID_VYLOG_FILE: Invalid VYLOG file: Run 6 deleted twice
```
or
``` …
```
> vinyl: do not discard run on dump/compaction abort if index was dropped

- changelogs/3.1.2.md
- changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
- changelogs/unreleased/gh-10199-luajit-fixes.md
- changelogs/unreleased/gh-10280-fix-replication-sync-timeout-default-value.md
- changelogs/unreleased/gh-10331-tz-in-totable.md
- changelogs/unreleased/gh-10374-timestamp-in-totable.md
- changelogs/unreleased/gh-10375-vy-do-not-abort-unrelated-tx-on-ddl.md
- changelogs/unreleased/gh-10396-memtx-mvcc-exclude-null-count.md
- changelogs/unreleased/gh-10412-box-begin-is-sync-async-commit-after-recovery.md
- changelogs/unreleased/gh-10442-vy-exact-match-optimization.md
- changelogs/unreleased/gh-10452-vy-log-discard-run-after-index-drop-fix.md
- changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
- changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
- changelogs/unreleased/gh-9535-close-listen-socket-after-replace.md
- changelogs/unreleased/gh-9849-grant-revoke-user-right-after-upgrade.md
- src/box/lua/upgrade.lua
Also, remote unreleased/ entries and add a new downgrade version to downgrade versions list.
@Totktonada, I see some entries which duplicate the ones fixed in 2.11.4 (https://github.com/tarantool/tarantool/releases/tag/2.11.4). I'm not sure if we should remove or keep them in this changelog.
> [release/3.1] Generate changelog for 3.1.2

- test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua
The test function `g.jit_off_on_macOS_by_default` in `gh_8252` was silently ignored by the luatest due to its lack of the required `test_` prefix. This commit renames the function to `test_jit_off_on_macOS_by_default`, ensuring that it is recognized and executed by the luatest.
Closes #10210
NO_CHANGELOG=codehealt
> refactor: rename test function in gh_8252 with luatest requirements

- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- test/box-luatest/gh_8204_fast_offset_test.lua
Prior to this patch the count request had been performed in the memtx
in a straightforward way: we created an iterator by a type and key and
simply called its `next` method until it's exhausted. That means the
operation had a linear complexity, which could lead to DoS situations.
Also the count operation with ALL iterator hadn't been recorded in the
MVCC previously and had an erroneous logic (see the https://github.com/tarantool/tarantool/issues/10140). This is
fixed too as a side effect.
This patch makes the memtx tree index use a version of BPS tree with
the cardinality information enabled and takes advantage of its offset
based API to implement the count operation using tree lookups.
Since the method does not read each counted tuple now, MVCC subsystem
would be unaware of it. In order …
> Implement logarithmic `index:count` in the memtx tree

- test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua
*(This is a backport of PR #10408 to release/2.11)*
--------------
The test function `g.jit_off_on_macOS_by_default` in `gh_8252` was silently ignored by the luatest due to its lack of the required `test_` prefix. This commit renames the function to `test_jit_off_on_macOS_by_default`, ensuring that it is recognized and executed by the luatest.
Closes #10210
> [backport 2.11] test: add test_ prefix to a function name

- test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua
*(This is a backport of PR #10408 to release/3.2)*
--------------
The test function `g.jit_off_on_macOS_by_default` in `gh_8252` was silently ignored by the luatest due to its lack of the required `test_` prefix. This commit renames the function to `test_jit_off_on_macOS_by_default`, ensuring that it is recognized and executed by the luatest.
Closes #10210
> [backport 3.2] test: add test_ prefix to a function name 

- tools/check-entrypoint-tag.sh
In practice we may want to create new branch exactly for release skipping release candidate etc.
Closes #10501
> tools: do not require entrypoint in branch

- changelogs/unreleased/gh-10512-fix-vinyl-page-load-error-handling.md
- src/box/vy_run.c
- test/vinyl-luatest/gh_10512_page_load_error_test.lua
`vy_page_stmt()` may fail (return NULL) if:
- the statement is corrupted;
- memory allocation for the statement fails;
- the statement size exceeds `box.cfg.vinyl_max_tuple_size`.
If this happens `vy_page_find_key()` won't return an error. Instead, it'll either point the caller to a wrong statement or claim that there's no statement matching the key in this page. This may result in invalid index selection results and, later on, a crash caused by inconsistencies in the tuple cache. The issue was introduced by commit ac8ce0233a00.
All of the three cases are actually very unlikely to happen in production:
- If a statement stored in a run file is corrupted, we'll probably fail to load the whole page due to failed checksums and never even get to `vy_page_stmt()`.
- Statements are allocated …
> vinyl: handle error loading statement from disk during key lookup

- changelogs/unreleased/gh-10148-fix-small-crash-low-alloc-factor.md
- test/box-luatest/gh_10148_fix_crash_low_slab_alloc_factor_test.lua
Closes #10148
Small PR https://github.com/tarantool/small/pull/94
> Fix crash in small when when `slab_alloc_factor` is low and memory pressure is high

- changelogs/unreleased/gh-10524-use-verbose-level-for-logging-vinyl-ranges.md
- src/box/vy_lsm.c
- src/box/vy_scheduler.c
- test/vinyl-luatest/shutdown_test.lua
Whenever a range is compacted, split, or coalesced, we log the range boundaries. This gets really annoying if there's an index that has a lot of key parts or contains binary strings. Let's lower the level used for logging these events down to VERBOSE so that they are not shown by default but can be enabled if needed.
Closes #10524
> vinyl: use VERBOSE level for logging ranges

- src/box/vinyl.c
- src/box/vy_point_lookup.c
- src/lib/core/errinj.h
- test/fuzz/lua/test_engine.lua
- test/vinyl/errinj.result
- test/vinyl/errinj.test.lua
Enabling `ERRINJ_VY_DELAY_PK_LOOKUP` makes Vinyl yield in a place where it wouldn't normally do. If the transaction is aborted in the meantime, we'll get the assertion failure:
```
./src/box/vy_point_lookup.c:219: vy_point_lookup: Assertion 'tx == NULL || tx->state == VINYL_TX_READY' failed.
```
To prevent this from happening, let's replace this invalid error injection with the new one `ERRINJ_VY_POINT_LOOKUP_DELAY` that injects a delay to `vy_point_lookup()` before reading disk. This doesn't have exactly the same effect as the old error injection because it also delays direct lookups in the primary index. Fortunately, the old error injection is used in the only test, where the new one works as expected if we make the secondary index created in the test non-unique and enable deferred …
> vinyl: fix `ERRINJ_VY_DELAY_PK_LOOKUP`

- test/box-luatest/gh_10148_fix_crash_low_slab_alloc_factor_test.lua
The test may exceed the default fiber slice (1 second):
```
[060] server | 2024-09-09 09:16:16.329 [33093] main/111/main fiber.h:1132 W> fiber has not yielded for more than 0.500 seconds
[060] server | 2024-09-09 09:16:16.825 [33093] main/111/main/test-run.lib.luatest.luatest.log I> Assert "FiberSliceIsExceeded" equals to "OutOfMemory"
[060] not ok 1	box-luatest.gh_10148_fix_crash_low_slab_alloc_factor.test_low_slab_alloc_factor
[060] #   ...uatest/gh_10148_fix_crash_low_slab_alloc_factor_test.lua:36: expected: "OutOfMemory"
[060] #   actual: "FiberSliceIsExceeded"
[060] #   stack traceback:
[060] #   	...uatest/gh_10148_fix_crash_low_slab_alloc_factor_test.lua:30: in function 'box-luatest.gh_10148_fix_crash_low_slab_alloc_factor.test_low_slab_alloc_factor'
[060] #   	...
[060] #   	[C]: …
```
> test: fix flaky #10148 test

- test/fuzz/lua/test_engine.lua
The remote console is enabled for debugging purposes. It can be helpful when Tarantool is stuck and need an access to console to gather an additional information about state.
NO_DOC=testing
> test: enable remote console for debug

- test/fuzz/lua/test_engine.lua
The function `console.listen` does not accept a path with duplicate slashes, so absolute pathes were rejected. The patch fixes that by building a path to Unix socket using `fio.pathjoin` that avoid double slashes. Follows up the commit 5d18b84e1e76 ("test: enable remote console for debug").
NO_DOC=testing
> test/fuzz: fix socket path in an engine test

- src/box/lua/config/configdata.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
Added the support for the failover per repliaset `failover.replicasets` configuration. Existance of the specified replicasets are checked when the config is loaded.
Added the `failover.replicasets.<replicaset_name>.priority` section for specifying the priorities for the supervised failover per each instance. Made the config applier check if all of the specified instances exist.
EE Issue: [tarantool/taranool-ee#846](https://github.com/tarantool/tarantool-ee/issues/846)
EE PR: [tarantool/tarantool-ee#845](https://github.com/tarantool/tarantool-ee/pull/845)
> config: add per instance failover priority

- .pack.mk
- apk/APKBUILD
- cmake/compiler.cmake
- debian/rules
- rpm/tarantool.spec
- rump/Makefile
`CMAKE_BUILD_TYPE` environment is now considered in all Tarantool packages specs. The behavior is the same as before if omitted (build RelWithDebInfo). Command to build debug tarantool package:
`CMAKE_BUILD_TYPE=Debug OS=ubuntu DIST=jammy make -f .pack.mk package`
Part of #5416
NO_TEST=make
NO_CHANGELOG=make
NO_DOC=make
> build: allow to build debug packages

- test/fuzz/lua/test_engine.lua
`test_engine.lua` actively uses error injections. Sometimes error injections remain enabled and triggered on test teardown. This leads to false positive test fails like below:
NOWRAP
```
2024-09-10 12:38:42.317 [1305] main/3502/WRK #3387/..test.fuzz.lua.test_engine I> Worker #3387 has finished.
2024-09-10 12:38:47.167 [1305] main/104/test_engine.lua/..test.fuzz.lua.test_engine I> TEARDOWN
2024-09-10 12:38:47.171 [1305] main/104/test_engine.lua wal.c:1327 E> ER_WAL_IO: Failed to write to disk
2024-09-10 12:38:47.174 [1305] main test_engine.lua:564 E> ER_WAL_IO: Failed to write to disk
2024-09-10 12:38:47.174 [1305] main F> fatal error, exiting the event loop
```
NOWRAP
The patch disables error injection at the beginning of teardown.
NO_DOC=testing
> test/fuzz: disable error injections on teardown

- src/main.cc
- test/box-py/args.result
Changes `tt start --name <instance name>` to `tt start <app name>:<instance name>`.
Fixes #10563
> doc: fix tt start command in --help

- src/box/memtx_tx.c
- test/box-luatest/mvcc_ddl_test.lua
During the latest rework of DDL in MVCC, the new helper `memtx_tx_history_rollback_empty_stmt` was introduced - it is used for statements without stories (such statements can appear, for example, when DDL removes all stories). By mistake, we forgot to unreference the new tuple and reference the old one there - the commit fixes this embarassing mistake.
Follow-up #10146
> memtx: reference tuples when rolling back statements without story

- src/main.cc
- test/box-py/args.result
*(This is a backport of PR #10568 to `release/3.2`, a future `3.2.1` release.)*
----
Changes `tt start --name <instance name>` to `tt start <app name>:<instance name>`.
Fixes #10563
> [backport 3.2] doc: fix tt start command in --help

- changelogs/unreleased/gh-8204-offset_of.md
- changelogs/unreleased/gh-8204-pairs-offset.md
- changelogs/unreleased/gh-8204-select-offset-count-perf.md
- extra/exports
- src/box/box.cc
- src/box/index.cc
- src/box/index.h
- src/box/lua/index.c
- src/box/lua/schema.lua
- src/box/memtx_bitset.cc
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/session_settings.c
- src/box/sysview.c
- src/box/vinyl.c
- test/box-luatest/gh_8204_fast_offset_test.lua
This patchset completes the CE part of the logarithmic offset RFC:
1. accelerate the `select` with `offset` in memtx;
2. introduce the `offset` parameter of `index:pairs` method;
3. introduce the `index:offset_of` method.
Closes #8204
> Finish the CE part of the logarithmic offset RFC

- changelogs/unreleased/gh-10551-fix-index-crash-on-OOM-on-rollback.md
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/lib/core/assoc.h
- test/box-luatest/gh_10551_massive_index_change_on_rollback_test.lua
We cannot tolerate index extent memory allocation failure on rollback. At the same time it is not practical to reserve memory because a whole index can easily be changed on rollback if read view is created before rollback.
So in case of rollback and memtx memory OOM let's allocate outside the memtx arena limited by quota.
Now part of the index can reside outside memtx arena. But regularly the index changes will move this part back to the memtx arena. Until next such situation of course.
Closes #10551
> box: fix crash on rollback on memtx memory OOM and massive index change

- cmake/luajit.cmake
- src/lua/varbinary.lua
Original PR:  "test/fuzz: unblock tests after fixing UBSan" #10276 
Commit "test/fuzz: unblock tests after fixing UBSan" b6efcd114a9ebf1e9ea573e51bc6cf2a871d0e0b is missed intentionally.
> [Backport 3.2]  test/fuzz: unblock tests after fixing UBSan

- changelogs/unreleased/gh-10146-mvcc-ddl-crashes-and-isolation-violation.md
- src/box/index.cc
- src/box/memtx_space.c
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/space.c
- src/lib/core/errinj.h
- test/box-luatest/mvcc_ddl_stress_test.lua
- test/box-luatest/mvcc_ddl_test.lua
This is a backport of #10160 and #10567 to 2.11
> [backport 2.11] memtx: re-design handling of DDL in memtx MVCC

- changelogs/unreleased/gh-10391-forbid-non-integers-datetime-new.md
- changelogs/unreleased/gh-10391-forbid-non-integers-datetime-set.md
- changelogs/unreleased/gh-10391-forbid-non-integers-sql-datetime.md
- src/lib/core/datetime.c
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
- test/sql-luatest/datetime_test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/10488
> [Backport 2.11]  Forbid non-integers in datetime.new, :set() and parse()

- changelogs/unreleased/gh-10391-forbid-non-integers-datetime-new.md
- changelogs/unreleased/gh-10391-forbid-non-integers-datetime-set.md
- changelogs/unreleased/gh-10391-forbid-non-integers-sql-datetime.md
- src/lib/core/datetime.c
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
- test/sql-luatest/datetime_test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/10488
> [Backport 3.2] Forbid non-integers in datetime.new, :set() and parse()

- changelogs/unreleased/gh-10420-introduce-tz-option-in-parse.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
> datetime: introduce tz in datetime.parse()

- changelogs/unreleased/gh-8333-fix-ignoring-tzoffset-in-parse.md
- src/box/sql/mem.c
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- src/lua/datetime.lua
- src/lua/tnt_datetime.c
- test/app-tap/datetime.test.lua
- test/fuzz/datetime_parse_full_fuzzer.c
- test/unit/datetime.c
Orig PR: https://github.com/tarantool/tarantool/pull/8412
>  [Backport 2.11] datetime: use tzoffset in datetime.parse{format}

- changelogs/unreleased/gh-8333-fix-ignoring-tzoffset-in-parse.md
- src/box/sql/mem.c
- src/lib/core/datetime.c
- src/lib/core/datetime.h
- src/lua/datetime.lua
- src/lua/tnt_datetime.c
- test/app-tap/datetime.test.lua
- test/fuzz/datetime_parse_full_fuzzer.c
- test/unit/datetime.c
Orig PR: https://github.com/tarantool/tarantool/pull/8412
> [Backport 3.2] datetime: use tzoffset in datetime.parse{format}

- src/box/index.h
As we are going to add more members to `struct memcs_index_read_view_iterator` in EE.
Required for EE PR https://github.com/tarantool/tarantool-ee/pull/917
> box: increase INDEX_READ_VIEW_ITERATOR_SIZE

- changelogs/unreleased/gh-10420-introduce-tz-option-in-parse.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/10526
----
There is an option tz in `datetime.parse()`, it was added in commit 3c40366172e3 ("datetime, lua: date parsing functions"). The option is not documented, and the commit message says that option `tz` is "Not yet implemented in this commit.".
The patch added tests and a doc request for this option. The behaviour of the option `tz` is the same as with option `tzoffset`:
- if timezone was not set in a parsed string then it is set to a value specified by `tz`
- if timezone was set in a parsed string then option `tz` is ignored
```
tarantool> date.parse("1970-01-01T01:00:00 MSK", { tz = 'Europe/Paris' })
---
- 1970-01-01T01:00:00 MSK
- 23
...
tarantool> date.parse("1970-01-01T01:00:00", { tz = 'Europe/Paris' })
---
- …
```
> [Backport 3.2] datetime: introduce tz in datetime.parse()

- changelogs/unreleased/gh-10420-introduce-tz-option-in-parse.md
- src/lua/datetime.lua
- test/app-tap/datetime.test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/10526
----
There is an option tz in `datetime.parse()`, it was added in commit 3c40366172e3 ("datetime, lua: date parsing functions"). The option is not documented, and the commit message says that option `tz` is "Not yet implemented in this commit.".
The patch added tests and a doc request for this option. The behaviour of the option `tz` is the same as with option `tzoffset`:
- if timezone was not set in a parsed string then it is set to a value specified by `tz`
- if timezone was set in a parsed string then option `tz` is ignored
```
tarantool> date.parse("1970-01-01T01:00:00 MSK", { tz = 'Europe/Paris' })
---
- 1970-01-01T01:00:00 MSK
- 23
...
tarantool> date.parse("1970-01-01T01:00:00", { tz = 'Europe/Paris' })
---
- …
```
> [Backport 2.11] datetime: introduce tz in datetime.parse()

- src/box/box.cc
- src/box/call.c
- src/box/call.h
- src/box/lua/call.c
- src/lib/core/assoc.h
- test/box-luatest/gh_10306_lua_call_runtime_access_test.lua
This patch adds internal API methods for granting and revoking Lua function access.
New internal API methods:
-  `box.internal.lua_call_runtime_priv_grant(<user-name>, <function-name>)` grants access to the specified function for the specified user.
-  `box.internal.lua_call_runtime_priv_grant(<user-name>, '')` grants universal access (excluding built-in functions) for the specified user.
- `box.internal.lua_call_runtime_priv_reset()` revokes all previously granted function execution permissions for all users.
Closes https://github.com/tarantool/tarantool/issues/10306
Part of https://github.com/tarantool/tarantool/issues/10310
> box: add runtime lua_call privileges

- changelogs/unreleased/gh-10558-fix-vinyl-cache-corruption-on-skipping-unconfirmed-tuple.md
- src/box/vy_point_lookup.c
- src/box/vy_read_iterator.c
- test/vinyl-luatest/gh_10558_iterator_restore_after_unconfirmed_tuple_test.lua
The tuple cache doesn't store historical data. It stores only the newest tuple versions, including prepared but not yet confirmed (committed but not written to WAL) tuples. This means that transactions sent to a read view shouldn't add any new chains to the cache because such a chain may bypass a tuple invisible from the read view.
A transaction may be sent to a read view in two cases:
1. If some other transactions updates data read by it.
2. If the transaction is operating in the 'read-confirmed' isolation mode and skips an unconfirmed tuple while scanning the memory level. This was added in commit 588170a77c9a ("vinyl: implement transaction isolation levels").
The second point should be checked by the read iterator itself, and it is indeed for the standard case when we scan the memory …
> vinyl: fix cache corruption on skipping unconfirmed tuple

- changelogs/unreleased/gh-10553-check-fiber-slice-in-vinyl-index-count.md
- src/box/index.cc
- test/vinyl-luatest/gh_10553_index_count_fiber_slice_test.lua
`index.count()` may hang for too long in Vinyl if a substantial consecutive hunk of the space is stored in memory. Let's add a fiber slice check to it to prevent it from blocking the TX thread for too long.
Closes #10553
> box: check fiber slice in generic implementation of index count

- changelogs/unreleased/libcurl-doc-option-fix.md
- cmake/BuildLibCURL.cmake
Curl option BUILD_MISC_DOCS set OFF
Curl option BUILD_MISC_DOCS builds misc man pages and set ON by default.
Other documentation building options such as ENABLE_CURL_MANUAL and
BUILD_LIBCURL_DOCS was set OFF in BuildLibCurl.cmake.
I suppose this option has to be added in commit https://github.com/tarantool/tarantool/commit/7192bf66791748a4d399322378d23b1abfa477aa
("third_party: update libcurl from 8.7.0 to 8.8.0+patches") and set OFF.
Follows up https://github.com/tarantool/tarantool/pull/9885
> build: curl option BUILD_MISC_DOCS turned OFF.

- changelogs/unreleased/libcurl-doc-option-fix.md
- cmake/BuildLibCURL.cmake
*(This is a backport of PR #10597 to `release/3.2`, a future `3.2.1` release.)*
----
Curl option BUILD_MISC_DOCS builds misc man pages and set ON by default. Other documentation building options such as ENABLE_CURL_MANUAL and BUILD_LIBCURL_DOCS was set OFF in BuildLibCurl.cmake. I suppose this option has to be added in commit 7192bf667917 ("third_party: update libcurl from 8.7.0 to 8.8.0+patches") and set OFF.
Follows up #9885
> [backport 3.2] build: curl option BUILD_MISC_DOCS set OFF

- changelogs/unreleased/libcurl-doc-option-fix.md
- cmake/BuildLibCURL.cmake
*(This is a backport of PR #10597 to `release/2.11`, a future `2.11.5` release.)*
----
Curl option BUILD_MISC_DOCS builds misc man pages and set ON by default. Other documentation building options such as ENABLE_CURL_MANUAL and BUILD_LIBCURL_DOCS was set OFF in BuildLibCurl.cmake. I suppose this option has to be added in commit 7192bf667917 ("third_party: update libcurl from 8.7.0 to 8.8.0+patches") and set OFF.
Follows up #9885
> [backport 2.11] build: curl option BUILD_MISC_DOCS set OFF

- changelogs/unreleased/gh-10603-fix-vinyl-pk-alter-crash.md
- src/box/vinyl.c
- test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua
Vinyl doesn't support altering the primary index of a non-empty space, but the check forbidding this isn't entirely reliable - the DDL function may yield to wait for pending WAL writes to finish after ensuring that the space doesn't contain any tuples. If a new tuples is inserted into the space in the meantime, the DDL operation will proceed rebuilding the primary index and trigger a crash because the code is written on the assumption that it's rebuilding a secondary index:
```
./src/box/vinyl.c:1572: vy_check_is_unique_secondary_one: Assertion `lsm->index_id > 0' failed.
```
Let's fix this by moving the check after syncing on WAL.
Closes #10603
> vinyl: fix crash when empty PK DDL races with DML

- changelogs/unreleased/gh-10286-faster-connpool-filter.md
- src/box/lua/connpool.lua
- test/config-luatest/rpc_test.lua
Connpool `filter()` method used to be executed synchroniously in a single fiber. Thus the maximum evaluation time was `number of instances * timeout`. Make its execution parallel limiting the evaluation time with `timeout`.
Closes #10286
> connpool: make checking connections parallel

- test/config-luatest/cluster.lua
The cluster helper in `test/config-luatest/cluster.lua` is used to define the clusters in an easy way. Though every time the `cluster.new` is called it creates a new temporary directory, which is not good when you're writing a test setting up the directory before the cluster start.
This patch adds an `opts` object as the fourth parameter for `cluster.new` and makes the function use `opts.dir` as a key for specifying the directory to start the cluster.
Example:
```lua
local dir = '/some/long/dir'
local cluster_config = cbuilder:new(remote_config)
:use_replicaset('r-001')
:add_instance('i-001', {})
:config()
-- The cluster will be started in a new temp directory.
local cluster = cluster.new(g, cluster_config)
-- The cluster will be started in '/some/long/dir'.
local cluster = cluster.new(g, …
```
> test: specify the dir in the cluster helper

- .github/workflows/publish-module-api-doc.yaml
The `ubuntu-latest` image is now `ubuntu-24.04`, see https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/. The job fails on this image with the following error:
```
CMake Error at /usr/local/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
```
It seems, the libreadline-dev package is missing. Let's install it.
Also, update a version of the publishing action to the latest at the moment. I didn't perform any check, but I guess that a new version of NodeJS is needed and the latest action version has better support of it.
> ci: fix module API build/publish job

- .github/workflows/publish-module-api-doc.yaml
The new version of the publishing action leads to the following error:
```
Error: File not found: '/home/runner/work/_actions/JamesIves/github-pages-deploy-action/v4.6.6/lib/main.js'
```
Let's revert it to v4.6.4 (because v4.6.5 change was reverted in v4.6.6).
See also JamesIves/github-pages-deploy-action#1697
> ci: fix module API publish job (again)

- .github/workflows/publish-module-api-doc.yaml
*(This is a backport of PR #10624 and PR #10625 to `release/3.2`.)*
The second commit fixes the publication step, which is performed only on the `master` branch. In fact, it is not necessary, but left here to minimize a difference in workflows with `master`.
----
The `ubuntu-latest` image is now `ubuntu-24.04`, see https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/. The job fails on this image with the following error:
```
CMake Error at /usr/local/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
```
It seems, the libreadline-dev package is missing. Let's install it.
Also, update a version of the publishing action to `v4.6.4`. I guess that a new version …
> [backport 3.2] ci: fix module API build/publish job

- .github/workflows/publish-module-api-doc.yaml
*(This is a backport of PR #10624 and PR #10625 to `release/2.11`.)*
The second commit fixes the publication step, which is performed only on the `master` branch. In fact, it is not necessary, but left here to minimize a difference in workflows with `master`.
----
The `ubuntu-latest` image is now `ubuntu-24.04`, see https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/. The job fails on this image with the following error:
```
CMake Error at /usr/local/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
```
It seems, the libreadline-dev package is missing. Let's install it.
Also, update a version of the publishing action to `v4.6.4`. I guess that a new version …
> [backport 2.11] ci: fix module API build/publish job

- test/replication/replica_apply_order.result
- test/replication/replica_apply_order.test.lua
Since commit e19bca5a74e8 ("box: check fiber slice in generic implementation of index count"), Vinyl's version of `index.count()` checks the fiber slice. As a result, the test may fail if it runs under a heavy load:
```
| @@ -94,6 +94,7 @@
|      end
|  end;
|   | ---
| + | - error: fiber slice is exceeded
|   | ...
|  -- Verify that at any moment max index is corresponding to amount of tuples,
|  -- which means that changes apply order is correct
```
Let's set the max fiber slice to a big value to avoid that.
> test: disable fiber slice check in replica_apply_order test

- cmake/BuildNanoarrow.cmake
Currently, in case of in-source build, the nanoarrow library is compiled in `<tarantool_git>/third_party/nanoarrow/`, although it is better to compile it in `<tarantool_git>/build/nanoarrow/`, because the `build` directory is ignored by `.gitignore`.
Follow-up #10508
> third_party: fix `nanoarrow` install directory

- test/replication-luatest/gh_9918_synchro_queue_additional_info_test.lua
This patch eliminates flaking in the `gh_9918_synchro_queue_additional_info_test.lua` test. The problem was that the test did not wait for the connection between master and replica to be established, and therefore master node was in the "orphan" state at the time `box.ctl.promote()` was called. Thus, it turned out that the master node became the owner of the limbo, but was still read only.
Closes #10463
> test: fix flaky gh_9918_synchro_queue_additional_info_test.lua

- test/replication-luatest/gh_9918_synchro_queue_additional_info_test.lua
This patch eliminates flaking in the
`gh_9918_synchro_queue_additional_info_test.lua` test. The problem was that the test did not wait for the connection between master and replica to be established, and therefore master node was in the "orphan" state at the time `box.ctl.promote()` was called. Thus, it turned out that the master node became the owner of the limbo, but was still read only.
To fix this, this patch simply calls `cg.replica_set:wait_for_fullmesh()` on the previous line before `box.ctl.promote()`.
Closes #10463
(cherry picked from commit 37bf64b7d7f76ea3330909655da90d64d0add558)
> [backport 3.2] test: fix flaky gh_9918_synchro_queue_additional_info_test.lua

- changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md
- src/lua/trigger.c
- test/box-luatest/gh_10622_net_box_trigger_crash_on_self_delete_test.lua
In https://github.com/tarantool/tarantool/commit/6d882740f3e56b62527fb9a606b748a138090014 we rewrote Lua module `internal.trigger` that is used in
`net.box` and possibly some external modules. Old implementation held
all triggers in a Lua table, so deleting a trigger on the fly wasn't a
problem. Now we store all triggers in a list and simply iterate over it
when the triggers are fired, so the trigger list became non-resistent to
modifications on the fly. In order to fix it, let's simply use
`trigger_run` - it is resistant to the list modifications.
Closes #10622
> net_box: fix a crash when a trigger deletes itself

- src/box/memtx_tx.c
According to the C standard, passing `NULL` to `memcpy` is UB, even if it copies nothing (number of bytes to copy is 0). The commit fixes such situation in memtx MVCC.
**NB**: This problem is [already fixed](https://github.com/tarantool/tarantool/blob/37bf64b7d7f76ea3330909655da90d64d0add558/src/box/memtx_tx.c#L3343) in `master`, so the PR is going to be merged into `release/3.2`. Also, it should be cherry-picked to `2.11`.
Closes tarantool/security#129
> memtx: do not pass NULL to memcpy when creating gap item in MVCC

- src/httpc.c
There is no check for NULL for a value returned by `ibuf_alloc`, the NULL will be passed to `memcpy()` if the aforementioned function will return a NULL. The patch fixes that by replacing `ibuf_alloc` with macros `xibuf_alloc` that never return NULL.
Found by Svace.
NO_TEST=codehealth
> httpc: replace ibuf_alloc with xibuf_alloc

- src/httpc.c
Orig PR: https://github.com/tarantool/tarantool/pull/10654
> [Backport 3.2] httpc: replace ibuf_alloc with xibuf_alloc

- src/httpc.c
Orig PR: https://github.com/tarantool/tarantool/pull/10654
> [Backport 2.11] httpc: replace ibuf_alloc with xibuf_alloc

- src/box/alter.cc
- src/box/index_def.c
- src/box/index_def.h
- src/box/key_def.c
- src/box/schema.cc
- src/box/sql.c
- src/box/sql/build.c
- src/box/sql/where.c
Function `index_def_new` can fail only due to failure of identifier
validation and due to failure of `key_def_merge` helper. The helper
`key_def_merge` can fail only because of OOM or if multikey validation
has failed.
Firstly, we never need to check identifier in `index_def_new` because we
always do it earlier actually (except for cases we use string literals
for internal indexes, but we don't need to check them anyway), so let's
remove this check. Secondly, `key_def_merge` cannot fail because of
multikey validation in `index_def_new` because the secondary index is
already validated and primary index cannot have multikey path at all.
So here it can fail only because of allocation failure - let's simply
make `key_def_merge` panic on OOM so that `index_def_new` will become
non-failing. …
> index_def: make index_def_new non-failing

- test/unit/bps_tree_iterator.cc
- test/unit/bps_tree_view.c
On COW matras make a copy of extent while API requires only copy a block. So bps tree may miss COW requests for its block but the block is copied accidentally and the test passes. To avoid this issue let's make extent and block the same size.
The same improvement we done for bps vector in https://github.com/tarantool/tarantool-ee/pull/932.
> bps: improve tree view tests

- src/box/box.cc
Currently, we just panic without providing any additional information if we failed to create the initial checkpoint on bootstrap. This complicates trouble shooting. Let's replace `panic()` with `say_error()` and raise the exception that caused the failure. The exception will be caught by by `box_cfg()`, which will log it and then panic.
> box: log error that caused initial checkpoint failure

- changelogs/unreleased/gh-10546-schema-version-broadcast.md
- src/box/alter.cc
- src/box/box.cc
- src/box/box.h
- test/box-luatest/builtin_events_test.lua
- test/box-luatest/upgrade_to_3_0_0_test.lua
https://github.com/tarantool/tarantool/issues/10520 will allow DDL before schema is upgraded
in order to simplify the upgrade process. However, some DDL will
remain forbidden until box.schema.upgrade is called, e.g. creating
persistent triggers when upgrading to 3.0.0.
In order to make writing upgrade triggers easier this commit adds
new field to the box.status system event: dd_version. This should
not be confused with schema.version value, as the latter shows, whether
the database schema (e.g. creating space) was updated.
box.status.dd_version on the other side is the value of the
persistent schema from box.space._schema['version'].
Without box.status.dd_version user has to set on_replace trigger for
box.space._schema, which will check version and rw state, after which
trigger will send …
> schema: broadcast persistent schema version in box.status

- test/app-tap/datetime.test.lua
The testsuite "Datetime string parsing by format (detailed)" tests parsing of a string with various conversion specifications. However, `tostring(dt)` is used as a test oracle and all these testcases does not test some conversion specifications at all, because metamethod `__tostring` for datetime object uses `:format()` with default format string.
Due to missed tests for conversion specifications behavior described in #10470 was missed:
```
tarantool> dt = date.parse('Mon', {format = '%a'})
tarantool> dt
---
...
tarantool> dt:format('%a')
---
- Thu
...
```
The patch adds tests for `strptime` with all possible conversion specifications described in strftime(3).
Follows up #8588
Relates to #10470
NO_DOC=testing
> datetime: add additional tests for a strptime()

- cmake/luajit.cmake
This patch enables `LUAJIT_USE_SYSMALLOC` in ASAN build when also GC64 mode is enabled (to avoid allocator and pointer bitness incompatibility).
Closes https://github.com/tarantool/tarantool/issues/10550
Follows up https://github.com/tarantool/tarantool/issues/3071
> cmake: turn on sysmalloc with ASAN build

- test/app-tap/datetime.test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/10499
-----
The testsuite "Datetime string parsing by format (detailed)" tests parsing of a string with various conversion specifications. However, `tostring(dt)` is used as a test oracle, and all these testcases do not test some conversion specifications at all because the metamethod `__tostring` for the datetime object uses `:format()` with the default format string.
Due to missed tests for conversion specifications, the behavior described in #10470 was missed:
```
tarantool> dt = date.parse('Mon', {format = '%a'})
tarantool> dt
---
...
tarantool> dt:format('%a')
---
- Thu
...
```
The patch adds tests for `strptime` with all possible conversion specifications described in strftime(3) [1][2].
1. …
> [Backport 3.2] test: add additional tests for a strptime()

- test/app-tap/datetime.test.lua
Orig PR: https://github.com/tarantool/tarantool/pull/10499
-----
The testsuite "Datetime string parsing by format (detailed)" tests parsing of a string with various conversion specifications. However, `tostring(dt)` is used as a test oracle, and all these testcases do not test some conversion specifications at all because the metamethod `__tostring` for the datetime object uses `:format()` with the default format string.
Due to missed tests for conversion specifications, the behavior described in #10470 was missed:
```
tarantool> dt = date.parse('Mon', {format = '%a'})
tarantool> dt
---
...
tarantool> dt:format('%a')
---
- Thu
...
```
The patch adds tests for `strptime` with all possible conversion specifications described in strftime(3) [1][2].
1. …
> [Backport 2.11] test: add additional tests for a strptime()

- .github/workflows/coverity.yml
- .test.mk
*(This is a backport of PR #10673 to `release/2.11`. In fact, the triggered workflow resides in the default branch, but I don't want to leave some dead code in the release branches. Let's make it consistent.)*
----
It doesn't work since 2023-11-18. The uploading succeeds, but the website says:
> The Coverity Build tool version is no longer supported. Please
> download the latest version for your platform from
> https://scan.coverity.com/download...
It seems, some specific toolset is installed in the `tarantool/testing:debian-buster` image and it was deprecated 11 months ago.
Recently the CI workflow starts to fail due to use of the old image with an old CMake in it:
> [  2%] Performing configure step for 'bundled-nanoarrow-project'
> -- Building using CMake version: 3.13.4
> -- …
> [backport 2.11] ci: fix Coverity workflow

- changelogs/unreleased/config-schema-improve-unexpected-array-message.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/schema_test.lua
How it looks for a map:
```lua
local schema = require('experimental.config.utils.schema')
local s = schema.new('foo', schema.map({
key = schema.scalar({type = 'string'}),
value = schema.scalar({type = 'string'}),
}))
s:validate({'a', 'b', 'c'})
-- Before the patch:
-- [foo] [1]: Unexpected data for scalar "string": Expected "string", got "number"
-- Now:
-- [foo] Expected a map, got an array: ["a","b","c"]
```
How it looks for a record:
```lua
local schema = require('experimental.config.utils.schema')
local s = schema.new('foo', schema.record({
foo = schema.scalar({type = 'string'}),
}))
s:validate({'a', 'b', 'c'})
-- Before the patch:
-- [foo] Unexpected field "1"
-- Now:
-- [foo] Expected a record, got an array: ["a","b","c"]
```
The tricky part of the patch is to determine that the …
> config/schema: improve unexpected array error

- src/box/applier.cc
- src/box/iproto.cc
- src/box/relay.cc
- src/box/replication.cc
- src/trivia/util.h
**Revert "hotfix: change aligned_alloc to posix_memalign"**
This reverts commit https://github.com/tarantool/tarantool/commit/3c25c667352ec4f9c733c514a1b8c15264c6ad88.
`aligned_alloc()` is supported by macOS since 10.15. I believe that we do not support older versions now.
**box: fix `SIGSEGV` on unaligned access to a struct with extended alignment**
All structures with a non-default alignment (set by `alignas()`) must be allocated by `aligned_alloc()`, otherwise an access to such a structure member fill crash, e.g. if compiled with AVX-512 support.
Closes https://github.com/tarantool/tarantool/issues/10215
Part of https://github.com/tarantool/tarantool/issues/10631
> box: fix `SIGSEGV` on unaligned access to a struct with extended alignment

- src/box/field_map.c
The type cast is unnecessary and causes false-positive errors:
```
./src/box/field_map.c:110:10: runtime error: store to misaligned address 0x507000071082 for type 'uint32_t *' (aka 'unsigned int *'), which requires 4 byte alignment
0x507000071082: note: pointer points here
01 00  00 00 be be be be f0 ff  ff ff 02 00 00 00 be be  be be be be be be 00 00  00 00 00 00 00 00
^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ./src/box/field_map.c:110:10
```
Closes https://github.com/tarantool/tarantool/issues/10631
> box: fix UBSan error regarding misaligned store in `field_map.c`

- changelogs/unreleased/bump-libcurl-to-8.10.1.md
- cmake/BuildLibCURL.cmake
The reason is that the previous libcurl submodule update in commit 0919f390802f146852b462215327ef03e2730cfc ("third_party: update libcurl from 8.8.0 to 8.10.1") reveals the following regression:
```c
$ tarantool -e "require('http.client').new():get('https://google.com')"
tarantool: ./third_party/curl/lib/multi.c:3691: curl_multi_assign: Assertion `!(multi)' failed.
Aborted (core dumped)
```
The stacktrace is the following:
```c
<...>
#4  __assert_fail
#5  curl_multi_assign            // <- called by us
#6  curl_multi_sock_cb           // <- this is our callback
#7  Curl_multi_pollset_ev
#8  cpool_update_shutdown_ev
#9  cpool_discard_conn
#10 cpool_close_and_destroy_all
#11 Curl_cpool_destroy
#12 curl_multi_cleanup
#13 curl_env_finish              // <- destroy the multi handle
#14 …
```
> build: update libcurl to curl-8_10_1-241-g461ce6c61

- src/box/lua/config/configdata.lua
No functional changes, just a little refactoring.
These two commits adjust the configdata code to reuse a few values, which are already calculated, instead of acquiring them once again.
> config: refactor to reuse already calculated values in configdata

- changelogs/unreleased/bump-libcurl-to-8.10.1.md
- cmake/BuildLibCURL.cmake
*(This is a backport of PR #10681 to `release/3.2`.)*
----
The reason is that the previous libcurl submodule update in commit 0919f390802f146852b462215327ef03e2730cfc ("third_party: update libcurl from 8.8.0 to 8.10.1") reveals the following regression:
```c
$ tarantool -e "require('http.client').new():get('https://google.com')"
tarantool: ./third_party/curl/lib/multi.c:3691: curl_multi_assign: Assertion `!(multi)' failed.
Aborted (core dumped)
```
The stacktrace is the following:
```c
<...>
#4  __assert_fail
#5  curl_multi_assign            // <- called by us
#6  curl_multi_sock_cb           // <- this is our callback
#7  Curl_multi_pollset_ev
#8  cpool_update_shutdown_ev
#9  cpool_discard_conn
#10 cpool_close_and_destroy_all
#11 Curl_cpool_destroy
#12 curl_multi_cleanup
#13 …
```
> [backport 3.2] build: update libcurl to curl-8_10_1-241-g461ce6c61

- changelogs/unreleased/bump-libcurl-to-8.10.1.md
- cmake/BuildLibCURL.cmake
*(This is a backport of PR #10681 to `release/2.11`.)*
----
The reason is that the previous libcurl submodule update in commit 0919f390802f146852b462215327ef03e2730cfc ("third_party: update libcurl from 8.8.0 to 8.10.1") reveals the following regression:
```c
$ tarantool -e "require('http.client').new():get('https://google.com')"
tarantool: ./third_party/curl/lib/multi.c:3691: curl_multi_assign: Assertion `!(multi)' failed.
Aborted (core dumped)
```
The stacktrace is the following:
```c
<...>
#4  __assert_fail
#5  curl_multi_assign            // <- called by us
#6  curl_multi_sock_cb           // <- this is our callback
#7  Curl_multi_pollset_ev
#8  cpool_update_shutdown_ev
#9  cpool_discard_conn
#10 cpool_close_and_destroy_all
#11 Curl_cpool_destroy
#12 curl_multi_cleanup
#13 …
```
> [backport 2.11] build: update libcurl to curl-8_10_1-241-g461ce6c61

- src/box/lua/config/configdata.lua
*(This is a backport of PR #10683 to `release/3.2`.)*
----
No functional changes, just a little refactoring.
These two commits adjust the configdata code to reuse a few values, which are already calculated, instead of acquiring them once again.
> [backport 3.2]  config: refactor to reuse already calculated values in configdata

- src/lib/core/say.c
If `opts.identity` is `NULL` and `strdup()` is failed we do `NULL` pointer dereference when reporting the error. Let's just panic if `strdup()` failed. While at it replace another `strdup()` with `xstrdup()` in this function. Our current approach is to panic on runtime OOM.
Closes tarantool/security#128
> say: fix NULL pointer dereference in log_syslog_init

- src/box/applier.cc
All structures with a non-default alignment (set by `alignas()`) must be allocated by `aligned_alloc()`, otherwise an access to such a structure member fill crash, e.g. if compiled with AVX-512 support.
See also commit a60ec82d4f07 ("box: fix SIGSEGV on unaligned access to a struct with extended alignment").
Closes #10699
> box: fix `SIGSEGV` on unaligned access to `struct applier`

- changelogs/unreleased/gh-10199-luajit-fixes.md
* Fix typo.
* OSX/iOS: Always generate 64 bit non-FAT Mach-O object files.
* test: don't run JIT-based LuaJIT tests without JIT
* test: actualize <LuaJIT-tests/README.md>
* test: enable <misc/alias_alloc.lua> LuaJIT test
* test: refactor <alias_alloc.lua> LuaJIT test
* test: refactor <lang/coroutine.lua> LuaJIT test
* test: remove <misc/coro_yield.lua> LuaJIT test
* test: enable <misc/debug_gc.lua> LuaJIT test
* test: enable <misc/dualnum.lua> LuaJIT test
* test: refactor <lang/dualnum.lua> LuaJIT test
* test: remove <misc/fori_coerce.lua> LuaJIT test
* test: remove <misc/fori_dir.lua> LuaJIT test
* test: remove <misc/gc_rechain.lua> LuaJIT test
* test: enable <misc/gc_trace.lua> LuaJIT test
* test: refactor <trace/gc.lua> LuaJIT test
* test: enable <misc/gcstep.lua> LuaJIT test
* test: …
>  [backport/release/3.2] luajit: bump new version

- changelogs/unreleased/gh-10199-luajit-fixes.md
* Fix typo.
* OSX/iOS: Always generate 64 bit non-FAT Mach-O object files.
* test: don't run JIT-based LuaJIT tests without JIT
* test: actualize <LuaJIT-tests/README.md>
* test: enable <misc/alias_alloc.lua> LuaJIT test
* test: refactor <alias_alloc.lua> LuaJIT test
* test: refactor <lang/coroutine.lua> LuaJIT test
* test: remove <misc/coro_yield.lua> LuaJIT test
* test: enable <misc/debug_gc.lua> LuaJIT test
* test: enable <misc/dualnum.lua> LuaJIT test
* test: refactor <lang/dualnum.lua> LuaJIT test
* test: remove <misc/fori_coerce.lua> LuaJIT test
* test: remove <misc/fori_dir.lua> LuaJIT test
* test: remove <misc/gc_rechain.lua> LuaJIT test
* test: enable <misc/gc_trace.lua> LuaJIT test
* test: refactor <trace/gc.lua> LuaJIT test
* test: enable <misc/gcstep.lua> LuaJIT test
* test: …
>  [backport/release/2.11] luajit: bump new version

- changelogs/unreleased/gh-9735-fix-space-bsize-return-type.md
- src/box/lua/schema.lua
- test/box/space_bsize.result
- test/box/space_bsize.test.lua
To be consistent with other similar methods, e.g. `index:bsize()`.
Closes #9735
> box/lua: change `space:bsize()` return type from `cdata` to `number`

- src/box/box.cc
- src/box/box.h
- src/box/lua/slab.cc
- src/symbols.c
- test/app-luatest/tnt_internal_symbol_test.lua
Added the new C function `box_slab_info` that returns information about the memory state depending on the passed argument `box_slab_info_type`. The same information is available in Lua via `box.slab.info()`.
Backported to 3.2.1 in the sake of TCS, which uses that function to get information about the memory state during automatic selection of the columns to delete when tarantool's memory runs out.
Co-authored-by: SEChudinov <s.chudinov@vkteam.ru>
> [backport] box: export box_slab_info via C API

- src/box/tuple_hash.cc
I got compile error for release build on gcc 14.2.1 20240910 version.
```
In function ‘char* mp_store_double(char*, double)’,
inlined from ‘char* mp_encode_double(char*, double)’ at /home/shiny/dev/tarantool-ee/tarantool/src/lib/msgpuck/msgpuck.h:2409:24,
inlined from ‘uint32_t tuple_hash_field(uint32_t*, uint32_t*, const char**, field_type, coll*)’ at /home/shiny/dev/tarantool-ee/tarantool/src/box/tuple_hash.cc:317:46:
/home/shiny/dev/tarantool-ee/tarantool/src/lib/msgpuck/msgpuck.h:340:16: error: ‘value’ may be used uninitialized [-Werror=maybe-uninitialized]
340 |         cast.d = val;
|         ~~~~~~~^~~~~
/home/shiny/dev/tarantool-ee/tarantool/src/box/tuple_hash.cc: In function ‘uint32_t tuple_hash_field(uint32_t*, uint32_t*, const char**, field_type, coll*)’: …
```
> box: build fix

- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
Currently, we create `memtx_tx_snapshot_cleaner` for each index in read view. However, we somewhy clarify all tuples against primary index in all cleaners. As a result, secondary indexes work incorrectly in read view when MVCC is enabled, we may even get a tuple with one key, but a tuple with another key will be returned because it is clarified against primary index and repsects its order - that's wrong because all indexes have its own orders.
Community Edition is not affected at all since it uses read view only for making a snapshot - we use only primary indexes there.
Part of https://github.com/tarantool/tarantool-ee/issues/939
EE part: https://github.com/tarantool/tarantool-ee/pull/948
> memtx: clarify tuples against given index in memtx_tx_snapshot_cleaner

- src/box/lua/tuple_format.c
- test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua
Even though `box.internal.tuple_format.new()` is an internal function, it is quite easy to call it from the console using auto completion and to crash Tarantool. Let's replace the assertion with an error.
Closes #10529
> box/lua: don't crash on `box.internal.tuple_format.new()` misuse

- changelogs/unreleased/gh-10716-config-scaling-down.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/downscaling_test.lua
Before this patch there was a mistake in the YAML configuration processing, when an instance removal is not taken into account in generation of a list of upstreams. It occurs when the updated YAML configuration has only one instance in the given replicaset.
Fixes #10716
> config: fix scaling a replicaset down to one node

- src/box/lua/tuple_format.c
- test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua
Even though `box.internal.tuple_format.new()` is an internal function, it is quite easy to call it from the console using auto completion and to crash Tarantool. Let's replace the assertion with an error.
Closes #10529
NO_DOC=bugfix
(cherry picked from commit 3831f9d1a75dd98d11027e8ac47bc0229966bc7d)
This is a backport of https://github.com/tarantool/tarantool/pull/10705
> [backport 3.2] box/lua: don't crash on box.internal.tuple_format.new() misuse

- changelogs/unreleased/gh-10716-config-scaling-down.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/downscaling_test.lua
*(This is a backport of PR #10718 to `release/3.2`. Planned to `3.2.1` release.)*
----
Before this patch there was a mistake in the YAML configuration processing, when an instance removal is not taken into account in generation of a list of upstreams. It occurs when the updated YAML configuration has only one instance in the given replicaset.
Fixes #10716
> [backport 3.2] config: fix scaling a replicaset down to one node

- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
Currently, we create `memtx_tx_snapshot_cleaner` for each index in read view. However, we somewhy clarify all tuples against primary index in all cleaners. As a result, secondary indexes work incorrectly in read view when MVCC is enabled, we may even get a tuple with one key, but a tuple with another key will be returned because it is clarified against primary index and repsects its order - that's wrong because all indexes have its own orders. Let's clarify tuples against given index to fix this mistake.
Community Edition is not affected at all since it uses read view only for making a snapshot - we use only primary indexes there.
Part of tarantool/tarantool-ee#939
EE part: https://github.com/tarantool/tarantool-ee/pull/967
> [backport 2.11] memtx: clarify tuples against given index in memtx_tx_snapshot_cleaner

- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
Currently, we create `memtx_tx_snapshot_cleaner` for each index in read view. However, we somewhy clarify all tuples against primary index in all cleaners. As a result, secondary indexes work incorrectly in read view when MVCC is enabled, we may even get a tuple with one key, but a tuple with another key will be returned because it is clarified against primary index and repsects its order - that's wrong because all indexes have its own orders. Let's clarify tuples against given index to fix this mistake.
Community Edition is not affected at all since it uses read view only for making a snapshot - we use only primary indexes there.
Part of tarantool/tarantool-ee#939
EE part: https://github.com/tarantool/tarantool-ee/pull/966
> [backport 3.2] memtx: clarify tuples against given index in memtx_tx_snapshot_cleaner

- changelogs/unreleased/gh-9913-emit-filename-for-all-log-levels.md
- src/lib/core/say.c
- test/box-luatest/gh_3211_per_module_log_level_test.lua
- test/box-tap/gh-4785-syslog.test.lua
- test/config-luatest/log_test.lua
Currently in `plain` log format the file name and line are printed only for `syserror`, `error` and `warn` log levels.
Let's print them for all log levels. In `json` log format the name and line are already emitted unconditionally.
Closes #9913
> log: emit file name and line for all log levels

- tools/check-entrypoint-tag.sh
To fix [CI failure in EE](https://github.com/tarantool/tarantool-ee/actions/runs/11558881187/job/32172404641) for the related workflow.
(cherry picked from commit 218fc46f5f44e6e27be73c6dceaa58f1eb377f46)
> [backport 3.2] tools: do not require entrypoint in branch

- cmake/compiler.cmake
- src/box/sql/expr.c
- src/box/sql/func.c
- src/box/sql/util.c
- src/lib/core/datetime.c
- src/lib/core/fiber.c
- src/trivia/config.h.cmake
Orig PR: https://github.com/tarantool/tarantool/pull/10702
>  [Backport 2.11] Fix GCC's UBsan and update a list of disabled UBSan checks

- changelogs/unreleased/gh-6403-index-iterator-methods.md
- changelogs/unreleased/gh-6403-luafun-fixes.md
- perf/lua/CMakeLists.txt
- perf/lua/luafun.lua
- test/app/luafun.result
- test/box-luatest/gh_6403_space_pairs_luafun_integration_test.lua
Since our index iterators are stateful (can return different values with the same state passed), old luafun drop_while implementation didn't work well with them - it was skipping an extra element. The PR bumps luafun and resolves this issue.
Closes https://github.com/tarantool/tarantool/issues/6403
> box: fix drop_while integration with index:pairs

- changelogs/unreleased/gh-10606-json-encode-key-order.md
- src/lua/serializer.c
- src/lua/serializer.h
- test/app-tap/json.test.lua
- third_party/lua-cjson/lua_cjson.c
This option allows to pass an array of keys that will be used to sort keys in maps during serialization to json. The order of the provided keys in the resulting string will be the same as in the `encode_key_order` array. Keys, present in maps and not included in `encode_key_order` will be serialized after the sorted ones in arbitrary order.
Closes #10606
> Add `encode_key_order` option to json encoder

- changelogs/unreleased/gh-10777-check-fixed-int-key-in-range.md
- src/box/errcode.h
- src/box/field_def.c
- src/box/field_def.h
- src/box/key_def.h
- src/box/tuple_format.c
- src/box/tuple_format.h
- test/box-luatest/gh_10777_fixed_size_keys_test.lua
- test/box/error.result
Currently `index:get({256})` is valid request for 'uint8' field for example.  It is not on par with error for negative values and for range check for tuples. Let's add range check for fixed integer types for keys too.
While at it let's move and rename `tuple_field_type_is_fixed_int`. Also function for checking range is fixed to fill min and max MsgPack values only on errors. This potential performance issue was introduced in the commit 7410a4f0f291 ("box: add payload info for client error codes").
Follow-up #9548
Closes #10777
> box: validate fixed integer types keys range

- changelogs/unreleased/gh-9929-fix-updates-on-fixed-size-fp-fields.md
- src/box/xrow_update_field.c
- test/engine-luatest/gh_9548_fixed_size_numeric_types_test.lua
Currently for floating-point arithmetic operations the smallest type that can represent the resulting value is chosen (`MP_FLOAT` vs. `MP_DOUBLE`).
This doesn't work for fixed-size field types (`float32` and `float64`) that require the data to be encoded only to the corresponding type.
Closes #9929
Follow-up #9548
> box: fix update operations on the fixed-size floating-point fields

- changelogs/unreleased/config-log-modules-removal.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/log_modules_test.lua
The option was not set to its default value on `config:reload()` (without restarting the instance) if removed from the YAML configuration. This patch works the problem around. The root of the problem will be fixed in #10756.
Fixes #10728
> config: fix handling of log.modules removal

- changelogs/unreleased/config-wal-ext-removal.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/wal_ext_test.lua
The option was not set to its default value on `config:reload()` (without restarting the instance) if removed from the YAML configuration. This patch works the problem around. The root of the problem will be fixed in #10756.
Fixes tarantool/tarantool-ee#963
> config: fix handling of wal.ext removal

- changelogs/unreleased/config-audit-log-spaces-removal.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/audit_log_spaces_test.lua
If the option is removed from the YAML configuration, `config:reload()` should add an alert that a non-dynamic option is changed and it will be applied after a restart. This patch works the problem around. The root of the problem will be fixed in #10756.
Fixes tarantool/tarantool-ee#964
> config: fix handling of audit_log.spaces removal

- changelogs/unreleased/gh-10604-bootstrap-leader-dynamic.md
- src/box/box.cc
- src/box/box.h
- src/box/lua/cfg.cc
- src/box/lua/load_cfg.lua
- src/box/replication.cc
- test/replication-luatest/bootstrap_strategy_test.lua
bootstrap_leader configuration option only takes effect during instance bootstrap. For this reason, the option was made static. One can't change the bootstrap_leader after initial box.cfg() call.
So when a user has bootstrap_strategy = 'config' and joins new nodes during replicaset lifespan, he ends up with instances having different `bootstrap_leader` configuration, depending on which node was writable at the moment of each instance bootstrap.
It would be better to have matching configuration on each replica set member with no exceptions and to be able to set bootstrap_leader to the same value on all the instances of the replica set, even on the ones which are already bootstrapped.
Let's allow changing `bootstrap_leader` option even though it affects nothing.
While we're at it, fix a …
> [backport 3.2] box: make bootstrap_leader cfg option dynamic

- src/box/lua/iproto.c
- test/box-luatest/iproto_drop_connections_test.lua
This low-level API is needed to prevent execution of user's requests over iproto, when an instance is marked as disabled/isolated. See details about this mode in #10796.
Part of #10796
> iproto: add Lua API to drop connections (internal)

- src/box/lua/config/configdata.lua
- test/config-luatest/isolated_mode_test.lua
In the isolated mode an instance refuses to fetch any data from other replicaset members. An attempt to bootstrap a database on such an instance would produce its own database (for example, it assigns its own replicaset UUID).
Unlikely a user wants to place two instances into the same replicaset in the configuration and get two different databases.
Part of #10796
> config: don't bootstrap database in isolated mode

- src/box/lua/call.c
- src/box/lua/call.h
- src/symbols.c
- test/app-luatest/tnt_internal_symbol_test.lua
In some cases, one might want to access a deeply nested Lua function from C, which is exactly the functionality implemented by the `box_lua_find`. Since the function in question is quite complex to re-implement, it is beneficial to expose it for internal use.
> box: expose box_lua_find via tnt_internal_symbol

- perf/bps_tree.cc
- perf/light.cc
- src/box/memtx_bitset.cc
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_space.c
- src/box/memtx_tree.cc
- src/box/sequence.c
- src/box/vy_cache.c
- src/box/vy_cache.h
- src/box/vy_mem.c
- src/box/vy_mem.h
- src/lib/salad/bps_tree.h
- src/lib/salad/light.h
- src/lib/salad/rtree.c
- src/lib/salad/rtree.h
- test/box/errinj_index.result
- test/box/errinj_index.test.lua
- test/unit/bps_tree.cc
- test/unit/bps_tree_iterator.cc
- test/unit/bps_tree_offset_api.cc
- test/unit/bps_tree_view.c
- test/unit/light.cc
- test/unit/light_view.c
- test/unit/rtree.cc
- test/unit/rtree_iterator.cc
- test/unit/rtree_multidim.cc
A long time ago the it's been found that in some circumstances the
RTREE index could fail to rollback because of OOM. This is the case
because removal of a key from such an index can sometimes lead to
allocation of new blocks that could fail. So, in order to guarantee
a successful rollback of an insertion into the index, the memtx
engine extent reservation machinery had been introduced (see the
issue #727).
But some time ago it's beed found out that the reservation of memory
prior to insertion can be not enough to guarantee a successful roll
back of the statements, so it's been decided to use a regular malloc
for failed allocations performed during rollback (see #10551). This
also fixed the RTREE issue for which the extent reservation had been
introduced in the first place.
But this …
> memtx: use the matras's new reservation machinery

- src/box/lua/schema.lua
- test/box-luatest/gh_8204_fast_offset_test.lua
The function assumes the given key is a Lua table and the given opts is not nil. Let's fix that.
Closes #10827
> schema: fix the index:offset_of parameter handling

- src/box/lua/config/configdata.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/config_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patch adds the support for `failover.replicasets.<replicaset-name>.learners` configuration section and corresponding checks for it.
This option is used to specify the list of instances from the specific replicaset that can't be selected as a master by the supervised failover coordinator.
The supervised coordinator is enterprise-edition feature.
EE issue: tarantool/tarantool-ee#991
EE PR: tarantool/tarantool-ee#992
Jira task: [TNTP-192](https://jira.vk.team/browse/TNTP-192)
> config: add failover learners section

- changelogs/unreleased/gh-10825-sql-count-as-first-stmt.md
- src/box/sql.c
- src/box/sql/vdbe.c
- test/engine-luatest/gh_10825_sql_count_ro_txn_test.lua
Currently, we use raw index for count operation instead of `box_index_count`. As a result, we skip a check if current transaction can continue and we don't begin transaction in engine if needed. So, if count statement is the first in a transaction, it won't be tracked by MVCC since it wasn't notified about the transaction. The commit fixes the mistake. Also, the commit adds a check if count was successful and covers it with a test.
See the commit for additional details.
Closes #10825
> [Backport 2.11] sql: do not use raw index for count

- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
Now `failover.stateboard.enabled` boolean option can be used to enable/disable the failover coordinator stateboard. Default value equals to `true`.
`failover.stateboard.enabled: true` requires for one of the compatible remote config sources to be set in the `config` section. Otherwise the failover coordinator doesn't start.
The option is enterprise-only since it's a part of the supervised failover.
Needed for EE tarantool/tarantool-ee#996.
> config: add failover.stateboard.enabled option

- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/isolated_mode_test.lua
An isolated instance shouldn't process user traffic. This commit adds a logic to the isolated mode that stop listening for new connections and drop existing connections in iproto.
Part of #10796
> config: drop iproto connections in isolated mode

- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/isolated_mode_test.lua
The isolated mode can be enabled to stop data modifications on the given instance, including ones from the replication: it may help to debug a problem or extract some needed data. So, it seems worthful to stop replication from the non-isolated part of the replicaset to the instance.
The isolated instance goes to RO and drops iproto connections -- it should effectively stop replication from it *to* the non-isolated part of the replicaset. There is no sense to retry an attempt to connect to it and flood logs with errors. Let's just remove the isolated instance from the upstreams list.
Part of #10796
> config: don't replicate data from/to isolated instance

- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/isolated_mode_test.lua
This way it is harder to overlook that the instance is isolated. It islikely important information for a person who performs administration tasks.
Closes #10796
> config: issue an alert on isolated instance

- changelogs/unreleased/gh-9849-lua-memory-limit-config.md
- src/CMakeLists.txt
- src/box/CMakeLists.txt
- src/box/lua/config/applier/lua.lua
- src/box/lua/config/init.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/init.c
- src/lua/alloc.c
- src/lua/alloc.h
- src/lua/init.c
- src/lua/utils.c
- src/lua/utils.h
- test/app-luatest/alloc_test.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/lua_memory_test.lua
Sometimes we need to limit Lua maximum available memory. Add the config property `lua.memory` to specify the maximum byte amount used for lua allocations.
The limit is implemented with a custom allocation function. It's passed into a Lua state during instantiation. The function itself counts memory used by LuaJIT and prevents allocating more than specified in the config file.
If new memory limit is applied at runtime Tarantool waits for instance reload before applying a new option. 
Closes #8881
> config: add `lua.memory` option

- .github/workflows/perf_micro.yml
- .test.mk
- CMakeLists.txt
- cmake/BuildBenchmark.cmake
- perf/CMakeLists.txt
This patch fixates the GitHub CI runner with the label 'performance' for the aforementioned workflow, if it is run from the master, release branch, or triggered by PR from the main repository. It helps to avoid disturbance in the results of benchmarks due to different machine parameters.
NO_TEST=ci
NO_DOC=ci
----
Depends on https://github.com/tarantool/small/pull/100
> ci: fixate the runner for perf_micro workflow

- perf/lua/uri_escape_unescape.lua
- perf/tools/setup_env.sh
This patchset makes Lua benchmars more stable:
The first commit removes excess JIT settings from <lua/uri_escape_unescape.lua> and increases the amount of iterations for tests.
The second commit disables ASLR to avoid different LuaJIT VM states from run to run.
> Stabilize Lua benches

- changelogs/unreleased/gh-10596-connpool-filter-support-alive-filtering.md
- changelogs/unreleased/gh-10598-make-connpool-call-faster.md
- src/box/lua/connpool.lua
- test/config-luatest/rpc_test.lua
This patch consist of two changes in the connection pool. For sure, they should be two different PRs, but I've accidentally made one of them as a minor change in terms of the other not knowing there is an issue on it.
The `connpool.filter()` now by default returns only available instances. This check can be skipped using a new `connpool.filter()` boolean option `skip_connection_check` (by default it equals `false`).
Filtering by `ro`/`rw` mode requires the connection check to be enabled.
Examples:
```lua
-- 'instance-001', 'instance-002' are available, 'instance-003' is down.
-- The table will contain 'instance-001' and 'instance-002'.
let alive = connpool.filter()
-- The table will contain 'instance-001', 'instance-002' and
-- 'instance-003'.
let all = connpool.filter({ …
```
> connpool: make `call()` execution faster

- changelogs/unreleased/gh-10538-add-on-event-callback-to-roles.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
config: add on_event callback for roles
This patch add `on_event` callback for roles.
Closes #10538
Closes TNTP-225
Title: `on_event` callback for roles
Roles can now set a `on_event` callback, which will be called
every time a `box.status` system event is broadcasted or the
configuration has been updated (after the `apply` has finished).
`on_event` callbacks are called one after another in the order
the roles are applied (according to their dependencies). Each
event (`box.status` or configuration change) triggers a series
of callbacks, next series (for a new event) will be triggered
after the previous finishes.
`on_event` callbacks are executed inside a `pcall` and if error is
raised, it is logged with 'error' level and the series execution
continues.
It is …
> config: add on_event callback for roles

- changelogs/unreleased/config-replication-autoexpel.md
- src/box/CMakeLists.txt
- src/box/lua/config/applier/autoexpel.lua
- src/box/lua/config/configdata.lua
- src/box/lua/config/descriptions.lua
- src/box/lua/config/init.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/init.c
- test/config-luatest/autoexpel_test.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
The new option is useful for management of dynamic clusters using the YAML configuration. The option allows to automatically expel instances that are removed from the YAML configuration.
A ready-to-run example:
```yaml
credentials:
users:
guest:
roles: [super]
replication:
failover: manual
autoexpel:
enabled: true
by: prefix
prefix: '{{ replicaset_name }}'
iproto:
listen:
- uri: 'unix/:./var/run/{{ instance_name }}.iproto'
groups:
g-001:
replicasets:
r-001:
leader: r-001-i-001
instances:
r-001-i-001: {}
r-001-i-002: {}
r-001-i-003: {}
```
How to run the example:
1. Start all the three instances:
```shell
$ tarantool --name r-001-i-001 --config config.yaml -i
$ tarantool --name r-001-i-002 --config config.yaml -i
$ tarantool --name r-001-i-003 --config config.yaml -i
```
2. Remove …
> config: allow to automatically expel instances

- changelogs/unreleased/gh_10155_make_iproto_resistant_to_misusage.md
- src/box/iproto.cc
- src/lib/core/errinj.h
- test/box-luatest/gh_10155_make_iproto_resistant_to_misusage_test.lua
Fixed an issue when the tarantool could be easily crashed using iproto incorrectly, not according to the protocol.
The problem seems to be unsynchronized multi-threaded communication with the socket. Hence the large number of different backtraces and assertions. To reproduce this, instead of `IPROTO_OK` you can use anything whose route looks like ->main->iproto (looks like all messages are going this way now), for example, I checked this with `IPROTO_PING`. A bad execution scenario is shown in the picture:
More specifically, the problem is that when `tx_process_replication` is executed in `main`, it does not know anything about the c-messages that are queued at the "net_x" endpoint in `iproto`. In `iproto_enqueue_batch` we call `ev_io_stop` on both `input`/`output` watchers, which …
> iproto: make iproto resistant to misusage

- src/box/relay.cc
- test/replication-luatest/gh_10727_no_local_rows_test.lua
Commit 7aac790ef3e28 ("relay: send raft requests with GROUP_DEFAULT id") tried to send all raft rows with GROUP_DEFAULT id. However, relay didn't know the version_id of the instance during initial JOIN, so raft state was sent with GROUP_LOCAL id. The test didn't properly work.
This commit fixes relay by setting proper version_id during initial JOIN. The test is also fully rewritten.
Follows up #10727
> relay: fix sending raft requests with GROUP_DEFAULT id

- src/main.cc
Dear Tarantool team,
NO_DOC: Documentation changes not needed - only fixing typos
NO_CHANGELOG: No functional changes that need changelog entry
NO_TEST: Changes are limited to comments and includes
Fixed several typos in src/main.cc:
- Removed duplicate include of <getopt.h>
- Fixed 'reponsible' -> 'responsible' in comments
- Fixed 'interpeter' -> 'interpreter' in comments 
- Fixed 'tarantol' -> 'tarantool' in comments
have a good day.
> main: fix typos in comments and includes

- changelogs/unreleased/gh-10870-fix-vinyl-tx-stmt-overwrite-multikey.md
- src/box/vy_tx.c
- test/vinyl-luatest/tx_stmt_overwrite_test.lua
A multikey index stores a tuple once per each entry of the indexed array field, excluding duplicates. For example, if the array field equals {1, 3, 2, 3}, the tuple will be stored three times. Currently, when a tuple with duplicate multikey entries is inserted into a transaction write set, duplicates are overwritten as if they belonged to different statements. Actually, this is pointless: we could just as well skip them without trying to add to the write set. Besides, this may break the assumptions taken by various optimizations, resulting in anomalies. Consider the following example:
```lua
local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('primary')
s:create_index('secondary', {parts = {{'[2][*]', 'unsigned'}}})
s:replace({1, {10, 10}})
s:update({1}, {{'=', 2, …
```
> vinyl: fix handling of duplicate multikey entries in transaction write set

- changelogs/unreleased/config-lack-of-sharding-role.md
- src/box/lua/config/configdata.lua
- test/config-luatest/vshard_test.lua
Before this change an instance with enabled sharding role assumes that all the other instances in the cluster have some sharding role enabled or at least an empty list of sharding roles.
This is a bug: a cluster may have instances that have no role in regards to sharding.
Fixes #10458
> config: don't fail on lack of sharding.roles

- changelogs/unreleased/config-lack-of-sharding-role.md
- src/box/lua/config/configdata.lua
- test/config-luatest/vshard_test.lua
*(This is a backport of PR #10884 to `release/3.3`, a future `3.3.1` release.)*
----
Before this change an instance with enabled sharding role assumes that all the other instances in the cluster have some sharding role enabled or at least an empty list of sharding roles.
This is a bug: a cluster may have instances that have no role in regards to sharding.
Fixes #10458
> [backport 3.3] config: don't fail on lack of sharding.roles

- changelogs/unreleased/config-lack-of-sharding-role.md
- src/box/lua/config/configdata.lua
- test/config-luatest/vshard_test.lua
*(This is a backport of PR #10884 to `release/3.2`, a future `3.2.2` release.)*
----
Before this change an instance with enabled sharding role assumes that all the other instances in the cluster have some sharding role enabled or at least an empty list of sharding roles.
This is a bug: a cluster may have instances that have no role in regards to sharding.
Fixes #10458
> [backport 3.2] config: don't fail on lack of sharding.roles

- changelogs/unreleased/gh-10855-schema-get-set-changes-path.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/config_test.lua
- test/config-luatest/schema_test.lua
This patch makes `schema:get()`, `schema:set()` and `config:get()` not change the passed path argument when it is a table.
The problem was in the way the walkthrough process is set up during the `schema:get()` and `schema:set()` method execution. These methods used `walkthrough_start()` performing a shallow copy of the passed option table containing the information on the desired path. The value of the path was modified during the walkthrough itself. The patch makes
the methods perform a shallow copy of the path field. It also fixes `config:get()` since it internally uses `schema:get()`.
This is how broken scenario could be reproduced when using `config:get()`:
```
tarantool> config = require('config')
tarantool> path = {'fiber', 'slice'}
tarantool> config:get(path)
---
- err: 1
warn: 0.5 …
```
> config: fix schema:get/schema:set() changes passed path

- changelogs/unreleased/gh-10855-schema-get-set-changes-path.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/config_test.lua
- test/config-luatest/schema_test.lua
*(This is a backport of PR #10886 to `release/3.3`, a future `3.3.1` release.)*
----
This patch makes `schema:get()`, `schema:set()` and `config:get()` not change the passed path argument when it is a table.
The problem was in the way the walkthrough process is set up during the `schema:get()` and `schema:set()` method execution. These methods used `walkthrough_start()` performing a shallow copy of the passed option table containing the information on the desired path. The value of the path was modified during the walkthrough itself. The patch makes the methods perform a shallow copy of the path field. It also fixes `config:get()` since it's internally uses `schema:get()`.
This is how broken scenario could be reproduced when using `config:get()`:
```
tarantool> config = require('config') …
```
> [backport 3.3] config: fix schema:get()/set() changes passed path

- changelogs/unreleased/gh-10855-schema-get-set-changes-path.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/config_test.lua
- test/config-luatest/schema_test.lua
*(This is a backport of PR #10886 to `release/3.2`, a future `3.2.2` release.)*
----
This patch makes `schema:get()`, `schema:set()` and `config:get()` not change the passed path argument when it is a table.
The problem was in the way the walkthrough process is set up during the `schema:get()` and `schema:set()` method execution. These methods used `walkthrough_start()` performing a shallow copy of the passed option table containing the information on the desired path. The value of the path was modified during the walkthrough itself. The patch makes the methods perform a shallow copy of the path field. It also fixes `config:get()` since it's internally uses `schema:get()`.
This is how broken scenario could be reproduced when using `config:get()`:
```
tarantool> config = require('config') …
```
> [backport 3.2] config: fix schema:get()/set() changes passed path

- test/config-luatest/compat_test.lua
*(This is a backport of PR #10867 to `release/3.2`.)*
*Once it reaches a timeout on the ASAN job in CI, so I decided to backport it.*
----
It spawns a lot of processes and sometimes hits a test timeout limit on my machine, when run in parallel with other tests.
Also, if I run the single test with the parallelization, the parallel execution reduces time from 45 to 25 seconds.
> [backport 3.2] test: parallelize config-luatest/compat_test

- changelogs/unreleased/gh_10155_make_iproto_resistant_to_misusage.md
- src/box/iproto.cc
- src/lib/core/errinj.h
- test/box-luatest/gh_10155_make_iproto_resistant_to_misusage_test.lua
Fixed an issue when the tarantool could be easily crashed using iproto incorrectly, not according to the protocol.
Closes #10155
NO_DOC=bugfix
(cherry picked from commit https://github.com/tarantool/tarantool/pull/10589/commits/45f42c79f2be17d98ef557bdbfacf6426dbbdf29)
> [backport 3.2] iproto: make iproto resistant to misusage

- changelogs/unreleased/gh_10155_make_iproto_resistant_to_misusage.md
- src/box/iproto.cc
- src/lib/core/errinj.h
- test/box-luatest/gh_10155_make_iproto_resistant_to_misusage_test.lua
Fixed an issue when the tarantool could be easily crashed using iproto incorrectly, not according to the protocol.
Closes #10155
NO_DOC=bugfix
(cherry picked from commit 45f42c79f2be17d98ef557bdbfacf6426dbbdf29)
> [backport 2.11] iproto: make iproto resistant to misusage

- test/app-luatest/alloc_test.lua
This patch fixes the flaky test verifying `used()` and `unused()` functions of the `internal.alloc` module in the `alloc_test` suite.
The test compares the value of the unused memory with the one calculated by the builtin Lua functions. This test has been failing on a few coverage workflows. The executed and the real values has been close to each other though not equal. This false negative result likely happens because of the details of the `collectgarbage()` implementation.
This patch fixes it by adding arbitrary margin equal to 16Kb of memory when comparing the value calculated using the LuaJIT call with the one provided by the module function.
> lua: fix flaky custom allocator test

- test/app-luatest/alloc_test.lua
*(This is a backport of PR #10909 to `release/3.3`.)*
----
This patch fixes the flaky test verifying `used()` and `unused()` functions of the `internal.alloc` module in the `alloc_test` suite.
The test compares the value of the unused memory with the one calculated by the builtin Lua functions. This test has been failing on a few workflows. The executed and the real values has been close to each other though not equal. This false negative result likely happens because of the details of the `collectgarbage()` implementation.
This patch fixes it by adding arbitrary margin equal to 16Kb of memory when comparing the value calculated using the LuaJIT call with the one provided by the module function.
> [backport 3.3] lua: fix flaky custom allocator test

- changelogs/unreleased/gh-10879-fix-vinyl-cache-invalidation-on-rollback.md
- src/box/vy_cache.c
- src/box/vy_cache.h
- src/box/vy_lsm.c
- src/box/vy_tx.c
- test/vinyl-luatest/gh_10879_invalidate_cache_on_rollback_test.lua
Once a statement is prepared to be committed to WAL, it becomes visible (in the 'read-committed' isolation level) so it can be added to the tuple cache. That's why if the statement is rolled back due to a WAL error, we have to invalidate the cache. The problem is that the function invalidating the cache (`vy_cache_on_write`) ignores the statement if it's a DELETE judging that "there was nothing and there is nothing now". This is apparently wrong for rollback. Fix it.
While we are at it, let's also do a bit of related refactoring. It isn't necessary to fix the bug, but it should make the code more straightforward.
Closes #10879
> vinyl: fix cache invalidation on rollback of DELETE statement

- changelogs/unreleased/gh-10347-proper-instance-duplicates-messages.md
- src/box/lua/config/configdata.lua
- test/config-luatest/cluster.lua
- test/config-luatest/cluster_config_test.lua
*(This is a backport of PR #10913 to `release/3.3`, a future `3.3.1` release.)*
----
Tarantool couldn't start with more than one group/replicaset/instance with the same name. Applying cluster configuration with name duplicates results with failed checks during the config application and violated constraints w/o proper error message.
This patchset makes Tarantool throw proper error messages when it has replicasets with the same name in different groups or instances with the same names in different replicasets in the cluster configuration.
Closes #10347
> [backport 3.3] config: add error on the same replicaset/instance names

- changelogs/unreleased/gh-10561-anon-replicas-dont-participate-in-elections.md
- src/box/box.cc
- test/replication-luatest/anon_test.lua
Fixed a bug where anonymous replicas could participate in elections or even be chosen as a leader. It is now forbidden to configure a replica so `replication_anon == true` and `election_mode != 'off'`. It is also now prohibited to issue PROMOTE from an anonymous replica.
Closes #10561
> replication: anon replicas don't participate in elections

- changelogs/unreleased/config-schema-deep-merge.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/app_test.lua
- test/config-luatest/roles_test.lua
- test/config-luatest/schema_test.lua
`<schema object>:merge()` now performs a deep merge inside an `any` scalar value if left-hand and right-hand values are both tables, where all the keys are strings.
The cluster configuration options that are marked as `any` in the schema (fields of `app.cfg` and `roles_cfg`) are now merged deeply.
Fixes #10450
> config/schema: deep-merge tables under `any` type

- changelogs/unreleased/gh-10561-anon-replicas-dont-participate-in-elections.md
- src/box/box.cc
- test/replication-luatest/anon_test.lua
Fixed a bug where anonymous replicas could participate in elections or even be chosen as a leader. It is now forbidden to configure a replica so that `replication_anon` is `true` and `election_mode` is not `off`. It is also now prohibited to issue PROMOTE from an anonymous replica.
Closes #10561
Title: changes in `replication_anon` and `election_mode` configuration Product: Tarantool
Since: 3.3
[replication-anon] https://www.tarantool.io/ru/doc/latest/reference/configuration/#cfg-replication-replication-anon
```diff
- In order to make a replica anonymous, pass the option `replication_anon=true` to `box.cfg` and set `read_only` to `true`.
+ In order to make a replica anonymous, pass the option `replication_anon=true` to `box.cfg`, set `read_only` to `true` and …
```
> [backport 2.11] replication: anon replicas don't participate in elections

- changelogs/unreleased/config-schema-deep-merge.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/app_test.lua
- test/config-luatest/roles_test.lua
- test/config-luatest/schema_test.lua
*(This is a backport of PR #10921 to `release/3.3`, a future `3.3.1` release.)*
----
`<schema object>:merge()` now performs a deep merge inside an `any` scalar value if left-hand and right-hand values are both tables, where all the keys are strings.
The cluster configuration options that are marked as `any` in the schema (fields of `app.cfg` and `roles_cfg`) are now merged deeply.
Fixes #10450
> [backport 3.3] config/schema: deep-merge tables under `any` type

- changelogs/unreleased/config-schema-deep-merge.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/app_test.lua
- test/config-luatest/roles_test.lua
- test/config-luatest/schema_test.lua
*(This is a backport of PR #10921 to `release/3.2`, a future `3.2.2` release.)*
----
`<schema object>:merge()` now performs a deep merge inside an `any` scalar value if left-hand and right-hand values are both tables, where all the keys are strings.
The cluster configuration options that are marked as `any` in the schema (fields of `app.cfg` and `roles_cfg`) are now merged deeply.
Fixes #10450
> [backport 3.2] config/schema: deep-merge tables under `any` type

- changelogs/unreleased/gh-10561-anon-replicas-dont-participate-in-elections.md
- src/box/box.cc
- test/replication-luatest/anon_test.lua
Fixed a bug where anonymous replicas could participate in elections or even be chosen as a leader. It is now forbidden to configure a replica so that `replication_anon` is `true` and `election_mode` is not `off`. It is also now prohibited to issue PROMOTE from an anonymous replica.
Closes #10561
Title: changes in `replication_anon` and `election_mode` configuration Product: Tarantool
Since: 3.3
[replication-anon] https://www.tarantool.io/ru/doc/latest/reference/configuration/#cfg-replication-replication-anon
```diff
- In order to make a replica anonymous, pass the option `replication_anon=true` to `box.cfg` and set `read_only` to `true`.
+ In order to make a replica anonymous, pass the option `replication_anon=true` to `box.cfg`, set `read_only` to `true` and …
```
> [backport 3.2] replication: anon replicas don't participate in elections

- changelogs/unreleased/gh-10561-anon-replicas-dont-participate-in-elections.md
- src/box/box.cc
- test/replication-luatest/anon_test.lua
Fixed a bug where anonymous replicas could participate in elections or even be chosen as a leader. It is now forbidden to configure a replica so that `replication_anon` is `true` and `election_mode` is not `off`. It is also now prohibited to issue PROMOTE from an anonymous replica.
Closes #10561
Title: changes in `replication_anon` and `election_mode` configuration Product: Tarantool
Since: 3.3
[replication-anon] https://www.tarantool.io/ru/doc/latest/reference/configuration/#cfg-replication-replication-anon
```diff
- In order to make a replica anonymous, pass the option `replication_anon=true` to `box.cfg` and set `read_only` to `true`.
+ In order to make a replica anonymous, pass the option `replication_anon=true` to `box.cfg`, set `read_only` to `true` and …
```
> [backport 3.3] replication: anon replicas don't participate in elections

- changelogs/unreleased/gh-10707-fix-vinyl-abort-writers-on-ddl.md
- src/box/vinyl.c
- src/box/vy_lsm.c
- src/box/vy_tx.c
- src/box/vy_tx.h
- test/engine-luatest/gh_10377_ddl_and_concurrent_transactions_test.lua
When a DDL statement is committed, all transactions writing to the space must be aborted so that they don't access the stale `txn_stmt::space` pointer on commit. In Vinyl we abort all writers from the special `space_invalidate` engine callback, where we iterate over all writing transactions and abort those of them that have a write set entry pointing to the primary key of the invalidated space, see commit d3e1236956515 ("vinyl: abort affected transactions when space is removed from cache"). We also abort transactions that haven't yet created a write set entry because they need to read the disk first, for example, to perform a tuple update, see commit 4f62ec2102f4 ("vinyl: make tx_manager_abort_writers_for_ddl more thorough").
However, as spotted by @drewdzzz, this code doesn't always work …
> vinyl: fix abort of writers on DDL

- perf/lua/column_insert.lua
- perf/lua/column_insert_module.c
- test/unit/mp_print_unknown_ext.c
It allows to choose how non-NULL columns are distributed across the dataset - sequentially or randomly (new default mode).
> perf/lua: introduce sparse_mode option for column_insert.lua

- src/box/memtx_tx.c
- src/box/txn.c
- src/box/txn.h
- src/box/vinyl.c
- src/box/vy_tx.c
- src/box/vy_tx.h
- test/unit/core_test_utils.c
- tools/tarantool-gdb.py
It is not something intrinsic to the manager and also is useful for other engines.
Part of tarantool/tarantool-ee#893
> box: move txn list out of memtx manager

- cmake/luajit.cmake
- test/luajit-test-init.lua
Since the commit db351d3bc46cf80f4f673129c46a3a4b8be3cadd ("luajit: bump new version"), which introduces CTest as a launcher for LuaJIT's test suites, the LuaJIT tests are not run by Tarantool since `LUAJIT_USE_TEST` is disabled. This patch enables all tests, except ASAN build, due to #10733.
NO_DOC=testing
NO_TEST=enable tests back
> test: enable back tests for LuaJIT

- perf/light.cc
- src/box/memtx_bitset.cc
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/sequence.c
- src/box/vy_cache.c
- src/box/vy_cache.h
- src/box/vy_mem.c
- src/box/vy_mem.h
- src/lib/salad/bps_tree.h
- src/lib/salad/light.h
- src/lib/salad/rtree.c
- src/lib/salad/rtree.h
- test/unit/bps_tree.cc
- test/unit/bps_tree_iterator.cc
- test/unit/bps_tree_view.c
- test/unit/light.cc
- test/unit/light_view.c
- test/unit/rtree.cc
- test/unit/rtree_iterator.cc
- test/unit/rtree_multidim.cc
A long time ago the it's been found that in some circumstances the RTREE index could fail to rollback because of OOM. This is the case because removal of a key from such an index can sometimes lead to allocation of new blocks that could fail. So, in order to guarantee a successful rollback of an insertion into the index, the memtx engine extent reservation machinery had been introduced (see the issue #727).
But some time ago it's beed found out that the reservation of memory prior to insertion can be not enough to guarantee a successful roll back of the statements, so it's been decided to use a regular malloc for failed allocations performed during rollback (see #10551). This also fixed the RTREE issue for which the extent reservation had been introduced in the first place.
But this …
> [backport 2.11] small: bump version

- cmake/luajit.cmake
Orig PR: https://github.com/tarantool/tarantool/pull/10824.
The first commit isn't taken, since the Lua memory limit is introduced for version 3.3+.
---
Since the commit db351d3bc46cf80f4f673129c46a3a4b8be3cadd ("luajit: bump new version"), which introduces CTest as a launcher for LuaJIT's test suites, the LuaJIT tests are not run by Tarantool since `LUAJIT_USE_TEST` is disabled. This patch enables all tests, except ASAN build, due to #10733.
NO_DOC=testing
NO_TEST=enable tests back
(cherry picked from commit 1f09ba66ed30311256fb0235a08870a1193f750c)
> [backport/release/3.2] test: enable back tests for LuaJIT

- changelogs/unreleased/gh-10934-fix-roles-on_event-config-argument.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
The config object was passed to the `on_event` callback instead of the corresponding roles config before. Lets fix it, implementing the intended behavior.
NO_DOC=bugfix
Closes #10934
> config: fix on_event roles callback config argument

- changelogs/unreleased/gh-10934-fix-roles-on_event-config-argument.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
*(This is a backport of PR #10935 to `release/3.3`, a future `3.3.1` release.)*
----
The config object was passed to the `on_event` callback instead of the corresponding roles config before. Lets fix it, implementing the intended behavior.
Closes #10934
> [backport 3.3] config: fix on_event roles callback config argument

- test/CMakeLists.txt
In CMake command `file(GLOB_RECURSE ...)` latest unnamed arguments are search patterns `<globbing-expressions>`. In the patch with initial CTest support pattern `${PROJECT_SOURCE_DIR}/test` was used and with commands below:
```
$ mkdir -p {a,b}/my
$ touch {a,b}/my/test
$ cmake .
```
this leads to an error:
```
-- Add regression tests
CMake Error at test/CMakeLists.txt:196 (add_test):
add_test given test NAME "test/my/test" which already exists in this
directory.
```
The patch fixes the problem. Follows up commit a9b9f2eb4f71 ("test: execute tests using CTest").
1. https://cmake.org/cmake/help/latest/command/file.html#glob-recurse
NO_DOC=testing
Reported-By: Alexander Turenko <alexander.turenko@tarantool.org>
Reported-By: Sergey Kaplun …
> cmake: fix search patterns used by ctest

- test/config-luatest/log_wrapper_test.lua
The test has 172 test cases and spawns a lot of processes. It takes ~30 seconds (+/-10 seconds) on my laptop in the sequential and in the parallel run both. The difference seems within the noise level. The parallel execution seems slightly longer, approximately +5 seconds.
However, if we run the test cases separately, the test timeout limit (110 seconds by default) is applied to each particular test case. It may be important for testing runs on a slow machine or when a slow instrumented build (such as ASAN) is used.
> test: parallelize config-luatest/log_wrapper_test

- test/config-luatest/failover_and_election_mode_test.lua
This test file has 36 test cases and gains some speed from the parallelization (35-40 seconds to 15-25 seconds on my laptop).
However, it is more important that now the test-run's test timeout (110 seconds by default) is applied for each particular test case. I met some test timeout fails on this test in CI. Don't remember precisely, but it is likely on a slow machine or on a build instrumented by the address sanitizer.
> test: parallelize failover_and_election_mode_test

- test/config-luatest/rpc_test.lua
The test gains a lot from the parallelization, because there are test cases that verify connpool's connection timeout (10 seconds) and they have to wait for the connection failure for this time interval without any actual workload.
On my laptop the parallelization reduces the execution time from 58 seconds to 15-16 seconds.
Also, I met a failure of this test due to the default test-run's test timeout (110 seconds), when it is run in parallel with others. Now it shouldn't occur anymore.
> test: parallelize config-luatest/rpc_test

- test/app-luatest/alloc_test.lua
This patch fixes the flaky test verifying `used()` and `unused()` functions of the `internal.alloc` module in the `alloc_test` suite.
The test compares the value of the used memory with the one calculated by the builtin Lua functions. The executed and the real values has been close to each other though not equal. This false negative result likely happens because of the details of the `collectgarbage()` implementation.
This patch fixes it by adding arbitrary margin equal to 16Kb of memory when comparing the value calculated using the LuaJIT call with the one provided by the module function.
The same problem has been fixed in terms of the commit 7731d13d0af6a1 ("lua: fix flaky custom allocator test"). The previous commit fixed corresponding checks on the `unused()` value. This one fixes …
> lua: fix flaky custom allocator test again

- test/app-luatest/alloc_test.lua
*(This is a backport of PR #10967  to `release/3.3`, a future `3.3.1` release.)*.
---
This patch fixes the flaky test verifying `used()` and `unused()` functions of the `internal.alloc` module in the `alloc_test` suite.
The test compares the value of the used memory with the one calculated by the builtin Lua functions. The executed and the real values has been close to each other though not equal. This false negative result likely happens because of the details of the `collectgarbage()` implementation.
This patch fixes it by adding arbitrary margin equal to 16Kb of memory when comparing the value calculated using the LuaJIT call with the one provided by the module function.
The same problem has been fixed in terms of the commit 7731d13d0af6a1 ("lua: fix flaky custom allocator test"). The …
> [backport 3.3] lua: fix flaky custom allocator test again

- test/config-luatest/failover_and_election_mode_test.lua
- test/config-luatest/log_wrapper_test.lua
- test/config-luatest/rpc_test.lua
This is a backport of several PRs to `release/3.3`.
| Test                                                 | Pull request |
| ---------------------------------------------------- | ------------ |
| `config-luatest/log_wrapper_test.lua`                | #10960       |
| `config-luatest/failover_and_election_mode_test.lua` | #10962       |
| `config-luatest/rpc_test.lua`                        | #10963       |
> [backport 3.3] test: parallelize several `config-luatest/*` tests

- test/config-luatest/failover_and_election_mode_test.lua
- test/config-luatest/log_wrapper_test.lua
- test/config-luatest/rpc_test.lua
This is a backport of several PRs to `release/3.2`.
| Test                                                 | Pull request |
| ---------------------------------------------------- | ------------ |
| `config-luatest/log_wrapper_test.lua`                | #10960       |
| `config-luatest/failover_and_election_mode_test.lua` | #10962       |
| `config-luatest/rpc_test.lua`                        | #10963       |
> [backport 3.2] test: parallelize several `config-luatest/*` tests

- test/CMakeLists.txt
The glob `*.test.sql` is missed in ctest search patterns. The patch fixes that. Follows up a9b9f2eb4f71
("test: execute tests using CTest").
NO_DOC=testing
> test: add missed *.test.sql pattern

- cmake/luajit.cmake
Orig PR: https://github.com/tarantool/tarantool/pull/10824.
The first commit isn't taken, since the Lua memory limit is introduced for version 3.3+.
---
Since the commit db351d3bc46cf80f4f673129c46a3a4b8be3cadd ("luajit: bump new version"), which introduces CTest as a launcher for LuaJIT's test suites, the LuaJIT tests are not run by Tarantool since `LUAJIT_USE_TEST` is disabled. This patch enables all tests, except ASAN build, due to #10733.
NO_DOC=testing
NO_TEST=enable tests back
(cherry picked from commit 1f09ba66ed30311256fb0235a08870a1193f750c)
> [backport/release/2.11] test: enable back tests for LuaJIT

- test/app-luatest/CMakeLists.txt
- test/config-luatest/CMakeLists.txt
- test/metrics-luatest/CMakeLists.txt
- test/vinyl-luatest/CMakeLists.txt
luatest has an option `--shuffle` that allows to reorder testcases before execution. This can be useful to detect a test that passes just because it happens to run after an unrelated test that leaves the system in a favourable state. Patch enables tests shuffling with predefined random seed generated by CMake [1] and a fixes for a tests were failed after enabling shuffle mode. Seed is useful for reproducing a problems related to the specific test order.
The patch enables shuffle mode only in `appl-luatest`, `metrics-luatest`, `config-luatest` and `vinyl-luatest`. In other test suites tests failed with enabled shuffle mode. For these suites mode will be enabled later.
Follows up commit 9e3e9eedc025
("cmake: support luatest tests by CTest")
1. …
> cmake: shuffle testcases in luatest's tests

- src/lib/bit/bit.c
- src/lib/bit/bit.h
- test/unit/bit.c
- test/unit/bit.result
This function sets a range of bits to all-zeros or all-ones.
Needed for tarantool/tarantool-ee#1050
> lib/bit: introduce `bit_set_range()`

- changelogs/unreleased/gh-9923-fix-invalid-iproto-name-mapping-on-the-server-side.md
- src/box/iproto.cc
- test/box-luatest/gh_9923_invalid_iproto_index_name_mapping_on_the_server_side_test.lua
iproto: fix IPROTO index name to ID mapping
Previously, index names were resolved to dense IDs, which caused
failures when accessing indexes by name. This happened because the
index_map lookup expected user-visible IDs (index->def->iid), not dense IDs.
The fix replaces dense_id with index->def->iid to ensure correct mapping
of index names to their numeric IDs, aligning with the expected behavior
when accessing indexes by name.
Closes #9923
> Fix iproto index name to ID mapping

- changelogs/unreleased/gh-9923-fix-invalid-iproto-name-mapping-on-the-server-side.md
- src/box/iproto.cc
- test/box-luatest/gh_9923_invalid_iproto_index_name_mapping_on_the_server_side_test.lua
Previously, index names were resolved to dense IDs, which caused failures when accessing indexes by name. This happened because the index_map lookup expected user-visible IDs (index->def->iid), not dense IDs.
The fix replaces dense_id with index->def->iid to ensure correct mapping of index names to their numeric IDs.
Closes #9923
NO_DOC=bug fix
(cherry picked from commit ef3775abf030132fddf7e6f2fcacb8fc809a9720)
> [backport 3.2] iproto: fix IPROTO index name to ID mapping

- changelogs/unreleased/gh-9923-fix-invalid-iproto-name-mapping-on-the-server-side.md
- src/box/iproto.cc
- test/box-luatest/gh_9923_invalid_iproto_index_name_mapping_on_the_server_side_test.lua
Previously, index names were resolved to dense IDs, which caused failures when accessing indexes by name. This happened because the index_map lookup expected user-visible IDs (index->def->iid), not dense IDs.
The fix replaces dense_id with index->def->iid to ensure correct mapping of index names to their numeric IDs.
Closes #9923
NO_DOC=bug fix
(cherry picked from commit ef3775abf030132fddf7e6f2fcacb8fc809a9720)
> [backport 3.3] iproto: fix IPROTO index name to ID mapping

- src/lib/bit/bit.c
- src/lib/bit/bit.h
- test/unit/bit.c
- test/unit/bit.result
This function sets a range of bits to all-zeros or all-ones.
Needed for tarantool/tarantool-ee#1050
(cherry picked from commit 41c33ed046ecdbb3b819706e8290a44b9d95158c)
> [backport 3.2] lib/bit: introduce `bit_set_range()`

- src/lib/bit/bit.c
- src/lib/bit/bit.h
- test/unit/bit.c
- test/unit/bit.result
This function sets a range of bits to all-zeros or all-ones.
Needed for tarantool/tarantool-ee#1050
(cherry picked from commit 41c33ed046ecdbb3b819706e8290a44b9d95158c)
> [backport 3.3] lib/bit: introduce `bit_set_range()`

- test/box-luatest/gh_7605_qsort_recovery_test.lua
- test/box-luatest/suite.ini
The test used to take around 180 seconds in debug build and was quite flaky.
When the test was introduced in commit e1d961708504 ("Fix a bug in qsort") it was stated that such a long test with 2 million keys was needed to reproduce the bug.
Since the test introduction our sort implementation was rewritten in commit ec34bf7ba3ea ("core: introduce sample sort algorithm") and commit 4f617b702f0f ("box: introduce memtx_sort_threads config parameter").
Now multithread sort is used as long as there are more than a 1024 keys to sort, so such a huge test seems unnecessary.
Let's reduce test size to 20000 keys from 2000000 and make the test code yield every 1000 iterations instead of 10000, which is a more common practice.
When running the test a lot times in parallel the fiber slice check may …
> test: speedup and stabilize the gh_7605_qsort_recovery test

- test/box-luatest/gh_7605_qsort_recovery_test.lua
- test/box-luatest/suite.ini
The test used to take around 180 seconds in debug build and was quite flaky.
When the test was introduced in commit e1d961708504 ("Fix a bug in qsort") it was stated that such a long test with 2 million keys was needed to reproduce the bug.
Since the test introduction our sort implementation was rewritten in commit ec34bf7ba3ea ("core: introduce sample sort algorithm") and commit 4f617b702f0f ("box: introduce memtx_sort_threads config parameter").
Now multithread sort is used as long as there are more than a 1024 keys to sort, so such a huge test seems unnecessary.
Let's reduce test size to 20000 keys from 2000000 and make the test code yield every 1000 iterations instead of 10000, which is a more common practice.
When running the test a lot times in parallel the fiber slice check may …
> [backport 3.3] test: speedup and stabilize the gh_7605_qsort_recovery test

- changelogs/unreleased/config-lack-of-sharding-role.md
- changelogs/unreleased/config-schema-deep-merge.md
- changelogs/unreleased/gh-10347-proper-instance-duplicates-messages.md
- changelogs/unreleased/gh-10561-anon-replicas-dont-participate-in-elections.md
- changelogs/unreleased/gh-10707-fix-vinyl-abort-writers-on-ddl.md
- changelogs/unreleased/gh-10855-schema-get-set-changes-path.md
- changelogs/unreleased/gh-10870-fix-vinyl-tx-stmt-overwrite-multikey.md
- changelogs/unreleased/gh-10879-fix-vinyl-cache-invalidation-on-rollback.md
- changelogs/unreleased/gh-10895-fix-vinyl-deferred-delete-compaction.md
- changelogs/unreleased/gh-10934-fix-roles-on_event-config-argument.md
- changelogs/unreleased/gh-9923-fix-invalid-iproto-name-mapping-on-the-server-side.md
- src/box/lua/upgrade.lua
Remove all changelogs reported in release notes for 3.3.1.
Also add the new downgrade version to the downgrade versions list.
> changelog: cleanup 3.3.1 changelogs

- changelogs/unreleased/gh-8611-log-tables-in-json.md
- src/lua/log.lua
- test/app-luatest/gh_8611_log_tables_in_json_test.lua
This is more convenient than calling `json.encode` manually. It is also more efficient in case logging is skipped due to the log level.
How it used to work:
```
tarantool> require('log').info('%s', {foo = 'bar'})
table: 0x41f9d2e8
```
How it works now:
```
tarantool> require('log').info('%s', {foo = 'bar'})
{"foo":"bar"}
```
Note, JSON encoding is enabled only for tables that don't have the `__tostring` meta-method:
```
tarantool> require('log').info('%s', setmetatable({foo = 'bar'}, {__tostring = function() return 'foobar' end}))
foobar
```
Closes #8611
> log: encode table arguments in json

- test/replication/bootstrap_leader.result
- test/replication/bootstrap_leader.test.lua
- test/replication/rebootstrap.result
- test/replication/rebootstrap.test.lua
- test/replication/suite.cfg
- test/replication/suite.ini
The commit 89cd7f43fd37 ("replication: do not account booting replicas in sync quorum") allowed replicas to leave orphan mode without waiting for everyone listed in box.cfg.replication.
As a result, bootstrap_leader test started exiting too early, because it relied on one of the replicas staying in orphan mode until all the others finish bootstrap. Fix it.
Also, remove "memtx" and "vinyl" configuration for the test. There is nothing in the test related to engines.
While we're at it, remove the test from fragile list. It hasn't flaked since long ago, excluding the last couple of weeks, which's fixed now.
Closes tarantool/tarantool-qa#63
NO_CHANGELOG=flaky test
NO_DOC=flaky test
> test: stabilize replication rebootstrap and bootstrap_leader tests

- test/box-luatest/gh_7605_qsort_recovery_test.lua
- test/box-luatest/suite.ini
The test used to take around 180 seconds in debug build and was quite flaky.
When the test was introduced in commit e1d961708504 ("Fix a bug in qsort") it was stated that such a long test with 2 million keys was needed to reproduce the bug.
Since the test introduction our sort implementation was rewritten in commit ec34bf7ba3ea ("core: introduce sample sort algorithm") and commit 4f617b702f0f ("box: introduce memtx_sort_threads config parameter").
Now multithread sort is used as long as there are more than a 1024 keys to sort, so such a huge test seems unnecessary.
Let's reduce test size to 20000 keys from 2000000 and make the test code yield every 1000 iterations instead of 10000, which is a more common practice.
When running the test a lot times in parallel the fiber slice check may …
> [backport 2.11] test: speedup and stabilize the gh_7605_qsort_recovery test

- test/box-luatest/gh_7605_qsort_recovery_test.lua
- test/box-luatest/suite.ini
The test used to take around 180 seconds in debug build and was quite flaky.
When the test was introduced in commit e1d961708504 ("Fix a bug in qsort") it was stated that such a long test with 2 million keys was needed to reproduce the bug.
Since the test introduction our sort implementation was rewritten in commit ec34bf7ba3ea ("core: introduce sample sort algorithm") and commit 4f617b702f0f ("box: introduce memtx_sort_threads config parameter").
Now multithread sort is used as long as there are more than a 1024 keys to sort, so such a huge test seems unnecessary.
Let's reduce test size to 20000 keys from 2000000 and make the test code yield every 1000 iterations instead of 10000, which is a more common practice.
When running the test a lot times in parallel the fiber slice check may …
> [backport 3.2] test: speedup and stabilize the gh_7605_qsort_recovery test

- .github/workflows/static_build_cmake_linux.yml
- test/CMakeLists.txt
Orig PR: https://github.com/tarantool/tarantool/pull/10995
> [backport 3.3] ci: use cmake 3.17 in static_build_cmake_linux

- src/box/CMakeLists.txt
- src/box/lua/config/extras.h
- src/box/lua/config/init.lua
- src/box/lua/init.c
This patch migrates config.extras module definitions to Tarantool EE.
Now its sources are defined there.
Also, it makes Tarantool validate extras module during a config
initialization phase. It is changed this way to achieve possibility to
load configuration extras after loading the basic config module to
simplify the order of modules loading.
Previous loading order:
* Load `config.extras`.
* Load `config`.
* Load a few more `config.extras`.
New loading order:
* Load `config`.
* Load `config.extras`.
The simplification comes with a cost of less checks in no-configuration
mode though they're not so important since the scenario when we add
`config.extras` and work in no-configuration mode sounds quite strange.
Needed for tarantool/tarantool-ee#1024
> config: migrate extras module definitions to EE

- src/box/CMakeLists.txt
- src/box/lua/config/extras.h
- src/box/lua/config/init.lua
- src/box/lua/init.c
*(This is a backport of PR #10990 to `release/3.3` to a future `3.3.2` release.)*
---
This patch migrates config.extras module definitions to Tarantool EE. Now its sources are defined there.
Also, it makes Tarantool validate extras module during a config initialization phase. It is changed this way to achieve possibility to load configuration extras after loading the basic config module to simplify the order of modules loading.
Previous loading order:
* Load `config.extras`.
* Load `config`.
* Load a few more `config.extras`.
New loading order:
* Load `config`.
* Load `config.extras`.
The simplification comes with a cost of less checks in no-configuration mode though they're not so important since the scenario when we add `config.extras` and work in no-configuration mode sounds quite …
> [backport 3.3] config: migrate extras module definitions to EE

- src/box/CMakeLists.txt
- src/box/lua/config/extras.h
- src/box/lua/config/init.lua
- src/box/lua/init.c
*(This is a backport of PR #10990 to `release/3.2` to a future `3.2.2` release.)*
---
This patch migrates config.extras module definitions to Tarantool EE. Now its sources are defined there.
Also, it makes Tarantool validate extras module during a config initialization phase. It is changed this way to achieve possibility to load configuration extras after loading the basic config module to simplify the order of modules loading.
Previous loading order:
* Load `config.extras`.
* Load `config`.
* Load a few more `config.extras`.
New loading order:
* Load `config`.
* Load `config.extras`.
The simplification comes with a cost of less checks in no-configuration mode though they're not so important since the scenario when we add `config.extras` and work in no-configuration mode sounds quite …
> [backport 3.2] config: migrate extras module definitions to EE

- test/app-luatest/gh_7000_compat_module_test.lua
The commit 8af038b00d32
("cmake: shuffle testcases in luatest's tests") enabled shuffle mode in app-luatest suite. This makes a test
`app-luatest/gh_7000_compat_module_test.lua` flaky, because testcases shares a common state with compat options state
(`option_1_called`, `option_2_called`). The patch adds
initiatilization for the state of the second option to make the test more reliable.
NO_TEST=codehealth
> test: fix app-luatest/gh_7000_compat_module_test.lua

- changelogs/unreleased/gh-10766-synchro-crash-on-exit.md
- src/box/box.cc
- src/box/wal.c
- src/lib/core/errinj.h
- test/replication-luatest/gh_10766_shutdown_non_empty_limbo_test.lua
Normally it couldn't happen with user-originated transactions, because they were always attached to a fiber, and the shutdown code would panic if any user fibers couldn't be cancelled and joined fast enough.
However it could always happen with applier txns (async, no fiber) and now is possible with `wait='none'` or `'submit'` commit modes.
When this would happen, at least 2 situations were possible:
- The txn was not synchro and was just ignored, deleted together with the memory allocator.
- The txn was synchro and waiting for ACKs. It was "freed" (put back into the txn cache) without completion, and its triggers would leak.
- The txn was synchro and being written to WAL right now. Then it was also freed (including its region memory removal), and the WAL thread would sometimes crash on …
> replication: fix crash on non-empty limbo exit

- changelogs/unreleased/gh-10766-synchro-crash-on-exit.md
- src/box/box.cc
- src/box/wal.c
- src/lib/core/errinj.h
- test/replication-luatest/gh_10766_shutdown_non_empty_limbo_test.lua
Normally it couldn't happen with user-originated transactions, because they were always attached to a fiber, and the shutdown code would panic if any user fibers couldn't be cancelled and joined fast enough.
However it could always happen with applier txns (async, no fiber) and now is possible with `wait='none'` and `'submit'` commit modes.
When this happened, at least 2 situations were possible:
- The txn was not synchro and was just ignored, deleted together with the memory allocator.
- The txn was synchro and waiting for ACKs. It was "freed" (put back into the txn cache) without completion, and its triggers would leak.
- The txn was synchro and being written to WAL right now. Then it was also freed (including its region memory removal), and the WAL thread would sometimes crash on …
> [backport 3.3] replication: fix crash on non-empty limbo exit

- test/box-luatest/gh_8650_add_is_sync_option_test.lua
The test runs with memtx mvcc engine turned on, so a synchronous transaction committed on master may not be visible on replica immediately. It becomes visible only after a corresponding CONFIRM entry arrives on replica. Fix the test accordingly.
NO_DOC=test
(cherry picked from commit 714052225ebd282797cb6bf92d431811c6eea5d1)
> [backport 3.2] test: stabilize the gh_8650_add_is_sync_option test

- .github/workflows/backport.yml
This patch adds an action for backporting automatization. Instead of
doing everything with your hands you may now use one the following
workflows for simple cherry-pick cases.
The first option (using labels).
* Add labels `backport/<release to backport to>` to the PR you want to
backport (e.g for backporting to versions 2.11 and 3.2 add labels
`backport/3.2` and `backport/2.11`).
* Merge the original pull request.
* Merge the automatically created Pull requests by GitHub-actions bot.
The second option (using command).
* Merge the original pull request.
* Write `/backport <releases to backport to list separated by space...>`
comment (e.g. `/backport 3.2 3.3`).
* Merge the automatically created Pull requests by GitHub-actions bot.
The bot creates a pull request from
`backport/${target …
> ci: add action for automatic backporting

- src/lib/core/say.c
- src/lib/core/say.h
- src/lua/utils.c
This patch refactors the panic macro into a function to prevent preprocessor conflicts. Previously, the panic macro in `src/lib/core/say.h` could clash with LuaJIT's internal panic routine, causing macro expansion issues and compilation failures. By using a function instead, the patch resolves these conflicts and ensures correct handling of panic calls.
Closes #5365
> say: replace panic macro with a function

- test/app-luatest/gh_7000_compat_module_test.lua
The original test use global variables that altered during testcase execution. Moreover, testcases were depend on global state changed previous testcases. This leads to a flaky behaviour. The patch add a hook `g.before_each` that set global options to `false` before running each testcase, remove calling `test_options_calls` in testcase `g.test_call` because this testcase does not set options to a `true`. Also, the patch fixes formatting for a table.
Follows up commit 25a979a1abd4
("test: fix app-luatest/gh_7000_compat_module_test.lua").
Follows up #7000
NO_DOC=testing
> test: fix flakiness in gh_7000_compat_module_test

- .github/workflows/backport.yml
This patch makes backport workflow use TarantoolBot for creating backport PRs and leaving comments.
After merging tarantool#11040 with `backport/3.3` label the backport PR tarantool#11041 didn't fire CI. Turns out that workflows can't be triggered by the GitHub actions bot [^1]. This patch makes the action use TarantoolBot for creating PRs to start CI automatically.
Also, the comments on backporting are now made by TarantoolBot too just for consistency.
[^1] https://github.com/orgs/community/discussions/25786
> ci: use TarantoolBot for backporting

- src/box/vy_run.c
Just add missing `vy_page_delete()` to `vy_slice_stream_search()`.
The error is very unlikely to happen because:
- `vy_slice_stream_search()` is called only once during a compaction task execution.
- Memory leaks if `vy_page_find_key()` fails to decode a statement. Practically, this can only occur on memory allocation error. In tests it's triggered by an error injection.
Closes #11044
> vinyl: fix memory leak on error decoding row during compaction

- changelogs/unreleased/gh_9871_sequence_data_recovery_after_reset.md
- src/box/box.cc
- src/box/request.c
- test/engine-luatest/gh_9871_sequence_restart_after_reset_test.lua
There are two sources of sequence state in tarantool: `_sequence_data` table and it's light version used in `box/sequence.c` which is stored in a hashmap. The reason for this decision was lack of cross-engine transactions. The first is used in lua API, the second -- internally to process memtx index updates. Now lua `reset()` call always produce WAL entry and we don't rely on memtx tables content during the initial recovery since the latest hasmap state is stored into snapshot directly.
Fixes #9871
NO_DOC=bugfix
> box.sequence: sequence_data recovery after reset

- changelogs/unreleased/gh-10709-luajit-fixes.md
* Fix compilation of getmetatable() for UDTYPE_IO_FILE
* Ensure full init of IR_NOP instructions.
* cmake: run tests with Valgrind
* ci: add Valgrind testing workflow
* x86/x64: Don't fuse loads across table.clear.
* Improve last commit.
* x86/x64: Don't fuse loads across IR_NEWREF.
* Fix last commit.
* Cleanup CPU detection and tuning for old CPUs.
* Disable FMA by default. Use -Ofma or jit.opt.start("+fma") to enable.
* x86/x64: Add more red zone checks to assembler backend.
* Prevent loop in snap_usedef().
* FFI: Add missing coercion when recording 64-bit bit.*().
* Fix command-line argv handling.
* Fix predict_next() in parser (for real now).
Closes #10709
> [backport/release/3.3] luajit: bump new version

- changelogs/unreleased/gh-10709-luajit-fixes.md
* Fix compilation of getmetatable() for UDTYPE_IO_FILE
* Ensure full init of IR_NOP instructions.
* cmake: run tests with Valgrind
* ci: add Valgrind testing workflow
* x86/x64: Don't fuse loads across table.clear.
* Improve last commit.
* x86/x64: Don't fuse loads across IR_NEWREF.
* Fix last commit.
* Cleanup CPU detection and tuning for old CPUs.
* Disable FMA by default. Use -Ofma or jit.opt.start("+fma") to enable.
* x86/x64: Add more red zone checks to assembler backend.
* Prevent loop in snap_usedef().
* FFI: Add missing coercion when recording 64-bit bit.*().
* Fix command-line argv handling.
* Fix predict_next() in parser (for real now).
Closes #10709
> [backport/release/3.2] luajit: bump new version

- .github/workflows/fuzzing.yml
- The path `test/static/corpus/**` is gone in the commit b24328cd57b7 ("test/static: replace seed corpus with repository").
- The paths `third_party/c-dt` and `third_party/tz` are affected by datetime fuzzing tests `datetime_parse_full_fuzzer` and `datetime_strptime_fuzzer`.
- The path `third_party/decNumber` is affected by fuzzing test `decimal_to_int64_fuzzer`.
- The path `third_party/luajit` is affected by fuzzing test `luaL_loadbuffer_fuzzer`.
- The path `cmake` contains CMake modules for third party components and also `cmake/BuildLuaTests.cmake` that builds additional fuzzing tests maintained in external repository.
NO_DOC=ci
NO_TEST=ci
> ci: update path whitelist in a fuzzing workflow

- changelogs/unreleased/gh-11062-net-box-fetch-schema-restart-fix.md
- src/box/lua/net_box.c
- test/box-luatest/gh_11062_net_box_fetch_schema_restart_test.lua
If the remote schema changes while the client is fetching it, it will restart the procedure. This effectively abandons the requests issued in the previous attempt to fetch the schema. The server will still reply to them though - when this happens, the client will subtract the counter of in-progress requests, underflowing it, because these requests were never accounted in the first place.
In case of a debug build, this bug results in a client crash due to an assertion failure. In case of a release build, the client doesn't crash, but the server will hang on shutdown because the counter is used for implementing the graceful shutdown protocol.
Let's fix this issue by accounting these abandoned requests when we restart fetching the remote schema.
Closes #11062
> netbox: fix in-progress request counter underflow during schema fetch

- changelogs/unreleased/config-failover-section-in-global-scope.md
- src/box/lua/config/instance_config.lua
- src/box/lua/config/validators.lua
- test/config-luatest/cluster_config_schema_test.lua
This patch adds validation on the scope of the `failover` section in the instance configuration. This section configures a EE-only supervised failover and it should be configured only in the global configuration scope. This patch implements this restriction.
It's already documented. Only the check hasn't been implemented yet.
> config: allow failover only in the global scope

- changelogs/unreleased/gh-10715-memtx-mvcc-conflict-with-prepared-sysview-txn.md
- src/box/memtx_engine.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- src/box/txn.c
- test/box-luatest/gh_10715_memtx_mvcc_conflict_with_prepared_sysview_txn_test.lua
We have a special `sysview` engine that bypasses transaction management and reads right from memtx indexes. The problem is memtx indexes use memtx MVCC by themselves, so despite `sysview` bypasses transaction management process, it actually uses memtx MVCC. So the problem here is that transaction can actually read something using `sysview`, a tracker in MVCC will be allocated, but `txn->engine[memtx->id]` still will be `NULL`, so the preparation of the transaction won't be finalized by memtx_tx and the tracker won't be deleted when transaction is prepared. On conflict, MVCC will try to abort that already prepared transaction and it will lead to a crash.
Actually, crashing scenarios are rather synthetic and break only our engine fuzzer. Here is an example of such scenario without manual …
> memtx: finalize prepare of all transactions in memtx MVCC

- changelogs/unreleased/gh-11081-fix-wal-queue-size-accounting.md
- src/box/journal.h
- test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua
If cascade rollback is in progress any new write to WAL will be accounted in queue size forever. Eventually queue size will become larger then threshold forever and writing to WAL will be blocked.
Closes #11081
> box: fix WAL queue size accounting on errors

- test/engine/errinj_ddl.result
- test/engine/errinj_ddl.test.lua
- test/engine/suite.ini
The test relied on fibers finishing execution in particular order and setting/unsetting error injections in time. Of course it was flaky. In all the 3 flaky cases the fiber unsetting the injection could be executed before the fiber which sets the injection, and the rest of the test would run with that injection being set.
Fix this properly and remove the test from the fragile list.
Closes tarantool/tarantool-qa#20
NO_CHANGELOG=flaky test
NO_DOC=flaky test
> test: stabilize engine/errinj_ddl test

- test/replication/suite.ini
- test/replication/sync.result
- test/replication/sync.test.lua
When replication is restarted with the same replica, there's a chance that an old relay may be not stopped yet when a new applier connects. In this case the applier should get ER_CFG error and it should continue trying to sync with master.
The test stopped the relay from exiting with slowing sending of the rows. This is not reliable and sometimes relay successfully exited before replica tried to connect, which leads to the absence of the ER_CFG error. Let's block relay exit with ERRINJ_RELAY_EXIT_DELAY instead, which is much more reliable.
Closes tarantool/tarantool-qa#6
Closes #4129
NO_CHANGELOG=flaky test
NO_DOC=flaky test
> test: stabilize replication/sync test

- changelogs/unreleased/config-failover-section-in-global-scope.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
*(This PR is a backport of #11072 to `release/3.3` to a future `3.3.2` release.)*
---
This patch adds validation on the scope of the `failover` section in the instance configuration. This section configures a EE-only supervised failover and it should be configured only in the global configuration scope. This patch implements this restriction.
(cherry picked from commit f63a8dad657a66db51dc44eb3b0318cf90dd1d89)
> [backport 3.3] config: allow failover only in the global scope

- changelogs/unreleased/config-failover-section-in-global-scope.md
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
*(This PR is a backport of #11072 to `release/3.2` to a future `3.2.2` release.)*
---
This patch adds validation on the scope of the `failover` section in the instance configuration. This section configures a EE-only supervised failover and it should be configured only in the global configuration scope. This patch implements this restriction.
(cherry picked from commit f63a8dad657a66db51dc44eb3b0318cf90dd1d89)
> [backport 3.2] config: allow failover only in the global scope

- changelogs/unreleased/gh-11088-vy-tx-crash-on-timeout-fix.md
- src/box/txn.c
- test/vinyl-luatest/gh_11088_tx_abort_on_timeout_test.lua
The transaction timeout may be triggered by vinyl taking too long to read disk while executing a statement. If we roll back the transaction in this case, the statement will be deleted, resulting in a crash when we finally try to commit the statement. Actually, in contrast to the case when a transaction is aborted by a fiber yield, there's no need to rollback the transaction on timeout  We don't rollback the transaction on conflict so let's not do it on timeout, either.
Closes #11088
> txn: do not rollback transaction statements on timeout

- test/replication/suite.ini
- test/replication/sync.result
- test/replication/sync.test.lua
When replication is restarted with the same replica, there's a chance that an old relay may be not stopped yet when a new applier connects. In this case the applier should get ER_CFG error and it should continue trying to sync with master.
The test stopped the relay from exiting with slowing sending of the rows. This is not reliable and sometimes relay successfully exited before replica tried to connect, which leads to the absence of the ER_CFG error. Let's block relay exit with ERRINJ_RELAY_EXIT_DELAY instead, which is much more reliable.
Closes tarantool/tarantool-qa#6
Closes #4129
NO_CHANGELOG=flaky test
NO_DOC=flaky test
(cherry picked from commit e0c6126742e1ba9016f8dcb5b749210f6020e9a7)
> [backport 2.11] test: stabilize replication/sync test

- changelogs/unreleased/gh-10918-fix-log-message-truncate.md
- src/lib/core/say.c
- src/lib/core/util.c
- src/trivia/util.h
- test/app-tap/logger.test.lua
Before this patch, when log format was set to 'json' and log entry was written with format-string API (`require('log').info(<format string>, args...)`), in the output the message was truncated to 1024 bytes.
This patch fixes this behavior, and now the message will only be truncated if the full log entry (with all the context) doesn't fit into the 16KiB buffer. The message will be truncated in a way, so all the context is present.
Closes #10918
NO_DOC=bugfix
> log: fix truncating log message to 1024 bytes in 'json' log

- changelogs/unreleased/gh-10918-fix-log-message-truncate.md
- src/lib/core/say.c
- src/lib/core/util.c
- src/trivia/util.h
- test/app-tap/logger.test.lua
*(This PR is a backport of #10952 to `release/2.11` to a future `2.11.6` release.)*
----
Before this patch, when log format was set to 'json' and log entry was written with format-string API (`require('log').info(<format string>, args...)`), in the output the message was truncated to 1024 bytes.
This patch fixes this behavior, and now the message will only be truncated if the full log entry (with all the context) doesn't fit into the 16KiB buffer. The message will be truncated in a way, so all the context is present.
Closes #10918
NO_DOC=bugfix
> [backport 2.11] log: fix truncating log message to 1024 bytes in 'json' log

- perf/bps_tree.cc
Clang warned about the getting the offset of a field in a structure
with a non-standard layout because of a `std::unique_ptr` field in
the `DummyAllocator` class. Let's simply replace it with a regular
pointer.
Closes #11122
NO_DOC=minor
NO_TEST=minor
> perf: fix a clang warning for BPS tree perftest

- changelogs/unreleased/gh-11079-vy-cache-read-view-fix.md
- src/box/vinyl.c
- src/box/vy_cache.c
- src/box/vy_cache.h
- src/box/vy_lsm.c
- src/box/vy_point_lookup.c
- src/box/vy_point_lookup.h
- src/box/vy_read_iterator.c
- src/box/vy_read_iterator.h
- src/box/vy_stmt.h
- test/unit/vy_iterators_helper.c
- test/unit/vy_point_lookup.c
- test/vinyl-luatest/gh_11079_invisible_delete_caching_test.lua
- test/vinyl/cache.result
- test/vinyl/deferred_delete.result
- test/vinyl/deferred_delete.test.lua
- test/vinyl/stat.result
This commit fixes a few issues in the tuple cache when a transaction operating in a read view could skip tuples deleted after the read view was created.
Closes #11079
> vinyl: fix cache read view

- changelogs/unreleased/gh-11091-synchro-queue-is-unlimited-after-local-recovery.md
- src/box/box.cc
- test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua
Fixed a bug when the synchronous queue size limit was not enabled after a local reсvery, i.e. its size was not limited by `replication_synchro_queue_max_size`.
Closes #11091
NO_DOC=bugfix
> relay: fix synchro queue limitation after a local recovery

- .github/workflows/ubuntu_24_04.yml
- .github/workflows/ubuntu_24_04_aarch64.yml
- changelogs/unreleased/add-ubuntu-noble.md
Copy workflow files for Ubuntu Jammy (22.04) with replacing `22.04` -> `24.04` and `jammy` -> `noble`.
<details>
<summary><code>diff -u .github/workflows/ubuntu_{22_04,24_04}.yml</code></summary>
```diff
--- .github/workflows/ubuntu_22_04.yml
+++ .github/workflows/ubuntu_24_04.yml
@@ -1,4 +1,4 @@
-name: ubuntu_22_04
+name: ubuntu_24_04
on:
push:
@@ -31,7 +31,7 @@
cancel-in-progress: true
jobs:
-  ubuntu_22_04:
+  ubuntu_24_04:
if: github.repository == 'tarantool/tarantool' &&
@@ -59,7 +59,7 @@
env:
RWS_AUTH: ${{ secrets.RWS_AUTH }}
OS: 'ubuntu'
-          DIST: 'jammy'
+          DIST: 'noble'
GC64: ${{ matrix.build-type == 'gc64' }}
uses: ./.github/actions/pack-and-deploy
- name: Send VK Teams message on failure
@@ -71,7 +71,7 @@
uses: actions/upload-artifact@v4
if: failure()
with:
- …
```
> ci: deploy Ubuntu Noble (24.04) packages

- test/config-luatest/iproto_listen_test.lua
If `iproto.listen` is removed, it should be set to its default value (`nil`) that means to don't listen on any port.
> config: add test for iproto.listen removal

- changelogs/unreleased/gh-11140-vy-deferred-delete-rollback-fix.md
- src/box/vy_read_iterator.c
- test/vinyl-luatest/gh_11140_deferred_delete_rollback_test.lua
While scanning a non-unique secondary index of a vinyl space, we skip a tuple if there's no match for it in the primary index because it means that the tuple was overwritten by a newer statement but the secondary index DELETE was deferred until compaction. We still create a cache chain link in this case so that we skip the overwritten tuple when we scan the secondary index next time. We do it even if the overwriting statement is unconfirmed (not yet written to WAL), which is actually incorrect. The problem is that if the overwriting statement is rolled back on a WAL write error, the chain created in the secondary index cache won't be broken because nothing was actually written to the secondary index (DELETE was deferred) therefore there's nothing to roll back therefore there's nothing to …
> vinyl: don't create cache chain over unconfirmed deferred DELETE

- src/box/vy_lsm.c
To force compaction, `index:compact()` sets the `needs_compaction` flag on all ranges of the target LSM tree. When a range is split, the new ranges inherit this flag. The problem is that there's a yield caused by `vy_log_tx_commit()` between setting the flag in `vy_lsm_split_range()` and adding the new ranges to the LSM tree. If `vinyl_index_compact()` is called while `vy_lsm_split_range()` is waiting for `vy_log_tx_commit()` to complete, the `needs_compaction` flag will be set for the old range but not for the new ranges hence compaction won't be triggered for them. This breaks assumptions made by some tests (`select_consistency_test`, for example).
Fix this issue by setting the needs_compaction flag right before modifying the LSM tree, after the vylog record is committed.
Note that …
> vinyl: fix race between manual compaction and range splitting

- changelogs/unreleased/gh-10132-full-mp_int-support-sql.md
- src/box/sql/func.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/box/sql/vdbe.c
- src/box/sql/vdbeapi.c
- src/box/sql/vdbeaux.c
- test/sql-luatest/CMakeLists.txt
- test/sql-luatest/gh_10132_mp_int_bugs.c
- test/sql-luatest/gh_10132_mp_int_bugs_test.lua
Same as in #9965, some places in SQL treated `MP_INT` as always negative. Luckily, it didn't affect the stored files and hashes.
See #10132.
> Fix `MP_INT` misusage in SQL

- changelogs/unreleased/gh-11163-vy-incomplete-run-gc-fix.md
- src/box/vinyl.c
- src/box/vy_scheduler.c
- test/vinyl-luatest/gh_11163_gc_while_compaction_in_progress_test.lua
A space may be dropped while it's being compacted. The vinyl garbage collector purges all run files left after a dropped space, including `.run.inprogress` and `.index.inprogress` files currently being written by compaction tasks. As a result, when a compaction task is completed, it may fail to rename the new run file with a `ENOENT` error:
```
vinyl.compaction.0/102/task xlog.c:800 !> can't rename ./512/0/00000000000000000006.index.inprogress to ./512/0/00000000000000000006.index: No such file or directory
```
This bug has another effect. If the compaction starts writing the file after the garbage collector purges meta-information about it from vylog, the run file will be successfully written but never committed to vylog. As a result, it will never be deleted.
Let's fix this issue by …
> vinyl: fix gc of incomplete runs left after dropped space

- changelogs/unreleased/gh-10132-full-mp_int-support-sql.md
- src/box/sql/func.c
- src/box/sql/mem.c
- src/box/sql/mem.h
- src/box/sql/vdbe.c
- src/box/sql/vdbeapi.c
- src/box/sql/vdbeaux.c
- test/sql-luatest/CMakeLists.txt
- test/sql-luatest/gh_10132_mp_int_bugs.c
- test/sql-luatest/gh_10132_mp_int_bugs_test.lua
> [backport 3.3] Fix `MP_INT` misusage in SQL

- .github/workflows/downgrade_versions.yml
- tools/check-downgrade-versions.sh
There is a CI workflow that verifies correctness of the list of versions to where the downgrade is possible, see commit 6d8563472785 ("ci: add workflow to check downgrade versions").
However, this check is run only on push of a tag that marks the new release. It is too late, because other CI workflows that deploy source tarball and built packages are run by pushing this tag too. The uploads are already in-progress or done, when a human sees that the downgrade list check fails.
Let's add another criteria to run the check:
* the commit is `X.Y.Z-entrypoint-<...>`, and
* there is the `changelogs/X.Y.Z.md` file.
This way we can catch the problem while preparing the release notes, *before the release*.
Follows up #8319
> ci: verify the downgrade list before the release

- .github/workflows/source.yml
The new AWS CLI version (v2.23.0) enables an integrity protection mechanism by default. It is incompatible with VK Cloud that we use for storing source tarballs. The commit changes the source tarball uploading job to install AWS CLI v2.22.35, the last tool version, where the feature is disabled by default.
See https://github.com/aws/aws-cli/issues/9214 for details.
The source uploading job uses GitHub hosted runners with the `runs-on: ubuntu-22.04` directive. This environment has AWS CLI v2.24.0 preinstalled (see [here](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#cli-tools)).
Note: The `config_jsonschema_check.yml` workflow also uses AWS CLI, but it is a container job with fixed packages versions. It is not affected by the given problem.
> ci: use AWS CLI v2.22.35

- src/box/alter.cc
- src/box/index_def.c
- src/box/index_def.h
- src/box/lua/schema.lua
- src/box/lua/space.cc
- src/box/memtx_space.c
- src/box/vinyl.c
- src/trivia/util.h
- test/box-luatest/index_covers_test.lua
It is intended to be used by memcs engine to specify columns of the secondary index. Usage example: `space:create_index('sk', {parts = {2}, covers = {5, 7}}`.
Part of tarantool/tarantool-ee#893
Required for PR https://github.com/tarantool/tarantool-ee/pull/1129.
> box: introduce index covers option

- changelogs/unreleased/config-transform-composite-type.md
- src/box/lua/config/utils/schema.lua
- test/config-luatest/schema_test.lua
`<schema object>:map()` now calls the user-provided transformation function not only on scalar schema nodes, but also on `record`, `map` and `array` nodes. The function is called on the outmost node first, then on the descandant ones.
`<schema object>:apply_default()` now supports the `default` annotation (and the `apply_default_if` one) for composite types. Similarly to `:map()` it traverses the nodes in the pre-order way.
Fixes #10756
> config/schema: transform composite types in :map()

- src/box/lua/config/instance_config.lua
- src/box/lua/config/validators.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
This patchset revisits `replication.failover` and `sharding.*` scope validation code. It uses the computed annotations feature (see 4ddb9f21f6b6) to simplify these checks and reduces code duplication.
No functional changes except wording in validation failure messages.
> config: simplify scope validation code

- src/box/lua/config/applier/box_cfg.lua
The patchset splits the large apply() function in the `box_cfg` configuration applier into meaningful pieces. This way it is easier to navigate over this code.
> config: structurize applier/box_cfg

- src/box/txn.c
- src/box/txn.h
Without it we have to add on commit trigger just to destroy on rollback trigger in memcs and memtx index build.
Part of tarantool/tarantool-ee#893
Required for EE PR https://github.com/tarantool/tarantool-ee/pull/1153.
> box: call destroy callback for stmt on rollback trigger

- src/box/lua/tuple.c
- src/box/lua/tuple.lua
This refactoring allows us to fully take advantage of the JIT compiler for the indexing tuple by the given path. The most common cases of tuples containing strings or numbers are accessed 1.5-2.5 times faster. The drawback is the field contains the cdata from the msgpack extensions (like decimals). Their decoding still takes approximately the same time (maybe 5% slower).
NO_CHANGELOG=performance improvement
NO_DOC=performance improvement
NO_TEST=performance improvement
---
Depends on #11182.
Before the patch the trace related to the tuple indexing is stitched on the call to the `lbox_tuple_field_by_path()`.
The related part of the JIT dump:
```
0052       >  p32 HREFK  0051  "tuple_field_by_path" @15 ; internal.tuple.tuple_field_by_path
0053       >  fun HLOAD  0052
0054       >  fun EQ …
```
> lua: rewrite `tuple_field_by_path()` in FFI

- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/instance_config.lua
This is purely refactoring change: it eliminates code that was needed before the schema module began to support default values for schema nodes of composite types (see #10756). Now, we can just assign the defaults in the schema and it works as expected.
Follows up #10756
Follows up #10757
Follows up #10758
Follows up #10759
Follows up #11153
> config: remove tricks around non-scalar defaults

- changelogs/unreleased/gh-11249-vy-space-truncate-under-load-fix.md
- src/box/vy_tx.c
- test/engine-luatest/gh_11249_space_truncate_under_load_test.lua
Under the hood, `space:truncate()` calls `space_vtab::build_index` to notify the engine about index recreation, see `TruncateIndex::prepare`. `space_vtab::build_index` isn't supposed to yield in this case because the space is empty (note that `TruncateIndex::prepare` passes the new space to the callback). However, there's a bug in vinyl that makes this callback yield for no good reason, aborting `space:truncate()` with `ER_TRANSACTION_YIELD`.
The problem lies in `vy_tx_manager_abort_writers_for_ddl()`, which is called by `vinyl_space_build_index()` to abort all transactions that write to the target space. If a transaction can't be aborted because it has reached WAL, the function sets the `need_wal_sync` flag which indicates the caller that they should call `wal_sync()` to flush all …
> vinyl: fix space truncation being aborted by yield under load

- changelogs/unreleased/config-schema-unique-items.md
- src/box/lua/config/instance_config.lua
- src/box/lua/config/utils/schema.lua
- src/box/lua/config/validators.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
- test/config-luatest/schema_test.lua
Now, the `experimental.config.utils.schema` module has the `unique_items` annotation taken into account by the `<schema object>:validate()` method.
The annotation can be assigned to a schema node that represents an array of strings. An attempt to assign it to another schema node leads to an error on the schema object creation (`schema.new()`).
The `<schema object>:validate()` method now raises an error if the `unique_items` annotation is assigned and truthly, but the corresponding value (an array) contains the same string two or more times.
The `schema.set()` constructor (creates an array with enumerated values without duplicates) now assigns the `unique_items` annotation to the created schema node instead of defining its own `validate` annotation.
The `schema.set()` constructor now …
> config/schema: support `unique_items` annotation

- tools/gen-release-notes
The given template comes from the time, when we had 1.10 and 2.x with the old release policy (see https://github.com/orgs/tarantool/discussions/6182). In fact, almost every aspect of this template is obsolete now.
For example, we have no stable and non-stable releases anymore: there are pre-releases (marked with alpha, beta, rc keywords) and releases. We don't need to say explicitly that the given release is stable.
Also, 1.10 is not LTS anymore (it is EOL) and 2.11 is not the latest series.
The links needs an update too.
So, I decided to write these templates from scratch, but keep the idea: give some release status information, highlight notable changes (for feature releases), provide a few hints about the update procedure.
----
Resulting templates are below.
```markdown
Tarantool 3.x …
```
> tools: update release notes template

- changelogs/unreleased/gh-10842-learners-not-bootstrap-leaders.md
- src/box/lua/config/applier/box_cfg.lua
- src/box/lua/config/configdata.lua
- test/config-luatest/failover_learners_test.lua
This patch makes Tarantool configured in `replication.failover =
'supervised'` mode not choose instances marked as learners for the
failover coordinator as a bootstrap leader.
Marking instance as a learner means it shouldn't be appointed as a
master by the failover. Thus, the user would expect for the learners not
to become RW during the bootstrap too.
Example.
```yaml
replication:
failover: supervised
failover:
replicasets:
r-001:
learners:
- i-001
groups:
g-001:
replicasets:
r-001:
instances:
i-001: {}
i-002: {}
```
`i-002` will be chosen as a replicaset bootstrap leader.
If all non-anonymous instances are marked as learners the initial
cluster bootstrap fails since every instance starts in RO and none
of them might become the leader.
If user applies a config where all non-anonymous …
> config: don't choose learners as bootstrap leaders

- changelogs/unreleased/gh-10795-role-stop-on-shutdown.md
- src/box/lua/config/applier/roles.lua
- test/config-luatest/roles_test.lua
This commit makes it so the `stop` callbacks are called for all registered roles, in the reverse order of roles startup.
Closed #10795
Closes TNTP-667
Title: roles are stopped on graceful shutdown
From now on during the graceful shutdown process `stop` callback for all registered roles are called in the reverse order of roles startup.
> config: call roles `stop` callback on shutdown

- changelogs/unreleased/gh-11078-handle-cancel-of-request-in-wal-queue.md
- src/box/applier.cc
- src/box/box.cc
- src/box/journal.c
- src/box/journal.h
- src/box/txn.c
- src/box/txn.h
- src/box/txn_limbo.h
- src/box/wal.c
- test/box-luatest/gh_11078_wal_queue_fiber_cancel_test.lua
Currently if fiber waiting in wal queue is cancelled it will go on writing to all breaking queue order. So wal is corrupted so that even next Tarantool restart may fail. Unfortunately we cancel fibers on Tarantool shutdown so the issue may arise just buy terminating Tarantool instance.
Let's instead fail the cancelled request and all the newer request in the queue.
Work around is to disable wal queue by `box.cfg{wal_queue_max_size = 0}` so that only one write request can be in the queue.
Closes #11078
> [!NOTE]
> We have to cherry-pick additionally 2 commits that refactor journal and txn.
> [backport 2.11] box: handle cancelling fiber waiting in wal queue

- src/box/xrow.c
The old (7.5.0) GCC compiler leaves the following compilation warning (leading to the error with `-Werror`):
NO_WRAP
```
src/box/xrow.c: In function ‘xrow_decode_call’:
src/box/xrow.c:1616:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
request->tuple_formats_end = data;
~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
src/box/xrow.c:1617:3: note: here
default:
^~~~~~~
cc1: all warnings being treated as errors
```
NO_WRAP
The missing statement is harmless since the `default` just does the same thing, but to fix the error for old compilers and make the code cleaner, the missing statement is added in this patch.
NO_DOC=cleanup
NO_TEST=cleanup
NO_CHANGELOG=cleanup
> xrow: add missing break statement

- changelogs/unreleased/gh-11288-enabled-roles-api.md
- src/box/lua/config/init.lua
- test/config-luatest/roles_test.lua
- test/config-luatest/vshard_test.lua
config: add API to test if role is set for instance
New `has_role`, `is_router` and `is_storage` methods added to the config
module.
Closes #11288
Closes TNTP-969
Title: config module `has_role`, `is_router` and `is_storage` methods
`has_role(<role_name>, {instance = <instance_name})` returns true if
the instance with the name <instance_name> has role <role_name> enabled
in the current config, false if not. Second argument is optional, and
if not provided the check will be done for the instance the method is
called on.
`is_router({instance = <instance_name})` returns true if the instance
with name <instance_name> is a vshard router, according to the current
config, false if not. Argument is optional, and if not provided the
check will be done for the instance the …
> config: add API to test if role is set for instance

- changelogs/unreleased/lua-call-runtime-priv-before-bootstrap.md
- src/box/lua/config/init.lua
- test/config-luatest/runtime_priv_test.lua
This patch is a bugfix of the `lua_call` runtime access implemented in
commit 38c6b0d38254 ("config: grant runtime access to lua_call from
config").
One of the main reason for runtime privileges is to allow granting guest
user `lua_call` access before the initial bootstrap. During the
implementation of the #10857 in terms of the new behavior of the
supervised failover with the supervised bootstrap strategy it turned out
runtime privileges haven't been added as a first-phase applier making it
impossible to executing some of the lua functions before the initial
bootstrap. This patch fixes it by adding a first-phase applier.
For instance, you might allow guest connection to fetch information on
instances before the bootstrap by configuring `credentials` section like
this.
```yaml …
```
> config: apply lua_call privileges before bootstrap

- changelogs/unreleased/gh-11079-vy-cache-read-view-fix.md
- src/box/vy_cache.c
- test/vinyl-luatest/gh_11079_invisible_delete_caching_test.lua
Since commit e8109b2fe0b3 ("vinyl: ignore cache chains with invisible DELETEs") each cache node stores the LSNs of the left and right links. They are used to ignore links that are invisible from the current read view (created after the read view was opened). We update the LSN not only when we link two nodes together but also when we update the node's boundary level. This is incorrect if the node is linked.
For example, suppose we have an index over two fields that contains tuples {0,2} and {2,0} and there's a transaction that was sent to a read view. Now another transaction inserts {0,1} and deletes {0,2}, then selects all tuples. This results in creation of two interlinked cache nodes: {0,1} and {2,0}. The link is invisible from the read view: since we skipped DELETE{0,2}, its LSN equals …
> vinyl: do not reset cache link LSN on partial key lookup

- changelogs/unreleased/gh-9820-checkpoint-interval-after-restart.md
- src/box/checkpoint_schedule.c
- src/box/checkpoint_schedule.h
- src/box/gc.c
- src/box/gc.h
- src/box/memtx_engine.cc
- test/box-luatest/gh_9820_checkpoint_interval_after_restart_test.lua
- test/unit/checkpoint_schedule.c
Introduce the `timestamp` field in `gc_checkpoint` so now `gc.{c,h}` are aware of actual times of checkpoints, which is important since this subsystem is responsible for scheduling. Now, one can track the unix time of a new checkpoint with new `timestamp` argument of `gc_add_checkpoint`. This change allows us to track previous checkpoints made before the server restart and even `checkpoint_interval` value reconfiguring.
This approach was chosen instead of just scanning the `snap_dir` in `gc.c` because it was engine-independent. One may also notice that even if the actual time after the last snapshot before the restart is greater than `2 * checkpoint_interval` we won't start checkpointing immediately because that may cause high disk load in case of multiple instances. So in this case we …
> gc: use *.snap st_mtime to schedule after restart

- changelogs/unreleased/gh-9811-checkpoint-wal-threshold-after-restart.md
- src/box/box.cc
- src/box/wal.c
- src/box/wal.h
- test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua
During the `checkpoint_wal_threshold` exceedance checks tarantool used to ignore the sizes of files created prior to the server restart which resulted in cases when the server didn't create any checkpoints and generate a huge amount of logs which were replayed each server restart. Now the `wal_dir` is scanned for proper `writer->checkpoint_wal_size` calculation after the recovery process.
Fixes #9811
NO_DOC=bugfix
> wal: use existing logs sizes after restart

- changelogs/unreleased/gh-11179-wal-queue-rollback.md
- src/box/journal.c
- src/box/journal.h
- src/box/wal.c
- test/box-luatest/gh_11179_wal_queue_rollback_test.lua
In case of WAL error we should rollback txns in WAL queue before any in-flight txns (already submitted to WAL thread).
Work around is to disable WAL queue by `box.cfg{wal_queue_max_size = 0}` so that no request can be queued.
Closes #11179
> box: rollback txns in WAL queue before in-flight tnxs

- src/box/iproto_features.h
Currently, the only way to find the IPROTO protocol version where a particular feature first appeared is to read the Git history, which is inconvenient. Let's add this information to comments.
> iproto: add min version to feature comments

- src/box/box.cc
- src/box/gc.c
- test/box-luatest/ghs_135_check_iterator_when_loading_gc_consumers_test.lua
We load WAL GC consumers right after recovery - it is done by iterating over space `_gc_consumers`. However, we forgot to check if the iterator is successfully created, hence, in the case of OOM right after recovery, Tarantool will crash because iterator is NULL. The commit adds the check. Along the way, let's log an explanatory message when we fail to load consumers to make the problem clear. Also, this message will allow us to write a more stable test.
Closes tarantool/security#135
> box: check if iterator was created when loading WAL GC consumers

- src/lib/core/errinj.h
- src/lib/core/say.c
- src/main.cc
- test/app-luatest/gh_11323_write_to_stderr_at_exit_test.lua
We must not close stderr because it's used for reporting crashes and memory leaks, but if the logger is configured to log to stderr, it's closed at exit. Let's fix it.
While we are at it, let's also remove usage of `pm_atomic_store()` and `pm_atomic_load()` for updating `log::type` because it makes no sense.
The bug was introduced by commit 6d7437dae2dfc ("say: Add several loggers support").
Close #11323
> say: do not close stderr at exit

- changelogs/unreleased/gh-11118-flush-journal-on-wal-sync.md
- src/box/box.cc
- src/box/wal.c
- test/box-luatest/gh_11118_flush_journal_on_wal_sync_test.lua
`wal_sync()` is expected to flush all prepared txns on disk. Currently it is not so because we do not flush txns waiting in WAL queue. AFAIU the issue exists for all the places where we use `wal_sync()` (except for `box_wait_limbo_acked()` where we already flush WAL queue). The test is only added for the vinyl index build as there are explicit tickets for that.
Closes #11118
Closes #11119
> box: flush WAL queue on sync

- changelogs/unreleased/gh-9920-tx-with-dead-relay.md
- src/box/relay.cc
- src/lib/core/errinj.h
- test/replication-luatest/gh_9920_tx_with_dead_relay_test.lua
In relay there's a message, which travels between relay and tx threads and which is used to deliver vclock of the relay to tx thread.
However, when the message is in tx thread, it may happen, that relay thread dies and tx may try to send message back without checking, whether the thread is alive.
Let's check `is_paired` flag, which is set to `false`, when relay thread dies, before sending the cbus message.
Closes #9920
> relay: fix crash during shut down

- src/box/alter.cc
- src/box/errcode.h
- test/box/error.result
This is a backport of #11317 to a future `3.3.2` release.
> [backport 3.3] Refactoring needed for banning change of indexed fields by space upgrade

- changelogs/unreleased/change-er-invalid-dec-errcode.md
- src/box/alter.cc
- src/box/errcode.h
- test/box/error.result
This is a backport of https://github.com/tarantool/tarantool/pull/11317 to a future 2.11.7 release.
Along the way we fix a wrong error code being assigned to `ER_INVALID_DEC` error during its backport to 2.11.
> [backport 2.11] Refactoring needed for banning change of indexed fields by space upgrade

- changelogs/unreleased/gh-11326-fix-crash-on-insertion-on-oom.md
- src/lib/salad/bps_tree.h
- test/unit/bps_tree.cc
On insertion into bps tree we first reserve blocks for the case we need to insert new leaf during rebalancing. Next there can be a free block on last extent in matras but no more free extents in tuple arena. So `bps_tree_reserve_blocks()` is able to allocate a block but then `bps_tree_garbage_push()` is called that touches a block. As there no free extents touch is failed which is unexpected and causes a crash.
We don't need to touch the block on this path as block is newly allocated and is not shared with any read view. We don't need to touch block on other paths too (disposing a leaf or a inner node) because we move data from this node before so it is already should be touched.
So just don't touch the block in `bps_tree_garbage_push()`.
The issue is introduced in the commit 51c56d9b3319 …
> salad: fix crash on insertion into bps tree with OOM conditions

- .gitmodules
New commits:
- fix: Fix potential integer overflows
- fix: Fix issues found by a static analyzer
Closes tarantool/security#138
> third_party: switch `nanoarrow` to the forked version

- src/box/index.cc
- src/box/index.h
- src/box/memtx_bitset.cc
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/read_view.c
- src/box/read_view.h
- src/box/sequence.c
- src/box/session_settings.c
- src/box/sysview.c
- src/box/vinyl.c
Currently, these methods are implemented only by memcs (available in EE only) so we don't really need to make them virtual. In future, however, we're planning to introduce a new column store engine, which will export the arrow API, too.
EE part: https://github.com/tarantool/tarantool-ee/pull/1203
> index: add virtual methods for creating arrow streams

- src/box/index_def.c
It's not safe to use `strlcpy()` for non-null-terminated strings, because this function requires a null-terminated string. Found by AddressSanitizer.
> box: fix out-of-bounds read in `index_opts_parse_layout()`

- .luacheckrc
- changelogs/unreleased/gh-10182-add-ability-to-run-code-before-box-cfg.md
- src/box/lua/config/applier/app.lua
- src/box/lua/config/applier/roles.lua
- src/box/lua/config/init.lua
- src/box/lua/config/utils/file.lua
- test/config-luatest/appliers_test.lua
- test/config-luatest/gh_10182_roles_before_box_cfg_test.lua
- test/config-luatest/metadata_test.lua
config: add ability to run code before box.cfg
This commit adds 'metadata' support for roles and app scripts.
Currently only 'early_load' tag is supported. If this 'early_load'
tag is set to `true` for a role or a script, this role or script will
be loaded before the execution of `box.cfg` by the config module.
Closes #10182
Closes TNTP-227
Title: roles and scripts metadata
Metadata can be specified for roles and scripts (module or file in `app`
config section) in lua files. To add metadata to a source file, a
comment must be added to the beginning of the file (or after a shebang).
The metadata comment must contain a YAML-formatted section begging with
'--- #tarantool.metadata.v1' line and ending with '...' line. Example:
```lua
-- This script will be loaded before …
```
> config: add ability to run code before box.cfg

- changelogs/unreleased/gh-11053-gc_consumers-record-lost-after-promote-and-restart.md
- src/box/box.cc
- src/box/txn.c
- src/box/txn.h
- test/replication-luatest/gh_11053_gc_consumer_record_lost_after_promote_and_restart_test.lua
This patchset fixes a bug with `TXN_FORCE_ASYNC` transactions being lost after receiving a promote request from another instance and restarting the current instance.
Closes #11053
> box: set TXN_WAIT_SYNC with xrow rather than limbo state during recovery

- changelogs/unreleased/gh-11224-fix-commit-wait-none-yield.md
- src/box/journal.c
- src/box/journal.h
- src/box/txn.c
- test/box-luatest/gh_11224_fix_commit_wait_none_journal_queue_test.lua
The issue is in order to decide whether submitting request to journal would yield or not we check the journal queue size. But the size can be less then limit while queue is not empty. At this moment submitting new request will yield.
Closes #11224
> box: fix box.commit({wait = 'none'}) could yield

- changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
- src/box/memtx_space.c
- test/box-luatest/gh_4348_transactional_ddl_test.lua
- test/box-luatest/memtx_mvcc_unsupported_features_test.lua
Memtx MVCC does not support multikey indexes, but allows to use them. If one will use them, Tarantool is most likely to crash, and that's the best scenario - otherwise Tarantool will work, but something terribly wrong will be happening under the hood. Let's simply forbid to create such indexes along with MVCC until we support them.
In addition to that, the commit forbids to create functional indexes along with memtx MVCC enabled since target Tarantool version for this commit does not support them completely.
Workaround for #6385
Workaround for #11099
NO_DOC=backport
(cherry picked from commit ae067afb6f45e65913c2996bdedb752d14a1ec64)
> [backport 3.3] memtx: raise an error when trying to use unsupported MVCC feature

- changelogs/unreleased/allow-bootstrap-in-ro-in-supervised-bs.md
- changelogs/unreleased/early-make-bootstrap-leader.md
- changelogs/unreleased/graceful-make-bootstrap-leader.md
- changelogs/unreleased/single-instance-in-supervised-bs.md
- src/box/alter.cc
- src/box/box.cc
- src/box/box.h
- src/box/lua/ctl.c
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/bootstrap_strategy_test.lua
This patchset contains a few tightly coupled features.
Now, it is allowed to call `box.ctl.make_bootstrap_leader()` before a first `box.cfg()` call to mark the instance as a bootstrap leader.
It works if `box.cfg({bootstrap_strategy = 'supervised'})` is set, ignored otherwise.
So, the following code is now possible:
```lua
box.ctl.make_bootstrap_leader()
box.cfg({
bootstrap_strategy = 'supervised',
})
```
In earlier Tarantool version a user has to call `box.cfg()` in a separate fiber first and then call `box.ctl.make_bootstrap_leader()`.
Also, earlier Tarantool versions do not allow to bootstrap a database using the `'supervised'` bootstrap strategy if there are no upstreams configured (empty `box.cfg.replication`). It means that there were no way to bootstrap the database without iproto …
> replication: add early and graceful make_bootstrap_leader()

- changelogs/unreleased/gh-11267-fix-session-use-after-free.md
- src/box/session.c
- test/app-luatest/lib/tx_user_fiber_pool.cc
- test/app-luatest/tx_user_fiber_pool_test.lua
If session is created on demand in fiber we delete it when fiber is stopped. But we do not clear session and credentials in fiber storage. It is not an issue for standalone fiber (outside of fiber pool) as fiber will be destroyed or recycled and will not have chance to execute any code before that. In case of fiber pool it become dangerous as fiber is reused. Fortunately we never hit this because we either reset session and credentials at start in code executed in fiber (like in iproto) or execute code that does not check access (like in vinyl).
Recently we add `tnt_tx_push()` to execute callback in TX. This time the issue is revealed.
Let's just clear session and credentials in fiber storage when fiber is stopped.
Closes #11267
> box: fix session use-after-free

- changelogs/unreleased/bootstrap-strategy-native.md
- src/box/lua/config/applier/box_cfg.lua
- test/config-luatest/native_bootstrap_strategy_test.lua
The new bootstrap strategy `native` is added here. It can be enabled using the `replication.bootstrap_strategy` option in the YAML configuration.
The new strategy acts more or less similar to the `auto` strategy, but relaxes its limitations (see details in #10857).
It is based on the `supervised` strategy and mainly performs two things:
* issues `box.ctl.make_bootstrap_leader({graceful = true})` to bootstrap a replicaset
* issues `box.ctl.make_bootstrap_leader()` to keep the bootstrap leader record pointing to the instance that is currently in the RW mode (to register new replicas)
The choice how to choose a bootstrap leader to initialize the replicaset depends on the `replication.failover` option. See details in #10857 or commit descriptions.
Fixes #10857
> replication.boostrap_strategy = native

- changelogs/unreleased/allow-guest-call-failover-execute.md
- src/box/lua/config/applier/runtime_priv.lua
- src/box/lua/config/descriptions.lua
This patch grants the guest user runtime privileges for running
`failover.execute` function. This is an internal function used by the
supervised failover coordinator. This privileges are needed for the
guest user to be able to perform the initial bootstrap since there is no
other users available before it.
Technically it's a part of a native and supervised bootstrap strategy
support allowing the external agent (i.e the supervised failover
coordinator) to perform the initial bootstrap.
Needed for tarantool/tarantool-ee#1194
> config: allow guest to perform `failover.execute`

- changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
- src/box/memtx_space.c
- test/box-luatest/memtx_mvcc_unsupported_features_test.lua
Memtx MVCC does not support multikey indexes, but allows to use them. If one will use them, Tarantool is most likely to crash, and that's the best scenario - otherwise Tarantool will work, but something terribly wrong will be happening under the hood. Let's simply forbid to create such indexes along with MVCC until we support them.
In addition to that, the commit forbids to create functional indexes along with memtx MVCC enabled since target Tarantool version for this commit does not support them completely.
Workaround for #6385
Workaround for #11099
NO_DOC=backport
(cherry picked from commit ae067afb6f45e65913c2996bdedb752d14a1ec64)
> [backport 2.11] memtx: raise an error when trying to use unsupported MVCC feature

- changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
- src/box/memtx_space.c
- test/box-luatest/gh_4348_transactional_ddl_test.lua
- test/box-luatest/memtx_mvcc_unsupported_features_test.lua
Memtx MVCC does not support multikey indexes, but allows to use them. If one will use them, Tarantool is most likely to crash, and that's the best scenario - otherwise Tarantool will work, but something terribly wrong will be happening under the hood. Let's simply forbid to create such indexes along with MVCC until we support them.
In addition to that, the commit forbids to create functional indexes along with memtx MVCC enabled since target Tarantool version for this commit does not support them completely.
Workaround for #6385
Workaround for #11099
NO_DOC=backport
(cherry picked from commit ae067afb6f45e65913c2996bdedb752d14a1ec64)
> [backport 3.2] memtx: raise an error when trying to use unsupported MVCC feature

- src/box/box.cc
- src/box/txn.c
- src/box/txn.h
*(This PR is a backport of #11295 to `release/2.11` to a future `2.11.7` release.)*
----
This patchset fixes a bug with `TXN_FORCE_ASYNC` transactions being lost after receiving a promote request from another instance and restarting the current instance.
Closes #11053
> [backport 2.11] box: set TXN_WAIT_SYNC with xrow rather than limbo state during recovery

- src/box/CMakeLists.txt
We can link extra libraries to core (see `EXTRA_CORE_LINK_LIBRARIES`). Let's also do it for box.
Will be used to link the Apache Arrow library to Tarantool EE.
> cmake: link extra libraries to box

- perf/lua/column_scan.lua
- perf/lua/column_scan_module.c
- test/fuzz/lua/test_engine.lua
It will be removed from Tarantool Enterprise Edition.
Needed for tarantool/tarantool-ee#1040
> test: drop `box_index_scanner()` usage from perf and fuzz tests

- test/unit/func_adapter_func.c
- test/unit/func_cache.c
When I use LTO and warning-as-an-error locally with GCC 13 I got the following build failure:
```c
In function ‘test_func_adapter_func_is_pinned’,
inlined from ‘test_main’ at <...>/test/unit/func_adapter_func.c:142:2,
inlined from ‘main’ at <...>/test/unit/func_adapter_func.c:163:11:
<...>/test/unit/func_adapter_func.c:124:17: error: ‘returned_pin_type’ may be used uninitialized [-Werror=maybe-uninitialized]
124 |                 is(returned_pin_type, pin_type,
|                 ^
<...>/test/unit/func_adapter_func.c: In function ‘main’:
<...>/test/unit/func_adapter_func.c:121:39: note: ‘returned_pin_type’ was declared here
121 |                 enum func_holder_type returned_pin_type;
|                                       ^
lto1: all warnings being treated as errors
```
The build …
> Fix FP compilation warning in func_adapter test

- changelogs/unreleased/gh-11171-fix-crash-on-oom-statement-rollback.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_engine.cc
- src/box/memtx_hash.cc
- src/box/memtx_tree.cc
- src/box/txn.c
- src/box/txn.h
- src/lib/core/errinj.h
- test/box-luatest/memtx_oom_test.lua
- test/box/errinj_index.result
- test/box/errinj_index.test.lua
- test/fuzz/lua/test_engine.lua
Currently during statement rollback we either assume that rollback does not fail or panic on failure. Unfortunately rollback can fail due to OOM because of opened read view and reservations done for rollback.
Let's handle this situation similar to transaction rollback in [1]. Let's set new transaction flag `TXN_STMT_ROLLBACK` before doing statement rollback and check it when we need to allocate memory in memtx arena. If flag is set and memory exhausted then allocate memory outside the arena.
Handle is added to `HASH` and `TREE `indexes. `RTREE` data structure does not handle OOM's yet, we have heuristic reservation in `RTREE `index. `BITSET` partially allocates memory using `realloc`.
To test the situation we can add something like `ERRINJ_INDEX_ALLOC_COUNTDOWN` injection to imitate …
> memtx: handle OOM on statement rollback

- doc/examples/config/config-storage/config.yaml
This patchset adjusts config storage configuration example to reflect recent Tarantool EE changes. See https://github.com/tarantool/tarantool-ee/issues/1227.
Also, it changes the `universe` permission to more granular ones, where we show all the config storage API functions.
> config-storage: reflect changed priv requirements

- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/engine.c
- src/box/engine.h
- src/box/quiver_engine.h
- src/trivia/config.h.cmake
The stub will be implemented in Tarantool Enterprise Edition.
Part of tarantool/tarantool-ee#1207
EE part: https://github.com/tarantool/tarantool-ee/pull/1234
> box: add quiver engine initialization stub

- changelogs/unreleased/gh-10159-11292-mvcc-bitwise-key-comparison.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_tx.c
- test/box-luatest/gh_10159_11292_mvcc_bitwise_key_comparison_test.lua
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
This patchset fixes the incorrect assumption that point hole equivalence classes are defined by
their keys' binary (MsgPack) representation.
Closes #10159
Closes #11292
> memtx: use index definition's `key_def` for point hole comparisons

- test/fuzz/luaL_loadbuffer/serializer.cc
This patch fixes the Lua inputs in `luaL_loadbuffer_fuzzer` that generate the infinite cycles or recursive function calls, like the following:
```lua
if counter_0 > 5 then break end
counter_0 = counter_0 + 1
and (0.000000 );
```
The `and` here is generated by the `NameToString()` function, which doesn't check that the name shouldn't be reserved.
This patch adds the corresponding check and separates the counter increment with `;` to avoid any ambiguous syntax.
NO_CHANGELOG=fuzzing
NO_DOC=fuzzing
> test/fuzz: fix possible timeout in result chunks

- src/box/lua/net_replicaset.lua
Remove vararg passed to `connect_by_cfg()`, because it accepts a single argument.
NO_TEST=codehealth
> box: fix a number of arguments

- changelogs/unreleased/gh-9937-commit-transaction-after-readonly.md
- src/box/blackhole.c
- src/box/box.cc
- src/box/engine.c
- src/box/engine.h
- src/box/memtx_engine.cc
- src/box/service_engine.c
- src/box/sysview.c
- src/box/txn.h
- src/box/vinyl.c
- src/box/vy_tx.c
- src/box/vy_tx.h
- test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua
- test/vinyl/misc.result
The `switch_to_ro` callback was first introduced in the `engine_vtab` as a solution to the issue in vinyl, where it was possible to commit a transaction after becoming read-only. Since mvcc was introduced in the memtx engine, a similar issue became possible. A possible solution in the memtx engine with implementing the `switch_to_ro` callback would just abort all writing transactions related to memtx, so cross-engine transactions would be aborted in vinyl and memtx, which doesn't introduce a bug but seems redundant. So now we just abort all writing transactions disregarding the engine which resulted in the `switch_to_ro` callback becoming useless. It is now impossible for a fiber to awake and commit after switching the node to read-only. Also more explicit error messages were implemented …
> engine: abort writing transactions after ro switch

- changelogs/unreleased/gh-8782-yaml-decode-char-code-fix.md
- test/app-luatest/gh_8782_yaml_decode_char_code_test.lua
This PR backprots 2 commits from the master.
---
libyaml: bump new version
* cmake: update the minimum required version
NO_DOC=build
NO_TEST=build
(cherry picked from commit ea1471b325ae63421fa43fb24a0c9e24f81dc56d)
---
yaml: fix decoding single-byte char codes >= 0x80
The bug was fixed in the libyaml repository. This commit just updates
the submodule and adds a test.
Closes #8782
NO_DOC=bug fix
(cherry picked from commit fa6b08a842a00e4f4bb350d0414e5a9c3e803b61)
---
> [backport release/2.11] libyaml: bump new version

- cmake/compiler.cmake
CMake 3.0 and above recognize that Apple Clang is a different compiler than upstream Clang. CMake 4.0 prefers to set the
`CMAKE_<LANG>_COMPILER_ID` variable to AppleClang instead of Clang. See [1] for details.
This patch adds the corresponding check to set `CMAKE_COMPILER_IS_CLANG` for the Apple Clang too.
[1]: https://cmake.org/cmake/help/v4.0/policy/CMP0025.html
NO_DOC=build
NO_TEST=build
> cmake: fix AppleClang detection

- changelogs/unreleased/gh-10159-11292-mvcc-bitwise-key-comparison.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_tx.c
- test/box-luatest/gh_10159_11292_mvcc_bitwise_key_comparison_test.lua
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
*(This PR is a backport of #11388 to `release/3.3` to a future `3.3.3` release.)*
----
This patchset fixes the incorrect assumption that point hole equivalence classes are defined by
their keys' binary (MsgPack) representation.
Closes #10159
Closes #11292
> [backport 3.3] memtx: use index definition's key_def for point hole comparisons

- src/lib/core/errinj.h
- src/trivia/config.h.cmake
To introduce a new error injection to the EE repository, one has to first add it to the CE repository and bump the CE submodule in EE. This is inconvenient. Let's move all EE error injections to extras and define them in the EE repository.
EE part: https://github.com/tarantool/tarantool-ee/pull/1264
> core: move EE error injections to extras

- changelogs/unreleased/gh-10159-11292-mvcc-bitwise-key-comparison.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_tx.c
- test/box-luatest/gh_10159_11292_mvcc_bitwise_key_comparison_test.lua
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
*(This PR is a backport of #11388 to `release/2.11` to a future `2.11.7` release.)*
----
This patchset fixes the incorrect assumption that point hole equivalence classes are defined by
their keys' binary (MsgPack) representation.
Closes #10159
Closes #11292
> [backport 2.11] memtx: use index definition's key_def for point hole comparisons

- test/unit/CMakeLists.txt
This patch is a follow-up to the commit
25af976f5279720079e00be390fb065d1ea5446d ("build: support cmake 4.0"). Since version 3.4, CMake doesn't add flags to export symbols from executables without the ENABLE_EXPORTS target property, see CMP0065 [1] for details.  Without this property, some unit C tests produce build warnings with LTO optimization enabled (for example, on Fedora 39):
NO_WRAP
```
[ 72%] Linking CXX executable luaT_tuple_new.test
In function ‘rmean_collect’,
inlined from ‘txn_complete_success’ at src/box/txn.c:836:2,
inlined from ‘txn_limbo_complete’ at src/box/txn_limbo.c:205:3:
src/lib/core/rmean.c:65:9: error: ‘__atomic_add_fetch_8’ writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
65 | …
```
> cmake: fix LTO build on Fedora

- src/box/memtx_engine.cc
- src/box/recovery.cc
- src/box/vy_log.c
- src/box/wal.c
- src/box/xlog.c
- src/box/xlog.h
- test/unit/xlog.c
To use xdir in EE, one has to add a new type to the CE repository, which is inconvenient. Let's refactor xdir so that one can specify an arbitrary type string and drop the xdir type enumeration.
Needed for https://github.com/tarantool/tarantool-ee/issues/1254
> xlog: drop xdir type

- src/box/lua/config/descriptions.lua
- src/box/lua/config/instance_config.lua
- test/config-luatest/cluster_config_schema_test.lua
This patch introduces a new `stateboard` configuration section. It's used for configuring a service reporting instance state to the configured remote key-value storage.
Part of tarantool/tarantool-ee#1229
Doc request tarantool/doc#5091
> config: add the `stateboard` section

- changelogs/unreleased/gh-10159-11292-mvcc-bitwise-key-comparison.md
- src/box/index.cc
- src/box/index.h
- src/box/memtx_tx.c
- test/box-luatest/gh_10159_11292_mvcc_bitwise_key_comparison_test.lua
- test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
*(This PR is a backport of #11388 to `release/3.2` to a future `3.2.2` release.)*
----
This patchset fixes the incorrect assumption that point hole equivalence classes are defined by
their keys' binary (MsgPack) representation.
Closes #10159
Closes #11292
> [backport 3.2] memtx: use index definition's key_def for point hole comparisons

- src/lib/tzcode/localtime.c
- test/unit/uuid.c
Build start to fail with my distro's new gcc version 15.1.1:
```
in file included from /home/shiny/dev/tarantool/src/lib/tzcode/localtime.c:18:
/home/shiny/dev/tarantool/src/lib/tzcode/tzfile.h:25:15: error: initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (2> 1 chars into 20 available) [-Werror=unterminated-string-initialization]
25 | #define TZDIR "/usr/share/zoneinfo" /* Time zone object file directory */
|               ^~~~~~~~~~~~~~~~~~~~~
/home/shiny/dev/tarantool/src/lib/tzcode/localtime.c:310:46: note: in expansion of macro ‘TZDIR’
310 | static char const tzdirslash[sizeof TZDIR] = TZDIR "/";
|
```
Fix by adding `__attribute((nonstring))__` where required.
> lib: fix build error with fresh gcc compiler

- .github/workflows/distrib.yml
This patch is a follow-up for the commit
d1574f794da59786daabb3a9a5d069d77c074fda ("ci: disable the reusable run for some workflows"). It has removed the inputs usage from the distrib.yml workflow (former packaging.yml), but didn't remove inputs declaration at the beginning like for other workflows. This patch drops unused inputs.
NO_DOC=CI
NO_TEST=CI
> ci: drop unused inputs for distrib workflow

- changelogs/unreleased/gh-9979-space-format-object.md
- changelogs/unreleased/gh-9979-tuple-format-validate.md
- src/box/alter.cc
- src/box/lua/space.cc
- src/box/lua/tuple_format.c
- src/box/lua/tuple_format.h
- src/box/space.c
- src/box/space.h
- test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua
- test/box-luatest/gh_9979_tuple_format_validate_test.lua
- test/box/net.box_reuse_tuple_formats_gh-6217.result
- test/box/net.box_reuse_tuple_formats_gh-6217.test.lua
- test/wal_off/alter.result
- test/wal_off/alter.test.lua
Added field `format_object` to spaces and method `validate` to `tuple.format`
The `format_object` field is not available for spaces accessed over net.box,
because creating it would trigger C-level validation of field types and collation 
IDs on the client. If the format references a field type unknown to the client or
a collation ID that isn’t present locally, an error will be raised during schema
installation.
The `format_object` field creates references to `tuple_format` for space objects
via `tuple_format_ref`. These references can be retained by spaces remaining in
memory (e.g., in the global space table), especially if other tests create spaces.
- In `gh_4693_formats_for_standalone_tuples_test`, added an initial call to
`collectgarbage()` to clear the tuple format pool before …
> feature: add validate method to space and tuple.format objects

- .github/workflows/config_jsonschema_check.yml
- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/perf_micro.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
There is no way to detect the revision of the Tarantool or Tarantool's workflow, which is called in the role of a reusable workflow, since all context is determined by the caller [1]. When a reusable workflow is called on the non-master Tarantool branch, it is desirable to check out Tarantool to the corresponding branch. For now this branch is hardcoded as master, and it is easy to forget to update the hardcoded value after creating a new branch for the Tarantool's release. OTOH, the caller should already update the target branch in its own workflow, so it is easier to maintain this logic in one place (the caller's workflow). Thus, this patch adds an additional optional parameter -- revision of the Tarantool to be checked out during the integration. It is set to 'master' by default to …
> ci: add Tarantool's revision in reusable workflows

- changelogs/unreleased/gh-10653-passwords-are-logged-in-clear-text.md
- src/box/lua/load_cfg.lua
- test/box-luatest/gh_10653_passwords_are_logged_in_clear_text_test.lua
Before this patch the password could leak into logs when user set
`listen` or `bootstrap_leader` option containing URI with user's
credentials.
Now, the `purge_password_from_uri` and the
`purge_password_from_listen_options_uri` are applied to appropriate cfg
options. These functions prevent password leaks. Also all possible
`listen` and `replication` options are handled: single string uri, comma
separated uris, table uris, multiple table uris and combined uris.
Closes https://github.com/tarantool/tarantool/issues/10653
NO_DOC=bugfix
> box: eliminate password leaks in logs

- src/box/lua/config/descriptions.lua
This patch adds `ro_reason` field to the `stateboard` configuration
section. The section describes the information reported by instances to
remote storage having a stateboard client configured. Reporting
`ro_reason` supplies `box.info.ro_reason` allowing one to understand
why the instance is RO. Adding this option to the list of the reported
has been suggested later that's why it's added separately.
It also adds two missing dots at the end of the elements list in the
description just for consistency.
Part of tarantool/tarantool-ee#1229
> config: add ro_reason to stateboard description

- .github/workflows/config_jsonschema_check.yml
- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/perf_micro.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
There is no way to detect the revision of the Tarantool or Tarantool's workflow, which is called in the role of a reusable workflow, since all context is determined by the caller [1]. When a reusable workflow is called on the non-master Tarantool branch, it is desirable to check out Tarantool to the corresponding branch. For now this branch is hardcoded as master, and it is easy to forget to update the hardcoded value after creating a new branch for the Tarantool's release. OTOH, the caller should already update the target branch in its own workflow, so it is easier to maintain this logic in one place (the caller's workflow). Thus, this patch adds an additional optional parameter -- revision of the Tarantool to be checked out during the integration. It is set to 'master' by default to …
> [backport: release/3.4] ci: add Tarantool's revision in reusable workflows

- .github/workflows/config_jsonschema_check.yml
- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/perf_micro.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
There is no way to detect the revision of the Tarantool or Tarantool's workflow, which is called in the role of a reusable workflow, since all context is determined by the caller [1]. When a reusable workflow is called on the non-master Tarantool branch, it is desirable to check out Tarantool to the corresponding branch. For now this branch is hardcoded as master, and it is easy to forget to update the hardcoded value after creating a new branch for the Tarantool's release. OTOH, the caller should already update the target branch in its own workflow, so it is easier to maintain this logic in one place (the caller's workflow). Thus, this patch adds an additional optional parameter -- revision of the Tarantool to be checked out during the integration. It is set to 'master' by default to …
> [backport: release/3.3] ci: add Tarantool's revision in reusable workflows

- .github/workflows/coverage.yml
- .github/workflows/debug.yml
- .github/workflows/debug_aarch64.yml
- .github/workflows/debug_asan_clang.yml
- .github/workflows/default_gcc_centos_7.yml
- .github/workflows/integration.yml
- .github/workflows/memtx_allocator_based_on_malloc.yml
- .github/workflows/out_of_source.yml
- .github/workflows/perf_micro.yml
- .github/workflows/release.yml
- .github/workflows/release_asan_clang.yml
- .github/workflows/release_clang.yml
- .github/workflows/release_lto.yml
- .github/workflows/release_lto_clang.yml
- .github/workflows/static_build.yml
- .github/workflows/static_build_cmake_linux.yml
There is no way to detect the revision of the Tarantool or Tarantool's workflow, which is called in the role of a reusable workflow, since all context is determined by the caller [1]. When a reusable workflow is called on the non-master Tarantool branch, it is desirable to check out Tarantool to the corresponding branch. For now this branch is hardcoded as master, and it is easy to forget to update the hardcoded value after creating a new branch for the Tarantool's release. OTOH, the caller should already update the target branch in its own workflow, so it is easier to maintain this logic in one place (the caller's workflow). Thus, this patch adds an additional optional parameter -- revision of the Tarantool to be checked out during the integration. It is set to 'master' by default to …
> [backport: release/3.2] ci: add Tarantool's revision in reusable workflows

- changelogs/unreleased/gh-10951-alter-pk-with-dependent-sk.md
- src/box/alter.cc
- test/box/tree_pk.result
- test/box/tree_pk.test.lua
- test/engine-luatest/gh_10951_memtx_alter_pk_with_dependent_sk_test.lua
Rebuild of several indexes in one statement is broken because we need to maintain consistency of built indexes while building the next ones, and we don't do that. Such rebuilds can happen only when primary index is altered and all non-unique and nullable indexes need to be rebuilt as well. Let's simply forbid such alters.
We could forbid any alter of primary index, and the patch would be even a bit simpler, but let's allow to alter primary in a space without dependent secondary indexes - it seems to work fine, and people would use it, at least someone reported this problem, hence, someone actually tried to alter primary.
Closes #10951
> box: disallow alter of primary index with dependent secondary

- test/box-luatest/gh_8204_fast_offset_test.lua
The test runs lots of read operations without yields, so default fiber slice is not enough. Let's simply set a huge one (30 seconds) by default to make the test stable even on very slow runners.
> test: increase fiber slice for fast offset test

- changelogs/unreleased/gh-11291-mutikey-index-alter.md
- src/box/tuple.h
- test/box-luatest/gh_11291_assert_after_mk_index_alter_test.lua
After a multikey index is altered or dropped, tuples that were inserted
while it existed stil reference the format with multikey parts. Actually,
that multikey format field shouldn't be used anymore because multikey
index is gone, but that's not true. It happens because format is arranged
to a JSON tree, and this tree has an interesting property. Imagine having
a field with path '[1][\*]' in the tree. Then, when looking for a field
'[1][1]' (or '[1]["abc"]', the second key can be anything), the field with
path '[1][\*]' will be returned since '\*' is actually wildcard. Hence,
even if the format is stale and there are no multikey fields in actual
format, we can obtain a multikey field even if we didn't search for it
and `multikey_idx` will be MULTIKEY_NONE in this case. Let's handle this …
> box: handle stale multikey tuple fields

- test/fuzz/lua/CMakeLists.txt
- test/fuzz/lua/test_mvcc.lua
The test for Tarantool allows you to generate random interleaved (concurrent) transactions for the memtx and vinyl engines, and verify the consistency of their execution w.r.t. serializability.
Bugs found by the test:
- #6206
- #6325
- #6452
- #7073
- #7113
- #7214
- #7217
- #7234
- #7235
- #7238
- #7239
- #7240
- #7343
- #7375
- #7409
- #7432
- #7449
- #7477
- #7478
- #7490
- #7493
- #7670
- #7685
- #7712
- #7755
- #7756
- #7757
- #7761
- #7828
- #7837
- #8104
- #11294
- #11354
Closes #5999
> test: add a MVCC fuzzing test

- changelogs/unreleased/gh-11490-expose-box-status.md
- extra/exports
- src/box/box.cc
- src/box/box.h
- test/box-luatest/gh_11490_expose_box_status_test.lua
Make `box_status` function result avialable in TX thread bypassing lua stack.
Fixes #11490
Title: `box_status` exposed in C API.
> box: expose box_status C API

- changelogs/unreleased/gh-10987-min-tarantool-version-for-roles.md
- src/box/lua/config/applier/app.lua
- src/box/lua/config/applier/roles.lua
- test/config-luatest/app_test.lua
- test/config-luatest/roles_test.lua
Closes #10987
Closes TNTP-1016
Title: `fail_if` tag for roles and scripts.
If the tag `fail_if` is set to an expression string role/script loading will raise an error, if fail_if expression is evaluated to be `true`.
The syntax for `fail_if` tag is the same as in config `conditional.if` section.
Example:
```lua
-- --- #tarantool.metadata.v1
-- fail_if: "tarantool_version < 3.1.0"
-- ...
```
> config: add `fail_if` tag for roles and scripts

- changelogs/unreleased/gh-10149-index-len-mvcc.md
- src/box/index.h
- src/box/memtx_bitset.cc
- src/box/memtx_hash.cc
- src/box/memtx_rtree.cc
- src/box/memtx_tree.cc
- src/box/memtx_tx.c
- src/box/memtx_tx.h
- test/box-luatest/gh_10149_index_len_mvcc_test.lua
- test/box-luatest/gh_8204_fast_offset_test.lua
Currently getting the index size (aka calling the index.len() method) is not recorded in the MVCC. This has a side effect that if the size if an index is changed after the transaction first inspected it, it's not conflicted and may continue performing writing operations on the space. That's a problem since in this case the transaction can perform a set of operations assuming that at the time it commits the size of the index is the same as been checked, which may not be true.
Let's fix this by informing the MVCC system about the index size check performed by a transaction.
Closes #10149
NO_DOC=buffix
> memtx: record getting the index size in the MVCC

- src/box/lua/xlog.c
- test/xlog/reader.result
- test/xlog/reader.test.lua
There's absolutely no point in that because the meta type doesn't affect the xlog format anyhow. This useless check complicates addition of new xlog meta types because we have to add each new meta type to the xlog reader Lua module so let's remove it.
> lua: don't check meta type in xlog reader

- src/box/lua/config/descriptions.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/load_cfg.lua
- test/box/box.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/instance_config_schema_test.lua
This commit adds the following configuration options:
```
* quiver.dir (box.cfg.quiver_dir)
* quiver.memory (box.cfg.quiver_memory)
* quiver.run_size (box.cfg.quiver_run_size)
```
They will be implemented in the EE repository.
Needed for tarantool/tarantool-ee#1258
Needed for tarantool/tarantool-ee#1259
Needed for tarantool/tarantool-ee#1260
EE PR that bumps the CE submodule: https://github.com/tarantool/tarantool-ee/pull/1313
> box: add configuration option for quiver storage engine

- src/box/read_view.c
- src/box/read_view.h
Added space `engine` field to space read view, so that we can expose its name in a public read view API method in Tarantool-EE.
Part of tarantool/tarantool-ee#1276
Required by Tarantool-EE PR [#1297](https://github.com/tarantool/tarantool-ee/pull/1297)
NO_TEST=field addition
> read view: add read view space engine field

- .gitignore
> gitignore: add generated TLA+ Makefile

- changelogs/unreleased/config-reload-by-signal.md
- src/box/lua/config/init.lua
- src/main.cc
- test/config-luatest/reload_test.lua
The idea is quite straightforward: once tarantool receives `SIGUSR2`, it reloads the YAML configuration. If the YAML configuration is not provided (the instance is started using the 2.x Lua script flow), it is no-op.
Consequent signals may be coalesced by the OS if they're sent fast enough. However, if tarantool is in processing of one reload triggered by a signal, the next signal is queued and a second reload happens after the first one.
The current implementation has a nuance: `config:reload()` called from Lua is not queued. If `SIGUSR2` arrives during `config:reload()`, a log warning issued and the second reload doesn't happen. Similarly, automatic reload from a remote configuration source (etcd/config storage) is not queued.
These nuances are *not* an API guarantee and I hope that …
> config: reload config by SIGUSR2

- changelogs/unreleased/gh-10592-replica-does-not-receive-its-own-rows.md
- changelogs/unreleased/gh-11156-fix-calculation-of-sync-quorum-in-config-and-supervised.md
- src/box/applier.cc
- src/box/box.cc
- src/box/box.h
- src/box/replication.cc
- src/box/replication.h
- test/replication-luatest/gh_10592_replica_does_not_receive_its_own_rows_test.lua
- test/replication-luatest/gh_11156_calculation_of_sync_quorum_in_config_and_supervised_test.lua
This is a backport of #11060 to `release/3.3` to a future `3.3.3` release.
> [backport 3.3] replication: fix several issues related to the 'orphan' status

- src/box/xrow_update_field.h
Without it, it's impossible to use functions defined there from a C++ source file.
> Add missing `extern "C"` to `xrow_update_field.h`

- changelogs/unreleased/gh-11531-crash-in-anon-subscribe-request-with-nil-id.md
- src/box/box.cc
- test/box-luatest/gh_10155_make_iproto_resistant_to_misusage_test.lua
- test/replication-luatest/gh_11531_crash_in_anonymous_subscribe_request_test.lua
- test/replication-luatest/persistent_gc_anon_test.lua
Before this patch a master node could crash when it processed an
anonymous iproto subscribe request which had a nil instance uuid.
The reason of this error is that in `box_connect_replica` we didn't
throw an error when non-exist replica tried to connect to node. It
led to a situation when the nullified replica object was tried to
dereferenced while iproto subscribe request. Now, we raise an
ER_NIL_UUID error if we get an iproto request with nil `instance_uuid`.
After this change `test_fetch_snapshot_no_uuid` and
`test_checkpoint_join` start fail. The reason of these failures is an
incorrect err.type and err.msg of iproto response when we try to send
an iproto request with nil `instance_uuid`. Now, these tests are fixed
by changing an err.type and err.msg to appropriate values.
Also we …
> box: fix crash while nil-uuid subscribe request

- changelogs/unreleased/gh-11531-crash-in-anon-subscribe-request-with-nil-id.md
- src/box/box.cc
- test/replication-luatest/gh_11531_crash_in_anonymous_subscribe_request_test.lua
(This PR is a backport of https://github.com/tarantool/tarantool/pull/11593 to release/3.2 to a future 3.2.2 release.)
Before this patch a master node could crash when it processed an anonymous iproto subscribe request which had a nil instance uuid. The reason of this error is that in `box_connect_replica` we didn't throw an error when non-exist replica tried to connect to node. It led to a situation when the nullified replica object was tried to dereferenced while iproto subscribe request. Now, we raise an ER_NIL_UUID error if we get an iproto request with nil `instance_uuid`.
After this change `test_fetch_snapshot_no_uuid` and `test_checkpoint_join` start fail. The reason of these failures is an incorrect err.type and err.msg of iproto response when we try to send an iproto request with …
> [backport 3.2] box: fix crash while nil-uuid subscribe request

- src/box/lua/schema.lua
Currently, we normalize option `covers` on each alter, even if it wasn't changed and this option is already normalized. Since normalization is not idempotent (it shifts all numeric fields from 1-indexation to 0-indexation), such alter can break `covers` option. Let's normalize `covers` only if it was updated.
Along the way, use `options` variable instead of `index_opts` to make `box.schema.index.alter` code more consistent.
Part of tarantool/tarantool-ee#1335
Covers was introduced in Tarantool 3.4.
EE part: https://github.com/tarantool/tarantool-ee/pull/1356
> box: do not normalize `covers` twice on index alter

- changelogs/unreleased/gh-11583-config-files-include.md
- src/box/lua/config/cluster_config.lua
- src/box/lua/config/descriptions.lua
- src/box/lua/config/instance_config.lua
- src/box/lua/config/source/file.lua
- src/box/lua/config/utils/file.lua
- test/config-luatest/cluster_config_schema_test.lua
- test/config-luatest/config_include_test.lua
Closes #11583
Closes TNTP-229
Title: config: `include` section for config files.
Using this section it is possible to include one or several other config
files from any config file. This is a top level field for file-based
configuration. If present, this field must be an array of strings.
Each entry in this array can be an absolute or relative path to a config
file to be included, or a wildcard pattern. Relative path are considered
relative to the file, where they are included.
Include section can be placed inside a `conditional` section.
The non-existing included files are skipped. If an included file exists
and is not a valid tarantool config file, an error will be raised.
Example config.yaml:
```yaml
include:
- config_a.yaml
- /etc/tarantool/config_b.yaml
- …
```
> config: add `include` field for config files

- perf/lua/column_scan_module.c
Recently, the Arrow stream API (available only in EE) was updated: now, enabling `force_view_types` in case it isn't supported raises an ER_UNSUPPORTED error. Let's fix the perf test to handle it gracefully instead of checking the schema.
Follow-up tarantool/tarantool-ee#1370
> perf: fix handling of unsupported `force_view_types` arrow options

- changelogs/unreleased/gh-11185-sysprof-crash.md
- changelogs/unreleased/gh-11229-sysprof-report.md
- changelogs/unreleased/gh-11278-luajit-fixes.md
* gdb: fix flake-7.2.0 F824 warning
* ci: use Tarantool revision in integration workflow
* ARM64: Fix IR_SLOAD assembly.
* ARM64: Fix code generation for IR_SLOAD with typecheck + conversion.
* sysprof: allow calling sysprof.report before stop
* build: provide LUAJIT_USE_PERFTOOLS option
* Fix JIT slot overflow during up-recursion.
* Rework stack overflow handling.
* ci: add track-fds Valgrind scenario
* Fix potential file descriptor leak in luaL_loadfile*().
* Fix another potential file descriptor leak in luaL_loadfile*().
* Handle partial snapshot restore due to stack overflow.
* Different fix for partial snapshot restore due to stack overflow.
* Avoid out-of-range PC for stack overflow error from snapshot restore.
* ARM64: Fix LDP code generation.
* ARM64: Fix assembly of HREFK.
* …
> [backport/release/3.4] luajit: bump new version

- changelogs/unreleased/gh-11526-misleading-admin-priv-revoke-error.md
- src/box/lua/schema.lua
- test/box-luatest/gh_11526_misleading_privilege_error_test.lua
Trying to revoke privileges from an admin user or a super role results in misleading errors:
```
error: 'Tuple field 5 (privilege) type does not match one required by operation:
expected unsigned, got integer'
```
The reason is that privileges use bit module for privilege grant/revoke, and this module operates 32-bit **signed** integers (see https://bitop.luajit.org/semantics.html#range for details). So any bit operation on a privilege set greater than 2^31 (for example, box.priv.ALL == 2^32 - 1) results in a negative number:
```lua
tarantool> bit.band(box.priv.ALL, bit.bnot(box.priv.W))
---
- -3
...
```
Fortunately, this can be fixed by casting one of the operands to a uint64_t type, so let's cast all granted or revoked privileges prior to calculating the resulting privilege set.
Closes …
> box: fix misleading errors on privilege revoke from admin

- src/lib/bit/NOTICE
- src/lib/bit/bit.c
- src/lib/bit/bit.h
- src/trivia/util.h
- test/unit/bit.c
- test/unit/bit.result
Add `bit_count_vec` function utilizing batching vectorized instructions on word aligned boundaries.
> lib bit: add `bit_count` implementation 

- changelogs/unreleased/gh-10057-box-schema-user-info.md
- src/box/sysview.c
- src/box/user.cc
- src/box/user.h
- test/box-luatest/gh_10057_user_role_test.lua
Prior to this patch it was not possible for a user to see any role in the `_vuser` space except the one created by him and the `public` one.
Let's also make it possible to see roles that he is granted with, so calls to the `box.schema.user.info()` functions won't fail if a user has a non-'public' role granted.
Closes #10057
NO_DOC=bugfix
> box: allow to access to the granted role in _vuser space

- changelogs/unreleased/connpool-reconnect-to-recent.md
- changelogs/unreleased/gh-10330-connpool-works-faster.md
- src/box/lua/connpool.lua
- test/config-luatest/rpc_test.lua
The main aim of the patchset is to make the connection pool methods
`connpool.call()` and `connpool.filter()` faster by making they behave as
follows when they need a connection to multiple instances.
* Run some of the mentioned connpool methods.
* Apply static configuration filters and find instance candidates.
* Check if there are "actual" connections to all of the candidates.
- Yes, there are "actual" connections to all of them (both active and broken).
In that case, try to use the active and available ones. If the
connection is not available, we may guarantee that it has been also
unavailable during past 3 seconds interval (hardcoded reconnect after interval). That
means there is no need to wait and try to reconnect to it.
- No, some instances have not been accessed yet or they have …
> connpool: make `filter()` and `call()` faster via advanced connection management

- changelogs/unreleased/gh-10360-fix-interval-decoding.md
- src/lib/core/datetime.h
- src/lib/core/mp_interval.c
- test/unit/interval.c
Currently we do not check if we have enough data to read when loading field key.
While at it also fix limits checking for `year`, `month`, `week` and `nanoseconds` fields we lost in the commit 01c7ae1128e1 ("msgpack: fix decoding intervals with int64").
Also as we check the upper limit for `ajust` field let's check the lower limit too.
Closes #10360
> core: fix interval MsgPack decoding

- changelogs/unreleased/gh-10361-box-zero-len-mp-decoding.md
- src/box/mp_tuple.c
- src/lib/core/decimal.c
- src/lib/core/mp_interval.c
- test/unit/decimal.c
- test/unit/interval.c
- test/unit/mp_tuple.c
Zero length data is possible input for MsgPack validation functions. So let's handle it for decimal, interval and tuple.
Closes #10361
> box: fix interval/decimal/tuple MsgPack decoding of zero length data

- test/fuzz/xrow_header_decode_fuzzer.c
The commit dc3fbcc64071 ("test/fuzz: add dummy mp_check_on_error in xrow fuzzer") broke fuzzing build. Let's add missing dependency on box_error library.
```
/src/tarantool/test/fuzz/xrow_header_decode_fuzzer.c:12:2: warning: call to undeclared function 'BuildClientError'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
12 |         diag_set(ClientError, ER_INVALID_MSGPACK, "dummy");
|         ^
/src/tarantool/src/lib/core/diag.h:477:2: note: expanded from macro 'diag_set'
477 |         diag_set_detailed(__FILE__, __LINE__, __VA_ARGS__)
|         ^
/src/tarantool/src/lib/core/diag.h:469:6: note: expanded from macro 'diag_set_detailed'
469 |         e = Build##class(file, line, ##__VA_ARGS__);                    \
|             ^
<scratch …
```
> test/fuzz: build fix

- changelogs/unreleased/gh-11221-pagination-key-corruption.md
- src/box/lua/schema.lua
- src/box/lua/tuple.lua
- test/engine-luatest/pagination_test.lua
Function `iterator_pos_set` works completely incorrectly when tuple
is passed to the option `after`.
Firstly, before extracting position, we call `ibuf:consume()` for
the memory allocated before position (this method is actaully ASAN
poisoning) - that's not correct since consumed memory contains query key
that will be used later. Let's remove this call.
Secondly, new allocation on ibuf can lead to its reallocation, so
pointers to old allocations can be invalidated. Let's set the pointers
to the key after all allocations are done, just like in `index:quantile()`.
What's about performance, `perf/lua/box_select.lua` shows no degradation.
Closes https://github.com/tarantool/tarantool/issues/11221
Closes https://github.com/tarantool/tarantool/issues/11648
> box: fix key corruption when pagination by tuple is used

- src/box/index_def.c
- src/box/index_def.h
- src/box/lua/schema.lua
- src/box/memtx_engine.cc
- src/box/memtx_engine.h
- src/box/memtx_space.c
- src/box/vinyl.c
- test/box-luatest/index_aggregates_test.lua
This is CE part of MemCS skip index patch. See commits for details.
Note that I didn't do refactoring of MemTX allocator (allocate blocks instead of tuples) because we definitely won't make it to the nearest release then. Let's do this refactoring in the future, after basic BRIN functionality is implemented.
EE part: https://github.com/tarantool/tarantool-ee/pull/1288.
> box: introduce aggregates

- asan/lsan.supp
Based on PR https://github.com/tarantool/tarantool/pull/11751 but with one suppression more.
EE pr with full-ci: https://github.com/tarantool/tarantool-ee/pull/1414
Leak sanitizer started detecting new leaks in etcd-client tests in the enterprise repo. This only happens on 3.2 branch, and must be due to the fact we haven't backported commits regarding correct Lua state cleanup on shutdown. Commit 80a11c49c35e ("box: close Lua state on exit") in particular.
Since that patch series is rather heavy, let's simply suppress the leak in 3.2 branch.
The leaks in question:
```
Direct leak of 52 byte(s) in 1 object(s) allocated from:
#0 0x556c873b3aae in malloc (/__w/tarantool-ee/tarantool-ee/tarantool/src/tarantool+0x1573aae) (BuildId: b2a73382837eb52617097838e12bd4d33ce21792)
#1 0x556c89ebd8ec in …
```
> [3.2] lsan: add more suppressions for reported leaks

- changelogs/unreleased/gh-10708-fix-setting-error-name.md
- doc/rfc/1148-stacked-diagnostics.md
- src/box/applier.cc
- src/box/errcode.h
- src/box/error.cc
- src/box/error.h
- src/box/index.cc
- src/box/index.h
- src/box/lua/error.cc
- src/box/memtx_engine.h
- src/box/recovery.cc
- src/box/user.cc
- src/lib/core/diag.h
- src/lib/core/exception.cc
- src/lib/core/exception.h
- test/app/fiber.result
- test/box-luatest/error_subsystem_improvements_test.lua
- test/box-luatest/index_aggregates_test.lua
- test/box-luatest/index_layout_test.lua
- test/box/error.result
- test/unit/error.c
- test/unit/mp_error.cc
Currently we fail to set box error name is some cases. Error name is error payload with key `name`.
Closes #10708
> box: fix setting box error name

- changelogs/unreleased/gh-11180-outdated-snapshot.md
- changelogs/unreleased/gh-11180-synchro-spurious-wakeup.md
- src/box/CMakeLists.txt
- src/box/applier.cc
- src/box/box.cc
- src/box/gc.c
- src/box/journal.c
- src/box/journal.h
- src/box/lua/ctl.c
- src/box/lua/info.c
- src/box/memtx_engine.cc
- src/box/txn.c
- src/box/txn.h
- src/box/txn_checkpoint.c
- src/box/txn_checkpoint.h
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- src/box/vinyl.c
- src/box/vy_tx.h
- src/box/wal.c
- src/box/wal.h
- test/box-luatest/gh_11180_wal_volatile_snapshot_test.lua
- test/replication-luatest/gh_11180_qsync_join_overfilled_limbo_test.lua
- test/replication-luatest/gh_11180_qsync_order_test.lua
- test/replication-luatest/gh_11180_qsync_volatile_snapshot_test.lua
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/unit/snap_quorum_delay.cc
The patchset fixes multiple bugs discovered in #11180 which could lead to crashes, undefined behaviour, and simply inconsistent data as locally on the master as between the master and replicas.
> Spurious Wakeupaloosa: spurious wakups and cascading rollbacks in the limbo and WAL

- changelogs/unreleased/gh-11180-outdated-snapshot.md
- src/box/CMakeLists.txt
- src/box/box.cc
- src/box/journal.c
- src/box/journal.h
- src/box/lua/ctl.c
- src/box/lua/info.c
- src/box/memtx_engine.cc
- src/box/txn.c
- src/box/txn_checkpoint.c
- src/box/txn_checkpoint.h
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- src/box/vinyl.c
- src/box/vy_tx.h
- src/box/wal.c
- src/box/wal.h
- test/box-luatest/gh_11180_wal_volatile_snapshot_test.lua
- test/replication-luatest/gh_6033_box_promote_demote_test.lua
- test/unit/snap_quorum_delay.cc
> [backport 3.2] Spurious Wakeupaloosa: spurious wakups and cascading rollbacks in the limbo and WAL

- changelogs/unreleased/gh-ee-1454-fix-fixed-decimal-validation.md
- src/box/field_def.c
- src/box/field_def.h
- src/box/key_def.c
- src/box/tuple_format.c
- test/box-luatest/fixed_point_decimal_test.lua
Currently if part of key or tuple field that corresponds to fixed point decimal type is MP_NIL we crash.
Closes tarantool/tarantool-ee#1454
> box: fix fixed point decimal validation of MP_NIL

- changelogs/unreleased/gh-10853-async-commit-async-tx-after-sync-tx-synchro-timeout-crash.md
- src/box/applier.cc
- src/box/box.cc
- src/box/relay.cc
- src/box/txn.c
- src/box/txn.h
- src/box/txn_checkpoint.c
- src/box/txn_limbo.c
- src/box/txn_limbo.h
- src/lib/core/errinj.h
- test/box-luatest/gh_10628_ack_limbo_owner_wal_writes_to_limbo_async_test.lua
- test/box-luatest/gh_10853_async_commit_async_tx_after_sync_tx_synchro_timeout_crash_test.lua
- test/replication-luatest/gh_10628_ack_limbo_owner_wal_writes_to_limbo_async_test.lua
- test/replication-luatest/gh_11790_qsync_confirmed_lsn_race_test.lua
- test/replication-luatest/gh_5295_split_brain_test.lua
#11790 + second part of #11180.
The patchset from #11180 couldn't be all applied right away, because the second half of it depends on the limbo having a worker fiber and doing confirmations asynchronously.
Coincidentally, this also led (seemingly) to #11790. On old versions (3.2 and older) the confirmation LSN was updated by the limbo before the WAL write. So after the WAL write it could happen that the "volatile" confirmed LSN has moved forward already, and the just written CONFIRM is already stale.
That case was just ignored previously, but this was blocking the second part of #11180 fixes.
The patchset entirely consists of some existing commits being cherry-picked from the master, but in a bit weird order. Since most of them were done long time ago and just were not considered as …
> Limbo confirmed LSN race

- src/box/memtx_space.c
- src/box/txn.c
- src/box/txn.h
Currently format of old tuple in `on_replace` trigger may be in new or old format during space upgrade depending on whether replace is done before or after upgrade cursor. Space upgrade is designed to be instant from user POV: it returns upgraded tuples in `space.get()` for example even if tuple is not upgraded internally. So to make the trigger consistent with overall design let's always return old tuple in new format.
The old tuple visible in trigger is set by `memtx_space_replace_tuple()` function. Instead of fixing it let's get rid of it for a few reasons:
- The interface is a bit odd. `old_tuple` is compressed and `new_tuple` is not. Also reference for `new_tuple` is taken by the function and is not for `old_tuple`.  
- With this function we do some a bit heavy actions twice. For …
>  box: fix old tuple format in on_replace trigger on space upgrade

- perf/lua/1mops_write.lua
Since the commit 4c8463cc498d ("core: bind to all addresses") we bind to all addresses so the test expectation that master is listen only on single address is broken. Let's fix it by taking the first address if there are many of them.
Closes #11843
> perf: fix 1mops replication

- changelogs/unreleased/gh-10595-config-expand_any.md
- src/box/lua/config/instance_config.lua
- src/box/lua/config/utils/schema.lua
- test/config-luatest/expand_any_test.lua
- test/config-luatest/schema_test.lua
Template variables (e.g. `{{ context.title }}`, `{{ instance_name }})` are now expanded inside `app.cfg.*` and `roles_cfg.*` (`any` type fields).
Closes #10595
> config: expand vars in `any` nodes

- changelogs/unreleased/gh-11848-box-replication-role-system.md
- src/box/lua/space.cc
- src/box/user_def.h
- test/box/access.result
- test/box/access.test.lua
The `replication` role (id = 3) was predefined but not included in the system users/roles definitions. As a result, it was not protected from being dropped or modified, unlike `guest`, `admin`, `public`, and `super`.
This patch adds `replication` to the list of system roles and extends `BOX_SYSTEM_USER_ID_MAX` accordingly, so that the role is treated consistently as a system entity.
Follow-up to #1205, #3084.
Closes #11848
NO_DOC=already in doc
> box: mark replication role as system

- changelogs/unreleased/gh-11807-linearization-txn-crash.md
- src/box/box.cc
- src/box/txn_limbo.c
- test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua
The DB state synchronization for a linearizable transaction is trying to wait for the receipt of all potentially confirmed synchro txns from a remote master, and then waits for their confirmation locally. Thus guaranteeing, that if any transaction was committed on the master before this point, then it is now visible on the current replica too.
Waiting for the synchro txns confirmation was done in a way that if the limbo isn't empty, then it 100% must contain a synchro txn in it.
But it is not always so. Sometimes it might contain a volatile async txn, which isn't written to WAL yet. Or it might even contain dummy entries created by the limbo flush operation (for a snapshot, for a new replica join). About these things the linearization sync must not care and should treat them like if the …
> limbo: fix a crash in linearization point waiting

- changelogs/unreleased/gh-11788-crash-in-bps_tree_memtx_tree_garbage_pop.md
- src/lib/salad/bps_tree.h
- test/unit/bps_tree.cc
The commit 51c56d9b3319 ("salad: reserve extents for matras_touch on BPS tree operations") already made the tree self-sufficient  - reserved blocks in garbage and extents for `matras_touch` calls prior to insertion and deletion. However, it didn't account for the addition of the first element to the tree, which creates the root leaf - this could also trigger `matras_touch` in `bps_tree_garbage_pop`.
However, it turns out there is no need to touch blocks before taking them out of the garbage. There is an invariant that blocks in the garbage are definitely not used by any read views. Although from the point of view of the matras, they require copying and could potentially have been needed by these read views. Let's just remove this `matras_touch` from `bps_tree_garbage_pop`. Also let's …
> salad: reserve block before bps_tree_insert_first_elem
